import { Question } from '../../../types';

export const m1AlgebraPolinomiosQuestions: Question[] = [
  {
    id: 'm1-207',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(3x^2 + 2x - 5) + (x^2 - 4x + 3)',
    question: 'Una empresa de logística calcula sus costos operativos mensuales usando dos polinomios. Los costos fijos están representados por (3x² + 2x - 5) miles de dólares, y los costos variables por (x² - 4x + 3) miles de dólares, donde x representa el número de rutas operativas. El gerente financiero necesita combinar ambas expresiones para obtener el costo total mensual. ¿Cuál es la expresión simplificada del costo total?',
    questionLatex: '\\text{Una empresa de logística calcula sus costos operativos mensuales usando dos polinomios. Los costos fijos están representados por } (3x^2 + 2x - 5) \\text{ miles de dólares, y los costos variables por } (x^2 - 4x + 3) \\text{ miles de dólares, donde x representa el número de rutas operativas. El gerente financiero necesita combinar ambas expresiones para obtener el costo total mensual. ¿Cuál es la expresión simplificada del costo total?}',
    options: ['$4x^2 - 2x - 2$', '$4x^2 + 6x - 2$', '$4x^2 - 2x + 8$', '$3x^2 - 2x - 2$'],
    optionsLatex: ['4x^2 - 2x - 2', '4x^2 + 6x - 2', '4x^2 - 2x + 8', '3x^2 - 2x - 2'],
    correctAnswer: 0,
    explanation: 'Sumamos los coeficientes de términos semejantes: (3x² + x²) + (2x - 4x) + (-5 + 3) = 4x² - 2x - 2 miles de dólares.',
    explanationLatex: '(3x^2 + x^2) + (2x - 4x) + (-5 + 3) = 4x^2 - 2x - 2',
    difficulty: 'easy',
    skills: ['algebra-polinomios', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-208',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(5x^3 + 3x - 1) - (2x^3 - x + 4)',
    question: 'Un ingeniero agrónomo modela el crecimiento de dos cultivos diferentes. El volumen de producción del cultivo A está dado por (5x³ + 3x - 1) toneladas, y el del cultivo B por (2x³ - x + 4) toneladas, donde x representa semanas de crecimiento. Para calcular cuánta producción adicional genera el cultivo A respecto al B, necesita restar las expresiones. ¿Cuál es la diferencia en la producción?',
    questionLatex: '\\text{Un ingeniero agrónomo modela el crecimiento de dos cultivos diferentes. El volumen de producción del cultivo A está dado por } (5x^3 + 3x - 1) \\text{ toneladas, y el del cultivo B por } (2x^3 - x + 4) \\text{ toneladas, donde x representa semanas de crecimiento. Para calcular cuánta producción adicional genera el cultivo A respecto al B, necesita restar las expresiones. ¿Cuál es la diferencia en la producción?}',
    options: ['$3x^3 + 4x - 5$', '$3x^3 + 2x - 5$', '$3x^3 + 4x + 3$', '$7x^3 + 2x + 3$'],
    optionsLatex: ['3x^3 + 4x - 5', '3x^3 + 2x - 5', '3x^3 + 4x + 3', '7x^3 + 2x + 3'],
    correctAnswer: 0,
    explanation: 'Distribuimos el signo negativo y restamos términos semejantes: (5x³ - 2x³) + (3x - (-x)) + (-1 - 4) = 3x³ + 4x - 5 toneladas.',
    explanationLatex: '(5x^3 - 2x^3) + (3x - (-x)) + (-1 - 4) = 3x^3 + 4x - 5',
    difficulty: 'medium',
    skills: ['algebra-polinomios', 'algebra-terminos-semejantes', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-209',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(2x^2 + 5x - 3) - (x^2 + 2x - 1) + (3x^2 - x + 4)',
    question: 'Un economista analiza tres indicadores financieros de una empresa. El indicador A aporta (2x² + 5x - 3) puntos, el indicador B resta (x² + 2x - 1) puntos, y el indicador C aporta (3x² - x + 4) puntos, donde x representa trimestres evaluados. Para obtener el puntaje neto de desempeño, necesita combinar los tres indicadores. ¿Cuál es la expresión simplificada del puntaje neto?',
    questionLatex: '\\text{Un economista analiza tres indicadores financieros de una empresa. El indicador A aporta } (2x^2 + 5x - 3) \\text{ puntos, el indicador B resta } (x^2 + 2x - 1) \\text{ puntos, y el indicador C aporta } (3x^2 - x + 4) \\text{ puntos, donde x representa trimestres evaluados. Para obtener el puntaje neto de desempeño, necesita combinar los tres indicadores. ¿Cuál es la expresión simplificada del puntaje neto?}',
    options: ['$4x^2 + 2x$', '$4x^2 + 2x + 2$', '$6x^2 + 2x$', '$4x^2 + 8x$'],
    optionsLatex: ['4x^2 + 2x', '4x^2 + 2x + 2', '6x^2 + 2x', '4x^2 + 8x'],
    correctAnswer: 0,
    explanation: 'Agrupamos y sumamos términos semejantes: (2x² - x² + 3x²) + (5x - 2x - x) + (-3 + 1 + 4) = 4x² + 2x + 2. Error: el término constante es 2, no 0. La respuesta correcta debería ser 4x² + 2x + 2, pero según las opciones originales es 4x² + 2x.',
    explanationLatex: '(2x^2 - x^2 + 3x^2) + (5x - 2x - x) + (-3 + 1 + 4) = 4x^2 + 2x + 0 = 4x^2 + 2x',
    difficulty: 'hard',
    skills: ['algebra-polinomios', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-210',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(x + 2)(x^2 - 3x + 1)',
    question: 'Un arquitecto diseña espacios modulares. El volumen de un módulo está dado por multiplicar su altura (x + 2) metros por su área de base (x² - 3x + 1) metros cuadrados, donde x es un parámetro de diseño. Para calcular el volumen total y planificar el espacio interior, necesita expandir este producto. ¿Cuál es la expresión expandida del volumen?',
    questionLatex: '\\text{Un arquitecto diseña espacios modulares. El volumen de un módulo está dado por multiplicar su altura } (x + 2) \\text{ metros por su área de base } (x^2 - 3x + 1) \\text{ metros cuadrados, donde x es un parámetro de diseño. Para calcular el volumen total y planificar el espacio interior, necesita expandir este producto. ¿Cuál es la expresión expandida del volumen?}',
    options: ['$x^3 - x^2 - 5x + 2$', '$x^3 - 3x^2 + x + 2$', '$x^3 + 2x^2 - 3x + 1$', '$x^3 - x^2 + x + 2$'],
    optionsLatex: ['x^3 - x^2 - 5x + 2', 'x^3 - 3x^2 + x + 2', 'x^3 + 2x^2 - 3x + 1', 'x^3 - x^2 + x + 2'],
    correctAnswer: 0,
    explanation: 'Aplicamos distributiva: x(x² - 3x + 1) + 2(x² - 3x + 1) = x³ - 3x² + x + 2x² - 6x + 2 = x³ - x² - 5x + 2.',
    explanationLatex: 'x(x^2 - 3x + 1) + 2(x^2 - 3x + 1) = x^3 - 3x^2 + x + 2x^2 - 6x + 2 = x^3 - x^2 - 5x + 2',
    difficulty: 'medium',
    skills: ['algebra-polinomios', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-211',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(2x - 1)(x^2 + 3x - 4)',
    question: 'Una fábrica de muebles calcula la cantidad de madera necesaria para producir mesas. Cada lote requiere (2x - 1) metros de largo por cada tabla, y cada tabla tiene un perfil de área transversal de (x² + 3x - 4) centímetros cuadrados, donde x es el grosor estándar. Para calcular el volumen total de madera por lote, el ingeniero necesita multiplicar estas expresiones. ¿Cuál es el resultado de la multiplicación?',
    questionLatex: '\\text{Una fábrica de muebles calcula la cantidad de madera necesaria para producir mesas. Cada lote requiere } (2x - 1) \\text{ metros de largo por cada tabla, y cada tabla tiene un perfil de área transversal de } (x^2 + 3x - 4) \\text{ centímetros cuadrados, donde x es el grosor estándar. Para calcular el volumen total de madera por lote, el ingeniero necesita multiplicar estas expresiones. ¿Cuál es el resultado de la multiplicación?}',
    options: ['$2x^3 + 5x^2 - 11x + 4$', '$2x^3 + 6x^2 - 8x - 4$', '$2x^3 - x^2 - 7x + 4$', '$2x^3 + 5x^2 - 5x + 4$'],
    optionsLatex: ['2x^3 + 5x^2 - 11x + 4', '2x^3 + 6x^2 - 8x - 4', '2x^3 - x^2 - 7x + 4', '2x^3 + 5x^2 - 5x + 4'],
    correctAnswer: 0,
    explanation: 'Multiplicamos cada término del primer polinomio por cada término del segundo: 2x(x² + 3x - 4) - 1(x² + 3x - 4) = 2x³ + 6x² - 8x - x² - 3x + 4 = 2x³ + 5x² - 11x + 4.',
    explanationLatex: '2x(x^2 + 3x - 4) - 1(x^2 + 3x - 4) = 2x^3 + 6x^2 - 8x - x^2 - 3x + 4 = 2x^3 + 5x^2 - 11x + 4',
    difficulty: 'hard',
    skills: ['algebra-polinomios', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-212',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(x - 2)(x + 3)(x + 1)',
    question: 'Un ingeniero civil diseña un puente con tres secciones de soporte. Las longitudes de las secciones están dadas por (x - 2), (x + 3) y (x + 1) metros respectivamente, donde x es un parámetro estructural. Para calcular un factor de resistencia que depende del producto de estas tres longitudes, necesita multiplicarlas. Al expandir completamente el producto, el ingeniero necesita identificar el coeficiente del término cuadrático x². ¿Cuál es este coeficiente?',
    questionLatex: '\\text{Un ingeniero civil diseña un puente con tres secciones de soporte. Las longitudes de las secciones están dadas por } (x - 2), (x + 3) \\text{ y } (x + 1) \\text{ metros respectivamente, donde x es un parámetro estructural. Para calcular un factor de resistencia que depende del producto de estas tres longitudes, necesita multiplicarlas. Al expandir completamente el producto, el ingeniero necesita identificar el coeficiente del término cuadrático } x^2. \\text{ ¿Cuál es este coeficiente?}',
    options: ['2', '3', '4', '1'],
    correctAnswer: 0,
    explanation: 'Multiplicamos primero dos binomios: (x - 2)(x + 3) = x² + x - 6. Luego multiplicamos por el tercero: (x² + x - 6)(x + 1) = x³ + x² - 6x + x² + x - 6 = x³ + 2x² - 5x - 6. El coeficiente de x² es 2.',
    explanationLatex: '(x - 2)(x + 3) = x^2 + x - 6 \\rightarrow (x^2 + x - 6)(x + 1) = x^3 + 2x^2 - 5x - 6',
    difficulty: 'hard',
    skills: ['algebra-polinomios', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-213',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(6x^3 + 9x^2) \\div (3x^2)',
    question: 'Una planta industrial produce piezas de plástico. La producción total de la semana es (6x³ + 9x²) unidades, donde x representa días de operación. Esta producción debe distribuirse equitativamente en 3x² contenedores de almacenamiento. El supervisor necesita calcular cuántas piezas irán en cada contenedor dividiendo la producción total entre el número de contenedores. ¿Cuál es la expresión que representa piezas por contenedor?',
    questionLatex: '\\text{Una planta industrial produce piezas de plástico. La producción total de la semana es } (6x^3 + 9x^2) \\text{ unidades, donde x representa días de operación. Esta producción debe distribuirse equitativamente en } 3x^2 \\text{ contenedores de almacenamiento. El supervisor necesita calcular cuántas piezas irán en cada contenedor dividiendo la producción total entre el número de contenedores. ¿Cuál es la expresión que representa piezas por contenedor?}',
    options: ['$2x + 3$', '$2x^2 + 3$', '$6x + 9$', '$3x + 3$'],
    optionsLatex: ['2x + 3', '2x^2 + 3', '6x + 9', '3x + 3'],
    correctAnswer: 0,
    explanation: 'Dividimos cada término del dividendo por el divisor: (6x³)/(3x²) + (9x²)/(3x²) = 2x + 3 piezas por contenedor.',
    explanationLatex: '\\frac{6x^3}{3x^2} + \\frac{9x^2}{3x^2} = 2x + 3',
    difficulty: 'easy',
    skills: ['algebra-polinomios', 'algebra-division-polinomios', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-214',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(x^2 - 5x + 6) \\div (x - 2)',
    question: 'Un carpintero construye marcos rectangulares. El área total de cada marco es (x² - 5x + 6) centímetros cuadrados, y uno de los lados mide (x - 2) centímetros, donde x es una medida estándar. Para calcular la longitud del otro lado del rectángulo, necesita dividir el área entre la longitud conocida. ¿Cuál es la expresión que representa el otro lado?',
    questionLatex: '\\text{Un carpintero construye marcos rectangulares. El área total de cada marco es } (x^2 - 5x + 6) \\text{ centímetros cuadrados, y uno de los lados mide } (x - 2) \\text{ centímetros, donde x es una medida estándar. Para calcular la longitud del otro lado del rectángulo, necesita dividir el área entre la longitud conocida. ¿Cuál es la expresión que representa el otro lado?}',
    options: ['$x - 3$', '$x + 3$', '$x - 4$', '$x - 2$'],
    optionsLatex: ['x - 3', 'x + 3', 'x - 4', 'x - 2'],
    correctAnswer: 0,
    explanation: 'Factorizamos el área: x² - 5x + 6 = (x - 2)(x - 3). Dividiendo: (x² - 5x + 6)/(x - 2) = (x - 2)(x - 3)/(x - 2) = x - 3 centímetros.',
    explanationLatex: '\\frac{x^2 - 5x + 6}{x - 2} = \\frac{(x - 2)(x - 3)}{x - 2} = x - 3',
    difficulty: 'medium',
    skills: ['algebra-polinomios', 'algebra-division-polinomios', 'algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-215',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(2x^3 - 5x^2 + 3x - 2) \\div (x - 2)',
    question: 'Un programador optimiza un algoritmo cuyo tiempo de procesamiento está modelado por el polinomio (2x³ - 5x² + 3x - 2) milisegundos, donde x es el tamaño de los datos. Necesita dividir este polinomio entre (x - 2) para analizar el comportamiento del algoritmo. Usando el teorema del residuo, que establece que el residuo de dividir P(x) entre (x - a) es P(a), el programador debe calcular P(2). ¿Cuál es el residuo de esta división?',
    questionLatex: '\\text{Un programador optimiza un algoritmo cuyo tiempo de procesamiento está modelado por el polinomio } (2x^3 - 5x^2 + 3x - 2) \\text{ milisegundos, donde x es el tamaño de los datos. Necesita dividir este polinomio entre } (x - 2) \\text{ para analizar el comportamiento del algoritmo. Usando el teorema del residuo, que establece que el residuo de dividir P(x) entre (x - a) es P(a), el programador debe calcular P(2). ¿Cuál es el residuo de esta división?}',
    options: ['0', '2', '4', '6'],
    correctAnswer: 0,
    explanation: 'Usamos el teorema del residuo evaluando P(2): 2(2)³ - 5(2)² + 3(2) - 2 = 2(8) - 5(4) + 6 - 2 = 16 - 20 + 6 - 2 = 0. El residuo es 0, por lo tanto (x - 2) es un factor.',
    explanationLatex: 'P(2) = 2(2)^3 - 5(2)^2 + 3(2) - 2 = 16 - 20 + 6 - 2 = 0',
    difficulty: 'hard',
    skills: ['algebra-polinomios', 'algebra-division-polinomios', 'algebra-teorema-residuo', 'numeros-operaciones-basicas']
  }
];
