import { Question } from '../../../types';

export const m2AlgebraExpresionesAlgebraicasQuestions: Question[] = [
  {
    id: 'm2-alg-expr-1',
    level: 'M2',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    questionLatex: '\\text{Simplifica la expresión: } (2x^2 - 3x + 1) - (x^2 + 2x - 4)',
    options: ['$x^2 - 5x + 5$', '$x^2 - x - 3$', '$3x^2 - x - 3$', '$x^2 + x + 5$'],
    optionsLatex: ['x^2 - 5x + 5', 'x^2 - x - 3', '3x^2 - x - 3', 'x^2 + x + 5'],
    correctAnswer: 0,
    explanation: 'Distribuimos el negativo y combinamos términos semejantes:',
    explanationLatex: '2x^2 - 3x + 1 - x^2 - 2x + 4 = x^2 - 5x + 5',
    difficulty: 'medium',
    skills: ['algebra-expresiones-algebraicas', 'algebra-terminos-semejantes', 'algebra-distributiva', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-alg-expr-2',
    level: 'M2',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    questionLatex: '\\text{Factoriza completamente: } 4x^2 - 9y^2',
    options: ['$(2x - 3y)(2x + 3y)$', '$(4x - 9y)(x + y)$', '$(2x - 3y)^2$', '$(x - y)(4x + 9y)$'],
    optionsLatex: ['(2x - 3y)(2x + 3y)', '(4x - 9y)(x + y)', '(2x - 3y)^2', '(x - y)(4x + 9y)'],
    correctAnswer: 0,
    explanation: 'Es una diferencia de cuadrados perfectos: a² - b² = (a-b)(a+b)',
    explanationLatex: '4x^2 - 9y^2 = (2x)^2 - (3y)^2 = (2x - 3y)(2x + 3y)',
    difficulty: 'hard',
    skills: ['algebra-factorizacion', 'algebra-diferencia-cuadrados', 'algebra-productos-notables', 'algebra-expresiones-algebraicas']
  },
  {
    id: 'm2-alg-expr-3',
    level: 'M2',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    questionLatex: '\\text{Simplifica: } \\frac{x^2 - 4}{x^2 + 4x + 4}',
    options: ['$\\frac{x - 2}{x + 2}$', '$\\frac{x + 2}{x - 2}$', '$\\frac{x - 2}{x}$', '$\\frac{1}{x + 2}$'],
    optionsLatex: ['\\frac{x - 2}{x + 2}', '\\frac{x + 2}{x - 2}', '\\frac{x - 2}{x}', '\\frac{1}{x + 2}'],
    correctAnswer: 0,
    explanation: 'Factorizamos numerador y denominador:',
    explanationLatex: '\\frac{(x-2)(x+2)}{(x+2)^2} = \\frac{x-2}{x+2}',
    difficulty: 'hard',
    skills: ['algebra-fracciones-algebraicas', 'algebra-factorizacion', 'algebra-simplificacion', 'algebra-productos-notables']
  },
  {
    id: 'm2-alg-expr-4',
    level: 'M2',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    questionLatex: '\\text{Simplifica: } \\frac{1}{x-1} - \\frac{2}{x^2-1} + \\frac{1}{x+1}',
    options: ['$\\frac{2x}{x^2-1}$', '$\\frac{x}{x^2-1}$', '$\\frac{2}{x-1}$', '$\\frac{1}{x-1}$'],
    optionsLatex: ['\\frac{2x}{x^2-1}', '\\frac{x}{x^2-1}', '\\frac{2}{x-1}', '\\frac{1}{x-1}'],
    correctAnswer: 0,
    explanation: 'Factorizamos x²-1 = (x-1)(x+1) y encontramos común denominador:',
    explanationLatex: '\\frac{x+1}{x^2-1} - \\frac{2}{x^2-1} + \\frac{x-1}{x^2-1} = \\frac{x+1-2+x-1}{x^2-1} = \\frac{2x}{x^2-1}',
    difficulty: 'extreme',
    skills: ['algebra-fracciones-algebraicas', 'algebra-factorizacion', 'algebra-simplificacion', 'algebra-comun-denominador', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-alg-expr-5',
    level: 'M2',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    questionLatex: '\\text{Expande y simplifica: } (2x + 3)^2 - (x - 1)^2',
    options: ['$3x^2 + 14x + 8$', '$3x^2 + 10x + 10$', '$4x^2 + 14x + 8$', '$3x^2 + 8x + 10$'],
    optionsLatex: ['3x^2 + 14x + 8', '3x^2 + 10x + 10', '4x^2 + 14x + 8', '3x^2 + 8x + 10'],
    correctAnswer: 0,
    explanation: 'Expandimos ambos cuadrados:',
    explanationLatex: '(4x^2 + 12x + 9) - (x^2 - 2x + 1) = 4x^2 + 12x + 9 - x^2 + 2x - 1 = 3x^2 + 14x + 8',
    difficulty: 'hard',
    skills: ['algebra-productos-notables', 'algebra-cuadrado-binomio', 'algebra-terminos-semejantes', 'algebra-expresiones-algebraicas', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-alg-expr-6',
    level: 'M2',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    questionLatex: '\\text{Factoriza: } x^3 - 8',
    options: ['$(x - 2)(x^2 + 2x + 4)$', '$(x - 2)(x^2 - 2x + 4)$', '$(x + 2)(x^2 - 2x + 4)$', '$(x - 2)^3$'],
    optionsLatex: ['(x - 2)(x^2 + 2x + 4)', '(x - 2)(x^2 - 2x + 4)', '(x + 2)(x^2 - 2x + 4)', '(x - 2)^3'],
    correctAnswer: 0,
    explanation: 'Es una diferencia de cubos: a³ - b³ = (a - b)(a² + ab + b²)',
    explanationLatex: 'x^3 - 8 = x^3 - 2^3 = (x - 2)(x^2 + 2x + 4)',
    difficulty: 'hard',
    skills: ['algebra-factorizacion', 'algebra-diferencia-cubos', 'algebra-productos-notables', 'algebra-expresiones-algebraicas']
  },
  {
    id: 'm2-alg-expr-7',
    level: 'M2',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    questionLatex: '\\text{Simplifica: } \\frac{x^3 - x}{x^2 + 2x + 1}',
    options: ['$\\frac{x(x-1)}{x+1}$', '$\\frac{x(x+1)}{x-1}$', '$\\frac{x^2-1}{x+1}$', '$\\frac{x(x-1)(x+1)}{(x+1)^2}$'],
    optionsLatex: ['\\frac{x(x-1)}{x+1}', '\\frac{x(x+1)}{x-1}', '\\frac{x^2-1}{x+1}', '\\frac{x(x-1)(x+1)}{(x+1)^2}'],
    correctAnswer: 3,
    explanation: 'Factorizamos numerador y denominador:',
    explanationLatex: '\\frac{x(x^2-1)}{(x+1)^2} = \\frac{x(x-1)(x+1)}{(x+1)^2}',
    difficulty: 'extreme',
    skills: ['algebra-fracciones-algebraicas', 'algebra-factorizacion', 'algebra-simplificacion', 'algebra-productos-notables']
  }
];
