import { Question } from '../../../types';

export const m1AlgebraEcuacionesInecuacionesQuestions: Question[] = [
  {
    id: 'm1-5',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver la ecuación: $2x - 5 = 11$',
    questionLatex: '\\text{Resolver la ecuación: } 2x - 5 = 11',
    options: ['$x = 6$', '$x = 7$', '$x = 8$', '$x = 9$'],
    optionsLatex: ['x = 6', 'x = 7', 'x = 8', 'x = 9'],
    correctAnswer: 2,
    explanation: 'Despejamos $x$:',
    explanationLatex: '2x - 5 = 11 \\rightarrow 2x = 16 \\rightarrow x = 8',
    difficulty: 'easy',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-16',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver la desigualdad: $2x + 3 > 7$',
    questionLatex: '\\text{Resolver la desigualdad: } 2x + 3 > 7',
    options: ['$x > 2$', '$x < 2$', '$x > 5$', '$x < 5$'],
    optionsLatex: ['x > 2', 'x < 2', 'x > 5', 'x < 5'],
    correctAnswer: 0,
    explanation: 'Despejamos $x$ igual que en una ecuación:',
    explanationLatex: '2x + 3 > 7 \\rightarrow 2x > 4 \\rightarrow x > 2',
    difficulty: 'medium',
    skills: ['algebra-desigualdades', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-30',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $x + 5 = 12$, ¿cuál es el valor de $2x$?',
    questionLatex: '\\text{Si } x + 5 = 12 \\text{, ¿cuál es el valor de } 2x?',
    options: ['7', '10', '14', '17'],
    correctAnswer: 2,
    explanation: 'Primero encontramos x, luego calculamos 2x:',
    explanationLatex: 'x + 5 = 12 \\rightarrow x = 7 \\quad \\Rightarrow \\quad 2x = 2(7) = 14',
    difficulty: 'easy',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-33',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\frac{x}{3} + 2 = 5$',
    questionLatex: '\\text{Resolver: } \\frac{x}{3} + 2 = 5',
    options: ['$x = 3$', '$x = 6$', '$x = 9$', '$x = 12$'],
    optionsLatex: ['x = 3', 'x = 6', 'x = 9', 'x = 12'],
    correctAnswer: 2,
    explanation: 'Despejamos x:',
    explanationLatex: '\\frac{x}{3} + 2 = 5 \\rightarrow \\frac{x}{3} = 3 \\rightarrow x = 9',
    difficulty: 'easy',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-141',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\frac{x}{2} + \\frac{x}{3} = 10$',
    questionLatex: '\\text{Resolver: } \\frac{x}{2} + \\frac{x}{3} = 10',
    options: ['$x = 6$', '$x = 12$', '$x = 15$', '$x = 20$'],
    optionsLatex: ['x = 6', 'x = 12', 'x = 15', 'x = 20'],
    correctAnswer: 1,
    explanation: 'Encontramos común denominador y despejamos:',
    explanationLatex: '\\frac{x}{2} + \\frac{x}{3} = 10 \\rightarrow \\frac{3x + 2x}{6} = 10 \\rightarrow \\frac{5x}{6} = 10 \\rightarrow x = 12',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-fracciones', 'numeros-fracciones-comun-denominador', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-142',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\frac{2x - 1}{3} = 5$',
    questionLatex: '\\text{Resolver: } \\frac{2x - 1}{3} = 5',
    options: ['$x = 7$', '$x = 8$', '$x = 9$', '$x = 10$'],
    optionsLatex: ['x = 7', 'x = 8', 'x = 9', 'x = 10'],
    correctAnswer: 1,
    explanation: 'Multiplicamos ambos lados por 3 y despejamos:',
    explanationLatex: '\\frac{2x - 1}{3} = 5 \\rightarrow 2x - 1 = 15 \\rightarrow 2x = 16 \\rightarrow x = 8',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-143',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\frac{x + 2}{4} - \\frac{x - 1}{2} = 1$',
    questionLatex: '\\text{Resolver: } \\frac{x + 2}{4} - \\frac{x - 1}{2} = 1',
    options: ['$x = -4$', '$x = -6$', '$x = 4$', '$x = 6$'],
    optionsLatex: ['x = -4', 'x = -6', 'x = 4', 'x = 6'],
    correctAnswer: 1,
    explanation: 'Usamos común denominador 4 y resolvemos:',
    explanationLatex: '\\frac{x + 2}{4} - \\frac{2(x - 1)}{4} = 1 \\rightarrow \\frac{x + 2 - 2x + 2}{4} = 1 \\rightarrow \\frac{4 - x}{4} = 1 \\rightarrow 4 - x = 4 \\rightarrow x = -6',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-fracciones', 'numeros-fracciones-comun-denominador', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-144',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $3(x - 2) = 2(x + 1)$',
    questionLatex: '\\text{Resolver: } 3(x - 2) = 2(x + 1)',
    options: ['$x = 6$', '$x = 7$', '$x = 8$', '$x = 9$'],
    optionsLatex: ['x = 6', 'x = 7', 'x = 8', 'x = 9'],
    correctAnswer: 2,
    explanation: 'Aplicamos distributiva en ambos lados y despejamos:',
    explanationLatex: '3(x - 2) = 2(x + 1) \\rightarrow 3x - 6 = 2x + 2 \\rightarrow 3x - 2x = 2 + 6 \\rightarrow x = 8',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'algebra-propiedad-distributiva', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-145',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $4(2x + 1) - 3(x - 2) = 22$',
    questionLatex: '\\text{Resolver: } 4(2x + 1) - 3(x - 2) = 22',
    options: ['$x = 2$', '$x = 3$', '$x = 4$', '$x = 5$'],
    optionsLatex: ['x = 2', 'x = 3', 'x = 4', 'x = 5'],
    correctAnswer: 0,
    explanation: 'Expandimos y simplificamos:',
    explanationLatex: '4(2x + 1) - 3(x - 2) = 22 \\rightarrow 8x + 4 - 3x + 6 = 22 \\rightarrow 5x + 10 = 22 \\rightarrow 5x = 12 \\rightarrow x = 2',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-146',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $2[x - (3 - x)] = 10$',
    questionLatex: '\\text{Resolver: } 2[x - (3 - x)] = 10',
    options: ['$x = 2$', '$x = 3$', '$x = 4$', '$x = 5$'],
    optionsLatex: ['x = 2', 'x = 3', 'x = 4', 'x = 5'],
    correctAnswer: 2,
    explanation: 'Resolvemos el paréntesis interno primero:',
    explanationLatex: '2[x - (3 - x)] = 10 \\rightarrow 2[x - 3 + x] = 10 \\rightarrow 2[2x - 3] = 10 \\rightarrow 4x - 6 = 10 \\rightarrow 4x = 16 \\rightarrow x = 4',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'algebra-propiedad-distributiva', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-147',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Pedro tiene el doble de edad que su hermana Ana. Si Ana tiene $x$ años y la suma de sus edades es 36 años, ¿cuántos años tiene Pedro?',
    questionLatex: '\\text{Pedro tiene el doble de edad que Ana. Si Ana tiene } x \\text{ años y la suma es 36 años, ¿cuántos años tiene Pedro?}',
    options: ['12 años', '18 años', '24 años', '30 años'],
    correctAnswer: 2,
    explanation: 'Planteamos la ecuación donde Pedro tiene 2x años:',
    explanationLatex: 'x + 2x = 36 \\rightarrow 3x = 36 \\rightarrow x = 12 \\text{ (Ana)} \\quad \\Rightarrow \\quad \\text{Pedro} = 2(12) = 24 \\text{ años}',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-148',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'La suma de tres números consecutivos es 48. ¿Cuál es el número mayor?',
    questionLatex: '\\text{La suma de tres números consecutivos es 48. ¿Cuál es el número mayor?}',
    options: ['15', '16', '17', '18'],
    correctAnswer: 2,
    explanation: 'Si el primer número es x, los consecutivos son x+1 y x+2:',
    explanationLatex: 'x + (x + 1) + (x + 2) = 48 \\rightarrow 3x + 3 = 48 \\rightarrow 3x = 45 \\rightarrow x = 15 \\quad \\Rightarrow \\quad \\text{mayor} = 15 + 2 = 17',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-149',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Un rectángulo tiene un largo que es 5 cm mayor que su ancho. Si el perímetro es 50 cm, ¿cuál es el ancho?',
    questionLatex: '\\text{Un rectángulo tiene largo 5 cm mayor que el ancho. Si el perímetro es 50 cm, ¿cuál es el ancho?}',
    options: ['8 cm', '10 cm', '12 cm', '15 cm'],
    correctAnswer: 1,
    explanation: 'Si el ancho es x, el largo es x+5. Perímetro: 2x + 2(x+5) = 50:',
    explanationLatex: '2x + 2(x + 5) = 50 \\rightarrow 2x + 2x + 10 = 50 \\rightarrow 4x = 40 \\rightarrow x = 10 \\text{ cm}',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'geometria-perimetro', 'geometria-rectangulos', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-201',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $3x - 7 \\leq 8$',
    questionLatex: '\\text{Resolver: } 3x - 7 \\leq 8',
    options: ['$x \\leq 5$', '$x \\geq 5$', '$x \\leq 15$', '$x < 5$'],
    optionsLatex: ['x \\leq 5', 'x \\geq 5', 'x \\leq 15', 'x < 5'],
    correctAnswer: 0,
    explanation: 'Despejamos $x$ como en una ecuación:',
    explanationLatex: '3x - 7 \\leq 8 \\rightarrow 3x \\leq 15 \\rightarrow x \\leq 5',
    difficulty: 'easy',
    skills: ['algebra-desigualdades', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-202',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $-2x + 4 > 10$',
    questionLatex: '\\text{Resolver: } -2x + 4 > 10',
    options: ['$x < -3$', '$x > -3$', '$x < 3$', '$x > 3$'],
    optionsLatex: ['x < -3', 'x > -3', 'x < 3', 'x > 3'],
    correctAnswer: 0,
    explanation: 'Al dividir por un número negativo, invertimos el signo de la desigualdad:',
    explanationLatex: '-2x + 4 > 10 \\rightarrow -2x > 6 \\rightarrow x < -3',
    difficulty: 'medium',
    skills: ['algebra-desigualdades', 'algebra-despeje', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-203',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\frac{x - 2}{3} \\geq 2$',
    questionLatex: '\\text{Resolver: } \\frac{x - 2}{3} \\geq 2',
    options: ['$x \\geq 8$', '$x \\geq 4$', '$x \\leq 8$', '$x > 8$'],
    optionsLatex: ['x \\geq 8', 'x \\geq 4', 'x \\leq 8', 'x > 8'],
    correctAnswer: 0,
    explanation: 'Multiplicamos ambos lados por 3 (positivo, no cambia el signo):',
    explanationLatex: '\\frac{x - 2}{3} \\geq 2 \\rightarrow x - 2 \\geq 6 \\rightarrow x \\geq 8',
    difficulty: 'medium',
    skills: ['algebra-desigualdades', 'algebra-despeje', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-204',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $|x| < 5$',
    questionLatex: '\\text{Resolver: } |x| < 5',
    options: ['$-5 < x < 5$', '$x < 5$', '$x > -5$', '$x < -5$ o $x > 5$'],
    optionsLatex: ['-5 < x < 5', 'x < 5', 'x > -5', 'x < -5 \\text{ o } x > 5'],
    correctAnswer: 0,
    explanation: 'El valor absoluto menor que un número positivo significa:',
    explanationLatex: '|x| < 5 \\quad \\Leftrightarrow \\quad -5 < x < 5',
    difficulty: 'medium',
    skills: ['algebra-desigualdades', 'algebra-valor-absoluto']
  },
  {
    id: 'm1-205',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $|x - 3| \\leq 2$',
    questionLatex: '\\text{Resolver: } |x - 3| \\leq 2',
    options: ['$1 \\leq x \\leq 5$', '$-2 \\leq x \\leq 2$', '$x \\leq 5$', '$x \\geq 1$'],
    optionsLatex: ['1 \\leq x \\leq 5', '-2 \\leq x \\leq 2', 'x \\leq 5', 'x \\geq 1'],
    correctAnswer: 0,
    explanation: 'Aplicamos la definición de valor absoluto:',
    explanationLatex: '|x - 3| \\leq 2 \\quad \\Leftrightarrow \\quad -2 \\leq x - 3 \\leq 2 \\quad \\Rightarrow \\quad 1 \\leq x \\leq 5',
    difficulty: 'hard',
    skills: ['algebra-desigualdades', 'algebra-valor-absoluto', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-206',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $|2x + 1| > 5$',
    questionLatex: '\\text{Resolver: } |2x + 1| > 5',
    options: ['$x < -3$ o $x > 2$', '$-3 < x < 2$', '$x > 2$', '$x < -3$'],
    optionsLatex: ['x < -3 \\text{ o } x > 2', '-3 < x < 2', 'x > 2', 'x < -3'],
    correctAnswer: 0,
    explanation: 'Para valor absoluto mayor que un número positivo:',
    explanationLatex: '|2x + 1| > 5 \\quad \\Leftrightarrow \\quad 2x + 1 < -5 \\text{ o } 2x + 1 > 5 \\quad \\Rightarrow \\quad x < -3 \\text{ o } x > 2',
    difficulty: 'hard',
    skills: ['algebra-desigualdades', 'algebra-valor-absoluto', 'numeros-operaciones-basicas']
  }
];
