import { Question } from '../../../types';

export const m1AlgebraExpresionesQuestions: Question[] = [
  {
    id: 'm1-13',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar la expresión: $3x + 5x - 2x$',
    questionLatex: '\\text{Simplificar la expresión: } 3x + 5x - 2x',
    options: ['$6x$', '$10x$', '$8x$', '$5x$'],
    optionsLatex: ['6x', '10x', '8x', '5x'],
    correctAnswer: 0,
    explanation: 'Sumamos y restamos los coeficientes de términos semejantes:',
    explanationLatex: '3x + 5x - 2x = (3 + 5 - 2)x = 6x',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-14',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Factorizar: $x^2 - 9$',
    questionLatex: '\\text{Factorizar: } x^2 - 9',
    options: ['$(x-3)(x-3)$', '$(x+3)(x+3)$', '$(x-3)(x+3)$', '$x(x-9)$'],
    optionsLatex: ['(x-3)(x-3)', '(x+3)(x+3)', '(x-3)(x+3)', 'x(x-9)'],
    correctAnswer: 2,
    explanation: 'Es una diferencia de cuadrados:',
    explanationLatex: 'x^2 - 9 = x^2 - 3^2 = (x-3)(x+3)',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'algebra-diferencia-cuadrados', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-31',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Expandir: $(x + 3)(x + 2)$',
    questionLatex: '\\text{Expandir: } (x + 3)(x + 2)',
    options: ['$x^2 + 5x + 6$', '$x^2 + 6x + 5$', '$x^2 + 5x + 5$', '$x^2 + 6x + 6$'],
    optionsLatex: ['x^2 + 5x + 6', 'x^2 + 6x + 5', 'x^2 + 5x + 5', 'x^2 + 6x + 6'],
    correctAnswer: 0,
    explanation: 'Aplicamos la propiedad distributiva:',
    explanationLatex: '(x + 3)(x + 2) = x^2 + 2x + 3x + 6 = x^2 + 5x + 6',
    difficulty: 'medium',
    skills: ['algebra-expansion', 'algebra-propiedad-distributiva', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-123',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el resultado de $(3x^2)(4x^3)$?',
    questionLatex: '\\text{¿Cuál es el resultado de } (3x^2)(4x^3)?',
    options: ['$7x^5$', '$12x^5$', '$7x^6$', '$12x^6$'],
    optionsLatex: ['7x^5', '12x^5', '7x^6', '12x^6'],
    correctAnswer: 1,
    explanation: 'Multiplicamos los coeficientes y sumamos los exponentes:',
    explanationLatex: '(3x^2)(4x^3) = 3 \\times 4 \\times x^{2+3} = 12x^5',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-124',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $(2a^3b)(5ab^2)$',
    questionLatex: '\\text{Simplificar: } (2a^3b)(5ab^2)',
    options: ['$10a^3b^2$', '$7a^4b^3$', '$10a^4b^3$', '$7a^3b^2$'],
    optionsLatex: ['10a^3b^2', '7a^4b^3', '10a^4b^3', '7a^3b^2'],
    correctAnswer: 2,
    explanation: 'Multiplicamos coeficientes y sumamos exponentes de cada variable:',
    explanationLatex: '(2a^3b)(5ab^2) = 2 \\times 5 \\times a^{3+1} \\times b^{1+2} = 10a^4b^3',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-125',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Juan multiplica dos monomios: $(-3x^2y)$ y $(2xy^3)$. ¿Cuál es el resultado?',
    questionLatex: '\\text{Juan multiplica dos monomios: } (-3x^2y) \\text{ y } (2xy^3). \\text{ ¿Cuál es el resultado?}',
    options: ['$-6x^2y^3$', '$-6x^3y^4$', '$-5x^3y^4$', '$6x^3y^4$'],
    optionsLatex: ['-6x^2y^3', '-6x^3y^4', '-5x^3y^4', '6x^3y^4'],
    correctAnswer: 1,
    explanation: 'Multiplicamos coeficientes (incluyendo signos) y sumamos exponentes:',
    explanationLatex: '(-3x^2y)(2xy^3) = -3 \\times 2 \\times x^{2+1} \\times y^{1+3} = -6x^3y^4',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-126',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el resultado de $\\frac{12x^5}{4x^2}$?',
    questionLatex: '\\text{¿Cuál es el resultado de } \\frac{12x^5}{4x^2}?',
    options: ['$3x^3$', '$8x^3$', '$3x^{10}$', '$8x^7$'],
    optionsLatex: ['3x^3', '8x^3', '3x^{10}', '8x^7'],
    correctAnswer: 0,
    explanation: 'Dividimos los coeficientes y restamos los exponentes:',
    explanationLatex: '\\frac{12x^5}{4x^2} = \\frac{12}{4} \\times x^{5-2} = 3x^3',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-127',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $\\frac{18a^4b^3}{6a^2b}$',
    questionLatex: '\\text{Simplificar: } \\frac{18a^4b^3}{6a^2b}',
    options: ['$3a^2b^2$', '$12a^2b^2$', '$3a^6b^4$', '$12a^6b^4$'],
    optionsLatex: ['3a^2b^2', '12a^2b^2', '3a^6b^4', '12a^6b^4'],
    correctAnswer: 0,
    explanation: 'Dividimos coeficientes y restamos exponentes de cada variable:',
    explanationLatex: '\\frac{18a^4b^3}{6a^2b} = \\frac{18}{6} \\times a^{4-2} \\times b^{3-1} = 3a^2b^2',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-128',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Calcular: $\\frac{-24x^6y^4}{8x^2y}$',
    questionLatex: '\\text{Calcular: } \\frac{-24x^6y^4}{8x^2y}',
    options: ['$-3x^4y^3$', '$3x^4y^3$', '$-3x^8y^5$', '$-16x^4y^3$'],
    optionsLatex: ['-3x^4y^3', '3x^4y^3', '-3x^8y^5', '-16x^4y^3'],
    correctAnswer: 0,
    explanation: 'Dividimos coeficientes con signo y restamos exponentes:',
    explanationLatex: '\\frac{-24x^6y^4}{8x^2y} = \\frac{-24}{8} \\times x^{6-2} \\times y^{4-1} = -3x^4y^3',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-129',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el resultado de $(2x^3)^2$?',
    questionLatex: '\\text{¿Cuál es el resultado de } (2x^3)^2?',
    options: ['$2x^6$', '$4x^6$', '$2x^5$', '$4x^5$'],
    optionsLatex: ['2x^6', '4x^6', '2x^5', '4x^5'],
    correctAnswer: 1,
    explanation: 'Elevamos el coeficiente y multiplicamos los exponentes:',
    explanationLatex: '(2x^3)^2 = 2^2 \\times (x^3)^2 = 4 \\times x^{3 \\times 2} = 4x^6',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-130',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $(3a^2b)^3$',
    questionLatex: '\\text{Simplificar: } (3a^2b)^3',
    options: ['$9a^5b^3$', '$27a^5b^3$', '$9a^6b^3$', '$27a^6b^3$'],
    optionsLatex: ['9a^5b^3', '27a^5b^3', '9a^6b^3', '27a^6b^3'],
    correctAnswer: 3,
    explanation: 'Elevamos cada factor a la potencia:',
    explanationLatex: '(3a^2b)^3 = 3^3 \\times (a^2)^3 \\times b^3 = 27 \\times a^6 \\times b^3 = 27a^6b^3',
    difficulty: 'hard',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-131',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Calcular: $(-2xy^2)^3$',
    questionLatex: '\\text{Calcular: } (-2xy^2)^3',
    options: ['$-8x^3y^6$', '$8x^3y^6$', '$-6x^3y^5$', '$-8x^4y^6$'],
    optionsLatex: ['-8x^3y^6', '8x^3y^6', '-6x^3y^5', '-8x^4y^6'],
    correctAnswer: 0,
    explanation: 'Elevamos cada factor, recordando que (-2)³ = -8:',
    explanationLatex: '(-2xy^2)^3 = (-2)^3 \\times x^3 \\times (y^2)^3 = -8 \\times x^3 \\times y^6 = -8x^3y^6',
    difficulty: 'hard',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-132',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $a = 2$ y $b = 3$, ¿cuál es el valor de $3a + 2b$?',
    questionLatex: '\\text{Si } a = 2 \\text{ y } b = 3, \\text{ ¿cuál es el valor de } 3a + 2b?',
    options: ['8', '11', '12', '15'],
    correctAnswer: 2,
    explanation: 'Sustituimos los valores y calculamos:',
    explanationLatex: '3a + 2b = 3(2) + 2(3) = 6 + 6 = 12',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'algebra-evaluacion-funciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-133',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Evaluar $x^2 - 2xy + y^2$ cuando $x = 5$ y $y = 3$',
    questionLatex: '\\text{Evaluar } x^2 - 2xy + y^2 \\text{ cuando } x = 5 \\text{ y } y = 3',
    options: ['4', '9', '16', '25'],
    correctAnswer: 0,
    explanation: 'Sustituimos los valores en la expresión:',
    explanationLatex: 'x^2 - 2xy + y^2 = 5^2 - 2(5)(3) + 3^2 = 25 - 30 + 9 = 4',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'algebra-evaluacion-funciones', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-134',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $a = -2$, $b = 4$ y $c = 1$, calcular $\\frac{a^2 + b}{c}$',
    questionLatex: '\\text{Si } a = -2, b = 4 \\text{ y } c = 1, \\text{ calcular } \\frac{a^2 + b}{c}',
    options: ['0', '4', '6', '8'],
    correctAnswer: 3,
    explanation: 'Sustituimos y evaluamos paso a paso:',
    explanationLatex: '\\frac{a^2 + b}{c} = \\frac{(-2)^2 + 4}{1} = \\frac{4 + 4}{1} = 8',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'algebra-evaluacion-funciones', 'numeros-potencias', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-135',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $2(x + 3) - 3(x - 1)$',
    questionLatex: '\\text{Simplificar: } 2(x + 3) - 3(x - 1)',
    options: ['$-x + 9$', '$-x + 3$', '$x + 9$', '$5x + 3$'],
    optionsLatex: ['-x + 9', '-x + 3', 'x + 9', '5x + 3'],
    correctAnswer: 0,
    explanation: 'Aplicamos distributiva y combinamos términos:',
    explanationLatex: '2(x + 3) - 3(x - 1) = 2x + 6 - 3x + 3 = -x + 9',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-136',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $5x - [2x - (3x - 4)]$',
    questionLatex: '\\text{Simplificar: } 5x - [2x - (3x - 4)]',
    options: ['$6x - 4$', '$6x + 4$', '$4x - 4$', '$4x + 4$'],
    optionsLatex: ['6x - 4', '6x + 4', '4x - 4', '4x + 4'],
    correctAnswer: 1,
    explanation: 'Resolvemos de adentro hacia afuera:',
    explanationLatex: '5x - [2x - (3x - 4)] = 5x - [2x - 3x + 4] = 5x - [-x + 4] = 5x + x - 4 = 6x + 4',
    difficulty: 'hard',
    skills: ['algebra-expresiones', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-137',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $3(2a - b) - 2(a + 3b)$',
    questionLatex: '\\text{Simplificar: } 3(2a - b) - 2(a + 3b)',
    options: ['$4a - 9b$', '$4a + 9b$', '$8a - 9b$', '$8a + 3b$'],
    optionsLatex: ['4a - 9b', '4a + 9b', '8a - 9b', '8a + 3b'],
    correctAnswer: 0,
    explanation: 'Aplicamos distributiva y simplificamos:',
    explanationLatex: '3(2a - b) - 2(a + 3b) = 6a - 3b - 2a - 6b = 4a - 9b',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-138',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'El perímetro de un rectángulo se calcula con $P = 2l + 2a$. Si $l = 8$ cm y $a = 5$ cm, ¿cuál es el perímetro?',
    questionLatex: '\\text{El perímetro de un rectángulo es } P = 2l + 2a. \\text{ Si } l = 8 \\text{ cm y } a = 5 \\text{ cm, ¿cuál es el perímetro?}',
    options: ['13 cm', '21 cm', '26 cm', '40 cm'],
    correctAnswer: 2,
    explanation: 'Sustituimos los valores en la fórmula:',
    explanationLatex: 'P = 2l + 2a = 2(8) + 2(5) = 16 + 10 = 26 \\text{ cm}',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'algebra-evaluacion-funciones', 'geometria-perimetro', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-139',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'La distancia recorrida es $d = vt$ donde $v$ es velocidad y $t$ es tiempo. Si un auto viaja a $v = 80$ km/h por $t = 2.5$ horas, ¿qué distancia recorre?',
    questionLatex: '\\text{La distancia es } d = vt. \\text{ Si } v = 80 \\text{ km/h y } t = 2.5 \\text{ h, ¿qué distancia recorre?}',
    options: ['160 km', '180 km', '200 km', '220 km'],
    correctAnswer: 2,
    explanation: 'Multiplicamos velocidad por tiempo:',
    explanationLatex: 'd = vt = 80 \\times 2.5 = 200 \\text{ km}',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'algebra-evaluacion-funciones', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-140',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'La temperatura en Fahrenheit se calcula con $F = \\frac{9}{5}C + 32$. Si $C = 25°$, ¿cuál es la temperatura en Fahrenheit?',
    questionLatex: '\\text{La temperatura es } F = \\frac{9}{5}C + 32. \\text{ Si } C = 25°, \\text{ ¿cuál es } F?',
    options: ['45°F', '57°F', '77°F', '93°F'],
    correctAnswer: 2,
    explanation: 'Sustituimos C = 25 en la fórmula:',
    explanationLatex: 'F = \\frac{9}{5}(25) + 32 = \\frac{225}{5} + 32 = 45 + 32 = 77°F',
    difficulty: 'hard',
    skills: ['algebra-expresiones', 'algebra-evaluacion-funciones', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-150',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Factorizar: $6x + 9$',
    questionLatex: '\\text{Factorizar: } 6x + 9',
    options: ['$3(2x + 3)$', '$6(x + 9)$', '$3(2x + 9)$', '$2(3x + 3)$'],
    optionsLatex: ['3(2x + 3)', '6(x + 9)', '3(2x + 9)', '2(3x + 3)'],
    correctAnswer: 0,
    explanation: 'Sacamos el factor común 3:',
    explanationLatex: '6x + 9 = 3(2x) + 3(3) = 3(2x + 3)',
    difficulty: 'easy',
    skills: ['algebra-factorizacion', 'numeros-mcd-mcm', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-151',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Factorizar: $4x^2 - 8x$',
    questionLatex: '\\text{Factorizar: } 4x^2 - 8x',
    options: ['$4x(x - 2)$', '$4(x^2 - 2x)$', '$x(4x - 8)$', '$2x(2x - 4)$'],
    optionsLatex: ['4x(x - 2)', '4(x^2 - 2x)', 'x(4x - 8)', '2x(2x - 4)'],
    correctAnswer: 0,
    explanation: 'Sacamos el factor común 4x:',
    explanationLatex: '4x^2 - 8x = 4x(x) - 4x(2) = 4x(x - 2)',
    difficulty: 'easy',
    skills: ['algebra-factorizacion', 'algebra-expresiones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-152',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Factorizar: $6a^3b + 9a^2b^2 - 12ab$',
    questionLatex: '\\text{Factorizar: } 6a^3b + 9a^2b^2 - 12ab',
    options: ['$3ab(2a^2 + 3ab - 4)$', '$6ab(a^2 + ab - 2)$', '$3a(2a^2b + 3ab^2 - 4b)$', '$ab(6a^2 + 9ab - 12)$'],
    optionsLatex: ['3ab(2a^2 + 3ab - 4)', '6ab(a^2 + ab - 2)', '3a(2a^2b + 3ab^2 - 4b)', 'ab(6a^2 + 9ab - 12)'],
    correctAnswer: 0,
    explanation: 'Identificamos el factor común: 3ab es el MCD de los términos:',
    explanationLatex: '6a^3b + 9a^2b^2 - 12ab = 3ab(2a^2) + 3ab(3ab) - 3ab(4) = 3ab(2a^2 + 3ab - 4)',
    difficulty: 'hard',
    skills: ['algebra-factorizacion', 'algebra-expresiones', 'numeros-mcd-mcm', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-153',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Factorizar: $x^2 + 6x + 9$',
    questionLatex: '\\text{Factorizar: } x^2 + 6x + 9',
    options: ['$(x + 3)^2$', '$(x - 3)^2$', '$(x + 3)(x - 3)$', '$(x + 9)(x + 1)$'],
    optionsLatex: ['(x + 3)^2', '(x - 3)^2', '(x + 3)(x - 3)', '(x + 9)(x + 1)'],
    correctAnswer: 0,
    explanation: 'Es un trinomio cuadrado perfecto de la forma $a^2 + 2ab + b^2 = (a + b)^2$:',
    explanationLatex: 'x^2 + 6x + 9 = x^2 + 2(x)(3) + 3^2 = (x + 3)^2',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-154',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Factorizar: $4x^2 - 12x + 9$',
    questionLatex: '\\text{Factorizar: } 4x^2 - 12x + 9',
    options: ['$(2x - 3)^2$', '$(2x + 3)^2$', '$(4x - 3)^2$', '$(x - 3)^2$'],
    optionsLatex: ['(2x - 3)^2', '(2x + 3)^2', '(4x - 3)^2', '(x - 3)^2'],
    correctAnswer: 0,
    explanation: 'Es un trinomio cuadrado perfecto: $a^2 - 2ab + b^2 = (a - b)^2$:',
    explanationLatex: '4x^2 - 12x + 9 = (2x)^2 - 2(2x)(3) + 3^2 = (2x - 3)^2',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-155',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál de las siguientes expresiones es un trinomio cuadrado perfecto?',
    questionLatex: '\\text{¿Cuál de las siguientes expresiones es un trinomio cuadrado perfecto?}',
    options: ['$x^2 + 4x + 4$', '$x^2 + 4x + 2$', '$x^2 + 2x + 4$', '$x^2 + 8x + 4$'],
    optionsLatex: ['x^2 + 4x + 4', 'x^2 + 4x + 2', 'x^2 + 2x + 4', 'x^2 + 8x + 4'],
    correctAnswer: 0,
    explanation: 'Para ser TCP, el tercer término debe ser el cuadrado de la mitad del coeficiente de x:',
    explanationLatex: 'x^2 + 4x + 4 = x^2 + 2(x)(2) + 2^2 = (x + 2)^2 \\text{ es TCP}',
    difficulty: 'hard',
    skills: ['algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-156',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Factorizar: $x^2 + 7x + 12$',
    questionLatex: '\\text{Factorizar: } x^2 + 7x + 12',
    options: ['$(x + 3)(x + 4)$', '$(x + 2)(x + 6)$', '$(x + 1)(x + 12)$', '$(x + 3)(x + 5)$'],
    optionsLatex: ['(x + 3)(x + 4)', '(x + 2)(x + 6)', '(x + 1)(x + 12)', '(x + 3)(x + 5)'],
    correctAnswer: 0,
    explanation: 'Buscamos dos números que sumen 7 y multipliquen 12: 3 y 4:',
    explanationLatex: 'x^2 + 7x + 12 = (x + 3)(x + 4) \\quad \\text{porque } 3 + 4 = 7 \\text{ y } 3 \\times 4 = 12',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-157',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Factorizar: $x^2 - 5x + 6$',
    questionLatex: '\\text{Factorizar: } x^2 - 5x + 6',
    options: ['$(x - 2)(x - 3)$', '$(x + 2)(x + 3)$', '$(x - 1)(x - 6)$', '$(x - 2)(x + 3)$'],
    optionsLatex: ['(x - 2)(x - 3)', '(x + 2)(x + 3)', '(x - 1)(x - 6)', '(x - 2)(x + 3)'],
    correctAnswer: 0,
    explanation: 'Buscamos dos números que sumen -5 y multipliquen 6: -2 y -3:',
    explanationLatex: 'x^2 - 5x + 6 = (x - 2)(x - 3) \\quad \\text{porque } (-2) + (-3) = -5 \\text{ y } (-2)(-3) = 6',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-158',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Factorizar: $x^2 + 2x - 15$',
    questionLatex: '\\text{Factorizar: } x^2 + 2x - 15',
    options: ['$(x + 5)(x - 3)$', '$(x - 5)(x + 3)$', '$(x + 15)(x - 1)$', '$(x + 3)(x - 5)$'],
    optionsLatex: ['(x + 5)(x - 3)', '(x - 5)(x + 3)', '(x + 15)(x - 1)', '(x + 3)(x - 5)'],
    correctAnswer: 0,
    explanation: 'Buscamos dos números que sumen 2 y multipliquen -15: 5 y -3:',
    explanationLatex: 'x^2 + 2x - 15 = (x + 5)(x - 3) \\quad \\text{porque } 5 + (-3) = 2 \\text{ y } 5(-3) = -15',
    difficulty: 'hard',
    skills: ['algebra-factorizacion', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-159',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Expandir: $(x + 5)^2$',
    questionLatex: '\\text{Expandir: } (x + 5)^2',
    options: ['$x^2 + 25$', '$x^2 + 10x + 25$', '$x^2 + 5x + 25$', '$x^2 + 10x + 10$'],
    optionsLatex: ['x^2 + 25', 'x^2 + 10x + 25', 'x^2 + 5x + 25', 'x^2 + 10x + 10'],
    correctAnswer: 1,
    explanation: 'Aplicamos la fórmula del cuadrado de un binomio: $(a + b)^2 = a^2 + 2ab + b^2$',
    explanationLatex: '(x + 5)^2 = x^2 + 2(x)(5) + 5^2 = x^2 + 10x + 25',
    difficulty: 'easy',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-160',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Expandir: $(2x - 3)^2$',
    questionLatex: '\\text{Expandir: } (2x - 3)^2',
    options: ['$4x^2 - 12x + 9$', '$4x^2 + 12x + 9$', '$4x^2 - 6x + 9$', '$2x^2 - 6x + 9$'],
    optionsLatex: ['4x^2 - 12x + 9', '4x^2 + 12x + 9', '4x^2 - 6x + 9', '2x^2 - 6x + 9'],
    correctAnswer: 0,
    explanation: 'Aplicamos $(a - b)^2 = a^2 - 2ab + b^2$:',
    explanationLatex: '(2x - 3)^2 = (2x)^2 - 2(2x)(3) + 3^2 = 4x^2 - 12x + 9',
    difficulty: 'medium',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-161',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'María quiere expandir $(3a + 2b)^2$. ¿Cuál es el resultado correcto?',
    questionLatex: '\\text{María quiere expandir } (3a + 2b)^2. \\text{ ¿Cuál es el resultado correcto?}',
    options: ['$9a^2 + 4b^2$', '$9a^2 + 6ab + 4b^2$', '$9a^2 + 12ab + 4b^2$', '$3a^2 + 12ab + 2b^2$'],
    optionsLatex: ['9a^2 + 4b^2', '9a^2 + 6ab + 4b^2', '9a^2 + 12ab + 4b^2', '3a^2 + 12ab + 2b^2'],
    correctAnswer: 2,
    explanation: 'Aplicamos $(a + b)^2 = a^2 + 2ab + b^2$ con a = 3a y b = 2b:',
    explanationLatex: '(3a + 2b)^2 = (3a)^2 + 2(3a)(2b) + (2b)^2 = 9a^2 + 12ab + 4b^2',
    difficulty: 'hard',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-162',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Expandir: $(x + 4)(x - 4)$',
    questionLatex: '\\text{Expandir: } (x + 4)(x - 4)',
    options: ['$x^2 - 16$', '$x^2 + 16$', '$x^2 - 8x - 16$', '$x^2 + 8x - 16$'],
    optionsLatex: ['x^2 - 16', 'x^2 + 16', 'x^2 - 8x - 16', 'x^2 + 8x - 16'],
    correctAnswer: 0,
    explanation: 'Aplicamos la diferencia de cuadrados: $(a + b)(a - b) = a^2 - b^2$',
    explanationLatex: '(x + 4)(x - 4) = x^2 - 4^2 = x^2 - 16',
    difficulty: 'easy',
    skills: ['algebra-productos-notables', 'algebra-diferencia-cuadrados', 'algebra-expansion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-163',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Calcular: $(3x + 5)(3x - 5)$',
    questionLatex: '\\text{Calcular: } (3x + 5)(3x - 5)',
    options: ['$3x^2 - 25$', '$9x^2 - 25$', '$9x^2 - 30x - 25$', '$9x^2 + 25$'],
    optionsLatex: ['3x^2 - 25', '9x^2 - 25', '9x^2 - 30x - 25', '9x^2 + 25'],
    correctAnswer: 1,
    explanation: 'Aplicamos $(a + b)(a - b) = a^2 - b^2$ con a = 3x y b = 5:',
    explanationLatex: '(3x + 5)(3x - 5) = (3x)^2 - 5^2 = 9x^2 - 25',
    difficulty: 'medium',
    skills: ['algebra-productos-notables', 'algebra-diferencia-cuadrados', 'algebra-expansion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-164',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Un terreno cuadrado de lado $x$ metros se expande $3$ metros en una dirección pero se reduce $3$ metros en la otra. ¿Cuál es el área del terreno rectangular resultante?',
    questionLatex: '\\text{Un terreno cuadrado de lado } x \\text{ m se expande 3 m en una dirección pero se reduce 3 m en la otra. ¿Cuál es el área?}',
    options: ['$x^2$ m²', '$x^2 - 9$ m²', '$x^2 + 9$ m²', '$x^2 - 6x - 9$ m²'],
    optionsLatex: ['x^2 \\text{ m}^2', 'x^2 - 9 \\text{ m}^2', 'x^2 + 9 \\text{ m}^2', 'x^2 - 6x - 9 \\text{ m}^2'],
    correctAnswer: 1,
    explanation: 'El área es (x + 3)(x - 3), que es una diferencia de cuadrados:',
    explanationLatex: '\\text{Área} = (x + 3)(x - 3) = x^2 - 9 \\text{ m}^2',
    difficulty: 'hard',
    skills: ['algebra-productos-notables', 'algebra-diferencia-cuadrados', 'geometria-area', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-165',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Expandir: $(x + 2)^3$',
    questionLatex: '\\text{Expandir: } (x + 2)^3',
    options: ['$x^3 + 6x^2 + 12x + 8$', '$x^3 + 8$', '$x^3 + 2x^2 + 4x + 8$', '$x^3 + 6x^2 + 8x + 8$'],
    optionsLatex: ['x^3 + 6x^2 + 12x + 8', 'x^3 + 8', 'x^3 + 2x^2 + 4x + 8', 'x^3 + 6x^2 + 8x + 8'],
    correctAnswer: 0,
    explanation: 'Aplicamos $(a + b)^3 = a^3 + 3a^2b + 3ab^2 + b^3$:',
    explanationLatex: '(x + 2)^3 = x^3 + 3x^2(2) + 3x(2^2) + 2^3 = x^3 + 6x^2 + 12x + 8',
    difficulty: 'medium',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-166',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Expandir: $(x - 1)^3$',
    questionLatex: '\\text{Expandir: } (x - 1)^3',
    options: ['$x^3 - 3x^2 + 3x - 1$', '$x^3 - 1$', '$x^3 - x^2 - x - 1$', '$x^3 + 3x^2 - 3x + 1$'],
    optionsLatex: ['x^3 - 3x^2 + 3x - 1', 'x^3 - 1', 'x^3 - x^2 - x - 1', 'x^3 + 3x^2 - 3x + 1'],
    correctAnswer: 0,
    explanation: 'Aplicamos $(a - b)^3 = a^3 - 3a^2b + 3ab^2 - b^3$:',
    explanationLatex: '(x - 1)^3 = x^3 - 3x^2(1) + 3x(1^2) - 1^3 = x^3 - 3x^2 + 3x - 1',
    difficulty: 'medium',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-167',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el coeficiente del término $x^2$ en la expansión de $(2x + 1)^3$?',
    questionLatex: '\\text{¿Cuál es el coeficiente del término } x^2 \\text{ en la expansión de } (2x + 1)^3?',
    options: ['6', '12', '24', '8'],
    correctAnswer: 1,
    explanation: 'Expandimos usando $(a + b)^3 = a^3 + 3a^2b + 3ab^2 + b^3$:',
    explanationLatex: '(2x + 1)^3 = (2x)^3 + 3(2x)^2(1) + 3(2x)(1)^2 + 1^3 = 8x^3 + 12x^2 + 6x + 1',
    difficulty: 'hard',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-207',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Sumar: $(3x^2 + 2x - 5) + (x^2 - 4x + 3)$',
    questionLatex: '\\text{Sumar: } (3x^2 + 2x - 5) + (x^2 - 4x + 3)',
    options: ['$4x^2 - 2x - 2$', '$4x^2 + 6x - 2$', '$4x^2 - 2x + 8$', '$3x^2 - 2x - 2$'],
    optionsLatex: ['4x^2 - 2x - 2', '4x^2 + 6x - 2', '4x^2 - 2x + 8', '3x^2 - 2x - 2'],
    correctAnswer: 0,
    explanation: 'Sumamos coeficientes de términos semejantes:',
    explanationLatex: '(3x^2 + x^2) + (2x - 4x) + (-5 + 3) = 4x^2 - 2x - 2',
    difficulty: 'easy',
    skills: ['algebra-polinomios', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-208',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Restar: $(5x^3 + 3x - 1) - (2x^3 - x + 4)$',
    questionLatex: '\\text{Restar: } (5x^3 + 3x - 1) - (2x^3 - x + 4)',
    options: ['$3x^3 + 4x - 5$', '$3x^3 + 2x - 5$', '$3x^3 + 4x + 3$', '$7x^3 + 2x + 3$'],
    optionsLatex: ['3x^3 + 4x - 5', '3x^3 + 2x - 5', '3x^3 + 4x + 3', '7x^3 + 2x + 3'],
    correctAnswer: 0,
    explanation: 'Distribuimos el signo negativo y restamos términos semejantes:',
    explanationLatex: '(5x^3 - 2x^3) + (3x - (-x)) + (-1 - 4) = 3x^3 + 4x - 5',
    difficulty: 'medium',
    skills: ['algebra-polinomios', 'algebra-terminos-semejantes', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-209',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $(2x^2 + 5x - 3) - (x^2 + 2x - 1) + (3x^2 - x + 4)$',
    questionLatex: '\\text{Simplificar: } (2x^2 + 5x - 3) - (x^2 + 2x - 1) + (3x^2 - x + 4)',
    options: ['$4x^2 + 2x$', '$4x^2 + 2x + 2$', '$6x^2 + 2x$', '$4x^2 + 8x$'],
    optionsLatex: ['4x^2 + 2x', '4x^2 + 2x + 2', '6x^2 + 2x', '4x^2 + 8x'],
    correctAnswer: 0,
    explanation: 'Agrupamos y sumamos términos semejantes:',
    explanationLatex: '(2x^2 - x^2 + 3x^2) + (5x - 2x - x) + (-3 + 1 + 4) = 4x^2 + 2x + 0 = 4x^2 + 2x',
    difficulty: 'hard',
    skills: ['algebra-polinomios', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-210',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Multiplicar: $(x + 2)(x^2 - 3x + 1)$',
    questionLatex: '\\text{Multiplicar: } (x + 2)(x^2 - 3x + 1)',
    options: ['$x^3 - x^2 - 5x + 2$', '$x^3 - 3x^2 + x + 2$', '$x^3 + 2x^2 - 3x + 1$', '$x^3 - x^2 + x + 2$'],
    optionsLatex: ['x^3 - x^2 - 5x + 2', 'x^3 - 3x^2 + x + 2', 'x^3 + 2x^2 - 3x + 1', 'x^3 - x^2 + x + 2'],
    correctAnswer: 0,
    explanation: 'Aplicamos distributiva:',
    explanationLatex: 'x(x^2 - 3x + 1) + 2(x^2 - 3x + 1) = x^3 - 3x^2 + x + 2x^2 - 6x + 2 = x^3 - x^2 - 5x + 2',
    difficulty: 'medium',
    skills: ['algebra-polinomios', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-211',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Multiplicar: $(2x - 1)(x^2 + 3x - 4)$',
    questionLatex: '\\text{Multiplicar: } (2x - 1)(x^2 + 3x - 4)',
    options: ['$2x^3 + 5x^2 - 11x + 4$', '$2x^3 + 6x^2 - 8x - 4$', '$2x^3 - x^2 - 7x + 4$', '$2x^3 + 5x^2 - 5x + 4$'],
    optionsLatex: ['2x^3 + 5x^2 - 11x + 4', '2x^3 + 6x^2 - 8x - 4', '2x^3 - x^2 - 7x + 4', '2x^3 + 5x^2 - 5x + 4'],
    correctAnswer: 0,
    explanation: 'Multiplicamos cada término del primer polinomio por cada término del segundo:',
    explanationLatex: '2x(x^2 + 3x - 4) - 1(x^2 + 3x - 4) = 2x^3 + 6x^2 - 8x - x^2 - 3x + 4 = 2x^3 + 5x^2 - 11x + 4',
    difficulty: 'hard',
    skills: ['algebra-polinomios', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-212',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'María multiplica $(x - 2)(x + 3)(x + 1)$. ¿Cuál es el coeficiente de $x^2$ en el resultado?',
    questionLatex: '\\text{María multiplica } (x - 2)(x + 3)(x + 1). \\text{ ¿Cuál es el coeficiente de } x^2?',
    options: ['2', '3', '4', '1'],
    correctAnswer: 0,
    explanation: 'Multiplicamos primero dos binomios y luego por el tercero:',
    explanationLatex: '(x - 2)(x + 3) = x^2 + x - 6 \\rightarrow (x^2 + x - 6)(x + 1) = x^3 + 2x^2 - 5x - 6',
    difficulty: 'hard',
    skills: ['algebra-polinomios', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-213',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Dividir: $(6x^3 + 9x^2) \\div (3x^2)$',
    questionLatex: '\\text{Dividir: } (6x^3 + 9x^2) \\div (3x^2)',
    options: ['$2x + 3$', '$2x^2 + 3$', '$6x + 9$', '$3x + 3$'],
    optionsLatex: ['2x + 3', '2x^2 + 3', '6x + 9', '3x + 3'],
    correctAnswer: 0,
    explanation: 'Dividimos cada término del dividendo por el divisor:',
    explanationLatex: '\\frac{6x^3}{3x^2} + \\frac{9x^2}{3x^2} = 2x + 3',
    difficulty: 'easy',
    skills: ['algebra-polinomios', 'algebra-division-polinomios', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-214',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Dividir: $(x^2 - 5x + 6) \\div (x - 2)$',
    questionLatex: '\\text{Dividir: } (x^2 - 5x + 6) \\div (x - 2)',
    options: ['$x - 3$', '$x + 3$', '$x - 4$', '$x - 2$'],
    optionsLatex: ['x - 3', 'x + 3', 'x - 4', 'x - 2'],
    correctAnswer: 0,
    explanation: 'Factorizamos el dividendo y simplificamos:',
    explanationLatex: '\\frac{x^2 - 5x + 6}{x - 2} = \\frac{(x - 2)(x - 3)}{x - 2} = x - 3',
    difficulty: 'medium',
    skills: ['algebra-polinomios', 'algebra-division-polinomios', 'algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-215',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Al dividir $(2x^3 - 5x^2 + 3x - 2)$ por $(x - 2)$, ¿cuál es el residuo?',
    questionLatex: '\\text{Al dividir } (2x^3 - 5x^2 + 3x - 2) \\text{ por } (x - 2), \\text{ ¿cuál es el residuo?}',
    options: ['0', '2', '4', '6'],
    correctAnswer: 0,
    explanation: 'Usamos el teorema del residuo: evaluamos $P(2)$:',
    explanationLatex: 'P(2) = 2(2)^3 - 5(2)^2 + 3(2) - 2 = 16 - 20 + 6 - 2 = 0',
    difficulty: 'hard',
    skills: ['algebra-polinomios', 'algebra-division-polinomios', 'algebra-teorema-residuo', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-216',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $\\frac{6x^2}{3x}$',
    questionLatex: '\\text{Simplificar: } \\frac{6x^2}{3x}',
    options: ['$2x$', '$3x$', '$2x^2$', '$\\frac{2}{x}$'],
    optionsLatex: ['2x', '3x', '2x^2', '\\frac{2}{x}'],
    correctAnswer: 0,
    explanation: 'Dividimos coeficientes y restamos exponentes:',
    explanationLatex: '\\frac{6x^2}{3x} = \\frac{6}{3} \\times x^{2-1} = 2x',
    difficulty: 'easy',
    skills: ['algebra-expresiones-racionales', 'algebra-simplificacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-217',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $\\frac{x^2 - 4}{x + 2}$',
    questionLatex: '\\text{Simplificar: } \\frac{x^2 - 4}{x + 2}',
    options: ['$x - 2$', '$x + 2$', '$x^2 - 2$', '$\\frac{x - 4}{1}$'],
    optionsLatex: ['x - 2', 'x + 2', 'x^2 - 2', '\\frac{x - 4}{1}'],
    correctAnswer: 0,
    explanation: 'Factorizamos el numerador como diferencia de cuadrados:',
    explanationLatex: '\\frac{x^2 - 4}{x + 2} = \\frac{(x - 2)(x + 2)}{x + 2} = x - 2',
    difficulty: 'medium',
    skills: ['algebra-expresiones-racionales', 'algebra-simplificacion', 'algebra-factorizacion', 'algebra-diferencia-cuadrados']
  },
  {
    id: 'm1-218',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $\\frac{x^2 + 5x + 6}{x^2 + 3x + 2}$',
    questionLatex: '\\text{Simplificar: } \\frac{x^2 + 5x + 6}{x^2 + 3x + 2}',
    options: ['$\\frac{x + 3}{x + 1}$', '$\\frac{x + 2}{x + 1}$', '$\\frac{x + 3}{x + 2}$', '$\\frac{x + 6}{x + 2}$'],
    optionsLatex: ['\\frac{x + 3}{x + 1}', '\\frac{x + 2}{x + 1}', '\\frac{x + 3}{x + 2}', '\\frac{x + 6}{x + 2}'],
    correctAnswer: 0,
    explanation: 'Factorizamos numerador y denominador:',
    explanationLatex: '\\frac{(x + 2)(x + 3)}{(x + 1)(x + 2)} = \\frac{x + 3}{x + 1}',
    difficulty: 'hard',
    skills: ['algebra-expresiones-racionales', 'algebra-simplificacion', 'algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-219',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Multiplicar: $\\frac{2x}{3} \\times \\frac{6}{x}$',
    questionLatex: '\\text{Multiplicar: } \\frac{2x}{3} \\times \\frac{6}{x}',
    options: ['4', '$\\frac{12x}{3x}$', '$\\frac{2x}{x}$', '12'],
    correctAnswer: 0,
    explanation: 'Multiplicamos numeradores y denominadores, luego simplificamos:',
    explanationLatex: '\\frac{2x}{3} \\times \\frac{6}{x} = \\frac{2x \\times 6}{3 \\times x} = \\frac{12x}{3x} = 4',
    difficulty: 'easy',
    skills: ['algebra-expresiones-racionales', 'algebra-multiplicacion-fracciones', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-220',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Dividir: $\\frac{x^2}{2} \\div \\frac{x}{4}$',
    questionLatex: '\\text{Dividir: } \\frac{x^2}{2} \\div \\frac{x}{4}',
    options: ['$2x$', '$\\frac{x^2}{8}$', '$\\frac{x}{2}$', '$4x$'],
    optionsLatex: ['2x', '\\frac{x^2}{8}', '\\frac{x}{2}', '4x'],
    correctAnswer: 0,
    explanation: 'Multiplicamos por el recíproco:',
    explanationLatex: '\\frac{x^2}{2} \\div \\frac{x}{4} = \\frac{x^2}{2} \\times \\frac{4}{x} = \\frac{4x^2}{2x} = 2x',
    difficulty: 'medium',
    skills: ['algebra-expresiones-racionales', 'algebra-division-fracciones', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-221',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Sumar: $\\frac{2}{x} + \\frac{3}{x}$',
    questionLatex: '\\text{Sumar: } \\frac{2}{x} + \\frac{3}{x}',
    options: ['$\\frac{5}{x}$', '$\\frac{5}{2x}$', '$\\frac{2x + 3}{x}$', '$5x$'],
    optionsLatex: ['\\frac{5}{x}', '\\frac{5}{2x}', '\\frac{2x + 3}{x}', '5x'],
    correctAnswer: 0,
    explanation: 'Como tienen el mismo denominador, sumamos los numeradores:',
    explanationLatex: '\\frac{2}{x} + \\frac{3}{x} = \\frac{2 + 3}{x} = \\frac{5}{x}',
    difficulty: 'easy',
    skills: ['algebra-expresiones-racionales', 'algebra-suma-fracciones', 'numeros-fracciones', 'numeros-operaciones-basicas']
  }
];
