import { Question } from '../../../types';

export const m1AlgebraFactorizacionQuestions: Question[] = [
  {
    id: 'm1-14',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: 'x^2 - 9',
    question: 'Un terreno cuadrado tiene un área de x² metros cuadrados. El dueño decide vender una porción cuadrada de 9 metros cuadrados de una esquina para construir una caseta de vigilancia. Un agrimensor necesita expresar el área restante del terreno como un producto de dos factores lineales para calcular las dimensiones posibles del cercado. ¿Cuál es la factorización correcta de la expresión que representa el área restante?',
    questionLatex: '\\text{Un terreno cuadrado tiene un área de } x^2 \\text{ metros cuadrados. El dueño decide vender una porción cuadrada de 9 metros cuadrados de una esquina para construir una caseta de vigilancia. Un agrimensor necesita expresar el área restante del terreno como un producto de dos factores lineales para calcular las dimensiones posibles del cercado. ¿Cuál es la factorización correcta de la expresión que representa el área restante?}',
    options: ['$(x-3)(x-3)$', '$(x+3)(x+3)$', '$(x-3)(x+3)$', '$x(x-9)$'],
    optionsLatex: ['(x-3)(x-3)', '(x+3)(x+3)', '(x-3)(x+3)', 'x(x-9)'],
    correctAnswer: 2,
    explanation: 'El área restante x² - 9 es una diferencia de cuadrados, donde x² = x² y 9 = 3². Aplicando la fórmula a² - b² = (a - b)(a + b), obtenemos: x² - 9 = (x - 3)(x + 3).',
    explanationLatex: 'x^2 - 9 = x^2 - 3^2 = (x-3)(x+3)',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'algebra-diferencia-cuadrados', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-150',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '6x + 9',
    question: 'Una pastelería prepara cajas de regalo que contienen 6 unidades de un producto x más 9 unidades de otro producto. El gerente quiere reorganizar el inventario agrupando los productos en paquetes iguales lo más grandes posible, donde cada paquete contenga la misma combinación de productos. Para optimizar el espacio, necesita factorizar la expresión que representa el total de productos. ¿Cuál es la factorización correcta?',
    questionLatex: '\\text{Una pastelería prepara cajas de regalo que contienen 6 unidades de un producto x más 9 unidades de otro producto. El gerente quiere reorganizar el inventario agrupando los productos en paquetes iguales lo más grandes posible, donde cada paquete contenga la misma combinación de productos. Para optimizar el espacio, necesita factorizar la expresión que representa el total de productos. ¿Cuál es la factorización correcta?}',
    options: ['$3(2x + 3)$', '$6(x + 9)$', '$3(2x + 9)$', '$2(3x + 3)$'],
    optionsLatex: ['3(2x + 3)', '6(x + 9)', '3(2x + 9)', '2(3x + 3)'],
    correctAnswer: 0,
    explanation: 'Identificamos el máximo común divisor de 6 y 9, que es 3. Sacamos el factor común: 6x + 9 = 3(2x) + 3(3) = 3(2x + 3). Cada paquete contendrá 3 unidades divididas en 2x + 3 productos.',
    explanationLatex: '6x + 9 = 3(2x) + 3(3) = 3(2x + 3)',
    difficulty: 'easy',
    skills: ['algebra-factorizacion', 'numeros-mcd-mcm', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-151',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '4x^2 - 8x',
    question: 'Un carpintero construye mesas rectangulares. El área total de madera usada en tableros es 4x² metros cuadrados, y el área usada en bordes decorativos es 8x metros cuadrados. Para calcular eficientemente el costo, necesita factorizar la expresión que representa la diferencia entre estas áreas, sacando el máximo factor común. ¿Cuál es la factorización correcta?',
    questionLatex: '\\text{Un carpintero construye mesas rectangulares. El área total de madera usada en tableros es } 4x^2 \\text{ metros cuadrados, y el área usada en bordes decorativos es } 8x \\text{ metros cuadrados. Para calcular eficientemente el costo, necesita factorizar la expresión que representa la diferencia entre estas áreas, sacando el máximo factor común. ¿Cuál es la factorización correcta?}',
    options: ['$4x(x - 2)$', '$4(x^2 - 2x)$', '$x(4x - 8)$', '$2x(2x - 4)$'],
    optionsLatex: ['4x(x - 2)', '4(x^2 - 2x)', 'x(4x - 8)', '2x(2x - 4)'],
    correctAnswer: 0,
    explanation: 'Identificamos el factor común máximo entre 4x² y 8x, que es 4x. Factorizamos: 4x² - 8x = 4x(x) - 4x(2) = 4x(x - 2).',
    explanationLatex: '4x^2 - 8x = 4x(x) - 4x(2) = 4x(x - 2)',
    difficulty: 'easy',
    skills: ['algebra-factorizacion', 'algebra-expresiones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-152',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '6a^3b + 9a^2b^2 - 12ab',
    question: 'Un laboratorio químico mezcla tres compuestos en diferentes concentraciones: 6a³b moléculas del compuesto A, más 9a²b² moléculas del compuesto B, menos 12ab moléculas del compuesto C, donde a y b son factores de dilución. El químico necesita factorizar completamente esta expresión para identificar la concentración base común y simplificar los cálculos de dosificación. ¿Cuál es la factorización que extrae el máximo factor común?',
    questionLatex: '\\text{Un laboratorio químico mezcla tres compuestos en diferentes concentraciones: } 6a^3b \\text{ moléculas del compuesto A, más } 9a^2b^2 \\text{ moléculas del compuesto B, menos } 12ab \\text{ moléculas del compuesto C, donde a y b son factores de dilución. El químico necesita factorizar completamente esta expresión para identificar la concentración base común y simplificar los cálculos de dosificación. ¿Cuál es la factorización que extrae el máximo factor común?}',
    options: ['$3ab(2a^2 + 3ab - 4)$', '$6ab(a^2 + ab - 2)$', '$3a(2a^2b + 3ab^2 - 4b)$', '$ab(6a^2 + 9ab - 12)$'],
    optionsLatex: ['3ab(2a^2 + 3ab - 4)', '6ab(a^2 + ab - 2)', '3a(2a^2b + 3ab^2 - 4b)', 'ab(6a^2 + 9ab - 12)'],
    correctAnswer: 0,
    explanation: 'Identificamos el MCD de los coeficientes (6, 9, 12) que es 3, y las variables comunes ab. El factor común es 3ab. Factorizamos: 6a³b + 9a²b² - 12ab = 3ab(2a²) + 3ab(3ab) - 3ab(4) = 3ab(2a² + 3ab - 4).',
    explanationLatex: '6a^3b + 9a^2b^2 - 12ab = 3ab(2a^2) + 3ab(3ab) - 3ab(4) = 3ab(2a^2 + 3ab - 4)',
    difficulty: 'hard',
    skills: ['algebra-factorizacion', 'algebra-expresiones', 'numeros-mcd-mcm', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-153',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: 'x^2 + 6x + 9',
    question: 'Un jardinero diseña un jardín cuadrado de lado (x + 3) metros. Al calcular el área total del jardín expandiendo la expresión, obtiene x² + 6x + 9 metros cuadrados. Un inspector municipal necesita verificar que esta expresión corresponde efectivamente a un cuadrado perfecto para aprobar el diseño. ¿Cuál es la factorización que demuestra que es un trinomio cuadrado perfecto?',
    questionLatex: '\\text{Un jardinero diseña un jardín cuadrado de lado } (x + 3) \\text{ metros. Al calcular el área total del jardín expandiendo la expresión, obtiene } x^2 + 6x + 9 \\text{ metros cuadrados. Un inspector municipal necesita verificar que esta expresión corresponde efectivamente a un cuadrado perfecto para aprobar el diseño. ¿Cuál es la factorización que demuestra que es un trinomio cuadrado perfecto?}',
    options: ['$(x + 3)^2$', '$(x - 3)^2$', '$(x + 3)(x - 3)$', '$(x + 9)(x + 1)$'],
    optionsLatex: ['(x + 3)^2', '(x - 3)^2', '(x + 3)(x - 3)', '(x + 9)(x + 1)'],
    correctAnswer: 0,
    explanation: 'Identificamos que es un trinomio cuadrado perfecto con la forma a² + 2ab + b². Aquí x² + 6x + 9 = x² + 2(x)(3) + 3² = (x + 3)².',
    explanationLatex: 'x^2 + 6x + 9 = x^2 + 2(x)(3) + 3^2 = (x + 3)^2',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-154',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '4x^2 - 12x + 9',
    question: 'Una fábrica produce paneles cuadrados para construcción. El área de cada panel está dada por la expresión 4x² - 12x + 9 metros cuadrados, donde x es un parámetro de diseño. El ingeniero de calidad necesita factorizar esta expresión para verificar que representa un cuadrado perfecto y calcular la longitud del lado del panel. ¿Cuál es la factorización correcta?',
    questionLatex: '\\text{Una fábrica produce paneles cuadrados para construcción. El área de cada panel está dada por la expresión } 4x^2 - 12x + 9 \\text{ metros cuadrados, donde x es un parámetro de diseño. El ingeniero de calidad necesita factorizar esta expresión para verificar que representa un cuadrado perfecto y calcular la longitud del lado del panel. ¿Cuál es la factorización correcta?}',
    options: ['$(2x - 3)^2$', '$(2x + 3)^2$', '$(4x - 3)^2$', '$(x - 3)^2$'],
    optionsLatex: ['(2x - 3)^2', '(2x + 3)^2', '(4x - 3)^2', '(x - 3)^2'],
    correctAnswer: 0,
    explanation: 'Es un trinomio cuadrado perfecto: 4x² - 12x + 9 = (2x)² - 2(2x)(3) + 3² = (2x - 3)². El lado del panel mide (2x - 3) metros.',
    explanationLatex: '4x^2 - 12x + 9 = (2x)^2 - 2(2x)(3) + 3^2 = (2x - 3)^2',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-155',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: 'x^2 + 4x + 4',
    question: 'Un arquitecto analiza cuatro diseños diferentes de pisos cuadrados para un proyecto habitacional. Las áreas propuestas son: x² + 4x + 4, x² + 4x + 2, x² + 2x + 4, y x² + 8x + 4 metros cuadrados. El arquitecto necesita identificar cuál de estas expresiones representa un trinomio cuadrado perfecto, es decir, el área de un cuadrado real. ¿Cuál expresión es un trinomio cuadrado perfecto?',
    questionLatex: '\\text{Un arquitecto analiza cuatro diseños diferentes de pisos cuadrados para un proyecto habitacional. Las áreas propuestas son: } x^2 + 4x + 4, x^2 + 4x + 2, x^2 + 2x + 4, \\text{ y } x^2 + 8x + 4 \\text{ metros cuadrados. El arquitecto necesita identificar cuál de estas expresiones representa un trinomio cuadrado perfecto, es decir, el área de un cuadrado real. ¿Cuál expresión es un trinomio cuadrado perfecto?}',
    options: ['$x^2 + 4x + 4$', '$x^2 + 4x + 2$', '$x^2 + 2x + 4$', '$x^2 + 8x + 4$'],
    optionsLatex: ['x^2 + 4x + 4', 'x^2 + 4x + 2', 'x^2 + 2x + 4', 'x^2 + 8x + 4'],
    correctAnswer: 0,
    explanation: 'Para ser trinomio cuadrado perfecto, el término constante debe ser el cuadrado de la mitad del coeficiente de x. En x² + 4x + 4: (4/2)² = 2² = 4 ✓. Factorización: x² + 4x + 4 = (x + 2)².',
    explanationLatex: 'x^2 + 4x + 4 = x^2 + 2(x)(2) + 2^2 = (x + 2)^2 \\text{ es TCP}',
    difficulty: 'hard',
    skills: ['algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-156',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: 'x^2 + 7x + 12',
    question: 'Una empresa de eventos organiza mesas rectangulares para una conferencia. El área de cada zona de mesas está representada por x² + 7x + 12 metros cuadrados, donde x es una medida base en metros. El coordinador necesita factorizar esta expresión para encontrar dos dimensiones enteras posibles que faciliten la distribución de las mesas. ¿Cuál es la factorización correcta?',
    questionLatex: '\\text{Una empresa de eventos organiza mesas rectangulares para una conferencia. El área de cada zona de mesas está representada por } x^2 + 7x + 12 \\text{ metros cuadrados, donde x es una medida base en metros. El coordinador necesita factorizar esta expresión para encontrar dos dimensiones enteras posibles que faciliten la distribución de las mesas. ¿Cuál es la factorización correcta?}',
    options: ['$(x + 3)(x + 4)$', '$(x + 2)(x + 6)$', '$(x + 1)(x + 12)$', '$(x + 3)(x + 5)$'],
    optionsLatex: ['(x + 3)(x + 4)', '(x + 2)(x + 6)', '(x + 1)(x + 12)', '(x + 3)(x + 5)'],
    correctAnswer: 0,
    explanation: 'Buscamos dos números que sumen 7 y multipliquen 12. Esos números son 3 y 4, ya que 3 + 4 = 7 y 3 × 4 = 12. Por lo tanto: x² + 7x + 12 = (x + 3)(x + 4).',
    explanationLatex: 'x^2 + 7x + 12 = (x + 3)(x + 4) \\quad \\text{porque } 3 + 4 = 7 \\text{ y } 3 \\times 4 = 12',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-157',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: 'x^2 - 5x + 6',
    question: 'Un programador optimiza el rendimiento de un algoritmo cuyo tiempo de ejecución está modelado por x² - 5x + 6 milisegundos, donde x es el tamaño de los datos de entrada. Para identificar los puntos críticos del algoritmo, necesita factorizar esta expresión cuadrática. ¿Cuál es la factorización correcta?',
    questionLatex: '\\text{Un programador optimiza el rendimiento de un algoritmo cuyo tiempo de ejecución está modelado por } x^2 - 5x + 6 \\text{ milisegundos, donde x es el tamaño de los datos de entrada. Para identificar los puntos críticos del algoritmo, necesita factorizar esta expresión cuadrática. ¿Cuál es la factorización correcta?}',
    options: ['$(x - 2)(x - 3)$', '$(x + 2)(x + 3)$', '$(x - 1)(x - 6)$', '$(x - 2)(x + 3)$'],
    optionsLatex: ['(x - 2)(x - 3)', '(x + 2)(x + 3)', '(x - 1)(x - 6)', '(x - 2)(x + 3)'],
    correctAnswer: 0,
    explanation: 'Buscamos dos números que sumen -5 y multipliquen 6. Esos números son -2 y -3, ya que (-2) + (-3) = -5 y (-2) × (-3) = 6. Por lo tanto: x² - 5x + 6 = (x - 2)(x - 3).',
    explanationLatex: 'x^2 - 5x + 6 = (x - 2)(x - 3) \\quad \\text{porque } (-2) + (-3) = -5 \\text{ y } (-2)(-3) = 6',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-158',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: 'x^2 + 2x - 15',
    question: 'Un biólogo modela el crecimiento poblacional de una colonia de bacterias usando la función x² + 2x - 15, donde x representa las horas transcurridas desde el inicio del experimento. Para analizar cuándo la población alcanza valores específicos, necesita factorizar esta expresión cuadrática. ¿Cuál es la factorización correcta?',
    questionLatex: '\\text{Un biólogo modela el crecimiento poblacional de una colonia de bacterias usando la función } x^2 + 2x - 15, \\text{ donde x representa las horas transcurridas desde el inicio del experimento. Para analizar cuándo la población alcanza valores específicos, necesita factorizar esta expresión cuadrática. ¿Cuál es la factorización correcta?}',
    options: ['$(x + 5)(x - 3)$', '$(x - 5)(x + 3)$', '$(x + 15)(x - 1)$', '$(x + 3)(x - 5)$'],
    optionsLatex: ['(x + 5)(x - 3)', '(x - 5)(x + 3)', '(x + 15)(x - 1)', '(x + 3)(x - 5)'],
    correctAnswer: 0,
    explanation: 'Buscamos dos números que sumen 2 y multipliquen -15. Esos números son 5 y -3, ya que 5 + (-3) = 2 y 5 × (-3) = -15. Por lo tanto: x² + 2x - 15 = (x + 5)(x - 3).',
    explanationLatex: 'x^2 + 2x - 15 = (x + 5)(x - 3) \\quad \\text{porque } 5 + (-3) = 2 \\text{ y } 5(-3) = -15',
    difficulty: 'hard',
    skills: ['algebra-factorizacion', 'numeros-enteros', 'numeros-operaciones-basicas']
  }
];
