import { Question } from '../../../types';

export const m1AlgebraFuncionesLinealesQuestions: Question[] = [
  {
    id: 'm1-2',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $f(x) = 2x + 3$, ¿cuál es el valor de $f(5)$?',
    questionLatex: '\\text{Si } f(x) = 2x + 3 \\text{, ¿cuál es el valor de } f(5)?',
    options: ['10', '11', '12', '13'],
    correctAnswer: 3,
    explanation: 'Sustituimos $x = 5$:',
    explanationLatex: 'f(5) = 2(5) + 3 = 10 + 3 = 13',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-evaluacion-funciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-15',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $y = 3x - 2$, ¿cuál es la pendiente de la recta?',
    questionLatex: '\\text{Si } y = 3x - 2 \\text{, ¿cuál es la pendiente de la recta?}',
    options: ['-2', '2', '3', '-3'],
    correctAnswer: 2,
    explanation: 'En la forma $y = mx + b$, $m$ es la pendiente:',
    explanationLatex: 'y = 3x - 2 \\quad \\Rightarrow \\quad m = 3',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-funciones-lineales', 'algebra-pendiente']
  },
  {
    id: 'm1-168',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál de las siguientes relaciones es una función?',
    questionLatex: '\\text{¿Cuál de las siguientes relaciones es una función?}',
    options: ['$\\{(1, 2), (1, 3), (2, 4)\\}$', '$\\{(1, 2), (2, 2), (3, 4)\\}$', '$\\{(1, 2), (2, 3), (1, 4)\\}$', '$\\{(1, 2), (1, 5), (3, 2)\\}$'],
    optionsLatex: ['\\{(1, 2), (1, 3), (2, 4)\\}', '\\{(1, 2), (2, 2), (3, 4)\\}', '\\{(1, 2), (2, 3), (1, 4)\\}', '\\{(1, 2), (1, 5), (3, 2)\\}'],
    correctAnswer: 1,
    explanation: 'Una función asigna exactamente un valor de salida a cada entrada. Solo la opción B cumple esta condición:',
    explanationLatex: '\\text{En una función, cada valor de } x \\text{ tiene exactamente un valor de } y. \\text{ Solo B cumple.}',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-relaciones-funciones']
  },
  {
    id: 'm1-169',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $f(x) = 3x - 4$, ¿cuál es el dominio de la función?',
    questionLatex: '\\text{Si } f(x) = 3x - 4, \\text{ ¿cuál es el dominio de la función?}',
    options: ['Todos los números reales', 'Solo números positivos', 'Solo números mayores que 4', 'Solo números enteros'],
    correctAnswer: 0,
    explanation: 'Una función lineal está definida para todos los números reales:',
    explanationLatex: '\\text{Dom}(f) = \\mathbb{R} \\text{ porque no hay restricciones para } x',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-dominio-rango', 'algebra-funciones-lineales']
  },
  {
    id: 'm1-171',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál de las siguientes funciones es una función lineal?',
    questionLatex: '\\text{¿Cuál de las siguientes funciones es una función lineal?}',
    options: ['$f(x) = x^2 + 1$', '$f(x) = 2x - 5$', '$f(x) = \\frac{1}{x}$', '$f(x) = 3$'],
    optionsLatex: ['f(x) = x^2 + 1', 'f(x) = 2x - 5', 'f(x) = \\frac{1}{x}', 'f(x) = 3'],
    correctAnswer: 1,
    explanation: 'Una función lineal tiene la forma $f(x) = mx + b$ donde $m \\neq 0$:',
    explanationLatex: 'f(x) = 2x - 5 \\text{ tiene la forma } mx + b \\text{ con } m = 2 \\text{ y } b = -5',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-funciones-lineales']
  },
  {
    id: 'm1-172',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Una función constante tiene la forma $f(x) = c$. ¿Cuál es el rango de $f(x) = 7$?',
    questionLatex: '\\text{Una función constante tiene la forma } f(x) = c. \\text{ ¿Cuál es el rango de } f(x) = 7?',
    options: ['$\\{7\\}$', 'Todos los números reales', '$\\{0, 7\\}$', '$\\{x : x \\geq 7\\}$'],
    optionsLatex: ['\\{7\\}', '\\text{Todos los números reales}', '\\{0, 7\\}', '\\{x : x \\geq 7\\}'],
    correctAnswer: 0,
    explanation: 'Una función constante siempre devuelve el mismo valor:',
    explanationLatex: '\\text{Para todo } x, f(x) = 7 \\quad \\Rightarrow \\quad \\text{Rango} = \\{7\\}',
    difficulty: 'medium',
    skills: ['algebra-funciones', 'algebra-dominio-rango', 'algebra-funciones-lineales']
  },
  {
    id: 'm1-174',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el dominio de $f(x) = \\frac{1}{x - 3}$?',
    questionLatex: '\\text{¿Cuál es el dominio de } f(x) = \\frac{1}{x - 3}?',
    options: ['Todos los reales excepto 3', 'Todos los reales excepto 0', 'Todos los reales mayores que 3', 'Todos los reales'],
    correctAnswer: 0,
    explanation: 'El denominador no puede ser cero, entonces $x - 3 \\neq 0$:',
    explanationLatex: 'x - 3 \\neq 0 \\quad \\Rightarrow \\quad x \\neq 3 \\quad \\therefore \\quad \\text{Dom}(f) = \\mathbb{R} - \\{3\\}',
    difficulty: 'medium',
    skills: ['algebra-funciones', 'algebra-dominio-rango', 'algebra-funciones-racionales']
  },
  {
    id: 'm1-175',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el dominio de $g(x) = \\sqrt{x - 2}$?',
    questionLatex: '\\text{¿Cuál es el dominio de } g(x) = \\sqrt{x - 2}?',
    options: ['$x \\geq 2$', '$x > 2$', '$x \\geq -2$', 'Todos los reales'],
    optionsLatex: ['x \\geq 2', 'x > 2', 'x \\geq -2', '\\text{Todos los reales}'],
    correctAnswer: 0,
    explanation: 'La raíz cuadrada solo está definida para valores no negativos:',
    explanationLatex: 'x - 2 \\geq 0 \\quad \\Rightarrow \\quad x \\geq 2 \\quad \\therefore \\quad \\text{Dom}(g) = [2, \\infty)',
    difficulty: 'hard',
    skills: ['algebra-funciones', 'algebra-dominio-rango', 'algebra-desigualdades', 'numeros-raices']
  },
  {
    id: 'm1-177',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el intercepto con el eje $y$ de la función $f(x) = 2x - 6$?',
    questionLatex: '\\text{¿Cuál es el intercepto con el eje } y \\text{ de la función } f(x) = 2x - 6?',
    options: ['-6', '-3', '2', '6'],
    correctAnswer: 0,
    explanation: 'El intercepto con el eje $y$ ocurre cuando $x = 0$:',
    explanationLatex: 'f(0) = 2(0) - 6 = -6 \\quad \\Rightarrow \\quad \\text{Intercepto en } (0, -6)',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-interceptos', 'algebra-funciones-lineales']
  },
  {
    id: 'm1-178',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el intercepto con el eje $x$ de la función $g(x) = 3x + 9$?',
    questionLatex: '\\text{¿Cuál es el intercepto con el eje } x \\text{ de la función } g(x) = 3x + 9?',
    options: ['-3', '3', '9', '-9'],
    correctAnswer: 0,
    explanation: 'El intercepto con el eje $x$ ocurre cuando $g(x) = 0$:',
    explanationLatex: '3x + 9 = 0 \\rightarrow 3x = -9 \\rightarrow x = -3 \\quad \\Rightarrow \\quad \\text{Intercepto en } (-3, 0)',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-interceptos', 'algebra-funciones-lineales', 'algebra-ecuaciones-lineales']
  },
  {
    id: 'm1-179',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Una recta tiene ecuación $y = -2x + 8$. ¿En qué punto la recta cruza el eje $x$?',
    questionLatex: '\\text{Una recta tiene ecuación } y = -2x + 8. \\text{ ¿En qué punto cruza el eje } x?',
    options: ['$(4, 0)$', '$(0, 8)$', '$(-4, 0)$', '$(8, 0)$'],
    optionsLatex: ['(4, 0)', '(0, 8)', '(-4, 0)', '(8, 0)'],
    correctAnswer: 0,
    explanation: 'Para encontrar el intercepto con $x$, hacemos $y = 0$:',
    explanationLatex: '0 = -2x + 8 \\rightarrow 2x = 8 \\rightarrow x = 4 \\quad \\Rightarrow \\quad (4, 0)',
    difficulty: 'medium',
    skills: ['algebra-funciones', 'algebra-interceptos', 'algebra-funciones-lineales', 'algebra-ecuaciones-lineales']
  },
  {
    id: 'm1-180',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si la gráfica de $f(x)$ pasa por el punto $(3, 7)$, ¿cuál es el valor de $f(3)$?',
    questionLatex: '\\text{Si la gráfica de } f(x) \\text{ pasa por el punto } (3, 7), \\text{ ¿cuál es el valor de } f(3)?',
    options: ['3', '7', '10', '21'],
    correctAnswer: 1,
    explanation: 'Si la gráfica pasa por $(a, b)$, entonces $f(a) = b$:',
    explanationLatex: '\\text{El punto } (3, 7) \\text{ significa que cuando } x = 3, y = 7 \\quad \\therefore \\quad f(3) = 7',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-evaluacion-funciones', 'algebra-graficas']
  },
  {
    id: 'm1-181',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Una función lineal tiene intercepto en $y$ igual a $5$ y pendiente $m = -1$. ¿Cuál es su ecuación?',
    questionLatex: '\\text{Una función lineal tiene intercepto en } y \\text{ igual a } 5 \\text{ y pendiente } m = -1. \\text{ ¿Cuál es su ecuación?}',
    options: ['$y = -x + 5$', '$y = x + 5$', '$y = -x - 5$', '$y = 5x - 1$'],
    optionsLatex: ['y = -x + 5', 'y = x + 5', 'y = -x - 5', 'y = 5x - 1'],
    correctAnswer: 0,
    explanation: 'Usamos la forma $y = mx + b$ donde $m$ es la pendiente y $b$ el intercepto en $y$:',
    explanationLatex: 'y = mx + b = -1 \\cdot x + 5 = -x + 5',
    difficulty: 'medium',
    skills: ['algebra-funciones', 'algebra-funciones-lineales', 'algebra-pendiente', 'algebra-interceptos']
  },
  {
    id: 'm1-182',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si la pendiente de una recta que pasa por los puntos $(2, 5)$ y $(4, 9)$ es $m$, ¿cuál es el valor de $m$?',
    questionLatex: '\\text{Si la pendiente de una recta que pasa por } (2, 5) \\text{ y } (4, 9) \\text{ es } m, \\text{ ¿cuál es } m?',
    options: ['1', '2', '3', '4'],
    correctAnswer: 1,
    explanation: 'La pendiente se calcula con $m = \\frac{y_2 - y_1}{x_2 - x_1}$:',
    explanationLatex: 'm = \\frac{9 - 5}{4 - 2} = \\frac{4}{2} = 2',
    difficulty: 'hard',
    skills: ['algebra-funciones', 'algebra-funciones-lineales', 'algebra-pendiente', 'numeros-fracciones', 'numeros-operaciones-basicas']
  }
];
