import { Question } from '../../../types';

export const m1AlgebraFuncionesCuadraticasQuestions: Question[] = [
  {
    id: 'm1-32',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $f(x) = x^2 - 1$, ¿cuál es $f(3)$?',
    questionLatex: '\\text{Si } f(x) = x^2 - 1 \\text{, ¿cuál es } f(3)?',
    options: ['6', '7', '8', '9'],
    correctAnswer: 2,
    explanation: 'Sustituimos x por 3:',
    explanationLatex: 'f(3) = 3^2 - 1 = 9 - 1 = 8',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-evaluacion-funciones', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-170',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $g(x) = x^2$ y el dominio es $\\{-2, -1, 0, 1, 2\\}$, ¿cuál es el rango?',
    questionLatex: '\\text{Si } g(x) = x^2 \\text{ y el dominio es } \\{-2, -1, 0, 1, 2\\}, \\text{ ¿cuál es el rango?}',
    options: ['$\\{0, 1, 2, 4\\}$', '$\\{-2, -1, 0, 1, 2\\}$', '$\\{0, 1, 4\\}$', '$\\{1, 2, 4\\}$'],
    optionsLatex: ['\\{0, 1, 2, 4\\}', '\\{-2, -1, 0, 1, 2\\}', '\\{0, 1, 4\\}', '\\{1, 2, 4\\}'],
    correctAnswer: 0,
    explanation: 'Evaluamos la función para cada valor del dominio:',
    explanationLatex: 'g(-2) = 4, g(-1) = 1, g(0) = 0, g(1) = 1, g(2) = 4 \\quad \\Rightarrow \\quad \\text{Rango} = \\{0, 1, 4\\}',
    difficulty: 'medium',
    skills: ['algebra-funciones', 'algebra-dominio-rango', 'algebra-evaluacion-funciones', 'numeros-potencias']
  },
  {
    id: 'm1-173',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Carlos estudia una función $h(x) = ax^2 + bx + c$ donde $a \\neq 0$. ¿Qué tipo de función es?',
    questionLatex: '\\text{Carlos estudia } h(x) = ax^2 + bx + c \\text{ donde } a \\neq 0. \\text{ ¿Qué tipo de función es?}',
    options: ['Función lineal', 'Función cuadrática', 'Función constante', 'Función exponencial'],
    correctAnswer: 1,
    explanation: 'La forma $ax^2 + bx + c$ con $a \\neq 0$ define una función cuadrática:',
    explanationLatex: 'h(x) = ax^2 + bx + c \\text{ es cuadrática porque el término de mayor grado es } x^2',
    difficulty: 'medium',
    skills: ['algebra-funciones', 'algebra-funciones-cuadraticas']
  },
  {
    id: 'm1-176',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $f(x) = -x^2 + 4$, ¿cuál es el valor máximo de la función (el mayor valor del rango)?',
    questionLatex: '\\text{Si } f(x) = -x^2 + 4, \\text{ ¿cuál es el valor máximo de la función?}',
    options: ['0', '2', '4', 'No tiene máximo'],
    correctAnswer: 2,
    explanation: 'La función es una parábola que abre hacia abajo. El máximo ocurre cuando $x = 0$:',
    explanationLatex: 'f(0) = -(0)^2 + 4 = 4 \\text{ es el valor máximo porque } -x^2 \\leq 0 \\text{ para todo } x',
    difficulty: 'hard',
    skills: ['algebra-funciones', 'algebra-dominio-rango', 'algebra-funciones-cuadraticas', 'numeros-potencias']
  },
  {
    id: 'm1-192',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver la ecuación: $x^2 - 5x + 6 = 0$',
    questionLatex: '\\text{Resolver la ecuación: } x^2 - 5x + 6 = 0',
    options: ['$x = 2$ o $x = 3$', '$x = 1$ o $x = 6$', '$x = -2$ o $x = -3$', '$x = 5$ o $x = 6$'],
    optionsLatex: ['x = 2 \\text{ o } x = 3', 'x = 1 \\text{ o } x = 6', 'x = -2 \\text{ o } x = -3', 'x = 5 \\text{ o } x = 6'],
    correctAnswer: 0,
    explanation: 'Factorizamos y usamos la propiedad del producto cero:',
    explanationLatex: 'x^2 - 5x + 6 = (x - 2)(x - 3) = 0 \\quad \\Rightarrow \\quad x = 2 \\text{ o } x = 3',
    difficulty: 'easy',
    skills: ['algebra-ecuaciones-cuadraticas', 'algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-193',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $x^2 + 7x + 10 = 0$',
    questionLatex: '\\text{Resolver: } x^2 + 7x + 10 = 0',
    options: ['$x = -2$ o $x = -5$', '$x = 2$ o $x = 5$', '$x = -1$ o $x = -10$', '$x = 1$ o $x = 10$'],
    optionsLatex: ['x = -2 \\text{ o } x = -5', 'x = 2 \\text{ o } x = 5', 'x = -1 \\text{ o } x = -10', 'x = 1 \\text{ o } x = 10'],
    correctAnswer: 0,
    explanation: 'Factorizamos y encontramos las raíces:',
    explanationLatex: 'x^2 + 7x + 10 = (x + 2)(x + 5) = 0 \\quad \\Rightarrow \\quad x = -2 \\text{ o } x = -5',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-cuadraticas', 'algebra-factorizacion', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-194',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $x^2 - 9 = 0$',
    questionLatex: '\\text{Resolver: } x^2 - 9 = 0',
    options: ['$x = 3$ o $x = -3$', '$x = 9$ o $x = -9$', '$x = 3$ solamente', '$x = 9$ solamente'],
    optionsLatex: ['x = 3 \\text{ o } x = -3', 'x = 9 \\text{ o } x = -9', 'x = 3 \\text{ solamente}', 'x = 9 \\text{ solamente}'],
    correctAnswer: 0,
    explanation: 'Es una diferencia de cuadrados:',
    explanationLatex: 'x^2 - 9 = (x - 3)(x + 3) = 0 \\quad \\Rightarrow \\quad x = 3 \\text{ o } x = -3',
    difficulty: 'easy',
    skills: ['algebra-ecuaciones-cuadraticas', 'algebra-factorizacion', 'algebra-diferencia-cuadrados', 'numeros-raices']
  },
  {
    id: 'm1-195',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Usar la fórmula cuadrática para resolver: $x^2 + 2x - 3 = 0$',
    questionLatex: '\\text{Usar la fórmula cuadrática para resolver: } x^2 + 2x - 3 = 0',
    options: ['$x = 1$ o $x = -3$', '$x = -1$ o $x = 3$', '$x = 2$ o $x = -3$', '$x = -2$ o $x = 3$'],
    optionsLatex: ['x = 1 \\text{ o } x = -3', 'x = -1 \\text{ o } x = 3', 'x = 2 \\text{ o } x = -3', 'x = -2 \\text{ o } x = 3'],
    correctAnswer: 0,
    explanation: 'Aplicamos $x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}$ con $a=1, b=2, c=-3$:',
    explanationLatex: 'x = \\frac{-2 \\pm \\sqrt{4 + 12}}{2} = \\frac{-2 \\pm 4}{2} \\quad \\Rightarrow \\quad x = 1 \\text{ o } x = -3',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-cuadraticas', 'algebra-formula-cuadratica', 'numeros-raices', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-196',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el discriminante de $x^2 - 4x + 4 = 0$?',
    questionLatex: '\\text{¿Cuál es el discriminante de } x^2 - 4x + 4 = 0?',
    options: ['0', '4', '8', '16'],
    correctAnswer: 0,
    explanation: 'El discriminante es $\\Delta = b^2 - 4ac$:',
    explanationLatex: '\\Delta = (-4)^2 - 4(1)(4) = 16 - 16 = 0 \\text{ (una raíz doble)}',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-cuadraticas', 'algebra-discriminante', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-197',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si el discriminante de una ecuación cuadrática es negativo, ¿qué podemos concluir sobre sus soluciones?',
    questionLatex: '\\text{Si el discriminante de una ecuación cuadrática es negativo, ¿qué podemos concluir?}',
    options: ['No tiene soluciones reales', 'Tiene dos soluciones reales distintas', 'Tiene una solución real', 'Tiene infinitas soluciones'],
    correctAnswer: 0,
    explanation: 'Un discriminante negativo indica que no hay raíces reales:',
    explanationLatex: '\\Delta < 0 \\quad \\Rightarrow \\quad \\text{No existen soluciones reales (las soluciones son complejas)}',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-cuadraticas', 'algebra-discriminante']
  },
  {
    id: 'm1-198',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'La ecuación $h(t) = -5t^2 + 20t$ representa la altura de un objeto. ¿En qué tiempos $t$ el objeto está en el suelo ($h = 0$)?',
    questionLatex: '\\text{La ecuación } h(t) = -5t^2 + 20t \\text{ representa la altura. ¿Cuándo } h = 0?',
    options: ['$t = 0$ o $t = 4$', '$t = 0$ o $t = 5$', '$t = 2$ o $t = 4$', '$t = 1$ o $t = 4$'],
    optionsLatex: ['t = 0 \\text{ o } t = 4', 't = 0 \\text{ o } t = 5', 't = 2 \\text{ o } t = 4', 't = 1 \\text{ o } t = 4'],
    correctAnswer: 0,
    explanation: 'Resolvemos $-5t^2 + 20t = 0$:',
    explanationLatex: '-5t(t - 4) = 0 \\quad \\Rightarrow \\quad t = 0 \\text{ (lanzamiento) o } t = 4 \\text{ (aterrizaje)}',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-cuadraticas', 'algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-199',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'El área de un rectángulo es 24 m². Si el largo es $x + 2$ y el ancho es $x$, ¿cuál es el valor de $x$?',
    questionLatex: '\\text{Área = 24 m}^2. \\text{ Largo = } x + 2, \\text{ ancho = } x. \\text{ ¿Cuál es } x?',
    options: ['4 m', '5 m', '6 m', '8 m'],
    correctAnswer: 0,
    explanation: 'Planteamos $x(x + 2) = 24$:',
    explanationLatex: 'x^2 + 2x = 24 \\rightarrow x^2 + 2x - 24 = 0 \\rightarrow (x + 6)(x - 4) = 0 \\quad \\Rightarrow \\quad x = 4 \\text{ (positivo)}',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-cuadraticas', 'algebra-factorizacion', 'geometria-area', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-200',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'La parábola $y = x^2 - 6x + 8$ cruza el eje $x$ en dos puntos. ¿Cuáles son las coordenadas de esos puntos?',
    questionLatex: '\\text{La parábola } y = x^2 - 6x + 8 \\text{ cruza el eje } x \\text{ en dos puntos. ¿Cuáles son?}',
    options: ['$(2, 0)$ y $(4, 0)$', '$(1, 0)$ y $(8, 0)$', '$(-2, 0)$ y $(-4, 0)$', '$(3, 0)$ y $(6, 0)$'],
    optionsLatex: ['(2, 0) \\text{ y } (4, 0)', '(1, 0) \\text{ y } (8, 0)', '(-2, 0) \\text{ y } (-4, 0)', '(3, 0) \\text{ y } (6, 0)'],
    correctAnswer: 0,
    explanation: 'Resolvemos $x^2 - 6x + 8 = 0$ para encontrar los interceptos con $x$:',
    explanationLatex: 'x^2 - 6x + 8 = (x - 2)(x - 4) = 0 \\quad \\Rightarrow \\quad x = 2 \\text{ o } x = 4',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-cuadraticas', 'algebra-factorizacion', 'algebra-funciones-cuadraticas', 'algebra-interceptos', 'numeros-operaciones-basicas']
  }
];
