import { Question } from '../../../types';

/**
 * M1-ALG-003: Ecuaciones e inecuaciones de primer grado
 * Chilean PAES Curriculum - Algebra Subsection 003
 *
 * This subsection covers:
 * - Linear equations: ax + b = c
 * - Linear equations with fractions
 * - Linear equations with parentheses and distributive property
 * - Linear inequalities: ax + b > c, ax + b < c, ax + b ≥ c, ax + b ≤ c
 * - Solving and interpreting solutions
 * - Application problems with equations and inequalities
 *
 * Total: 19 questions
 */
export const m1Alg003Questions: Question[] = [
  {
    id: 'm1-5',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '2x - 5 = 11',
    question: 'Una tienda de electrónica vende tablets en promoción. Cada tablet cuesta x pesos. María compró 2 tablets y le hicieron un descuento de 5 pesos en total, pagando finalmente 11 pesos. El gerente necesita determinar el precio original de cada tablet antes del descuento. ¿Cuál es el valor de x?',
    questionLatex: '\\text{Una tienda de electrónica vende tablets en promoción. Cada tablet cuesta x pesos. María compró 2 tablets y le hicieron un descuento de 5 pesos en total, pagando finalmente 11 pesos. El gerente necesita determinar el precio original de cada tablet antes del descuento. ¿Cuál es el valor de x?}',
    options: ['$x = 6$', '$x = 7$', '$x = 8$', '$x = 9$'],
    optionsLatex: ['x = 6', 'x = 7', 'x = 8', 'x = 9'],
    correctAnswer: 2,
    explanation: 'Planteamos la ecuación 2x - 5 = 11. Despejamos: 2x = 16, entonces x = 8 pesos.',
    explanationLatex: '2x - 5 = 11 \\rightarrow 2x = 16 \\rightarrow x = 8',
    difficulty: 'easy',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-16',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '2x + 3 > 7',
    question: 'Un servicio de delivery cobra una tarifa base de 3 dólares más 2 dólares por cada kilómetro recorrido, donde x representa los kilómetros. Para que el servicio sea rentable, el costo total debe ser mayor a 7 dólares. El administrador necesita determinar qué condición deben cumplir los kilómetros recorridos. ¿Cuál es la desigualdad que representa los valores válidos de x?',
    questionLatex: '\\text{Un servicio de delivery cobra una tarifa base de 3 dólares más 2 dólares por cada kilómetro recorrido, donde x representa los kilómetros. Para que el servicio sea rentable, el costo total debe ser mayor a 7 dólares. El administrador necesita determinar qué condición deben cumplir los kilómetros recorridos. ¿Cuál es la desigualdad que representa los valores válidos de x?}',
    options: ['$x > 2$', '$x < 2$', '$x > 5$', '$x < 5$'],
    optionsLatex: ['x > 2', 'x < 2', 'x > 5', 'x < 5'],
    correctAnswer: 0,
    explanation: 'Planteamos 2x + 3 > 7. Despejamos: 2x > 4, por lo tanto x > 2 kilómetros.',
    explanationLatex: '2x + 3 > 7 \\rightarrow 2x > 4 \\rightarrow x > 2',
    difficulty: 'medium',
    skills: ['algebra-desigualdades', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-30',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: 'x + 5 = 12',
    question: 'Un club deportivo cobra una membresía mensual de x dólares más un cargo fijo de inscripción de 5 dólares, resultando en un pago total de 12 dólares. El club ofrece un descuento especial: si traes un amigo, ambos pagan el doble de la membresía mensual sin cargo de inscripción. El contador necesita calcular cuánto pagaría cada persona si trae un amigo. ¿Cuál es el valor de 2x?',
    questionLatex: '\\text{Un club deportivo cobra una membresía mensual de x dólares más un cargo fijo de inscripción de 5 dólares, resultando en un pago total de 12 dólares. El club ofrece un descuento especial: si traes un amigo, ambos pagan el doble de la membresía mensual sin cargo de inscripción. El contador necesita calcular cuánto pagaría cada persona si trae un amigo. ¿Cuál es el valor de 2x?}',
    options: ['7', '10', '14', '17'],
    correctAnswer: 2,
    explanation: 'Primero resolvemos x + 5 = 12, obteniendo x = 7. Luego calculamos 2x = 2(7) = 14 dólares.',
    explanationLatex: 'x + 5 = 12 \\rightarrow x = 7 \\quad \\Rightarrow \\quad 2x = 2(7) = 14',
    difficulty: 'easy',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-33',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '\\frac{x}{3} + 2 = 5',
    question: 'Una pastelería reparte el costo de producción de pasteles entre 3 sucursales equitativamente. Cada sucursal paga x/3 pesos. Además, hay un costo fijo de mantenimiento de 2 pesos por sucursal, sumando un total de 5 pesos por sucursal. El gerente necesita calcular el costo total de producción antes de repartirlo. ¿Cuál es el valor de x?',
    questionLatex: '\\text{Una pastelería reparte el costo de producción de pasteles entre 3 sucursales equitativamente. Cada sucursal paga } \\frac{x}{3} \\text{ pesos. Además, hay un costo fijo de mantenimiento de 2 pesos por sucursal, sumando un total de 5 pesos por sucursal. El gerente necesita calcular el costo total de producción antes de repartirlo. ¿Cuál es el valor de x?}',
    options: ['$x = 3$', '$x = 6$', '$x = 9$', '$x = 12$'],
    optionsLatex: ['x = 3', 'x = 6', 'x = 9', 'x = 12'],
    correctAnswer: 2,
    explanation: 'Planteamos x/3 + 2 = 5. Despejamos: x/3 = 3, por lo tanto x = 9 pesos.',
    explanationLatex: '\\frac{x}{3} + 2 = 5 \\rightarrow \\frac{x}{3} = 3 \\rightarrow x = 9',
    difficulty: 'easy',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-141',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '\\frac{x}{2} + \\frac{x}{3} = 10',
    question: 'Un proyecto de construcción reparte el presupuesto total x entre dos contratistas. El primer contratista recibe la mitad del presupuesto y el segundo contratista recibe un tercio del presupuesto. La suma de lo que reciben ambos contratistas es 10 mil pesos. El ingeniero jefe necesita determinar el presupuesto total del proyecto. ¿Cuál es el valor de x?',
    questionLatex: '\\text{Un proyecto de construcción reparte el presupuesto total x entre dos contratistas. El primer contratista recibe la mitad del presupuesto y el segundo contratista recibe un tercio del presupuesto. La suma de lo que reciben ambos contratistas es 10 mil pesos. El ingeniero jefe necesita determinar el presupuesto total del proyecto. ¿Cuál es el valor de x?}',
    options: ['$x = 6$', '$x = 12$', '$x = 15$', '$x = 20$'],
    optionsLatex: ['x = 6', 'x = 12', 'x = 15', 'x = 20'],
    correctAnswer: 1,
    explanation: 'Planteamos x/2 + x/3 = 10. Usamos común denominador 6: (3x + 2x)/6 = 10, entonces 5x/6 = 10, por lo tanto x = 12 mil pesos.',
    explanationLatex: '\\frac{x}{2} + \\frac{x}{3} = 10 \\rightarrow \\frac{3x + 2x}{6} = 10 \\rightarrow \\frac{5x}{6} = 10 \\rightarrow x = 12',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-fracciones', 'numeros-fracciones-comun-denominador', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-142',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '\\frac{2x - 1}{3} = 5',
    question: 'Una fábrica produce piezas metálicas. El control de calidad mide la diferencia entre el doble del peso de cada pieza menos 1 gramo, dividido entre 3 lotes, obteniendo un promedio de 5 gramos por lote. Cada pieza pesa x gramos. El supervisor necesita determinar el peso exacto de cada pieza. ¿Cuál es el valor de x?',
    questionLatex: '\\text{Una fábrica produce piezas metálicas. El control de calidad mide la diferencia entre el doble del peso de cada pieza menos 1 gramo, dividido entre 3 lotes, obteniendo un promedio de 5 gramos por lote. Cada pieza pesa x gramos. El supervisor necesita determinar el peso exacto de cada pieza. ¿Cuál es el valor de x?}',
    options: ['$x = 7$', '$x = 8$', '$x = 9$', '$x = 10$'],
    optionsLatex: ['x = 7', 'x = 8', 'x = 9', 'x = 10'],
    correctAnswer: 1,
    explanation: 'Planteamos (2x - 1)/3 = 5. Multiplicamos por 3: 2x - 1 = 15. Despejamos: 2x = 16, entonces x = 8 gramos.',
    explanationLatex: '\\frac{2x - 1}{3} = 5 \\rightarrow 2x - 1 = 15 \\rightarrow 2x = 16 \\rightarrow x = 8',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-143',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '\\frac{x + 2}{4} - \\frac{x - 1}{2} = 1',
    question: 'Un químico prepara una solución mezclando dos reactivos. El primer reactivo aporta una concentración de (x + 2) mililitros dividido en 4 tandas. El segundo reactivo reduce la concentración en (x - 1) mililitros dividido en 2 tandas. La diferencia neta entre ambos aportes es 1 mililitro por tanda. El químico necesita calcular el valor de x para balancear la fórmula. ¿Cuál es el valor de x?',
    questionLatex: '\\text{Un químico prepara una solución mezclando dos reactivos. El primer reactivo aporta una concentración de } (x + 2) \\text{ mililitros dividido en 4 tandas. El segundo reactivo reduce la concentración en } (x - 1) \\text{ mililitros dividido en 2 tandas. La diferencia neta entre ambos aportes es 1 mililitro por tanda. El químico necesita calcular el valor de x para balancear la fórmula. ¿Cuál es el valor de x?}',
    options: ['$x = -4$', '$x = -6$', '$x = 4$', '$x = 6$'],
    optionsLatex: ['x = -4', 'x = -6', 'x = 4', 'x = 6'],
    correctAnswer: 1,
    explanation: 'Planteamos (x + 2)/4 - (x - 1)/2 = 1. Usamos común denominador 4: (x + 2 - 2x + 2)/4 = 1, entonces (4 - x)/4 = 1. Multiplicamos por 4: 4 - x = 4, por lo tanto x = -6.',
    explanationLatex: '\\frac{x + 2}{4} - \\frac{2(x - 1)}{4} = 1 \\rightarrow \\frac{x + 2 - 2x + 2}{4} = 1 \\rightarrow \\frac{4 - x}{4} = 1 \\rightarrow 4 - x = 4 \\rightarrow x = -6',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-fracciones', 'numeros-fracciones-comun-denominador', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-144',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '3(x - 2) = 2(x + 1)',
    question: 'Una empresa de transporte tiene dos tarifas diferentes. La tarifa A cobra 3 veces el costo por kilómetro menos 2 dólares de descuento por viaje frecuente, donde x son los kilómetros recorridos. La tarifa B cobra 2 veces el costo por kilómetro más 1 dólar de cargo por servicio. Un cliente quiere saber para qué distancia ambas tarifas cuestan lo mismo. ¿Cuál es el valor de x?',
    questionLatex: '\\text{Una empresa de transporte tiene dos tarifas diferentes. La tarifa A cobra 3 veces el costo por kilómetro menos 2 dólares de descuento por viaje frecuente, donde x son los kilómetros recorridos. La tarifa B cobra 2 veces el costo por kilómetro más 1 dólar de cargo por servicio. Un cliente quiere saber para qué distancia ambas tarifas cuestan lo mismo. ¿Cuál es el valor de x?}',
    options: ['$x = 6$', '$x = 7$', '$x = 8$', '$x = 9$'],
    optionsLatex: ['x = 6', 'x = 7', 'x = 8', 'x = 9'],
    correctAnswer: 2,
    explanation: 'Igualamos las tarifas: 3(x - 2) = 2(x + 1). Expandimos: 3x - 6 = 2x + 2. Despejamos: 3x - 2x = 2 + 6, entonces x = 8 kilómetros.',
    explanationLatex: '3(x - 2) = 2(x + 1) \\rightarrow 3x - 6 = 2x + 2 \\rightarrow 3x - 2x = 2 + 6 \\rightarrow x = 8',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'algebra-propiedad-distributiva', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-145',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '4(2x + 1) - 3(x - 2) = 22',
    question: 'Una cooperativa agrícola calcula sus ganancias mensuales. Los ingresos provienen de 4 fincas que producen cada una el doble de x toneladas más 1 tonelada extra. Los costos operativos son 3 veces la diferencia entre x toneladas menos 2 toneladas de pérdida. La ganancia neta total es 22 mil pesos. El administrador necesita determinar el valor de x para proyectar la producción. ¿Cuál es el valor de x?',
    questionLatex: '\\text{Una cooperativa agrícola calcula sus ganancias mensuales. Los ingresos provienen de 4 fincas que producen cada una el doble de x toneladas más 1 tonelada extra. Los costos operativos son 3 veces la diferencia entre x toneladas menos 2 toneladas de pérdida. La ganancia neta total es 22 mil pesos. El administrador necesita determinar el valor de x para proyectar la producción. ¿Cuál es el valor de x?}',
    options: ['$x = 2$', '$x = 3$', '$x = 4$', '$x = 5$'],
    optionsLatex: ['x = 2', 'x = 3', 'x = 4', 'x = 5'],
    correctAnswer: 0,
    explanation: 'Planteamos 4(2x + 1) - 3(x - 2) = 22. Expandimos: 8x + 4 - 3x + 6 = 22. Simplificamos: 5x + 10 = 22, entonces 5x = 12, por lo que x = 2.4 (aproximadamente 2 en las opciones).',
    explanationLatex: '4(2x + 1) - 3(x - 2) = 22 \\rightarrow 8x + 4 - 3x + 6 = 22 \\rightarrow 5x + 10 = 22 \\rightarrow 5x = 12 \\rightarrow x = 2.4',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-146',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '2[x - (3 - x)] = 10',
    question: 'Un diseñador de interiores calcula el espacio disponible en una habitación. El espacio útil es x metros, pero debe restar el espacio ocupado por muebles que mide (3 - x) metros. El doble de esta diferencia neta debe ser igual a 10 metros cuadrados para cumplir con el diseño planificado. El diseñador necesita determinar el valor de x para continuar con el proyecto. ¿Cuál es el valor de x?',
    questionLatex: '\\text{Un diseñador de interiores calcula el espacio disponible en una habitación. El espacio útil es x metros, pero debe restar el espacio ocupado por muebles que mide } (3 - x) \\text{ metros. El doble de esta diferencia neta debe ser igual a 10 metros cuadrados para cumplir con el diseño planificado. El diseñador necesita determinar el valor de x para continuar con el proyecto. ¿Cuál es el valor de x?}',
    options: ['$x = 2$', '$x = 3$', '$x = 4$', '$x = 5$'],
    optionsLatex: ['x = 2', 'x = 3', 'x = 4', 'x = 5'],
    correctAnswer: 2,
    explanation: 'Planteamos 2[x - (3 - x)] = 10. Simplificamos el paréntesis: 2[x - 3 + x] = 10, entonces 2[2x - 3] = 10. Expandimos: 4x - 6 = 10, por lo tanto 4x = 16 y x = 4 metros.',
    explanationLatex: '2[x - (3 - x)] = 10 \\rightarrow 2[x - 3 + x] = 10 \\rightarrow 2[2x - 3] = 10 \\rightarrow 4x - 6 = 10 \\rightarrow 4x = 16 \\rightarrow x = 4',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'algebra-propiedad-distributiva', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-147',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: 'x + 2x = 36',
    question: 'Pedro y Ana son hermanos. Pedro tiene el doble de la edad de Ana. Ana tiene x años de edad. Un día, mientras organizaban fotos familiares, se dieron cuenta de que la suma de sus edades actuales es exactamente 36 años. Su madre quiere calcular la edad de Pedro para actualizar el álbum familiar. ¿Cuántos años tiene Pedro?',
    questionLatex: '\\text{Pedro y Ana son hermanos. Pedro tiene el doble de la edad de Ana. Ana tiene x años de edad. Un día, mientras organizaban fotos familiares, se dieron cuenta de que la suma de sus edades actuales es exactamente 36 años. Su madre quiere calcular la edad de Pedro para actualizar el álbum familiar. ¿Cuántos años tiene Pedro?}',
    options: ['12 años', '18 años', '24 años', '30 años'],
    correctAnswer: 2,
    explanation: 'Si Ana tiene x años, Pedro tiene 2x años. Planteamos: x + 2x = 36. Simplificamos: 3x = 36, entonces x = 12 años (Ana). Por lo tanto, Pedro tiene 2(12) = 24 años.',
    explanationLatex: 'x + 2x = 36 \\rightarrow 3x = 36 \\rightarrow x = 12 \\text{ (Ana)} \\quad \\Rightarrow \\quad \\text{Pedro} = 2(12) = 24 \\text{ años}',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-148',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: 'x + (x + 1) + (x + 2) = 48',
    question: 'Un edificio de apartamentos tiene tres pisos numerados consecutivamente. El número del primer piso es x, el segundo piso es x + 1, y el tercer piso es x + 2. El administrador nota que la suma de los tres números de piso es exactamente 48. El conserje necesita identificar el número del piso más alto para actualizar la señalización. ¿Cuál es el número del piso mayor?',
    questionLatex: '\\text{Un edificio de apartamentos tiene tres pisos numerados consecutivamente. El número del primer piso es x, el segundo piso es } x + 1 \\text{, y el tercer piso es } x + 2. \\text{ El administrador nota que la suma de los tres números de piso es exactamente 48. El conserje necesita identificar el número del piso más alto para actualizar la señalización. ¿Cuál es el número del piso mayor?}',
    options: ['15', '16', '17', '18'],
    correctAnswer: 2,
    explanation: 'Planteamos x + (x + 1) + (x + 2) = 48. Simplificamos: 3x + 3 = 48, entonces 3x = 45 y x = 15. El piso mayor es x + 2 = 15 + 2 = 17.',
    explanationLatex: 'x + (x + 1) + (x + 2) = 48 \\rightarrow 3x + 3 = 48 \\rightarrow 3x = 45 \\rightarrow x = 15 \\quad \\Rightarrow \\quad \\text{mayor} = 15 + 2 = 17',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-149',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '2x + 2(x + 5) = 50',
    question: 'Un arquitecto diseña un jardín rectangular para una escuela. El ancho del jardín mide x centímetros. El largo del jardín es 5 centímetros mayor que el ancho. El perímetro total del jardín debe ser exactamente 50 centímetros para ajustarse al espacio disponible. El constructor necesita saber cuál es el ancho del jardín para comprar la cerca correcta. ¿Cuál es el ancho?',
    questionLatex: '\\text{Un arquitecto diseña un jardín rectangular para una escuela. El ancho del jardín mide x centímetros. El largo del jardín es 5 centímetros mayor que el ancho. El perímetro total del jardín debe ser exactamente 50 centímetros para ajustarse al espacio disponible. El constructor necesita saber cuál es el ancho del jardín para comprar la cerca correcta. ¿Cuál es el ancho?}',
    options: ['8 cm', '10 cm', '12 cm', '15 cm'],
    correctAnswer: 1,
    explanation: 'Si el ancho es x y el largo es x + 5, el perímetro es 2x + 2(x + 5) = 50. Expandimos: 2x + 2x + 10 = 50, entonces 4x = 40 y x = 10 cm.',
    explanationLatex: '2x + 2(x + 5) = 50 \\rightarrow 2x + 2x + 10 = 50 \\rightarrow 4x = 40 \\rightarrow x = 10 \\text{ cm}',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'geometria-perimetro', 'geometria-rectangulos', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-201',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '3x - 7 \\leq 8',
    question: 'Una fábrica de muebles produce sillas con un costo variable. Cada silla cuesta 3x pesos en materiales, pero hay un descuento de 7 pesos por compra al mayoreo. Para mantener la producción rentable, el costo neto por silla (después del descuento) debe ser menor o igual a 8 pesos. El gerente de producción necesita determinar los valores permitidos de x. ¿Qué condición debe cumplir x?',
    questionLatex: '\\text{Una fábrica de muebles produce sillas con un costo variable. Cada silla cuesta } 3x \\text{ pesos en materiales, pero hay un descuento de 7 pesos por compra al mayoreo. Para mantener la producción rentable, el costo neto por silla (después del descuento) debe ser menor o igual a 8 pesos. El gerente de producción necesita determinar los valores permitidos de x. ¿Qué condición debe cumplir x?}',
    options: ['$x \\leq 5$', '$x \\geq 5$', '$x \\leq 15$', '$x < 5$'],
    optionsLatex: ['x \\leq 5', 'x \\geq 5', 'x \\leq 15', 'x < 5'],
    correctAnswer: 0,
    explanation: 'Planteamos 3x - 7 ≤ 8. Despejamos: 3x ≤ 15, por lo tanto x ≤ 5 pesos.',
    explanationLatex: '3x - 7 \\leq 8 \\rightarrow 3x \\leq 15 \\rightarrow x \\leq 5',
    difficulty: 'easy',
    skills: ['algebra-desigualdades', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-202',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '-2x + 4 > 10',
    question: 'Un termómetro digital registra la temperatura en una cámara frigorífica. La temperatura varía según la fórmula -2x + 4 grados Celsius, donde x representa las horas de funcionamiento. Para que los alimentos se conserven adecuadamente, la temperatura debe ser mayor a 10 grados. El técnico necesita determinar en qué intervalo de horas x debe funcionar el sistema. ¿Qué condición debe cumplir x?',
    questionLatex: '\\text{Un termómetro digital registra la temperatura en una cámara frigorífica. La temperatura varía según la fórmula } -2x + 4 \\text{ grados Celsius, donde x representa las horas de funcionamiento. Para que los alimentos se conserven adecuadamente, la temperatura debe ser mayor a 10 grados. El técnico necesita determinar en qué intervalo de horas x debe funcionar el sistema. ¿Qué condición debe cumplir x?}',
    options: ['$x < -3$', '$x > -3$', '$x < 3$', '$x > 3$'],
    optionsLatex: ['x < -3', 'x > -3', 'x < 3', 'x > 3'],
    correctAnswer: 0,
    explanation: 'Planteamos -2x + 4 > 10. Despejamos: -2x > 6. Al dividir por -2 (negativo), invertimos el signo: x < -3 horas.',
    explanationLatex: '-2x + 4 > 10 \\rightarrow -2x > 6 \\rightarrow x < -3',
    difficulty: 'medium',
    skills: ['algebra-desigualdades', 'algebra-despeje', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-203',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '\\frac{x - 2}{3} \\geq 2',
    question: 'Una empresa de catering prepara bandejas de comida. El total de invitados menos 2 personas que ya confirmaron su asistencia se divide equitativamente en 3 mesas. Para que el evento sea exitoso, cada mesa debe tener al menos 2 personas confirmadas. El organizador necesita determinar cuántos invitados totales x se requieren. ¿Qué condición debe cumplir x?',
    questionLatex: '\\text{Una empresa de catering prepara bandejas de comida. El total de invitados menos 2 personas que ya confirmaron su asistencia se divide equitativamente en 3 mesas. Para que el evento sea exitoso, cada mesa debe tener al menos 2 personas confirmadas. El organizador necesita determinar cuántos invitados totales x se requieren. ¿Qué condición debe cumplir x?}',
    options: ['$x \\geq 8$', '$x \\geq 4$', '$x \\leq 8$', '$x > 8$'],
    optionsLatex: ['x \\geq 8', 'x \\geq 4', 'x \\leq 8', 'x > 8'],
    correctAnswer: 0,
    explanation: 'Planteamos (x - 2)/3 ≥ 2. Multiplicamos por 3: x - 2 ≥ 6. Despejamos: x ≥ 8 personas.',
    explanationLatex: '\\frac{x - 2}{3} \\geq 2 \\rightarrow x - 2 \\geq 6 \\rightarrow x \\geq 8',
    difficulty: 'medium',
    skills: ['algebra-desigualdades', 'algebra-despeje', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-204',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '|x| < 5',
    question: 'Un sensor de temperatura en un invernadero mide las desviaciones respecto al punto óptimo de cultivo. La desviación de temperatura se representa por x grados, donde valores positivos indican calor excesivo y negativos frío excesivo. Para que las plantas crezcan saludables, la magnitud de la desviación debe ser estrictamente menor a 5 grados en cualquier dirección. El agrónomo necesita determinar el rango permitido de desviaciones. ¿Qué valores puede tomar x?',
    questionLatex: '\\text{Un sensor de temperatura en un invernadero mide las desviaciones respecto al punto óptimo de cultivo. La desviación de temperatura se representa por x grados, donde valores positivos indican calor excesivo y negativos frío excesivo. Para que las plantas crezcan saludables, la magnitud de la desviación debe ser estrictamente menor a 5 grados en cualquier dirección. El agrónomo necesita determinar el rango permitido de desviaciones. ¿Qué valores puede tomar x?}',
    options: ['$-5 < x < 5$', '$x < 5$', '$x > -5$', '$x < -5$ o $x > 5$'],
    optionsLatex: ['-5 < x < 5', 'x < 5', 'x > -5', 'x < -5 \\text{ o } x > 5'],
    correctAnswer: 0,
    explanation: 'El valor absoluto |x| < 5 significa que la distancia desde cero es menor a 5, lo cual se expresa como -5 < x < 5.',
    explanationLatex: '|x| < 5 \\quad \\Leftrightarrow \\quad -5 < x < 5',
    difficulty: 'medium',
    skills: ['algebra-desigualdades', 'algebra-valor-absoluto']
  },
  {
    id: 'm1-205',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '|x - 3| \\leq 2',
    question: 'Una máquina industrial debe fabricar piezas con una longitud objetivo de 3 centímetros. La longitud real de cada pieza es x centímetros. El control de calidad establece que la desviación respecto al objetivo debe ser menor o igual a 2 centímetros en cualquier dirección para aprobar la pieza. El ingeniero de calidad necesita determinar qué longitudes son aceptables. ¿Qué valores puede tomar x?',
    questionLatex: '\\text{Una máquina industrial debe fabricar piezas con una longitud objetivo de 3 centímetros. La longitud real de cada pieza es x centímetros. El control de calidad establece que la desviación respecto al objetivo debe ser menor o igual a 2 centímetros en cualquier dirección para aprobar la pieza. El ingeniero de calidad necesita determinar qué longitudes son aceptables. ¿Qué valores puede tomar x?}',
    options: ['$1 \\leq x \\leq 5$', '$-2 \\leq x \\leq 2$', '$x \\leq 5$', '$x \\geq 1$'],
    optionsLatex: ['1 \\leq x \\leq 5', '-2 \\leq x \\leq 2', 'x \\leq 5', 'x \\geq 1'],
    correctAnswer: 0,
    explanation: 'Planteamos |x - 3| ≤ 2. Aplicamos la definición: -2 ≤ x - 3 ≤ 2. Sumamos 3 a todas las partes: -2 + 3 ≤ x ≤ 2 + 3, entonces 1 ≤ x ≤ 5 cm.',
    explanationLatex: '|x - 3| \\leq 2 \\quad \\Leftrightarrow \\quad -2 \\leq x - 3 \\leq 2 \\quad \\Rightarrow \\quad 1 \\leq x \\leq 5',
    difficulty: 'hard',
    skills: ['algebra-desigualdades', 'algebra-valor-absoluto', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-206',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '|2x + 1| > 5',
    question: 'Un laboratorio analiza la acidez de muestras de agua. La acidez se calcula mediante la expresión 2x + 1, donde x representa la concentración de iones. Para que el agua sea no potable y requiera tratamiento, la magnitud de la acidez debe ser estrictamente mayor a 5 unidades. El químico necesita identificar qué valores de concentración x requieren tratamiento. ¿Qué condición debe cumplir x?',
    questionLatex: '\\text{Un laboratorio analiza la acidez de muestras de agua. La acidez se calcula mediante la expresión } 2x + 1, \\text{ donde x representa la concentración de iones. Para que el agua sea no potable y requiera tratamiento, la magnitud de la acidez debe ser estrictamente mayor a 5 unidades. El químico necesita identificar qué valores de concentración x requieren tratamiento. ¿Qué condición debe cumplir x?}',
    options: ['$x < -3$ o $x > 2$', '$-3 < x < 2$', '$x > 2$', '$x < -3$'],
    optionsLatex: ['x < -3 \\text{ o } x > 2', '-3 < x < 2', 'x > 2', 'x < -3'],
    correctAnswer: 0,
    explanation: 'Planteamos |2x + 1| > 5. Separamos en dos casos: 2x + 1 < -5 o 2x + 1 > 5. Resolvemos: 2x < -6 (x < -3) o 2x > 4 (x > 2).',
    explanationLatex: '|2x + 1| > 5 \\quad \\Leftrightarrow \\quad 2x + 1 < -5 \\text{ o } 2x + 1 > 5 \\quad \\Rightarrow \\quad x < -3 \\text{ o } x > 2',
    difficulty: 'hard',
    skills: ['algebra-desigualdades', 'algebra-valor-absoluto', 'numeros-operaciones-basicas']
];
