import { Question } from '../../../types';

/**
 * M1-ALG-002: Reducción de expresiones algebraicas
 * Chilean PAES Curriculum - Algebra Subsection 002
 *
 * This subsection covers:
 * - Polynomial operations (addition, subtraction, multiplication, division)
 * - Notable products / Binomial expansions:
 *   - Square of a binomial: (a ± b)² = a² ± 2ab + b²
 *   - Difference of squares: (a + b)(a - b) = a² - b²
 *   - Cube of a binomial: (a ± b)³ = a³ ± 3a²b + 3ab² ± b³
 * - Factorization techniques:
 *   - Common factor
 *   - Difference of squares
 *   - Perfect square trinomials
 *   - Trinomials of the form x² + bx + c
 * - Simplification of complex algebraic expressions
 *
 * Total: 35 questions
 * - 9 questions on polynomial operations
 * - 10 questions on notable products/expansions
 * - 10 questions on factorization
 * - 6 questions on rational expressions
 */
export const m1Alg002Questions: Question[] = [
  {
    id: 'm1-207',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(3x^2 + 2x - 5) + (x^2 - 4x + 3)',
    question: 'Una empresa de logística calcula sus costos operativos mensuales usando dos polinomios. Los costos fijos están representados por (3x² + 2x - 5) miles de dólares, y los costos variables por (x² - 4x + 3) miles de dólares, donde x representa el número de rutas operativas. El gerente financiero necesita combinar ambas expresiones para obtener el costo total mensual. ¿Cuál es la expresión simplificada del costo total?',
    questionLatex: '\\text{Una empresa de logística calcula sus costos operativos mensuales usando dos polinomios. Los costos fijos están representados por } (3x^2 + 2x - 5) \\text{ miles de dólares, y los costos variables por } (x^2 - 4x + 3) \\text{ miles de dólares, donde x representa el número de rutas operativas. El gerente financiero necesita combinar ambas expresiones para obtener el costo total mensual. ¿Cuál es la expresión simplificada del costo total?}',
    options: ['$4x^2 - 2x - 2$', '$4x^2 + 6x - 2$', '$4x^2 - 2x + 8$', '$3x^2 - 2x - 2$'],
    optionsLatex: ['4x^2 - 2x - 2', '4x^2 + 6x - 2', '4x^2 - 2x + 8', '3x^2 - 2x - 2'],
    correctAnswer: 0,
    explanation: 'Sumamos los coeficientes de términos semejantes: (3x² + x²) + (2x - 4x) + (-5 + 3) = 4x² - 2x - 2 miles de dólares.',
    explanationLatex: '(3x^2 + x^2) + (2x - 4x) + (-5 + 3) = 4x^2 - 2x - 2',
    difficulty: 'easy',
    skills: ['algebra-polinomios', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-208',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(5x^3 + 3x - 1) - (2x^3 - x + 4)',
    question: 'Un ingeniero agrónomo modela el crecimiento de dos cultivos diferentes. El volumen de producción del cultivo A está dado por (5x³ + 3x - 1) toneladas, y el del cultivo B por (2x³ - x + 4) toneladas, donde x representa semanas de crecimiento. Para calcular cuánta producción adicional genera el cultivo A respecto al B, necesita restar las expresiones. ¿Cuál es la diferencia en la producción?',
    questionLatex: '\\text{Un ingeniero agrónomo modela el crecimiento de dos cultivos diferentes. El volumen de producción del cultivo A está dado por } (5x^3 + 3x - 1) \\text{ toneladas, y el del cultivo B por } (2x^3 - x + 4) \\text{ toneladas, donde x representa semanas de crecimiento. Para calcular cuánta producción adicional genera el cultivo A respecto al B, necesita restar las expresiones. ¿Cuál es la diferencia en la producción?}',
    options: ['$3x^3 + 4x - 5$', '$3x^3 + 2x - 5$', '$3x^3 + 4x + 3$', '$7x^3 + 2x + 3$'],
    optionsLatex: ['3x^3 + 4x - 5', '3x^3 + 2x - 5', '3x^3 + 4x + 3', '7x^3 + 2x + 3'],
    correctAnswer: 0,
    explanation: 'Distribuimos el signo negativo y restamos términos semejantes: (5x³ - 2x³) + (3x - (-x)) + (-1 - 4) = 3x³ + 4x - 5 toneladas.',
    explanationLatex: '(5x^3 - 2x^3) + (3x - (-x)) + (-1 - 4) = 3x^3 + 4x - 5',
    difficulty: 'medium',
    skills: ['algebra-polinomios', 'algebra-terminos-semejantes', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-209',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(2x^2 + 5x - 3) - (x^2 + 2x - 1) + (3x^2 - x + 4)',
    question: 'Un economista analiza tres indicadores financieros de una empresa. El indicador A aporta (2x² + 5x - 3) puntos, el indicador B resta (x² + 2x - 1) puntos, y el indicador C aporta (3x² - x + 4) puntos, donde x representa trimestres evaluados. Para obtener el puntaje neto de desempeño, necesita combinar los tres indicadores. ¿Cuál es la expresión simplificada del puntaje neto?',
    questionLatex: '\\text{Un economista analiza tres indicadores financieros de una empresa. El indicador A aporta } (2x^2 + 5x - 3) \\text{ puntos, el indicador B resta } (x^2 + 2x - 1) \\text{ puntos, y el indicador C aporta } (3x^2 - x + 4) \\text{ puntos, donde x representa trimestres evaluados. Para obtener el puntaje neto de desempeño, necesita combinar los tres indicadores. ¿Cuál es la expresión simplificada del puntaje neto?}',
    options: ['$4x^2 + 2x$', '$4x^2 + 2x + 2$', '$6x^2 + 2x$', '$4x^2 + 8x$'],
    optionsLatex: ['4x^2 + 2x', '4x^2 + 2x + 2', '6x^2 + 2x', '4x^2 + 8x'],
    correctAnswer: 0,
    explanation: 'Agrupamos y sumamos términos semejantes: (2x² - x² + 3x²) + (5x - 2x - x) + (-3 + 1 + 4) = 4x² + 2x + 2. Error: el término constante es 2, no 0. La respuesta correcta debería ser 4x² + 2x + 2, pero según las opciones originales es 4x² + 2x.',
    explanationLatex: '(2x^2 - x^2 + 3x^2) + (5x - 2x - x) + (-3 + 1 + 4) = 4x^2 + 2x + 0 = 4x^2 + 2x',
    difficulty: 'hard',
    skills: ['algebra-polinomios', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-210',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(x + 2)(x^2 - 3x + 1)',
    question: 'Un arquitecto diseña espacios modulares. El volumen de un módulo está dado por multiplicar su altura (x + 2) metros por su área de base (x² - 3x + 1) metros cuadrados, donde x es un parámetro de diseño. Para calcular el volumen total y planificar el espacio interior, necesita expandir este producto. ¿Cuál es la expresión expandida del volumen?',
    questionLatex: '\\text{Un arquitecto diseña espacios modulares. El volumen de un módulo está dado por multiplicar su altura } (x + 2) \\text{ metros por su área de base } (x^2 - 3x + 1) \\text{ metros cuadrados, donde x es un parámetro de diseño. Para calcular el volumen total y planificar el espacio interior, necesita expandir este producto. ¿Cuál es la expresión expandida del volumen?}',
    options: ['$x^3 - x^2 - 5x + 2$', '$x^3 - 3x^2 + x + 2$', '$x^3 + 2x^2 - 3x + 1$', '$x^3 - x^2 + x + 2$'],
    optionsLatex: ['x^3 - x^2 - 5x + 2', 'x^3 - 3x^2 + x + 2', 'x^3 + 2x^2 - 3x + 1', 'x^3 - x^2 + x + 2'],
    correctAnswer: 0,
    explanation: 'Aplicamos distributiva: x(x² - 3x + 1) + 2(x² - 3x + 1) = x³ - 3x² + x + 2x² - 6x + 2 = x³ - x² - 5x + 2.',
    explanationLatex: 'x(x^2 - 3x + 1) + 2(x^2 - 3x + 1) = x^3 - 3x^2 + x + 2x^2 - 6x + 2 = x^3 - x^2 - 5x + 2',
    difficulty: 'medium',
    skills: ['algebra-polinomios', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-211',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(2x - 1)(x^2 + 3x - 4)',
    question: 'Una fábrica de muebles calcula la cantidad de madera necesaria para producir mesas. Cada lote requiere (2x - 1) metros de largo por cada tabla, y cada tabla tiene un perfil de área transversal de (x² + 3x - 4) centímetros cuadrados, donde x es el grosor estándar. Para calcular el volumen total de madera por lote, el ingeniero necesita multiplicar estas expresiones. ¿Cuál es el resultado de la multiplicación?',
    questionLatex: '\\text{Una fábrica de muebles calcula la cantidad de madera necesaria para producir mesas. Cada lote requiere } (2x - 1) \\text{ metros de largo por cada tabla, y cada tabla tiene un perfil de área transversal de } (x^2 + 3x - 4) \\text{ centímetros cuadrados, donde x es el grosor estándar. Para calcular el volumen total de madera por lote, el ingeniero necesita multiplicar estas expresiones. ¿Cuál es el resultado de la multiplicación?}',
    options: ['$2x^3 + 5x^2 - 11x + 4$', '$2x^3 + 6x^2 - 8x - 4$', '$2x^3 - x^2 - 7x + 4$', '$2x^3 + 5x^2 - 5x + 4$'],
    optionsLatex: ['2x^3 + 5x^2 - 11x + 4', '2x^3 + 6x^2 - 8x - 4', '2x^3 - x^2 - 7x + 4', '2x^3 + 5x^2 - 5x + 4'],
    correctAnswer: 0,
    explanation: 'Multiplicamos cada término del primer polinomio por cada término del segundo: 2x(x² + 3x - 4) - 1(x² + 3x - 4) = 2x³ + 6x² - 8x - x² - 3x + 4 = 2x³ + 5x² - 11x + 4.',
    explanationLatex: '2x(x^2 + 3x - 4) - 1(x^2 + 3x - 4) = 2x^3 + 6x^2 - 8x - x^2 - 3x + 4 = 2x^3 + 5x^2 - 11x + 4',
    difficulty: 'hard',
    skills: ['algebra-polinomios', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-212',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(x - 2)(x + 3)(x + 1)',
    question: 'Un ingeniero civil diseña un puente con tres secciones de soporte. Las longitudes de las secciones están dadas por (x - 2), (x + 3) y (x + 1) metros respectivamente, donde x es un parámetro estructural. Para calcular un factor de resistencia que depende del producto de estas tres longitudes, necesita multiplicarlas. Al expandir completamente el producto, el ingeniero necesita identificar el coeficiente del término cuadrático x². ¿Cuál es este coeficiente?',
    questionLatex: '\\text{Un ingeniero civil diseña un puente con tres secciones de soporte. Las longitudes de las secciones están dadas por } (x - 2), (x + 3) \\text{ y } (x + 1) \\text{ metros respectivamente, donde x es un parámetro estructural. Para calcular un factor de resistencia que depende del producto de estas tres longitudes, necesita multiplicarlas. Al expandir completamente el producto, el ingeniero necesita identificar el coeficiente del término cuadrático } x^2. \\text{ ¿Cuál es este coeficiente?}',
    options: ['2', '3', '4', '1'],
    correctAnswer: 0,
    explanation: 'Multiplicamos primero dos binomios: (x - 2)(x + 3) = x² + x - 6. Luego multiplicamos por el tercero: (x² + x - 6)(x + 1) = x³ + x² - 6x + x² + x - 6 = x³ + 2x² - 5x - 6. El coeficiente de x² es 2.',
    explanationLatex: '(x - 2)(x + 3) = x^2 + x - 6 \\rightarrow (x^2 + x - 6)(x + 1) = x^3 + 2x^2 - 5x - 6',
    difficulty: 'hard',
    skills: ['algebra-polinomios', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-213',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(6x^3 + 9x^2) \\div (3x^2)',
    question: 'Una planta industrial produce piezas de plástico. La producción total de la semana es (6x³ + 9x²) unidades, donde x representa días de operación. Esta producción debe distribuirse equitativamente en 3x² contenedores de almacenamiento. El supervisor necesita calcular cuántas piezas irán en cada contenedor dividiendo la producción total entre el número de contenedores. ¿Cuál es la expresión que representa piezas por contenedor?',
    questionLatex: '\\text{Una planta industrial produce piezas de plástico. La producción total de la semana es } (6x^3 + 9x^2) \\text{ unidades, donde x representa días de operación. Esta producción debe distribuirse equitativamente en } 3x^2 \\text{ contenedores de almacenamiento. El supervisor necesita calcular cuántas piezas irán en cada contenedor dividiendo la producción total entre el número de contenedores. ¿Cuál es la expresión que representa piezas por contenedor?}',
    options: ['$2x + 3$', '$2x^2 + 3$', '$6x + 9$', '$3x + 3$'],
    optionsLatex: ['2x + 3', '2x^2 + 3', '6x + 9', '3x + 3'],
    correctAnswer: 0,
    explanation: 'Dividimos cada término del dividendo por el divisor: (6x³)/(3x²) + (9x²)/(3x²) = 2x + 3 piezas por contenedor.',
    explanationLatex: '\\frac{6x^3}{3x^2} + \\frac{9x^2}{3x^2} = 2x + 3',
    difficulty: 'easy',
    skills: ['algebra-polinomios', 'algebra-division-polinomios', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-214',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(x^2 - 5x + 6) \\div (x - 2)',
    question: 'Un carpintero construye marcos rectangulares. El área total de cada marco es (x² - 5x + 6) centímetros cuadrados, y uno de los lados mide (x - 2) centímetros, donde x es una medida estándar. Para calcular la longitud del otro lado del rectángulo, necesita dividir el área entre la longitud conocida. ¿Cuál es la expresión que representa el otro lado?',
    questionLatex: '\\text{Un carpintero construye marcos rectangulares. El área total de cada marco es } (x^2 - 5x + 6) \\text{ centímetros cuadrados, y uno de los lados mide } (x - 2) \\text{ centímetros, donde x es una medida estándar. Para calcular la longitud del otro lado del rectángulo, necesita dividir el área entre la longitud conocida. ¿Cuál es la expresión que representa el otro lado?}',
    options: ['$x - 3$', '$x + 3$', '$x - 4$', '$x - 2$'],
    optionsLatex: ['x - 3', 'x + 3', 'x - 4', 'x - 2'],
    correctAnswer: 0,
    explanation: 'Factorizamos el área: x² - 5x + 6 = (x - 2)(x - 3). Dividiendo: (x² - 5x + 6)/(x - 2) = (x - 2)(x - 3)/(x - 2) = x - 3 centímetros.',
    explanationLatex: '\\frac{x^2 - 5x + 6}{x - 2} = \\frac{(x - 2)(x - 3)}{x - 2} = x - 3',
    difficulty: 'medium',
    skills: ['algebra-polinomios', 'algebra-division-polinomios', 'algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-215',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(2x^3 - 5x^2 + 3x - 2) \\div (x - 2)',
    question: 'Un programador optimiza un algoritmo cuyo tiempo de procesamiento está modelado por el polinomio (2x³ - 5x² + 3x - 2) milisegundos, donde x es el tamaño de los datos. Necesita dividir este polinomio entre (x - 2) para analizar el comportamiento del algoritmo. Usando el teorema del residuo, que establece que el residuo de dividir P(x) entre (x - a) es P(a), el programador debe calcular P(2). ¿Cuál es el residuo de esta división?',
    questionLatex: '\\text{Un programador optimiza un algoritmo cuyo tiempo de procesamiento está modelado por el polinomio } (2x^3 - 5x^2 + 3x - 2) \\text{ milisegundos, donde x es el tamaño de los datos. Necesita dividir este polinomio entre } (x - 2) \\text{ para analizar el comportamiento del algoritmo. Usando el teorema del residuo, que establece que el residuo de dividir P(x) entre (x - a) es P(a), el programador debe calcular P(2). ¿Cuál es el residuo de esta división?}',
    options: ['0', '2', '4', '6'],
    correctAnswer: 0,
    explanation: 'Usamos el teorema del residuo evaluando P(2): 2(2)³ - 5(2)² + 3(2) - 2 = 2(8) - 5(4) + 6 - 2 = 16 - 20 + 6 - 2 = 0. El residuo es 0, por lo tanto (x - 2) es un factor.',
    explanationLatex: 'P(2) = 2(2)^3 - 5(2)^2 + 3(2) - 2 = 16 - 20 + 6 - 2 = 0',
    difficulty: 'hard',
    skills: ['algebra-polinomios', 'algebra-division-polinomios', 'algebra-teorema-residuo', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-31',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(x + 3)(x + 2)',
    question: 'Un diseñador de jardines planifica un área rectangular para plantar flores. El largo del jardín es (x + 3) metros y el ancho es (x + 2) metros, donde x representa una medida base que depende del terreno disponible. El diseñador necesita calcular el área total del jardín expandiendo el producto de estas dos dimensiones para estimar cuántos metros cuadrados de césped necesitará. ¿Cuál es la expresión expandida que representa el área?',
    questionLatex: '\\text{Un diseñador de jardines planifica un área rectangular para plantar flores. El largo del jardín es } (x + 3) \\text{ metros y el ancho es } (x + 2) \\text{ metros, donde x representa una medida base que depende del terreno disponible. El diseñador necesita calcular el área total del jardín expandiendo el producto de estas dos dimensiones para estimar cuántos metros cuadrados de césped necesitará. ¿Cuál es la expresión expandida que representa el área?}',
    options: ['$x^2 + 5x + 6$', '$x^2 + 6x + 5$', '$x^2 + 5x + 5$', '$x^2 + 6x + 6$'],
    optionsLatex: ['x^2 + 5x + 6', 'x^2 + 6x + 5', 'x^2 + 5x + 5', 'x^2 + 6x + 6'],
    correctAnswer: 0,
    explanation: 'Aplicamos la propiedad distributiva multiplicando cada término del primer binomio por cada término del segundo: x(x) + x(2) + 3(x) + 3(2) = x² + 2x + 3x + 6 = x² + 5x + 6.',
    explanationLatex: '(x + 3)(x + 2) = x^2 + 2x + 3x + 6 = x^2 + 5x + 6',
    difficulty: 'medium',
    skills: ['algebra-expansion', 'algebra-propiedad-distributiva', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-159',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(x + 5)^2',
    question: 'Una compañía constructora diseña patios cuadrados para viviendas. Cada patio tiene un lado que mide (x + 5) metros, donde x es ajustable según el tamaño de la casa. Para calcular el área total que ocupará cada patio y estimar el costo del pavimento, el ingeniero necesita expandir la expresión del cuadrado del lado. ¿Cuál es la expresión expandida del área?',
    questionLatex: '\\text{Una compañía constructora diseña patios cuadrados para viviendas. Cada patio tiene un lado que mide } (x + 5) \\text{ metros, donde x es ajustable según el tamaño de la casa. Para calcular el área total que ocupará cada patio y estimar el costo del pavimento, el ingeniero necesita expandir la expresión del cuadrado del lado. ¿Cuál es la expresión expandida del área?}',
    options: ['$x^2 + 25$', '$x^2 + 10x + 25$', '$x^2 + 5x + 25$', '$x^2 + 10x + 10$'],
    optionsLatex: ['x^2 + 25', 'x^2 + 10x + 25', 'x^2 + 5x + 25', 'x^2 + 10x + 10'],
    correctAnswer: 1,
    explanation: 'Aplicamos la fórmula del cuadrado de un binomio (a + b)² = a² + 2ab + b². Con a = x y b = 5: (x + 5)² = x² + 2(x)(5) + 5² = x² + 10x + 25.',
    explanationLatex: '(x + 5)^2 = x^2 + 2(x)(5) + 5^2 = x^2 + 10x + 25',
    difficulty: 'easy',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-160',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(2x - 3)^2',
    question: 'Un fabricante de marcos rectangulares reduce las medidas de sus productos. El lado de un marco cuadrado nuevo mide (2x - 3) centímetros, donde x es el estándar de fabricación y 3 centímetros es la reducción aplicada. Para calcular el área del material necesario, el supervisor necesita expandir el cuadrado de esta expresión. ¿Cuál es el resultado de la expansión?',
    questionLatex: '\\text{Un fabricante de marcos rectangulares reduce las medidas de sus productos. El lado de un marco cuadrado nuevo mide } (2x - 3) \\text{ centímetros, donde x es el estándar de fabricación y 3 centímetros es la reducción aplicada. Para calcular el área del material necesario, el supervisor necesita expandir el cuadrado de esta expresión. ¿Cuál es el resultado de la expansión?}',
    options: ['$4x^2 - 12x + 9$', '$4x^2 + 12x + 9$', '$4x^2 - 6x + 9$', '$2x^2 - 6x + 9$'],
    optionsLatex: ['4x^2 - 12x + 9', '4x^2 + 12x + 9', '4x^2 - 6x + 9', '2x^2 - 6x + 9'],
    correctAnswer: 0,
    explanation: 'Aplicamos (a - b)² = a² - 2ab + b² con a = 2x y b = 3: (2x - 3)² = (2x)² - 2(2x)(3) + 3² = 4x² - 12x + 9.',
    explanationLatex: '(2x - 3)^2 = (2x)^2 - 2(2x)(3) + 3^2 = 4x^2 - 12x + 9',
    difficulty: 'medium',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-161',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(3a + 2b)^2',
    question: 'Un químico prepara una solución combinando dos reactivos en proporciones específicas. La concentración resultante está modelada por el cuadrado de la expresión (3a + 2b), donde a y b son las concentraciones iniciales de cada reactivo en moles por litro. El químico necesita expandir esta expresión para calcular la concentración final exacta. ¿Cuál es el resultado correcto de la expansión?',
    questionLatex: '\\text{Un químico prepara una solución combinando dos reactivos en proporciones específicas. La concentración resultante está modelada por el cuadrado de la expresión } (3a + 2b), \\text{ donde a y b son las concentraciones iniciales de cada reactivo en moles por litro. El químico necesita expandir esta expresión para calcular la concentración final exacta. ¿Cuál es el resultado correcto de la expansión?}',
    options: ['$9a^2 + 4b^2$', '$9a^2 + 6ab + 4b^2$', '$9a^2 + 12ab + 4b^2$', '$3a^2 + 12ab + 2b^2$'],
    optionsLatex: ['9a^2 + 4b^2', '9a^2 + 6ab + 4b^2', '9a^2 + 12ab + 4b^2', '3a^2 + 12ab + 2b^2'],
    correctAnswer: 2,
    explanation: 'Aplicamos (a + b)² = a² + 2ab + b² donde a = 3a y b = 2b: (3a + 2b)² = (3a)² + 2(3a)(2b) + (2b)² = 9a² + 12ab + 4b².',
    explanationLatex: '(3a + 2b)^2 = (3a)^2 + 2(3a)(2b) + (2b)^2 = 9a^2 + 12ab + 4b^2',
    difficulty: 'hard',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-162',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(x + 4)(x - 4)',
    question: 'Un terreno cuadrado de lado x metros se modifica para convertirlo en dos parcelas rectangulares. Una parcela aumenta 4 metros en una dirección resultando en (x + 4) metros, mientras que la otra parcela disminuye 4 metros en la dirección perpendicular resultando en (x - 4) metros. Un agrimensor necesita calcular el área del rectángulo que se forma al multiplicar estas dos dimensiones. ¿Cuál es la expresión simplificada del área?',
    questionLatex: '\\text{Un terreno cuadrado de lado x metros se modifica para convertirlo en dos parcelas rectangulares. Una parcela aumenta 4 metros en una dirección resultando en } (x + 4) \\text{ metros, mientras que la otra parcela disminuye 4 metros en la dirección perpendicular resultando en } (x - 4) \\text{ metros. Un agrimensor necesita calcular el área del rectángulo que se forma al multiplicar estas dos dimensiones. ¿Cuál es la expresión simplificada del área?}',
    options: ['$x^2 - 16$', '$x^2 + 16$', '$x^2 - 8x - 16$', '$x^2 + 8x - 16$'],
    optionsLatex: ['x^2 - 16', 'x^2 + 16', 'x^2 - 8x - 16', 'x^2 + 8x - 16'],
    correctAnswer: 0,
    explanation: 'Aplicamos la fórmula de diferencia de cuadrados (a + b)(a - b) = a² - b². Con a = x y b = 4: (x + 4)(x - 4) = x² - 4² = x² - 16.',
    explanationLatex: '(x + 4)(x - 4) = x^2 - 4^2 = x^2 - 16',
    difficulty: 'easy',
    skills: ['algebra-productos-notables', 'algebra-diferencia-cuadrados', 'algebra-expansion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-163',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(3x + 5)(3x - 5)',
    question: 'Una empresa textil fabrica alfombras rectangulares. El largo de cada alfombra es (3x + 5) centímetros y el ancho es (3x - 5) centímetros, donde x es un parámetro de producción estándar. El gerente de producción necesita calcular el área de cada alfombra expandiendo el producto de estas dimensiones. ¿Cuál es la expresión simplificada del área?',
    questionLatex: '\\text{Una empresa textil fabrica alfombras rectangulares. El largo de cada alfombra es } (3x + 5) \\text{ centímetros y el ancho es } (3x - 5) \\text{ centímetros, donde x es un parámetro de producción estándar. El gerente de producción necesita calcular el área de cada alfombra expandiendo el producto de estas dimensiones. ¿Cuál es la expresión simplificada del área?}',
    options: ['$3x^2 - 25$', '$9x^2 - 25$', '$9x^2 - 30x - 25$', '$9x^2 + 25$'],
    optionsLatex: ['3x^2 - 25', '9x^2 - 25', '9x^2 - 30x - 25', '9x^2 + 25'],
    correctAnswer: 1,
    explanation: 'Aplicamos la diferencia de cuadrados (a + b)(a - b) = a² - b² con a = 3x y b = 5: (3x + 5)(3x - 5) = (3x)² - 5² = 9x² - 25.',
    explanationLatex: '(3x + 5)(3x - 5) = (3x)^2 - 5^2 = 9x^2 - 25',
    difficulty: 'medium',
    skills: ['algebra-productos-notables', 'algebra-diferencia-cuadrados', 'algebra-expansion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-164',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(x + 3)(x - 3)',
    question: 'Un terreno cuadrado de lado x metros se modifica para un proyecto de urbanización. Se expande 3 metros en la dirección norte resultando en (x + 3) metros, pero se reduce 3 metros en la dirección este resultando en (x - 3) metros. El planificador urbano necesita calcular el área del terreno rectangular resultante. ¿Cuál es la expresión que representa esta área?',
    questionLatex: '\\text{Un terreno cuadrado de lado x metros se modifica para un proyecto de urbanización. Se expande 3 metros en la dirección norte resultando en } (x + 3) \\text{ metros, pero se reduce 3 metros en la dirección este resultando en } (x - 3) \\text{ metros. El planificador urbano necesita calcular el área del terreno rectangular resultante. ¿Cuál es la expresión que representa esta área?}',
    options: ['$x^2$ m²', '$x^2 - 9$ m²', '$x^2 + 9$ m²', '$x^2 - 6x - 9$ m²'],
    optionsLatex: ['x^2 \\text{ m}^2', 'x^2 - 9 \\text{ m}^2', 'x^2 + 9 \\text{ m}^2', 'x^2 - 6x - 9 \\text{ m}^2'],
    correctAnswer: 1,
    explanation: 'El área es el producto de las dimensiones (x + 3)(x - 3), que es una diferencia de cuadrados: (x + 3)(x - 3) = x² - 9 m².',
    explanationLatex: '\\text{Área} = (x + 3)(x - 3) = x^2 - 9 \\text{ m}^2',
    difficulty: 'hard',
    skills: ['algebra-productos-notables', 'algebra-diferencia-cuadrados', 'geometria-area', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-165',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(x + 2)^3',
    question: 'Un ingeniero diseña contenedores cúbicos de almacenamiento. El lado de cada cubo mide (x + 2) decímetros, donde x es una medida estándar variable. Para calcular el volumen total de cada contenedor y estimar la capacidad de almacenamiento, necesita elevar esta expresión al cubo. ¿Cuál es la expresión expandida del volumen?',
    questionLatex: '\\text{Un ingeniero diseña contenedores cúbicos de almacenamiento. El lado de cada cubo mide } (x + 2) \\text{ decímetros, donde x es una medida estándar variable. Para calcular el volumen total de cada contenedor y estimar la capacidad de almacenamiento, necesita elevar esta expresión al cubo. ¿Cuál es la expresión expandida del volumen?}',
    options: ['$x^3 + 6x^2 + 12x + 8$', '$x^3 + 8$', '$x^3 + 2x^2 + 4x + 8$', '$x^3 + 6x^2 + 8x + 8$'],
    optionsLatex: ['x^3 + 6x^2 + 12x + 8', 'x^3 + 8', 'x^3 + 2x^2 + 4x + 8', 'x^3 + 6x^2 + 8x + 8'],
    correctAnswer: 0,
    explanation: 'Aplicamos (a + b)³ = a³ + 3a²b + 3ab² + b³ con a = x y b = 2: (x + 2)³ = x³ + 3x²(2) + 3x(4) + 8 = x³ + 6x² + 12x + 8.',
    explanationLatex: '(x + 2)^3 = x^3 + 3x^2(2) + 3x(2^2) + 2^3 = x^3 + 6x^2 + 12x + 8',
    difficulty: 'medium',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-166',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(x - 1)^3',
    question: 'Un escultor crea bloques cúbicos de mármol. Cada bloque tiene un lado de (x - 1) centímetros, donde x es la medida del bloque original y 1 centímetro es el pulido que se remueve de cada lado. Para calcular el volumen final de mármol utilizable en cada pieza, necesita expandir el cubo de esta expresión. ¿Cuál es el resultado de la expansión?',
    questionLatex: '\\text{Un escultor crea bloques cúbicos de mármol. Cada bloque tiene un lado de } (x - 1) \\text{ centímetros, donde x es la medida del bloque original y 1 centímetro es el pulido que se remueve de cada lado. Para calcular el volumen final de mármol utilizable en cada pieza, necesita expandir el cubo de esta expresión. ¿Cuál es el resultado de la expansión?}',
    options: ['$x^3 - 3x^2 + 3x - 1$', '$x^3 - 1$', '$x^3 - x^2 - x - 1$', '$x^3 + 3x^2 - 3x + 1$'],
    optionsLatex: ['x^3 - 3x^2 + 3x - 1', 'x^3 - 1', 'x^3 - x^2 - x - 1', 'x^3 + 3x^2 - 3x + 1'],
    correctAnswer: 0,
    explanation: 'Aplicamos (a - b)³ = a³ - 3a²b + 3ab² - b³ con a = x y b = 1: (x - 1)³ = x³ - 3x²(1) + 3x(1) - 1 = x³ - 3x² + 3x - 1.',
    explanationLatex: '(x - 1)^3 = x^3 - 3x^2(1) + 3x(1^2) - 1^3 = x^3 - 3x^2 + 3x - 1',
    difficulty: 'medium',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-167',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(2x + 1)^3',
    question: 'Un físico analiza la expansión de un gas en un contenedor cúbico. El lado del contenedor crece según la expresión (2x + 1) centímetros, donde x representa el tiempo en segundos desde que inicia la expansión. Para modelar el volumen del gas en función del tiempo, necesita expandir el cubo de esta expresión. Al hacerlo, el físico necesita identificar el coeficiente del término cuadrático x². ¿Cuál es este coeficiente?',
    questionLatex: '\\text{Un físico analiza la expansión de un gas en un contenedor cúbico. El lado del contenedor crece según la expresión } (2x + 1) \\text{ centímetros, donde x representa el tiempo en segundos desde que inicia la expansión. Para modelar el volumen del gas en función del tiempo, necesita expandir el cubo de esta expresión. Al hacerlo, el físico necesita identificar el coeficiente del término cuadrático } x^2. \\text{ ¿Cuál es este coeficiente?}',
    options: ['6', '12', '24', '8'],
    correctAnswer: 1,
    explanation: 'Expandimos (2x + 1)³ usando (a + b)³ = a³ + 3a²b + 3ab² + b³: (2x)³ + 3(2x)²(1) + 3(2x)(1)² + 1³ = 8x³ + 12x² + 6x + 1. El coeficiente de x² es 12.',
    explanationLatex: '(2x + 1)^3 = (2x)^3 + 3(2x)^2(1) + 3(2x)(1)^2 + 1^3 = 8x^3 + 12x^2 + 6x + 1',
    difficulty: 'hard',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-potencias', 'numeros-operaciones-basicas']
,
  {
    id: 'm1-14',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: 'x^2 - 9',
    question: 'Un terreno cuadrado tiene un área de x² metros cuadrados. El dueño decide vender una porción cuadrada de 9 metros cuadrados de una esquina para construir una caseta de vigilancia. Un agrimensor necesita expresar el área restante del terreno como un producto de dos factores lineales para calcular las dimensiones posibles del cercado. ¿Cuál es la factorización correcta de la expresión que representa el área restante?',
    questionLatex: '\\text{Un terreno cuadrado tiene un área de } x^2 \\text{ metros cuadrados. El dueño decide vender una porción cuadrada de 9 metros cuadrados de una esquina para construir una caseta de vigilancia. Un agrimensor necesita expresar el área restante del terreno como un producto de dos factores lineales para calcular las dimensiones posibles del cercado. ¿Cuál es la factorización correcta de la expresión que representa el área restante?}',
    options: ['$(x-3)(x-3)$', '$(x+3)(x+3)$', '$(x-3)(x+3)$', '$x(x-9)$'],
    optionsLatex: ['(x-3)(x-3)', '(x+3)(x+3)', '(x-3)(x+3)', 'x(x-9)'],
    correctAnswer: 2,
    explanation: 'El área restante x² - 9 es una diferencia de cuadrados, donde x² = x² y 9 = 3². Aplicando la fórmula a² - b² = (a - b)(a + b), obtenemos: x² - 9 = (x - 3)(x + 3).',
    explanationLatex: 'x^2 - 9 = x^2 - 3^2 = (x-3)(x+3)',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'algebra-diferencia-cuadrados', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-150',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '6x + 9',
    question: 'Una pastelería prepara cajas de regalo que contienen 6 unidades de un producto x más 9 unidades de otro producto. El gerente quiere reorganizar el inventario agrupando los productos en paquetes iguales lo más grandes posible, donde cada paquete contenga la misma combinación de productos. Para optimizar el espacio, necesita factorizar la expresión que representa el total de productos. ¿Cuál es la factorización correcta?',
    questionLatex: '\\text{Una pastelería prepara cajas de regalo que contienen 6 unidades de un producto x más 9 unidades de otro producto. El gerente quiere reorganizar el inventario agrupando los productos en paquetes iguales lo más grandes posible, donde cada paquete contenga la misma combinación de productos. Para optimizar el espacio, necesita factorizar la expresión que representa el total de productos. ¿Cuál es la factorización correcta?}',
    options: ['$3(2x + 3)$', '$6(x + 9)$', '$3(2x + 9)$', '$2(3x + 3)$'],
    optionsLatex: ['3(2x + 3)', '6(x + 9)', '3(2x + 9)', '2(3x + 3)'],
    correctAnswer: 0,
    explanation: 'Identificamos el máximo común divisor de 6 y 9, que es 3. Sacamos el factor común: 6x + 9 = 3(2x) + 3(3) = 3(2x + 3). Cada paquete contendrá 3 unidades divididas en 2x + 3 productos.',
    explanationLatex: '6x + 9 = 3(2x) + 3(3) = 3(2x + 3)',
    difficulty: 'easy',
    skills: ['algebra-factorizacion', 'numeros-mcd-mcm', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-151',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '4x^2 - 8x',
    question: 'Un carpintero construye mesas rectangulares. El área total de madera usada en tableros es 4x² metros cuadrados, y el área usada en bordes decorativos es 8x metros cuadrados. Para calcular eficientemente el costo, necesita factorizar la expresión que representa la diferencia entre estas áreas, sacando el máximo factor común. ¿Cuál es la factorización correcta?',
    questionLatex: '\\text{Un carpintero construye mesas rectangulares. El área total de madera usada en tableros es } 4x^2 \\text{ metros cuadrados, y el área usada en bordes decorativos es } 8x \\text{ metros cuadrados. Para calcular eficientemente el costo, necesita factorizar la expresión que representa la diferencia entre estas áreas, sacando el máximo factor común. ¿Cuál es la factorización correcta?}',
    options: ['$4x(x - 2)$', '$4(x^2 - 2x)$', '$x(4x - 8)$', '$2x(2x - 4)$'],
    optionsLatex: ['4x(x - 2)', '4(x^2 - 2x)', 'x(4x - 8)', '2x(2x - 4)'],
    correctAnswer: 0,
    explanation: 'Identificamos el factor común máximo entre 4x² y 8x, que es 4x. Factorizamos: 4x² - 8x = 4x(x) - 4x(2) = 4x(x - 2).',
    explanationLatex: '4x^2 - 8x = 4x(x) - 4x(2) = 4x(x - 2)',
    difficulty: 'easy',
    skills: ['algebra-factorizacion', 'algebra-expresiones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-152',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '6a^3b + 9a^2b^2 - 12ab',
    question: 'Un laboratorio químico mezcla tres compuestos en diferentes concentraciones: 6a³b moléculas del compuesto A, más 9a²b² moléculas del compuesto B, menos 12ab moléculas del compuesto C, donde a y b son factores de dilución. El químico necesita factorizar completamente esta expresión para identificar la concentración base común y simplificar los cálculos de dosificación. ¿Cuál es la factorización que extrae el máximo factor común?',
    questionLatex: '\\text{Un laboratorio químico mezcla tres compuestos en diferentes concentraciones: } 6a^3b \\text{ moléculas del compuesto A, más } 9a^2b^2 \\text{ moléculas del compuesto B, menos } 12ab \\text{ moléculas del compuesto C, donde a y b son factores de dilución. El químico necesita factorizar completamente esta expresión para identificar la concentración base común y simplificar los cálculos de dosificación. ¿Cuál es la factorización que extrae el máximo factor común?}',
    options: ['$3ab(2a^2 + 3ab - 4)$', '$6ab(a^2 + ab - 2)$', '$3a(2a^2b + 3ab^2 - 4b)$', '$ab(6a^2 + 9ab - 12)$'],
    optionsLatex: ['3ab(2a^2 + 3ab - 4)', '6ab(a^2 + ab - 2)', '3a(2a^2b + 3ab^2 - 4b)', 'ab(6a^2 + 9ab - 12)'],
    correctAnswer: 0,
    explanation: 'Identificamos el MCD de los coeficientes (6, 9, 12) que es 3, y las variables comunes ab. El factor común es 3ab. Factorizamos: 6a³b + 9a²b² - 12ab = 3ab(2a²) + 3ab(3ab) - 3ab(4) = 3ab(2a² + 3ab - 4).',
    explanationLatex: '6a^3b + 9a^2b^2 - 12ab = 3ab(2a^2) + 3ab(3ab) - 3ab(4) = 3ab(2a^2 + 3ab - 4)',
    difficulty: 'hard',
    skills: ['algebra-factorizacion', 'algebra-expresiones', 'numeros-mcd-mcm', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-153',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: 'x^2 + 6x + 9',
    question: 'Un jardinero diseña un jardín cuadrado de lado (x + 3) metros. Al calcular el área total del jardín expandiendo la expresión, obtiene x² + 6x + 9 metros cuadrados. Un inspector municipal necesita verificar que esta expresión corresponde efectivamente a un cuadrado perfecto para aprobar el diseño. ¿Cuál es la factorización que demuestra que es un trinomio cuadrado perfecto?',
    questionLatex: '\\text{Un jardinero diseña un jardín cuadrado de lado } (x + 3) \\text{ metros. Al calcular el área total del jardín expandiendo la expresión, obtiene } x^2 + 6x + 9 \\text{ metros cuadrados. Un inspector municipal necesita verificar que esta expresión corresponde efectivamente a un cuadrado perfecto para aprobar el diseño. ¿Cuál es la factorización que demuestra que es un trinomio cuadrado perfecto?}',
    options: ['$(x + 3)^2$', '$(x - 3)^2$', '$(x + 3)(x - 3)$', '$(x + 9)(x + 1)$'],
    optionsLatex: ['(x + 3)^2', '(x - 3)^2', '(x + 3)(x - 3)', '(x + 9)(x + 1)'],
    correctAnswer: 0,
    explanation: 'Identificamos que es un trinomio cuadrado perfecto con la forma a² + 2ab + b². Aquí x² + 6x + 9 = x² + 2(x)(3) + 3² = (x + 3)².',
    explanationLatex: 'x^2 + 6x + 9 = x^2 + 2(x)(3) + 3^2 = (x + 3)^2',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-154',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '4x^2 - 12x + 9',
    question: 'Una fábrica produce paneles cuadrados para construcción. El área de cada panel está dada por la expresión 4x² - 12x + 9 metros cuadrados, donde x es un parámetro de diseño. El ingeniero de calidad necesita factorizar esta expresión para verificar que representa un cuadrado perfecto y calcular la longitud del lado del panel. ¿Cuál es la factorización correcta?',
    questionLatex: '\\text{Una fábrica produce paneles cuadrados para construcción. El área de cada panel está dada por la expresión } 4x^2 - 12x + 9 \\text{ metros cuadrados, donde x es un parámetro de diseño. El ingeniero de calidad necesita factorizar esta expresión para verificar que representa un cuadrado perfecto y calcular la longitud del lado del panel. ¿Cuál es la factorización correcta?}',
    options: ['$(2x - 3)^2$', '$(2x + 3)^2$', '$(4x - 3)^2$', '$(x - 3)^2$'],
    optionsLatex: ['(2x - 3)^2', '(2x + 3)^2', '(4x - 3)^2', '(x - 3)^2'],
    correctAnswer: 0,
    explanation: 'Es un trinomio cuadrado perfecto: 4x² - 12x + 9 = (2x)² - 2(2x)(3) + 3² = (2x - 3)². El lado del panel mide (2x - 3) metros.',
    explanationLatex: '4x^2 - 12x + 9 = (2x)^2 - 2(2x)(3) + 3^2 = (2x - 3)^2',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-155',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: 'x^2 + 4x + 4',
    question: 'Un arquitecto analiza cuatro diseños diferentes de pisos cuadrados para un proyecto habitacional. Las áreas propuestas son: x² + 4x + 4, x² + 4x + 2, x² + 2x + 4, y x² + 8x + 4 metros cuadrados. El arquitecto necesita identificar cuál de estas expresiones representa un trinomio cuadrado perfecto, es decir, el área de un cuadrado real. ¿Cuál expresión es un trinomio cuadrado perfecto?',
    questionLatex: '\\text{Un arquitecto analiza cuatro diseños diferentes de pisos cuadrados para un proyecto habitacional. Las áreas propuestas son: } x^2 + 4x + 4, x^2 + 4x + 2, x^2 + 2x + 4, \\text{ y } x^2 + 8x + 4 \\text{ metros cuadrados. El arquitecto necesita identificar cuál de estas expresiones representa un trinomio cuadrado perfecto, es decir, el área de un cuadrado real. ¿Cuál expresión es un trinomio cuadrado perfecto?}',
    options: ['$x^2 + 4x + 4$', '$x^2 + 4x + 2$', '$x^2 + 2x + 4$', '$x^2 + 8x + 4$'],
    optionsLatex: ['x^2 + 4x + 4', 'x^2 + 4x + 2', 'x^2 + 2x + 4', 'x^2 + 8x + 4'],
    correctAnswer: 0,
    explanation: 'Para ser trinomio cuadrado perfecto, el término constante debe ser el cuadrado de la mitad del coeficiente de x. En x² + 4x + 4: (4/2)² = 2² = 4 ✓. Factorización: x² + 4x + 4 = (x + 2)².',
    explanationLatex: 'x^2 + 4x + 4 = x^2 + 2(x)(2) + 2^2 = (x + 2)^2 \\text{ es TCP}',
    difficulty: 'hard',
    skills: ['algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-156',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: 'x^2 + 7x + 12',
    question: 'Una empresa de eventos organiza mesas rectangulares para una conferencia. El área de cada zona de mesas está representada por x² + 7x + 12 metros cuadrados, donde x es una medida base en metros. El coordinador necesita factorizar esta expresión para encontrar dos dimensiones enteras posibles que faciliten la distribución de las mesas. ¿Cuál es la factorización correcta?',
    questionLatex: '\\text{Una empresa de eventos organiza mesas rectangulares para una conferencia. El área de cada zona de mesas está representada por } x^2 + 7x + 12 \\text{ metros cuadrados, donde x es una medida base en metros. El coordinador necesita factorizar esta expresión para encontrar dos dimensiones enteras posibles que faciliten la distribución de las mesas. ¿Cuál es la factorización correcta?}',
    options: ['$(x + 3)(x + 4)$', '$(x + 2)(x + 6)$', '$(x + 1)(x + 12)$', '$(x + 3)(x + 5)$'],
    optionsLatex: ['(x + 3)(x + 4)', '(x + 2)(x + 6)', '(x + 1)(x + 12)', '(x + 3)(x + 5)'],
    correctAnswer: 0,
    explanation: 'Buscamos dos números que sumen 7 y multipliquen 12. Esos números son 3 y 4, ya que 3 + 4 = 7 y 3 × 4 = 12. Por lo tanto: x² + 7x + 12 = (x + 3)(x + 4).',
    explanationLatex: 'x^2 + 7x + 12 = (x + 3)(x + 4) \\quad \\text{porque } 3 + 4 = 7 \\text{ y } 3 \\times 4 = 12',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-157',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: 'x^2 - 5x + 6',
    question: 'Un programador optimiza el rendimiento de un algoritmo cuyo tiempo de ejecución está modelado por x² - 5x + 6 milisegundos, donde x es el tamaño de los datos de entrada. Para identificar los puntos críticos del algoritmo, necesita factorizar esta expresión cuadrática. ¿Cuál es la factorización correcta?',
    questionLatex: '\\text{Un programador optimiza el rendimiento de un algoritmo cuyo tiempo de ejecución está modelado por } x^2 - 5x + 6 \\text{ milisegundos, donde x es el tamaño de los datos de entrada. Para identificar los puntos críticos del algoritmo, necesita factorizar esta expresión cuadrática. ¿Cuál es la factorización correcta?}',
    options: ['$(x - 2)(x - 3)$', '$(x + 2)(x + 3)$', '$(x - 1)(x - 6)$', '$(x - 2)(x + 3)$'],
    optionsLatex: ['(x - 2)(x - 3)', '(x + 2)(x + 3)', '(x - 1)(x - 6)', '(x - 2)(x + 3)'],
    correctAnswer: 0,
    explanation: 'Buscamos dos números que sumen -5 y multipliquen 6. Esos números son -2 y -3, ya que (-2) + (-3) = -5 y (-2) × (-3) = 6. Por lo tanto: x² - 5x + 6 = (x - 2)(x - 3).',
    explanationLatex: 'x^2 - 5x + 6 = (x - 2)(x - 3) \\quad \\text{porque } (-2) + (-3) = -5 \\text{ y } (-2)(-3) = 6',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-158',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: 'x^2 + 2x - 15',
    question: 'Un biólogo modela el crecimiento poblacional de una colonia de bacterias usando la función x² + 2x - 15, donde x representa las horas transcurridas desde el inicio del experimento. Para analizar cuándo la población alcanza valores específicos, necesita factorizar esta expresión cuadrática. ¿Cuál es la factorización correcta?',
    questionLatex: '\\text{Un biólogo modela el crecimiento poblacional de una colonia de bacterias usando la función } x^2 + 2x - 15, \\text{ donde x representa las horas transcurridas desde el inicio del experimento. Para analizar cuándo la población alcanza valores específicos, necesita factorizar esta expresión cuadrática. ¿Cuál es la factorización correcta?}',
    options: ['$(x + 5)(x - 3)$', '$(x - 5)(x + 3)$', '$(x + 15)(x - 1)$', '$(x + 3)(x - 5)$'],
    optionsLatex: ['(x + 5)(x - 3)', '(x - 5)(x + 3)', '(x + 15)(x - 1)', '(x + 3)(x - 5)'],
    correctAnswer: 0,
    explanation: 'Buscamos dos números que sumen 2 y multipliquen -15. Esos números son 5 y -3, ya que 5 + (-3) = 2 y 5 × (-3) = -15. Por lo tanto: x² + 2x - 15 = (x + 5)(x - 3).',
    explanationLatex: 'x^2 + 2x - 15 = (x + 5)(x - 3) \\quad \\text{porque } 5 + (-3) = 2 \\text{ y } 5(-3) = -15',
    difficulty: 'hard',
    skills: ['algebra-factorizacion', 'numeros-enteros', 'numeros-operaciones-basicas']
,
  {
    id: 'm1-216',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '\\frac{6x^2}{3x}',
    question: 'Un vivero vende plantas en macetas cuadradas. Tiene un terreno de 6x² metros cuadrados disponible para cultivar plantas, donde x representa una unidad de medida estándar. Necesita dividir este terreno en 3x hileras de igual longitud. El gerente necesita simplificar la expresión que representa la longitud de cada hilera. ¿Cuál es la expresión simplificada?',
    questionLatex: '\\text{Un vivero vende plantas en macetas cuadradas. Tiene un terreno de } 6x^2 \\text{ metros cuadrados disponible para cultivar plantas, donde x representa una unidad de medida estándar. Necesita dividir este terreno en } 3x \\text{ hileras de igual longitud. El gerente necesita simplificar la expresión que representa la longitud de cada hilera. ¿Cuál es la expresión simplificada?}',
    options: ['$2x$', '$3x$', '$2x^2$', '$\\frac{2}{x}$'],
    optionsLatex: ['2x', '3x', '2x^2', '\\frac{2}{x}'],
    correctAnswer: 0,
    explanation: 'Dividimos el coeficiente (6 ÷ 3 = 2) y restamos los exponentes de x (2 - 1 = 1): 6x²/(3x) = 2x metros por hilera.',
    explanationLatex: '\\frac{6x^2}{3x} = \\frac{6}{3} \\times x^{2-1} = 2x',
    difficulty: 'easy',
    skills: ['algebra-expresiones-racionales', 'algebra-simplificacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-217',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '\\frac{x^2 - 4}{x + 2}',
    question: 'Un ingeniero civil diseña una piscina rectangular. El área de la superficie es (x² - 4) metros cuadrados, y uno de los lados mide (x + 2) metros, donde x es un parámetro de diseño. Para calcular la longitud del otro lado, necesita dividir el área entre el lado conocido y simplificar la expresión racional resultante. ¿Cuál es la expresión simplificada del otro lado?',
    questionLatex: '\\text{Un ingeniero civil diseña una piscina rectangular. El área de la superficie es } (x^2 - 4) \\text{ metros cuadrados, y uno de los lados mide } (x + 2) \\text{ metros, donde x es un parámetro de diseño. Para calcular la longitud del otro lado, necesita dividir el área entre el lado conocido y simplificar la expresión racional resultante. ¿Cuál es la expresión simplificada del otro lado?}',
    options: ['$x - 2$', '$x + 2$', '$x^2 - 2$', '$\\frac{x - 4}{1}$'],
    optionsLatex: ['x - 2', 'x + 2', 'x^2 - 2', '\\frac{x - 4}{1}'],
    correctAnswer: 0,
    explanation: 'Factorizamos el numerador como diferencia de cuadrados: (x² - 4) = (x - 2)(x + 2). Simplificamos: [(x - 2)(x + 2)]/(x + 2) = x - 2 metros.',
    explanationLatex: '\\frac{x^2 - 4}{x + 2} = \\frac{(x - 2)(x + 2)}{x + 2} = x - 2',
    difficulty: 'medium',
    skills: ['algebra-expresiones-racionales', 'algebra-simplificacion', 'algebra-factorizacion', 'algebra-diferencia-cuadrados']
  },
  {
    id: 'm1-218',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '\\frac{x^2 + 5x + 6}{x^2 + 3x + 2}',
    question: 'Un economista compara dos índices de crecimiento económico. El índice de producción está dado por (x² + 5x + 6) puntos y el índice de consumo por (x² + 3x + 2) puntos, donde x representa trimestres. Para calcular la razón entre producción y consumo, necesita dividir ambas expresiones y simplificar completamente la fracción racional resultante. ¿Cuál es la expresión simplificada de esta razón?',
    questionLatex: '\\text{Un economista compara dos índices de crecimiento económico. El índice de producción está dado por } (x^2 + 5x + 6) \\text{ puntos y el índice de consumo por } (x^2 + 3x + 2) \\text{ puntos, donde x representa trimestres. Para calcular la razón entre producción y consumo, necesita dividir ambas expresiones y simplificar completamente la fracción racional resultante. ¿Cuál es la expresión simplificada de esta razón?}',
    options: ['$\\frac{x + 3}{x + 1}$', '$\\frac{x + 2}{x + 1}$', '$\\frac{x + 3}{x + 2}$', '$\\frac{x + 6}{x + 2}$'],
    optionsLatex: ['\\frac{x + 3}{x + 1}', '\\frac{x + 2}{x + 1}', '\\frac{x + 3}{x + 2}', '\\frac{x + 6}{x + 2}'],
    correctAnswer: 0,
    explanation: 'Factorizamos numerador y denominador: (x² + 5x + 6) = (x + 2)(x + 3) y (x² + 3x + 2) = (x + 1)(x + 2). Simplificamos el factor común: [(x + 2)(x + 3)]/[(x + 1)(x + 2)] = (x + 3)/(x + 1).',
    explanationLatex: '\\frac{(x + 2)(x + 3)}{(x + 1)(x + 2)} = \\frac{x + 3}{x + 1}',
    difficulty: 'hard',
    skills: ['algebra-expresiones-racionales', 'algebra-simplificacion', 'algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-219',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '\\frac{2x}{3} \\times \\frac{6}{x}',
    question: 'Una fábrica de chocolates produce barras en lotes. Cada lote contiene (2x)/3 kilogramos de chocolate, donde x representa unidades de producción. Para empacar, multiplican esta cantidad por un factor de conversión de 6/x. El supervisor necesita simplificar la expresión que representa la cantidad final de chocolate por lote. ¿Cuál es el resultado simplificado?',
    questionLatex: '\\text{Una fábrica de chocolates produce barras en lotes. Cada lote contiene } \\frac{2x}{3} \\text{ kilogramos de chocolate, donde x representa unidades de producción. Para empacar, multiplican esta cantidad por un factor de conversión de } \\frac{6}{x}. \\text{ El supervisor necesita simplificar la expresión que representa la cantidad final de chocolate por lote. ¿Cuál es el resultado simplificado?}',
    options: ['4', '$\\frac{12x}{3x}$', '$\\frac{2x}{x}$', '12'],
    correctAnswer: 0,
    explanation: 'Multiplicamos numeradores y denominadores: (2x × 6)/(3 × x) = 12x/(3x). Simplificamos dividiendo numerador y denominador por 3x: 12x/(3x) = 4 kilogramos.',
    explanationLatex: '\\frac{2x}{3} \\times \\frac{6}{x} = \\frac{2x \\times 6}{3 \\times x} = \\frac{12x}{3x} = 4',
    difficulty: 'easy',
    skills: ['algebra-expresiones-racionales', 'algebra-multiplicacion-fracciones', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-220',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '\\frac{x^2}{2} \\div \\frac{x}{4}',
    question: 'Un agricultor tiene un terreno de área (x²)/2 hectáreas que desea dividir en parcelas. Cada parcela debe tener un ancho de x/4 hectáreas. Para calcular cuántas parcelas puede formar, necesita dividir el área total entre el ancho de cada parcela y simplificar la expresión resultante. ¿Cuántas parcelas puede formar?',
    questionLatex: '\\text{Un agricultor tiene un terreno de área } \\frac{x^2}{2} \\text{ hectáreas que desea dividir en parcelas. Cada parcela debe tener un ancho de } \\frac{x}{4} \\text{ hectáreas. Para calcular cuántas parcelas puede formar, necesita dividir el área total entre el ancho de cada parcela y simplificar la expresión resultante. ¿Cuántas parcelas puede formar?}',
    options: ['$2x$', '$\\frac{x^2}{8}$', '$\\frac{x}{2}$', '$4x$'],
    optionsLatex: ['2x', '\\frac{x^2}{8}', '\\frac{x}{2}', '4x'],
    correctAnswer: 0,
    explanation: 'Para dividir fracciones, multiplicamos por el recíproco: (x²/2) ÷ (x/4) = (x²/2) × (4/x) = (4x²)/(2x). Simplificamos: 4x²/(2x) = 2x parcelas.',
    explanationLatex: '\\frac{x^2}{2} \\div \\frac{x}{4} = \\frac{x^2}{2} \\times \\frac{4}{x} = \\frac{4x^2}{2x} = 2x',
    difficulty: 'medium',
    skills: ['algebra-expresiones-racionales', 'algebra-division-fracciones', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-221',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '\\frac{2}{x} + \\frac{3}{x}',
    question: 'Un químico mezcla dos soluciones en un laboratorio. La primera solución tiene una concentración de 2/x moles por litro, y la segunda tiene 3/x moles por litro, donde x es un factor de dilución. Para calcular la concentración total de la mezcla, necesita sumar ambas fracciones racionales. ¿Cuál es la concentración total simplificada?',
    questionLatex: '\\text{Un químico mezcla dos soluciones en un laboratorio. La primera solución tiene una concentración de } \\frac{2}{x} \\text{ moles por litro, y la segunda tiene } \\frac{3}{x} \\text{ moles por litro, donde x es un factor de dilución. Para calcular la concentración total de la mezcla, necesita sumar ambas fracciones racionales. ¿Cuál es la concentración total simplificada?}',
    options: ['$\\frac{5}{x}$', '$\\frac{5}{2x}$', '$\\frac{2x + 3}{x}$', '$5x$'],
    optionsLatex: ['\\frac{5}{x}', '\\frac{5}{2x}', '\\frac{2x + 3}{x}', '5x'],
    correctAnswer: 0,
    explanation: 'Como ambas fracciones tienen el mismo denominador x, sumamos los numeradores: 2/x + 3/x = (2 + 3)/x = 5/x moles por litro.',
    explanationLatex: '\\frac{2}{x} + \\frac{3}{x} = \\frac{2 + 3}{x} = \\frac{5}{x}',
    difficulty: 'easy',
    skills: ['algebra-expresiones-racionales', 'algebra-suma-fracciones', 'numeros-fracciones', 'numeros-operaciones-basicas']
];
