import { Question } from '../../../types';

export const m1AlgebraProductosNotablesQuestions: Question[] = [
  {
    id: 'm1-31',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(x + 3)(x + 2)',
    question: 'Un diseñador de jardines planifica un área rectangular para plantar flores. El largo del jardín es (x + 3) metros y el ancho es (x + 2) metros, donde x representa una medida base que depende del terreno disponible. El diseñador necesita calcular el área total del jardín expandiendo el producto de estas dos dimensiones para estimar cuántos metros cuadrados de césped necesitará. ¿Cuál es la expresión expandida que representa el área?',
    questionLatex: '\\text{Un diseñador de jardines planifica un área rectangular para plantar flores. El largo del jardín es } (x + 3) \\text{ metros y el ancho es } (x + 2) \\text{ metros, donde x representa una medida base que depende del terreno disponible. El diseñador necesita calcular el área total del jardín expandiendo el producto de estas dos dimensiones para estimar cuántos metros cuadrados de césped necesitará. ¿Cuál es la expresión expandida que representa el área?}',
    options: ['$x^2 + 5x + 6$', '$x^2 + 6x + 5$', '$x^2 + 5x + 5$', '$x^2 + 6x + 6$'],
    optionsLatex: ['x^2 + 5x + 6', 'x^2 + 6x + 5', 'x^2 + 5x + 5', 'x^2 + 6x + 6'],
    correctAnswer: 0,
    explanation: 'Aplicamos la propiedad distributiva multiplicando cada término del primer binomio por cada término del segundo: x(x) + x(2) + 3(x) + 3(2) = x² + 2x + 3x + 6 = x² + 5x + 6.',
    explanationLatex: '(x + 3)(x + 2) = x^2 + 2x + 3x + 6 = x^2 + 5x + 6',
    difficulty: 'medium',
    skills: ['algebra-expansion', 'algebra-propiedad-distributiva', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-159',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(x + 5)^2',
    question: 'Una compañía constructora diseña patios cuadrados para viviendas. Cada patio tiene un lado que mide (x + 5) metros, donde x es ajustable según el tamaño de la casa. Para calcular el área total que ocupará cada patio y estimar el costo del pavimento, el ingeniero necesita expandir la expresión del cuadrado del lado. ¿Cuál es la expresión expandida del área?',
    questionLatex: '\\text{Una compañía constructora diseña patios cuadrados para viviendas. Cada patio tiene un lado que mide } (x + 5) \\text{ metros, donde x es ajustable según el tamaño de la casa. Para calcular el área total que ocupará cada patio y estimar el costo del pavimento, el ingeniero necesita expandir la expresión del cuadrado del lado. ¿Cuál es la expresión expandida del área?}',
    options: ['$x^2 + 25$', '$x^2 + 10x + 25$', '$x^2 + 5x + 25$', '$x^2 + 10x + 10$'],
    optionsLatex: ['x^2 + 25', 'x^2 + 10x + 25', 'x^2 + 5x + 25', 'x^2 + 10x + 10'],
    correctAnswer: 1,
    explanation: 'Aplicamos la fórmula del cuadrado de un binomio (a + b)² = a² + 2ab + b². Con a = x y b = 5: (x + 5)² = x² + 2(x)(5) + 5² = x² + 10x + 25.',
    explanationLatex: '(x + 5)^2 = x^2 + 2(x)(5) + 5^2 = x^2 + 10x + 25',
    difficulty: 'easy',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-160',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(2x - 3)^2',
    question: 'Un fabricante de marcos rectangulares reduce las medidas de sus productos. El lado de un marco cuadrado nuevo mide (2x - 3) centímetros, donde x es el estándar de fabricación y 3 centímetros es la reducción aplicada. Para calcular el área del material necesario, el supervisor necesita expandir el cuadrado de esta expresión. ¿Cuál es el resultado de la expansión?',
    questionLatex: '\\text{Un fabricante de marcos rectangulares reduce las medidas de sus productos. El lado de un marco cuadrado nuevo mide } (2x - 3) \\text{ centímetros, donde x es el estándar de fabricación y 3 centímetros es la reducción aplicada. Para calcular el área del material necesario, el supervisor necesita expandir el cuadrado de esta expresión. ¿Cuál es el resultado de la expansión?}',
    options: ['$4x^2 - 12x + 9$', '$4x^2 + 12x + 9$', '$4x^2 - 6x + 9$', '$2x^2 - 6x + 9$'],
    optionsLatex: ['4x^2 - 12x + 9', '4x^2 + 12x + 9', '4x^2 - 6x + 9', '2x^2 - 6x + 9'],
    correctAnswer: 0,
    explanation: 'Aplicamos (a - b)² = a² - 2ab + b² con a = 2x y b = 3: (2x - 3)² = (2x)² - 2(2x)(3) + 3² = 4x² - 12x + 9.',
    explanationLatex: '(2x - 3)^2 = (2x)^2 - 2(2x)(3) + 3^2 = 4x^2 - 12x + 9',
    difficulty: 'medium',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-161',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(3a + 2b)^2',
    question: 'Un químico prepara una solución combinando dos reactivos en proporciones específicas. La concentración resultante está modelada por el cuadrado de la expresión (3a + 2b), donde a y b son las concentraciones iniciales de cada reactivo en moles por litro. El químico necesita expandir esta expresión para calcular la concentración final exacta. ¿Cuál es el resultado correcto de la expansión?',
    questionLatex: '\\text{Un químico prepara una solución combinando dos reactivos en proporciones específicas. La concentración resultante está modelada por el cuadrado de la expresión } (3a + 2b), \\text{ donde a y b son las concentraciones iniciales de cada reactivo en moles por litro. El químico necesita expandir esta expresión para calcular la concentración final exacta. ¿Cuál es el resultado correcto de la expansión?}',
    options: ['$9a^2 + 4b^2$', '$9a^2 + 6ab + 4b^2$', '$9a^2 + 12ab + 4b^2$', '$3a^2 + 12ab + 2b^2$'],
    optionsLatex: ['9a^2 + 4b^2', '9a^2 + 6ab + 4b^2', '9a^2 + 12ab + 4b^2', '3a^2 + 12ab + 2b^2'],
    correctAnswer: 2,
    explanation: 'Aplicamos (a + b)² = a² + 2ab + b² donde a = 3a y b = 2b: (3a + 2b)² = (3a)² + 2(3a)(2b) + (2b)² = 9a² + 12ab + 4b².',
    explanationLatex: '(3a + 2b)^2 = (3a)^2 + 2(3a)(2b) + (2b)^2 = 9a^2 + 12ab + 4b^2',
    difficulty: 'hard',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-162',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(x + 4)(x - 4)',
    question: 'Un terreno cuadrado de lado x metros se modifica para convertirlo en dos parcelas rectangulares. Una parcela aumenta 4 metros en una dirección resultando en (x + 4) metros, mientras que la otra parcela disminuye 4 metros en la dirección perpendicular resultando en (x - 4) metros. Un agrimensor necesita calcular el área del rectángulo que se forma al multiplicar estas dos dimensiones. ¿Cuál es la expresión simplificada del área?',
    questionLatex: '\\text{Un terreno cuadrado de lado x metros se modifica para convertirlo en dos parcelas rectangulares. Una parcela aumenta 4 metros en una dirección resultando en } (x + 4) \\text{ metros, mientras que la otra parcela disminuye 4 metros en la dirección perpendicular resultando en } (x - 4) \\text{ metros. Un agrimensor necesita calcular el área del rectángulo que se forma al multiplicar estas dos dimensiones. ¿Cuál es la expresión simplificada del área?}',
    options: ['$x^2 - 16$', '$x^2 + 16$', '$x^2 - 8x - 16$', '$x^2 + 8x - 16$'],
    optionsLatex: ['x^2 - 16', 'x^2 + 16', 'x^2 - 8x - 16', 'x^2 + 8x - 16'],
    correctAnswer: 0,
    explanation: 'Aplicamos la fórmula de diferencia de cuadrados (a + b)(a - b) = a² - b². Con a = x y b = 4: (x + 4)(x - 4) = x² - 4² = x² - 16.',
    explanationLatex: '(x + 4)(x - 4) = x^2 - 4^2 = x^2 - 16',
    difficulty: 'easy',
    skills: ['algebra-productos-notables', 'algebra-diferencia-cuadrados', 'algebra-expansion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-163',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(3x + 5)(3x - 5)',
    question: 'Una empresa textil fabrica alfombras rectangulares. El largo de cada alfombra es (3x + 5) centímetros y el ancho es (3x - 5) centímetros, donde x es un parámetro de producción estándar. El gerente de producción necesita calcular el área de cada alfombra expandiendo el producto de estas dimensiones. ¿Cuál es la expresión simplificada del área?',
    questionLatex: '\\text{Una empresa textil fabrica alfombras rectangulares. El largo de cada alfombra es } (3x + 5) \\text{ centímetros y el ancho es } (3x - 5) \\text{ centímetros, donde x es un parámetro de producción estándar. El gerente de producción necesita calcular el área de cada alfombra expandiendo el producto de estas dimensiones. ¿Cuál es la expresión simplificada del área?}',
    options: ['$3x^2 - 25$', '$9x^2 - 25$', '$9x^2 - 30x - 25$', '$9x^2 + 25$'],
    optionsLatex: ['3x^2 - 25', '9x^2 - 25', '9x^2 - 30x - 25', '9x^2 + 25'],
    correctAnswer: 1,
    explanation: 'Aplicamos la diferencia de cuadrados (a + b)(a - b) = a² - b² con a = 3x y b = 5: (3x + 5)(3x - 5) = (3x)² - 5² = 9x² - 25.',
    explanationLatex: '(3x + 5)(3x - 5) = (3x)^2 - 5^2 = 9x^2 - 25',
    difficulty: 'medium',
    skills: ['algebra-productos-notables', 'algebra-diferencia-cuadrados', 'algebra-expansion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-164',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(x + 3)(x - 3)',
    question: 'Un terreno cuadrado de lado x metros se modifica para un proyecto de urbanización. Se expande 3 metros en la dirección norte resultando en (x + 3) metros, pero se reduce 3 metros en la dirección este resultando en (x - 3) metros. El planificador urbano necesita calcular el área del terreno rectangular resultante. ¿Cuál es la expresión que representa esta área?',
    questionLatex: '\\text{Un terreno cuadrado de lado x metros se modifica para un proyecto de urbanización. Se expande 3 metros en la dirección norte resultando en } (x + 3) \\text{ metros, pero se reduce 3 metros en la dirección este resultando en } (x - 3) \\text{ metros. El planificador urbano necesita calcular el área del terreno rectangular resultante. ¿Cuál es la expresión que representa esta área?}',
    options: ['$x^2$ m²', '$x^2 - 9$ m²', '$x^2 + 9$ m²', '$x^2 - 6x - 9$ m²'],
    optionsLatex: ['x^2 \\text{ m}^2', 'x^2 - 9 \\text{ m}^2', 'x^2 + 9 \\text{ m}^2', 'x^2 - 6x - 9 \\text{ m}^2'],
    correctAnswer: 1,
    explanation: 'El área es el producto de las dimensiones (x + 3)(x - 3), que es una diferencia de cuadrados: (x + 3)(x - 3) = x² - 9 m².',
    explanationLatex: '\\text{Área} = (x + 3)(x - 3) = x^2 - 9 \\text{ m}^2',
    difficulty: 'hard',
    skills: ['algebra-productos-notables', 'algebra-diferencia-cuadrados', 'geometria-area', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-165',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(x + 2)^3',
    question: 'Un ingeniero diseña contenedores cúbicos de almacenamiento. El lado de cada cubo mide (x + 2) decímetros, donde x es una medida estándar variable. Para calcular el volumen total de cada contenedor y estimar la capacidad de almacenamiento, necesita elevar esta expresión al cubo. ¿Cuál es la expresión expandida del volumen?',
    questionLatex: '\\text{Un ingeniero diseña contenedores cúbicos de almacenamiento. El lado de cada cubo mide } (x + 2) \\text{ decímetros, donde x es una medida estándar variable. Para calcular el volumen total de cada contenedor y estimar la capacidad de almacenamiento, necesita elevar esta expresión al cubo. ¿Cuál es la expresión expandida del volumen?}',
    options: ['$x^3 + 6x^2 + 12x + 8$', '$x^3 + 8$', '$x^3 + 2x^2 + 4x + 8$', '$x^3 + 6x^2 + 8x + 8$'],
    optionsLatex: ['x^3 + 6x^2 + 12x + 8', 'x^3 + 8', 'x^3 + 2x^2 + 4x + 8', 'x^3 + 6x^2 + 8x + 8'],
    correctAnswer: 0,
    explanation: 'Aplicamos (a + b)³ = a³ + 3a²b + 3ab² + b³ con a = x y b = 2: (x + 2)³ = x³ + 3x²(2) + 3x(4) + 8 = x³ + 6x² + 12x + 8.',
    explanationLatex: '(x + 2)^3 = x^3 + 3x^2(2) + 3x(2^2) + 2^3 = x^3 + 6x^2 + 12x + 8',
    difficulty: 'medium',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-166',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(x - 1)^3',
    question: 'Un escultor crea bloques cúbicos de mármol. Cada bloque tiene un lado de (x - 1) centímetros, donde x es la medida del bloque original y 1 centímetro es el pulido que se remueve de cada lado. Para calcular el volumen final de mármol utilizable en cada pieza, necesita expandir el cubo de esta expresión. ¿Cuál es el resultado de la expansión?',
    questionLatex: '\\text{Un escultor crea bloques cúbicos de mármol. Cada bloque tiene un lado de } (x - 1) \\text{ centímetros, donde x es la medida del bloque original y 1 centímetro es el pulido que se remueve de cada lado. Para calcular el volumen final de mármol utilizable en cada pieza, necesita expandir el cubo de esta expresión. ¿Cuál es el resultado de la expansión?}',
    options: ['$x^3 - 3x^2 + 3x - 1$', '$x^3 - 1$', '$x^3 - x^2 - x - 1$', '$x^3 + 3x^2 - 3x + 1$'],
    optionsLatex: ['x^3 - 3x^2 + 3x - 1', 'x^3 - 1', 'x^3 - x^2 - x - 1', 'x^3 + 3x^2 - 3x + 1'],
    correctAnswer: 0,
    explanation: 'Aplicamos (a - b)³ = a³ - 3a²b + 3ab² - b³ con a = x y b = 1: (x - 1)³ = x³ - 3x²(1) + 3x(1) - 1 = x³ - 3x² + 3x - 1.',
    explanationLatex: '(x - 1)^3 = x^3 - 3x^2(1) + 3x(1^2) - 1^3 = x^3 - 3x^2 + 3x - 1',
    difficulty: 'medium',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-167',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    operacionBase: '(2x + 1)^3',
    question: 'Un físico analiza la expansión de un gas en un contenedor cúbico. El lado del contenedor crece según la expresión (2x + 1) centímetros, donde x representa el tiempo en segundos desde que inicia la expansión. Para modelar el volumen del gas en función del tiempo, necesita expandir el cubo de esta expresión. Al hacerlo, el físico necesita identificar el coeficiente del término cuadrático x². ¿Cuál es este coeficiente?',
    questionLatex: '\\text{Un físico analiza la expansión de un gas en un contenedor cúbico. El lado del contenedor crece según la expresión } (2x + 1) \\text{ centímetros, donde x representa el tiempo en segundos desde que inicia la expansión. Para modelar el volumen del gas en función del tiempo, necesita expandir el cubo de esta expresión. Al hacerlo, el físico necesita identificar el coeficiente del término cuadrático } x^2. \\text{ ¿Cuál es este coeficiente?}',
    options: ['6', '12', '24', '8'],
    correctAnswer: 1,
    explanation: 'Expandimos (2x + 1)³ usando (a + b)³ = a³ + 3a²b + 3ab² + b³: (2x)³ + 3(2x)²(1) + 3(2x)(1)² + 1³ = 8x³ + 12x² + 6x + 1. El coeficiente de x² es 12.',
    explanationLatex: '(2x + 1)^3 = (2x)^3 + 3(2x)^2(1) + 3(2x)(1)^2 + 1^3 = 8x^3 + 12x^2 + 6x + 1',
    difficulty: 'hard',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-potencias', 'numeros-operaciones-basicas']
  }
];
