import { Question } from '../../../types';

export const m1AlgebraSistemasEcuacionesQuestions: Question[] = [
  {
    id: 'm1-183',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver el sistema: $\\begin{cases} y = 2x \\\\ x + y = 6 \\end{cases}$',
    questionLatex: '\\text{Resolver el sistema: } \\begin{cases} y = 2x \\\\ x + y = 6 \\end{cases}',
    options: ['$x = 2, y = 4$', '$x = 3, y = 3$', '$x = 4, y = 2$', '$x = 1, y = 5$'],
    optionsLatex: ['x = 2, y = 4', 'x = 3, y = 3', 'x = 4, y = 2', 'x = 1, y = 5'],
    correctAnswer: 0,
    explanation: 'Sustituimos $y = 2x$ en la segunda ecuación:',
    explanationLatex: 'x + 2x = 6 \\rightarrow 3x = 6 \\rightarrow x = 2 \\quad \\Rightarrow \\quad y = 2(2) = 4',
    difficulty: 'easy',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-184',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\begin{cases} x = y + 1 \\\\ 2x + y = 8 \\end{cases}$',
    questionLatex: '\\text{Resolver: } \\begin{cases} x = y + 1 \\\\ 2x + y = 8 \\end{cases}',
    options: ['$x = 2, y = 1$', '$x = 3, y = 2$', '$x = 4, y = 3$', '$x = 5, y = 4$'],
    optionsLatex: ['x = 2, y = 1', 'x = 3, y = 2', 'x = 4, y = 3', 'x = 5, y = 4'],
    correctAnswer: 1,
    explanation: 'Sustituimos $x = y + 1$ en la segunda ecuación:',
    explanationLatex: '2(y + 1) + y = 8 \\rightarrow 2y + 2 + y = 8 \\rightarrow 3y = 6 \\rightarrow y = 2 \\quad \\Rightarrow \\quad x = 2 + 1 = 3',
    difficulty: 'medium',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-ecuaciones-lineales', 'algebra-propiedad-distributiva', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-185',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\begin{cases} y = 3x - 1 \\\\ 2x - y = 5 \\end{cases}$',
    questionLatex: '\\text{Resolver: } \\begin{cases} y = 3x - 1 \\\\ 2x - y = 5 \\end{cases}',
    options: ['$x = 4, y = 11$', '$x = 6, y = 17$', '$x = 3, y = 8$', '$x = 5, y = 14$'],
    optionsLatex: ['x = 4, y = 11', 'x = 6, y = 17', 'x = 3, y = 8', 'x = 5, y = 14'],
    correctAnswer: 0,
    explanation: 'Sustituimos $y = 3x - 1$ en la segunda ecuación:',
    explanationLatex: '2x - (3x - 1) = 5 \\rightarrow 2x - 3x + 1 = 5 \\rightarrow -x = 4 \\rightarrow x = 4 \\quad \\Rightarrow \\quad y = 3(4) - 1 = 11',
    difficulty: 'medium',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-ecuaciones-lineales', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-186',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver por eliminación: $\\begin{cases} x + y = 7 \\\\ x - y = 3 \\end{cases}$',
    questionLatex: '\\text{Resolver por eliminación: } \\begin{cases} x + y = 7 \\\\ x - y = 3 \\end{cases}',
    options: ['$x = 5, y = 2$', '$x = 4, y = 3$', '$x = 6, y = 1$', '$x = 3, y = 4$'],
    optionsLatex: ['x = 5, y = 2', 'x = 4, y = 3', 'x = 6, y = 1', 'x = 3, y = 4'],
    correctAnswer: 0,
    explanation: 'Sumamos ambas ecuaciones para eliminar $y$:',
    explanationLatex: '(x + y) + (x - y) = 7 + 3 \\rightarrow 2x = 10 \\rightarrow x = 5 \\quad \\Rightarrow \\quad 5 + y = 7 \\rightarrow y = 2',
    difficulty: 'easy',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-187',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\begin{cases} 2x + y = 10 \\\\ 2x - y = 6 \\end{cases}$',
    questionLatex: '\\text{Resolver: } \\begin{cases} 2x + y = 10 \\\\ 2x - y = 6 \\end{cases}',
    options: ['$x = 4, y = 2$', '$x = 3, y = 4$', '$x = 5, y = 0$', '$x = 2, y = 6$'],
    optionsLatex: ['x = 4, y = 2', 'x = 3, y = 4', 'x = 5, y = 0', 'x = 2, y = 6'],
    correctAnswer: 0,
    explanation: 'Sumamos las ecuaciones para eliminar $y$:',
    explanationLatex: '(2x + y) + (2x - y) = 10 + 6 \\rightarrow 4x = 16 \\rightarrow x = 4 \\quad \\Rightarrow \\quad 2(4) + y = 10 \\rightarrow y = 2',
    difficulty: 'medium',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-188',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\begin{cases} 3x + 2y = 13 \\\\ 3x - y = 7 \\end{cases}$',
    questionLatex: '\\text{Resolver: } \\begin{cases} 3x + 2y = 13 \\\\ 3x - y = 7 \\end{cases}',
    options: ['$x = 2, y = 5$', '$x = 3, y = 2$', '$x = 4, y = 2$', '$x = 2, y = 3$'],
    optionsLatex: ['x = 2, y = 5', 'x = 3, y = 2', 'x = 4, y = 2', 'x = 2, y = 3'],
    correctAnswer: 1,
    explanation: 'Restamos la segunda ecuación de la primera para eliminar $3x$:',
    explanationLatex: '(3x + 2y) - (3x - y) = 13 - 7 \\rightarrow 3y = 6 \\rightarrow y = 2 \\quad \\Rightarrow \\quad 3x - 2 = 7 \\rightarrow x = 3',
    difficulty: 'hard',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-189',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'En una tienda, 2 cuadernos y 3 lápices cuestan $2.100. Si 1 cuaderno y 1 lápiz cuestan $900, ¿cuánto cuesta un cuaderno?',
    questionLatex: '\\text{2 cuadernos y 3 lápices cuestan \\$2.100. 1 cuaderno y 1 lápiz cuestan \\$900. ¿Cuánto cuesta un cuaderno?}',
    options: ['$500', '$600', '$700', '$800'],
    correctAnswer: 1,
    explanation: 'Planteamos el sistema con $c$ = cuaderno y $l$ = lápiz:',
    explanationLatex: '\\begin{cases} 2c + 3l = 2100 \\\\ c + l = 900 \\end{cases} \\rightarrow l = 900 - c \\rightarrow 2c + 3(900 - c) = 2100 \\rightarrow c = 600',
    difficulty: 'medium',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-190',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'La suma de dos números es 50 y su diferencia es 10. ¿Cuál es el número mayor?',
    questionLatex: '\\text{La suma de dos números es 50 y su diferencia es 10. ¿Cuál es el número mayor?}',
    options: ['25', '30', '35', '40'],
    correctAnswer: 1,
    explanation: 'Planteamos el sistema con $x$ e $y$ como los números:',
    explanationLatex: '\\begin{cases} x + y = 50 \\\\ x - y = 10 \\end{cases} \\rightarrow 2x = 60 \\rightarrow x = 30 \\text{ (número mayor)}',
    difficulty: 'easy',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-191',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Un estacionamiento cobra $a$ pesos por hora para autos y $m$ pesos por hora para motos. Si 3 autos y 2 motos pagan $5.000 en total, y 1 auto y 1 moto pagan $1.800, ¿cuánto cobra por hora para un auto?',
    questionLatex: '\\text{3 autos y 2 motos: \\$5.000. 1 auto y 1 moto: \\$1.800. ¿Cuánto cobra por auto?}',
    options: ['$600', '$800', '$1.000', '$1.200'],
    optionsLatex: ['\\$600', '\\$800', '\\$1.000', '\\$1.200'],
    correctAnswer: 3,
    explanation: 'Planteamos el sistema y resolvemos:',
    explanationLatex: '\\begin{cases} 3a + 2m = 5000 \\\\ a + m = 1800 \\end{cases} \\rightarrow m = 1800 - a \\rightarrow 3a + 2(1800 - a) = 5000 \\rightarrow a = 1200',
    difficulty: 'hard',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  }
];
