// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/m1/index.mdx?collection=docs"), "algebra/ecuaciones-inecuaciones.mdx": () => import("../content/docs/m1/algebra/ecuaciones-inecuaciones.mdx?collection=docs"), "algebra/expresiones-algebraicas.mdx": () => import("../content/docs/m1/algebra/expresiones-algebraicas.mdx?collection=docs"), "algebra/funciones-cuadraticas.mdx": () => import("../content/docs/m1/algebra/funciones-cuadraticas.mdx?collection=docs"), "algebra/funciones-lineales.mdx": () => import("../content/docs/m1/algebra/funciones-lineales.mdx?collection=docs"), "algebra/sistemas-ecuaciones.mdx": () => import("../content/docs/m1/algebra/sistemas-ecuaciones.mdx?collection=docs"), "geometria/perimetro-area.mdx": () => import("../content/docs/m1/geometria/perimetro-area.mdx?collection=docs"), "geometria/teorema-pitagoras.mdx": () => import("../content/docs/m1/geometria/teorema-pitagoras.mdx?collection=docs"), "geometria/transformaciones.mdx": () => import("../content/docs/m1/geometria/transformaciones.mdx?collection=docs"), "geometria/volumen.mdx": () => import("../content/docs/m1/geometria/volumen.mdx?collection=docs"), "numeros/enteros-racionales.mdx": () => import("../content/docs/m1/numeros/enteros-racionales.mdx?collection=docs"), "numeros/porcentaje.mdx": () => import("../content/docs/m1/numeros/porcentaje.mdx?collection=docs"), "numeros/potencias-raices.mdx": () => import("../content/docs/m1/numeros/potencias-raices.mdx?collection=docs"), "numeros/proporcionalidad.mdx": () => import("../content/docs/m1/numeros/proporcionalidad.mdx?collection=docs"), "probabilidad/medidas-posicion.mdx": () => import("../content/docs/m1/probabilidad/medidas-posicion.mdx?collection=docs"), "probabilidad/reglas-probabilidad.mdx": () => import("../content/docs/m1/probabilidad/reglas-probabilidad.mdx?collection=docs"), "probabilidad/tablas-graficos.mdx": () => import("../content/docs/m1/probabilidad/tablas-graficos.mdx?collection=docs"), "probabilidad/tendencia-central.mdx": () => import("../content/docs/m1/probabilidad/tendencia-central.mdx?collection=docs"), }),
};
export default browserCollections;