import { Question } from '../../../types';

export const m1NumerosEnterosRacionalesQuestions: Question[] = [
  {
    id: 'm1-9',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $\\frac{2}{3} + \\frac{1}{4}$?',
    questionLatex: '\\text{¿Cuál es el resultado de } \\frac{2}{3} + \\frac{1}{4}?',
    options: ['$\\frac{3}{7}$', '$\\frac{11}{12}$', '$\\frac{5}{6}$', '$\\frac{3}{4}$'],
    optionsLatex: ['\\frac{3}{7}', '\\frac{11}{12}', '\\frac{5}{6}', '\\frac{3}{4}'],
    correctAnswer: 1,
    explanation: 'Para sumar fracciones, necesitamos un denominador común:',
    explanationLatex: '\\frac{2}{3} + \\frac{1}{4} = \\frac{8}{12} + \\frac{3}{12} = \\frac{11}{12}',
    difficulty: 'easy',
    skills: ['numeros-fracciones-sumar-restar-distinto-denominador', 'numeros-simplificar-fracciones', 'numeros-jerarquia-operaciones']
  },
  {
    id: 'm1-11',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el Máximo Común Divisor (MCD) de 12 y 18?',
    questionLatex: '\\text{¿Cuál es el Máximo Común Divisor (MCD) de 12 y 18?}',
    options: ['2', '3', '6', '36'],
    correctAnswer: 2,
    explanation: 'Factorizamos ambos números y encontramos los factores comunes:',
    explanationLatex: '12 = 2^2 \\times 3, \\quad 18 = 2 \\times 3^2 \\quad \\Rightarrow \\quad \\text{MCD} = 2 \\times 3 = 6',
    difficulty: 'medium',
    skills: ['numeros-mcd-mcm', 'numeros-factorizacion-prima']
  },
  {
    id: 'm1-26',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $(-3) \\times (-5)$?',
    questionLatex: '\\text{¿Cuál es el resultado de } (-3) \\times (-5)?',
    options: ['-15', '-8', '8', '15'],
    correctAnswer: 3,
    explanation: 'El producto de dos números negativos es positivo:',
    explanationLatex: '(-3) \\times (-5) = 15',
    difficulty: 'easy',
    skills: ['numeros-enteros-multiplicar-dividir', 'numeros-patrones-signos', 'numeros-enteros-comprender-significado']
  },
  {
    id: 'm1-28',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Si $\\frac{3}{4}$ de un número es 15, ¿cuál es el número?',
    questionLatex: '\\text{Si } \\frac{3}{4} \\text{ de un número es 15, ¿cuál es el número?}',
    options: ['12', '18', '20', '24'],
    correctAnswer: 2,
    explanation: 'Planteamos la ecuación y despejamos:',
    explanationLatex: '\\frac{3}{4}x = 15 \\quad \\Rightarrow \\quad x = 15 \\times \\frac{4}{3} = 20',
    difficulty: 'medium',
    skills: ['numeros-fracciones-multiplicar-dividir', 'numeros-inverso-aditivo-multiplicativo', 'algebra-ecuaciones-lineales', 'algebra-despeje']
  },
  {
    id: 'm1-42',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $\\frac{2}{3} \\times \\frac{5}{4}$?',
    questionLatex: '\\text{¿Cuál es el resultado de } \\frac{2}{3} \\times \\frac{5}{4}?',
    options: ['$\\frac{7}{12}$', '$\\frac{10}{12}$', '$\\frac{5}{6}$', '$\\frac{10}{7}$'],
    optionsLatex: ['\\frac{7}{12}', '\\frac{10}{12}', '\\frac{5}{6}', '\\frac{10}{7}'],
    correctAnswer: 2,
    explanation: 'Para multiplicar fracciones, multiplicamos numerador por numerador y denominador por denominador:',
    explanationLatex: '\\frac{2}{3} \\times \\frac{5}{4} = \\frac{2 \\times 5}{3 \\times 4} = \\frac{10}{12} = \\frac{5}{6}',
    difficulty: 'easy',
    skills: ['numeros-fracciones-multiplicar-dividir', 'numeros-simplificar-fracciones']
  },
  {
    id: 'm1-43',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $\\frac{3}{4} \\div \\frac{2}{5}$?',
    questionLatex: '\\text{¿Cuál es el resultado de } \\frac{3}{4} \\div \\frac{2}{5}?',
    options: ['$\\frac{6}{20}$', '$\\frac{5}{8}$', '$\\frac{15}{8}$', '$\\frac{8}{15}$'],
    optionsLatex: ['\\frac{6}{20}', '\\frac{5}{8}', '\\frac{15}{8}', '\\frac{8}{15}'],
    correctAnswer: 2,
    explanation: 'Para dividir fracciones, multiplicamos por el recíproco (invertimos la segunda fracción):',
    explanationLatex: '\\frac{3}{4} \\div \\frac{2}{5} = \\frac{3}{4} \\times \\frac{5}{2} = \\frac{15}{8}',
    difficulty: 'medium',
    skills: ['numeros-fracciones-multiplicar-dividir', 'numeros-inverso-aditivo-multiplicativo']
  },
  {
    id: 'm1-44',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'María tiene $\\frac{2}{3}$ de un pastel y lo divide en 4 partes iguales. ¿Qué fracción del pastel completo es cada parte?',
    questionLatex: '\\text{María tiene } \\frac{2}{3} \\text{ de un pastel y lo divide en 4 partes iguales. ¿Qué fracción del pastel completo es cada parte?}',
    options: ['$\\frac{1}{6}$', '$\\frac{2}{12}$', '$\\frac{1}{8}$', '$\\frac{8}{3}$'],
    optionsLatex: ['\\frac{1}{6}', '\\frac{2}{12}', '\\frac{1}{8}', '\\frac{8}{3}'],
    correctAnswer: 0,
    explanation: 'Dividir una fracción entre un número entero es multiplicar por su recíproco:',
    explanationLatex: '\\frac{2}{3} \\div 4 = \\frac{2}{3} \\times \\frac{1}{4} = \\frac{2}{12} = \\frac{1}{6}',
    difficulty: 'medium',
    skills: ['numeros-fracciones-multiplicar-dividir', 'numeros-modelar-proporciones-repartos', 'numeros-interpretar-resultados-razonabilidad']
  },
  {
    id: 'm1-45',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Convierte el número mixto $2\\frac{3}{5}$ a fracción impropia:',
    questionLatex: '\\text{Convierte el número mixto } 2\\frac{3}{5} \\text{ a fracción impropia:}',
    options: ['$\\frac{8}{5}$', '$\\frac{11}{5}$', '$\\frac{13}{5}$', '$\\frac{6}{5}$'],
    optionsLatex: ['\\frac{8}{5}', '\\frac{11}{5}', '\\frac{13}{5}', '\\frac{6}{5}'],
    correctAnswer: 2,
    explanation: 'Multiplicamos el entero por el denominador y sumamos el numerador:',
    explanationLatex: '2\\frac{3}{5} = \\frac{(2 \\times 5) + 3}{5} = \\frac{10 + 3}{5} = \\frac{13}{5}',
    difficulty: 'easy',
    skills: ['numeros-fracciones-impropias-mixtos', 'numeros-jerarquia-operaciones']
  },
  {
    id: 'm1-46',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Convierte la fracción impropia $\\frac{17}{4}$ a número mixto:',
    questionLatex: '\\text{Convierte la fracción impropia } \\frac{17}{4} \\text{ a número mixto:}',
    options: ['$4\\frac{1}{4}$', '$3\\frac{5}{4}$', '$4\\frac{1}{17}$', '$5\\frac{2}{4}$'],
    optionsLatex: ['4\\frac{1}{4}', '3\\frac{5}{4}', '4\\frac{1}{17}', '5\\frac{2}{4}'],
    correctAnswer: 0,
    explanation: 'Dividimos el numerador entre el denominador:',
    explanationLatex: '17 \\div 4 = 4 \\text{ con resto } 1 \\quad \\Rightarrow \\quad \\frac{17}{4} = 4\\frac{1}{4}',
    difficulty: 'easy',
    skills: ['numeros-fracciones-impropias-mixtos']
  },
  {
    id: 'm1-47',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $1\\frac{2}{3} + 2\\frac{1}{4}$?',
    questionLatex: '\\text{¿Cuál es el resultado de } 1\\frac{2}{3} + 2\\frac{1}{4}?',
    options: ['$3\\frac{3}{7}$', '$3\\frac{11}{12}$', '$4\\frac{5}{12}$', '$3\\frac{5}{12}$'],
    optionsLatex: ['3\\frac{3}{7}', '3\\frac{11}{12}', '4\\frac{5}{12}', '3\\frac{5}{12}'],
    correctAnswer: 1,
    explanation: 'Sumamos los enteros y las fracciones por separado:',
    explanationLatex: '(1 + 2) + \\left(\\frac{2}{3} + \\frac{1}{4}\\right) = 3 + \\frac{8}{12} + \\frac{3}{12} = 3\\frac{11}{12}',
    difficulty: 'medium',
    skills: ['numeros-fracciones-impropias-mixtos', 'numeros-fracciones-sumar-restar-distinto-denominador', 'numeros-jerarquia-operaciones']
  },
  {
    id: 'm1-48',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál de las siguientes fracciones es mayor?',
    questionLatex: '\\text{¿Cuál de las siguientes fracciones es mayor?}',
    options: ['$\\frac{3}{4}$', '$\\frac{5}{6}$', '$\\frac{2}{3}$', '$\\frac{7}{12}$'],
    optionsLatex: ['\\frac{3}{4}', '\\frac{5}{6}', '\\frac{2}{3}', '\\frac{7}{12}'],
    correctAnswer: 1,
    explanation: 'Buscamos un denominador común (12) y comparamos:',
    explanationLatex: '\\frac{3}{4} = \\frac{9}{12}, \\quad \\frac{5}{6} = \\frac{10}{12}, \\quad \\frac{2}{3} = \\frac{8}{12}, \\quad \\frac{7}{12} = \\frac{7}{12} \\quad \\Rightarrow \\quad \\frac{5}{6} \\text{ es mayor}',
    difficulty: 'medium',
    skills: ['numeros-fracciones-comparar-distinto-denominador', 'numeros-identificar-mayor-menor-mixtos']
  },
  {
    id: 'm1-49',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Ordena las fracciones de menor a mayor: $\\frac{1}{2}, \\frac{3}{5}, \\frac{2}{3}$',
    questionLatex: '\\text{Ordena las fracciones de menor a mayor: } \\frac{1}{2}, \\frac{3}{5}, \\frac{2}{3}',
    options: ['$\\frac{1}{2}, \\frac{3}{5}, \\frac{2}{3}$', '$\\frac{3}{5}, \\frac{1}{2}, \\frac{2}{3}$', '$\\frac{2}{3}, \\frac{3}{5}, \\frac{1}{2}$', '$\\frac{1}{2}, \\frac{2}{3}, \\frac{3}{5}$'],
    optionsLatex: ['\\frac{1}{2}, \\frac{3}{5}, \\frac{2}{3}', '\\frac{3}{5}, \\frac{1}{2}, \\frac{2}{3}', '\\frac{2}{3}, \\frac{3}{5}, \\frac{1}{2}', '\\frac{1}{2}, \\frac{2}{3}, \\frac{3}{5}'],
    correctAnswer: 0,
    explanation: 'Convertimos a denominador común (30):',
    explanationLatex: '\\frac{1}{2} = \\frac{15}{30}, \\quad \\frac{3}{5} = \\frac{18}{30}, \\quad \\frac{2}{3} = \\frac{20}{30} \\quad \\Rightarrow \\quad \\frac{1}{2} < \\frac{3}{5} < \\frac{2}{3}',
    difficulty: 'medium',
    skills: ['numeros-fracciones-comparar-distinto-denominador', 'numeros-enteros-ordenar-recta']
  },
  {
    id: 'm1-50',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Qué fracción es equivalente a $\\frac{4}{6}$?',
    questionLatex: '\\text{¿Qué fracción es equivalente a } \\frac{4}{6}?',
    options: ['$\\frac{3}{4}$', '$\\frac{2}{3}$', '$\\frac{6}{8}$', '$\\frac{8}{10}$'],
    optionsLatex: ['\\frac{3}{4}', '\\frac{2}{3}', '\\frac{6}{8}', '\\frac{8}{10}'],
    correctAnswer: 1,
    explanation: 'Simplificamos dividiendo numerador y denominador por su MCD (2):',
    explanationLatex: '\\frac{4}{6} = \\frac{4 \\div 2}{6 \\div 2} = \\frac{2}{3}',
    difficulty: 'easy',
    skills: ['numeros-equivalencia-fracciones', 'numeros-simplificar-fracciones', 'numeros-mcd-mcm']
  },
  {
    id: 'm1-51',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Convierte el decimal 0.75 a fracción:',
    questionLatex: '\\text{Convierte el decimal 0.75 a fracción:}',
    options: ['$\\frac{3}{4}$', '$\\frac{7}{5}$', '$\\frac{75}{10}$', '$\\frac{15}{20}$'],
    optionsLatex: ['\\frac{3}{4}', '\\frac{7}{5}', '\\frac{75}{10}', '\\frac{15}{20}'],
    correctAnswer: 0,
    explanation: 'Escribimos el decimal como fracción y simplificamos:',
    explanationLatex: '0.75 = \\frac{75}{100} = \\frac{75 \\div 25}{100 \\div 25} = \\frac{3}{4}',
    difficulty: 'easy',
    skills: ['numeros-relacionar-fraccion-decimal-porcentaje', 'numeros-simplificar-fracciones']
  },
  {
    id: 'm1-52',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Convierte la fracción $\\frac{7}{8}$ a decimal:',
    questionLatex: '\\text{Convierte la fracción } \\frac{7}{8} \\text{ a decimal:}',
    options: ['0.78', '0.875', '0.85', '0.7'],
    correctAnswer: 1,
    explanation: 'Dividimos el numerador entre el denominador:',
    explanationLatex: '\\frac{7}{8} = 7 \\div 8 = 0.875',
    difficulty: 'easy',
    skills: ['numeros-relacionar-fraccion-decimal-porcentaje', 'numeros-decimales-multiplicar-dividir']
  },
  {
    id: 'm1-53',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Convierte el decimal 0.625 a fracción simplificada:',
    questionLatex: '\\text{Convierte el decimal 0.625 a fracción simplificada:}',
    options: ['$\\frac{5}{8}$', '$\\frac{625}{100}$', '$\\frac{25}{40}$', '$\\frac{3}{5}$'],
    optionsLatex: ['\\frac{5}{8}', '\\frac{625}{100}', '\\frac{25}{40}', '\\frac{3}{5}'],
    correctAnswer: 0,
    explanation: 'Convertimos y simplificamos:',
    explanationLatex: '0.625 = \\frac{625}{1000} = \\frac{625 \\div 125}{1000 \\div 125} = \\frac{5}{8}',
    difficulty: 'medium',
    skills: ['numeros-relacionar-fraccion-decimal-porcentaje', 'numeros-simplificar-fracciones']
  },
  {
    id: 'm1-54',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'El decimal periódico $0.\\overline{3}$ (0.333...) es equivalente a:',
    questionLatex: '\\text{El decimal periódico } 0.\\overline{3} \\text{ (0.333...) es equivalente a:}',
    options: ['$\\frac{1}{3}$', '$\\frac{3}{10}$', '$\\frac{33}{100}$', '$\\frac{3}{9}$'],
    optionsLatex: ['\\frac{1}{3}', '\\frac{3}{10}', '\\frac{33}{100}', '\\frac{3}{9}'],
    correctAnswer: 0,
    explanation: 'El decimal periódico 0.333... es la fracción:',
    explanationLatex: '0.\\overline{3} = \\frac{1}{3}',
    difficulty: 'medium',
    skills: ['numeros-fracciones-periodicas', 'numeros-convertir-decimal-periodico', 'numeros-densidad-racionales']
  },
  {
    id: 'm1-55',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál de las siguientes fracciones genera un decimal periódico?',
    questionLatex: '\\text{¿Cuál de las siguientes fracciones genera un decimal periódico?}',
    options: ['$\\frac{1}{4}$', '$\\frac{1}{5}$', '$\\frac{1}{3}$', '$\\frac{1}{8}$'],
    optionsLatex: ['\\frac{1}{4}', '\\frac{1}{5}', '\\frac{1}{3}', '\\frac{1}{8}'],
    correctAnswer: 2,
    explanation: 'Un decimal es periódico cuando el denominador tiene factores primos diferentes de 2 y 5:',
    explanationLatex: '\\frac{1}{3} = 0.\\overline{3} \\text{ (periódico). Las otras: } \\frac{1}{4}=0.25, \\frac{1}{5}=0.2, \\frac{1}{8}=0.125',
    difficulty: 'hard',
    skills: ['numeros-fracciones-periodicas', 'numeros-factorizacion-prima', 'numeros-argumentar-sentido-resultado']
  },
  {
    id: 'm1-56',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'El decimal periódico $0.\\overline{6}$ (0.666...) es equivalente a:',
    questionLatex: '\\text{El decimal periódico } 0.\\overline{6} \\text{ (0.666...) es equivalente a:}',
    options: ['$\\frac{2}{3}$', '$\\frac{6}{10}$', '$\\frac{66}{100}$', '$\\frac{6}{9}$'],
    optionsLatex: ['\\frac{2}{3}', '\\frac{6}{10}', '\\frac{66}{100}', '\\frac{6}{9}'],
    correctAnswer: 0,
    explanation: 'El decimal periódico se convierte:',
    explanationLatex: '0.\\overline{6} = \\frac{6}{9} = \\frac{2}{3}',
    difficulty: 'medium',
    skills: ['numeros-fracciones-periodicas', 'numeros-convertir-decimal-periodico', 'numeros-simplificar-fracciones']
  },
  {
    id: 'm1-57',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál de los siguientes números es primo?',
    questionLatex: '\\text{¿Cuál de los siguientes números es primo?}',
    options: ['15', '17', '21', '25'],
    correctAnswer: 1,
    explanation: 'Un número primo solo es divisible por 1 y por sí mismo:',
    explanationLatex: '17 \\text{ es primo. } 15=3\\times5, \\quad 21=3\\times7, \\quad 25=5\\times5',
    difficulty: 'easy',
    skills: ['numeros-factorizacion-prima']
  },
  {
    id: 'm1-58',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuántos números primos hay entre 1 y 10?',
    questionLatex: '\\text{¿Cuántos números primos hay entre 1 y 10?}',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    explanation: 'Los números primos entre 1 y 10 son:',
    explanationLatex: '2, 3, 5, 7 \\quad \\Rightarrow \\quad 4 \\text{ números primos}',
    difficulty: 'easy',
    skills: ['numeros-factorizacion-prima']
  },
  {
    id: 'm1-59',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el número primo más pequeño mayor que 20?',
    questionLatex: '\\text{¿Cuál es el número primo más pequeño mayor que 20?}',
    options: ['21', '22', '23', '25'],
    correctAnswer: 2,
    explanation: 'Verificamos cada número:',
    explanationLatex: '21=3\\times7, \\quad 22=2\\times11, \\quad 23 \\text{ es primo}, \\quad 25=5\\times5',
    difficulty: 'medium',
    skills: ['numeros-factorizacion-prima']
  },
  {
    id: 'm1-60',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es la factorización prima de 24?',
    questionLatex: '\\text{¿Cuál es la factorización prima de 24?}',
    options: ['$2 \\times 12$', '$2^3 \\times 3$', '$4 \\times 6$', '$2^2 \\times 6$'],
    optionsLatex: ['2 \\times 12', '2^3 \\times 3', '4 \\times 6', '2^2 \\times 6'],
    correctAnswer: 1,
    explanation: 'Descomponemos 24 en sus factores primos:',
    explanationLatex: '24 = 2 \\times 12 = 2 \\times 2 \\times 6 = 2 \\times 2 \\times 2 \\times 3 = 2^3 \\times 3',
    difficulty: 'easy',
    skills: ['numeros-factorizacion-prima', 'numeros-potencias']
  },
  {
    id: 'm1-61',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Si $60 = 2^2 \\times 3 \\times 5$, ¿cuál es la factorización prima de 30?',
    questionLatex: '\\text{Si } 60 = 2^2 \\times 3 \\times 5, \\text{ ¿cuál es la factorización prima de 30?}',
    options: ['$2 \\times 3 \\times 5$', '$2^2 \\times 3$', '$3 \\times 10$', '$2 \\times 15$'],
    optionsLatex: ['2 \\times 3 \\times 5', '2^2 \\times 3', '3 \\times 10', '2 \\times 15'],
    correctAnswer: 0,
    explanation: '30 es la mitad de 60, entonces quitamos un factor de 2:',
    explanationLatex: '30 = \\frac{60}{2} = \\frac{2^2 \\times 3 \\times 5}{2} = 2 \\times 3 \\times 5',
    difficulty: 'medium',
    skills: ['numeros-factorizacion-prima', 'numeros-potencias', 'numeros-argumentar-sentido-resultado']
  },
  {
    id: 'm1-62',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es la factorización prima de 72?',
    questionLatex: '\\text{¿Cuál es la factorización prima de 72?}',
    options: ['$2^3 \\times 3^2$', '$2^2 \\times 3^3$', '$8 \\times 9$', '$2^4 \\times 3$'],
    optionsLatex: ['2^3 \\times 3^2', '2^2 \\times 3^3', '8 \\times 9', '2^4 \\times 3'],
    correctAnswer: 0,
    explanation: 'Descomponemos completamente en factores primos:',
    explanationLatex: '72 = 8 \\times 9 = (2^3) \\times (3^2) = 2^3 \\times 3^2',
    difficulty: 'medium',
    skills: ['numeros-factorizacion-prima', 'numeros-potencias']
  },
  {
    id: 'm1-63',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el Mínimo Común Múltiplo (MCM) de 4 y 6?',
    questionLatex: '\\text{¿Cuál es el Mínimo Común Múltiplo (MCM) de 4 y 6?}',
    options: ['10', '12', '24', '2'],
    correctAnswer: 1,
    explanation: 'Encontramos el múltiplo común más pequeño:',
    explanationLatex: '\\text{Múltiplos de 4: } 4, 8, 12, 16... \\quad \\text{Múltiplos de 6: } 6, 12, 18... \\quad \\Rightarrow \\quad \\text{MCM} = 12',
    difficulty: 'easy',
    skills: ['numeros-mcd-mcm']
  },
  {
    id: 'm1-64',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el MCM de 8, 12 y 18?',
    questionLatex: '\\text{¿Cuál es el MCM de 8, 12 y 18?}',
    options: ['36', '48', '72', '144'],
    correctAnswer: 2,
    explanation: 'Factorizamos y tomamos los factores con mayor exponente:',
    explanationLatex: '8=2^3, \\quad 12=2^2\\times3, \\quad 18=2\\times3^2 \\quad \\Rightarrow \\quad \\text{MCM} = 2^3\\times3^2 = 72',
    difficulty: 'hard',
    skills: ['numeros-mcd-mcm', 'numeros-factorizacion-prima']
  },
  {
    id: 'm1-65',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Dos buses salen de la estación al mismo tiempo. Uno pasa cada 15 minutos y el otro cada 20 minutos. ¿En cuántos minutos volverán a coincidir en la estación?',
    questionLatex: '\\text{Dos buses salen de la estación al mismo tiempo. Uno pasa cada 15 minutos y el otro cada 20 minutos. ¿En cuántos minutos volverán a coincidir?}',
    options: ['30 minutos', '35 minutos', '60 minutos', '300 minutos'],
    correctAnswer: 2,
    explanation: 'Necesitamos el MCM de 15 y 20:',
    explanationLatex: '15 = 3 \\times 5, \\quad 20 = 2^2 \\times 5 \\quad \\Rightarrow \\quad \\text{MCM} = 2^2 \\times 3 \\times 5 = 60',
    difficulty: 'medium',
    skills: ['numeros-mcd-mcm', 'numeros-factorizacion-prima', 'numeros-problemas-unidades-conversiones']
  },
  {
    id: 'm1-66',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál de los siguientes números es divisible por 3?',
    questionLatex: '\\text{¿Cuál de los siguientes números es divisible por 3?}',
    options: ['124', '235', '342', '455'],
    correctAnswer: 2,
    explanation: 'Un número es divisible por 3 si la suma de sus dígitos es divisible por 3:',
    explanationLatex: '342: \\quad 3+4+2 = 9 \\text{ (divisible por 3)} \\quad \\Rightarrow \\quad 342 \\text{ es divisible por 3}',
    difficulty: 'easy',
    skills: ['numeros-patrones-signos', 'numeros-argumentar-sentido-resultado']
  },
  {
    id: 'm1-67',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál de los siguientes números es divisible por 9?',
    questionLatex: '\\text{¿Cuál de los siguientes números es divisible por 9?}',
    options: ['234', '567', '729', '891'],
    correctAnswer: 2,
    explanation: 'Un número es divisible por 9 si la suma de sus dígitos es divisible por 9:',
    explanationLatex: '729: \\quad 7+2+9 = 18 \\text{ (divisible por 9)} \\quad \\Rightarrow \\quad 729 \\text{ es divisible por 9}',
    difficulty: 'medium',
    skills: ['numeros-patrones-signos', 'numeros-argumentar-sentido-resultado']
  },
  {
    id: 'm1-68',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Un número de tres dígitos es divisible por 11 si:',
    questionLatex: '\\text{Un número de tres dígitos es divisible por 11 si:}',
    options: ['La suma de sus dígitos es 11', 'La diferencia entre la suma de dígitos en posiciones impares y pares es 0 o múltiplo de 11', 'El último dígito es 1', 'La suma de sus dígitos es divisible por 11'],
    correctAnswer: 1,
    explanation: 'Regla de divisibilidad por 11:',
    explanationLatex: '\\text{Ejemplo: } 121 \\rightarrow (1+1)-2 = 0 \\text{ (divisible por 11)}',
    difficulty: 'hard',
    skills: ['numeros-patrones-signos', 'numeros-argumentar-sentido-resultado']
  },
  {
    id: 'm1-108',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $8 + 2 \\times 5$?',
    questionLatex: '\\text{¿Cuál es el resultado de } 8 + 2 \\times 5?',
    options: ['18', '50', '26', '15'],
    correctAnswer: 0,
    explanation: 'Primero multiplicación, luego suma:',
    explanationLatex: '8 + 2 \\times 5 = 8 + 10 = 18',
    difficulty: 'easy',
    skills: ['numeros-jerarquia-operaciones']
  },
  {
    id: 'm1-109',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $20 - 3 \\times 4 + 6$?',
    questionLatex: '\\text{¿Cuál es el resultado de } 20 - 3 \\times 4 + 6?',
    options: ['14', '26', '74', '2'],
    correctAnswer: 0,
    explanation: 'Multiplicación primero, luego operaciones de izquierda a derecha:',
    explanationLatex: '20 - 3 \\times 4 + 6 = 20 - 12 + 6 = 14',
    difficulty: 'medium',
    skills: ['numeros-jerarquia-operaciones', 'numeros-enteros-sumar-restar']
  },
  {
    id: 'm1-110',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $2^3 + 4 \\times 3 - 5$?',
    questionLatex: '\\text{¿Cuál es el resultado de } 2^3 + 4 \\times 3 - 5?',
    options: ['15', '19', '21', '27'],
    correctAnswer: 0,
    explanation: 'Orden: exponentes, multiplicación, luego suma y resta:',
    explanationLatex: '2^3 + 4 \\times 3 - 5 = 8 + 12 - 5 = 15',
    difficulty: 'medium',
    skills: ['numeros-jerarquia-operaciones', 'numeros-potencias']
  },
  {
    id: 'm1-111',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $(8 + 2) \\times 5$?',
    questionLatex: '\\text{¿Cuál es el resultado de } (8 + 2) \\times 5?',
    options: ['18', '40', '50', '26'],
    correctAnswer: 2,
    explanation: 'Primero resolvemos el paréntesis:',
    explanationLatex: '(8 + 2) \\times 5 = 10 \\times 5 = 50',
    difficulty: 'easy',
    skills: ['numeros-jerarquia-operaciones']
  },
  {
    id: 'm1-112',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $3 \\times (12 - 4) + 8$?',
    questionLatex: '\\text{¿Cuál es el resultado de } 3 \\times (12 - 4) + 8?',
    options: ['24', '28', '32', '36'],
    correctAnswer: 2,
    explanation: 'Paréntesis primero, luego multiplicación y suma:',
    explanationLatex: '3 \\times (12 - 4) + 8 = 3 \\times 8 + 8 = 24 + 8 = 32',
    difficulty: 'medium',
    skills: ['numeros-jerarquia-operaciones']
  },
  {
    id: 'm1-113',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $[(15 - 3) \\div 4 + 2] \\times 3$?',
    questionLatex: '\\text{¿Cuál es el resultado de } [(15 - 3) \\div 4 + 2] \\times 3?',
    options: ['12', '15', '18', '21'],
    correctAnswer: 1,
    explanation: 'Resolvemos de adentro hacia afuera:',
    explanationLatex: '[(15 - 3) \\div 4 + 2] \\times 3 = [12 \\div 4 + 2] \\times 3 = [3 + 2] \\times 3 = 5 \\times 3 = 15',
    difficulty: 'hard',
    skills: ['numeros-jerarquia-operaciones']
  },
  {
    id: 'm1-114',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál de los siguientes es un número irracional?',
    questionLatex: '\\text{¿Cuál de los siguientes es un número irracional?}',
    options: ['$\\frac{22}{7}$', '$\\sqrt{16}$', '$\\pi$', '$0.\\overline{3}$'],
    optionsLatex: ['\\frac{22}{7}', '\\sqrt{16}', '\\pi', '0.\\overline{3}'],
    correctAnswer: 2,
    explanation: 'Un número irracional no puede expresarse como fracción:',
    explanationLatex: '\\pi \\text{ es irracional. } \\frac{22}{7} \\text{ y } 0.\\overline{3} \\text{ son racionales, } \\sqrt{16}=4',
    difficulty: 'medium',
    skills: ['numeros-racionales-comprender-significado', 'numeros-argumentar-sentido-resultado']
  },
  {
    id: 'm1-115',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál de los siguientes es un número racional?',
    questionLatex: '\\text{¿Cuál de los siguientes es un número racional?}',
    options: ['$\\pi$', '$\\sqrt{2}$', '$\\sqrt{9}$', '$\\sqrt{7}$'],
    optionsLatex: ['\\pi', '\\sqrt{2}', '\\sqrt{9}', '\\sqrt{7}'],
    correctAnswer: 2,
    explanation: 'Un número racional puede expresarse como fracción:',
    explanationLatex: '\\sqrt{9} = 3 \\text{ (racional). Los demás son irracionales.}',
    difficulty: 'easy',
    skills: ['numeros-racionales-comprender-significado', 'numeros-raices']
  },
  {
    id: 'm1-117',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'En la recta numérica, ¿qué número está exactamente a mitad de camino entre -3 y 5?',
    questionLatex: '\\text{En la recta numérica, ¿qué número está a mitad de camino entre -3 y 5?}',
    options: ['0', '1', '2', '4'],
    correctAnswer: 1,
    explanation: 'El punto medio es el promedio de los dos números:',
    explanationLatex: '\\frac{-3 + 5}{2} = \\frac{2}{2} = 1',
    difficulty: 'easy',
    skills: ['numeros-representar-recta-numerica', 'numeros-enteros-ordenar-recta', 'numeros-calcular-promedios-racionales']
  },
  {
    id: 'm1-118',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál número está más cerca de 0 en la recta numérica?',
    questionLatex: '\\text{¿Cuál número está más cerca de 0 en la recta numérica?}',
    options: ['-0.5', '0.6', '-0.8', '1.2'],
    correctAnswer: 0,
    explanation: 'El número más cercano a 0 es el de menor valor absoluto:',
    explanationLatex: '|-0.5| = 0.5 \\text{ es el menor}',
    difficulty: 'medium',
    skills: ['numeros-valor-absoluto', 'numeros-comparar-distancia-cero', 'numeros-decimales-comparar']
  },
  {
    id: 'm1-119',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'En la recta numérica, ¿qué distancia hay entre -4 y 7?',
    questionLatex: '\\text{En la recta numérica, ¿qué distancia hay entre -4 y 7?}',
    options: ['3', '7', '11', '28'],
    correctAnswer: 2,
    explanation: 'La distancia es el valor absoluto de la diferencia:',
    explanationLatex: '|7 - (-4)| = |7 + 4| = 11',
    difficulty: 'medium',
    skills: ['numeros-representar-recta-numerica', 'numeros-valor-absoluto']
  },
  {
    id: 'm1-120',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el valor de $|-8|$?',
    questionLatex: '\\text{¿Cuál es el valor de } |-8|?',
    options: ['-8', '0', '8', '16'],
    correctAnswer: 2,
    explanation: 'El valor absoluto es la distancia al cero (siempre positivo):',
    explanationLatex: '|-8| = 8',
    difficulty: 'easy',
    skills: ['numeros-valor-absoluto', 'numeros-enteros-comprender-significado']
  },
  {
    id: 'm1-121',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $|5 - 9|$?',
    questionLatex: '\\text{¿Cuál es el resultado de } |5 - 9|?',
    options: ['-4', '4', '14', '-14'],
    correctAnswer: 1,
    explanation: 'Primero restamos, luego tomamos el valor absoluto:',
    explanationLatex: '|5 - 9| = |-4| = 4',
    difficulty: 'easy',
    skills: ['numeros-valor-absoluto', 'numeros-enteros-sumar-restar']
  },
  {
    id: 'm1-122',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $|-3| + |2| - |-5|$?',
    questionLatex: '\\text{¿Cuál es el resultado de } |-3| + |2| - |-5|?',
    options: ['0', '4', '6', '10'],
    correctAnswer: 0,
    explanation: 'Calculamos cada valor absoluto y luego operamos:',
    explanationLatex: '|-3| + |2| - |-5| = 3 + 2 - 5 = 0',
    difficulty: 'medium',
    skills: ['numeros-valor-absoluto', 'numeros-jerarquia-operaciones']
  }
];
