import { Question } from '../../../types';

/**
 * M1-NUM-002: Operaciones y comparación entre números racionales
 *
 * Topics covered:
 * - Fraction operations (addition, subtraction, multiplication, division)
 * - Comparing and ordering fractions
 * - Simplifying fractions and equivalence
 * - Converting between fractions, decimals, and mixed numbers
 * - Periodic decimals
 * - MCD and MCM
 * - Prime factorization
 * - Divisibility rules
 * - Rational vs irrational numbers
 */

export const m1Num002Questions: Question[] = [
  {
    id: 'm1-9',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\frac{2}{3} + \\frac{1}{4}',
    questionLatex: '\\text{Ana está preparando una receta de pastel que requiere combinar ingredientes medidos en tazas. Para la mezcla principal necesita 2/3 de taza de harina, y para el glaseado adicional requiere 1/4 de taza más de harina. Ana quiere saber cuánta harina necesitará en total para completar toda la preparación. ¿Cuántas tazas de harina debe usar en total?}',
    options: ['\\frac{3}{7}', '\\frac{11}{12}', '\\frac{5}{6}', '\\frac{3}{4}'],
    correctAnswer: 1,
    explanation: '\\frac{2}{3} + \\frac{1}{4} = \\frac{8}{12} + \\frac{3}{12} = \\frac{11}{12}',
    difficulty: 'easy',
    difficultyScore: 0.32,
    skills: ['numeros-fracciones-sumar-restar-distinto-denominador', 'numeros-simplificar-fracciones', 'numeros-jerarquia-operaciones']
  },
  {
    id: 'm1-11',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\text{MCD}(12, 18)',
    questionLatex: '\\text{En una bodega de materiales escolares hay dos tipos de cajas que deben organizarse en estantes. Las cajas del primer tipo contienen 12 lápices cada una, y las del segundo tipo contienen 18 lápices cada una. El encargado necesita formar paquetes que contengan la misma cantidad de lápices, utilizando cajas completas de ambos tipos sin que sobre ningún lápiz. Para optimizar el espacio, busca la mayor cantidad posible de lápices por paquete. ¿Cuál es el número máximo de lápices que puede tener cada paquete?}',
    options: ['2', '3', '6', '36'],
    correctAnswer: 2,
    explanation: '12 = 2^2 \\times 3, \\quad 18 = 2 \\times 3^2 \\quad \\Rightarrow \\quad \\text{MCD} = 2 \\times 3 = 6',
    difficulty: 'medium',
    difficultyScore: 0.40,
    skills: ['numeros-mcd-mcm', 'numeros-factorizacion-prima']
  },
  {
    id: 'm1-28',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\frac{3}{4}x = 15',
    questionLatex: '\\text{En una campaña de reciclaje escolar, un grupo de estudiantes ha logrado recolectar 15 kilogramos de papel. El profesor les informa que esta cantidad representa exactamente tres cuartos del total que deben recolectar para alcanzar su meta mensual. Los estudiantes necesitan determinar cuál es la meta completa de recolección que deben alcanzar. ¿Cuántos kilogramos en total deben recolectar?}',
    options: ['12', '18', '20', '24'],
    correctAnswer: 2,
    explanation: '\\frac{3}{4}x = 15 \\quad \\Rightarrow \\quad x = 15 \\times \\frac{4}{3} = 20',
    difficulty: 'medium',
    difficultyScore: 0.35,
    skills: ['numeros-fracciones-multiplicar-dividir', 'numeros-inverso-aditivo-multiplicativo', 'algebra-ecuaciones-lineales', 'algebra-despeje']
  },
  {
    id: 'm1-42',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\frac{2}{3} \\times \\frac{5}{4}',
    questionLatex: '\\text{María está cosiendo una falda y necesita calcular la cantidad total de tela requerida. El patrón indica que debe usar 2/3 de metro de tela como medida base, pero debido al diseño con pliegues, esta cantidad debe multiplicarse por 5/4 para obtener la tela real necesaria. María quiere saber cuánta tela debe comprar antes de comenzar el proyecto. ¿Qué fracción de metro de tela necesita en total?}',
    options: ['\\frac{7}{12}', '\\frac{10}{12}', '\\frac{5}{6}', '\\frac{10}{7}'],
    correctAnswer: 2,
    explanation: '\\frac{2}{3} \\times \\frac{5}{4} = \\frac{2 \\times 5}{3 \\times 4} = \\frac{10}{12} = \\frac{5}{6}',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['numeros-fracciones-multiplicar-dividir', 'numeros-simplificar-fracciones']
  },
  {
    id: 'm1-43',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\frac{3}{4} \\div \\frac{2}{5}',
    questionLatex: '\\text{Un chef está preparando porciones individuales de postre. Tiene 3/4 de kilogramo de chocolate disponible en su cocina, y cada porción individual requiere 2/5 de kilogramo de chocolate. El chef necesita calcular cuántas porciones completas puede preparar con el chocolate disponible. ¿Cuál es el resultado de esta división?}',
    options: ['\\frac{6}{20}', '\\frac{5}{8}', '\\frac{15}{8}', '\\frac{8}{15}'],
    correctAnswer: 2,
    explanation: '\\frac{3}{4} \\div \\frac{2}{5} = \\frac{3}{4} \\times \\frac{5}{2} = \\frac{15}{8}',
    difficulty: 'easy',
    difficultyScore: 0.32,
    skills: ['numeros-fracciones-multiplicar-dividir', 'numeros-inverso-aditivo-multiplicativo']
  },
  {
    id: 'm1-44',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\frac{2}{3} \\div 4',
    questionLatex: '\\text{María tiene un pastel que representa 2/3 del pastel completo que horneó originalmente, ya que compartió una parte con su familia. Ahora necesita dividir la porción restante equitativamente entre sus 4 hijos para que cada uno reciba exactamente la misma cantidad. María quiere determinar qué fracción del pastel completo original recibirá cada hijo. ¿Qué fracción del pastel completo es cada parte?}',
    options: ['\\frac{1}{6}', '\\frac{2}{12}', '\\frac{1}{8}', '\\frac{8}{3}'],
    correctAnswer: 0,
    explanation: '\\frac{2}{3} \\div 4 = \\frac{2}{3} \\times \\frac{1}{4} = \\frac{2}{12} = \\frac{1}{6}',
    difficulty: 'easy',
    difficultyScore: 0.30,
    skills: ['numeros-fracciones-multiplicar-dividir', 'numeros-modelar-proporciones-repartos', 'numeros-interpretar-resultados-razonabilidad']
  },
  {
    id: 'm1-45',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '2\\frac{3}{5} \\rightarrow \\text{fracción impropia}',
    questionLatex: '\\text{En una ferretería se venden listones de madera. Un carpintero compra un listón que mide 2 metros completos más 3/5 de metro adicional, lo que se expresa como el número mixto 2 y 3/5 metros. Para realizar cálculos precisos en su proyecto de construcción, necesita expresar esta medida como una fracción impropia donde el numerador puede ser mayor que el denominador. ¿Cuál es la fracción impropia equivalente?}',
    options: ['\\frac{8}{5}', '\\frac{11}{5}', '\\frac{13}{5}', '\\frac{6}{5}'],
    correctAnswer: 2,
    explanation: '2\\frac{3}{5} = \\frac{(2 \\times 5) + 3}{5} = \\frac{10 + 3}{5} = \\frac{13}{5}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['numeros-fracciones-impropias-mixtos', 'numeros-jerarquia-operaciones']
  },
  {
    id: 'm1-46',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\frac{17}{4} \\rightarrow \\text{número mixto}',
    questionLatex: '\\text{Una fábrica de bebidas produce jugo en botellas de un cuarto de litro cada una. Al finalizar el día, quedaron 17 botellas de cuarto de litro sin empacar, lo que representa 17/4 de litro en total. El supervisor necesita registrar esta cantidad en el sistema usando números mixtos para facilitar la lectura en litros completos más la fracción sobrante. ¿Cómo se expresa esta fracción como número mixto?}',
    options: ['4\\frac{1}{4}', '3\\frac{5}{4}', '4\\frac{1}{17}', '5\\frac{2}{4}'],
    correctAnswer: 0,
    explanation: '17 \\div 4 = 4 \\text{ con resto } 1 \\quad \\Rightarrow \\quad \\frac{17}{4} = 4\\frac{1}{4}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['numeros-fracciones-impropias-mixtos']
  },
  {
    id: 'm1-47',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '1\\frac{2}{3} + 2\\frac{1}{4}',
    questionLatex: '\\text{Un atleta está entrenando para una maratón y registra sus distancias diarias en kilómetros. El lunes corrió 1 kilómetro completo más 2/3 de kilómetro adicional. El martes aumentó su entrenamiento y corrió 2 kilómetros completos más 1/4 de kilómetro adicional. Su entrenador necesita calcular la distancia total recorrida en ambos días para ajustar el plan de entrenamiento. ¿Cuántos kilómetros corrió en total?}',
    options: ['3\\frac{3}{7}', '3\\frac{11}{12}', '4\\frac{5}{12}', '3\\frac{5}{12}'],
    correctAnswer: 1,
    explanation: '(1 + 2) + \\left(\\frac{2}{3} + \\frac{1}{4}\\right) = 3 + \\frac{8}{12} + \\frac{3}{12} = 3\\frac{11}{12}',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['numeros-fracciones-impropias-mixtos', 'numeros-fracciones-sumar-restar-distinto-denominador', 'numeros-jerarquia-operaciones']
  },
  {
    id: 'm1-48',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\text{Comparar: } \\frac{3}{4}, \\frac{5}{6}, \\frac{2}{3}, \\frac{7}{12}',
    questionLatex: '\\text{En una competencia de natación, cuatro nadadores completaron diferentes fracciones del recorrido total en el mismo tiempo. El nadador A completó 3/4 del recorrido, el nadador B completó 5/6, el nadador C completó 2/3, y el nadador D completó 7/12. Los organizadores necesitan determinar cuál nadador avanzó más distancia para otorgar el premio al mejor desempeño. ¿Cuál de las siguientes fracciones es mayor?}',
    options: ['\\frac{3}{4}', '\\frac{5}{6}', '\\frac{2}{3}', '\\frac{7}{12}'],
    correctAnswer: 1,
    explanation: '\\frac{3}{4} = \\frac{9}{12}, \\quad \\frac{5}{6} = \\frac{10}{12}, \\quad \\frac{2}{3} = \\frac{8}{12}, \\quad \\frac{7}{12} = \\frac{7}{12} \\quad \\Rightarrow \\quad \\frac{5}{6} \\text{ es mayor}',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['numeros-fracciones-comparar-distinto-denominador', 'numeros-identificar-mayor-menor-mixtos']
  },
  {
    id: 'm1-49',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\text{Ordenar: } \\frac{1}{2}, \\frac{3}{5}, \\frac{2}{3}',
    questionLatex: '\\text{En una biblioteca municipal se realizó una encuesta sobre preferencias de lectura entre los usuarios. Los resultados mostraron que 1/2 de los encuestados prefiere novelas, 3/5 prefiere ensayos, y 2/3 prefiere poesía. La bibliotecaria necesita ordenar estas preferencias de menor a mayor para planificar las compras del próximo semestre. ¿Cuál es el orden correcto de las fracciones de menor a mayor?}',
    options: ['\\frac{1}{2}, \\frac{3}{5}, \\frac{2}{3}', '\\frac{3}{5}, \\frac{1}{2}, \\frac{2}{3}', '\\frac{2}{3}, \\frac{3}{5}, \\frac{1}{2}', '\\frac{1}{2}, \\frac{2}{3}, \\frac{3}{5}'],
    correctAnswer: 0,
    explanation: '\\frac{1}{2} = \\frac{15}{30}, \\quad \\frac{3}{5} = \\frac{18}{30}, \\quad \\frac{2}{3} = \\frac{20}{30} \\quad \\Rightarrow \\quad \\frac{1}{2} < \\frac{3}{5} < \\frac{2}{3}',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['numeros-fracciones-comparar-distinto-denominador', 'numeros-enteros-ordenar-recta']
  },
  {
    id: 'm1-50',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\text{Simplificar } \\frac{4}{6}',
    questionLatex: '\\text{Un profesor de matemática está enseñando fracciones equivalentes a sus estudiantes. En un ejercicio, les muestra una pizza dividida en 6 pedazos iguales, de los cuales 4 pedazos tienen champiñones. Luego les pregunta si pueden expresar esta misma proporción usando números más pequeños, es decir, encontrando una fracción equivalente más simple. ¿Qué fracción es equivalente a 4/6?}',
    options: ['\\frac{3}{4}', '\\frac{2}{3}', '\\frac{6}{8}', '\\frac{8}{10}'],
    correctAnswer: 1,
    explanation: '\\frac{4}{6} = \\frac{4 \\div 2}{6 \\div 2} = \\frac{2}{3}',
    difficulty: 'easy',
    difficultyScore: 0.18,
    skills: ['numeros-equivalencia-fracciones', 'numeros-simplificar-fracciones', 'numeros-mcd-mcm']
  },
  {
    id: 'm1-51',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '0.75 \\rightarrow \\text{fracción}',
    questionLatex: '\\text{En un laboratorio de química, un estudiante mide el contenido de un recipiente y obtiene 0.75 litros de una solución. Para completar su informe experimental, el profesor le solicita que exprese esta medida como una fracción simplificada, ya que las proporciones en química tradicionalmente se escriben en formato fraccionario. ¿Cuál es la fracción que representa 0.75 litros?}',
    options: ['\\frac{3}{4}', '\\frac{7}{5}', '\\frac{75}{10}', '\\frac{15}{20}'],
    correctAnswer: 0,
    explanation: '0.75 = \\frac{75}{100} = \\frac{75 \\div 25}{100 \\div 25} = \\frac{3}{4}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['numeros-relacionar-fraccion-decimal-porcentaje', 'numeros-simplificar-fracciones']
  },
  {
    id: 'm1-52',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\frac{7}{8} \\rightarrow \\text{decimal}',
    questionLatex: '\\text{Una diseñadora de moda está calculando las medidas para confeccionar un vestido. El patrón indica que necesita 7/8 de metro de tela para una sección específica. Para programar la máquina de corte automático, que solo acepta valores decimales, necesita convertir esta fracción a su equivalente decimal con exactitud. ¿Cuál es el valor decimal de 7/8?}',
    options: ['0.78', '0.875', '0.85', '0.7'],
    correctAnswer: 1,
    explanation: '\\frac{7}{8} = 7 \\div 8 = 0.875',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['numeros-relacionar-fraccion-decimal-porcentaje', 'numeros-decimales-multiplicar-dividir']
  },
  {
    id: 'm1-53',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '0.625 \\rightarrow \\text{fracción}',
    questionLatex: '\\text{Un ingeniero está midiendo el grosor de una pieza metálica con un instrumento digital que indica 0.625 centímetros. Para el reporte técnico de fabricación, necesita expresar esta medida como una fracción simplificada, ya que los planos de ingeniería utilizan fracciones en lugar de decimales. ¿Cuál es la fracción simplificada que representa este grosor?}',
    options: ['\\frac{5}{8}', '\\frac{625}{100}', '\\frac{25}{40}', '\\frac{3}{5}'],
    correctAnswer: 0,
    explanation: '0.625 = \\frac{625}{1000} = \\frac{625 \\div 125}{1000 \\div 125} = \\frac{5}{8}',
    difficulty: 'medium',
    difficultyScore: 0.35,
    skills: ['numeros-relacionar-fraccion-decimal-porcentaje', 'numeros-simplificar-fracciones']
  },
  {
    id: 'm1-54',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '0.333... \\rightarrow \\text{fracción}',
    questionLatex: '\\text{Un estudiante está usando su calculadora para dividir una pizza equitativamente entre tres personas. Al ingresar la operación, la calculadora muestra 0.333... donde los tres se repiten infinitamente. El profesor le explica que este es un decimal periódico que puede expresarse como una fracción simple. ¿A qué fracción corresponde el decimal periódico 0.333...?}',
    options: ['\\frac{1}{3}', '\\frac{3}{10}', '\\frac{33}{100}', '\\frac{3}{9}'],
    correctAnswer: 0,
    explanation: '0.\\overline{3} = \\frac{1}{3}',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['numeros-fracciones-periodicas', 'numeros-convertir-decimal-periodico', 'numeros-densidad-racionales']
  },
  {
    id: 'm1-55',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\text{Identificar fracción periódica}',
    questionLatex: '\\text{Una profesora de matemática está enseñando sobre decimales periódicos y finitos. Explica que algunas fracciones generan decimales que terminan, mientras otras producen decimales con cifras que se repiten infinitamente. Muestra cuatro fracciones a sus estudiantes y les pide identificar cuál de ellas generará un decimal periódico al realizar la división. ¿Cuál de las siguientes fracciones genera un decimal periódico?}',
    options: ['\\frac{1}{4}', '\\frac{1}{5}', '\\frac{1}{3}', '\\frac{1}{8}'],
    correctAnswer: 2,
    explanation: '\\frac{1}{3} = 0.\\overline{3} \\text{ (periódico). Las otras: } \\frac{1}{4}=0.25, \\frac{1}{5}=0.2, \\frac{1}{8}=0.125',
    difficulty: 'medium',
    difficultyScore: 0.40,
    skills: ['numeros-fracciones-periodicas', 'numeros-factorizacion-prima', 'numeros-argumentar-sentido-resultado']
  },
  {
    id: 'm1-56',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '0.666... \\rightarrow \\text{fracción}',
    questionLatex: '\\text{En una clase de ciencias, un estudiante calcula la concentración de una solución y obtiene en su calculadora el resultado 0.666... donde el seis se repite infinitamente. Para completar su informe científico, necesita expresar este decimal periódico como una fracción simplificada. El profesor menciona que este tipo de decimal periódico simple puede convertirse fácilmente a fracción. ¿Cuál es la fracción equivalente a 0.666...?}',
    options: ['\\frac{2}{3}', '\\frac{6}{10}', '\\frac{66}{100}', '\\frac{6}{9}'],
    correctAnswer: 0,
    explanation: '0.\\overline{6} = \\frac{6}{9} = \\frac{2}{3}',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['numeros-fracciones-periodicas', 'numeros-convertir-decimal-periodico', 'numeros-simplificar-fracciones']
  },
  {
    id: 'm1-57',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\text{Identificar número primo}',
    questionLatex: '\\text{En una clase de teoría de números, el profesor explica que los números primos son aquellos que solo pueden dividirse exactamente por 1 y por sí mismos, sin dejar residuo. Presenta cuatro números a los estudiantes y les pide identificar cuál de ellos cumple con la definición de número primo. Los números son 15, 17, 21 y 25. ¿Cuál de los siguientes números es primo?}',
    options: ['15', '17', '21', '25'],
    correctAnswer: 1,
    explanation: '17 \\text{ es primo. } 15=3\\times5, \\quad 21=3\\times7, \\quad 25=5\\times5',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['numeros-factorizacion-prima']
  },
  {
    id: 'm1-58',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\text{Contar primos entre 1 y 10}',
    questionLatex: '\\text{Un estudiante está aprendiendo sobre números primos y su profesor le pide que identifique todos los números primos que se encuentran en el intervalo del 1 al 10. El estudiante recuerda que los números primos son aquellos que solo tienen dos divisores: el 1 y el número mismo. Para resolver el ejercicio, debe contar cuántos números cumplen esta condición en el rango indicado. ¿Cuántos números primos hay entre 1 y 10?}',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    explanation: '2, 3, 5, 7 \\quad \\Rightarrow \\quad 4 \\text{ números primos}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['numeros-factorizacion-prima']
  },
  {
    id: 'm1-59',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\text{Primo más pequeño } > 20',
    questionLatex: '\\text{En una competencia matemática, se le pregunta a un estudiante cuál es el número primo más pequeño que es mayor que 20. El estudiante debe analizar cada número después del 20 y determinar cuál es el primero que cumple con la condición de ser primo, es decir, que solo sea divisible por 1 y por sí mismo. ¿Cuál es el número primo más pequeño mayor que 20?}',
    options: ['21', '22', '23', '25'],
    correctAnswer: 2,
    explanation: '21=3\\times7, \\quad 22=2\\times11, \\quad 23 \\text{ es primo}, \\quad 25=5\\times5',
    difficulty: 'medium',
    difficultyScore: 0.32,
    skills: ['numeros-factorizacion-prima']
  },
  {
    id: 'm1-60',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\text{Factorización prima de } 24',
    questionLatex: '\\text{Un profesor de matemática está enseñando factorización prima a sus estudiantes. Les explica que todo número compuesto puede expresarse como producto de números primos. Como ejercicio, les pide descomponer el número 24 en sus factores primos, expresando el resultado usando exponentes cuando sea posible. ¿Cuál es la factorización prima de 24?}',
    options: ['2 \\times 12', '2^3 \\times 3', '4 \\times 6', '2^2 \\times 6'],
    correctAnswer: 1,
    explanation: '24 = 2 \\times 12 = 2 \\times 2 \\times 6 = 2 \\times 2 \\times 2 \\times 3 = 2^3 \\times 3',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['numeros-factorizacion-prima', 'numeros-potencias']
  },
  {
    id: 'm1-61',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\text{Factorización de 30 conociendo 60}',
    questionLatex: '\\text{En una clase de álgebra, el profesor escribe en la pizarra que 60 = 2² × 3 × 5. Luego plantea una pregunta a sus estudiantes: si conocemos la factorización prima de 60, podemos deducir fácilmente la factorización de 30, ya que 30 es exactamente la mitad de 60. Les pide que determinen la factorización prima de 30 usando esta información. ¿Cuál es la factorización prima de 30?}',
    options: ['2 \\times 3 \\times 5', '2^2 \\times 3', '3 \\times 10', '2 \\times 15'],
    correctAnswer: 0,
    explanation: '30 = \\frac{60}{2} = \\frac{2^2 \\times 3 \\times 5}{2} = 2 \\times 3 \\times 5',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['numeros-factorizacion-prima', 'numeros-potencias', 'numeros-argumentar-sentido-resultado']
  },
  {
    id: 'm1-62',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\text{Factorización prima de } 72',
    questionLatex: '\\text{Un estudiante avanzado está trabajando en un problema de factorización. Observa que el número 72 puede expresarse como el producto de 8 y 9, ambos números compuestos. Para obtener la factorización prima completa, debe descomponer tanto el 8 como el 9 en sus factores primos y luego combinarlos usando notación exponencial. ¿Cuál es la factorización prima de 72?}',
    options: ['2^3 \\times 3^2', '2^2 \\times 3^3', '8 \\times 9', '2^4 \\times 3'],
    correctAnswer: 0,
    explanation: '72 = 8 \\times 9 = (2^3) \\times (3^2) = 2^3 \\times 3^2',
    difficulty: 'medium',
    difficultyScore: 0.35,
    skills: ['numeros-factorizacion-prima', 'numeros-potencias']
  },
  {
    id: 'm1-63',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\text{MCM}(4, 6)',
    questionLatex: '\\text{En una escuela de música, dos estudiantes practican con metrónomo. El primer estudiante programa su metrónomo para que suene cada 4 segundos, mientras que el segundo lo programa para que suene cada 6 segundos. Ambos activan sus metrónomos simultáneamente al comenzar la práctica. Los profesores quieren saber cuándo volverán a sonar ambos metrónomos exactamente al mismo tiempo por primera vez. ¿Después de cuántos segundos coincidirán nuevamente?}',
    options: ['10', '12', '24', '2'],
    correctAnswer: 1,
    explanation: '\\text{Múltiplos de 4: } 4, 8, 12, 16... \\quad \\text{Múltiplos de 6: } 6, 12, 18... \\quad \\Rightarrow \\quad \\text{MCM} = 12',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['numeros-mcd-mcm']
  },
  {
    id: 'm1-64',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\text{MCM}(8, 12, 18)',
    questionLatex: '\\text{En una terminal de autobuses, tres líneas diferentes salen de la estación central. La línea A sale cada 8 minutos, la línea B cada 12 minutos, y la línea C cada 18 minutos. A las 6:00 AM las tres líneas salen simultáneamente. El administrador de la terminal necesita calcular en cuántos minutos volverán a coincidir las tres líneas saliendo al mismo tiempo. ¿Cuál es el MCM de 8, 12 y 18?}',
    options: ['36', '48', '72', '144'],
    correctAnswer: 2,
    explanation: '8=2^3, \\quad 12=2^2\\times3, \\quad 18=2\\times3^2 \\quad \\Rightarrow \\quad \\text{MCM} = 2^3\\times3^2 = 72',
    difficulty: 'medium',
    difficultyScore: 0.48,
    skills: ['numeros-mcd-mcm', 'numeros-factorizacion-prima']
  },
  {
    id: 'm1-65',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    operacionBase: '\\text{MCM}(15, 20)',
    questionLatex: '\\text{En una estación de transporte público hay dos buses que salen desde el mismo paradero. El bus de la línea roja pasa cada 15 minutos, mientras que el bus de la línea azul pasa cada 20 minutos. A las 7:00 AM ambos buses salen simultáneamente del paradero. Los usuarios regulares quieren saber a qué hora volverán a coincidir ambos buses en el paradero. ¿En cuántos minutos volverán a coincidir en la estación?}',
    options: ['30 minutos', '35 minutos', '60 minutos', '300 minutos'],
    correctAnswer: 2,
    explanation: '15 = 3 \\times 5, \\quad 20 = 2^2 \\times 5 \\quad \\Rightarrow \\quad \\text{MCM} = 2^2 \\times 3 \\times 5 = 60',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['numeros-mcd-mcm', 'numeros-factorizacion-prima', 'numeros-problemas-unidades-conversiones']
  },
  {
    id: 'm1-66',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\text{Divisibilidad por 3}',
    questionLatex: '\\text{En una clase de teoría de números, el profesor enseña la regla de divisibilidad por 3: un número es divisible por 3 si la suma de sus dígitos es divisible por 3. Como ejercicio de práctica, muestra cuatro números a sus estudiantes y les pide identificar cuál de ellos cumple con esta regla. Los números son 124, 235, 342 y 455. ¿Cuál de los siguientes números es divisible por 3?}',
    options: ['124', '235', '342', '455'],
    correctAnswer: 2,
    explanation: '342: \\quad 3+4+2 = 9 \\text{ (divisible por 3)} \\quad \\Rightarrow \\quad 342 \\text{ es divisible por 3}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['numeros-patrones-signos', 'numeros-argumentar-sentido-resultado']
  },
  {
    id: 'm1-67',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\text{Divisibilidad por 9}',
    questionLatex: '\\text{Un estudiante está aprendiendo las reglas de divisibilidad y su profesor le explica que un número es divisible por 9 si la suma de sus dígitos también es divisible por 9. Para practicar, le presenta cuatro números diferentes: 234, 567, 729 y 891. El estudiante debe aplicar esta regla a cada número y determinar cuál cumple con la condición de divisibilidad por 9. ¿Cuál de los siguientes números es divisible por 9?}',
    options: ['234', '567', '729', '891'],
    correctAnswer: 2,
    explanation: '729: \\quad 7+2+9 = 18 \\text{ (divisible por 9)} \\quad \\Rightarrow \\quad 729 \\text{ es divisible por 9}',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['numeros-patrones-signos', 'numeros-argumentar-sentido-resultado']
  },
  {
    id: 'm1-68',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\text{Regla divisibilidad por 11}',
    questionLatex: '\\text{En una clase avanzada de matemática, el profesor presenta la regla de divisibilidad por 11 para números de tres dígitos. Explica que un número es divisible por 11 si la diferencia entre la suma de los dígitos en posiciones impares y la suma de los dígitos en posiciones pares es cero o un múltiplo de 11. Les pide a los estudiantes que identifiquen esta regla entre varias opciones presentadas. Un número de tres dígitos es divisible por 11 si:}',
    options: ['La suma de sus dígitos es 11', 'La diferencia entre la suma de dígitos en posiciones impares y pares es 0 o múltiplo de 11', 'El último dígito es 1', 'La suma de sus dígitos es divisible por 11'],
    correctAnswer: 1,
    explanation: '\\text{Ejemplo: } 121 \\rightarrow (1+1)-2 = 0 \\text{ (divisible por 11)}',
    difficulty: 'medium',
    difficultyScore: 0.35,
    skills: ['numeros-patrones-signos', 'numeros-argumentar-sentido-resultado']
  },
  {
    id: 'm1-114',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\text{Identificar número irracional}',
    questionLatex: '\\text{En una clase de teoría de números, el profesor explica la diferencia entre números racionales e irracionales. Los números racionales pueden expresarse como fracción de dos enteros, mientras que los irracionales no. Presenta cuatro números a sus estudiantes: 22/7, la raíz cuadrada de 16, pi, y 0.333... periódico. Les pide identificar cuál de estos números no puede expresarse como fracción exacta. ¿Cuál de los siguientes es un número irracional?}',
    options: ['\\frac{22}{7}', '\\sqrt{16}', '\\pi', '0.\\overline{3}'],
    correctAnswer: 2,
    explanation: '\\pi \\text{ es irracional. } \\frac{22}{7} \\text{ y } 0.\\overline{3} \\text{ son racionales, } \\sqrt{16}=4',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['numeros-racionales-comprender-significado', 'numeros-argumentar-sentido-resultado']
  },
  {
    id: 'm1-115',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\text{Identificar número racional}',
    questionLatex: '\\text{Un profesor presenta a sus estudiantes cuatro expresiones diferentes y les explica que deben identificar cuál representa un número racional, es decir, un número que puede expresarse como fracción de dos enteros. Las opciones son pi, la raíz cuadrada de 2, la raíz cuadrada de 9, y la raíz cuadrada de 7. Los estudiantes deben determinar cuál de estas raíces resulta en un número entero o fraccionario. ¿Cuál de los siguientes es un número racional?}',
    options: ['\\pi', '\\sqrt{2}', '\\sqrt{9}', '\\sqrt{7}'],
    correctAnswer: 2,
    explanation: '\\sqrt{9} = 3 \\text{ (racional). Los demás son irracionales.}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['numeros-racionales-comprender-significado', 'numeros-raices']
  },
  // ========================================
  // OPERACIONES CON FRACCIONES DE DISTINTO DENOMINADOR
  // ========================================
  {
    id: 'm1-137',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\frac{1}{3} + \\frac{1}{4}',
    questionLatex: '\\text{María está cocinando y necesita mezclar ingredientes. La receta indica que debe agregar } \\frac{1}{3} \\text{ de taza de harina y } \\frac{1}{4} \\text{ de taza de azúcar. Quiere saber cuántas tazas en total de ingredientes secos está agregando. ¿Cuál es el resultado de sumar estas fracciones?}',
    options: ['\\frac{2}{7}', '\\frac{5}{12}', '\\frac{7}{12}', '\\frac{4}{7}'],
    correctAnswer: 2,
    explanation: '\\frac{1}{3} + \\frac{1}{4} = \\frac{4}{12} + \\frac{3}{12} = \\frac{7}{12}',
    difficulty: 'easy',
    difficultyScore: 0.32,
    skills: ['numeros-fracciones', 'numeros-fracciones-sumar-restar-distinto-denominador', 'numeros-mcd-mcm', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-138',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\frac{2}{5} + \\frac{1}{3}',
    questionLatex: '\\text{En un proyecto escolar, dos grupos deben completar partes de un trabajo. El primer grupo completó } \\frac{2}{5} \\text{ del proyecto y el segundo grupo completó } \\frac{1}{3}\\text{. ¿Qué fracción del proyecto han completado entre ambos grupos?}',
    options: ['\\frac{3}{8}', '\\frac{5}{8}', '\\frac{11}{15}', '\\frac{7}{15}'],
    correctAnswer: 2,
    explanation: '\\frac{2}{5} + \\frac{1}{3} = \\frac{6}{15} + \\frac{5}{15} = \\frac{11}{15}',
    difficulty: 'easy',
    difficultyScore: 0.32,
    skills: ['numeros-fracciones', 'numeros-fracciones-sumar-restar-distinto-denominador', 'numeros-mcd-mcm', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-139',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\frac{3}{4} - \\frac{1}{6}',
    questionLatex: '\\text{Pedro tenía } \\frac{3}{4} \\text{ de una pizza. Comió } \\frac{1}{6} \\text{ de la pizza completa. ¿Qué fracción de la pizza le queda?}',
    options: ['\\frac{1}{2}', '\\frac{7}{12}', '\\frac{5}{8}', '\\frac{2}{3}'],
    correctAnswer: 1,
    explanation: '\\frac{3}{4} - \\frac{1}{6} = \\frac{9}{12} - \\frac{2}{12} = \\frac{7}{12}',
    difficulty: 'easy',
    difficultyScore: 0.32,
    skills: ['numeros-fracciones', 'numeros-fracciones-sumar-restar-distinto-denominador', 'numeros-mcd-mcm', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-140',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\frac{5}{6} + \\frac{2}{9}',
    questionLatex: '\\text{En una carrera de relevos, el primer corredor completó } \\frac{5}{6} \\text{ del recorrido total y el segundo corredor agregó } \\frac{2}{9} \\text{ adicionales. ¿Qué fracción del recorrido han completado en total?}',
    options: ['\\frac{7}{15}', '\\frac{19}{18}', '\\frac{11}{18}', '\\frac{17}{18}'],
    correctAnswer: 1,
    explanation: '\\frac{5}{6} + \\frac{2}{9} = \\frac{15}{18} + \\frac{4}{18} = \\frac{19}{18}',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['numeros-fracciones', 'numeros-fracciones-sumar-restar-distinto-denominador', 'numeros-fracciones-impropias-mixtos', 'numeros-mcd-mcm', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-141',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\frac{7}{8} - \\frac{3}{10}',
    questionLatex: '\\text{Un tanque de agua estaba lleno en sus } \\frac{7}{8} \\text{ partes. Se usaron } \\frac{3}{10} \\text{ del tanque para regar el jardín. ¿Qué fracción del tanque queda con agua?}',
    options: ['\\frac{4}{18}', '\\frac{23}{40}', '\\frac{1}{2}', '\\frac{27}{40}'],
    correctAnswer: 1,
    explanation: '\\frac{7}{8} - \\frac{3}{10} = \\frac{35}{40} - \\frac{12}{40} = \\frac{23}{40}',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['numeros-fracciones', 'numeros-fracciones-sumar-restar-distinto-denominador', 'numeros-mcd-mcm', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-142',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\frac{2}{3} + \\frac{3}{5} + \\frac{1}{2}',
    questionLatex: '\\text{Tres amigos están juntando dinero para un regalo. El primero aporta } \\frac{2}{3} \\text{ del precio, el segundo aporta } \\frac{3}{5}\\text{, y el tercero aporta } \\frac{1}{2}\\text{. ¿Qué fracción del precio han juntado en total?}',
    options: ['\\frac{53}{30}', '\\frac{47}{30}', '\\frac{6}{10}', '\\frac{5}{6}'],
    correctAnswer: 0,
    explanation: '\\frac{2}{3} + \\frac{3}{5} + \\frac{1}{2} = \\frac{20}{30} + \\frac{18}{30} + \\frac{15}{30} = \\frac{53}{30}',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['numeros-fracciones', 'numeros-fracciones-sumar-restar-distinto-denominador', 'numeros-mcd-mcm', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-143',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\frac{5}{12} - \\frac{1}{8} + \\frac{2}{3}',
    questionLatex: '\\text{En un experimento de química, se mezclan tres cantidades de líquidos: se agregan } \\frac{5}{12} \\text{ de litro de una solución, se quitan } \\frac{1}{8} \\text{ de litro de otra, y se agregan } \\frac{2}{3} \\text{ de litro de una tercera. ¿Cuál es el volumen total final en litros?}',
    options: ['\\frac{13}{24}', '\\frac{17}{24}', '\\frac{19}{24}', '\\frac{23}{24}'],
    correctAnswer: 3,
    explanation: '\\frac{5}{12} - \\frac{1}{8} + \\frac{2}{3} = \\frac{10}{24} - \\frac{3}{24} + \\frac{16}{24} = \\frac{23}{24}',
    difficulty: 'medium',
    difficultyScore: 0.48,
    skills: ['numeros-fracciones', 'numeros-fracciones-sumar-restar-distinto-denominador', 'numeros-mcd-mcm', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-144',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\frac{11}{15} - \\frac{7}{20}',
    questionLatex: '\\text{Una biblioteca tiene dos secciones de libros. La sección de ficción representa } \\frac{11}{15} \\text{ del total de libros, y la sección de referencia representa } \\frac{7}{20}\\text{. ¿Cuál es la diferencia entre estas fracciones?}',
    options: ['\\frac{4}{35}', '\\frac{23}{60}', '\\frac{1}{3}', '\\frac{13}{30}'],
    correctAnswer: 1,
    explanation: '\\frac{11}{15} - \\frac{7}{20} = \\frac{44}{60} - \\frac{21}{60} = \\frac{23}{60}',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['numeros-fracciones', 'numeros-fracciones-sumar-restar-distinto-denominador', 'numeros-mcd-mcm', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-145',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '\\frac{1}{2} + \\frac{1}{3} + \\frac{1}{4} + \\frac{1}{6}',
    questionLatex: '\\text{Cuatro estudiantes deben completar partes de un proyecto grupal. El primero hace } \\frac{1}{2}\\text{, el segundo } \\frac{1}{3}\\text{, el tercero } \\frac{1}{4}\\text{, y el cuarto } \\frac{1}{6}\\text{. ¿Qué fracción del proyecto completaron en total?}',
    options: ['1', '\\frac{5}{4}', '\\frac{3}{2}', '\\frac{13}{12}'],
    correctAnswer: 1,
    explanation: '\\frac{1}{2} + \\frac{1}{3} + \\frac{1}{4} + \\frac{1}{6} = \\frac{6+4+3+2}{12} = \\frac{15}{12} = \\frac{5}{4}',
    difficulty: 'medium',
    difficultyScore: 0.48,
    skills: ['numeros-fracciones', 'numeros-fracciones-sumar-restar-distinto-denominador', 'numeros-mcd-mcm', 'numeros-simplificar-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-146',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    operacionBase: '1 - \\frac{2}{5} - \\frac{1}{5} - \\frac{1}{6}',
    questionLatex: '\\text{Un agricultor tiene un terreno del cual usa } \\frac{2}{5} \\text{ para cultivo, luego separa } \\frac{1}{5} \\text{ del terreno total para pastoreo, y finalmente reserva } \\frac{1}{6} \\text{ para construcción. ¿Qué fracción del terreno queda disponible después de estas asignaciones?}',
    options: ['\\frac{1}{3}', '\\frac{4}{15}', '\\frac{7}{30}', '\\frac{1}{5}'],
    correctAnswer: 2,
    explanation: '1 - \\frac{2}{5} - \\frac{1}{5} - \\frac{1}{6} = \\frac{30-12-6-5}{30} = \\frac{7}{30}',
    difficulty: 'medium',
    difficultyScore: 0.48,
    skills: ['numeros-fracciones', 'numeros-fracciones-sumar-restar-distinto-denominador', 'numeros-mcd-mcm', 'numeros-operaciones-basicas']
  }
];
