import { Question } from '../../../types';

export const m1NumerosPorcentajeQuestions: Question[] = [
  {
    id: 'm1-7',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'El 25% de 80 es igual a:',
    questionLatex: '\\text{El 25\\% de 80 es igual a:}',
    options: ['15', '20', '25', '30'],
    correctAnswer: 1,
    explanation: 'Calculamos el porcentaje:',
    explanationLatex: '25\\% \\text{ de } 80 = 0.25 \\times 80 = 20',
    difficulty: 'easy',
    skills: ['numeros-porcentajes', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-27',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Una camisa cuesta $20.000 y tiene un descuento del 15%. ¿Cuál es el precio final?',
    questionLatex: '\\text{Una camisa cuesta \\$20.000 y tiene un descuento del 15\\%. ¿Cuál es el precio final?}',
    options: ['$15.000', '$17.000', '$17.500', '$18.000'],
    correctAnswer: 1,
    explanation: 'Calculamos el 15% de descuento y lo restamos del precio original:',
    explanationLatex: '20.000 \\times 0.15 = 3.000 \\quad \\Rightarrow \\quad 20.000 - 3.000 = 17.000',
    difficulty: 'easy',
    skills: ['numeros-porcentajes', 'numeros-porcentajes-descuentos', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-94',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Una mezcla contiene 40% de agua y 60% de alcohol. Si tengo 50 litros de mezcla, ¿cuántos litros de alcohol hay?',
    questionLatex: '\\text{Una mezcla contiene 40\\% agua y 60\\% alcohol. Con 50 litros de mezcla, ¿cuántos litros de alcohol?}',
    options: ['20 litros', '25 litros', '30 litros', '35 litros'],
    correctAnswer: 2,
    explanation: 'Calculamos el 60% de 50 litros:',
    explanationLatex: '0.60 \\times 50 = 30 \\text{ litros de alcohol}',
    difficulty: 'easy',
    skills: ['numeros-porcentajes', 'numeros-proporcionalidad', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-96',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'El precio de un producto aumenta de $20.000 a $25.000. ¿Cuál es el porcentaje de aumento?',
    questionLatex: '\\text{El precio aumenta de \\$20.000 a \\$25.000. ¿Porcentaje de aumento?}',
    options: ['20%', '25%', '30%', '35%'],
    correctAnswer: 1,
    explanation: 'Calculamos la diferencia y la dividimos por el valor original:',
    explanationLatex: '\\frac{25000 - 20000}{20000} \\times 100\\% = \\frac{5000}{20000} \\times 100\\% = 25\\%',
    difficulty: 'medium',
    skills: ['numeros-porcentajes', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-97',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Una población disminuye de 8.000 a 6.400 habitantes. ¿Cuál es el porcentaje de disminución?',
    questionLatex: '\\text{Una población disminuye de 8.000 a 6.400. ¿Porcentaje de disminución?}',
    options: ['15%', '20%', '25%', '30%'],
    correctAnswer: 1,
    explanation: 'Calculamos la disminución relativa:',
    explanationLatex: '\\frac{8000 - 6400}{8000} \\times 100\\% = \\frac{1600}{8000} \\times 100\\% = 20\\%',
    difficulty: 'medium',
    skills: ['numeros-porcentajes', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-98',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'El sueldo de Pedro aumentó en un 12% y ahora gana $560.000. ¿Cuánto ganaba antes?',
    questionLatex: '\\text{El sueldo aumentó 12\\% y ahora es \\$560.000. ¿Cuánto ganaba antes?}',
    options: ['$480.000', '$500.000', '$520.000', '$540.000'],
    correctAnswer: 1,
    explanation: 'Si aumentó 12%, el nuevo sueldo es 112% del original:',
    explanationLatex: '1.12x = 560000 \\quad \\Rightarrow \\quad x = \\frac{560000}{1.12} = 500.000',
    difficulty: 'hard',
    skills: ['numeros-porcentajes', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-99',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Se depositan $100.000 en un banco que paga 5% de interés simple anual. ¿Cuánto dinero habrá después de 1 año?',
    questionLatex: '\\text{Se depositan \\$100.000 al 5\\% simple anual. ¿Cuánto habrá en 1 año?}',
    options: ['$105.000', '$110.000', '$115.000', '$120.000'],
    correctAnswer: 0,
    explanation: 'El interés es el 5% del capital:',
    explanationLatex: '100000 + (0.05 \\times 100000) = 100000 + 5000 = 105.000',
    difficulty: 'easy',
    skills: ['numeros-porcentajes', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-100',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Un capital de $50.000 genera $3.000 de interés simple en 1 año. ¿Cuál es la tasa de interés anual?',
    questionLatex: '\\text{Un capital de \\$50.000 genera \\$3.000 en 1 año. ¿Tasa de interés?}',
    options: ['4%', '5%', '6%', '7%'],
    correctAnswer: 2,
    explanation: 'La tasa es la razón entre el interés y el capital:',
    explanationLatex: '\\frac{3000}{50000} \\times 100\\% = 6\\%',
    difficulty: 'medium',
    skills: ['numeros-porcentajes', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-101',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Se depositan $200.000 al 8% de interés simple anual. ¿Cuánto dinero habrá después de 2 años?',
    questionLatex: '\\text{Se depositan \\$200.000 al 8\\% simple anual. ¿Cuánto en 2 años?}',
    options: ['$216.000', '$224.000', '$232.000', '$240.000'],
    correctAnswer: 2,
    explanation: 'El interés por 2 años es 16% del capital:',
    explanationLatex: '200000 + (0.08 \\times 200000 \\times 2) = 200000 + 32000 = 232.000',
    difficulty: 'medium',
    skills: ['numeros-porcentajes', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-102',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: '¿Cuánto es el 20% del 50% de 200?',
    questionLatex: '\\text{¿Cuánto es el 20\\% del 50\\% de 200?}',
    options: ['10', '20', '30', '40'],
    correctAnswer: 1,
    explanation: 'Calculamos paso a paso:',
    explanationLatex: '50\\% \\text{ de } 200 = 100, \\quad 20\\% \\text{ de } 100 = 20',
    difficulty: 'easy',
    skills: ['numeros-porcentajes', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-103',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Un producto tiene un descuento del 30% y luego otro descuento del 10% sobre el precio rebajado. Si el precio original es $100.000, ¿cuál es el precio final?',
    questionLatex: '\\text{Descuentos sucesivos de 30\\% y 10\\% sobre \\$100.000. ¿Precio final?}',
    options: ['$60.000', '$63.000', '$66.000', '$70.000'],
    correctAnswer: 1,
    explanation: 'Aplicamos los descuentos en secuencia:',
    explanationLatex: '100000 \\times 0.70 \\times 0.90 = 70000 \\times 0.90 = 63.000',
    difficulty: 'hard',
    skills: ['numeros-porcentajes', 'numeros-porcentajes-descuentos', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-104',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: '¿Cuál es el 25% del 40% de 800?',
    questionLatex: '\\text{¿Cuál es el 25\\% del 40\\% de 800?}',
    options: ['60', '70', '80', '90'],
    correctAnswer: 2,
    explanation: 'Calculamos los porcentajes en secuencia:',
    explanationLatex: '40\\% \\text{ de } 800 = 320, \\quad 25\\% \\text{ de } 320 = 80',
    difficulty: 'medium',
    skills: ['numeros-porcentajes', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-105',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Después de un descuento del 20%, un producto cuesta $24.000. ¿Cuál era el precio original?',
    questionLatex: '\\text{Después de un descuento del 20\\%, cuesta \\$24.000. ¿Precio original?}',
    options: ['$28.000', '$30.000', '$32.000', '$36.000'],
    correctAnswer: 1,
    explanation: 'Si tiene 20% de descuento, pagamos el 80% del precio original:',
    explanationLatex: '0.80x = 24000 \\quad \\Rightarrow \\quad x = \\frac{24000}{0.80} = 30.000',
    difficulty: 'medium',
    skills: ['numeros-porcentajes', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-106',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'El precio de un producto aumentó en un 25% y ahora cuesta $50.000. ¿Cuál era el precio original?',
    questionLatex: '\\text{Aumentó 25\\% y ahora cuesta \\$50.000. ¿Precio original?}',
    options: ['$37.500', '$40.000', '$42.500', '$45.000'],
    correctAnswer: 1,
    explanation: 'El precio actual es 125% del precio original:',
    explanationLatex: '1.25x = 50000 \\quad \\Rightarrow \\quad x = \\frac{50000}{1.25} = 40.000',
    difficulty: 'medium',
    skills: ['numeros-porcentajes', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-107',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'El 35% de un número es 70. ¿Cuál es el número?',
    questionLatex: '\\text{El 35\\% de un número es 70. ¿Cuál es el número?}',
    options: ['150', '180', '200', '240'],
    correctAnswer: 2,
    explanation: 'Planteamos la ecuación:',
    explanationLatex: '0.35x = 70 \\quad \\Rightarrow \\quad x = \\frac{70}{0.35} = 200',
    difficulty: 'hard',
    skills: ['numeros-porcentajes', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  }
];
