import { Question } from '../../../types';

/**
 * M2-PROB-003: Conceptos y resolución de problemas de conteo (permutación y combinatoria)
 *
 * Total questions: 39 (19 original + 20 new)
 *
 * Subsections:
 * A. Principio multiplicativo
 *    Habilidades: conteo-principio-multiplicativo
 * B. Permutaciones
 *    Habilidades: conteo-permutaciones
 * C. Combinaciones
 *    Habilidades: conteo-combinaciones
 * D. Problemas de conteo en probabilidad
 *    Habilidades: conteo-problemas-probabilidad
 */

export const m2Prob003Questions: Question[] = [
  // Subsection A: Principio multiplicativo
  {
    id: 'm2-prob-mult-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'n_1 \\times n_2 \\times n_3',
    questionLatex: '\\text{En un restaurant ofrecen un menú que incluye 3 tipos de entrada, 4 platos de fondo y 2 postres. Si un cliente debe elegir exactamente una opción de cada categoría, ¿de cuántas formas diferentes puede armar su menú completo?}',
    options: ['9', '12', '24', '32'],
    correctAnswer: 2,
    explanation: '3 \\times 4 \\times 2 = 24',
    difficulty: 'easy',
    difficultyScore: 0.18,
    skills: ['combinatoria-principio-multiplicativo', 'numeros-multiplicacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-mult-2',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '26^2 \\times 10^3',
    questionLatex: '\\text{Para crear una contraseña se deben elegir 2 letras (de un alfabeto de 26 letras) seguidas de 3 dígitos (del 0 al 9). Si se pueden repetir letras y dígitos, ¿cuántas contraseñas diferentes se pueden crear?}',
    options: ['26.000', '260.000', '676.000', '1.000.000'],
    correctAnswer: 2,
    explanation: '26^2 \\times 10^3 = 676 \\times 1{,}000 = 676{,}000',
    difficulty: 'medium',
    difficultyScore: 0.32,
    skills: ['combinatoria-principio-multiplicativo', 'numeros-potencias', 'numeros-multiplicacion', 'numeros-operaciones-basicas']
  },
  // Subsection B: Permutaciones
  {
    id: 'm2-prob-perm-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(n,r) = \\frac{n!}{(n-r)!}',
    questionLatex: '\\text{En una carrera participan 6 atletas y se entregarán medallas de oro, plata y bronce a los tres primeros lugares. ¿De cuántas formas diferentes se pueden asignar estas tres medallas?}',
    options: ['18', '20', '120', '216'],
    correctAnswer: 2,
    explanation: 'P(6,3) = \\frac{6!}{3!} = 6 \\times 5 \\times 4 = 120',
    difficulty: 'medium',
    difficultyScore: 0.35,
    skills: ['combinatoria-permutaciones', 'probabilidad-factorial', 'numeros-multiplicacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-comb-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'C(n,r) = \\frac{n!}{r!(n-r)!}',
    questionLatex: '\\text{Una profesora de música necesita formar un grupo de cámara seleccionando 3 estudiantes de un grupo de 5 violinistas. Como todos tocan el mismo instrumento, solo importa quiénes son seleccionados, no el orden. ¿De cuántas formas diferentes puede la profesora elegir a los 3 estudiantes para el grupo?}',
    options: ['10', '15', '20', '60'],
    correctAnswer: 0,
    explanation: 'C(5,3) = \\frac{5!}{3! \\times 2!} = \\frac{5 \\times 4}{2 \\times 1} = 10',
    difficulty: 'medium',
    difficultyScore: 0.35,
    skills: ['combinatoria-combinaciones', 'probabilidad-factorial', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-perm-ord-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(n) = n!',
    questionLatex: '\\text{Una bibliotecaria debe organizar 4 libros diferentes de literatura en un estante. Los libros deben quedar en fila y el orden en que se coloquen es importante porque afecta la estética del estante. ¿De cuántas formas diferentes puede la bibliotecaria ordenar estos 4 libros?}',
    options: ['12', '16', '20', '24'],
    correctAnswer: 3,
    explanation: 'P(4) = 4! = 4 \\times 3 \\times 2 \\times 1 = 24',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['combinatoria-permutaciones', 'probabilidad-factorial', 'numeros-operaciones-basicas']
  },
  // Subsection C: Combinaciones
  {
    id: 'm2-prob-comb-2',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'C(12,5) - C(10,3)',
    questionLatex: '\\text{Se forman equipos de 5 personas de un grupo de 12. Si dos personas específicas NO pueden estar juntas en el equipo, ¿cuántos equipos diferentes se pueden formar?}',
    options: ['672', '720', '792', '462'],
    correctAnswer: 0,
    explanation: 'C(12,5) - C(10,3) = 792 - 120 = 672',
    difficulty: 'hard',
    difficultyScore: 0.58,
    skills: ['probabilidad-combinatoria', 'probabilidad-combinaciones', 'probabilidad-casos-excluyentes', 'probabilidad-factorial', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-comb-3',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'C(n,2) = \\frac{n(n-1)}{2}',
    questionLatex: '\\text{El consejo estudiantil de un colegio está compuesto por 8 estudiantes. Para asistir a un congreso nacional, deben elegir a 2 representantes del consejo. Como ambos representantes tendrán las mismas funciones, no importa el orden de selección. ¿De cuántas maneras diferentes se pueden elegir los 2 representantes?}',
    options: ['16', '28', '56', '64'],
    correctAnswer: 1,
    explanation: 'C(8,2) = \\frac{8!}{2! \\times 6!} = \\frac{8 \\times 7}{2} = 28',
    difficulty: 'medium',
    difficultyScore: 0.32,
    skills: ['probabilidad-combinatoria', 'probabilidad-combinaciones', 'probabilidad-factorial', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-comb-4',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(n,r) = n \\times (n-1) \\times \\cdots \\times (n-r+1)',
    questionLatex: '\\text{Un programador debe crear códigos de acceso de 3 dígitos usando los números 1, 2, 3, 4 y 5, sin repetir ningún dígito. Cada código es una secuencia ordenada donde importa la posición de cada dígito. ¿Cuántos códigos de acceso diferentes puede crear el programador?}',
    options: ['10', '20', '60', '125'],
    correctAnswer: 2,
    explanation: 'P(5,3) = \\frac{5!}{2!} = 5 \\times 4 \\times 3 = 60',
    difficulty: 'medium',
    difficultyScore: 0.35,
    skills: ['combinatoria-permutaciones', 'probabilidad-factorial', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-comb-5',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'C(9,3) - C(5,3)',
    questionLatex: '\\text{Un comité de 3 personas debe incluir al menos 1 mujer. Si hay 5 hombres y 4 mujeres disponibles, ¿cuántos comités diferentes se pueden formar?}',
    options: ['74', '80', '84', '120'],
    correctAnswer: 0,
    explanation: 'C(9,3) - C(5,3) = 84 - 10 = 74',
    difficulty: 'hard',
    difficultyScore: 0.55,
    skills: ['combinatoria-combinaciones', 'probabilidad-casos-excluyentes', 'probabilidad-factorial', 'numeros-operaciones-basicas']
  },
  // Subsection D: Problemas de conteo en probabilidad
  {
    id: 'm2-prob-cont-prob-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'C(n,r)',
    questionLatex: '\\text{En una urna hay 5 bolitas rojas y 3 bolitas azules. Si se extraen 2 bolitas sin reposición, ¿cuántos resultados diferentes son posibles?}',
    options: ['16', '24', '28', '64'],
    correctAnswer: 2,
    explanation: 'C(8,2) = \\frac{8 \\times 7}{2} = 28',
    difficulty: 'medium',
    difficultyScore: 0.32,
    skills: ['combinatoria-problemas-probabilidad', 'combinatoria-combinaciones', 'probabilidad-factorial', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-cont-prob-2',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'n^r \\text{ (con repetición)}',
    questionLatex: '\\text{Un dado se lanza 3 veces. ¿Cuántos resultados diferentes son posibles si importa el orden en que salen los números?}',
    options: ['18', '20', '120', '216'],
    correctAnswer: 3,
    explanation: '6^3 = 216',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['combinatoria-problemas-probabilidad', 'combinatoria-principio-multiplicativo', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  // Additional Subsection B: Permutaciones
  {
    id: 'm2-prob-perm-2',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(n) = n!',
    questionLatex: '\\text{En una ceremonia de premiación, 5 estudiantes destacados deben sentarse en una fila de 5 sillas en el escenario. El orden en que se sienten determinará el orden de entrega de sus diplomas. ¿De cuántas formas diferentes pueden sentarse los 5 estudiantes en las 5 sillas?}',
    options: ['25', '60', '100', '120'],
    correctAnswer: 3,
    explanation: 'P(5) = 5! = 120',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['conteo-permutaciones', 'probabilidad-factorial', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-perm-3',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(10,4) = 10 \\times 9 \\times 8 \\times 7',
    questionLatex: '\\text{Un sistema de seguridad requiere una contraseña de exactamente 4 dígitos diferentes, usando los dígitos del 0 al 9 sin repetir ninguno. El técnico de seguridad necesita saber cuántas contraseñas distintas pueden configurarse en el sistema. ¿Cuántas contraseñas de 4 dígitos sin repetición se pueden crear?}',
    options: ['5{,}040', '10{,}000', '24', '210'],
    correctAnswer: 0,
    explanation: 'P(10,4) = 10 \\times 9 \\times 8 \\times 7 = 5{,}040',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['conteo-permutaciones', 'probabilidad-factorial', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-perm-4',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\frac{n!}{n_1! \\times n_2! \\times \\cdots}',
    questionLatex: '\\text{Una estudiante de lingüística está estudiando anagramas, que son reordenamientos de las letras de una palabra. Quiere calcular cuántos anagramas diferentes se pueden formar con las letras de la palabra CASA, considerando que la letra A aparece dos veces. ¿Cuántos anagramas distintos tiene la palabra CASA?}',
    options: ['4', '6', '12', '24'],
    correctAnswer: 2,
    explanation: '\\frac{4!}{2!} = \\frac{24}{2} = 12',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['conteo-permutaciones', 'probabilidad-factorial', 'probabilidad-permutaciones-repeticion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-perm-5',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(n,2) = n \\times (n-1)',
    questionLatex: '\\text{En un torneo de fútbol participan 8 equipos en formato de eliminación directa. Al finalizar el torneo, se entregarán trofeos al campeón (primer lugar) y al subcampeón (segundo lugar). Como el orden importa (no es lo mismo ser campeón que subcampeón), ¿de cuántas formas diferentes se pueden asignar estos dos primeros lugares?}',
    options: ['16', '28', '56', '64'],
    correctAnswer: 2,
    explanation: 'P(8,2) = 8 \\times 7 = 56',
    difficulty: 'easy',
    difficultyScore: 0.32,
    skills: ['conteo-permutaciones', 'probabilidad-factorial', 'numeros-operaciones-basicas']
  },
  // Additional Subsection C: Combinaciones
  {
    id: 'm2-prob-comb-6',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'C(n,r) = \\frac{n!}{r!(n-r)!}',
    questionLatex: '\\text{Un entrenador de voleibol tiene un plantel de 10 jugadores y debe seleccionar a 4 de ellos para que formen parte del equipo titular. Como todas las posiciones son intercambiables en el momento de la selección, solo importa quiénes son elegidos. ¿De cuántas formas diferentes puede el entrenador elegir a los 4 titulares?}',
    options: ['40', '210', '5{,}040', '151{,}200'],
    correctAnswer: 1,
    explanation: 'C(10,4) = \\frac{10!}{4! \\times 6!} = 210',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['conteo-combinaciones', 'probabilidad-factorial', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-comb-7',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'C(5,2) = \\frac{5 \\times 4}{2}',
    questionLatex: '\\text{Un profesor de teoría de conjuntos le pide a sus estudiantes que determinen cuántos subconjuntos de exactamente 2 elementos se pueden formar a partir del conjunto } \\{a, b, c, d, e\\}\\text{. Como un subconjunto no considera el orden de sus elementos, ¿cuántos subconjuntos de 2 elementos tiene este conjunto?}',
    options: ['5', '10', '20', '25'],
    correctAnswer: 1,
    explanation: 'C(5,2) = \\frac{5 \\times 4}{2} = 10',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['conteo-combinaciones', 'probabilidad-factorial', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-comb-8',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'C(7,3)',
    questionLatex: '\\text{Una pizzería ofrece a sus clientes la opción de personalizar su pizza eligiendo exactamente 3 ingredientes de un menú de 7 ingredientes disponibles. Un cliente quiere saber cuántas pizzas diferentes puede crear con estas opciones. Como el orden en que se agregan los ingredientes no importa, ¿cuántas combinaciones diferentes de ingredientes puede elegir el cliente?}',
    options: ['21', '35', '42', '210'],
    correctAnswer: 1,
    explanation: 'C(7,3) = \\frac{7 \\times 6 \\times 5}{6} = 35',
    difficulty: 'medium',
    difficultyScore: 0.35,
    skills: ['conteo-combinaciones', 'probabilidad-factorial', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-comb-9',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Permutación: orden importa; Combinación: orden no importa}',
    questionLatex: '\\text{Un profesor de estadística explica a sus estudiantes la diferencia entre permutaciones y combinaciones. Les presenta dos situaciones: formar una fila con 3 personas (donde importa quién va primero, segundo y tercero) versus elegir un comité de 3 personas (donde solo importa quiénes son elegidos). ¿Cuál es la diferencia fundamental entre permutación y combinación?}',
    options: ['\\text{Permutación: orden importa}', '\\text{Combinación: orden importa}', '\\text{Son lo mismo}', '\\text{Depende del contexto}'],
    correctAnswer: 0,
    explanation: '\\text{Permutación: } ABC \\neq BAC; \\quad \\text{Combinación: } \\{A,B,C\\} = \\{B,A,C\\}',
    difficulty: 'easy',
    difficultyScore: 0.15,
    skills: ['conteo-permutaciones', 'conteo-combinaciones', 'probabilidad-conceptos']
  },
  // ==================== NEW QUESTIONS (20) ====================
  // Subsection A: Principio multiplicativo (+8)
  {
    id: 'm2-prob-003-001',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'n_1 \\times n_2',
    questionLatex: '\\text{Una tienda de helados ofrece 5 sabores y 4 tipos de cono. Si un cliente elige exactamente un sabor y un tipo de cono, ¿cuántas combinaciones diferentes puede pedir?}',
    options: ['9', '15', '20', '25'],
    correctAnswer: 2,
    explanation: '5 \\times 4 = 20',
    difficulty: 'easy',
    difficultyScore: 0.15,
    skills: ['combinatoria-principio-multiplicativo', 'numeros-multiplicacion']
  },
  {
    id: 'm2-prob-003-002',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'n_1 \\times n_2 \\times n_3 \\times n_4',
    questionLatex: '\\text{Para formar un equipo escolar, se debe elegir 1 capitán de 3 candidatos, 1 arquero de 4 candidatos, 1 defensa de 5 candidatos y 1 delantero de 6 candidatos. ¿De cuántas formas diferentes se puede armar el equipo?}',
    options: ['18', '120', '360', '720'],
    correctAnswer: 2,
    explanation: '3 \\times 4 \\times 5 \\times 6 = 360',
    difficulty: 'medium',
    difficultyScore: 0.35,
    skills: ['combinatoria-principio-multiplicativo', 'numeros-multiplicacion']
  },
  {
    id: 'm2-prob-003-003',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '2 \\times 3 \\times 4',
    questionLatex: '\\text{Una cafetería ofrece café en 2 tamaños, con 3 tipos de leche y 4 saborizantes opcionales. Si un cliente debe elegir un tamaño, un tipo de leche y un saborizante, ¿cuántos cafés diferentes puede ordenar?}',
    options: ['9', '12', '18', '24'],
    correctAnswer: 3,
    explanation: '2 \\times 3 \\times 4 = 24',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['combinatoria-principio-multiplicativo', 'numeros-multiplicacion']
  },
  {
    id: 'm2-prob-003-004',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '10^4',
    questionLatex: '\\text{Un banco emite tarjetas con un PIN de 4 dígitos (0-9), pudiendo repetir dígitos. ¿Cuántos PIN diferentes son posibles?}',
    options: ['40', '5{,}040', '6{,}561', '10{,}000'],
    correctAnswer: 3,
    explanation: '10^4 = 10{,}000',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['combinatoria-principio-multiplicativo', 'numeros-potencias']
  },
  {
    id: 'm2-prob-003-005',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '26 \\times 25 \\times 10 \\times 9',
    questionLatex: '\\text{Una placa de auto tiene 2 letras distintas seguidas de 2 dígitos distintos. Usando 26 letras y 10 dígitos, ¿cuántas placas diferentes se pueden formar?}',
    options: ['45{,}000', '58{,}500', '67{,}600', '84{,}500'],
    correctAnswer: 1,
    explanation: '26 \\times 25 \\times 10 \\times 9 = 58{,}500',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['combinatoria-principio-multiplicativo', 'numeros-multiplicacion']
  },
  {
    id: 'm2-prob-003-006',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '3 \\times 4 \\times 2 \\times 2',
    questionLatex: '\\text{Un estudiante arma su almuerzo eligiendo: 1 proteína de 3 opciones, 1 acompañamiento de 4 opciones, con o sin ensalada, y con o sin postre. ¿Cuántas combinaciones de almuerzo puede crear?}',
    options: ['24', '36', '48', '96'],
    correctAnswer: 2,
    explanation: '3 \\times 4 \\times 2 \\times 2 = 48',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['combinatoria-principio-multiplicativo', 'numeros-multiplicacion']
  },
  {
    id: 'm2-prob-003-007',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '5 \\times 4 \\times 3',
    questionLatex: '\\text{Un fotógrafo debe colocar 3 modelos en fila para una foto. Tiene 5 modelos disponibles. ¿De cuántas formas puede elegir y ordenar a 3 modelos?}',
    options: ['15', '30', '60', '125'],
    correctAnswer: 2,
    explanation: '5 \\times 4 \\times 3 = 60',
    difficulty: 'medium',
    difficultyScore: 0.35,
    skills: ['combinatoria-principio-multiplicativo', 'numeros-multiplicacion']
  },
  {
    id: 'm2-prob-003-008',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '8 \\times 7 \\times 6 \\times 5',
    questionLatex: '\\text{En un concurso de canto, 8 participantes compiten por 4 premios distintos (1°, 2°, 3° y 4° lugar). ¿De cuántas formas se pueden asignar estos premios?}',
    options: ['70', '336', '1{,}680', '4{,}096'],
    correctAnswer: 2,
    explanation: '8 \\times 7 \\times 6 \\times 5 = 1{,}680',
    difficulty: 'hard',
    difficultyScore: 0.52,
    skills: ['combinatoria-principio-multiplicativo', 'numeros-multiplicacion']
  },
  // Subsection B: Permutaciones (+4)
  {
    id: 'm2-prob-003-009',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(6) = 6!',
    questionLatex: '\\text{Una familia de 6 personas se sienta alrededor de una mesa rectangular con 6 sillas en fila. ¿De cuántas formas diferentes pueden sentarse?}',
    options: ['36', '120', '720', '5{,}040'],
    correctAnswer: 2,
    explanation: '6! = 720',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['conteo-permutaciones', 'probabilidad-factorial']
  },
  {
    id: 'm2-prob-003-010',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\frac{6!}{3!}',
    questionLatex: '\\text{La palabra MAMÁ tiene 4 letras donde M aparece 2 veces y A aparece 2 veces. ¿Cuántos anagramas diferentes se pueden formar?}',
    options: ['4', '6', '12', '24'],
    correctAnswer: 1,
    explanation: '\\frac{4!}{2! \\times 2!} = \\frac{24}{4} = 6',
    difficulty: 'medium',
    difficultyScore: 0.45,
    skills: ['conteo-permutaciones', 'probabilidad-factorial', 'probabilidad-permutaciones-repeticion']
  },
  {
    id: 'm2-prob-003-011',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(7,3) = 7 \\times 6 \\times 5',
    questionLatex: '\\text{En una competencia de natación con 7 nadadores, se entregan medallas de oro, plata y bronce. ¿De cuántas formas pueden distribuirse las medallas?}',
    options: ['21', '35', '210', '343'],
    correctAnswer: 2,
    explanation: 'P(7,3) = 7 \\times 6 \\times 5 = 210',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['conteo-permutaciones', 'probabilidad-factorial']
  },
  {
    id: 'm2-prob-003-012',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\frac{6!}{3! \\times 2!}',
    questionLatex: '\\text{¿Cuántos anagramas diferentes se pueden formar con las letras de la palabra PAPAYA?}',
    options: ['60', '90', '120', '180'],
    correctAnswer: 0,
    explanation: '\\text{PAPAYA tiene 6 letras: 3 A, 2 P, 1 Y. } \\frac{6!}{3! \\times 2!} = \\frac{720}{6 \\times 2} = 60',
    difficulty: 'hard',
    difficultyScore: 0.58,
    skills: ['conteo-permutaciones', 'probabilidad-factorial', 'probabilidad-permutaciones-repeticion']
  },
  // Subsection C: Combinaciones (+1)
  {
    id: 'm2-prob-003-013',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'C(12,4)',
    questionLatex: '\\text{Un equipo de debate debe elegir 4 integrantes de un grupo de 12 estudiantes. ¿De cuántas formas puede formarse el equipo?}',
    options: ['48', '495', '11{,}880', '20{,}736'],
    correctAnswer: 1,
    explanation: 'C(12,4) = \\frac{12!}{4! \\times 8!} = 495',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['conteo-combinaciones', 'probabilidad-factorial']
  },
  // Subsection D: Problemas de conteo en probabilidad (+7)
  {
    id: 'm2-prob-003-014',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\frac{C(4,2)}{C(10,2)}',
    questionLatex: '\\text{Una bolsa tiene 4 bolitas rojas y 6 azules. Si se extraen 2 bolitas al azar sin reposición, ¿cuál es la probabilidad de que ambas sean rojas?}',
    options: ['\\frac{2}{15}', '\\frac{4}{25}', '\\frac{1}{5}', '\\frac{6}{45}'],
    correctAnswer: 0,
    explanation: '\\frac{C(4,2)}{C(10,2)} = \\frac{6}{45} = \\frac{2}{15}',
    difficulty: 'medium',
    difficultyScore: 0.45,
    skills: ['combinatoria-problemas-probabilidad', 'conteo-combinaciones', 'probabilidad-clasica']
  },
  {
    id: 'm2-prob-003-015',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\frac{P(5,3)}{5^3}',
    questionLatex: '\\text{Se lanzan 3 dados de 5 caras (1-5). ¿Cuál es la probabilidad de obtener tres números diferentes?}',
    options: ['\\frac{12}{25}', '\\frac{24}{125}', '\\frac{12}{125}', '\\frac{60}{125}'],
    correctAnswer: 0,
    explanation: '\\frac{5 \\times 4 \\times 3}{5^3} = \\frac{60}{125} = \\frac{12}{25}',
    difficulty: 'hard',
    difficultyScore: 0.55,
    skills: ['combinatoria-problemas-probabilidad', 'conteo-permutaciones', 'probabilidad-clasica']
  },
  {
    id: 'm2-prob-003-016',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\frac{C(5,2) \\times C(7,3)}{C(12,5)}',
    questionLatex: '\\text{De 5 hombres y 7 mujeres, se elige un comité de 5 personas. ¿Cuál es la probabilidad de que tenga exactamente 2 hombres y 3 mujeres?}',
    options: ['\\frac{175}{396}', '\\frac{350}{792}', '\\frac{35}{66}', '\\frac{25}{66}'],
    correctAnswer: 1,
    explanation: '\\frac{C(5,2) \\times C(7,3)}{C(12,5)} = \\frac{10 \\times 35}{792} = \\frac{350}{792}',
    difficulty: 'hard',
    difficultyScore: 0.62,
    skills: ['combinatoria-problemas-probabilidad', 'conteo-combinaciones', 'probabilidad-clasica']
  },
  {
    id: 'm2-prob-003-017',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\frac{4!}{4^4}',
    questionLatex: '\\text{Cuatro estudiantes eligen al azar un día de la semana (lunes a jueves) para entregar su tarea. ¿Cuál es la probabilidad de que todos elijan días diferentes?}',
    options: ['\\frac{3}{32}', '\\frac{6}{64}', '\\frac{24}{256}', '\\frac{1}{4}'],
    correctAnswer: 0,
    explanation: '\\frac{4!}{4^4} = \\frac{24}{256} = \\frac{3}{32}',
    difficulty: 'hard',
    difficultyScore: 0.58,
    skills: ['combinatoria-problemas-probabilidad', 'conteo-permutaciones', 'probabilidad-clasica']
  },
  {
    id: 'm2-prob-003-018',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '1 - \\frac{C(8,3)}{C(12,3)}',
    questionLatex: '\\text{En una caja hay 4 lápices rojos y 8 azules. Si se eligen 3 al azar, ¿cuál es la probabilidad de obtener al menos 1 rojo?}',
    options: ['\\frac{41}{55}', '\\frac{14}{55}', '\\frac{4}{11}', '\\frac{7}{11}'],
    correctAnswer: 0,
    explanation: '1 - \\frac{C(8,3)}{C(12,3)} = 1 - \\frac{56}{220} = \\frac{164}{220} = \\frac{41}{55}',
    difficulty: 'hard',
    difficultyScore: 0.65,
    skills: ['combinatoria-problemas-probabilidad', 'conteo-combinaciones', 'probabilidad-complemento']
  },
  {
    id: 'm2-prob-003-019',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\frac{C(6,3)}{C(9,3)}',
    questionLatex: '\\text{Una caja tiene 6 chocolates con leche y 3 amargos. Si se eligen 3 al azar, ¿cuál es la probabilidad de que los 3 sean con leche?}',
    options: ['\\frac{5}{21}', '\\frac{20}{84}', '\\frac{10}{42}', '\\frac{2}{9}'],
    correctAnswer: 0,
    explanation: '\\frac{C(6,3)}{C(9,3)} = \\frac{20}{84} = \\frac{5}{21}',
    difficulty: 'medium',
    difficultyScore: 0.48,
    skills: ['combinatoria-problemas-probabilidad', 'conteo-combinaciones', 'probabilidad-clasica']
  },
  {
    id: 'm2-prob-003-020',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\frac{C(n,r)}{\\text{total}}',
    questionLatex: '\\text{De un mazo de 52 cartas se extraen 5. ¿Cuál es la probabilidad de obtener exactamente 2 ases si hay 4 ases en el mazo?}',
    options: ['\\frac{2{,}162}{54{,}145}', '\\frac{2{,}162}{108{,}290}', '\\frac{1{,}081}{27{,}072}', '\\frac{4{,}324}{108{,}290}'],
    correctAnswer: 0,
    explanation: '\\frac{C(4,2) \\times C(48,3)}{C(52,5)} = \\frac{6 \\times 17{,}296}{2{,}598{,}960} = \\frac{103{,}776}{2{,}598{,}960} = \\frac{2{,}162}{54{,}145}',
    difficulty: 'extreme',
    difficultyScore: 0.78,
    skills: ['combinatoria-problemas-probabilidad', 'conteo-combinaciones', 'probabilidad-clasica']
  }
];
