import { Question } from '../../../types';

/**
 * M2-PROB-001: Cálculo y comparación de medidas de dispersión
 *
 * Subsections:
 * A. Varianza y desviación estándar
 *    Habilidades: estadistica-varianza-desviacion
 * B. Coeficiente de variación
 *    Habilidades: estadistica-coeficiente-variacion
 * C. Comparación de dispersión entre grupos
 *    Habilidades: estadistica-comparacion-dispersion
 * D. Interpretación de medidas de dispersión
 *    Habilidades: estadistica-interpretacion-dispersion
 */

export const m2Prob001Questions: Question[] = [
  {
    id: 'm2-7',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'IQR = Q_3 - Q_1',
    questionLatex: '\\text{Un investigador de mercado analiza los tiempos de espera en minutos de 7 clientes en una tienda, ordenados de menor a mayor: 2, 4, 5, 7, 9, 10, 12. Para medir la dispersión del 50\\% central de los datos, necesita calcular el rango intercuartílico (IQR). ¿Cuál es el valor del rango intercuartílico de estos tiempos de espera?}',
    options: ['4', '5', '6', '7'],
    correctAnswer: 2,
    explanation: 'Q_1 = 4, \\quad Q_3 = 10 \\quad \\Rightarrow \\quad \\text{IQR} = Q_3 - Q_1 = 10 - 4 = 6',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['estadistica-cuartiles', 'estadistica-rango-intercuartilico', 'estadistica-mediana', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-md-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Rango} = \\text{Máx} - \\text{Mín}',
    questionLatex: '\\text{Una nutricionista registra el consumo diario de calorías de 5 pacientes durante una semana. Los valores registrados en miles de calorías son: 10, 10, 15, 20, 30. Para tener una primera medida de la variabilidad en los consumos, la nutricionista necesita calcular el rango de estos datos. ¿Cuál es el rango del consumo calórico de los pacientes?}',
    options: ['10', '15', '20', '25'],
    correctAnswer: 2,
    explanation: '\\text{Rango} = \\text{Máx} - \\text{Mín} = 30 - 10 = 20',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['estadistica-rango', 'estadistica-medidas-dispersion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-md-2',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'DMA = \\frac{\\sum |x_i - \\bar{x}|}{n}',
    questionLatex: '\\text{Un entrenador deportivo registra las edades de 5 atletas de su equipo: 3, 5, 7, 9 y 11 años. La media de las edades es 7 años. El entrenador quiere calcular la desviación media absoluta para entender qué tan dispersas están las edades respecto a la media. ¿Cuál es la desviación media absoluta de las edades de los atletas?}',
    options: ['2', '2.4', '3', '3.2'],
    correctAnswer: 1,
    explanation: '\\text{DMA} = \\frac{|3-7|+|5-7|+|7-7|+|9-7|+|11-7|}{5} = \\frac{12}{5} = 2.4',
    difficulty: 'medium',
    difficultyScore: 0.48,
    skills: ['estadistica-desviacion-media', 'estadistica-medidas-dispersion', 'estadistica-media', 'numeros-valor-absoluto', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-md-3',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Var}(X + c) = \\text{Var}(X)',
    questionLatex: '\\text{Un profesor de estadística explica a sus estudiantes las propiedades de la varianza. Les presenta un conjunto de datos que tiene varianza igual a 5. Luego les pregunta: "Si a cada dato del conjunto le sumamos 3 unidades, ¿cuál será la nueva varianza?" El profesor quiere que los estudiantes apliquen la propiedad de que sumar una constante no afecta la dispersión. ¿Cuál es la nueva varianza después de sumar 3 a cada dato?}',
    options: ['5', '8', '10', '15'],
    correctAnswer: 0,
    explanation: '\\text{Var}(X + c) = \\text{Var}(X) = 5',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['estadistica-varianza', 'estadistica-medidas-dispersion', 'estadistica-propiedades-varianza']
  },
  {
    id: 'm2-prob-md-4',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'Q_1 = \\text{mediana de la mitad inferior}',
    questionLatex: '\\text{Un economista analiza los ingresos mensuales en miles de pesos de 7 familias de un barrio, ordenados de menor a mayor: 4, 8, 10, 15, 18, 22, 25. Para identificar el ingreso que separa al 25\\% más bajo de las familias, necesita calcular el primer cuartil (Q1). ¿Cuál es el valor del primer cuartil de estos ingresos?}',
    options: ['6', '8', '9', '10'],
    correctAnswer: 1,
    explanation: 'Q_1 = \\text{mediana}(\\{4, 8, 10\\}) = 8',
    difficulty: 'medium',
    difficultyScore: 0.35,
    skills: ['estadistica-cuartiles', 'estadistica-mediana', 'estadistica-medidas-posicion', 'numeros-operaciones-basicas']
  },
  // Subsection A: Varianza y desviación estándar
  {
    id: 'm2-prob-var-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Var} = \\frac{\\sum (x_i - \\bar{x})^2}{n}',
    questionLatex: '\\text{Un profesor de química califica los informes de laboratorio de cinco estudiantes de un curso pequeño. Las notas obtenidas fueron 4, 5, 6, 7 y 8 puntos respectivamente. El profesor quiere medir qué tan dispersas están las notas respecto a la media del grupo, que es 6 puntos. Para esto necesita calcular la varianza, que es el promedio de los cuadrados de las desviaciones. ¿Cuál es la varianza de estas notas?}',
    options: ['1', '2', '4', '5'],
    correctAnswer: 1,
    explanation: '\\text{Var} = \\frac{(4-6)^2+(5-6)^2+(6-6)^2+(7-6)^2+(8-6)^2}{5} = \\frac{10}{5} = 2',
    difficulty: 'medium',
    difficultyScore: 0.45,
    skills: ['estadistica-varianza-desviacion', 'estadistica-varianza', 'estadistica-media', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-var-2',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\sigma = \\sqrt{\\text{Var}}',
    questionLatex: '\\text{Un analista de datos está procesando información sobre tiempos de entrega de una empresa de mensajería. Ha calculado que la varianza de los tiempos es igual a 16 minutos cuadrados. Para reportar la dispersión en las mismas unidades que los datos originales, necesita calcular la desviación estándar. ¿Cuál es la desviación estándar de los tiempos de entrega?}',
    options: ['2', '4', '8', '256'],
    correctAnswer: 1,
    explanation: '\\sigma = \\sqrt{\\text{Var}} = \\sqrt{16} = 4',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['estadistica-varianza-desviacion', 'estadistica-desviacion-estandar', 'numeros-raices', 'numeros-operaciones-basicas']
  },
  // Subsection B: Coeficiente de variación
  {
    id: 'm2-prob-cv-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'CV = \\frac{\\sigma}{\\bar{x}}',
    questionLatex: '\\text{Ana revisa su desempeño académico del semestre. En matemáticas, sus notas tienen una media de 60 puntos con una desviación estándar de 12 puntos. En historia, la media es de 50 puntos con una desviación estándar de 8 puntos. Su orientador le explica que para comparar la variabilidad entre asignaturas con medias diferentes, debe usar el coeficiente de variación. ¿En qué asignatura es mayor la variabilidad relativa?}',
    options: ['Matemáticas', 'Historia', 'Iguales', 'No se puede determinar'],
    correctAnswer: 0,
    explanation: 'CV_{\\text{mates}} = \\frac{12}{60} = 0.20 > CV_{\\text{hist}} = \\frac{8}{50} = 0.16',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['estadistica-coeficiente-variacion', 'estadistica-comparacion-dispersion', 'numeros-division', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-cv-2',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'CV = \\frac{\\sigma}{\\bar{x}} \\times 100\\%',
    questionLatex: '\\text{Un investigador de mercado analiza los precios de un producto en diferentes tiendas. Los datos muestran una media de 40 pesos y una desviación estándar de 8 pesos. Para comparar la variabilidad de estos precios con la de otros productos, necesita calcular el coeficiente de variación. ¿Cuál es el coeficiente de variación expresado como porcentaje?}',
    options: ['5%', '10%', '20%', '32%'],
    correctAnswer: 2,
    explanation: 'CV = \\frac{8}{40} \\times 100\\% = 20\\%',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['estadistica-coeficiente-variacion', 'numeros-porcentaje', 'numeros-division', 'numeros-operaciones-basicas']
  },
  // Subsection C: Comparación de dispersión entre grupos
  {
    id: 'm2-prob-comp-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\sigma_B > \\sigma_A \\Rightarrow \\text{B más disperso}',
    questionLatex: '\\text{Un coordinador académico compara los resultados de dos secciones en una prueba estandarizada. El Grupo A obtuvo una media de 70 puntos con desviación estándar de 10 puntos. El Grupo B también obtuvo una media de 70 puntos, pero con desviación estándar de 15 puntos. El coordinador quiere determinar en cuál grupo las notas están más dispersas. ¿Qué grupo presenta mayor dispersión en sus notas?}',
    options: ['Grupo A', 'Grupo B', 'Igual dispersión', 'No se puede determinar'],
    correctAnswer: 1,
    explanation: '\\sigma_B = 15 > \\sigma_A = 10 \\Rightarrow \\text{Grupo B más disperso}',
    difficulty: 'easy',
    difficultyScore: 0.18,
    skills: ['estadistica-comparacion-dispersion', 'estadistica-desviacion-estandar', 'estadistica-interpretacion-dispersion', 'numeros-comparacion']
  },
  {
    id: 'm2-prob-comp-2',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Rango mayor} \\Rightarrow \\text{más dispersión}',
    questionLatex: '\\text{Un consultor de recursos humanos está comparando la estructura salarial de dos empresas. En la empresa X, el rango de salarios (diferencia entre el mayor y menor salario) es de \\$400.000. En la empresa Y, el rango de salarios es de \\$250.000. El consultor quiere determinar qué empresa tiene mayor dispersión en sus salarios. ¿Qué indica la comparación de rangos sobre la dispersión salarial?}',
    options: ['X más dispersa que Y', 'Y más dispersa que X', 'Igual dispersión', 'El rango no mide dispersión'],
    correctAnswer: 0,
    explanation: '\\text{Rango}_X > \\text{Rango}_Y \\Rightarrow \\text{X más dispersa}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['estadistica-comparacion-dispersion', 'estadistica-rango', 'estadistica-interpretacion-dispersion', 'numeros-comparacion']
  },
  // Subsection D: Interpretación de medidas de dispersión
  {
    id: 'm2-prob-int-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\sigma \\approx 0 \\Rightarrow \\text{datos homogéneos}',
    questionLatex: '\\text{Un profesor de estadística presenta a sus estudiantes un conjunto de datos cuya desviación estándar es cercana a cero. Les pide que interpreten qué significa este valor tan pequeño de desviación estándar en términos de la distribución de los datos. ¿Qué se puede concluir sobre los datos?}',
    options: ['Los datos están muy dispersos', 'Los datos son todos iguales o muy similares', 'La media es cero', 'Los datos son negativos'],
    correctAnswer: 1,
    explanation: '\\sigma \\approx 0 \\Rightarrow \\text{datos muy homogéneos}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['estadistica-interpretacion-dispersion', 'estadistica-desviacion-estandar', 'estadistica-analisis-datos']
  },
  {
    id: 'm2-prob-int-2',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\sigma_A < \\sigma_B \\Rightarrow \\text{A más equitativa}',
    questionLatex: '\\text{Un sindicato de trabajadores analiza la equidad salarial en dos empresas del mismo sector. Ambas empresas tienen la misma media salarial de \\$600.000. Sin embargo, la empresa A tiene una desviación estándar de \\$50.000 mientras que la empresa B tiene una desviación estándar de \\$200.000. El sindicato quiere determinar en cuál empresa hay mayor equidad salarial. ¿Qué implica la diferencia de desviaciones estándar sobre la equidad salarial?}',
    options: ['A tiene salarios más equitativos', 'B tiene salarios más equitativos', 'Ambas son igualmente equitativas', 'No se puede determinar'],
    correctAnswer: 0,
    explanation: '\\sigma_A < \\sigma_B \\Rightarrow \\text{A más equitativa}',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['estadistica-interpretacion-dispersion', 'estadistica-desviacion-estandar', 'estadistica-comparacion-dispersion', 'estadistica-aplicaciones-contexto']
  },
  // ========================================
  // NUEVAS PREGUNTAS - SUBSECCIÓN A: VARIANZA Y DESVIACIÓN ESTÁNDAR
  // ========================================
  {
    id: 'm2-prob-001-001',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Var} = \\frac{\\sum (x_i - \\bar{x})^2}{n}',
    questionLatex: '\\text{En una clínica pediátrica, una enfermera registra los pesos de cuatro bebés nacidos el mismo día: el primero pesa 3 kg, el segundo y tercero pesan 4 kg cada uno, y el cuarto pesa 5 kg. El peso promedio de estos bebés es 4 kg. Para evaluar qué tan diferentes son los pesos entre sí, la enfermera debe calcular la varianza de los datos. ¿Cuál es la varianza de los pesos de los bebés?}',
    options: ['0.25 kg²', '0.5 kg²', '0.75 kg²', '1 kg²'],
    correctAnswer: 1,
    explanation: '\\text{Var} = \\frac{(3-4)^2+(4-4)^2+(4-4)^2+(5-4)^2}{4} = \\frac{2}{4} = 0.5',
    difficulty: 'easy',
    difficultyScore: 0.32,
    skills: ['estadistica-varianza-desviacion', 'estadistica-varianza', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-001-002',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\sigma = \\sqrt{\\text{Var}}',
    questionLatex: '\\text{Un ingeniero de control de calidad analiza las mediciones de piezas producidas en una fábrica. Después de calcular la varianza de las medidas, obtiene un valor de 25 milímetros cuadrados. Para reportar la dispersión en las mismas unidades que las mediciones originales (milímetros), necesita calcular la desviación estándar. ¿Cuál es la desviación estándar de las mediciones?}',
    options: ['5 mm', '12.5 mm', '25 mm', '625 mm'],
    correctAnswer: 0,
    explanation: '\\sigma = \\sqrt{25} = 5 \\text{ mm}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['estadistica-varianza-desviacion', 'estadistica-desviacion-estandar', 'numeros-raices']
  },
  {
    id: 'm2-prob-001-003',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Var}(kX) = k^2 \\cdot \\text{Var}(X)',
    questionLatex: '\\text{Una empresa de conversión de moneda registra las transacciones diarias en dólares y calcula que la varianza de los montos es 4 dólares cuadrados. Para convertir todos los registros a pesos chilenos, multiplican cada transacción por 3 (el tipo de cambio simplificado). Un analista necesita determinar cómo afecta esta multiplicación a la varianza. ¿Cuál será la nueva varianza de los montos en pesos?}',
    options: ['4', '12', '36', '144'],
    correctAnswer: 2,
    explanation: '\\text{Var}(3X) = 3^2 \\cdot \\text{Var}(X) = 9 \\cdot 4 = 36',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['estadistica-varianza-desviacion', 'estadistica-propiedades-varianza', 'numeros-potencias']
  },
  {
    id: 'm2-prob-001-004',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Var} = E(X^2) - [E(X)]^2',
    questionLatex: '\\text{Si la media de un conjunto es 5 y la media de los cuadrados es 30, ¿cuál es la varianza?}',
    options: ['5', '10', '15', '25'],
    correctAnswer: 0,
    explanation: '\\text{Var} = E(X^2) - [E(X)]^2 = 30 - 25 = 5',
    difficulty: 'medium',
    difficultyScore: 0.48,
    skills: ['estadistica-varianza-desviacion', 'estadistica-varianza', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-001-005',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\sigma(kX) = |k| \\cdot \\sigma(X)',
    questionLatex: '\\text{La desviación estándar de un conjunto es 6. Si multiplicamos todos los datos por 2, ¿cuál será la nueva desviación estándar?}',
    options: ['3', '6', '12', '36'],
    correctAnswer: 2,
    explanation: '\\sigma(2X) = 2 \\cdot \\sigma(X) = 2 \\cdot 6 = 12',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['estadistica-varianza-desviacion', 'estadistica-propiedades-varianza', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-001-006',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Var} = \\frac{\\sum (x_i - \\bar{x})^2}{n}',
    questionLatex: '\\text{Las temperaturas en °C de 5 días fueron: 18, 20, 22, 20, 20. La media es 20°C. ¿Cuál es la varianza?}',
    options: ['1.6', '2', '2.4', '4'],
    correctAnswer: 0,
    explanation: '\\text{Var} = \\frac{4+0+4+0+0}{5} = \\frac{8}{5} = 1.6',
    difficulty: 'easy',
    difficultyScore: 0.35,
    skills: ['estadistica-varianza-desviacion', 'estadistica-varianza', 'numeros-operaciones-basicas']
  },
  // ========================================
  // NUEVAS PREGUNTAS - SUBSECCIÓN B: COEFICIENTE DE VARIACIÓN
  // ========================================
  {
    id: 'm2-prob-001-007',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'CV = \\frac{\\sigma}{\\bar{x}} \\times 100\\%',
    questionLatex: '\\text{Un grupo tiene media 80 y desviación estándar 16. ¿Cuál es el coeficiente de variación?}',
    options: ['5%', '10%', '20%', '25%'],
    correctAnswer: 2,
    explanation: 'CV = \\frac{16}{80} \\times 100\\% = 20\\%',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['estadistica-coeficiente-variacion', 'numeros-porcentaje', 'numeros-division']
  },
  {
    id: 'm2-prob-001-008',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'CV = \\frac{\\sigma}{\\bar{x}}',
    questionLatex: '\\text{El peso de manzanas tiene media 150g y CV=10\\%. ¿Cuál es la desviación estándar?}',
    options: ['10g', '15g', '20g', '25g'],
    correctAnswer: 1,
    explanation: '\\sigma = CV \\times \\bar{x} = 0.10 \\times 150 = 15',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['estadistica-coeficiente-variacion', 'numeros-porcentaje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-001-009',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'CV \\text{ mayor} \\Rightarrow \\text{más variación relativa}',
    questionLatex: '\\text{Máquina A: CV=8\\%. Máquina B: CV=12\\%. ¿Cuál produce piezas con mayor variabilidad relativa?}',
    options: ['Máquina A', 'Máquina B', 'Iguales', 'Falta información'],
    correctAnswer: 1,
    explanation: 'CV_B = 12\\% > CV_A = 8\\% \\Rightarrow \\text{B más variable}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['estadistica-coeficiente-variacion', 'estadistica-comparacion-dispersion', 'numeros-comparacion']
  },
  {
    id: 'm2-prob-001-010',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'CV = \\frac{\\sigma}{\\bar{x}} \\times 100\\%',
    questionLatex: '\\text{Producto A: media \\$5000, σ=\\$500. Producto B: media \\$100, σ=\\$20. ¿Cuál tiene mayor variabilidad relativa?}',
    options: ['Producto A', 'Producto B', 'Iguales', 'No se puede comparar'],
    correctAnswer: 1,
    explanation: 'CV_A = \\frac{500}{5000} = 10\\%, \\quad CV_B = \\frac{20}{100} = 20\\% \\Rightarrow \\text{B más variable}',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['estadistica-coeficiente-variacion', 'estadistica-comparacion-dispersion', 'numeros-division']
  },
  {
    id: 'm2-prob-001-011',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'CV \\text{ adimensional}',
    questionLatex: '\\text{¿Cuál es la principal ventaja del coeficiente de variación sobre la desviación estándar?}',
    options: ['Es siempre menor', 'Permite comparar variables con diferentes unidades', 'Es más fácil de calcular', 'Siempre es un número entero'],
    correctAnswer: 1,
    explanation: '\\text{El CV es adimensional, permitiendo comparar variables con distintas escalas o unidades}',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['estadistica-coeficiente-variacion', 'estadistica-conceptos']
  },
  {
    id: 'm2-prob-001-012',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'CV = \\frac{\\sigma}{\\bar{x}} \\times 100\\%',
    questionLatex: '\\text{Altura de hombres: media 175cm, σ=7cm. Altura de niños: media 110cm, σ=7cm. ¿Cuál grupo tiene mayor variabilidad relativa?}',
    options: ['Hombres', 'Niños', 'Iguales (misma σ)', 'No se puede determinar'],
    correctAnswer: 1,
    explanation: 'CV_{\\text{hombres}} = \\frac{7}{175} = 4\\%, \\quad CV_{\\text{niños}} = \\frac{7}{110} = 6.4\\% \\Rightarrow \\text{Niños mayor CV}',
    difficulty: 'medium',
    difficultyScore: 0.45,
    skills: ['estadistica-coeficiente-variacion', 'estadistica-comparacion-dispersion', 'numeros-division']
  },
  // ========================================
  // NUEVAS PREGUNTAS - SUBSECCIÓN C: COMPARACIÓN DE DISPERSIÓN ENTRE GRUPOS
  // ========================================
  {
    id: 'm2-prob-001-013',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'IQR_A < IQR_B \\Rightarrow \\text{A menos disperso}',
    questionLatex: '\\text{Grupo X tiene IQR=12 puntos. Grupo Y tiene IQR=8 puntos. ¿Cuál tiene menor dispersión en el 50\\% central?}',
    options: ['Grupo X', 'Grupo Y', 'Iguales', 'Falta información'],
    correctAnswer: 1,
    explanation: 'IQR_Y = 8 < IQR_X = 12 \\Rightarrow \\text{Y menor dispersión central}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['estadistica-comparacion-dispersion', 'estadistica-rango-intercuartilico', 'numeros-comparacion']
  },
  {
    id: 'm2-prob-001-014',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Comparar } \\sigma \\text{ con misma media}',
    questionLatex: '\\text{Sección A: media=75, σ=5. Sección B: media=75, σ=15. ¿Qué sección tiene notas más homogéneas?}',
    options: ['Sección A', 'Sección B', 'Iguales', 'No se puede saber'],
    correctAnswer: 0,
    explanation: '\\sigma_A = 5 < \\sigma_B = 15 \\Rightarrow \\text{A más homogéneo}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['estadistica-comparacion-dispersion', 'estadistica-desviacion-estandar', 'numeros-comparacion']
  },
  {
    id: 'm2-prob-001-015',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Usar CV para diferentes medias}',
    questionLatex: '\\text{Ciudad A: ingreso medio \\$800.000, σ=\\$160.000. Ciudad B: ingreso medio \\$400.000, σ=\\$100.000. ¿Cuál tiene distribución más desigual?}',
    options: ['Ciudad A', 'Ciudad B', 'Iguales', 'Falta información'],
    correctAnswer: 1,
    explanation: 'CV_A = \\frac{160}{800} = 20\\%, \\quad CV_B = \\frac{100}{400} = 25\\% \\Rightarrow \\text{B más desigual}',
    difficulty: 'medium',
    difficultyScore: 0.45,
    skills: ['estadistica-comparacion-dispersion', 'estadistica-coeficiente-variacion', 'numeros-division']
  },
  {
    id: 'm2-prob-001-016',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Varianza mayor} \\Rightarrow \\text{más disperso}',
    questionLatex: '\\text{Datos de temperatura: Var(ciudad A)=9, Var(ciudad B)=16. ¿Cuál tiene temperaturas más variables?}',
    options: ['Ciudad A', 'Ciudad B', 'Iguales', 'Falta información'],
    correctAnswer: 1,
    explanation: '\\text{Var}_B = 16 > \\text{Var}_A = 9 \\Rightarrow \\text{B más variable}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['estadistica-comparacion-dispersion', 'estadistica-varianza', 'numeros-comparacion']
  },
  {
    id: 'm2-prob-001-017',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Múltiples medidas de dispersión}',
    questionLatex: '\\text{Equipo A: Rango=20, IQR=8, σ=4. Equipo B: Rango=15, IQR=10, σ=5. ¿Qué equipo tiene rendimiento más consistente?}',
    options: ['Equipo A (menor σ)', 'Equipo B (menor rango)', 'Depende de la medida usada', 'Son iguales'],
    correctAnswer: 2,
    explanation: '\\text{A tiene menor σ pero B tiene menor rango; la respuesta depende de qué medida se priorice}',
    difficulty: 'hard',
    difficultyScore: 0.55,
    skills: ['estadistica-comparacion-dispersion', 'estadistica-medidas-dispersion', 'estadistica-analisis-critico']
  },
  {
    id: 'm2-prob-001-018',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Efecto de outliers en dispersión}',
    questionLatex: '\\text{Un grupo tiene σ=10. Se descubre un dato atípico extremo. Si se elimina, ¿qué ocurrirá probablemente con la desviación estándar?}',
    options: ['Aumentará', 'Disminuirá', 'Permanecerá igual', 'Se hará cero'],
    correctAnswer: 1,
    explanation: '\\text{Eliminar outliers generalmente reduce la dispersión (σ disminuye)}',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['estadistica-comparacion-dispersion', 'estadistica-outliers', 'estadistica-desviacion-estandar']
  },
  // ========================================
  // NUEVAS PREGUNTAS - SUBSECCIÓN D: INTERPRETACIÓN DE MEDIDAS DE DISPERSIÓN
  // ========================================
  {
    id: 'm2-prob-001-019',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\sigma \\text{ grande} \\Rightarrow \\text{datos dispersos}',
    questionLatex: '\\text{En control de calidad, ¿qué indica una desviación estándar muy alta en las mediciones de un producto?}',
    options: ['Producción muy consistente', 'Producción muy variable', 'Media muy alta', 'Pocos productos fabricados'],
    correctAnswer: 1,
    explanation: '\\sigma \\text{ alta} \\Rightarrow \\text{alta variabilidad en el proceso productivo}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['estadistica-interpretacion-dispersion', 'estadistica-aplicaciones-contexto', 'estadistica-desviacion-estandar']
  },
  {
    id: 'm2-prob-001-020',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'CV < 15\\% \\Rightarrow \\text{baja variabilidad}',
    questionLatex: '\\text{Un proceso tiene CV=5\\%. En términos de control de calidad, esto indica:}',
    options: ['Alta variabilidad - proceso deficiente', 'Baja variabilidad - proceso consistente', 'Variabilidad media', 'No se puede interpretar sin la media'],
    correctAnswer: 1,
    explanation: 'CV = 5\\% < 15\\% \\Rightarrow \\text{baja variabilidad relativa, proceso muy consistente}',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['estadistica-interpretacion-dispersion', 'estadistica-coeficiente-variacion', 'estadistica-aplicaciones-contexto']
  },
  {
    id: 'm2-prob-001-021',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{IQR resistente a outliers}',
    questionLatex: '\\text{¿Por qué el rango intercuartílico (IQR) es preferible al rango cuando hay valores atípicos?}',
    options: ['IQR es siempre mayor', 'IQR no se afecta por valores extremos', 'IQR es más fácil de calcular', 'IQR siempre es positivo'],
    correctAnswer: 1,
    explanation: '\\text{IQR usa solo el 50\\% central, ignorando valores extremos (outliers)}',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['estadistica-interpretacion-dispersion', 'estadistica-rango-intercuartilico', 'estadistica-conceptos']
  },
  {
    id: 'm2-prob-001-022',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Unidades de } \\sigma \\text{ vs Var}',
    questionLatex: '\\text{Si medimos pesos en kg, la varianza se expresa en kg² pero la desviación estándar en kg. ¿Por qué se prefiere reportar σ?}',
    options: ['σ es siempre menor', 'σ tiene las mismas unidades que los datos', 'σ es más preciso', 'La varianza no existe en kg'],
    correctAnswer: 1,
    explanation: '\\sigma = \\sqrt{\\text{Var}} \\text{ tiene las mismas unidades que los datos originales, facilitando la interpretación}',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['estadistica-interpretacion-dispersion', 'estadistica-varianza-desviacion', 'estadistica-conceptos']
  },
  {
    id: 'm2-prob-001-023',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\bar{x} \\pm \\sigma',
    questionLatex: '\\text{Notas: media=70, σ=10. Si la distribución es aproximadamente simétrica, ¿qué porcentaje de alumnos tiene nota entre 60 y 80?}',
    options: ['Aproximadamente 50%', 'Aproximadamente 68%', 'Aproximadamente 95%', 'Exactamente 100%'],
    correctAnswer: 1,
    explanation: '\\text{En distribuciones simétricas, } \\bar{x} \\pm \\sigma \\text{ contiene aproximadamente 68\\% de los datos}',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['estadistica-interpretacion-dispersion', 'estadistica-desviacion-estandar', 'estadistica-distribucion-normal']
  },
  {
    id: 'm2-prob-001-024',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Dispersión y predicción}',
    questionLatex: '\\text{Un economista tiene dos modelos: Modelo A (σ=5\\%) y Modelo B (σ=15\\%). ¿Cuál permite predicciones más confiables?}',
    options: ['Modelo A', 'Modelo B', 'Ambos son igual de confiables', 'Depende del valor de la media'],
    correctAnswer: 0,
    explanation: '\\sigma_A < \\sigma_B \\Rightarrow \\text{A tiene menor variabilidad, predicciones más estables}',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['estadistica-interpretacion-dispersion', 'estadistica-aplicaciones-contexto', 'estadistica-desviacion-estandar']
  },
  {
    id: 'm2-prob-001-025',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Var} = \\frac{\\sum (x_i - \\bar{x})^2}{n}',
    questionLatex: '\\text{Un conjunto de datos: 2, 4, 4, 4, 6 tiene media 4. Calcula la varianza.}',
    options: ['1.2', '1.6', '2', '2.4'],
    correctAnswer: 1,
    explanation: '\\text{Var} = \\frac{(2-4)^2+0+0+0+(6-4)^2}{5} = \\frac{4+0+0+0+4}{5} = \\frac{8}{5} = 1.6',
    difficulty: 'easy',
    difficultyScore: 0.32,
    skills: ['estadistica-varianza-desviacion', 'estadistica-varianza', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-001-026',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'CV = \\frac{\\sigma}{\\bar{x}} \\times 100\\%',
    questionLatex: '\\text{Datos de ventas: media=200 unidades, σ=30 unidades. ¿Cuál es el coeficiente de variación?}',
    options: ['10%', '15%', '20%', '25%'],
    correctAnswer: 1,
    explanation: 'CV = \\frac{30}{200} \\times 100\\% = 15\\%',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['estadistica-coeficiente-variacion', 'numeros-porcentaje', 'numeros-division']
  }
];
