import { Question } from '../../../types';

/**
 * M2-PROB-004: Problemas que involucren el modelo binomial y otros modelos probabilísticos
 *
 * Total questions: 40 (23 original + 17 new)
 *
 * Subsections:
 * A. Distribución binomial
 *    Habilidades: probabilidad-distribucion-binomial
 * B. Cálculo de probabilidades binomiales
 *    Habilidades: probabilidad-calculo-binomial
 * C. Otros modelos probabilísticos
 *    Habilidades: probabilidad-otros-modelos
 * D. Aplicaciones de modelos probabilísticos
 *    Habilidades: probabilidad-modelos-aplicaciones
 */

export const m2Prob004Questions: Question[] = [
  {
    id: 'm2-prob-bin-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X=k) = C(n,k) \\times p^k \\times (1-p)^{n-k}',
    questionLatex: '\\text{En un experimento de probabilidad, una estudiante de estadística lanza una moneda equilibrada 3 veces consecutivas para estudiar la distribución binomial. Cada lanzamiento es independiente y la probabilidad de obtener cara en cada lanzamiento es } \\frac{1}{2}\\text{. La estudiante quiere calcular la probabilidad de obtener exactamente 2 caras en los 3 lanzamientos. ¿Cuál es esta probabilidad?}',
    options: ['\\frac{1}{8}', '\\frac{3}{8}', '\\frac{1}{2}', '\\frac{5}{8}'],
    correctAnswer: 1,
    explanation: 'P = C(3,2) \\times \\left(\\frac{1}{2}\\right)^2 \\times \\left(\\frac{1}{2}\\right)^1 = 3 \\times \\frac{1}{8} = \\frac{3}{8}',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-calculo-binomial', 'probabilidad-combinaciones', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-bin-2',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X=1) = C(4,1) \\times \\left(\\frac{1}{6}\\right)^1 \\times \\left(\\frac{5}{6}\\right)^3',
    questionLatex: '\\text{Un profesor de matemáticas realiza un experimento en clase lanzando un dado equilibrado 4 veces consecutivas. Quiere demostrar a sus estudiantes cómo calcular la probabilidad de obtener exactamente un resultado específico usando la distribución binomial. Si el "éxito" se define como obtener un 6, y la probabilidad de éxito en cada lanzamiento es } \\frac{1}{6}\\text{, ¿cuál es la probabilidad de obtener exactamente un 6 en los 4 lanzamientos?}',
    options: ['\\frac{120}{324}', '\\frac{200}{648}', '\\frac{500}{1296}', '\\frac{625}{1296}'],
    correctAnswer: 2,
    explanation: 'P = C(4,1) \\times \\left(\\frac{1}{6}\\right)^1 \\times \\left(\\frac{5}{6}\\right)^3 = 4 \\times \\frac{125}{1296} = \\frac{500}{1296}',
    difficulty: 'medium',
    difficultyScore: 0.48,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-calculo-binomial', 'probabilidad-combinaciones', 'numeros-fracciones', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-bin-3',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X=3) = C(5,3) \\times \\left(\\frac{1}{4}\\right)^3 \\times \\left(\\frac{3}{4}\\right)^2',
    questionLatex: '\\text{Un estudiante rinde una prueba de selección múltiple que consta de 5 preguntas, donde cada pregunta tiene 4 alternativas y solo una es correcta. El estudiante no estudió y decide responder todas las preguntas al azar. Usando la distribución binomial, donde la probabilidad de acertar cada pregunta adivinando es } \\frac{1}{4}\\text{, ¿cuál es la probabilidad de que el estudiante acierte exactamente 3 de las 5 preguntas?}',
    options: ['\\frac{40}{512}', '\\frac{90}{1024}', '\\frac{135}{1024}', '\\frac{270}{1024}'],
    correctAnswer: 1,
    explanation: 'P = C(5,3) \\times \\left(\\frac{1}{4}\\right)^3 \\times \\left(\\frac{3}{4}\\right)^2 = 10 \\times \\frac{9}{1024} = \\frac{90}{1024}',
    difficulty: 'hard',
    difficultyScore: 0.55,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-calculo-binomial', 'probabilidad-combinaciones', 'numeros-fracciones', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-bin-4',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X=4) = C(5,4) \\times (0.8)^4 \\times (0.2)^1',
    questionLatex: '\\text{Una máquina de control de calidad en una fábrica tiene una precisión del 80\\% para detectar productos defectuosos. El supervisor de calidad selecciona aleatoriamente 5 productos defectuosos conocidos para evaluar el rendimiento de la máquina. Usando la distribución binomial con probabilidad de éxito } p = 0.8\\text{, ¿cuál es la probabilidad de que la máquina detecte correctamente exactamente 4 de los 5 productos defectuosos?}',
    options: ['0.2048', '0.4096', '0.6', '0.8192'],
    correctAnswer: 1,
    explanation: 'P = C(5,4) \\times (0.8)^4 \\times (0.2)^1 = 5 \\times 0.4096 \\times 0.2 = 0.4096',
    difficulty: 'medium',
    difficultyScore: 0.48,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-calculo-binomial', 'probabilidad-modelos-aplicaciones', 'probabilidad-combinaciones', 'numeros-decimales', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-bin-5',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X \\geq 8) = P(X=8) + P(X=9) + P(X=10)',
    questionLatex: '\\text{Un jugador de básquetbol tiene un 50\\% de efectividad en tiros libres. Durante una práctica, realiza 10 lanzamientos consecutivos. El entrenador quiere saber la probabilidad de que el jugador enceste al menos 8 de los 10 tiros. Usando la distribución binomial con } p = \\frac{1}{2}\\text{, ¿cuál es la probabilidad de obtener al menos 8 aciertos en los 10 lanzamientos?}',
    options: ['\\frac{5}{128}', '\\frac{11}{256}', '\\frac{7}{512}', '\\frac{56}{1024}'],
    correctAnswer: 3,
    explanation: 'P = \\frac{C(10,8) + C(10,9) + C(10,10)}{2^{10}} = \\frac{45 + 10 + 1}{1024} = \\frac{56}{1024}',
    difficulty: 'hard',
    difficultyScore: 0.58,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-calculo-binomial', 'probabilidad-combinaciones', 'numeros-fracciones', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-bin-6',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X=0) = (1-p)^n = (0.95)^3',
    questionLatex: '\\text{Una tienda de electrónica recibe un lote de 100 artículos de un proveedor. Históricamente, se sabe que el 5\\% de los artículos de este proveedor vienen defectuosos. Un cliente compra 3 artículos seleccionados al azar del lote. Usando la distribución binomial (asumiendo que la probabilidad se mantiene aproximadamente constante), ¿cuál es la probabilidad de que ninguno de los 3 artículos esté defectuoso?}',
    options: ['0.857', '0.902', '0.815', '0.950'],
    correctAnswer: 0,
    explanation: 'P(0 \\text{ defectuosos}) = (0.95)^3 \\approx 0.857',
    difficulty: 'medium',
    difficultyScore: 0.35,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-calculo-binomial', 'probabilidad-modelos-aplicaciones', 'numeros-decimales', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  // Subsection C: Otros modelos probabilísticos
  {
    id: 'm2-prob-unif-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(\\text{múltiplo de 5}) = \\frac{\\text{casos favorables}}{\\text{casos totales}}',
    questionLatex: '\\text{En un sorteo de una rifa escolar, se colocan 100 boletas numeradas del 1 al 100 en una urna. Cada boleta tiene la misma probabilidad de ser seleccionada (distribución uniforme discreta). Un estudiante compró todas las boletas que son múltiplos de 5. Si se extrae una boleta al azar, ¿cuál es la probabilidad de que el estudiante gane el sorteo?}',
    options: ['\\frac{1}{5}', '\\frac{1}{4}', '\\frac{1}{10}', '\\frac{3}{20}'],
    correctAnswer: 0,
    explanation: 'P = \\frac{20}{100} = \\frac{1}{5} \\text{ (distribución uniforme discreta)}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['probabilidad-otros-modelos', 'probabilidad-uniforme', 'numeros-multiplos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-geom-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X=k) = (1-p)^{k-1} \\times p',
    questionLatex: '\\text{Un jugador de un juego de mesa necesita obtener un 6 en un dado para comenzar a jugar. El jugador lanza el dado repetidamente hasta obtener el primer 6. Usando la distribución geométrica, donde cada lanzamiento es independiente y la probabilidad de éxito es } \\frac{1}{6}\\text{, ¿cuál es la probabilidad de que el jugador obtenga su primer 6 exactamente en el tercer intento?}',
    options: ['\\frac{1}{6}', '\\frac{25}{216}', '\\frac{5}{36}', '\\frac{1}{36}'],
    correctAnswer: 1,
    explanation: 'P = \\left(\\frac{5}{6}\\right)^2 \\times \\frac{1}{6} = \\frac{25}{216}',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['probabilidad-otros-modelos', 'probabilidad-geometrica', 'numeros-fracciones', 'numeros-potencias']
  },
  {
    id: 'm2-prob-poisson-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X=k) = \\frac{\\lambda^k e^{-\\lambda}}{k!}',
    questionLatex: '\\text{Una cafetería registra que en promedio llegan 3 clientes por hora durante las mañanas. El gerente quiere usar la distribución de Poisson para modelar las llegadas de clientes. Si } \\lambda = 3 \\text{ representa el promedio de clientes por hora y la fórmula de Poisson es } P(k) = \\frac{\\lambda^k e^{-\\lambda}}{k!}\\text{, ¿cuál es la probabilidad de que no llegue ningún cliente durante una hora específica?}',
    options: ['e^{-3} \\approx 0.05', '\\frac{1}{3}', '0', '1'],
    correctAnswer: 0,
    explanation: 'P(0) = \\frac{3^0 e^{-3}}{0!} = e^{-3} \\approx 0.05',
    difficulty: 'medium',
    difficultyScore: 0.45,
    skills: ['probabilidad-otros-modelos', 'probabilidad-poisson', 'numeros-potencias', 'numeros-factorial']
  },
  {
    id: 'm2-prob-modelo-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Binomial: n fijo; Geométrica: hasta primer éxito}',
    questionLatex: '\\text{Un profesor de estadística explica a sus estudiantes las diferencias entre los modelos probabilísticos. Presenta dos situaciones: (1) contar cuántos éxitos hay en exactamente 10 intentos, y (2) contar cuántos intentos se necesitan hasta obtener el primer éxito. Los estudiantes deben identificar qué distribución usar en cada caso. ¿Cuál es la diferencia fundamental entre usar la distribución binomial y la distribución geométrica?}',
    options: ['\\text{Binomial: n fijo; Geométrica: hasta éxito}', '\\text{Son iguales}', '\\text{Binomial: sin rep.; Geométrica: con rep.}', '\\text{Depende de n}'],
    correctAnswer: 0,
    explanation: '\\text{Binomial: } P(X=k) \\text{ en } n \\text{ ensayos}; \\quad \\text{Geométrica: ensayos hasta éxito}',
    difficulty: 'easy',
    difficultyScore: 0.18,
    skills: ['probabilidad-otros-modelos', 'probabilidad-conceptos', 'probabilidad-distribucion-binomial']
  },
  // Esperanza (Expected Value) E[X] = n·p
  {
    id: 'm2-prob-bin-esp-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'E[X] = n \\cdot p',
    questionLatex: '\\text{Si lanzas una moneda equilibrada 100 veces, ¿cuántas caras esperas obtener en promedio?}',
    options: ['25', '50', '75', '100'],
    correctAnswer: 1,
    explanation: 'E[X] = n \\cdot p = 100 \\times 0{,}5 = 50',
    difficulty: 'easy',
    difficultyScore: 0.18,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-esperanza', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-bin-esp-2',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'E[X] = n \\cdot p',
    questionLatex: '\\text{En una prueba de 20 preguntas de verdadero/falso, un estudiante responde al azar. ¿Cuántas preguntas se espera que acierte en promedio?}',
    options: ['5', '8', '10', '15'],
    correctAnswer: 2,
    explanation: 'E[X] = n \\cdot p = 20 \\times 0{,}5 = 10',
    difficulty: 'easy',
    difficultyScore: 0.18,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-esperanza', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-bin-esp-3',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'E[X] = n \\cdot p',
    questionLatex: '\\text{Un arquero tiene 70\\% de efectividad. Si realiza 50 lanzamientos, ¿cuántos goles se esperan en promedio?}',
    options: ['25', '30', '35', '40'],
    correctAnswer: 2,
    explanation: 'E[X] = n \\cdot p = 50 \\times 0{,}7 = 35',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-esperanza', 'numeros-porcentaje', 'numeros-operaciones-basicas']
  },
  // Varianza y Desviación Estándar Var(X) = n·p·(1-p)
  {
    id: 'm2-prob-bin-var-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'Var(X) = n \\cdot p \\cdot (1-p)',
    questionLatex: '\\text{En un experimento binomial con } n = 100 \\text{ ensayos y } p = 0{,}5\\text{, ¿cuál es la varianza del número de éxitos?}',
    options: ['25', '50', '100', '12{,}5'],
    correctAnswer: 0,
    explanation: 'Var(X) = n \\cdot p \\cdot (1-p) = 100 \\times 0{,}5 \\times 0{,}5 = 25',
    difficulty: 'medium',
    difficultyScore: 0.32,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-varianza', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-prob-bin-var-2',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\sigma = \\sqrt{n \\cdot p \\cdot (1-p)}',
    questionLatex: '\\text{Si la varianza del número de éxitos en un experimento binomial es 25, ¿cuál es la desviación estándar?}',
    options: ['5', '12{,}5', '25', '625'],
    correctAnswer: 0,
    explanation: '\\sigma = \\sqrt{Var(X)} = \\sqrt{25} = 5',
    difficulty: 'easy',
    difficultyScore: 0.18,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-desviacion-estandar', 'numeros-raices']
  },
  {
    id: 'm2-prob-bin-var-3',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\sigma = \\sqrt{n \\cdot p \\cdot (1-p)}',
    questionLatex: '\\text{En 400 lanzamientos de una moneda, ¿cuál es la desviación estándar del número de caras?}',
    options: ['5', '10', '20', '100'],
    correctAnswer: 1,
    explanation: '\\sigma = \\sqrt{400 \\times 0{,}5 \\times 0{,}5} = \\sqrt{100} = 10',
    difficulty: 'medium',
    difficultyScore: 0.35,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-desviacion-estandar', 'numeros-raices', 'numeros-operaciones-basicas']
  },
  // Probabilidades "al menos" / "a lo más" (at-least / at-most)
  {
    id: 'm2-prob-bin-atleast-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X \\geq 1) = 1 - P(X = 0)',
    questionLatex: '\\text{Un dado se lanza 3 veces. ¿Cuál es la probabilidad de obtener al menos un 6?}',
    options: ['\\frac{1}{6}', '\\frac{91}{216}', '\\frac{125}{216}', '\\frac{1}{2}'],
    correctAnswer: 1,
    explanation: 'P(X \\geq 1) = 1 - P(X=0) = 1 - \\left(\\frac{5}{6}\\right)^3 = 1 - \\frac{125}{216} = \\frac{91}{216}',
    difficulty: 'medium',
    difficultyScore: 0.45,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-complemento', 'numeros-fracciones', 'numeros-potencias']
  },
  {
    id: 'm2-prob-bin-atleast-2',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X \\geq 2) = 1 - P(X=0) - P(X=1)',
    questionLatex: '\\text{Una moneda se lanza 4 veces. ¿Cuál es la probabilidad de obtener al menos 2 caras?}',
    options: ['\\frac{5}{16}', '\\frac{6}{16}', '\\frac{11}{16}', '\\frac{15}{16}'],
    correctAnswer: 2,
    explanation: 'P(X \\geq 2) = 1 - P(X=0) - P(X=1) = 1 - \\frac{1}{16} - \\frac{4}{16} = \\frac{11}{16}',
    difficulty: 'hard',
    difficultyScore: 0.52,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-complemento', 'probabilidad-combinaciones', 'numeros-fracciones']
  },
  {
    id: 'm2-prob-bin-atmost-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X \\leq 1) = P(X=0) + P(X=1)',
    questionLatex: '\\text{Se lanza un dado 3 veces. ¿Cuál es la probabilidad de obtener a lo más un 6?}',
    options: ['\\frac{25}{216}', '\\frac{75}{216}', '\\frac{125}{216}', '\\frac{200}{216}'],
    correctAnswer: 3,
    explanation: 'P(X \\leq 1) = P(X=0) + P(X=1) = \\frac{125}{216} + 3 \\times \\frac{1}{6} \\times \\frac{25}{36} = \\frac{125 + 75}{216} = \\frac{200}{216}',
    difficulty: 'hard',
    difficultyScore: 0.52,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-calculo-binomial', 'numeros-fracciones', 'numeros-potencias']
  },
  // Control de calidad / Quality control
  {
    id: 'm2-prob-bin-qc-1',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X=0) = (1-p)^n',
    questionLatex: '\\text{Una fábrica produce artículos con 5\\% de defectos. Si se inspeccionan 10 artículos al azar, ¿cuál es la probabilidad de no encontrar ningún defectuoso? (Usa } (0{,}95)^{10} \\approx 0{,}599)',
    options: ['0{,}349', '0{,}500', '0{,}599', '0{,}950'],
    correctAnswer: 2,
    explanation: 'P(X=0) = (0{,}95)^{10} \\approx 0{,}599',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-modelos-aplicaciones', 'numeros-potencias', 'numeros-decimales']
  },
  {
    id: 'm2-prob-bin-qc-2',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X \\geq 1) = 1 - P(X=0)',
    questionLatex: '\\text{Un lote tiene 10\\% de productos defectuosos. Si se revisan 5 productos, ¿cuál es la probabilidad de encontrar al menos uno defectuoso? (Usa } (0{,}9)^5 \\approx 0{,}59)',
    options: ['0{,}10', '0{,}41', '0{,}50', '0{,}59'],
    correctAnswer: 1,
    explanation: 'P(X \\geq 1) = 1 - P(X=0) = 1 - (0{,}9)^5 \\approx 1 - 0{,}59 = 0{,}41',
    difficulty: 'medium',
    difficultyScore: 0.32,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-complemento', 'probabilidad-modelos-aplicaciones', 'numeros-potencias']
  },
  {
    id: 'm2-prob-bin-qc-3',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{En un proceso de manufactura, el 2\\% de los productos son defectuosos. Si se toma una muestra de 100 productos, ¿cuántos defectuosos se esperan encontrar?}',
    options: ['1', '2', '5', '10'],
    correctAnswer: 1,
    explanation: 'E[X] = n \\cdot p = 100 \\times 0{,}02 = 2',
    difficulty: 'easy',
    difficultyScore: 0.18,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-esperanza', 'probabilidad-modelos-aplicaciones', 'numeros-porcentaje']
  },
  // ==================== NEW QUESTIONS (17) ====================
  // Subsection A: Distribución binomial (+4)
  {
    id: 'm2-prob-004-001',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X=k) = C(n,k) \\cdot p^k \\cdot (1-p)^{n-k}',
    questionLatex: '\\text{Una bolsa contiene 60\\% de caramelos rojos. Si se extraen 5 caramelos con reposición, ¿cuál es la probabilidad de obtener exactamente 3 rojos?}',
    options: ['0.2304', '0.3456', '0.3110', '0.2592'],
    correctAnswer: 1,
    explanation: 'P(3) = C(5,3) \\times (0.6)^3 \\times (0.4)^2 = 10 \\times 0.216 \\times 0.16 = 0.3456',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-calculo-binomial', 'numeros-decimales']
  },
  {
    id: 'm2-prob-004-002',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X=n) = p^n',
    questionLatex: '\\text{Un tirador tiene 80\\% de efectividad. ¿Cuál es la probabilidad de acertar 4 tiros consecutivos?}',
    options: ['0.32', '0.4096', '0.512', '0.64'],
    correctAnswer: 1,
    explanation: 'P(4) = (0.8)^4 = 0.4096',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['probabilidad-distribucion-binomial', 'numeros-potencias', 'numeros-decimales']
  },
  {
    id: 'm2-prob-004-003',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X=2) = C(6,2) \\cdot p^2 \\cdot (1-p)^4',
    questionLatex: '\\text{En una encuesta, el 30\\% de las personas prefiere el producto A. Si se entrevistan 6 personas al azar, ¿cuál es la probabilidad de que exactamente 2 prefieran el producto A?}',
    options: ['0.1852', '0.3241', '0.2646', '0.3087'],
    correctAnswer: 1,
    explanation: 'P(2) = C(6,2) \\times (0.3)^2 \\times (0.7)^4 = 15 \\times 0.09 \\times 0.2401 \\approx 0.3241',
    difficulty: 'medium',
    difficultyScore: 0.45,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-calculo-binomial', 'numeros-decimales']
  },
  {
    id: 'm2-prob-004-004',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'C(n,k)',
    questionLatex: '\\text{En la fórmula binomial } P(X=k) = C(n,k) \\cdot p^k \\cdot (1-p)^{n-k}\\text{, ¿qué representa } C(n,k)\\text{?}',
    options: ['\\text{Número de formas de elegir k éxitos de n ensayos}', '\\text{La probabilidad de éxito}', '\\text{El número total de ensayos}', '\\text{La probabilidad de fracaso}'],
    correctAnswer: 0,
    explanation: 'C(n,k) = \\frac{n!}{k!(n-k)!} \\text{ representa las combinaciones de n en k}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['probabilidad-distribucion-binomial', 'probabilidad-conceptos', 'conteo-combinaciones']
  },
  // Subsection B: Cálculo de probabilidades binomiales (+4)
  {
    id: 'm2-prob-004-005',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X \\leq 2) = P(0) + P(1) + P(2)',
    questionLatex: '\\text{Una moneda se lanza 5 veces. ¿Cuál es la probabilidad de obtener a lo más 2 caras?}',
    options: ['\\frac{8}{32}', '\\frac{16}{32}', '\\frac{26}{32}', '\\frac{10}{32}'],
    correctAnswer: 1,
    explanation: 'P(X \\leq 2) = \\frac{C(5,0)+C(5,1)+C(5,2)}{32} = \\frac{1+5+10}{32} = \\frac{16}{32}',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['probabilidad-calculo-binomial', 'probabilidad-combinaciones', 'numeros-fracciones']
  },
  {
    id: 'm2-prob-004-006',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(2 \\leq X \\leq 4)',
    questionLatex: '\\text{Se lanza una moneda 6 veces. ¿Cuál es la probabilidad de obtener entre 2 y 4 caras (inclusive)?}',
    options: ['\\frac{35}{64}', '\\frac{50}{64}', '\\frac{45}{64}', '\\frac{57}{64}'],
    correctAnswer: 1,
    explanation: 'P(2 \\leq X \\leq 4) = \\frac{C(6,2)+C(6,3)+C(6,4)}{64} = \\frac{15+20+15}{64} = \\frac{50}{64}',
    difficulty: 'hard',
    difficultyScore: 0.55,
    skills: ['probabilidad-calculo-binomial', 'probabilidad-combinaciones', 'numeros-fracciones']
  },
  {
    id: 'm2-prob-004-007',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X > 3) = 1 - P(X \\leq 3)',
    questionLatex: '\\text{Un dado se lanza 5 veces. ¿Cuál es la probabilidad de obtener más de 3 veces el número 6?}',
    options: ['\\frac{5}{7776}', '\\frac{6}{7776}', '\\frac{11}{7776}', '\\frac{26}{7776}'],
    correctAnswer: 1,
    explanation: 'P(X > 3) = P(4) + P(5) = C(5,4)(\\frac{1}{6})^4(\\frac{5}{6}) + (\\frac{1}{6})^5 = \\frac{5+1}{7776} = \\frac{6}{7776}',
    difficulty: 'hard',
    difficultyScore: 0.62,
    skills: ['probabilidad-calculo-binomial', 'probabilidad-combinaciones', 'numeros-fracciones']
  },
  {
    id: 'm2-prob-004-008',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X=0) + P(X=n) = (1-p)^n + p^n',
    questionLatex: '\\text{Una moneda equilibrada se lanza 4 veces. ¿Cuál es la probabilidad de obtener todos los resultados iguales (todas caras o todas sellos)?}',
    options: ['\\frac{1}{16}', '\\frac{2}{16}', '\\frac{4}{16}', '\\frac{8}{16}'],
    correctAnswer: 1,
    explanation: 'P(\\text{iguales}) = P(0) + P(4) = \\frac{1}{16} + \\frac{1}{16} = \\frac{2}{16}',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['probabilidad-calculo-binomial', 'probabilidad-clasica', 'numeros-fracciones']
  },
  // Subsection C: Otros modelos probabilísticos (+4)
  {
    id: 'm2-prob-004-009',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X=k) = (1-p)^{k-1} \\cdot p',
    questionLatex: '\\text{Un vendedor tiene éxito en 20\\% de sus llamadas. ¿Cuál es la probabilidad de que su primera venta ocurra en la tercera llamada?}',
    options: ['0.064', '0.128', '0.160', '0.200'],
    correctAnswer: 1,
    explanation: 'P(X=3) = (0.8)^2 \\times 0.2 = 0.128',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['probabilidad-otros-modelos', 'probabilidad-geometrica', 'numeros-decimales']
  },
  {
    id: 'm2-prob-004-010',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'E[X] = \\frac{1}{p}',
    questionLatex: '\\text{En una distribución geométrica con } p = 0.25\\text{, ¿cuántos intentos se esperan en promedio para obtener el primer éxito?}',
    options: ['2', '3', '4', '5'],
    correctAnswer: 2,
    explanation: 'E[X] = \\frac{1}{p} = \\frac{1}{0.25} = 4',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['probabilidad-otros-modelos', 'probabilidad-geometrica', 'probabilidad-esperanza']
  },
  {
    id: 'm2-prob-004-011',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(a \\leq X \\leq b) = \\frac{b-a}{\\text{rango}}',
    questionLatex: '\\text{Un autobús llega a una parada cada 15 minutos. Si una persona llega en un momento aleatorio, ¿cuál es la probabilidad de esperar entre 5 y 10 minutos?}',
    options: ['\\frac{1}{5}', '\\frac{1}{3}', '\\frac{2}{5}', '\\frac{1}{2}'],
    correctAnswer: 1,
    explanation: 'P = \\frac{10-5}{15} = \\frac{5}{15} = \\frac{1}{3}',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['probabilidad-otros-modelos', 'probabilidad-uniforme', 'numeros-fracciones']
  },
  {
    id: 'm2-prob-004-012',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Poisson: eventos en intervalo de tiempo}',
    questionLatex: '\\text{¿Cuál de las siguientes situaciones se modela mejor con una distribución de Poisson?}',
    options: ['\\text{Lanzar una moneda 10 veces}', '\\text{Llamadas a un call center por hora}', '\\text{Elegir 5 cartas de un mazo}', '\\text{Tiempo hasta el primer éxito}'],
    correctAnswer: 1,
    explanation: '\\text{Poisson modela eventos raros en un intervalo de tiempo o espacio}',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['probabilidad-otros-modelos', 'probabilidad-poisson', 'probabilidad-conceptos']
  },
  // Subsection D: Aplicaciones de modelos probabilísticos (+5)
  {
    id: 'm2-prob-004-013',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'E[X] = n \\cdot p; \\quad Var(X) = n \\cdot p \\cdot (1-p)',
    questionLatex: '\\text{En 200 lanzamientos de una moneda equilibrada, ¿cuáles son la esperanza y la varianza del número de caras?}',
    options: ['E=100, Var=25', 'E=100, Var=50', 'E=50, Var=100', 'E=100, Var=100'],
    correctAnswer: 1,
    explanation: 'E = 200 \\times 0.5 = 100; \\quad Var = 200 \\times 0.5 \\times 0.5 = 50',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['probabilidad-modelos-aplicaciones', 'probabilidad-esperanza', 'probabilidad-varianza']
  },
  {
    id: 'm2-prob-004-014',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X \\geq 1) = 1 - P(X=0)',
    questionLatex: '\\text{Un medicamento tiene 90\\% de efectividad. Si se administra a 3 pacientes, ¿cuál es la probabilidad de que al menos uno no responda al tratamiento?}',
    options: ['0.001', '0.271', '0.729', '0.999'],
    correctAnswer: 1,
    explanation: 'P(\\text{al menos 1 no responde}) = 1 - (0.9)^3 = 1 - 0.729 = 0.271',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['probabilidad-modelos-aplicaciones', 'probabilidad-complemento', 'numeros-decimales']
  },
  {
    id: 'm2-prob-004-015',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X=k) \\text{ máximo cuando } k \\approx np',
    questionLatex: '\\text{En 10 lanzamientos de una moneda, ¿cuál es el número de caras más probable de obtener?}',
    options: ['4', '5', '6', '10'],
    correctAnswer: 1,
    explanation: '\\text{El valor más probable es } k = np = 10 \\times 0.5 = 5',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['probabilidad-modelos-aplicaciones', 'probabilidad-distribucion-binomial', 'probabilidad-esperanza']
  },
  {
    id: 'm2-prob-004-016',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P(X \\geq 2) = 1 - P(0) - P(1)',
    questionLatex: '\\text{Un examen tiene 10 preguntas de V/F. Si un estudiante responde al azar, ¿cuál es la probabilidad de aprobar con al menos 7 respuestas correctas?}',
    options: ['\\frac{56}{512}', '\\frac{120}{1024}', '\\frac{176}{1024}', '\\frac{386}{1024}'],
    correctAnswer: 2,
    explanation: 'P(X \\geq 7) = \\frac{C(10,7)+C(10,8)+C(10,9)+C(10,10)}{1024} = \\frac{120+45+10+1}{1024} = \\frac{176}{1024}',
    difficulty: 'hard',
    difficultyScore: 0.58,
    skills: ['probabilidad-modelos-aplicaciones', 'probabilidad-calculo-binomial', 'numeros-fracciones']
  },
  {
    id: 'm2-prob-004-017',
    level: 'M2',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\sigma = \\sqrt{npq}',
    questionLatex: '\\text{En una encuesta, el 40\\% está a favor de una medida. Si se encuestan 225 personas, ¿cuál es la desviación estándar del número de personas a favor?}',
    options: ['6', '7.35', '9', '54'],
    correctAnswer: 1,
    explanation: '\\sigma = \\sqrt{225 \\times 0.4 \\times 0.6} = \\sqrt{54} \\approx 7.35',
    difficulty: 'medium',
    difficultyScore: 0.45,
    skills: ['probabilidad-modelos-aplicaciones', 'probabilidad-desviacion-estandar', 'numeros-raices']
  }
];
