/**
 * Álgebra y Funciones lessons
 * M1-ALG-001 to M1-ALG-011
 */

import type { Lesson } from '../types';

export const ALGEBRA_LESSONS: Lesson[] = [
  {
    id: 'm1-alg-001-a',
    slug: 'terminos-semejantes',
    title: 'Términos Semejantes',
    description: 'Aprende a identificar y combinar términos algebraicos con la misma parte literal.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-terminos-semejantes', 'algebra-expresiones', 'algebra-simplificacion'],
    estimatedMinutes: 12,
    minEducOA: ['MA1M-OA-03'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><text x="40" y="30" text-anchor="middle" font-size="11" fill="#3B82F6">3x + 2x</text><line x1="20" y1="38" x2="60" y2="38" stroke="#9CA3AF" stroke-width="1"/><text x="40" y="55" text-anchor="middle" font-size="14" fill="#10B981" font-weight="bold">= 5x</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'La Frutería Matemática' },
      { id: 'anatomy', type: 'explore', title: 'Anatomía de un Término' },
      { id: 'explain', type: 'explain', title: 'La Regla de Oro' },
      { id: 'classify', type: 'explore', title: 'El Clasificador' },
      { id: 'practice', type: 'practice', title: 'Desafío Express' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-001-b',
    slug: 'propiedad-distributiva',
    title: 'Propiedad Distributiva',
    description: 'Aprende a expandir expresiones usando la propiedad distributiva.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'algebra-expresiones'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-03'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><rect x="15" y="20" width="25" height="20" fill="rgba(59, 130, 246, 0.3)" stroke="#3B82F6" stroke-width="1.5"/><rect x="40" y="20" width="25" height="20" fill="rgba(168, 85, 247, 0.3)" stroke="#A855F7" stroke-width="1.5"/><text x="27.5" y="34" text-anchor="middle" font-size="9" fill="#3B82F6">2·3</text><text x="52.5" y="34" text-anchor="middle" font-size="9" fill="#A855F7">2·x</text><text x="40" y="58" text-anchor="middle" font-size="10" fill="#6B7280">2(3+x)</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'La Tienda de Juguetes' },
      { id: 'explore', type: 'explore', title: 'El Constructor de Áreas' },
      { id: 'explain', type: 'explain', title: 'La Ley de Distribución' },
      { id: 'classify', type: 'explore', title: 'El Distribuidor' },
      { id: 'practice', type: 'practice', title: 'Desafío Distributivo' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-001-c',
    slug: 'productos-notables',
    title: 'Productos Notables',
    description: 'Domina los tres productos notables: cuadrado de binomio, suma por diferencia, y binomios con término común.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-productos-notables', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes'],
    estimatedMinutes: 17,
    minEducOA: ['MA1M-OA-03'],
    thumbnail: {
      type: 'area-model',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Arquitecto de Jardines' },
      { id: 'explore', type: 'explore', title: 'Descubre los Patrones' },
      { id: 'explain', type: 'explain', title: 'Los Tres Productos Notables' },
      { id: 'classify', type: 'explore', title: 'Identifica el Patrón' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-001-d',
    slug: 'productos-notables-cubos',
    title: 'Productos Notables: Cubos',
    description: 'Domina el cubo de un binomio y la suma/diferencia de cubos.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-productos-notables', 'algebra-cubos', 'algebra-factorizacion'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-03'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><path d="M25 50 L25 25 L50 25 L50 50 Z" fill="rgba(59, 130, 246, 0.2)" stroke="#3B82F6" stroke-width="1.5"/><path d="M25 25 L40 15 L65 15 L50 25" fill="rgba(59, 130, 246, 0.3)" stroke="#3B82F6" stroke-width="1.5"/><path d="M50 25 L65 15 L65 40 L50 50" fill="rgba(59, 130, 246, 0.15)" stroke="#3B82F6" stroke-width="1.5"/><text x="40" y="70" text-anchor="middle" font-size="10" fill="#6B7280">(a+b)³</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Cubo Mágico' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Las Fórmulas de los Cubos' },
      { id: 'classify', type: 'explore', title: 'Identifica el Tipo' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-001-e',
    slug: 'factor-comun',
    title: 'Factorización por Factor Común',
    description: 'Aprende a identificar y extraer el factor común de expresiones algebraicas.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-factorizacion', 'algebra-factorizacion-factor-comun', 'algebra-expresiones'],
    estimatedMinutes: 14,
    minEducOA: ['MA1M-OA-03'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><text x="40" y="28" text-anchor="middle" font-size="10" fill="#6B7280">6x + 9</text><line x1="20" y1="35" x2="60" y2="35" stroke="#9CA3AF" stroke-width="1"/><text x="40" y="52" text-anchor="middle" font-size="11" fill="#3B82F6" font-weight="bold">3</text><text x="40" y="52" text-anchor="middle" font-size="11" fill="#3B82F6">(2x + 3)</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Organizador de Cajas' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Tipos de Factor Común' },
      { id: 'classify', type: 'explore', title: 'Identifica el Tipo de Factor' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-001-f',
    slug: 'factorizacion-trinomios',
    title: 'Factorización de Trinomios',
    description: 'Aprende a factorizar trinomios de la forma x² + bx + c encontrando dos números que sumen b y multipliquen c.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-factorizacion', 'algebra-factorizacion-trinomios', 'algebra-expresiones'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-03'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><text x="40" y="25" text-anchor="middle" font-size="9" fill="#6B7280">x² + 5x + 6</text><line x1="20" y1="32" x2="60" y2="32" stroke="#9CA3AF" stroke-width="1"/><text x="40" y="48" text-anchor="middle" font-size="10" fill="#3B82F6">(x+2)(x+3)</text><text x="40" y="65" text-anchor="middle" font-size="8" fill="#A855F7">2+3=5, 2·3=6</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Jardín Rectangular' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Los Casos Según los Signos' },
      { id: 'classify', type: 'explore', title: 'Identifica el Caso de Signos' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-001-g',
    slug: 'diferencia-cuadrados',
    title: 'Factorización por Diferencia de Cuadrados',
    description: 'Domina la factorización de expresiones de la forma a² - b² usando la fórmula (a + b)(a - b).',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-factorizacion', 'algebra-diferencia-cuadrados', 'algebra-expresiones'],
    estimatedMinutes: 14,
    minEducOA: ['MA1M-OA-03'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><text x="40" y="28" text-anchor="middle" font-size="11" fill="#3B82F6">a² − b²</text><line x1="20" y1="38" x2="60" y2="38" stroke="#9CA3AF" stroke-width="1"/><text x="40" y="55" text-anchor="middle" font-size="10" fill="#10B981">(a+b)(a−b)</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Truco del Calculista' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Diferencia de Cuadrados' },
      { id: 'classify', type: 'explore', title: 'Identifica el Tipo de Expresión' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-001-h',
    slug: 'trinomios-cuadraticos-perfectos',
    title: 'Factorización de Trinomios Cuadráticos Perfectos',
    description: 'Aprende a factorizar trinomios de la forma a² ± 2ab + b² reconociéndolos como cuadrados perfectos (a ± b)².',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-factorizacion', 'algebra-trinomios-cuadraticos-perfectos', 'algebra-expresiones'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-03'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><text x="40" y="25" text-anchor="middle" font-size="9" fill="#6B7280">a² + 2ab + b²</text><line x1="20" y1="32" x2="60" y2="32" stroke="#9CA3AF" stroke-width="1"/><text x="40" y="50" text-anchor="middle" font-size="12" fill="#3B82F6">(a + b)²</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Inverso de los Productos Notables' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Trinomios Cuadráticos Perfectos' },
      { id: 'classify', type: 'explore', title: 'Identifica el Tipo' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-001-i',
    slug: 'factorizacion-trinomios-ax2',
    title: 'Factorización de Trinomios ax² + bx + c',
    description: 'Domina la factorización de trinomios cuando el coeficiente de x² no es 1, usando el Método AC.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-factorizacion', 'algebra-factorizacion-trinomios-ax2', 'algebra-metodo-ac'],
    estimatedMinutes: 16,
    minEducOA: ['MA1M-OA-03'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><text x="40" y="22" text-anchor="middle" font-size="9" fill="#6B7280">2x² + 7x + 3</text><rect x="25" y="30" width="30" height="20" rx="3" fill="rgba(168, 85, 247, 0.2)" stroke="#A855F7" stroke-width="1.5"/><text x="40" y="44" text-anchor="middle" font-size="10" fill="#A855F7" font-weight="bold">AC</text><text x="40" y="65" text-anchor="middle" font-size="9" fill="#3B82F6">(2x+1)(x+3)</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'La Bodega de Muebles' },
      { id: 'explore', type: 'explore', title: 'Descubre el Método AC' },
      { id: 'explain', type: 'explain', title: 'Métodos de Factorización' },
      { id: 'classify', type: 'explore', title: 'Identifica los Valores m y n' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-001-j',
    slug: 'factorizacion-agrupacion',
    title: 'Factorización por Agrupación',
    description: 'Aprende a factorizar expresiones de 4 términos agrupándolos de a pares y extrayendo factores comunes.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-factorizacion', 'algebra-factorizacion-agrupacion', 'algebra-expresiones'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-03'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><rect x="10" y="20" width="28" height="15" rx="2" fill="rgba(59, 130, 246, 0.2)" stroke="#3B82F6" stroke-width="1"/><rect x="42" y="20" width="28" height="15" rx="2" fill="rgba(16, 185, 129, 0.2)" stroke="#10B981" stroke-width="1"/><text x="24" y="31" text-anchor="middle" font-size="8" fill="#3B82F6">ax+ay</text><text x="56" y="31" text-anchor="middle" font-size="8" fill="#10B981">bx+by</text><text x="40" y="55" text-anchor="middle" font-size="9" fill="#A855F7">(a+b)(x+y)</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Terreno del Arquitecto' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Casos de Agrupación' },
      { id: 'classify', type: 'explore', title: '¿Se Puede Agrupar?' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-002-a',
    slug: 'suma-resta-polinomios',
    title: 'Suma y Resta de Polinomios',
    description: 'Aprende a sumar y restar polinomios agrupando términos semejantes y operando sus coeficientes.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-002',
    skills: ['algebra-polinomios', 'algebra-terminos-semejantes', 'algebra-operaciones-basicas'],
    estimatedMinutes: 15,
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><text x="40" y="22" text-anchor="middle" font-size="8" fill="#3B82F6">(2x² + 3x)</text><text x="40" y="35" text-anchor="middle" font-size="8" fill="#10B981">+ (x² − 2x)</text><line x1="20" y1="42" x2="60" y2="42" stroke="#9CA3AF" stroke-width="1"/><text x="40" y="58" text-anchor="middle" font-size="9" fill="#A855F7" font-weight="bold">3x² + x</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Gerente de la Empresa' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Las Reglas de la Operatoria' },
      { id: 'classify', type: 'explore', title: 'Identifica el Resultado' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-003-a',
    slug: 'ecuaciones-problemas',
    title: 'Problemas con Ecuaciones Lineales',
    description: 'Aprende a traducir problemas de la vida real a ecuaciones lineales y resolverlas paso a paso.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-003',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'algebra-traduccion-problemas'],
    estimatedMinutes: 15,
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><rect x="15" y="20" width="50" height="25" rx="4" fill="rgba(59, 130, 246, 0.1)" stroke="#3B82F6" stroke-width="1.5"/><text x="40" y="36" text-anchor="middle" font-size="10" fill="#3B82F6">2x + 5 = 15</text><text x="40" y="58" text-anchor="middle" font-size="12" fill="#10B981" font-weight="bold">x = 5</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Misterio del Precio' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Método para Resolver Problemas' },
      { id: 'classify', type: 'explore', title: 'Identifica la Ecuación' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-004-a',
    slug: 'proporcion-directa-inversa',
    title: 'Proporción Directa e Inversa',
    description: 'Aprende a identificar y calcular proporciones directas e inversas en problemas de la vida real.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-004',
    skills: ['algebra-proporcion-directa', 'algebra-proporcion-inversa', 'algebra-constante-proporcionalidad'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-10'],
    thumbnail: {
      type: 'line-chart',
      config: {
        data: [
          { label: '1', value: 2 },
          { label: '2', value: 4 },
          { label: '3', value: 6 },
          { label: '4', value: 8 },
        ],
      },
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Viaje en Auto' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Proporciones: Directa e Inversa' },
      { id: 'classify', type: 'explore', title: 'Clasifica la Proporción' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-005-a',
    slug: 'proporcionalidad-problemas',
    title: 'Problemas de Proporcionalidad',
    description: 'Aprende a identificar y resolver problemas de proporcionalidad directa e inversa usando regla de tres.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-005',
    skills: ['proporcionalidad-directa', 'proporcionalidad-inversa', 'regla-de-tres'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-10'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><text x="20" y="28" font-size="10" fill="#3B82F6">3</text><text x="55" y="28" font-size="10" fill="#3B82F6">6</text><line x1="30" y1="25" x2="48" y2="25" stroke="#9CA3AF" stroke-width="1"/><text x="20" y="50" font-size="10" fill="#10B981">5</text><text x="55" y="50" font-size="10" fill="#10B981">x</text><line x1="30" y1="47" x2="48" y2="47" stroke="#9CA3AF" stroke-width="1"/><line x1="15" y1="35" x2="15" y2="55" stroke="#A855F7" stroke-width="1.5"/><line x1="65" y1="35" x2="65" y2="55" stroke="#A855F7" stroke-width="1.5"/></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Proyecto de Construcción' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Fórmulas y Método de Resolución' },
      { id: 'classify', type: 'explore', title: 'Clasifica el Tipo' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-005-b',
    slug: 'proporcionalidad-compuesta',
    title: 'Proporcionalidad Compuesta',
    description: 'Aprende a resolver problemas donde varias magnitudes afectan el resultado, combinando proporcionalidad directa e inversa.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-005',
    skills: ['proporcionalidad-compuesta', 'regla-de-tres-compuesta', 'analisis-magnitudes'],
    estimatedMinutes: 18,
    minEducOA: ['MA1M-OA-10'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><circle cx="25" cy="30" r="10" fill="rgba(59, 130, 246, 0.2)" stroke="#3B82F6" stroke-width="1.5"/><circle cx="55" cy="30" r="10" fill="rgba(16, 185, 129, 0.2)" stroke="#10B981" stroke-width="1.5"/><text x="25" y="34" text-anchor="middle" font-size="8" fill="#3B82F6">A</text><text x="55" y="34" text-anchor="middle" font-size="8" fill="#10B981">B</text><path d="M25 42 L40 55 L55 42" stroke="#A855F7" stroke-width="1.5" fill="none"/><circle cx="40" cy="60" r="8" fill="rgba(168, 85, 247, 0.2)" stroke="#A855F7" stroke-width="1.5"/><text x="40" y="64" text-anchor="middle" font-size="8" fill="#A855F7">x</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'La Fábrica de Muebles' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Proporcionalidad Compuesta' },
      { id: 'classify', type: 'explore', title: 'Clasifica la Relación' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-006-a',
    slug: 'ecuaciones-lineales',
    title: 'Resolución de Ecuaciones Lineales',
    description: 'Aprende a resolver ecuaciones de primer grado usando operaciones inversas y verifica tus respuestas.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-006',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'algebra-operaciones-inversas'],
    estimatedMinutes: 15,
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><rect x="10" y="25" width="28" height="30" rx="3" fill="rgba(59, 130, 246, 0.2)" stroke="#3B82F6" stroke-width="1.5"/><rect x="42" y="25" width="28" height="30" rx="3" fill="rgba(16, 185, 129, 0.2)" stroke="#10B981" stroke-width="1.5"/><text x="24" y="44" text-anchor="middle" font-size="10" fill="#3B82F6">3x−2</text><text x="56" y="44" text-anchor="middle" font-size="10" fill="#10B981">10</text><line x1="38" y1="35" x2="42" y2="45" stroke="#9CA3AF" stroke-width="2"/><line x1="38" y1="45" x2="42" y2="35" stroke="#9CA3AF" stroke-width="2"/></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'La Cuenta del Restaurante' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Tipos de Ecuaciones Lineales' },
      { id: 'classify', type: 'explore', title: 'Resuelve las Ecuaciones' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-011-a',
    slug: 'completar-cuadrado',
    title: 'Completar el Cuadrado',
    description: 'Aprende la técnica de completar el cuadrado para resolver ecuaciones cuadráticas y encontrar vértices de parábolas.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-011',
    skills: ['algebra-completar-cuadrado', 'algebra-ecuaciones-cuadraticas', 'algebra-vertice-parabola'],
    estimatedMinutes: 15,
    minEducOA: ['MA2M-OA-03', 'MA2M-OA-04'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><rect x="15" y="15" width="30" height="30" fill="rgba(59, 130, 246, 0.3)" stroke="#3B82F6" stroke-width="1.5"/><rect x="45" y="15" width="15" height="30" fill="rgba(59, 130, 246, 0.2)" stroke="#3B82F6" stroke-width="1" stroke-dasharray="3,2"/><rect x="15" y="45" width="30" height="15" fill="rgba(59, 130, 246, 0.2)" stroke="#3B82F6" stroke-width="1" stroke-dasharray="3,2"/><rect x="45" y="45" width="15" height="15" fill="rgba(168, 85, 247, 0.3)" stroke="#A855F7" stroke-width="1.5"/><text x="40" y="75" text-anchor="middle" font-size="9" fill="#6B7280">(x+a)²</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Arquitecto y el Jardín' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Completar el Cuadrado' },
      { id: 'classify', type: 'explore', title: 'Identifica el Cuadrado Completo' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-008-a',
    slug: 'sistemas-metodo-grafico',
    title: 'Sistemas 2x2: Método Gráfico',
    description: 'Aprende a resolver sistemas de ecuaciones 2x2 graficando las rectas y encontrando su intersección.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-008',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-representacion-grafica', 'algebra-graficar-rectas'],
    estimatedMinutes: 14,
    minEducOA: ['MA1M-OA-04'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><line x1="10" y1="40" x2="70" y2="40" stroke="#9CA3AF" stroke-width="1"/><line x1="40" y1="10" x2="40" y2="70" stroke="#9CA3AF" stroke-width="1"/><line x1="15" y1="60" x2="65" y2="20" stroke="#3B82F6" stroke-width="2"/><line x1="15" y1="25" x2="65" y2="55" stroke="#10B981" stroke-width="2"/><circle cx="40" cy="40" r="4" fill="#EF4444"/></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Mapa del Tesoro' },
      { id: 'explore', type: 'explore', title: 'Representación Gráfica' },
      { id: 'explain', type: 'explain', title: 'Método Gráfico' },
      { id: 'classify', type: 'explore', title: 'Clasificar Sistemas' },
      { id: 'practice', type: 'practice', title: 'Lectura de Gráficos' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-008-b',
    slug: 'sistemas-sustitucion',
    title: 'Sistemas 2x2: Método de Sustitución',
    description: 'Domina el método de sustitución: despeja una variable y reemplázala en la otra ecuación.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-008',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-sustitucion', 'algebra-despeje'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-04'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><text x="40" y="22" text-anchor="middle" font-size="9" fill="#3B82F6">y = 2x + 1</text><text x="40" y="38" text-anchor="middle" font-size="9" fill="#10B981">3x + y = 11</text><path d="M55 18 C65 18, 68 28, 60 35" stroke="#A855F7" stroke-width="1.5" fill="none" marker-end="url(#arrow)"/><text x="40" y="58" text-anchor="middle" font-size="9" fill="#A855F7">3x + (2x+1) = 11</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Detective de Variables' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Método de Sustitución' },
      { id: 'classify', type: 'explore', title: 'Elige qué Variable Despejar' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-008-c',
    slug: 'sistemas-igualacion',
    title: 'Sistemas 2x2: Método de Igualación',
    description: 'Aprende el método de igualación: despeja la misma variable en ambas ecuaciones e iguala las expresiones.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-008',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-igualacion', 'algebra-despeje'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-04'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><text x="40" y="22" text-anchor="middle" font-size="9" fill="#3B82F6">y = 2x + 1</text><text x="40" y="38" text-anchor="middle" font-size="9" fill="#10B981">y = 5 − x</text><line x1="20" y1="45" x2="60" y2="45" stroke="#9CA3AF" stroke-width="1"/><text x="40" y="60" text-anchor="middle" font-size="9" fill="#A855F7">2x + 1 = 5 − x</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'Las Balanzas Gemelas' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Método de Igualación' },
      { id: 'classify', type: 'explore', title: 'Identifica las Expresiones' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-008-d',
    slug: 'sistemas-reduccion',
    title: 'Sistemas 2x2: Método de Reducción',
    description: 'Domina el método de reducción (eliminación): suma o resta ecuaciones para eliminar una variable.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-008',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-reduccion', 'algebra-eliminacion'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-04'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><text x="40" y="20" text-anchor="middle" font-size="9" fill="#3B82F6">2x + 3y = 8</text><text x="40" y="35" text-anchor="middle" font-size="9" fill="#10B981">2x − y = 4</text><text x="10" y="28" font-size="12" fill="#EF4444">−</text><line x1="15" y1="42" x2="65" y2="42" stroke="#9CA3AF" stroke-width="1.5"/><text x="40" y="58" text-anchor="middle" font-size="10" fill="#A855F7" font-weight="bold">4y = 4</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Truco del Mago' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Método de Reducción' },
      { id: 'classify', type: 'explore', title: '¿Sumar o Restar?' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-009-a',
    slug: 'funcion-lineal-afin',
    title: 'Función Lineal y Afín',
    description:
      'Distingue funciones lineales (y = mx) de afines (y = mx + b), calcula pendientes y grafica rectas.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-009',
    skills: [
      'funcion-concepto',
      'funcion-lineal-concepto',
      'funcion-afin-pendiente',
      'funcion-lineal-grafica',
    ],
    estimatedMinutes: 18,
    minEducOA: ['MA1M-OA-05'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><line x1="10" y1="40" x2="70" y2="40" stroke="#9CA3AF" stroke-width="1"/><line x1="40" y1="10" x2="40" y2="70" stroke="#9CA3AF" stroke-width="1"/><line x1="15" y1="55" x2="65" y2="25" stroke="#3B82F6" stroke-width="2"/><circle cx="40" cy="40" r="3" fill="#3B82F6"/><text x="50" y="18" font-size="9" fill="#3B82F6">y = mx + b</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Plan de Datos' },
      { id: 'explore', type: 'explore', title: 'Descubriendo el Patrón' },
      { id: 'explain', type: 'explain', title: 'Función Lineal vs Afín' },
      { id: 'classify', type: 'explore', title: 'Clasificación' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-010-a',
    slug: 'relaciones-lineales',
    title: 'Relaciones Lineales en Dos Variables',
    description:
      'Grafica relaciones lineales ax + by = c usando tablas de valores e interceptos.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-010',
    skills: [
      'relacion-lineal-forma-general',
      'interceptos',
      'tabla-valores',
      'graficar-recta',
    ],
    estimatedMinutes: 16,
    minEducOA: ['MA1M-OA-05'],
    thumbnail: {
      type: 'coordinate-plane',
      config: {
        points: [
          { x: 0, y: 3 },
          { x: 2, y: 0 },
        ],
      },
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'La Panadería Matemática' },
      { id: 'explore', type: 'explore', title: 'Descubre la Relación' },
      { id: 'explain', type: 'explain', title: 'Forma General ax + by = c' },
      { id: 'classify', type: 'explore', title: 'Identifica Interceptos' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
];
