/**
 * Álgebra y Funciones lessons
 * M1-ALG-001 to M1-ALG-011
 */

import type { Lesson } from '../types';

export const ALGEBRA_LESSONS: Lesson[] = [
  {
    id: 'm1-alg-001-a',
    slug: 'terminos-semejantes',
    title: 'Términos Semejantes',
    description: 'Aprende a identificar y combinar términos algebraicos con la misma parte literal.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-terminos-semejantes', 'algebra-expresiones', 'algebra-simplificacion'],
    estimatedMinutes: 12,
    minEducOA: ['MA1M-OA-03'],
    steps: [
      { id: 'hook', type: 'hook', title: 'La Frutería Matemática' },
      { id: 'anatomy', type: 'explore', title: 'Anatomía de un Término' },
      { id: 'explain', type: 'explain', title: 'La Regla de Oro' },
      { id: 'classify', type: 'explore', title: 'El Clasificador' },
      { id: 'practice', type: 'practice', title: 'Desafío Express' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-001-b',
    slug: 'propiedad-distributiva',
    title: 'Propiedad Distributiva',
    description: 'Aprende a expandir expresiones usando la propiedad distributiva.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'algebra-expresiones'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-03'],
    steps: [
      { id: 'hook', type: 'hook', title: 'La Tienda de Juguetes' },
      { id: 'explore', type: 'explore', title: 'El Constructor de Áreas' },
      { id: 'explain', type: 'explain', title: 'La Ley de Distribución' },
      { id: 'classify', type: 'explore', title: 'El Distribuidor' },
      { id: 'practice', type: 'practice', title: 'Desafío Distributivo' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-001-c',
    slug: 'productos-notables',
    title: 'Productos Notables',
    description: 'Domina los tres productos notables: cuadrado de binomio, suma por diferencia, y binomios con término común.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-productos-notables', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes'],
    estimatedMinutes: 17,
    minEducOA: ['MA1M-OA-03'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Arquitecto de Jardines' },
      { id: 'explore', type: 'explore', title: 'Descubre los Patrones' },
      { id: 'explain', type: 'explain', title: 'Los Tres Productos Notables' },
      { id: 'classify', type: 'explore', title: 'Identifica el Patrón' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-001-d',
    slug: 'productos-notables-cubos',
    title: 'Productos Notables: Cubos',
    description: 'Domina el cubo de un binomio y la suma/diferencia de cubos.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-productos-notables', 'algebra-cubos', 'algebra-factorizacion'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-03'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Cubo Mágico' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Las Fórmulas de los Cubos' },
      { id: 'classify', type: 'explore', title: 'Identifica el Tipo' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-001-e',
    slug: 'factor-comun',
    title: 'Factorización por Factor Común',
    description: 'Aprende a identificar y extraer el factor común de expresiones algebraicas.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-factorizacion', 'algebra-factorizacion-factor-comun', 'algebra-expresiones'],
    estimatedMinutes: 14,
    minEducOA: ['MA1M-OA-03'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Organizador de Cajas' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Tipos de Factor Común' },
      { id: 'classify', type: 'explore', title: 'Identifica el Tipo de Factor' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-001-f',
    slug: 'factorizacion-trinomios',
    title: 'Factorización de Trinomios',
    description: 'Aprende a factorizar trinomios de la forma x² + bx + c encontrando dos números que sumen b y multipliquen c.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-factorizacion', 'algebra-factorizacion-trinomios', 'algebra-expresiones'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-03'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Jardín Rectangular' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Los Casos Según los Signos' },
      { id: 'classify', type: 'explore', title: 'Identifica el Caso de Signos' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-001-g',
    slug: 'diferencia-cuadrados',
    title: 'Factorización por Diferencia de Cuadrados',
    description: 'Domina la factorización de expresiones de la forma a² - b² usando la fórmula (a + b)(a - b).',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-factorizacion', 'algebra-diferencia-cuadrados', 'algebra-expresiones'],
    estimatedMinutes: 14,
    minEducOA: ['MA1M-OA-03'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Truco del Calculista' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Diferencia de Cuadrados' },
      { id: 'classify', type: 'explore', title: 'Identifica el Tipo de Expresión' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-001-h',
    slug: 'trinomios-cuadraticos-perfectos',
    title: 'Factorización de Trinomios Cuadráticos Perfectos',
    description: 'Aprende a factorizar trinomios de la forma a² ± 2ab + b² reconociéndolos como cuadrados perfectos (a ± b)².',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-factorizacion', 'algebra-trinomios-cuadraticos-perfectos', 'algebra-expresiones'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-03'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Inverso de los Productos Notables' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Trinomios Cuadráticos Perfectos' },
      { id: 'classify', type: 'explore', title: 'Identifica el Tipo' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-001-i',
    slug: 'factorizacion-trinomios-ax2',
    title: 'Factorización de Trinomios ax² + bx + c',
    description: 'Domina la factorización de trinomios cuando el coeficiente de x² no es 1, usando el Método AC.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-factorizacion', 'algebra-factorizacion-trinomios-ax2', 'algebra-metodo-ac'],
    estimatedMinutes: 16,
    minEducOA: ['MA1M-OA-03'],
    steps: [
      { id: 'hook', type: 'hook', title: 'La Bodega de Muebles' },
      { id: 'explore', type: 'explore', title: 'Descubre el Método AC' },
      { id: 'explain', type: 'explain', title: 'Métodos de Factorización' },
      { id: 'classify', type: 'explore', title: 'Identifica los Valores m y n' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-001-j',
    slug: 'factorizacion-agrupacion',
    title: 'Factorización por Agrupación',
    description: 'Aprende a factorizar expresiones de 4 términos agrupándolos de a pares y extrayendo factores comunes.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-001',
    skills: ['algebra-factorizacion', 'algebra-factorizacion-agrupacion', 'algebra-expresiones'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-03'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Terreno del Arquitecto' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Casos de Agrupación' },
      { id: 'classify', type: 'explore', title: '¿Se Puede Agrupar?' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-002-a',
    slug: 'suma-resta-polinomios',
    title: 'Suma y Resta de Polinomios',
    description: 'Aprende a sumar y restar polinomios agrupando términos semejantes y operando sus coeficientes.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-002',
    skills: ['algebra-polinomios', 'algebra-terminos-semejantes', 'algebra-operaciones-basicas'],
    estimatedMinutes: 15,
    steps: [
      { id: 'hook', type: 'hook', title: 'El Gerente de la Empresa' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Las Reglas de la Operatoria' },
      { id: 'classify', type: 'explore', title: 'Identifica el Resultado' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-003-a',
    slug: 'ecuaciones-problemas',
    title: 'Problemas con Ecuaciones Lineales',
    description: 'Aprende a traducir problemas de la vida real a ecuaciones lineales y resolverlas paso a paso.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-003',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'algebra-traduccion-problemas'],
    estimatedMinutes: 15,
    steps: [
      { id: 'hook', type: 'hook', title: 'El Misterio del Precio' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Método para Resolver Problemas' },
      { id: 'classify', type: 'explore', title: 'Identifica la Ecuación' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-004-a',
    slug: 'proporcion-directa-inversa',
    title: 'Proporción Directa e Inversa',
    description: 'Aprende a identificar y calcular proporciones directas e inversas en problemas de la vida real.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-004',
    skills: ['algebra-proporcion-directa', 'algebra-proporcion-inversa', 'algebra-constante-proporcionalidad'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-10'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Viaje en Auto' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Proporciones: Directa e Inversa' },
      { id: 'classify', type: 'explore', title: 'Clasifica la Proporción' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-005-a',
    slug: 'proporcionalidad-problemas',
    title: 'Problemas de Proporcionalidad',
    description: 'Aprende a identificar y resolver problemas de proporcionalidad directa e inversa usando regla de tres.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-005',
    skills: ['proporcionalidad-directa', 'proporcionalidad-inversa', 'regla-de-tres'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-10'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Proyecto de Construcción' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Fórmulas y Método de Resolución' },
      { id: 'classify', type: 'explore', title: 'Clasifica el Tipo' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-005-b',
    slug: 'proporcionalidad-compuesta',
    title: 'Proporcionalidad Compuesta',
    description: 'Aprende a resolver problemas donde varias magnitudes afectan el resultado, combinando proporcionalidad directa e inversa.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-005',
    skills: ['proporcionalidad-compuesta', 'regla-de-tres-compuesta', 'analisis-magnitudes'],
    estimatedMinutes: 18,
    minEducOA: ['MA1M-OA-10'],
    steps: [
      { id: 'hook', type: 'hook', title: 'La Fábrica de Muebles' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Proporcionalidad Compuesta' },
      { id: 'classify', type: 'explore', title: 'Clasifica la Relación' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-006-a',
    slug: 'ecuaciones-lineales',
    title: 'Resolución de Ecuaciones Lineales',
    description: 'Aprende a resolver ecuaciones de primer grado usando operaciones inversas y verifica tus respuestas.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-006',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'algebra-operaciones-inversas'],
    estimatedMinutes: 15,
    steps: [
      { id: 'hook', type: 'hook', title: 'La Cuenta del Restaurante' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Tipos de Ecuaciones Lineales' },
      { id: 'classify', type: 'explore', title: 'Resuelve las Ecuaciones' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-011-a',
    slug: 'completar-cuadrado',
    title: 'Completar el Cuadrado',
    description: 'Aprende la técnica de completar el cuadrado para resolver ecuaciones cuadráticas y encontrar vértices de parábolas.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-011',
    skills: ['algebra-completar-cuadrado', 'algebra-ecuaciones-cuadraticas', 'algebra-vertice-parabola'],
    estimatedMinutes: 15,
    minEducOA: ['MA2M-OA-03', 'MA2M-OA-04'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Arquitecto y el Jardín' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Completar el Cuadrado' },
      { id: 'classify', type: 'explore', title: 'Identifica el Cuadrado Completo' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-008-a',
    slug: 'sistemas-metodo-grafico',
    title: 'Sistemas 2x2: Método Gráfico',
    description: 'Aprende a resolver sistemas de ecuaciones 2x2 graficando las rectas y encontrando su intersección.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-008',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-representacion-grafica', 'algebra-graficar-rectas'],
    estimatedMinutes: 14,
    minEducOA: ['MA1M-OA-04'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Mapa del Tesoro' },
      { id: 'explore', type: 'explore', title: 'Representación Gráfica' },
      { id: 'explain', type: 'explain', title: 'Método Gráfico' },
      { id: 'classify', type: 'explore', title: 'Clasificar Sistemas' },
      { id: 'practice', type: 'practice', title: 'Lectura de Gráficos' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-008-b',
    slug: 'sistemas-sustitucion',
    title: 'Sistemas 2x2: Método de Sustitución',
    description: 'Domina el método de sustitución: despeja una variable y reemplázala en la otra ecuación.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-008',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-sustitucion', 'algebra-despeje'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-04'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Detective de Variables' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Método de Sustitución' },
      { id: 'classify', type: 'explore', title: 'Elige qué Variable Despejar' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-008-c',
    slug: 'sistemas-igualacion',
    title: 'Sistemas 2x2: Método de Igualación',
    description: 'Aprende el método de igualación: despeja la misma variable en ambas ecuaciones e iguala las expresiones.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-008',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-igualacion', 'algebra-despeje'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-04'],
    steps: [
      { id: 'hook', type: 'hook', title: 'Las Balanzas Gemelas' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Método de Igualación' },
      { id: 'classify', type: 'explore', title: 'Identifica las Expresiones' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-alg-008-d',
    slug: 'sistemas-reduccion',
    title: 'Sistemas 2x2: Método de Reducción',
    description: 'Domina el método de reducción (eliminación): suma o resta ecuaciones para eliminar una variable.',
    level: 'M1',
    subject: 'álgebra',
    thematicUnit: 'M1-ALG-008',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-reduccion', 'algebra-eliminacion'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-04'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Truco del Mago' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Método de Reducción' },
      { id: 'classify', type: 'explore', title: '¿Sumar o Restar?' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
];
