/**
 * Geometría lessons
 * M1-GEO-001 to M1-GEO-003
 */

import type { Lesson } from '../types';

export const GEOMETRIA_LESSONS: Lesson[] = [
  {
    id: 'm1-geo-001-a',
    slug: 'teorema-pitagoras',
    title: 'El Teorema de Pitágoras',
    description: 'Descubre la relación entre los lados de un triángulo rectángulo.',
    level: 'M1',
    subject: 'geometría',
    thematicUnit: 'M1-GEO-001',
    skills: ['teorema-pitagoras-aplicar', 'teorema-pitagoras-identificar'],
    estimatedMinutes: 12,
    steps: [
      { id: 'hook', type: 'hook', title: 'El Problema de la Escalera' },
      { id: 'discover', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'proof', type: 'explore', title: 'La Prueba Visual' },
      { id: 'explain', type: 'explain', title: 'El Teorema de Pitágoras' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-geo-001-b',
    slug: 'area-rectangulos-triangulos',
    title: 'Área de Rectángulos y Triángulos',
    description: 'Aprende a calcular el área de rectángulos, cuadrados y triángulos.',
    level: 'M1',
    subject: 'geometría',
    thematicUnit: 'M1-GEO-001',
    skills: ['area-rectangulo', 'area-triangulo'],
    estimatedMinutes: 12,
    minEducOA: ['MA07-OA-13'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Proyecto de Pintura' },
      { id: 'explore', type: 'explore', title: 'Descubriendo Fórmulas' },
      { id: 'explain', type: 'explain', title: 'Fórmulas de Área' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-geo-001-c',
    slug: 'area-paralelogramos-trapecios',
    title: 'Área de Paralelogramos y Trapecios',
    description: 'Aprende a calcular el área de paralelogramos y trapecios usando descomposición.',
    level: 'M1',
    subject: 'geometría',
    thematicUnit: 'M1-GEO-001',
    skills: ['area-paralelogramo', 'area-trapecio', 'descomponer-figuras'],
    estimatedMinutes: 12,
    minEducOA: ['MA07-OA-13'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Jardín Irregular' },
      { id: 'explore', type: 'explore', title: 'Transformando Figuras' },
      { id: 'explain', type: 'explain', title: 'Las Fórmulas' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-geo-001-d',
    slug: 'angulos-interiores-poligonos',
    title: 'Ángulos Interiores de Polígonos',
    description:
      'Descubre la fórmula (n-2)×180° para calcular la suma de ángulos interiores de cualquier polígono.',
    level: 'M1',
    subject: 'geometría',
    thematicUnit: 'M1-GEO-001',
    skills: ['angulos-interiores', 'triangulacion-poligonos', 'poligonos-regulares'],
    estimatedMinutes: 14,
    minEducOA: ['MA07-OA-10'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Kultrun del Artesano' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Las Fórmulas' },
      { id: 'classify', type: 'explore', title: 'Identifica los Ángulos' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-geo-001-e',
    slug: 'angulos-exteriores-poligonos',
    title: 'Ángulos Exteriores de Polígonos',
    description: 'Descubre por qué los ángulos exteriores de cualquier polígono siempre suman 360°.',
    level: 'M1',
    subject: 'geometría',
    thematicUnit: 'M1-GEO-001',
    skills: ['angulos-exteriores', 'angulos-suplementarios', 'poligonos-regulares'],
    estimatedMinutes: 12,
    minEducOA: ['MA07-OA-10'],
    steps: [
      { id: 'hook', type: 'hook', title: 'Caminando por el Polígono' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Las Fórmulas' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-geo-002-a',
    slug: 'circulo-perimetro-area',
    title: 'Circunferencia y Área del Círculo',
    description: 'Descubre Pi (π) y aprende a calcular la circunferencia y el área de círculos.',
    level: 'M1',
    subject: 'geometría',
    thematicUnit: 'M1-GEO-002',
    skills: ['circunferencia-circulo', 'area-circulo', 'pi-concepto'],
    estimatedMinutes: 12,
    minEducOA: ['MA1M-OA-06', 'FG-MATE-3M-OAC-04', 'MA07-OA-11'],
    steps: [
      { id: 'hook', type: 'hook', title: 'La Rueda de la Fortuna' },
      { id: 'explore', type: 'explore', title: 'Descubriendo Pi (π)' },
      { id: 'explain', type: 'explain', title: 'Fórmulas del Círculo' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-geo-002-c',
    slug: 'sectores-circulares',
    title: 'Sectores Circulares y Longitud de Arco',
    description: 'Calcula el area de sectores circulares y la longitud de arcos usando proporciones.',
    level: 'M1',
    subject: 'geometría',
    thematicUnit: 'M1-GEO-002',
    skills: ['sector-circular-area', 'longitud-arco', 'proporciones-circulares'],
    estimatedMinutes: 14,
    minEducOA: ['MA1M-OA-06', 'MA07-OA-11'],
    steps: [
      { id: 'hook', type: 'hook', title: 'La Porcion de Pizza' },
      { id: 'explore', type: 'explore', title: 'Descubre la Fraccion' },
      { id: 'explain', type: 'explain', title: 'Las Formulas' },
      { id: 'practice', type: 'practice', title: 'Practica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-geo-002-b',
    slug: 'figuras-compuestas',
    title: 'Área de Figuras Compuestas',
    description: 'Aprende a calcular el área de figuras irregulares descomponiéndolas en formas simples.',
    level: 'M1',
    subject: 'geometría',
    thematicUnit: 'M1-GEO-002',
    skills: ['area-figuras-compuestas', 'descomponer-figuras', 'suma-areas', 'resta-areas'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-06'],
    steps: [
      { id: 'hook', type: 'hook', title: 'La Habitación en Forma de L' },
      { id: 'explore', type: 'explore', title: 'Dos Estrategias Poderosas' },
      { id: 'explain', type: 'explain', title: 'Fórmulas para Figuras Compuestas' },
      { id: 'classify', type: 'explore', title: '¿Sumar o Restar?' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-geo-003-a',
    slug: 'volumen-cono',
    title: 'Volumen del Cono',
    description: 'Descubre por qué el cono es un tercio del cilindro con una visualización 3D interactiva.',
    level: 'M1',
    subject: 'geometría',
    thematicUnit: 'M1-GEO-003',
    skills: ['geometria-volumen', 'geometria-volumen-cono'],
    estimatedMinutes: 16,
    minEducOA: ['MA1M-OA-07'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Cono de Helado Perfecto' },
      { id: 'explore', type: 'explore', title: 'El Experimento de los 3 Conos' },
      { id: 'explain', type: 'explain', title: 'La Fórmula del Cono' },
      { id: 'classify', type: 'explore', title: 'Identifica las Dimensiones' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-geo-004-a',
    slug: 'coordenadas-cartesianas',
    title: 'Sistema de Coordenadas Cartesianas',
    description:
      'Descubre el plano cartesiano, los cuatro cuadrantes, y aprende a ubicar puntos usando coordenadas (x, y).',
    level: 'M1',
    subject: 'geometría',
    thematicUnit: 'M1-GEO-004',
    skills: ['geometria-coordenadas', 'geometria-cuadrantes', 'geometria-plano-cartesiano'],
    estimatedMinutes: 14,
    minEducOA: ['MA1M-OA-06', 'MA07-OA-14'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Tesoro Escondido' },
      { id: 'explore', type: 'explore', title: 'Descubre el Plano' },
      { id: 'classify', type: 'explore', title: 'Cuadrantes y Signos' },
      { id: 'practice', type: 'practice', title: 'Practica Coordenadas' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm2-geo-001-a',
    slug: 'homotecia',
    title: 'Homotecia: Ampliaciones y Reducciones',
    description:
      'Descubre cómo transformar figuras manteniendo su forma usando el centro y la razón de homotecia.',
    level: 'M2',
    subject: 'geometría',
    thematicUnit: 'M2-GEO-001',
    skills: ['homotecia-concepto', 'homotecia-razon', 'homotecia-construccion'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-08'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Mural del Metro' },
      { id: 'explore', type: 'explore', title: 'Descubre la Homotecia' },
      { id: 'explain', type: 'explain', title: 'Conceptos Clave' },
      { id: 'classify', type: 'explore', title: 'Identifica el Tipo' },
      { id: 'practice', type: 'practice', title: 'Practica Cálculos' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
];
