/**
 * Números lessons
 * M1-NUM-001 to M1-NUM-007
 */

import type { Lesson } from '../types';

export const NUMEROS_LESSONS: Lesson[] = [
  {
    id: 'm1-num-001-a',
    slug: 'numeros-enteros-orden',
    title: 'Orden y Valor Absoluto',
    description: 'Aprende a ordenar números enteros y entender el valor absoluto como distancia.',
    level: 'M1',
    subject: 'números',
    thematicUnit: 'M1-NUM-001',
    skills: ['numeros-enteros-orden', 'numeros-enteros-valor-absoluto'],
    estimatedMinutes: 10,
    minEducOA: ['MA07-OA-01'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Termómetro Loco' },
      { id: 'number-line', type: 'explore', title: 'La Recta Numérica' },
      { id: 'explain', type: 'explain', title: '¿Qué son los Enteros?' },
      { id: 'comparison', type: 'explore', title: 'El Juego de Comparación' },
      { id: 'absolute-value', type: 'explore', title: 'Valor Absoluto: La Distancia' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-num-001-b',
    slug: 'suma-resta-enteros',
    title: 'Suma y Resta de Enteros',
    description: 'Descubre cómo funcionan la suma y resta con números negativos.',
    level: 'M1',
    subject: 'números',
    thematicUnit: 'M1-NUM-001',
    skills: ['numeros-enteros-sumar-restar', 'numeros-enteros-opuesto'],
    estimatedMinutes: 10,
    minEducOA: ['MA07-OA-01'],
    steps: [
      { id: 'hook', type: 'hook', title: 'La Alcancía' },
      { id: 'number-line-addition', type: 'explore', title: 'Suma en la Recta' },
      { id: 'explain', type: 'explain', title: 'Las Reglas de Signos' },
      { id: 'subtraction', type: 'explore', title: 'Resta = Sumar el Opuesto' },
      { id: 'practice', type: 'explore', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-num-001-c',
    slug: 'multiplicacion-division-enteros',
    title: 'Multiplicación y División de Enteros',
    description: 'Domina las reglas de signos en multiplicación y división.',
    level: 'M1',
    subject: 'números',
    thematicUnit: 'M1-NUM-001',
    skills: ['multiplicacion-enteros', 'division-enteros', 'reglas-signos'],
    estimatedMinutes: 15,
    steps: [
      { id: 'hook', type: 'hook', title: 'El Ascensor Mágico' },
      { id: 'sign-rules', type: 'explore', title: 'Descubre las Reglas' },
      { id: 'explain', type: 'explain', title: '¿Por qué funcionan las reglas?' },
      { id: 'practice', type: 'practice', title: 'Práctica de Multiplicación' },
      { id: 'division', type: 'explore', title: 'División con Signos' },
      { id: 'verify', type: 'verify', title: 'Checkpoint Final' },
    ],
  },
  {
    id: 'm1-num-002-a',
    slug: 'fracciones-concepto-comparacion',
    title: 'Fracciones: Concepto y Comparación',
    description: 'Comprende qué son las fracciones y aprende a compararlas usando modelos visuales.',
    level: 'M1',
    subject: 'números',
    thematicUnit: 'M1-NUM-002',
    skills: ['fracciones-concepto', 'fracciones-comparacion', 'fracciones-equivalentes'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-01', 'MA07-OA-03'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Chocolate Perfecto' },
      { id: 'fraction-bars', type: 'explore', title: 'La Barra de Fracciones' },
      { id: 'explain', type: 'explain', title: 'Una Fracción = Un Número' },
      { id: 'practice', type: 'practice', title: '¿Cuál es Mayor?' },
      { id: 'number-line', type: 'explore', title: 'La Recta Numérica' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-num-002-b',
    slug: 'fracciones-mayores-que-1',
    title: 'Fracciones Mayores que 1',
    description: 'Descubre las fracciones impropias y los números mixtos, y aprende a convertir entre ellos.',
    level: 'M1',
    subject: 'números',
    thematicUnit: 'M1-NUM-002',
    skills: ['fracciones-impropias', 'numeros-mixtos', 'conversion-fracciones'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-01', 'MA07-OA-03'],
    steps: [
      { id: 'hook', type: 'hook', title: 'La Fiesta de Pizza' },
      { id: 'improper-fractions', type: 'explore', title: 'Fracciones Impropias' },
      { id: 'explain', type: 'explain', title: 'Dos Formas, Un Número' },
      { id: 'practice', type: 'practice', title: 'Conversiones' },
      { id: 'number-line', type: 'explore', title: 'Más Allá del 1' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-num-002-c',
    slug: 'maximo-comun-divisor',
    title: 'Máximo Común Divisor (M.C.D.)',
    description: 'Aprende a encontrar el máximo común divisor y úsalo para simplificar fracciones.',
    level: 'M1',
    subject: 'números',
    thematicUnit: 'M1-NUM-002',
    skills: ['mcd-concepto', 'factores-comunes', 'simplificacion-fracciones'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-01'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Problema del Reparto' },
      { id: 'explore-factors', type: 'explore', title: 'El Detective de Divisores' },
      { id: 'explain', type: 'explain', title: 'El Método de los Factores' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'explore-tiles', type: 'explore', title: 'El Constructor de Baldosas' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-num-002-d',
    slug: 'suma-resta-fracciones-igual-denominador',
    title: 'Suma y Resta de Fracciones con Igual Denominador',
    description: 'Aprende a sumar y restar fracciones cuando tienen el mismo denominador y simplifica los resultados.',
    level: 'M1',
    subject: 'números',
    thematicUnit: 'M1-NUM-002',
    skills: ['fracciones-suma-igual-denominador', 'fracciones-resta-igual-denominador', 'simplificacion-fracciones'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-01'],
    steps: [
      { id: 'hook', type: 'hook', title: 'Combinando Rebanadas' },
      { id: 'explore-addition', type: 'explore', title: 'Sumando Pedazos' },
      { id: 'explain', type: 'explain', title: 'La Regla de Oro' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'explore-subtraction', type: 'explore', title: 'Restando Pedazos' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-num-002-e',
    slug: 'minimo-comun-multiplo',
    title: 'Mínimo Común Múltiplo (M.C.M.)',
    description: 'Aprende a encontrar el mínimo común múltiplo y úsalo para sumar fracciones con distinto denominador.',
    level: 'M1',
    subject: 'números',
    thematicUnit: 'M1-NUM-002',
    skills: ['mcm-concepto', 'multiplos-comunes', 'fracciones-denominador-comun'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-01', 'MA07-OA-03'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Problema de los Encuentros' },
      { id: 'explore-multiples', type: 'explore', title: 'El Cazador de Múltiplos' },
      { id: 'explain', type: 'explain', title: 'Los Métodos del M.C.M.' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'explore-sync', type: 'explore', title: 'Sincronizando Eventos' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-num-002-f',
    slug: 'suma-resta-fracciones-distinto-denominador',
    title: 'Suma y Resta de Fracciones con Distinto Denominador',
    description: 'Aprende a sumar y restar fracciones cuando tienen diferente denominador usando el mínimo común múltiplo.',
    level: 'M1',
    subject: 'números',
    thematicUnit: 'M1-NUM-002',
    skills: [
      'fracciones-suma-distinto-denominador',
      'fracciones-resta-distinto-denominador',
      'fracciones-denominador-comun',
      'simplificacion-fracciones',
    ],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-01', 'MA07-OA-02'],
    steps: [
      { id: 'hook', type: 'hook', title: 'Pizzas Diferentes' },
      { id: 'explore-lcd', type: 'explore', title: 'Buscando el Denominador Común' },
      { id: 'explain', type: 'explain', title: 'La Regla de la Conversión' },
      { id: 'practice', type: 'practice', title: 'Práctica: Suma' },
      { id: 'explore-subtraction', type: 'explore', title: 'Restando con Distinto Denominador' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-num-002-g',
    slug: 'multiplicacion-division-fracciones',
    title: 'Multiplicación y División de Fracciones',
    description: 'Domina la multiplicación y división de fracciones usando el modelo de área y el recíproco.',
    level: 'M1',
    subject: 'números',
    thematicUnit: 'M1-NUM-002',
    skills: [
      'fracciones-multiplicacion',
      'fracciones-division',
      'fracciones-reciproco',
      'simplificacion-fracciones',
    ],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-01', 'MA07-OA-02'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Chocolate Compartido' },
      { id: 'explore-multiply', type: 'explore', title: 'Descubre la Multiplicación' },
      { id: 'explain', type: 'explain', title: 'Las Reglas de Oro' },
      { id: 'practice', type: 'practice', title: 'Práctica: Multiplicación' },
      { id: 'explore-division', type: 'explore', title: 'El Secreto de la División' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-num-003-a',
    slug: 'potencias-exponente-positivo',
    title: 'Potencias con Exponente Positivo',
    description: 'Aprende qué son las potencias, cómo calcularlas y sus casos especiales.',
    level: 'M1',
    subject: 'números',
    thematicUnit: 'M1-NUM-003',
    skills: ['potencias-concepto', 'potencias-calcular', 'potencias-casos-especiales'],
    estimatedMinutes: 14,
    minEducOA: ['MA1M-OA-02', 'MA07-OA-05'],
    steps: [
      { id: 'hook', type: 'hook', title: 'La Leyenda del Tablero de Ajedrez' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Conceptos de Potencias' },
      { id: 'classify', type: 'explore', title: 'Identifica el Valor' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-num-003-b',
    slug: 'potencias-exponente-cero-negativo',
    title: 'Potencias con Exponente Cero y Negativo',
    description: 'Descubre qué pasa cuando el exponente es cero o negativo y aprende a calcular estas potencias.',
    level: 'M1',
    subject: 'números',
    thematicUnit: 'M1-NUM-003',
    skills: ['potencias-exponente-cero', 'potencias-exponente-negativo', 'potencias-calcular'],
    estimatedMinutes: 14,
    minEducOA: ['MA1M-OA-02', 'MA07-OA-05'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Misterio del Exponente Cero' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Reglas de Exponentes' },
      { id: 'classify', type: 'explore', title: 'Clasifica el Resultado' },
      { id: 'practice', type: 'practice', title: 'Practica Calculando' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-num-003-c',
    slug: 'propiedades-potencias',
    title: 'Propiedades de las Potencias',
    description: 'Domina las propiedades de las potencias: producto, cociente y potencia de potencia.',
    level: 'M1',
    subject: 'números',
    thematicUnit: 'M1-NUM-003',
    skills: ['potencias-producto', 'potencias-cociente', 'potencias-potencia-de-potencia'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-02', 'MA07-OA-05'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Secreto del Científico' },
      { id: 'explore', type: 'explore', title: 'Descubre las Propiedades' },
      { id: 'explain', type: 'explain', title: 'Propiedades de las Potencias' },
      { id: 'classify', type: 'explore', title: 'Identifica la Propiedad' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-num-003-d',
    slug: 'notacion-cientifica',
    title: 'Notación Científica',
    description: 'Aprende a expresar números muy grandes y muy pequeños usando potencias de 10.',
    level: 'M1',
    subject: 'números',
    thematicUnit: 'M1-NUM-003',
    skills: ['notacion-cientifica-convertir', 'notacion-cientifica-identificar', 'potencias-base-10'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-02'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Problema de los Científicos' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Notación Científica' },
      { id: 'classify', type: 'explore', title: 'Identifica la Notación' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-num-004-a',
    slug: 'porcentaje-concepto',
    title: 'Concepto y Cálculo de Porcentaje',
    description: 'Aprende qué son los porcentajes y cómo calcularlos en situaciones cotidianas.',
    level: 'M1',
    subject: 'números',
    thematicUnit: 'M1-NUM-004',
    skills: ['porcentaje-concepto', 'porcentaje-calcular', 'porcentaje-conversiones'],
    estimatedMinutes: 15,
    minEducOA: ['FG-MATE-4M-OAC-01', 'MA07-OA-04'],
    steps: [
      { id: 'hook', type: 'hook', title: 'Las Ofertas del Centro Comercial' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Conceptos de Porcentajes' },
      { id: 'classify', type: 'explore', title: 'Identifica el Valor' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-num-005-a',
    slug: 'problemas-porcentajes',
    title: 'Problemas con Porcentajes',
    description: 'Resuelve problemas de porcentajes en diversos contextos: descuentos, aumentos, comparaciones y más.',
    level: 'M1',
    subject: 'números',
    thematicUnit: 'M1-NUM-005',
    skills: ['porcentaje-problemas', 'porcentaje-sucesivos', 'porcentaje-inverso', 'porcentaje-comparacion'],
    estimatedMinutes: 16,
    minEducOA: ['MA2M-OA-06', 'FG-MATE-4M-OAC-01', 'MA07-OA-04'],
    steps: [
      { id: 'hook', type: 'hook', title: 'La Tienda de Electrónica' },
      { id: 'explore', type: 'explore', title: 'Tipos de Problemas' },
      { id: 'explain', type: 'explain', title: 'Estrategias Avanzadas' },
      { id: 'classify', type: 'explore', title: 'Clasifica el Problema' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-num-007-a',
    slug: 'raices-enesimas',
    title: 'Raíces Enésimas',
    description: 'Aprende qué son las raíces enésimas, cómo calcularlas y su relación con las potencias.',
    level: 'M1',
    subject: 'números',
    thematicUnit: 'M1-NUM-007',
    skills: ['raices-concepto', 'raices-calcular', 'raices-exponente-fraccionario'],
    estimatedMinutes: 15,
    minEducOA: ['MA2M-OA-01'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Jardín Cuadrado' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Conceptos de Raíces Enésimas' },
      { id: 'classify', type: 'explore', title: 'Identifica el Tipo de Raíz' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-num-007-b',
    slug: 'propiedades-raices',
    title: 'Propiedades de Raíces',
    description: 'Domina las tres propiedades fundamentales de las raíces: producto, cociente y raíz de raíz.',
    level: 'M1',
    subject: 'números',
    thematicUnit: 'M1-NUM-007',
    skills: ['raices-propiedad-producto', 'raices-propiedad-cociente', 'raices-propiedad-raiz-de-raiz'],
    estimatedMinutes: 15,
    minEducOA: ['MA2M-OA-01'],
    steps: [
      { id: 'hook', type: 'hook', title: 'La Fábrica de Chocolate' },
      { id: 'explore', type: 'explore', title: 'Descubre las Propiedades' },
      { id: 'explain', type: 'explain', title: 'Propiedades de las Raíces' },
      { id: 'classify', type: 'explore', title: 'Identifica la Propiedad' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm2-num-004-a',
    slug: 'logaritmos',
    title: 'Relación entre Potencias, Raíces y Logaritmos',
    description: 'Comprende los logaritmos como la operación inversa de las potencias.',
    level: 'M2',
    subject: 'números',
    thematicUnit: 'M2-NUM-004',
    skills: ['logaritmos-concepto', 'logaritmos-convertir', 'logaritmos-calcular'],
    estimatedMinutes: 15,
    minEducOA: ['MA2M-OA-02'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Terremoto de Chile' },
      { id: 'explore', type: 'explore', title: 'Descubre el Exponente' },
      { id: 'explain', type: 'explain', title: 'Conceptos de Logaritmos' },
      { id: 'classify', type: 'explore', title: 'Identifica la Forma' },
      { id: 'practice', type: 'practice', title: 'Calcula y Convierte' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm2-num-005-a',
    slug: 'propiedades-logaritmos',
    title: 'Propiedades de los Logaritmos',
    description: 'Domina las propiedades de producto, cociente y potencia para simplificar expresiones logarítmicas.',
    level: 'M2',
    subject: 'números',
    thematicUnit: 'M2-NUM-005',
    skills: ['logaritmos-producto', 'logaritmos-cociente', 'logaritmos-potencia', 'logaritmos-propiedades'],
    estimatedMinutes: 15,
    minEducOA: ['MA2M-OA-02'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Truco del Mago Matemático' },
      { id: 'explore', type: 'explore', title: 'Descubre los Patrones' },
      { id: 'explain', type: 'explain', title: 'Las Propiedades' },
      { id: 'classify', type: 'explore', title: 'Identifica la Propiedad' },
      { id: 'practice', type: 'practice', title: 'Simplifica Expresiones' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm2-num-006-a',
    slug: 'problemas-logaritmos',
    title: 'Problemas con Logaritmos',
    description: 'Aplica logaritmos a contextos reales: escala Richter, decibeles, pH y crecimiento exponencial.',
    level: 'M2',
    subject: 'números',
    thematicUnit: 'M2-NUM-006',
    skills: ['logaritmos-aplicaciones', 'escala-logaritmica', 'modelado-exponencial'],
    estimatedMinutes: 16,
    minEducOA: ['MA2M-OA-02'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Laboratorio de Sonido' },
      { id: 'explore', type: 'explore', title: 'Escalas Logarítmicas' },
      { id: 'explain', type: 'explain', title: 'Aplicaciones Reales' },
      { id: 'classify', type: 'explore', title: 'Identifica el Contexto' },
      { id: 'practice', type: 'practice', title: 'Resuelve Problemas' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
];
