/**
 * Probabilidad y Estadística lessons
 * M1-PROB-001 to M1-PROB-004 and M2-PROB-001
 */

import type { Lesson } from '../types';

export const PROBABILIDAD_LESSONS: Lesson[] = [
  {
    id: 'm1-prob-001-a',
    slug: 'tablas-frecuencia-graficos',
    title: 'Tablas de Frecuencia y Gráficos',
    description: 'Construye tablas de frecuencia y descubre cómo se transforman en gráficos de barras y circulares.',
    level: 'M1',
    subject: 'probabilidad',
    thematicUnit: 'M1-PROB-001',
    skills: ['tablas-frecuencia', 'frecuencia-relativa', 'grafico-barras', 'grafico-circular'],
    estimatedMinutes: 12,
    minEducOA: ['MA1M-OA-12'],
    thumbnail: {
      type: 'bar-chart',
      config: {
        data: [
          { category: 'A', value: 4 },
          { category: 'B', value: 7 },
          { category: 'C', value: 3 },
        ],
      },
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'La Encuesta Misteriosa' },
      { id: 'explore-build', type: 'explore', title: 'Construye tu Gráfico' },
      { id: 'explain', type: 'explain', title: 'Frecuencias y Gráficos' },
      { id: 'practice', type: 'practice', title: 'Interpreta los Datos' },
      { id: 'advanced', type: 'explore', title: 'Del Gráfico de Barras al Circular' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-prob-001-b',
    slug: 'histogramas-datos-agrupados',
    title: 'Histogramas y Datos Agrupados',
    description: 'Aprende a organizar datos numéricos en intervalos y representarlos con histogramas.',
    level: 'M1',
    subject: 'probabilidad',
    thematicUnit: 'M1-PROB-001',
    skills: ['histograma', 'datos-agrupados', 'intervalos', 'marca-clase'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-12'],
    thumbnail: {
      type: 'histogram',
      config: {
        data: [
          { interval: '[0-5)', frequency: 2 },
          { interval: '[5-10)', frequency: 5 },
          { interval: '[10-15)', frequency: 3 },
        ],
      },
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Entrenador Confundido' },
      { id: 'explore', type: 'explore', title: 'Agrupa los Datos' },
      { id: 'explain', type: 'explain', title: 'Histogramas y Datos Agrupados' },
      { id: 'classify', type: 'explore', title: 'Clasifica los Datos' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-prob-002-a',
    slug: 'tendencia-central',
    title: 'Tendencia Central: Media, Mediana y Moda',
    description: 'Descubre las formas de describir el valor "típico" de un conjunto de datos.',
    level: 'M1',
    subject: 'probabilidad',
    thematicUnit: 'M1-PROB-002',
    skills: ['estadistica-media', 'estadistica-mediana', 'estadistica-moda', 'estadistica-rango'],
    estimatedMinutes: 15,
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><circle cx="15" cy="50" r="4" fill="#3B82F6"/><circle cx="25" cy="50" r="4" fill="#3B82F6"/><circle cx="35" cy="50" r="4" fill="#3B82F6"/><circle cx="45" cy="50" r="4" fill="#10B981"/><circle cx="55" cy="50" r="4" fill="#3B82F6"/><circle cx="65" cy="50" r="4" fill="#3B82F6"/><line x1="45" y1="35" x2="45" y2="65" stroke="#10B981" stroke-width="2" stroke-dasharray="3,2"/><text x="45" y="28" text-anchor="middle" font-size="10" fill="#10B981">x̄</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'La Batalla del Top 10' },
      { id: 'explore', type: 'explore', title: 'El Laboratorio de Datos' },
      { id: 'explain', type: 'explain', title: 'Las Cuatro Medidas' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'advanced', type: 'explore', title: 'El Efecto del Outlier' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm2-prob-001-a',
    slug: 'medidas-dispersion',
    title: 'Medidas de Dispersión: Rango, Varianza y Desviación Estándar',
    description: 'Aprende a medir qué tan dispersos están los datos usando rango, varianza y desviación estándar.',
    level: 'M2',
    subject: 'probabilidad',
    thematicUnit: 'M2-PROB-001',
    skills: ['estadistica-rango', 'estadistica-varianza', 'estadistica-desviacion-estandar'],
    estimatedMinutes: 15,
    minEducOA: ['FG-MATE-3M-OAC-02'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><path d="M10 60 Q25 20, 40 40 Q55 60, 70 20" stroke="#3B82F6" stroke-width="2" fill="none"/><line x1="40" y1="25" x2="40" y2="55" stroke="#EF4444" stroke-width="1.5" stroke-dasharray="3,2"/><text x="40" y="68" text-anchor="middle" font-size="9" fill="#6B7280">σ</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Torneo de Tiro con Arco' },
      { id: 'explore', type: 'explore', title: 'El Laboratorio de Dispersión' },
      { id: 'explain', type: 'explain', title: 'Las Medidas de Dispersión' },
      { id: 'classify', type: 'explore', title: 'Compara la Dispersión' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-prob-003-a',
    slug: 'cuartiles-percentiles',
    title: 'Cuartiles, Percentiles y Diagramas de Caja',
    description: 'Aprende a dividir datos en partes iguales y visualizarlos con diagramas de caja.',
    level: 'M1',
    subject: 'probabilidad',
    thematicUnit: 'M1-PROB-003',
    skills: ['estadistica-cuartiles', 'estadistica-percentiles', 'estadistica-boxplot', 'interpretar-posicion'],
    estimatedMinutes: 15,
    minEducOA: ['FG-MATE-3M-OAC-02'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><line x1="10" y1="40" x2="20" y2="40" stroke="#3B82F6" stroke-width="2"/><rect x="20" y="30" width="25" height="20" fill="rgba(59, 130, 246, 0.3)" stroke="#3B82F6" stroke-width="2"/><line x1="35" y1="30" x2="35" y2="50" stroke="#3B82F6" stroke-width="2"/><line x1="45" y1="40" x2="70" y2="40" stroke="#3B82F6" stroke-width="2"/><line x1="10" y1="35" x2="10" y2="45" stroke="#3B82F6" stroke-width="2"/><line x1="70" y1="35" x2="70" y2="45" stroke="#3B82F6" stroke-width="2"/></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Ranking de la Clase' },
      { id: 'explore', type: 'explore', title: 'El Divisor de Datos' },
      { id: 'explain', type: 'explain', title: 'Cuartiles, IQR y Percentiles' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'advanced', type: 'explore', title: 'El Constructor de Boxplot' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-prob-004-a',
    slug: 'probabilidad-eventos',
    title: 'Probabilidad de Eventos',
    description: 'Descubre cómo calcular la probabilidad de que ocurra un evento.',
    level: 'M1',
    subject: 'probabilidad',
    thematicUnit: 'M1-PROB-004',
    skills: ['probabilidad-basica', 'espacio-muestral', 'eventos-favorables'],
    estimatedMinutes: 12,
    minEducOA: ['MA1M-OA-14'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><rect x="20" y="20" width="40" height="40" rx="6" fill="white" stroke="#3B82F6" stroke-width="2"/><circle cx="30" cy="30" r="3" fill="#3B82F6"/><circle cx="50" cy="30" r="3" fill="#3B82F6"/><circle cx="30" cy="50" r="3" fill="#3B82F6"/><circle cx="50" cy="50" r="3" fill="#3B82F6"/><circle cx="40" cy="40" r="3" fill="#3B82F6"/><circle cx="40" cy="60" r="3" fill="#3B82F6"/></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Juego de Dados' },
      { id: 'explore-dice', type: 'explore', title: 'Explorando Posibilidades' },
      { id: 'explain', type: 'explain', title: 'La Fórmula de Probabilidad' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'advanced', type: 'explore', title: 'Más Allá del Dado' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-prob-004-b',
    slug: 'reglas-probabilidad',
    title: 'Reglas de Probabilidad',
    description: 'Domina el complemento y la regla aditiva para calcular probabilidades compuestas.',
    level: 'M1',
    subject: 'probabilidad',
    thematicUnit: 'M1-PROB-004',
    skills: ['probabilidad-complemento', 'regla-aditiva', 'eventos-mutuamente-excluyentes'],
    estimatedMinutes: 12,
    minEducOA: ['MA1M-OA-14'],
    thumbnail: {
      type: 'venn',
      config: {
        countA: 5,
        countB: 4,
        countBoth: 2,
      },
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'Regalos para Sofía' },
      { id: 'explore-venn', type: 'explore', title: 'El Diagrama de Venn' },
      { id: 'explain', type: 'explain', title: 'Las Reglas de Probabilidad' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'advanced', type: 'explore', title: 'Casos Avanzados' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-prob-004-c',
    slug: 'probabilidad-condicional',
    title: 'Probabilidad Condicional e Independencia',
    description: 'Aprende a calcular probabilidades cuando tienes información adicional y a identificar eventos independientes.',
    level: 'M1',
    subject: 'probabilidad',
    thematicUnit: 'M1-PROB-004',
    skills: ['probabilidad-condicional', 'eventos-independientes', 'regla-multiplicacion'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-14', 'FG-MATE-3M-OAC-02'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><circle cx="25" cy="20" r="8" fill="rgba(59, 130, 246, 0.3)" stroke="#3B82F6" stroke-width="1.5"/><line x1="25" y1="28" x2="15" y2="45" stroke="#3B82F6" stroke-width="1.5"/><line x1="25" y1="28" x2="35" y2="45" stroke="#3B82F6" stroke-width="1.5"/><circle cx="15" cy="50" r="6" fill="rgba(16, 185, 129, 0.3)" stroke="#10B981" stroke-width="1.5"/><circle cx="35" cy="50" r="6" fill="rgba(239, 68, 68, 0.3)" stroke="#EF4444" stroke-width="1.5"/><line x1="15" y1="56" x2="10" y2="68" stroke="#10B981" stroke-width="1"/><line x1="15" y1="56" x2="20" y2="68" stroke="#10B981" stroke-width="1"/><text x="55" y="40" font-size="12" fill="#6B7280">P(B|A)</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Pronóstico del Tiempo' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Probabilidad Condicional' },
      { id: 'classify', type: 'explore', title: 'Clasifica los Eventos' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-prob-005-a',
    slug: 'principio-multiplicativo',
    title: 'Principio Multiplicativo de Conteo',
    description: 'Aprende a contar combinaciones usando el principio multiplicativo para resolver problemas de conteo.',
    level: 'M1',
    subject: 'probabilidad',
    thematicUnit: 'M1-PROB-005',
    skills: ['probabilidad-conteo', 'probabilidad-principio-multiplicativo', 'probabilidad-permutaciones'],
    estimatedMinutes: 14,
    minEducOA: ['MA1M-OA-14', 'MA2M-OA-11'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><rect x="10" y="15" width="18" height="18" rx="3" fill="rgba(59, 130, 246, 0.3)" stroke="#3B82F6" stroke-width="1.5"/><rect x="31" y="15" width="18" height="18" rx="3" fill="rgba(59, 130, 246, 0.3)" stroke="#3B82F6" stroke-width="1.5"/><rect x="52" y="15" width="18" height="18" rx="3" fill="rgba(59, 130, 246, 0.3)" stroke="#3B82F6" stroke-width="1.5"/><text x="40" y="50" text-anchor="middle" font-size="14" fill="#3B82F6" font-weight="bold">3 × 3 × 3</text><text x="40" y="68" text-anchor="middle" font-size="12" fill="#10B981">= 27</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'El Dilema del Armario' },
      { id: 'explore', type: 'explore', title: 'Descubriendo el Patrón' },
      { id: 'explain', type: 'explain', title: 'Principio Multiplicativo' },
      { id: 'classify', type: 'explore', title: '¿Multiplicar o No?' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-prob-006-a',
    slug: 'comparar-poblaciones',
    title: 'Comparar Poblaciones con Nubes de Puntos',
    description: 'Aprende a comparar dos poblaciones usando gráficos de dispersión con puntos de dos colores.',
    level: 'M1',
    subject: 'probabilidad',
    thematicUnit: 'M1-PROB-006',
    skills: ['graficos-dispersion', 'comparar-poblaciones', 'correlacion', 'analisis-datos'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-13'],
    thumbnail: {
      type: 'scatter-plot',
      config: {
        data: [
          { x: 1, y: 2 },
          { x: 2, y: 3 },
          { x: 3, y: 4 },
          { x: 4, y: 3.5 },
          { x: 5, y: 5 },
        ],
      },
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'Dos Escuelas, Una Pregunta' },
      { id: 'explore-scatter', type: 'explore', title: 'Construye tu Gráfico' },
      { id: 'explain', type: 'explain', title: 'Nubes de Puntos y Correlación' },
      { id: 'classify', type: 'explore', title: 'Compara las Poblaciones' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-prob-006-b',
    slug: 'comprender-azar',
    title: 'Comprender el Azar',
    description: 'Experimenta con la Tabla de Galton y descubre la Ley de los Grandes Numeros.',
    level: 'M1',
    subject: 'probabilidad',
    thematicUnit: 'M1-PROB-006',
    skills: ['azar', 'frecuencia-relativa', 'ley-grandes-numeros', 'distribucion-normal'],
    estimatedMinutes: 16,
    minEducOA: ['MA1M-OA-15'],
    thumbnail: {
      type: 'custom',
      customSvg: '<svg viewBox="0 0 80 80"><path d="M10 65 Q25 65, 30 50 Q35 30, 40 25 Q45 30, 50 50 Q55 65, 70 65" stroke="#3B82F6" stroke-width="2" fill="rgba(59, 130, 246, 0.2)"/><line x1="40" y1="20" x2="40" y2="70" stroke="#9CA3AF" stroke-width="1" stroke-dasharray="2,2"/><text x="40" y="78" text-anchor="middle" font-size="8" fill="#6B7280">μ</text></svg>',
    },
    steps: [
      { id: 'hook', type: 'hook', title: 'La Racha del Jugador' },
      { id: 'explore-galton', type: 'explore', title: 'La Tabla de Galton' },
      { id: 'explain', type: 'explain', title: 'La Teoria del Azar' },
      { id: 'practice', type: 'practice', title: 'Laboratorio de Frecuencias' },
      { id: 'advanced', type: 'explore', title: 'El Azar en el Mundo Real' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
];
