/**
 * Probabilidad y Estadística lessons
 * M1-PROB-001 to M1-PROB-004 and M2-PROB-001
 */

import type { Lesson } from '../types';

export const PROBABILIDAD_LESSONS: Lesson[] = [
  {
    id: 'm1-prob-001-a',
    slug: 'tablas-frecuencia-graficos',
    title: 'Tablas de Frecuencia y Gráficos',
    description: 'Construye tablas de frecuencia y descubre cómo se transforman en gráficos de barras y circulares.',
    level: 'M1',
    subject: 'probabilidad',
    thematicUnit: 'M1-PROB-001',
    skills: ['tablas-frecuencia', 'frecuencia-relativa', 'grafico-barras', 'grafico-circular'],
    estimatedMinutes: 12,
    minEducOA: ['MA1M-OA-12'],
    steps: [
      { id: 'hook', type: 'hook', title: 'La Encuesta Misteriosa' },
      { id: 'explore-build', type: 'explore', title: 'Construye tu Gráfico' },
      { id: 'explain', type: 'explain', title: 'Frecuencias y Gráficos' },
      { id: 'practice', type: 'practice', title: 'Interpreta los Datos' },
      { id: 'advanced', type: 'explore', title: 'Del Gráfico de Barras al Circular' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-prob-001-b',
    slug: 'histogramas-datos-agrupados',
    title: 'Histogramas y Datos Agrupados',
    description: 'Aprende a organizar datos numéricos en intervalos y representarlos con histogramas.',
    level: 'M1',
    subject: 'probabilidad',
    thematicUnit: 'M1-PROB-001',
    skills: ['histograma', 'datos-agrupados', 'intervalos', 'marca-clase'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-12'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Entrenador Confundido' },
      { id: 'explore', type: 'explore', title: 'Agrupa los Datos' },
      { id: 'explain', type: 'explain', title: 'Histogramas y Datos Agrupados' },
      { id: 'classify', type: 'explore', title: 'Clasifica los Datos' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-prob-002-a',
    slug: 'tendencia-central',
    title: 'Tendencia Central: Media, Mediana y Moda',
    description: 'Descubre las formas de describir el valor "típico" de un conjunto de datos.',
    level: 'M1',
    subject: 'probabilidad',
    thematicUnit: 'M1-PROB-002',
    skills: ['estadistica-media', 'estadistica-mediana', 'estadistica-moda', 'estadistica-rango'],
    estimatedMinutes: 15,
    steps: [
      { id: 'hook', type: 'hook', title: 'La Batalla del Top 10' },
      { id: 'explore', type: 'explore', title: 'El Laboratorio de Datos' },
      { id: 'explain', type: 'explain', title: 'Las Cuatro Medidas' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'advanced', type: 'explore', title: 'El Efecto del Outlier' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm2-prob-001-a',
    slug: 'medidas-dispersion',
    title: 'Medidas de Dispersión: Rango, Varianza y Desviación Estándar',
    description: 'Aprende a medir qué tan dispersos están los datos usando rango, varianza y desviación estándar.',
    level: 'M2',
    subject: 'probabilidad',
    thematicUnit: 'M2-PROB-001',
    skills: ['estadistica-rango', 'estadistica-varianza', 'estadistica-desviacion-estandar'],
    estimatedMinutes: 15,
    steps: [
      { id: 'hook', type: 'hook', title: 'El Torneo de Tiro con Arco' },
      { id: 'explore', type: 'explore', title: 'El Laboratorio de Dispersión' },
      { id: 'explain', type: 'explain', title: 'Las Medidas de Dispersión' },
      { id: 'classify', type: 'explore', title: 'Compara la Dispersión' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-prob-003-a',
    slug: 'cuartiles-percentiles',
    title: 'Cuartiles, Percentiles y Diagramas de Caja',
    description: 'Aprende a dividir datos en partes iguales y visualizarlos con diagramas de caja.',
    level: 'M1',
    subject: 'probabilidad',
    thematicUnit: 'M1-PROB-003',
    skills: ['estadistica-cuartiles', 'estadistica-percentiles', 'estadistica-boxplot', 'interpretar-posicion'],
    estimatedMinutes: 15,
    steps: [
      { id: 'hook', type: 'hook', title: 'El Ranking de la Clase' },
      { id: 'explore', type: 'explore', title: 'El Divisor de Datos' },
      { id: 'explain', type: 'explain', title: 'Cuartiles, IQR y Percentiles' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'advanced', type: 'explore', title: 'El Constructor de Boxplot' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-prob-004-a',
    slug: 'probabilidad-eventos',
    title: 'Probabilidad de Eventos',
    description: 'Descubre cómo calcular la probabilidad de que ocurra un evento.',
    level: 'M1',
    subject: 'probabilidad',
    thematicUnit: 'M1-PROB-004',
    skills: ['probabilidad-basica', 'espacio-muestral', 'eventos-favorables'],
    estimatedMinutes: 12,
    minEducOA: ['MA1M-OA-14'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Juego de Dados' },
      { id: 'explore-dice', type: 'explore', title: 'Explorando Posibilidades' },
      { id: 'explain', type: 'explain', title: 'La Fórmula de Probabilidad' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'advanced', type: 'explore', title: 'Más Allá del Dado' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-prob-004-b',
    slug: 'reglas-probabilidad',
    title: 'Reglas de Probabilidad',
    description: 'Domina el complemento y la regla aditiva para calcular probabilidades compuestas.',
    level: 'M1',
    subject: 'probabilidad',
    thematicUnit: 'M1-PROB-004',
    skills: ['probabilidad-complemento', 'regla-aditiva', 'eventos-mutuamente-excluyentes'],
    estimatedMinutes: 12,
    minEducOA: ['MA1M-OA-14'],
    steps: [
      { id: 'hook', type: 'hook', title: 'Regalos para Sofía' },
      { id: 'explore-venn', type: 'explore', title: 'El Diagrama de Venn' },
      { id: 'explain', type: 'explain', title: 'Las Reglas de Probabilidad' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'advanced', type: 'explore', title: 'Casos Avanzados' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
  {
    id: 'm1-prob-004-c',
    slug: 'probabilidad-condicional',
    title: 'Probabilidad Condicional e Independencia',
    description: 'Aprende a calcular probabilidades cuando tienes información adicional y a identificar eventos independientes.',
    level: 'M1',
    subject: 'probabilidad',
    thematicUnit: 'M1-PROB-004',
    skills: ['probabilidad-condicional', 'eventos-independientes', 'regla-multiplicacion'],
    estimatedMinutes: 15,
    minEducOA: ['MA1M-OA-14'],
    steps: [
      { id: 'hook', type: 'hook', title: 'El Pronóstico del Tiempo' },
      { id: 'explore', type: 'explore', title: 'Descubre el Patrón' },
      { id: 'explain', type: 'explain', title: 'Probabilidad Condicional' },
      { id: 'classify', type: 'explore', title: 'Clasifica los Eventos' },
      { id: 'practice', type: 'practice', title: 'Práctica Guiada' },
      { id: 'verify', type: 'verify', title: 'Checkpoint' },
    ],
  },
];
