import { Question } from '../../../types';

/**
 * M2-NUM-001: Operaciones en el conjunto de los números reales
 *
 * Subsections:
 * A. Números irracionales y su representación
 *    Habilidades: numeros-reales-irracionales
 * B. Operaciones con números reales
 *    Habilidades: numeros-reales-operaciones
 * C. Aproximaciones y redondeo
 *    Habilidades: numeros-reales-aproximaciones
 * D. Intervalos y conjuntos en la recta real
 *    Habilidades: numeros-reales-intervalos
 */

export const m2Num001Questions: Question[] = [
  {
    id: 'm2-num-ent-1',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '\\frac{a}{b} \\pm \\frac{c}{d} = \\frac{ad \\pm bc}{bd}',
    questionLatex: '\\text{Una receta de cocina requiere } \\frac{2}{3} \\text{ de taza de harina, pero el chef decide quitar } \\frac{3}{4} \\text{ de taza y luego agregar } \\frac{1}{6} \\text{ de taza adicional. Para calcular la cantidad final de harina, el chef debe realizar la operación } \\frac{2}{3} - \\frac{3}{4} + \\frac{1}{6}\\text{. ¿Cuál es el resultado de esta operación?}',
    options: ['\\frac{1}{12}', '\\frac{1}{6}', '\\frac{5}{12}', '\\frac{7}{12}'],
    correctAnswer: 0,
    explanation: '\\frac{8}{12} - \\frac{9}{12} + \\frac{2}{12} = \\frac{8 - 9 + 2}{12} = \\frac{1}{12}',
    difficulty: 'medium',
    difficultyScore: 0.55,
    skills: ['numeros-reales-operaciones', 'numeros-fracciones', 'numeros-fracciones-comun-denominador', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-num-ent-2',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '(-3) \\times (-2) \\times 5 \\times (-1)',
    questionLatex: '\\text{Un estudiante de matemáticas está revisando las reglas de los signos en la multiplicación de números enteros. Su profesor le propone evaluar la expresión } (-3) \\times (-2) \\times 5 \\times (-1)\\text{. ¿Cuál es el resultado de esta operación?}',
    options: ['-30', '30', '-15', '15'],
    correctAnswer: 0,
    explanation: '(-3) \\times (-2) \\times 5 \\times (-1) = 6 \\times 5 \\times (-1) = 30 \\times (-1) = -30',
    difficulty: 'medium',
    difficultyScore: 0.55,
    skills: ['numeros-reales-operaciones', 'numeros-enteros', 'numeros-multiplicacion-enteros', 'numeros-signos', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-num-ent-3',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '\\frac{\\frac{a}{b}}{\\frac{c}{d}} = \\frac{a}{b} \\times \\frac{d}{c}',
    questionLatex: '\\text{Un químico está preparando una solución y necesita calcular la concentración final. Para ello, debe dividir la suma de dos cantidades } \\left(\\frac{2}{3} + \\frac{1}{4}\\right) \\text{ entre la diferencia de otras dos } \\left(\\frac{5}{6} - \\frac{1}{3}\\right)\\text{. El químico debe simplificar la expresión } \\frac{\\frac{2}{3} + \\frac{1}{4}}{\\frac{5}{6} - \\frac{1}{3}}\\text{. ¿Cuál es el resultado de esta operación?}',
    options: ['\\frac{11}{6}', '\\frac{6}{11}', '\\frac{7}{6}', '2'],
    correctAnswer: 0,
    explanation: '\\frac{\\frac{11}{12}}{\\frac{1}{2}} = \\frac{11}{12} \\times \\frac{2}{1} = \\frac{11}{6}',
    difficulty: 'extreme',
    difficultyScore: 0.95,
    skills: ['numeros-reales-operaciones', 'numeros-fracciones', 'numeros-fracciones-complejas', 'numeros-division-fracciones', 'numeros-comun-denominador', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-num-pot-1',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '(a^m)^n = a^{mn}; \\quad a^m \\cdot a^n = a^{m+n}',
    questionLatex: '\\text{Un profesor de matemáticas propone a sus estudiantes simplificar la expresión } (2^3)^2 \\cdot 2^{-4} \\text{ como ejercicio de propiedades de potencias. ¿Cuál es la forma simplificada de esta expresión?}',
    options: ['2^2', '2^4', '2^{10}', '2^{-2}'],
    correctAnswer: 0,
    explanation: '(2^3)^2 \\cdot 2^{-4} = 2^6 \\cdot 2^{-4} = 2^{6-4} = 2^2',
    difficulty: 'medium',
    difficultyScore: 0.55,
    skills: ['numeros-reales-operaciones', 'numeros-potencias', 'numeros-propiedades-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-num-pot-2',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '\\sqrt{a \\times b} = \\sqrt{a} \\times \\sqrt{b}',
    questionLatex: '\\text{Un ingeniero civil necesita calcular la diagonal de un terreno cuadrado cuya área es 72 metros cuadrados. Sabe que la diagonal de un cuadrado de lado } l \\text{ es } l\\sqrt{2}\\text{, y que el lado se obtiene como } l = \\sqrt{\\text{área}}\\text{. Para expresar } \\sqrt{72} \\text{ en su forma más simple, el ingeniero debe simplificar esta raíz. ¿Cuál es la forma simplificada de } \\sqrt{72}\\text{?}',
    options: ['6\\sqrt{2}', '8\\sqrt{3}', '4\\sqrt{3}', '9\\sqrt{2}'],
    correctAnswer: 0,
    explanation: '\\sqrt{72} = \\sqrt{36 \\times 2} = \\sqrt{36} \\times \\sqrt{2} = 6\\sqrt{2}',
    difficulty: 'hard',
    difficultyScore: 0.75,
    skills: ['numeros-reales-irracionales', 'numeros-raices', 'numeros-simplificacion-raices', 'numeros-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-num-pot-3',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    questionLatex: '\\text{El valor de } \\left(\\frac{1}{2}\\right)^{-3} \\text{ es:}',
    options: ['8', '-8', '\\frac{1}{8}', '-\\frac{1}{8}'],
    correctAnswer: 0,
    explanation: '\\left(\\frac{1}{2}\\right)^{-3} = \\left(\\frac{2}{1}\\right)^{3} = 2^3 = 8',
    difficulty: 'hard',
    difficultyScore: 0.75,
    skills: ['numeros-reales-operaciones', 'numeros-potencias', 'numeros-exponentes-negativos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-num-pot-4',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '\\sqrt{a \\times b} = \\sqrt{a} \\times \\sqrt{b}',
    questionLatex: '\\text{Un estudiante de álgebra está practicando la simplificación de expresiones con radicales. Debe resolver la expresión } \\sqrt{50} + \\sqrt{32} - \\sqrt{18}\\text{. ¿Cuál es la forma simplificada de esta expresión?}',
    options: ['7\\sqrt{2}', '5\\sqrt{2}', '8\\sqrt{2}', '6\\sqrt{2}'],
    correctAnswer: 3,
    explanation: '5\\sqrt{2} + 4\\sqrt{2} - 3\\sqrt{2} = (5+4-3)\\sqrt{2} = 6\\sqrt{2}',
    difficulty: 'extreme',
    difficultyScore: 0.95,
    skills: ['numeros-reales-irracionales', 'numeros-raices', 'numeros-simplificacion-raices', 'numeros-suma-radicales', 'numeros-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-1',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '\\text{MCM} = \\prod \\text{factores comunes y no comunes con mayor exponente}',
    questionLatex: '\\text{Un organizador de eventos debe programar tres actividades que se repiten en ciclos de 12, 18 y 24 días respectivamente. Para saber cada cuántos días coinciden las tres actividades, necesita calcular el mínimo común múltiplo de estos números. ¿Cuál es el MCM de 12, 18 y 24?}',
    options: ['36', '48', '72', '144'],
    correctAnswer: 2,
    explanation: '12 = 2^2 \\times 3, \\quad 18 = 2 \\times 3^2, \\quad 24 = 2^3 \\times 3 \\quad \\Rightarrow \\quad \\text{MCM} = 2^3 \\times 3^2 = 8 \\times 9 = 72',
    difficulty: 'medium',
    difficultyScore: 0.55,
    skills: ['numeros-reales-operaciones', 'numeros-mcd-mcm', 'numeros-factorizacion-prima', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-num-mcd-1',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '\\text{MCD} = \\prod \\text{factores comunes con menor exponente}',
    questionLatex: '\\text{Una florista tiene 48 rosas, 72 claveles y 120 tulipanes. Quiere hacer la mayor cantidad posible de ramos idénticos usando todas las flores, sin que sobre ninguna. Para determinar cuántos ramos puede hacer, necesita calcular el máximo común divisor de estos números. ¿Cuál es el MCD de 48, 72 y 120?}',
    options: ['12', '24', '36', '8'],
    correctAnswer: 1,
    explanation: '48 = 2^4 \\times 3, \\quad 72 = 2^3 \\times 3^2, \\quad 120 = 2^3 \\times 3 \\times 5 \\quad \\Rightarrow \\quad \\text{MCD} = 2^3 \\times 3 = 24',
    difficulty: 'hard',
    difficultyScore: 0.75,
    skills: ['numeros-reales-operaciones', 'numeros-mcd-mcm', 'numeros-factorizacion-prima', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-num-mcd-2',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '\\text{MCM} = \\prod \\text{factores comunes y no comunes con mayor exponente}',
    questionLatex: '\\text{Tres semáforos cambian a verde cada 15, 20 y 25 segundos respectivamente. Si los tres acaban de ponerse en verde simultáneamente, ¿en cuántos segundos volverán a coincidir en verde? El técnico de tráfico necesita calcular el MCM de 15, 20 y 25.}',
    options: ['100', '150', '300', '75'],
    correctAnswer: 2,
    explanation: '15 = 3 \\times 5, \\quad 20 = 2^2 \\times 5, \\quad 25 = 5^2 \\quad \\Rightarrow \\quad \\text{MCM} = 2^2 \\times 3 \\times 5^2 = 300',
    difficulty: 'hard',
    difficultyScore: 0.75,
    skills: ['numeros-reales-operaciones', 'numeros-mcd-mcm', 'numeros-factorizacion-prima', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-num-mcd-3',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '\\text{MCD} = \\prod \\text{factores comunes con menor exponente}',
    questionLatex: '\\text{Un carpintero tiene dos tablas de madera: una de 36 cm y otra de 48 cm. Quiere cortarlas en trozos iguales de la mayor longitud posible, sin que sobre material. Para determinar la longitud de cada trozo, calcula el MCD de 36 y 48. ¿Cuál es este valor?}',
    options: ['6', '12', '18', '24'],
    correctAnswer: 1,
    explanation: '36 = 2^2 \\times 3^2, \\quad 48 = 2^4 \\times 3 \\quad \\Rightarrow \\quad \\text{MCD} = 2^2 \\times 3 = 12',
    difficulty: 'medium',
    difficultyScore: 0.55,
    skills: ['numeros-reales-operaciones', 'numeros-mcd-mcm', 'numeros-factorizacion-prima', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-num-mcd-4',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '\\text{MCD}(a,b) \\times \\text{MCM}(a,b) = a \\times b',
    questionLatex: '\\text{Un matemático está trabajando con dos números } a \\text{ y } b\\text{. Sabe que el MCD de ambos es 6, el MCM es 72, y que } a = 18\\text{. Usando la relación entre MCD y MCM, necesita determinar el valor de } b\\text{. ¿Cuál es el valor de } b\\text{?}',
    options: ['12', '24', '36', '48'],
    correctAnswer: 1,
    explanation: '6 \\times 72 = 18 \\times b \\quad \\Rightarrow \\quad b = \\frac{432}{18} = 24',
    difficulty: 'extreme',
    difficultyScore: 0.95,
    skills: ['numeros-reales-operaciones', 'numeros-mcd-mcm', 'numeros-relacion-mcd-mcm', 'numeros-operaciones-basicas', 'algebra-despeje']
  },
  {
    id: 'm2-9',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '\\frac{a}{\\sqrt{b}} = \\frac{a\\sqrt{b}}{b}',
    questionLatex: '\\text{Un estudiante de matemáticas está aprendiendo a racionalizar denominadores. Su profesor le pide que exprese la fracción } \\frac{6}{\\sqrt{3}} \\text{ con un denominador racional. ¿Cuál es la forma racionalizada de esta expresión?}',
    options: ['2\\sqrt{3}', '3\\sqrt{2}', '6\\sqrt{3}', '\\sqrt{18}'],
    correctAnswer: 0,
    explanation: '\\frac{6}{\\sqrt{3}} = \\frac{6}{\\sqrt{3}} \\times \\frac{\\sqrt{3}}{\\sqrt{3}} = \\frac{6\\sqrt{3}}{3} = 2\\sqrt{3}',
    difficulty: 'medium',
    difficultyScore: 0.55,
    skills: ['numeros-reales-irracionales', 'numeros-racionalizacion', 'numeros-raices', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-num-rac-1',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '\\frac{a}{\\sqrt{b} + \\sqrt{c}} \\cdot \\frac{\\sqrt{b} - \\sqrt{c}}{\\sqrt{b} - \\sqrt{c}}',
    questionLatex: '\\text{Un profesor de álgebra propone a sus estudiantes racionalizar la expresión } \\frac{10}{\\sqrt{5} + \\sqrt{3}} \\text{ usando el conjugado del denominador. ¿Cuál es la forma racionalizada de esta expresión?}',
    options: ['5(\\sqrt{5} - \\sqrt{3})', '5(\\sqrt{5} + \\sqrt{3})', '\\frac{10}{2}', '10\\sqrt{2}'],
    correctAnswer: 0,
    explanation: '\\frac{10}{\\sqrt{5} + \\sqrt{3}} \\times \\frac{\\sqrt{5} - \\sqrt{3}}{\\sqrt{5} - \\sqrt{3}} = \\frac{10(\\sqrt{5} - \\sqrt{3})}{5 - 3} = \\frac{10(\\sqrt{5} - \\sqrt{3})}{2} = 5(\\sqrt{5} - \\sqrt{3})',
    difficulty: 'extreme',
    difficultyScore: 0.95,
    skills: ['numeros-reales-irracionales', 'numeros-racionalizacion', 'numeros-racionalizacion-conjugado', 'numeros-raices', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-num-rac-2',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '\\frac{a}{b\\sqrt{c}} = \\frac{a\\sqrt{c}}{bc}',
    questionLatex: '\\text{Durante una clase de matemáticas, un estudiante debe racionalizar y simplificar la expresión } \\frac{12}{2\\sqrt{3}}\\text{. ¿Cuál es la forma racionalizada más simple de esta expresión?}',
    options: ['2\\sqrt{3}', '4\\sqrt{3}', '6\\sqrt{3}', '\\sqrt{3}'],
    correctAnswer: 0,
    explanation: '\\frac{12}{2\\sqrt{3}} = \\frac{6}{\\sqrt{3}} \\times \\frac{\\sqrt{3}}{\\sqrt{3}} = \\frac{6\\sqrt{3}}{3} = 2\\sqrt{3}',
    difficulty: 'medium',
    difficultyScore: 0.55,
    skills: ['numeros-reales-irracionales', 'numeros-racionalizacion', 'numeros-raices', 'numeros-fracciones', 'numeros-simplificacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-num-rac-3',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '\\frac{\\sqrt{a}}{\\sqrt{b}} = \\sqrt{\\frac{a}{b}}',
    questionLatex: '\\text{Un estudiante está simplificando expresiones con radicales en su tarea. Debe racionalizar y simplificar la expresión } \\frac{\\sqrt{8}}{\\sqrt{2}}\\text{. ¿Cuál es el resultado simplificado?}',
    options: ['2', '\\sqrt{4}', '4', '\\sqrt{2}'],
    correctAnswer: 0,
    explanation: '\\frac{\\sqrt{8}}{\\sqrt{2}} = \\sqrt{\\frac{8}{2}} = \\sqrt{4} = 2',
    difficulty: 'medium',
    difficultyScore: 0.55,
    skills: ['numeros-reales-irracionales', 'numeros-racionalizacion', 'numeros-raices', 'numeros-simplificacion-raices', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-num-rac-4',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '\\frac{a}{\\sqrt{b} - c} \\cdot \\frac{\\sqrt{b} + c}{\\sqrt{b} + c}',
    questionLatex: '\\text{En un examen de matemáticas, un estudiante debe racionalizar la expresión } \\frac{6}{\\sqrt{2} - 1} \\text{ multiplicando por el conjugado del denominador. ¿Cuál es la forma racionalizada de esta expresión?}',
    options: ['6(\\sqrt{2} + 1)', '6(\\sqrt{2} - 1)', '3(\\sqrt{2} + 1)', '12\\sqrt{2}'],
    correctAnswer: 0,
    explanation: '\\frac{6}{\\sqrt{2} - 1} \\times \\frac{\\sqrt{2} + 1}{\\sqrt{2} + 1} = \\frac{6(\\sqrt{2} + 1)}{2 - 1} = 6(\\sqrt{2} + 1)',
    difficulty: 'hard',
    difficultyScore: 0.75,
    skills: ['numeros-reales-irracionales', 'numeros-racionalizacion', 'numeros-racionalizacion-conjugado', 'numeros-raices', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  // Subsection C: Aproximaciones y redondeo
  {
    id: 'm2-num-aprox-1',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '\\text{Redondeo: si el siguiente dígito} \\geq 5 \\text{, se aumenta}',
    questionLatex: '\\text{Un ingeniero necesita usar el valor de } \\pi \\approx 3.14159265 \\text{ en sus cálculos, pero su calculadora solo permite 2 decimales. ¿Cuál es el valor de } \\pi \\text{ redondeado a 2 decimales?}',
    options: ['3.14', '3.15', '3.1', '3.2'],
    correctAnswer: 0,
    explanation: '3.14159... \\rightarrow 3.14 \\text{ (el tercer decimal es 1 < 5)}',
    difficulty: 'easy',
    difficultyScore: 0.35,
    skills: ['numeros-reales-aproximaciones', 'numeros-redondeo', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm2-num-aprox-2',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '\\text{Cifras significativas: dígitos confiables en una medición}',
    questionLatex: '\\text{Un químico mide la masa de una muestra y obtiene 45.678 gramos. Para reportar el resultado con 3 cifras significativas en su informe de laboratorio, ¿cómo debe expresar esta medición?}',
    options: ['45.6\\text{ g}', '45.7\\text{ g}', '46.0\\text{ g}', '45.0\\text{ g}'],
    correctAnswer: 1,
    explanation: '45.678 \\rightarrow 45.7 \\text{ g (3 cifras significativas)}',
    difficulty: 'medium',
    difficultyScore: 0.55,
    skills: ['numeros-reales-aproximaciones', 'numeros-cifras-significativas', 'numeros-redondeo', 'numeros-decimales']
  },
  {
    id: 'm2-num-aprox-3',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '\\text{Error absoluto} = |\\text{valor exacto} - \\text{valor aproximado}|',
    questionLatex: '\\text{Un estudiante de física utiliza } \\sqrt{2} \\approx 1.414 \\text{ en sus cálculos, pero por simplicidad lo aproxima a 1.4. Para evaluar la precisión de su aproximación, necesita calcular el error absoluto. ¿Cuál es el error absoluto de esta aproximación?}',
    options: ['0.014', '0.014213', '0.01', '0.1'],
    correctAnswer: 0,
    explanation: '\\text{Error} = |1.414 - 1.4| \\approx 0.014',
    difficulty: 'medium',
    difficultyScore: 0.55,
    skills: ['numeros-reales-aproximaciones', 'numeros-error-absoluto', 'numeros-raices', 'numeros-operaciones-basicas']
  },
  // Subsection D: Intervalos y conjuntos en la recta real
  {
    id: 'm2-num-int-1',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: '[a, b) = \\{x \\in \\mathbb{R} : a \\leq x < b\\}',
    questionLatex: '\\text{Un profesor de matemáticas está enseñando notación de intervalos a sus estudiantes. Les pregunta qué representa el intervalo } [2, 5) \\text{ en forma de desigualdad. ¿Cuál es la representación correcta?}',
    options: ['2 < x < 5', '2 \\leq x < 5', '2 < x \\leq 5', '2 \\leq x \\leq 5'],
    correctAnswer: 1,
    explanation: '[2, 5) = \\{x \\in \\mathbb{R} : 2 \\leq x < 5\\}',
    difficulty: 'easy',
    difficultyScore: 0.35,
    skills: ['numeros-reales-intervalos', 'numeros-notacion-intervalos', 'numeros-desigualdades']
  },
  {
    id: 'm2-num-int-2',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: 'x > a \\Leftrightarrow x \\in (a, \\infty)',
    questionLatex: '\\text{Un estudiante está convirtiendo desigualdades a notación de intervalos. Necesita expresar la desigualdad } x > -3 \\text{ en notación de intervalos. ¿Cuál es la representación correcta?}',
    options: ['[-3, \\infty)', '(-3, \\infty)', '(-\\infty, -3)', '(-\\infty, -3]'],
    correctAnswer: 1,
    explanation: 'x > -3 \\Leftrightarrow x \\in (-3, \\infty)',
    difficulty: 'medium',
    difficultyScore: 0.55,
    skills: ['numeros-reales-intervalos', 'numeros-notacion-intervalos', 'numeros-desigualdades', 'numeros-recta-numerica']
  },
  {
    id: 'm2-num-int-3',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: 'A \\cap B = \\{x : x \\in A \\text{ y } x \\in B\\}',
    questionLatex: '\\text{Un matemático está trabajando con dos intervalos: } [1, 6] \\text{ y } [4, 9]\\text{. Necesita encontrar todos los números que pertenecen a ambos intervalos simultáneamente. ¿Cuál es la intersección de estos intervalos?}',
    options: ['[1, 9]', '[4, 6]', '[1, 4]', '[6, 9]'],
    correctAnswer: 1,
    explanation: '[1, 6] \\cap [4, 9] = [4, 6]',
    difficulty: 'medium',
    difficultyScore: 0.55,
    skills: ['numeros-reales-intervalos', 'numeros-operaciones-intervalos', 'numeros-interseccion-intervalos', 'numeros-conjuntos']
  },
  {
    id: 'm2-num-int-4',
    level: 'M2',
    topic: 'Números',
    subject: 'números',
    operacionBase: 'A \\cup B = \\{x : x \\in A \\text{ o } x \\in B\\}',
    questionLatex: '\\text{Un estudiante está practicando operaciones con intervalos. Debe determinar la unión de los intervalos } (-\\infty, 2] \\text{ y } (5, \\infty)\\text{. ¿Cuál es el resultado de esta unión?}',
    options: ['(-\\infty, \\infty)', '(-\\infty, 2] \\cup (5, \\infty)', '[2, 5]', '(2, 5)'],
    correctAnswer: 1,
    explanation: '(-\\infty, 2] \\cup (5, \\infty) \\text{ (intervalos disjuntos)}',
    difficulty: 'hard',
    difficultyScore: 0.75,
    skills: ['numeros-reales-intervalos', 'numeros-operaciones-intervalos', 'numeros-union-intervalos', 'numeros-conjuntos']
  }
];
