import { Question } from '../../../types';

/**
 * M1-PROB-005: Reglas aditiva y multiplicativa de probabilidad
 * Chilean PAES Curriculum - Probability and Statistics Subsection 005
 *
 * This subsection covers:
 * - A: Regla aditiva para eventos mutuamente excluyentes
 * - B: Regla aditiva general
 * - C: Regla multiplicativa para eventos independientes
 * - D: Eventos complementarios
 *
 * Total: 33 questions
 */

export const m1Prob005Questions: Question[] = [
{
    id: 'm1-38',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Al lanzar una moneda dos veces, ¿cuál es la probabilidad de obtener dos caras?',
    questionLatex: '\\text{Al lanzar una moneda dos veces, ¿cuál es la probabilidad de obtener dos caras?}',
    options: ['$\\frac{1}{2}$', '$\\frac{1}{3}$', '$\\frac{1}{4}$', '$\\frac{2}{3}$'],
    optionsLatex: ['\\frac{1}{2}', '\\frac{1}{3}', '\\frac{1}{4}', '\\frac{2}{3}'],
    correctAnswer: 2,
    explanation: 'Los resultados posibles son CC, CS, SC, SS. Solo uno es favorable:',
    explanationLatex: 'P(\\text{dos caras}) = \\frac{1}{4}',
    difficulty: 'medium',
    skills: ['probabilidad-eventos-compuestos', 'probabilidad-basica', 'probabilidad-casos-favorables', 'numeros-fracciones']
  },
{
    id: 'm1-54',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Al lanzar un dado, ¿cuál es la probabilidad de obtener 1 o 2?',
    questionLatex: '\\text{Al lanzar un dado, ¿cuál es la probabilidad de obtener 1 o 2?}',
    options: ['$\\frac{1}{6}$', '$\\frac{1}{3}$', '$\\frac{1}{2}$', '$\\frac{2}{3}$'],
    optionsLatex: ['\\frac{1}{6}', '\\frac{1}{3}', '\\frac{1}{2}', '\\frac{2}{3}'],
    correctAnswer: 1,
    explanation: 'Para eventos mutuamente excluyentes, sumamos las probabilidades:',
    explanationLatex: 'P(1 \\text{ o } 2) = P(1) + P(2) = \\frac{1}{6} + \\frac{1}{6} = \\frac{2}{6} = \\frac{1}{3}',
    difficulty: 'easy',
    skills: ['probabilidad-union', 'probabilidad-basica', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-55',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Al lanzar un dado, ¿cuál es la probabilidad de obtener un número menor que 3 o mayor que 4?',
    questionLatex: '\\text{Al lanzar un dado, ¿cuál es la probabilidad de obtener un número menor que 3 o mayor que 4?}',
    options: ['$\\frac{1}{2}$', '$\\frac{2}{3}$', '$\\frac{5}{6}$', '$\\frac{1}{3}$'],
    optionsLatex: ['\\frac{1}{2}', '\\frac{2}{3}', '\\frac{5}{6}', '\\frac{1}{3}'],
    correctAnswer: 1,
    explanation: 'Menores que 3: {1,2}. Mayores que 4: {5,6}. Total: 4 casos favorables:',
    explanationLatex: 'P = \\frac{4}{6} = \\frac{2}{3}',
    difficulty: 'medium',
    skills: ['probabilidad-union', 'probabilidad-basica', 'numeros-fracciones']
  },
{
    id: 'm1-56',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'En una bolsa hay 3 bolas rojas, 4 azules y 5 verdes. ¿Cuál es la probabilidad de sacar una bola roja o azul?',
    questionLatex: '\\text{En una bolsa hay 3 bolas rojas, 4 azules y 5 verdes. ¿Cuál es la probabilidad de sacar roja o azul?}',
    options: ['$\\frac{1}{4}$', '$\\frac{7}{12}$', '$\\frac{1}{2}$', '$\\frac{2}{3}$'],
    optionsLatex: ['\\frac{1}{4}', '\\frac{7}{12}', '\\frac{1}{2}', '\\frac{2}{3}'],
    correctAnswer: 1,
    explanation: 'Total de bolas: 12. Bolas rojas o azules: 3 + 4 = 7:',
    explanationLatex: 'P(\\text{roja o azul}) = \\frac{7}{12}',
    difficulty: 'medium',
    skills: ['probabilidad-union', 'probabilidad-basica', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-57',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Si tienes 3 camisas y 4 pantalones, ¿de cuántas formas diferentes puedes vestirte?',
    questionLatex: '\\text{Si tienes 3 camisas y 4 pantalones, ¿de cuántas formas puedes vestirte?}',
    options: ['7', '12', '24', '81'],
    correctAnswer: 1,
    explanation: 'Por el principio multiplicativo:',
    explanationLatex: '3 \\times 4 = 12 \\text{ formas diferentes}',
    difficulty: 'easy',
    skills: ['probabilidad-conteo', 'probabilidad-principio-multiplicativo', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-58',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Un menú ofrece 2 entradas, 5 platos principales y 3 postres. ¿Cuántas combinaciones diferentes de menú completo se pueden formar?',
    questionLatex: '\\text{Un menú ofrece 2 entradas, 5 platos principales y 3 postres. ¿Cuántas combinaciones de menú se pueden formar?}',
    options: ['10', '15', '30', '60'],
    correctAnswer: 2,
    explanation: 'Multiplicamos las opciones de cada categoría:',
    explanationLatex: '2 \\times 5 \\times 3 = 30 \\text{ combinaciones}',
    difficulty: 'easy',
    skills: ['probabilidad-conteo', 'probabilidad-principio-multiplicativo', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-59',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: '¿Cuántos números de 3 dígitos se pueden formar con los dígitos 1, 2, 3, 4, 5 si se pueden repetir?',
    questionLatex: '\\text{¿Cuántos números de 3 dígitos se pueden formar con 1, 2, 3, 4, 5 con repetición?}',
    options: ['15', '60', '125', '243'],
    correctAnswer: 2,
    explanation: 'Para cada posición hay 5 opciones:',
    explanationLatex: '5 \\times 5 \\times 5 = 125 \\text{ números}',
    difficulty: 'medium',
    skills: ['probabilidad-conteo', 'probabilidad-principio-multiplicativo', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-60',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: '¿De cuántas formas diferentes se pueden ordenar 4 personas en una fila?',
    questionLatex: '\\text{¿De cuántas formas se pueden ordenar 4 personas en una fila?}',
    options: ['4', '8', '16', '24'],
    correctAnswer: 3,
    explanation: 'El número de permutaciones de 4 elementos es:',
    explanationLatex: '4! = 4 \\times 3 \\times 2 \\times 1 = 24',
    difficulty: 'easy',
    skills: ['probabilidad-permutaciones', 'probabilidad-conteo', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-61',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: '¿De cuántas maneras se pueden organizar las letras de la palabra "SOL"?',
    questionLatex: '\\text{¿De cuántas maneras se pueden organizar las letras de "SOL"?}',
    options: ['3', '6', '9', '27'],
    correctAnswer: 1,
    explanation: 'Permutaciones de 3 letras diferentes:',
    explanationLatex: '3! = 3 \\times 2 \\times 1 = 6',
    difficulty: 'easy',
    skills: ['probabilidad-permutaciones', 'probabilidad-conteo', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-62',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Cinco amigos van al cine. ¿De cuántas formas diferentes pueden sentarse en una fila de 5 asientos?',
    questionLatex: '\\text{Cinco amigos van al cine. ¿De cuántas formas pueden sentarse en una fila de 5 asientos?}',
    options: ['25', '60', '120', '625'],
    correctAnswer: 2,
    explanation: 'Permutaciones de 5 personas:',
    explanationLatex: '5! = 5 \\times 4 \\times 3 \\times 2 \\times 1 = 120',
    difficulty: 'medium',
    skills: ['probabilidad-permutaciones', 'probabilidad-conteo', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-63',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: '¿De cuántas formas se pueden elegir presidente y vicepresidente de un grupo de 5 personas?',
    questionLatex: '\\text{¿De cuántas formas se pueden elegir presidente y vicepresidente de 5 personas?}',
    options: ['5', '10', '20', '25'],
    correctAnswer: 2,
    explanation: 'Hay 5 opciones para presidente y 4 para vicepresidente:',
    explanationLatex: '5 \\times 4 = 20 \\text{ formas}',
    difficulty: 'easy',
    skills: ['probabilidad-variaciones', 'probabilidad-conteo', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-64',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: '¿Cuántos números de 2 dígitos diferentes se pueden formar con los dígitos 1, 2, 3, 4, 5?',
    questionLatex: '\\text{¿Cuántos números de 2 dígitos diferentes se pueden formar con 1, 2, 3, 4, 5?}',
    options: ['10', '20', '25', '30'],
    correctAnswer: 1,
    explanation: 'Para el primer dígito hay 5 opciones, para el segundo hay 4:',
    explanationLatex: '5 \\times 4 = 20 \\text{ números}',
    difficulty: 'easy',
    skills: ['probabilidad-variaciones', 'probabilidad-conteo', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-65',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'En una carrera con 8 participantes, ¿de cuántas formas pueden llegar los 3 primeros lugares?',
    questionLatex: '\\text{En una carrera con 8 participantes, ¿de cuántas formas pueden llegar los 3 primeros?}',
    options: ['24', '56', '168', '336'],
    correctAnswer: 3,
    explanation: 'Variaciones de 8 elementos tomados de 3 en 3:',
    explanationLatex: '8 \\times 7 \\times 6 = 336 \\text{ formas}',
    difficulty: 'hard',
    skills: ['probabilidad-variaciones', 'probabilidad-conteo', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-66',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se lanzan dos dados. ¿Cuál es la probabilidad de que la suma sea 7?',
    questionLatex: '\\text{Se lanzan dos dados. ¿Cuál es la probabilidad de que la suma sea 7?}',
    options: ['$\\frac{1}{12}$', '$\\frac{1}{9}$', '$\\frac{1}{6}$', '$\\frac{5}{36}$'],
    optionsLatex: ['\\frac{1}{12}', '\\frac{1}{9}', '\\frac{1}{6}', '\\frac{5}{36}'],
    correctAnswer: 2,
    explanation: 'Hay 6 formas de obtener suma 7: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1). Total: 36:',
    explanationLatex: 'P(\\text{suma} = 7) = \\frac{6}{36} = \\frac{1}{6}',
    difficulty: 'medium',
    skills: ['probabilidad-eventos-compuestos', 'probabilidad-conteo', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-67',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se lanzan dos monedas. ¿Cuál es la probabilidad de obtener exactamente una cara?',
    questionLatex: '\\text{Se lanzan dos monedas. ¿Cuál es la probabilidad de obtener exactamente una cara?}',
    options: ['$\\frac{1}{4}$', '$\\frac{1}{3}$', '$\\frac{1}{2}$', '$\\frac{3}{4}$'],
    optionsLatex: ['\\frac{1}{4}', '\\frac{1}{3}', '\\frac{1}{2}', '\\frac{3}{4}'],
    correctAnswer: 2,
    explanation: 'Casos favorables: CS y SC. Total de casos: 4:',
    explanationLatex: 'P = \\frac{2}{4} = \\frac{1}{2}',
    difficulty: 'easy',
    skills: ['probabilidad-eventos-compuestos', 'probabilidad-conteo', 'numeros-fracciones']
  },
{
    id: 'm1-68',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'De una baraja de 52 cartas se extrae una al azar. ¿Cuál es la probabilidad de que sea un as o un rey?',
    questionLatex: '\\text{De una baraja de 52 cartas, ¿cuál es la probabilidad de que sea un as o un rey?}',
    options: ['$\\frac{1}{13}$', '$\\frac{2}{13}$', '$\\frac{1}{6}$', '$\\frac{1}{7}$'],
    optionsLatex: ['\\frac{1}{13}', '\\frac{2}{13}', '\\frac{1}{6}', '\\frac{1}{7}'],
    correctAnswer: 1,
    explanation: 'Hay 4 ases y 4 reyes en la baraja:',
    explanationLatex: 'P = \\frac{4 + 4}{52} = \\frac{8}{52} = \\frac{2}{13}',
    difficulty: 'medium',
    skills: ['probabilidad-union', 'probabilidad-basica', 'numeros-fracciones']
  },
{
    id: 'm1-69',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se lanza una moneda tres veces. ¿Cuál es la probabilidad de obtener exactamente dos caras?',
    questionLatex: '\\text{Se lanza una moneda tres veces. ¿Cuál es la probabilidad de obtener exactamente dos caras?}',
    options: ['$\\frac{1}{8}$', '$\\frac{1}{4}$', '$\\frac{3}{8}$', '$\\frac{1}{2}$'],
    optionsLatex: ['\\frac{1}{8}', '\\frac{1}{4}', '\\frac{3}{8}', '\\frac{1}{2}'],
    correctAnswer: 2,
    explanation: 'Casos favorables: CCS, CSC, SCC. Total: 8 casos posibles:',
    explanationLatex: 'P = \\frac{3}{8}',
    difficulty: 'hard',
    skills: ['probabilidad-eventos-compuestos', 'probabilidad-conteo', 'numeros-fracciones']
  },
{
    id: 'm1-70',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Una familia tiene 3 hijos. ¿Cuál es la probabilidad de que los 3 sean del mismo sexo?',
    questionLatex: '\\text{Una familia tiene 3 hijos. ¿Cuál es la probabilidad de que los 3 sean del mismo sexo?}',
    options: ['$\\frac{1}{8}$', '$\\frac{1}{4}$', '$\\frac{3}{8}$', '$\\frac{1}{2}$'],
    optionsLatex: ['\\frac{1}{8}', '\\frac{1}{4}', '\\frac{3}{8}', '\\frac{1}{2}'],
    correctAnswer: 1,
    explanation: 'Casos favorables: HHH o MMM. Total: 8 casos:',
    explanationLatex: 'P = \\frac{2}{8} = \\frac{1}{4}',
    difficulty: 'hard',
    skills: ['probabilidad-eventos-compuestos', 'probabilidad-conteo', 'numeros-fracciones']
  },
{
    id: 'm1-71',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se lanza un dado dos veces. ¿Cuál es la probabilidad de obtener al menos un 6?',
    questionLatex: '\\text{Se lanza un dado dos veces. ¿Cuál es la probabilidad de obtener al menos un 6?}',
    options: ['$\\frac{1}{6}$', '$\\frac{11}{36}$', '$\\frac{1}{3}$', '$\\frac{5}{12}$'],
    optionsLatex: ['\\frac{1}{6}', '\\frac{11}{36}', '\\frac{1}{3}', '\\frac{5}{12}'],
    correctAnswer: 1,
    explanation: 'Más fácil calcular el complemento (ningún 6):',
    explanationLatex: 'P(\\text{al menos un 6}) = 1 - P(\\text{ningún 6}) = 1 - \\frac{5}{6} \\times \\frac{5}{6} = 1 - \\frac{25}{36} = \\frac{11}{36}',
    difficulty: 'hard',
    skills: ['probabilidad-complemento', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-72',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se lanza una moneda y un dado. ¿Cuál es la probabilidad de obtener cara y 5?',
    questionLatex: '\\text{Se lanza una moneda y un dado. ¿Cuál es la probabilidad de obtener cara y 5?}',
    options: ['$\\frac{1}{2}$', '$\\frac{1}{6}$', '$\\frac{1}{8}$', '$\\frac{1}{12}$'],
    optionsLatex: ['\\frac{1}{2}', '\\frac{1}{6}', '\\frac{1}{8}', '\\frac{1}{12}'],
    correctAnswer: 3,
    explanation: 'Para eventos independientes, multiplicamos las probabilidades:',
    explanationLatex: 'P(\\text{cara y 5}) = P(\\text{cara}) \\times P(5) = \\frac{1}{2} \\times \\frac{1}{6} = \\frac{1}{12}',
    difficulty: 'medium',
    skills: ['probabilidad-eventos-independientes', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-73',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se extraen dos cartas de una baraja CON reposición. ¿Cuál es la probabilidad de obtener dos ases?',
    questionLatex: '\\text{Se extraen dos cartas CON reposición. ¿Cuál es la probabilidad de obtener dos ases?}',
    options: ['$\\frac{1}{169}$', '$\\frac{1}{221}$', '$\\frac{4}{663}$', '$\\frac{1}{13}$'],
    optionsLatex: ['\\frac{1}{169}', '\\frac{1}{221}', '\\frac{4}{663}', '\\frac{1}{13}'],
    correctAnswer: 0,
    explanation: 'Con reposición, los eventos son independientes:',
    explanationLatex: 'P = \\frac{4}{52} \\times \\frac{4}{52} = \\frac{1}{13} \\times \\frac{1}{13} = \\frac{1}{169}',
    difficulty: 'hard',
    skills: ['probabilidad-eventos-independientes', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-74',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Ana y José lanzan una moneda cada uno. ¿Cuál es la probabilidad de que ambos obtengan cara?',
    questionLatex: '\\text{Ana y José lanzan una moneda cada uno. ¿Cuál es la probabilidad de que ambos obtengan cara?}',
    options: ['$\\frac{1}{2}$', '$\\frac{1}{3}$', '$\\frac{1}{4}$', '$\\frac{2}{3}$'],
    optionsLatex: ['\\frac{1}{2}', '\\frac{1}{3}', '\\frac{1}{4}', '\\frac{2}{3}'],
    correctAnswer: 2,
    explanation: 'Los lanzamientos son independientes:',
    explanationLatex: 'P = \\frac{1}{2} \\times \\frac{1}{2} = \\frac{1}{4}',
    difficulty: 'easy',
    skills: ['probabilidad-eventos-independientes', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-75',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'En una caja hay 5 bolas rojas y 3 azules. Se extraen 2 bolas SIN reposición. ¿Cuál es la probabilidad de que la primera sea roja y la segunda azul?',
    questionLatex: '\\text{En una caja hay 5 rojas y 3 azules. Se extraen 2 SIN reposición. P(roja y luego azul)?}',
    options: ['$\\frac{15}{56}$', '$\\frac{5}{28}$', '$\\frac{15}{64}$', '$\\frac{3}{14}$'],
    optionsLatex: ['\\frac{15}{56}', '\\frac{5}{28}', '\\frac{15}{64}', '\\frac{3}{14}'],
    correctAnswer: 0,
    explanation: 'Los eventos son dependientes:',
    explanationLatex: 'P = \\frac{5}{8} \\times \\frac{3}{7} = \\frac{15}{56}',
    difficulty: 'hard',
    skills: ['probabilidad-eventos-dependientes', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-76',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se extraen dos cartas de una baraja SIN reposición. ¿Cuál es la probabilidad de que ambas sean corazones?',
    questionLatex: '\\text{Se extraen dos cartas SIN reposición. ¿Cuál es la probabilidad de que ambas sean corazones?}',
    options: ['$\\frac{1}{17}$', '$\\frac{1}{16}$', '$\\frac{13}{204}$', '$\\frac{1}{20}$'],
    optionsLatex: ['\\frac{1}{17}', '\\frac{1}{16}', '\\frac{13}{204}', '\\frac{1}{20}'],
    correctAnswer: 0,
    explanation: 'Primera: 13/52. Segunda (quedan 12 corazones de 51 cartas):',
    explanationLatex: 'P = \\frac{13}{52} \\times \\frac{12}{51} = \\frac{1}{4} \\times \\frac{12}{51} = \\frac{12}{204} = \\frac{1}{17}',
    difficulty: 'hard',
    skills: ['probabilidad-eventos-dependientes', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-77',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Una bolsa tiene 4 bolas verdes y 2 amarillas. Se sacan 2 bolas sin reposición. ¿Cuál es la probabilidad de sacar 2 verdes?',
    questionLatex: '\\text{Una bolsa tiene 4 verdes y 2 amarillas. Se sacan 2 sin reposición. P(2 verdes)?}',
    options: ['$\\frac{1}{5}$', '$\\frac{2}{5}$', '$\\frac{4}{9}$', '$\\frac{2}{15}$'],
    optionsLatex: ['\\frac{1}{5}', '\\frac{2}{5}', '\\frac{4}{9}', '\\frac{2}{15}'],
    correctAnswer: 1,
    explanation: 'Primera verde: 4/6. Segunda verde (quedan 3 verdes de 5):',
    explanationLatex: 'P = \\frac{4}{6} \\times \\frac{3}{5} = \\frac{12}{30} = \\frac{2}{5}',
    difficulty: 'medium',
    skills: ['probabilidad-eventos-dependientes', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-78',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'En un grupo hay 10 hombres y 15 mujeres. Si se elige una persona al azar y resulta ser estudiante de ingeniería, y hay 8 hombres y 6 mujeres estudiando ingeniería, ¿cuál es la probabilidad de que sea mujer?',
    questionLatex: '\\text{10 hombres, 15 mujeres. 8H y 6M estudian ingeniería. Si es de ingeniería, P(mujer)?}',
    options: ['$\\frac{3}{7}$', '$\\frac{2}{5}$', '$\\frac{6}{25}$', '$\\frac{1}{2}$'],
    optionsLatex: ['\\frac{3}{7}', '\\frac{2}{5}', '\\frac{6}{25}', '\\frac{1}{2}'],
    correctAnswer: 0,
    explanation: 'De los 14 estudiantes de ingeniería, 6 son mujeres:',
    explanationLatex: 'P(\\text{mujer}|\\text{ingeniería}) = \\frac{6}{8+6} = \\frac{6}{14} = \\frac{3}{7}',
    difficulty: 'hard',
    skills: ['probabilidad-condicional', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-79',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se lanza un dado. Si el resultado es par, ¿cuál es la probabilidad de que sea mayor que 4?',
    questionLatex: '\\text{Se lanza un dado. Si es par, ¿cuál es la probabilidad de que sea mayor que 4?}',
    options: ['$\\frac{1}{6}$', '$\\frac{1}{3}$', '$\\frac{1}{2}$', '$\\frac{2}{3}$'],
    optionsLatex: ['\\frac{1}{6}', '\\frac{1}{3}', '\\frac{1}{2}', '\\frac{2}{3}'],
    correctAnswer: 1,
    explanation: 'Números pares: {2, 4, 6}. Mayor que 4 y par: solo 6:',
    explanationLatex: 'P(>4|\\text{par}) = \\frac{1}{3}',
    difficulty: 'medium',
    skills: ['probabilidad-condicional', 'numeros-fracciones']
  },
{
    id: 'm1-81',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'En una encuesta a 100 personas: 40 son hombres, 60 mujeres. 25 hombres y 35 mujeres usan redes sociales. ¿Cuál es la probabilidad de que una persona elegida al azar use redes sociales?',
    questionLatex: '\\text{100 personas: 40H, 60M. 25H y 35M usan redes. P(usa redes)?}',
    options: ['0.4', '0.5', '0.6', '0.75'],
    correctAnswer: 2,
    explanation: 'Total que usa redes sociales: 25 + 35 = 60:',
    explanationLatex: 'P = \\frac{60}{100} = 0.6',
    difficulty: 'easy',
    skills: ['probabilidad-tablas', 'estadistica-tablas', 'numeros-fracciones', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-82',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'De 50 estudiantes: 30 aprobaron matemáticas, 25 aprobaron física, 15 aprobaron ambas. ¿Cuántos no aprobaron ninguna?',
    questionLatex: '\\text{50 estudiantes: 30 aprobaron mate, 25 física, 15 ambas. ¿Cuántos ninguna?}',
    options: ['5', '10', '15', '20'],
    correctAnswer: 1,
    explanation: 'Usamos principio de inclusión-exclusión:',
    explanationLatex: '\\text{Al menos una} = 30 + 25 - 15 = 40 \\rightarrow \\text{Ninguna} = 50 - 40 = 10',
    difficulty: 'medium',
    skills: ['probabilidad-tablas', 'probabilidad-union', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-83',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'En un colegio: 120 estudiantes practican deportes, 80 tocan un instrumento, 40 hacen ambas. Si hay 200 estudiantes, ¿cuántos no hacen ninguna actividad?',
    questionLatex: '\\text{200 estudiantes: 120 deportes, 80 música, 40 ambas. ¿Cuántos ninguna?}',
    options: ['20', '40', '60', '80'],
    correctAnswer: 1,
    explanation: 'Estudiantes con al menos una actividad:',
    explanationLatex: '120 + 80 - 40 = 160 \\rightarrow \\text{Ninguna} = 200 - 160 = 40',
    difficulty: 'medium',
    skills: ['probabilidad-tablas', 'probabilidad-union', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-84',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se lanza una moneda 4 veces. ¿Cuántos resultados posibles hay?',
    questionLatex: '\\text{Se lanza una moneda 4 veces. ¿Cuántos resultados posibles?}',
    options: ['4', '8', '16', '32'],
    correctAnswer: 2,
    explanation: 'Cada lanzamiento tiene 2 opciones:',
    explanationLatex: '2^4 = 16 \\text{ resultados posibles}',
    difficulty: 'easy',
    skills: ['probabilidad-espacio-muestral', 'probabilidad-conteo', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-85',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se lanzan tres dados. ¿Cuál es el tamaño del espacio muestral?',
    questionLatex: '\\text{Se lanzan tres dados. ¿Tamaño del espacio muestral?}',
    options: ['18', '36', '108', '216'],
    correctAnswer: 3,
    explanation: 'Cada dado tiene 6 opciones:',
    explanationLatex: '6^3 = 6 \\times 6 \\times 6 = 216',
    difficulty: 'medium',
    skills: ['probabilidad-espacio-muestral', 'probabilidad-conteo', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-86',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: '¿Cuál es la probabilidad de obtener al menos una cara al lanzar 4 monedas?',
    questionLatex: '\\text{¿Probabilidad de al menos una cara al lanzar 4 monedas?}',
    options: ['$\\frac{15}{16}$', '$\\frac{1}{2}$', '$\\frac{7}{8}$', '$\\frac{3}{4}$'],
    optionsLatex: ['\\frac{15}{16}', '\\frac{1}{2}', '\\frac{7}{8}', '\\frac{3}{4}'],
    correctAnswer: 0,
    explanation: 'Complemento de obtener todas sellos:',
    explanationLatex: 'P = 1 - P(\\text{todas sellos}) = 1 - \\left(\\frac{1}{2}\\right)^4 = 1 - \\frac{1}{16} = \\frac{15}{16}',
    difficulty: 'hard',
    skills: ['probabilidad-complemento', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-potencias', 'numeros-operaciones-basicas']
  }
];
