import { Question } from '../../../types';

/**
 * M1-PROB-003: Cuartiles, percentiles y diagramas de caja
 * Chilean PAES Curriculum - Probability and Statistics Subsection 003
 *
 * This subsection covers:
 * - A: Cálculo de cuartiles
 * - B: Cálculo de percentiles
 * - C: Construcción de diagramas de caja
 * - D: Interpretación de diagramas de caja
 *
 * Total: 40 questions
 */

export const m1Prob003Questions: Question[] = [
  // A. Cálculo de cuartiles
  {
    id: 'm1-prob-003-001',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'Q_2 = \\text{mediana}',
    questionLatex: '\\text{Un profesor de educación física registra los tiempos de carrera de 7 estudiantes en orden creciente: 2, 4, 6, 8, 10, 12, 14 minutos. Para analizar el rendimiento del grupo, necesita calcular el segundo cuartil (Q2). ¿Cuál es el valor del segundo cuartil?}',
    options: ['6 minutos', '7 minutos', '8 minutos', '10 minutos'],
    correctAnswer: 2,
    explanation: 'Q_2 = \\text{mediana} = \\text{valor en posición 4} = 8',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['estadistica-cuartiles', 'estadistica-mediana', 'estadistica-medidas-posicion']
  },
  {
    id: 'm1-prob-003-002',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'Q_1 = \\text{mediana de mitad inferior}',
    questionLatex: '\\text{Una investigadora de mercado analiza las edades de 9 participantes en una encuesta. Los datos ordenados son: 3, 5, 7, 9, 11, 13, 15, 17, 19 años. Necesita calcular el primer cuartil (Q1) para identificar el rango de edades del 25\\% más joven. ¿Cuál es el primer cuartil?}',
    options: ['5 años', '6 años', '7 años', '8 años'],
    correctAnswer: 1,
    explanation: '\\text{Con 9 datos, la mediana es 11. Excluyendo la mediana, Q}_1 = \\text{mediana de } \\{3, 5, 7, 9\\} = \\frac{5 + 7}{2} = 6',
    difficulty: 'medium',
    difficultyScore: 0.35,
    skills: ['estadistica-cuartiles', 'estadistica-medidas-posicion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-prob-003-003',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'Q_3 = \\text{mediana de mitad superior}',
    questionLatex: '\\text{Un gerente de ventas revisa las cifras de ventas mensuales de su equipo en miles de pesos: 10, 20, 30, 40, 50, 60, 70, 80, 90. Necesita calcular el tercer cuartil (Q3) para determinar el nivel de ventas que supera al 75\\% de los meses. ¿Cuál es el tercer cuartil?}',
    options: ['60 mil', '65 mil', '70 mil', '75 mil'],
    correctAnswer: 2,
    explanation: 'Q_3 = \\text{mediana de } \\{50, 60, 70, 80, 90\\} = 70, \\text{ o mediana de } \\{60, 70, 80, 90\\} = \\frac{70 + 80}{2} = 75 \\text{ (método inclusivo)}',
    difficulty: 'medium',
    difficultyScore: 0.35,
    skills: ['estadistica-cuartiles', 'estadistica-medidas-posicion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-prob-003-004',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'Q_1 = \\text{mediana de mitad inferior}',
    questionLatex: '\\text{Un nutricionista registra el consumo diario de agua en litros de 6 pacientes: 5, 10, 15, 20, 25, 30. Necesita calcular el primer cuartil (Q1) para identificar el consumo típico del 25\\% de pacientes con menor ingesta. ¿Cuál es el valor del primer cuartil?}',
    options: ['7.5 litros', '10 litros', '12.5 litros', '15 litros'],
    correctAnswer: 1,
    explanation: 'Q_1 = \\text{mediana de } \\{5, 10, 15\\} = 10',
    difficulty: 'easy',
    difficultyScore: 0.32,
    skills: ['estadistica-cuartiles', 'estadistica-medidas-posicion', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-prob-003-005',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'IQR = Q_3 - Q_1',
    questionLatex: '\\text{Un analista financiero estudia los precios de acciones durante 8 días consecutivos en miles de pesos: 10, 14, 18, 22, 30, 34, 38, 42. Necesita calcular el rango intercuartílico (IQR) para medir la dispersión del 50\\% central de los datos. ¿Cuál es el rango intercuartílico?}',
    options: ['12 mil', '15 mil', '18 mil', '20 mil'],
    correctAnswer: 3,
    explanation: 'Q_1 = \\frac{14 + 18}{2} = 16, \\quad Q_3 = \\frac{34 + 38}{2} = 36, \\quad IQR = Q_3 - Q_1 = 36 - 16 = 20',
    difficulty: 'medium',
    difficultyScore: 0.45,
    skills: ['estadistica-cuartiles', 'estadistica-rango-intercuartilico', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-prob-003-006',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'Q_1 = \\text{mediana}(\\text{mitad inferior})',
    questionLatex: '\\text{Una maestra evalúa las calificaciones de 5 estudiantes que están ordenadas así: 2, 4, 6, 8, 10. Necesita calcular el primer cuartil (Q1). ¿Cuál es el primer cuartil?}',
    options: ['2', '3', '4', '5'],
    correctAnswer: 1,
    explanation: 'Q_1 = \\text{mediana de } \\{2, 4\\} = \\frac{2 + 4}{2} = 3',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['estadistica-cuartiles', 'estadistica-mediana', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-prob-003-025',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'Q_3 = \\text{mediana de mitad superior}',
    questionLatex: '\\text{Un veterinario registra los pesos en kilogramos de 12 perros atendidos en una jornada: 3, 5, 7, 8, 10, 12, 14, 16, 18, 20, 22, 25. Necesita calcular el tercer cuartil (Q3) para identificar el peso que supera el 75\\% de los perros. ¿Cuál es el tercer cuartil?}',
    options: ['16 kg', '17 kg', '18 kg', '19 kg'],
    correctAnswer: 1,
    explanation: 'Q_3 = \\text{mediana de } \\{14, 16, 18, 20, 22, 25\\} = \\frac{18 + 16}{2} = 17',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['estadistica-cuartiles', 'estadistica-medidas-posicion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-prob-003-026',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'IQR = Q_3 - Q_1',
    questionLatex: '\\text{Una empresa de envíos analiza los tiempos de entrega en horas de sus últimos 11 pedidos ordenados: 2, 4, 5, 7, 9, 10, 12, 14, 16, 18, 20. El analista calculó Q1=5 y Q3=16. ¿Cuál es el rango intercuartílico (IQR)?}',
    options: ['9 horas', '10 horas', '11 horas', '12 horas'],
    correctAnswer: 2,
    explanation: 'IQR = Q_3 - Q_1 = 16 - 5 = 11',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['estadistica-cuartiles', 'estadistica-rango-intercuartilico', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-prob-003-027',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'Q_1, Q_2, Q_3 \\text{ dividen datos en 4 partes}',
    questionLatex: '\\text{Un estadístico explica a sus alumnos que los cuartiles dividen un conjunto de datos ordenados en cuatro partes iguales. Si un conjunto tiene 100 datos, ¿cuántos datos aproximadamente hay entre el primer cuartil (Q1) y el tercer cuartil (Q3)?}',
    options: ['25 datos', '50 datos', '75 datos', '100 datos'],
    correctAnswer: 1,
    explanation: '\\text{Entre } Q_1 \\text{ y } Q_3 \\text{ hay } 50\\% \\text{ de los datos} = 50 \\text{ datos}',
    difficulty: 'easy',
    difficultyScore: 0.20,
    skills: ['estadistica-cuartiles', 'estadistica-conceptos', 'estadistica-medidas-posicion']
  },
  {
    id: 'm1-prob-003-028',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'Q_1 \\text{ con datos pares}',
    questionLatex: '\\text{Una bióloga mide la longitud en centímetros de 8 hojas de una planta: 4, 6, 8, 10, 12, 14, 16, 18. Para su análisis necesita calcular el primer cuartil (Q1). ¿Cuál es el valor del primer cuartil?}',
    options: ['6 cm', '7 cm', '8 cm', '9 cm'],
    correctAnswer: 1,
    explanation: 'Q_1 = \\text{mediana de } \\{4, 6, 8, 10\\} = \\frac{6 + 8}{2} = 7',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['estadistica-cuartiles', 'estadistica-mediana', 'numeros-operaciones-basicas']
  },

  // B. Cálculo de percentiles
  {
    id: 'm1-prob-003-007',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P_{50} = Q_2 = \\text{mediana}',
    questionLatex: '\\text{Un estadístico explica a sus estudiantes que los percentiles son medidas de posición que dividen los datos en 100 partes iguales. Les pregunta: "Si tenemos un conjunto de datos ordenados y calculamos el percentil 50 (P50), ¿a qué otra medida estadística corresponde exactamente?" ¿A qué medida es equivalente P50?}',
    options: ['Q1 (primer cuartil)', 'Q2 (mediana)', 'Q3 (tercer cuartil)', 'El rango'],
    correctAnswer: 1,
    explanation: 'P_{50} = Q_2 = \\text{mediana}',
    difficulty: 'easy',
    difficultyScore: 0.15,
    skills: ['estadistica-percentiles', 'estadistica-mediana', 'estadistica-conceptos']
  },
  {
    id: 'm1-prob-003-008',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P_{25} = \\frac{\\text{val}_2 + \\text{val}_3}{2}',
    questionLatex: '\\text{Una empresa analiza los salarios mensuales en miles de pesos de sus 10 empleados ordenados así: 10, 20, 30, 40, 50, 60, 70, 80, 90, 100. El gerente de recursos humanos necesita calcular el percentil 25 (P25) para determinar el salario por debajo del cual se encuentra el 25\\% de los empleados. ¿Cuál es el percentil 25?}',
    options: ['25 mil', '27.5 mil', '30 mil', '32.5 mil'],
    correctAnswer: 1,
    explanation: 'P_{25} = \\text{posición } 2.5: 20 + 0.5(30-20) = 27.5',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['estadistica-percentiles', 'estadistica-medidas-posicion', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-prob-003-009',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P_{75} \\rightarrow 75\\% \\text{ por debajo}',
    questionLatex: '\\text{En una prueba estandarizada nacional, un estudiante recibe su resultado junto con la información de que está en el percentil 75 (P75). Su familia le pregunta qué significa exactamente este valor. ¿Qué significa estar en el percentil 75?}',
    options: ['Obtuvo 75% de respuestas correctas en la prueba', 'Superó al 75% de los estudiantes que tomaron la prueba', 'Está entre el 75% más bajo de los estudiantes', '75 estudiantes obtuvieron puntajes superiores'],
    correctAnswer: 1,
    explanation: 'P_{75} \\rightarrow 75\\% \\text{ de los datos} \\leq \\text{puntaje del estudiante}',
    difficulty: 'easy',
    difficultyScore: 0.18,
    skills: ['estadistica-percentiles', 'estadistica-interpretacion', 'estadistica-conceptos']
  },
  {
    id: 'm1-prob-003-010',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P_{90} = \\text{posición } \\frac{90n}{100}',
    questionLatex: '\\text{Un cardiólogo monitorea la presión arterial sistólica de 10 pacientes y registra los valores ordenados: 5, 10, 15, 20, 25, 30, 35, 40, 45, 50 mmHg por encima de lo normal. Necesita calcular el percentil 90 (P90) para identificar el nivel que solo el 10\\% más alto de sus pacientes supera. ¿Cuál es el percentil 90?}',
    options: ['40 mmHg', '45 mmHg', '47.5 mmHg', '50 mmHg'],
    correctAnswer: 1,
    explanation: 'P_{90} = \\text{valor en posición } 9 = 45',
    difficulty: 'medium',
    difficultyScore: 0.35,
    skills: ['estadistica-percentiles', 'estadistica-medidas-posicion']
  },
  {
    id: 'm1-prob-003-011',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'Q_1 = P_{25}',
    questionLatex: '\\text{Un profesor de estadística explica a su clase la relación entre cuartiles y percentiles. Les indica que los cuartiles son casos especiales de percentiles que dividen los datos en cuatro partes iguales. Específicamente, pregunta: "El primer cuartil (Q1), que separa el 25\\% inferior de los datos, ¿a qué percentil corresponde exactamente?" ¿Qué percentil corresponde a Q1?}',
    options: ['P10 (percentil 10)', 'P25 (percentil 25)', 'P50 (percentil 50)', 'P75 (percentil 75)'],
    correctAnswer: 1,
    explanation: 'Q_1 = P_{25} \\text{ (ambos dejan 25\\% de datos por debajo)}',
    difficulty: 'easy',
    difficultyScore: 0.15,
    skills: ['estadistica-percentiles', 'estadistica-cuartiles', 'estadistica-conceptos']
  },
  {
    id: 'm1-prob-003-012',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P_{10} \\rightarrow 10\\% \\leq \\text{valor}',
    questionLatex: '\\text{Una economista analiza la distribución de salarios en una empresa grande y encuentra que el percentil 10 (P10) de los salarios es \\$400,000 pesos mensuales. El sindicato de trabajadores solicita una explicación clara de qué significa este valor estadístico. ¿Qué significa que el percentil 10 sea \\$400,000?}',
    options: ['El 10% de los empleados gana exactamente $400,000', 'El 10% de los empleados gana $400,000 o menos', 'El 90% de los empleados gana exactamente $400,000', 'El 10% de los empleados gana más de $400,000'],
    correctAnswer: 1,
    explanation: 'P_{10} = \\$400{,}000 \\rightarrow 10\\% \\text{ de salarios} \\leq \\$400{,}000',
    difficulty: 'easy',
    difficultyScore: 0.18,
    skills: ['estadistica-percentiles', 'estadistica-interpretacion', 'estadistica-conceptos']
  },
  {
    id: 'm1-prob-003-029',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P_{80} = \\text{posición } \\frac{80n}{100}',
    questionLatex: '\\text{Un profesor de educación física registra los tiempos en segundos de 20 estudiantes corriendo 100 metros. Los datos ordenados van desde 12 hasta 22 segundos. El percentil 80 (P80) es 19 segundos. ¿Cuántos estudiantes corrieron en 19 segundos o menos?}',
    options: ['4 estudiantes', '8 estudiantes', '16 estudiantes', '20 estudiantes'],
    correctAnswer: 2,
    explanation: 'P_{80} \\rightarrow 80\\% \\text{ de } 20 = 16 \\text{ estudiantes corrieron en 19s o menos}',
    difficulty: 'medium',
    difficultyScore: 0.40,
    skills: ['estadistica-percentiles', 'estadistica-interpretacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-prob-003-030',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'Q_3 = P_{75}',
    questionLatex: '\\text{Una estudiante de estadística necesita calcular el percentil 75 de un conjunto de datos para un informe. Su compañero le dice que ya calculó Q3 (tercer cuartil) y obtuvo 48. ¿Por qué este valor le es útil para calcular P75?}',
    options: ['No le sirve, son medidas diferentes', 'Porque Q3 = P75 (son equivalentes)', 'Porque P75 = Q3 + 25', 'Porque P75 = Q3 × 0.75'],
    correctAnswer: 1,
    explanation: 'Q_3 = P_{75} \\text{ ambos representan el valor que deja 75\\% de datos por debajo}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['estadistica-percentiles', 'estadistica-cuartiles', 'estadistica-conceptos']
  },
  {
    id: 'm1-prob-003-031',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P_{60} \\text{ interpolación}',
    questionLatex: '\\text{Un investigador médico analiza los niveles de colesterol de 10 pacientes ordenados: 140, 150, 160, 170, 180, 190, 200, 210, 220, 230. Necesita calcular el percentil 60 (P60). ¿Cuál es el valor del percentil 60?}',
    options: ['180', '184', '188', '190'],
    correctAnswer: 1,
    explanation: 'P_{60} = \\text{posición } 6.0 = 180 + 0.6(190-180) = 184',
    difficulty: 'hard',
    difficultyScore: 0.58,
    skills: ['estadistica-percentiles', 'estadistica-medidas-posicion', 'numeros-decimales']
  },
  {
    id: 'm1-prob-003-032',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'P_k \\rightarrow k\\% \\text{ por debajo}',
    questionLatex: '\\text{En un examen nacional, María obtuvo un puntaje que la ubicó en el percentil 95 (P95). Su hermano obtuvo un puntaje en el percentil 60 (P60). ¿Cuál de las siguientes afirmaciones es correcta sobre sus resultados?}',
    options: ['María superó al 95% de los estudiantes', 'María superó al 5% de los estudiantes', 'El hermano superó al 60% de los estudiantes', 'El hermano fue superado por el 40% de los estudiantes'],
    correctAnswer: 0,
    explanation: 'P_{95} \\rightarrow \\text{María superó al } 95\\% \\text{ de los estudiantes}',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['estadistica-percentiles', 'estadistica-interpretacion', 'estadistica-conceptos']
  },

  // C. Construcción de diagramas de caja
  {
    id: 'm1-prob-003-013',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Resumen de 5 números}',
    questionLatex: '\\text{Una estudiante de estadística aprende a construir diagramas de caja (box plots) en su clase. El profesor explica que este gráfico se basa en un "resumen de cinco números" que captura las características clave de la distribución de datos. ¿Cuáles son los cinco valores que se utilizan?}',
    options: ['Media, mediana, moda, rango, IQR', 'Mínimo, Q1, Q2 (mediana), Q3, máximo', 'P10, P25, P50, P75, P90', 'Mínimo, media, mediana, moda, máximo'],
    correctAnswer: 1,
    explanation: '\\text{Resumen de 5 números: Mínimo, } Q_1, Q_2, Q_3, \\text{ Máximo}',
    difficulty: 'easy',
    difficultyScore: 0.18,
    skills: ['estadistica-diagramas-caja', 'estadistica-conceptos']
  },
  {
    id: 'm1-prob-003-014',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Longitud} = Q_3 - Q_1',
    questionLatex: '\\text{Un analista de datos construye un diagrama de caja para un conjunto de 9 valores: 2, 4, 6, 8, 10, 12, 14, 16, 18. Ya calculó el resumen de cinco números: Mínimo=2, Q1=5, Q2=10, Q3=15, Máximo=18. Ahora necesita determinar la longitud física de la caja rectangular en el diagrama. ¿Cuál es la longitud de la caja?}',
    options: ['8 unidades', '10 unidades', '13 unidades', '16 unidades'],
    correctAnswer: 1,
    explanation: '\\text{Longitud de la caja} = IQR = Q_3 - Q_1 = 15 - 5 = 10',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['estadistica-diagramas-caja', 'estadistica-rango-intercuartilico', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-prob-003-015',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Línea central} = Q_2',
    questionLatex: '\\text{Durante una presentación de análisis de datos, un investigador muestra un diagrama de caja a su audiencia. Un asistente observa una línea vertical dibujada dentro de la caja rectangular y pregunta qué representa exactamente esa línea. ¿Qué representa la línea dentro de la caja?}',
    options: ['La media aritmética del conjunto', 'La mediana (Q2)', 'El rango de los datos', 'La moda del conjunto'],
    correctAnswer: 1,
    explanation: '\\text{Línea dentro de la caja} = Q_2 = \\text{mediana}',
    difficulty: 'easy',
    difficultyScore: 0.15,
    skills: ['estadistica-diagramas-caja', 'estadistica-conceptos']
  },
  {
    id: 'm1-prob-003-016',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Min}, Q_1, Q_2, Q_3, \\text{Max}',
    questionLatex: '\\text{Un bioestadístico analiza 7 mediciones de temperatura corporal en grados Celsius: 5, 10, 15, 20, 25, 30, 35. Necesita determinar el resumen de cinco números para crear un diagrama de caja completo. ¿Cuál es el resumen de cinco números correcto?}',
    options: ['Min=5, Q1=10, Q2=20, Q3=30, Max=35', 'Min=5, Q1=12.5, Q2=20, Q3=27.5, Max=35', 'Min=5, Q1=15, Q2=20, Q3=25, Max=35', 'Min=5, Q1=10, Q2=15, Q3=30, Max=35'],
    correctAnswer: 0,
    explanation: '\\text{Min}=5, Q_1=\\text{mediana de }\\{5,10,15\\}=10, Q_2=20, Q_3=\\text{mediana de }\\{25,30,35\\}=30, \\text{Max}=35',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['estadistica-diagramas-caja', 'estadistica-cuartiles', 'estadistica-mediana', 'numeros-decimales']
  },
  {
    id: 'm1-prob-003-017',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'Q_3 + 1.5 \\times IQR',
    questionLatex: '\\text{Un científico de datos utiliza la regla de Tukey para detectar valores atípicos (outliers) en un conjunto de datos. Esta regla establece que un valor es considerado atípico si está fuera del rango [Q1 - 1.5×IQR, Q3 + 1.5×IQR]. Para un conjunto donde Q1=20 y Q3=40, necesita encontrar el límite superior. ¿Cuál es el límite superior para outliers?}',
    options: ['50', '60', '70', '80'],
    correctAnswer: 2,
    explanation: 'IQR = 40 - 20 = 20; \\quad \\text{Límite superior} = 40 + 1.5(20) = 70',
    difficulty: 'medium',
    difficultyScore: 0.48,
    skills: ['estadistica-diagramas-caja', 'estadistica-outliers', 'estadistica-rango-intercuartilico', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-prob-003-018',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Bigotes: Q1-Min, Q3-Max}',
    questionLatex: '\\text{Un instructor de estadística muestra a sus estudiantes un diagrama de caja completo y señala las líneas que se extienden desde los bordes de la caja rectangular hacia los valores extremos. Explica que estas líneas se llaman "bigotes" (whiskers en inglés). ¿Desde dónde se extienden los bigotes?}',
    options: ['Desde Q1 al mínimo y desde Q3 al máximo', 'Desde la mediana hacia ambos extremos', 'Desde el centro de la caja hacia Q1 y Q3', 'Desde Q2 hacia Q1 y desde Q2 hacia Q3'],
    correctAnswer: 0,
    explanation: '\\text{Bigote izquierdo: } Q_1 \\to \\text{Mínimo}; \\quad \\text{Bigote derecho: } Q_3 \\to \\text{Máximo}',
    difficulty: 'easy',
    difficultyScore: 0.15,
    skills: ['estadistica-diagramas-caja', 'estadistica-conceptos']
  },
  {
    id: 'm1-prob-003-033',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Límite inferior} = Q_1 - 1.5 \\times IQR',
    questionLatex: '\\text{Un control de calidad analiza los pesos de productos y obtiene Q1=45g y Q3=55g. Para identificar productos defectuosos por peso anormalmente bajo, necesita calcular el límite inferior para outliers usando la regla de Tukey. ¿Cuál es el límite inferior?}',
    options: ['25g', '30g', '35g', '40g'],
    correctAnswer: 1,
    explanation: 'IQR = 55 - 45 = 10; \\quad \\text{Límite inferior} = 45 - 1.5(10) = 30',
    difficulty: 'medium',
    difficultyScore: 0.48,
    skills: ['estadistica-diagramas-caja', 'estadistica-outliers', 'estadistica-rango-intercuartilico', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-prob-003-034',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Min}, Q_1, Q_2, Q_3, \\text{Max}',
    questionLatex: '\\text{Una pediatra registra las estaturas en centímetros de 9 niños: 100, 105, 110, 115, 120, 125, 130, 135, 140. Necesita crear un diagrama de caja. ¿Cuál es el resumen de cinco números correcto?}',
    options: ['Min=100, Q1=107.5, Q2=120, Q3=132.5, Max=140', 'Min=100, Q1=110, Q2=120, Q3=130, Max=140', 'Min=100, Q1=105, Q2=120, Q3=135, Max=140', 'Min=100, Q1=115, Q2=120, Q3=125, Max=140'],
    correctAnswer: 0,
    explanation: '\\text{Min}=100, Q_1=\\frac{105+110}{2}=107.5, Q_2=120, Q_3=\\frac{130+135}{2}=132.5, \\text{Max}=140',
    difficulty: 'medium',
    difficultyScore: 0.45,
    skills: ['estadistica-diagramas-caja', 'estadistica-cuartiles', 'estadistica-mediana', 'numeros-decimales']
  },
  {
    id: 'm1-prob-003-035',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Bigote termina en dato real}',
    questionLatex: '\\text{Un estadístico construye un diagrama de caja para datos con Q1=30, Q3=50 y varios valores: 5, 10, 15, 20, 25, 30...50, 55, 60, 65, 100. Usando la regla de 1.5×IQR, ¿hasta dónde llega el bigote superior?}',
    options: ['Hasta 65', 'Hasta 70', 'Hasta 80', 'Hasta 100'],
    correctAnswer: 0,
    explanation: 'IQR=20; \\quad \\text{Límite}=50+30=80; \\quad \\text{Bigote llega a 65 (último dato } \\leq 80\\text{)}',
    difficulty: 'hard',
    difficultyScore: 0.62,
    skills: ['estadistica-diagramas-caja', 'estadistica-outliers', 'estadistica-rango-intercuartilico']
  },
  {
    id: 'm1-prob-003-036',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Outliers como puntos aislados}',
    questionLatex: '\\text{Al construir un diagrama de caja, un analista encuentra que hay 2 valores que están más allá del límite superior de 1.5×IQR. ¿Cómo debe representar estos valores en el diagrama de caja?}',
    options: ['Extender el bigote hasta incluirlos', 'Ignorarlos y no representarlos', 'Representarlos como puntos individuales separados del bigote', 'Incluirlos dentro de la caja'],
    correctAnswer: 2,
    explanation: '\\text{Outliers se representan como puntos individuales más allá de los bigotes}',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['estadistica-diagramas-caja', 'estadistica-outliers', 'estadistica-conceptos']
  },

  // D. Interpretación de diagramas de caja
  {
    id: 'm1-prob-003-019',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'Q_2 \\text{ cerca de } Q_1 \\rightarrow \\text{sesgo derecha}',
    questionLatex: '\\text{Una analista examina el diagrama de caja de los tiempos de respuesta de un servidor web y nota que la línea de la mediana (Q2) dentro de la caja está ubicada mucho más cerca del borde inferior (Q1) que del borde superior (Q3). ¿Qué indica esta configuración?}',
    options: ['Los datos son simétricos', 'Hay sesgo hacia la izquierda (negativo)', 'Hay sesgo hacia la derecha (positivo)', 'No se puede determinar el sesgo'],
    correctAnswer: 2,
    explanation: 'Q_2 \\text{ cerca de } Q_1 \\rightarrow \\text{más datos bajos, cola derecha} \\rightarrow \\text{sesgo positivo}',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['estadistica-diagramas-caja', 'estadistica-interpretacion', 'estadistica-asimetria']
  },
  {
    id: 'm1-prob-003-020',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'IQR \\text{ mayor} \\rightarrow \\text{más dispersión}',
    questionLatex: '\\text{Un investigador educativo compara el rendimiento en matemáticas de dos grupos de estudiantes mediante diagramas de caja. El Grupo A muestra un rango intercuartílico (IQR) de 10 puntos, mientras que el Grupo B tiene un IQR de 30 puntos. ¿Qué indica esta diferencia?}',
    options: ['El Grupo A tiene mayor dispersión en sus calificaciones', 'El Grupo B tiene mayor dispersión en sus calificaciones', 'Ambos grupos tienen igual dispersión', 'El Grupo A tiene mayor media'],
    correctAnswer: 1,
    explanation: 'IQR_B = 30 > IQR_A = 10 \\rightarrow \\text{Grupo B más disperso}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['estadistica-diagramas-caja', 'estadistica-interpretacion', 'estadistica-dispersion', 'estadistica-rango-intercuartilico']
  },
  {
    id: 'm1-prob-003-021',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Max} > Q_3 + 1.5 \\times IQR',
    questionLatex: '\\text{Un epidemiólogo analiza un diagrama de caja de los tiempos de recuperación de pacientes en días y observa estos valores: Mínimo=10, Q1=20, Q2=25, Q3=30, Máximo=80. El valor máximo parece estar inusualmente alejado del resto de los datos. ¿Qué se puede concluir sobre este conjunto de datos?}',
    options: ['Los datos son simétricos', 'Hay un posible valor atípico en el extremo superior', 'Hay un posible valor atípico en el extremo inferior', 'La distribución es uniforme'],
    correctAnswer: 1,
    explanation: 'IQR = 10; \\quad \\text{Límite} = 30 + 15 = 45; \\quad 80 > 45 \\rightarrow \\text{outlier}',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['estadistica-diagramas-caja', 'estadistica-interpretacion', 'estadistica-outliers', 'estadistica-rango-intercuartilico']
  },
  {
    id: 'm1-prob-003-022',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: 'Q_2 - Q_1 = Q_3 - Q_2',
    questionLatex: '\\text{Un matemático presenta a sus estudiantes un diagrama de caja perfectamente simétrico y les pide que identifiquen la relación matemática entre los tres cuartiles. ¿Qué relación existe en un diagrama simétrico?}',
    options: ['Q1 = Q2 = Q3 (todos son iguales)', 'Q2 - Q1 = Q3 - Q2 (mediana centrada)', 'Q3 = 2×Q1 (Q3 es el doble de Q1)', 'Q1 + Q3 = Q2 (suma de extremos)'],
    correctAnswer: 1,
    explanation: '\\text{Simetría: } Q_2 - Q_1 = Q_3 - Q_2 \\text{ (mediana centrada)}',
    difficulty: 'easy',
    difficultyScore: 0.32,
    skills: ['estadistica-diagramas-caja', 'estadistica-interpretacion', 'estadistica-simetria']
  },
  {
    id: 'm1-prob-003-023',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Caja} = 50\\% \\text{ central}',
    questionLatex: '\\text{Un profesor explica a su clase la interpretación de un diagrama de caja enfocándose en qué porción de los datos está representada por diferentes partes del gráfico. Un estudiante pregunta específicamente qué porcentaje de todos los datos se encuentra contenido dentro de la caja rectangular, es decir, entre Q1 y Q3. ¿Qué porcentaje está dentro de la caja?}',
    options: ['25% de los datos', '50% de los datos', '75% de los datos', '100% de los datos'],
    correctAnswer: 1,
    explanation: '\\text{Caja: de } P_{25} \\text{ a } P_{75} = 75\\% - 25\\% = 50\\% \\text{ de los datos}',
    difficulty: 'easy',
    difficultyScore: 0.18,
    skills: ['estadistica-diagramas-caja', 'estadistica-interpretacion', 'estadistica-conceptos']
  },
  {
    id: 'm1-prob-003-024',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Caja angosta} \\rightarrow IQR \\text{ pequeño}',
    questionLatex: '\\text{Una consultora compara los diagramas de caja de los salarios en dos empresas diferentes. Observa que la caja del diagrama de la Empresa X es notablemente más angosta que la caja del diagrama de la Empresa Y, aunque ambas tienen aproximadamente el mismo número de empleados. ¿Qué indica una caja más angosta?}',
    options: ['La empresa tiene menos empleados totales', 'La empresa tiene un salario medio más alto', 'La empresa tiene menor dispersión salarial en el 50% central', 'La empresa tiene más valores atípicos'],
    correctAnswer: 2,
    explanation: '\\text{Caja angosta} \\rightarrow IQR \\text{ pequeño} \\rightarrow \\text{menor dispersión central}',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['estadistica-diagramas-caja', 'estadistica-interpretacion', 'estadistica-dispersion', 'estadistica-rango-intercuartilico']
  },
  {
    id: 'm1-prob-003-037',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Comparar medianas de dos box plots}',
    questionLatex: '\\text{Un economista compara los ingresos mensuales de dos ciudades mediante diagramas de caja. La Ciudad A muestra Q2=\\$800,000 mientras que la Ciudad B tiene Q2=\\$650,000. ¿Qué se puede concluir sobre los ingresos típicos?}',
    options: ['La Ciudad A tiene mayor variabilidad de ingresos', 'La Ciudad B tiene ingresos más altos en promedio', 'La Ciudad A tiene un ingreso típico (mediana) más alto', 'Ambas ciudades tienen la misma distribución'],
    correctAnswer: 2,
    explanation: 'Q_2 \\text{ de A} = 800{,}000 > Q_2 \\text{ de B} = 650{,}000 \\rightarrow \\text{mediana A más alta}',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['estadistica-diagramas-caja', 'estadistica-interpretacion', 'estadistica-mediana']
  },
  {
    id: 'm1-prob-003-038',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Bigote largo} \\rightarrow \\text{datos dispersos}',
    questionLatex: '\\text{Al analizar un diagrama de caja de tiempos de espera en un banco, un gerente nota que el bigote derecho (desde Q3 hacia el máximo) es mucho más largo que el bigote izquierdo (desde Q1 hacia el mínimo). ¿Qué indica esta asimetría?}',
    options: ['Hay más clientes con tiempos bajos que altos', 'Los tiempos altos están más dispersos que los bajos', 'La mediana está cerca del máximo', 'Los datos son simétricos'],
    correctAnswer: 1,
    explanation: '\\text{Bigote derecho largo} \\rightarrow \\text{mayor dispersión en valores altos}',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['estadistica-diagramas-caja', 'estadistica-interpretacion', 'estadistica-asimetria']
  },
  {
    id: 'm1-prob-003-039',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Rango total} = \\text{Max} - \\text{Min}',
    questionLatex: '\\text{Un diagrama de caja muestra: Mínimo=15, Q1=25, Q2=35, Q3=45, Máximo=75. Un estudiante necesita calcular el rango total de los datos. ¿Cuál es el rango?}',
    options: ['20', '30', '50', '60'],
    correctAnswer: 3,
    explanation: '\\text{Rango} = \\text{Máximo} - \\text{Mínimo} = 75 - 15 = 60',
    difficulty: 'easy',
    difficultyScore: 0.20,
    skills: ['estadistica-diagramas-caja', 'estadistica-rango', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-prob-003-040',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    operacionBase: '\\text{Box plots paralelos para comparar}',
    questionLatex: '\\text{Un profesor muestra dos diagramas de caja paralelos de las calificaciones del mismo examen en dos secciones. La sección A tiene: IQR=15, Q2=70. La sección B tiene: IQR=5, Q2=75. ¿Cuál sección tuvo mejor rendimiento general y más homogéneo?}',
    options: ['Sección A: mejor rendimiento y más homogéneo', 'Sección B: mejor rendimiento y más homogéneo', 'Sección A: mejor rendimiento pero menos homogéneo', 'Sección B: peor rendimiento pero más homogéneo'],
    correctAnswer: 1,
    explanation: '\\text{B tiene } Q_2=75 > 70 \\text{ (mejor)} \\text{ y } IQR=5 < 15 \\text{ (más homogéneo)}',
    difficulty: 'medium',
    difficultyScore: 0.45,
    skills: ['estadistica-diagramas-caja', 'estadistica-interpretacion', 'estadistica-dispersion', 'estadistica-rango-intercuartilico']
  }
];
