import { Question } from '../../../types';

/**
 * M1-PROB-005: Reglas aditiva y multiplicativa de probabilidad
 * Chilean PAES Curriculum - Probability and Statistics Subsection 005
 *
 * This subsection covers:
 * - A: Regla aditiva para eventos mutuamente excluyentes
 * - B: Regla aditiva general
 * - C: Regla multiplicativa para eventos independientes
 * - D: Eventos complementarios
 *
 * Total: 40 questions
 */

export const m1Prob005Questions: Question[] = [
{
    id: 'm1-38',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Al lanzar una moneda dos veces, ¿cuál es la probabilidad de obtener dos caras?}',
    options: ['\\frac{1}{2}', '\\frac{1}{3}', '\\frac{1}{4}', '\\frac{2}{3}'],
    correctAnswer: 2,
    explanation: 'P(\\text{dos caras}) = \\frac{1}{4}',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['probabilidad-eventos-compuestos', 'probabilidad-basica', 'probabilidad-casos-favorables', 'numeros-fracciones']
  },
{
    id: 'm1-54',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Al lanzar un dado, ¿cuál es la probabilidad de obtener 1 o 2?}',
    options: ['\\frac{1}{6}', '\\frac{1}{3}', '\\frac{1}{2}', '\\frac{2}{3}'],
    correctAnswer: 1,
    explanation: 'P(1 \\text{ o } 2) = P(1) + P(2) = \\frac{1}{6} + \\frac{1}{6} = \\frac{2}{6} = \\frac{1}{3}',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['probabilidad-union', 'probabilidad-basica', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-55',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Al lanzar un dado, ¿cuál es la probabilidad de obtener un número menor que 3 o mayor que 4?}',
    options: ['\\frac{1}{2}', '\\frac{2}{3}', '\\frac{5}{6}', '\\frac{1}{3}'],
    correctAnswer: 1,
    explanation: 'P = \\frac{4}{6} = \\frac{2}{3}',
    difficulty: 'medium',
    difficultyScore: 0.32,
    skills: ['probabilidad-union', 'probabilidad-basica', 'numeros-fracciones']
  },
{
    id: 'm1-56',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{En una bolsa hay 3 bolas rojas, 4 azules y 5 verdes. ¿Cuál es la probabilidad de sacar roja o azul?}',
    options: ['\\frac{1}{4}', '\\frac{7}{12}', '\\frac{1}{2}', '\\frac{2}{3}'],
    correctAnswer: 1,
    explanation: 'P(\\text{roja o azul}) = \\frac{7}{12}',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['probabilidad-union', 'probabilidad-basica', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-57',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Si tienes 3 camisas y 4 pantalones, ¿de cuántas formas puedes vestirte?}',
    options: ['7', '12', '24', '81'],
    correctAnswer: 1,
    explanation: '3 \\times 4 = 12 \\text{ formas diferentes}',
    difficulty: 'easy',
    difficultyScore: 0.20,
    skills: ['probabilidad-conteo', 'probabilidad-principio-multiplicativo', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-58',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Un menú ofrece 2 entradas, 5 platos principales y 3 postres. ¿Cuántas combinaciones de menú se pueden formar?}',
    options: ['10', '15', '30', '60'],
    correctAnswer: 2,
    explanation: '2 \\times 5 \\times 3 = 30 \\text{ combinaciones}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['probabilidad-conteo', 'probabilidad-principio-multiplicativo', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-59',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{¿Cuántos números de 3 dígitos se pueden formar con 1, 2, 3, 4, 5 con repetición?}',
    options: ['15', '60', '125', '243'],
    correctAnswer: 2,
    explanation: '5 \\times 5 \\times 5 = 125 \\text{ números}',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['probabilidad-conteo', 'probabilidad-principio-multiplicativo', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-60',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{¿De cuántas formas se pueden ordenar 4 personas en una fila?}',
    options: ['4', '8', '16', '24'],
    correctAnswer: 3,
    explanation: '4! = 4 \\times 3 \\times 2 \\times 1 = 24',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['probabilidad-permutaciones', 'probabilidad-conteo', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-61',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{¿De cuántas maneras se pueden organizar las letras de "SOL"?}',
    options: ['3', '6', '9', '27'],
    correctAnswer: 1,
    explanation: '3! = 3 \\times 2 \\times 1 = 6',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['probabilidad-permutaciones', 'probabilidad-conteo', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-62',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Cinco amigos van al cine. ¿De cuántas formas pueden sentarse en una fila de 5 asientos?}',
    options: ['25', '60', '120', '625'],
    correctAnswer: 2,
    explanation: '5! = 5 \\times 4 \\times 3 \\times 2 \\times 1 = 120',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['probabilidad-permutaciones', 'probabilidad-conteo', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-63',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{¿De cuántas formas se pueden elegir presidente y vicepresidente de 5 personas?}',
    options: ['5', '10', '20', '25'],
    correctAnswer: 2,
    explanation: '5 \\times 4 = 20 \\text{ formas}',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['probabilidad-variaciones', 'probabilidad-conteo', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-64',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{¿Cuántos números de 2 dígitos diferentes se pueden formar con 1, 2, 3, 4, 5?}',
    options: ['10', '20', '25', '30'],
    correctAnswer: 1,
    explanation: '5 \\times 4 = 20 \\text{ números}',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['probabilidad-variaciones', 'probabilidad-conteo', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-65',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{En una carrera con 8 participantes, ¿de cuántas formas pueden llegar los 3 primeros?}',
    options: ['24', '56', '168', '336'],
    correctAnswer: 3,
    explanation: '8 \\times 7 \\times 6 = 336 \\text{ formas}',
    difficulty: 'medium',
    difficultyScore: 0.35,
    skills: ['probabilidad-variaciones', 'probabilidad-conteo', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-66',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Se lanzan dos dados. ¿Cuál es la probabilidad de que la suma sea 7?}',
    options: ['\\frac{1}{12}', '\\frac{1}{9}', '\\frac{1}{6}', '\\frac{5}{36}'],
    correctAnswer: 2,
    explanation: 'P(\\text{suma} = 7) = \\frac{6}{36} = \\frac{1}{6}',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['probabilidad-eventos-compuestos', 'probabilidad-conteo', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-67',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Se lanzan dos monedas. ¿Cuál es la probabilidad de obtener exactamente una cara?}',
    options: ['\\frac{1}{4}', '\\frac{1}{3}', '\\frac{1}{2}', '\\frac{3}{4}'],
    correctAnswer: 2,
    explanation: 'P = \\frac{2}{4} = \\frac{1}{2}',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['probabilidad-eventos-compuestos', 'probabilidad-conteo', 'numeros-fracciones']
  },
{
    id: 'm1-68',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{De una baraja de 52 cartas, ¿cuál es la probabilidad de que sea un as o un rey?}',
    options: ['\\frac{1}{13}', '\\frac{2}{13}', '\\frac{1}{6}', '\\frac{1}{7}'],
    correctAnswer: 1,
    explanation: 'P = \\frac{4 + 4}{52} = \\frac{8}{52} = \\frac{2}{13}',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['probabilidad-union', 'probabilidad-basica', 'numeros-fracciones']
  },
{
    id: 'm1-69',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Se lanza una moneda tres veces. ¿Cuál es la probabilidad de obtener exactamente dos caras?}',
    options: ['\\frac{1}{8}', '\\frac{1}{4}', '\\frac{3}{8}', '\\frac{1}{2}'],
    correctAnswer: 2,
    explanation: 'P = \\frac{3}{8}',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['probabilidad-eventos-compuestos', 'probabilidad-conteo', 'numeros-fracciones']
  },
{
    id: 'm1-70',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Una familia tiene 3 hijos. ¿Cuál es la probabilidad de que los 3 sean del mismo sexo?}',
    options: ['\\frac{1}{8}', '\\frac{1}{4}', '\\frac{3}{8}', '\\frac{1}{2}'],
    correctAnswer: 1,
    explanation: 'P = \\frac{2}{8} = \\frac{1}{4}',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['probabilidad-eventos-compuestos', 'probabilidad-conteo', 'numeros-fracciones']
  },
{
    id: 'm1-71',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Se lanza un dado dos veces. ¿Cuál es la probabilidad de obtener al menos un 6?}',
    options: ['\\frac{1}{6}', '\\frac{11}{36}', '\\frac{1}{3}', '\\frac{5}{12}'],
    correctAnswer: 1,
    explanation: 'P(\\text{al menos un 6}) = 1 - P(\\text{ningún 6}) = 1 - \\frac{5}{6} \\times \\frac{5}{6} = 1 - \\frac{25}{36} = \\frac{11}{36}',
    difficulty: 'medium',
    difficultyScore: 0.48,
    skills: ['probabilidad-complemento', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-72',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Se lanza una moneda y un dado. ¿Cuál es la probabilidad de obtener cara y 5?}',
    options: ['\\frac{1}{2}', '\\frac{1}{6}', '\\frac{1}{8}', '\\frac{1}{12}'],
    correctAnswer: 3,
    explanation: 'P(\\text{cara y 5}) = P(\\text{cara}) \\times P(5) = \\frac{1}{2} \\times \\frac{1}{6} = \\frac{1}{12}',
    difficulty: 'medium',
    difficultyScore: 0.32,
    skills: ['probabilidad-eventos-independientes', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-73',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Se extraen dos cartas CON reposición. ¿Cuál es la probabilidad de obtener dos ases?}',
    options: ['\\frac{1}{169}', '\\frac{1}{221}', '\\frac{4}{663}', '\\frac{1}{13}'],
    correctAnswer: 0,
    explanation: 'P = \\frac{4}{52} \\times \\frac{4}{52} = \\frac{1}{13} \\times \\frac{1}{13} = \\frac{1}{169}',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['probabilidad-eventos-independientes', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-74',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Ana y José lanzan una moneda cada uno. ¿Cuál es la probabilidad de que ambos obtengan cara?}',
    options: ['\\frac{1}{2}', '\\frac{1}{3}', '\\frac{1}{4}', '\\frac{2}{3}'],
    correctAnswer: 2,
    explanation: 'P = \\frac{1}{2} \\times \\frac{1}{2} = \\frac{1}{4}',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['probabilidad-eventos-independientes', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-75',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{En una caja hay 5 rojas y 3 azules. Se extraen 2 SIN reposición. P(roja y luego azul)?}',
    options: ['\\frac{15}{56}', '\\frac{5}{28}', '\\frac{15}{64}', '\\frac{3}{14}'],
    correctAnswer: 0,
    explanation: 'P = \\frac{5}{8} \\times \\frac{3}{7} = \\frac{15}{56}',
    difficulty: 'medium',
    difficultyScore: 0.45,
    skills: ['probabilidad-eventos-dependientes', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-76',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Se extraen dos cartas SIN reposición. ¿Cuál es la probabilidad de que ambas sean corazones?}',
    options: ['\\frac{1}{17}', '\\frac{1}{16}', '\\frac{13}{204}', '\\frac{1}{20}'],
    correctAnswer: 0,
    explanation: 'P = \\frac{13}{52} \\times \\frac{12}{51} = \\frac{1}{4} \\times \\frac{12}{51} = \\frac{12}{204} = \\frac{1}{17}',
    difficulty: 'medium',
    difficultyScore: 0.48,
    skills: ['probabilidad-eventos-dependientes', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-77',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{En una bolsa hay 4 canicas verdes y 2 canicas amarillas. Una niña saca dos canicas una después de otra sin devolver la primera a la bolsa. Para ganar un premio en la feria del colegio, necesita sacar ambas canicas de color verde. ¿Cuál es la probabilidad de que la niña gane el premio?}',
    options: ['\\frac{1}{5}', '\\frac{2}{5}', '\\frac{4}{9}', '\\frac{2}{15}'],
    correctAnswer: 1,
    explanation: 'P = \\frac{4}{6} \\times \\frac{3}{5} = \\frac{12}{30} = \\frac{2}{5}',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['probabilidad-eventos-dependientes', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-78',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{En una universidad hay 10 hombres y 15 mujeres en el primer año. De ellos, 8 hombres y 6 mujeres estudian ingeniería. Si se selecciona al azar un estudiante de ingeniería para representar a la carrera en una feria vocacional, ¿cuál es la probabilidad de que el seleccionado sea mujer?}',
    options: ['\\frac{3}{7}', '\\frac{2}{5}', '\\frac{6}{25}', '\\frac{1}{2}'],
    correctAnswer: 0,
    explanation: 'P(\\text{mujer}|\\text{ingeniería}) = \\frac{6}{8+6} = \\frac{6}{14} = \\frac{3}{7}',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['probabilidad-condicional', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-79',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{En un juego de mesa, un jugador lanza un dado de seis caras. Las reglas indican que si obtiene un número par, puede avanzar casillas adicionales según el valor obtenido. El jugador quiere saber, dado que ya obtuvo un número par, cuál es la probabilidad de que ese número sea mayor que 4. ¿Cuál es esta probabilidad condicional?}',
    options: ['\\frac{1}{6}', '\\frac{1}{3}', '\\frac{1}{2}', '\\frac{2}{3}'],
    correctAnswer: 1,
    explanation: 'P(>4|\\text{par}) = \\frac{1}{3} \\text{ ya que solo el 6 es par y mayor que 4, de los 3 pares posibles (2,4,6)}',
    difficulty: 'medium',
    difficultyScore: 0.35,
    skills: ['probabilidad-condicional', 'numeros-fracciones']
  },
{
    id: 'm1-81',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Una encuesta sobre hábitos digitales entrevistó a 100 personas: 40 hombres y 60 mujeres. De los hombres, 25 usan redes sociales diariamente, y de las mujeres, 35 las usan diariamente. Si se selecciona una persona al azar de este grupo, ¿cuál es la probabilidad de que use redes sociales diariamente?}',
    options: ['0.4', '0.5', '0.6', '0.75'],
    correctAnswer: 2,
    explanation: 'P = \\frac{25 + 35}{100} = \\frac{60}{100} = 0.6',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['probabilidad-tablas', 'estadistica-tablas', 'numeros-fracciones', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-82',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{En un curso de 50 estudiantes se realizaron exámenes de matemáticas y física. Los resultados mostraron que 30 estudiantes aprobaron matemáticas, 25 aprobaron física y 15 aprobaron ambas asignaturas. El profesor quiere identificar cuántos estudiantes necesitan refuerzo porque no aprobaron ninguna de las dos materias. ¿Cuántos estudiantes no aprobaron ninguna asignatura?}',
    options: ['5', '10', '15', '20'],
    correctAnswer: 1,
    explanation: '\\text{Al menos una} = 30 + 25 - 15 = 40 \\rightarrow \\text{Ninguna} = 50 - 40 = 10',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['probabilidad-tablas', 'probabilidad-union', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-83',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{En un colegio con 200 estudiantes se realizó una encuesta sobre actividades extracurriculares. Los resultados indicaron que 120 estudiantes practican deportes, 80 participan en actividades musicales y 40 hacen ambas actividades. El coordinador necesita saber cuántos estudiantes no participan en ninguna actividad para promover nuevos talleres. ¿Cuántos estudiantes no participan en ninguna actividad?}',
    options: ['20', '40', '60', '80'],
    correctAnswer: 1,
    explanation: '120 + 80 - 40 = 160 \\rightarrow \\text{Ninguna} = 200 - 160 = 40',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['probabilidad-tablas', 'probabilidad-union', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-84',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Un grupo de amigos juega un juego donde lanzan una moneda cuatro veces consecutivas y registran la secuencia de resultados (cara o sello). Para planificar las reglas del juego, necesitan saber cuántas secuencias diferentes son posibles. Por ejemplo, CCSS y CSCS son dos secuencias distintas. ¿Cuántos resultados posibles existen al lanzar una moneda 4 veces?}',
    options: ['4', '8', '16', '32'],
    correctAnswer: 2,
    explanation: '2^4 = 16 \\text{ resultados posibles (cada lanzamiento tiene 2 opciones)}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['probabilidad-espacio-muestral', 'probabilidad-conteo', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-85',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{En un casino se juega un juego donde se lanzan tres dados de seis caras simultáneamente. El jugador gana si la suma de los tres dados supera cierto valor. Un matemático quiere calcular las probabilidades exactas del juego y para eso necesita determinar primero cuántos resultados diferentes son posibles. ¿Cuál es el tamaño del espacio muestral al lanzar tres dados?}',
    options: ['18', '36', '108', '216'],
    correctAnswer: 3,
    explanation: '6^3 = 6 \\times 6 \\times 6 = 216 \\text{ (cada dado tiene 6 resultados posibles)}',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['probabilidad-espacio-muestral', 'probabilidad-conteo', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
{
    id: 'm1-86',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{En un juego de apuestas, un jugador lanza cuatro monedas simultáneamente. Para ganar el premio, necesita obtener al menos una cara entre las cuatro monedas (es decir, gana a menos que todas sean sello). El jugador quiere calcular qué tan probable es ganar antes de decidir si participa. ¿Cuál es la probabilidad de obtener al menos una cara al lanzar 4 monedas?}',
    options: ['\\frac{15}{16}', '\\frac{1}{2}', '\\frac{7}{8}', '\\frac{3}{4}'],
    correctAnswer: 0,
    explanation: 'P = 1 - P(\\text{todas sellos}) = 1 - \\left(\\frac{1}{2}\\right)^4 = 1 - \\frac{1}{16} = \\frac{15}{16}',
    difficulty: 'medium',
    difficultyScore: 0.45,
    skills: ['probabilidad-complemento', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  // ========================================
  // NUEVAS PREGUNTAS PARA COMPLETAR SUBSECCIONES
  // ========================================
  // A. Regla aditiva para eventos mutuamente excluyentes
  {
    id: 'm1-prob-005-001',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Al lanzar un dado, ¿cuál es la probabilidad de obtener un 1, 3 o 5?}',
    options: ['\\frac{1}{6}', '\\frac{1}{3}', '\\frac{1}{2}', '\\frac{2}{3}'],
    correctAnswer: 2,
    explanation: 'P(1 \\cup 3 \\cup 5) = P(1) + P(3) + P(5) = \\frac{1}{6} + \\frac{1}{6} + \\frac{1}{6} = \\frac{3}{6} = \\frac{1}{2}',
    difficulty: 'easy',
    difficultyScore: 0.22,
    skills: ['probabilidad-union', 'probabilidad-eventos-excluyentes', 'numeros-fracciones']
  },
  {
    id: 'm1-prob-005-002',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Una urna tiene 4 bolas rojas, 3 azules y 2 verdes. ¿Cuál es la probabilidad de sacar una bola roja o verde?}',
    options: ['\\frac{4}{9}', '\\frac{2}{3}', '\\frac{6}{9}', '\\frac{5}{9}'],
    correctAnswer: 1,
    explanation: 'P(R \\cup V) = P(R) + P(V) = \\frac{4}{9} + \\frac{2}{9} = \\frac{6}{9} = \\frac{2}{3}',
    difficulty: 'easy',
    difficultyScore: 0.25,
    skills: ['probabilidad-union', 'probabilidad-eventos-excluyentes', 'numeros-fracciones']
  },
  // B. Regla aditiva general
  {
    id: 'm1-prob-005-003',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{En una baraja de 52 cartas, ¿cuál es la probabilidad de sacar una carta roja o una figura (J, Q, K)?}',
    options: ['\\frac{26}{52}', '\\frac{32}{52}', '\\frac{38}{52}', '\\frac{8}{13}'],
    correctAnswer: 3,
    explanation: 'P(R \\cup F) = P(R) + P(F) - P(R \\cap F) = \\frac{26}{52} + \\frac{12}{52} - \\frac{6}{52} = \\frac{32}{52} = \\frac{8}{13}',
    difficulty: 'medium',
    difficultyScore: 0.48,
    skills: ['probabilidad-union', 'probabilidad-regla-aditiva', 'numeros-fracciones']
  },
  {
    id: 'm1-prob-005-004',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Al lanzar un dado, ¿cuál es la probabilidad de obtener un número par o un número menor que 4?}',
    options: ['\\frac{2}{3}', '\\frac{5}{6}', '\\frac{1}{2}', '\\frac{3}{4}'],
    correctAnswer: 0,
    explanation: 'P(\\text{par} \\cup <4) = P(\\text{par}) + P(<4) - P(\\text{par} \\cap <4) = \\frac{3}{6} + \\frac{3}{6} - \\frac{2}{6} = \\frac{4}{6} = \\frac{2}{3}',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['probabilidad-union', 'probabilidad-regla-aditiva', 'numeros-fracciones']
  },
  // C. Regla multiplicativa para eventos independientes
  {
    id: 'm1-prob-005-005',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Se lanzan dos dados independientemente. ¿Cuál es la probabilidad de obtener dos números pares?}',
    options: ['\\frac{1}{4}', '\\frac{1}{3}', '\\frac{1}{2}', '\\frac{1}{6}'],
    correctAnswer: 0,
    explanation: 'P(\\text{par}_1 \\cap \\text{par}_2) = P(\\text{par}) \\times P(\\text{par}) = \\frac{1}{2} \\times \\frac{1}{2} = \\frac{1}{4}',
    difficulty: 'easy',
    difficultyScore: 0.28,
    skills: ['probabilidad-eventos-independientes', 'probabilidad-regla-multiplicativa', 'numeros-fracciones']
  },
  {
    id: 'm1-prob-005-006',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Una máquina tiene probabilidad 0.9 de funcionar correctamente. Si hay 3 máquinas independientes, ¿cuál es la probabilidad de que todas funcionen?}',
    options: ['0.729', '0.810', '0.900', '0.270'],
    correctAnswer: 0,
    explanation: 'P = 0.9 \\times 0.9 \\times 0.9 = 0.9^3 = 0.729',
    difficulty: 'medium',
    difficultyScore: 0.38,
    skills: ['probabilidad-eventos-independientes', 'probabilidad-regla-multiplicativa', 'numeros-decimales']
  },
  // D. Eventos complementarios
  {
    id: 'm1-prob-005-007',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Se lanzan 5 monedas. ¿Cuál es la probabilidad de obtener al menos una cara?}',
    options: ['\\frac{1}{32}', '\\frac{15}{16}', '\\frac{31}{32}', '\\frac{5}{32}'],
    correctAnswer: 2,
    explanation: 'P(\\text{al menos 1 cara}) = 1 - P(\\text{todas sellos}) = 1 - \\left(\\frac{1}{2}\\right)^5 = 1 - \\frac{1}{32} = \\frac{31}{32}',
    difficulty: 'medium',
    difficultyScore: 0.42,
    skills: ['probabilidad-complemento', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-potencias']
  }
];
