import { Question } from '../../../types';

export const m1ProbabilidadMedidasPosicionQuestions: Question[] = [
  {
    id: 'm1-117',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Datos: 15, 23, 18, 32, 27, 19. ¿Rango?}',
    options: ['15', '17', '19', '32'],
    correctAnswer: 1,
    explanation: 'Rango = máximo - mínimo:',
    explanationLatex: '\\text{Rango} = 32 - 15 = 17',
    difficulty: 'easy',
    skills: ['estadistica-rango', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-118',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Si el rango es 0, ¿qué significa?}',
    options: ['Todos los datos son 0', 'Todos los datos son iguales', 'No hay datos', 'Hay un error'],
    correctAnswer: 1,
    explanation: 'Rango 0 implica que máximo = mínimo:',
    explanationLatex: '\\text{Todos los datos tienen el mismo valor}',
    difficulty: 'easy',
    skills: ['estadistica-rango', 'estadistica-conceptos']
  },
  {
    id: 'm1-119',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{A = \\{10, 15, 20\\}, B = \\{5, 15, 30\\}. ¿Mayor dispersión?}',
    options: ['A', 'B', 'Igual dispersión', 'No se puede determinar'],
    correctAnswer: 1,
    explanation: 'Comparamos rangos:',
    explanationLatex: '\\text{Rango}_A = 10, \\quad \\text{Rango}_B = 25',
    difficulty: 'medium',
    skills: ['estadistica-rango', 'estadistica-dispersion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-120',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Media = 50, dato = 55. ¿Desviación?}',
    options: ['-5', '5', '55', '105'],
    correctAnswer: 1,
    explanation: 'Desviación = dato - media:',
    explanationLatex: '55 - 50 = 5',
    difficulty: 'easy',
    skills: ['estadistica-desviacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-121',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Datos: 8, 10, 12. Media = 10. ¿Suma de desviaciones?}',
    options: ['-2', '0', '2', '6'],
    correctAnswer: 1,
    explanation: 'La suma de desviaciones respecto a la media siempre es 0:',
    explanationLatex: '(8-10) + (10-10) + (12-10) = -2 + 0 + 2 = 0',
    difficulty: 'medium',
    skills: ['estadistica-desviacion', 'estadistica-media', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-122',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Si todos los datos < media, ¿signo de las desviaciones?}',
    options: ['Todas positivas', 'Todas negativas', 'Algunas positivas, otras negativas', 'No es posible'],
    correctAnswer: 3,
    explanation: 'Es imposible que todos estén bajo la media:',
    explanationLatex: '\\text{La media se calcula con todos los datos, al menos uno debe ser } \\geq \\text{ media}',
    difficulty: 'hard',
    skills: ['estadistica-desviacion', 'estadistica-media', 'estadistica-conceptos']
  },
  {
    id: 'm1-123',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Datos: 5, 5, 5, 5. ¿Varianza?}',
    options: ['0', '5', '10', '25'],
    correctAnswer: 0,
    explanation: 'Sin variación en los datos, la varianza es 0:',
    explanationLatex: '\\text{Todas las desviaciones son 0} \\rightarrow \\sigma^2 = 0',
    difficulty: 'easy',
    skills: ['estadistica-varianza', 'estadistica-dispersion']
  },
  {
    id: 'm1-124',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{¿Qué mide la varianza?}',
    options: ['El centro de los datos', 'La dispersión de los datos', 'El valor más frecuente', 'El valor medio'],
    correctAnswer: 1,
    explanation: 'La varianza mide cuánto se dispersan los datos respecto a la media:',
    explanationLatex: '\\text{Mayor varianza} \\rightarrow \\text{Mayor dispersión}',
    difficulty: 'easy',
    skills: ['estadistica-varianza', 'estadistica-dispersion', 'estadistica-conceptos']
  },
  {
    id: 'm1-125',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Misma media, diferentes varianzas. ¿Qué significa?}',
    options: ['Tienen la misma dispersión', 'Tienen diferente dispersión', 'Tienen los mismos datos', 'No es posible'],
    correctAnswer: 1,
    explanation: 'Igual media pero diferente varianza indica:',
    explanationLatex: '\\text{Los datos están más o menos concentrados alrededor de la media}',
    difficulty: 'medium',
    skills: ['estadistica-varianza', 'estadistica-media', 'estadistica-dispersion', 'estadistica-conceptos']
  },
  {
    id: 'm1-126',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Si varianza = 16, ¿desviación estándar?}',
    options: ['2', '4', '8', '256'],
    correctAnswer: 1,
    explanation: 'La desviación estándar es la raíz cuadrada de la varianza:',
    explanationLatex: '\\sigma = \\sqrt{16} = 4',
    difficulty: 'easy',
    skills: ['estadistica-desviacion-estandar', 'estadistica-varianza', 'numeros-raices', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-127',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{¿Por qué desviación estándar > varianza?}',
    options: ['Es más fácil de calcular', 'Tiene las mismas unidades que los datos', 'Siempre es mayor', 'No hay diferencia'],
    correctAnswer: 1,
    explanation: 'La desviación estándar está en las mismas unidades que los datos:',
    explanationLatex: '\\text{Si datos en cm, } \\sigma \\text{ en cm, pero } \\sigma^2 \\text{ en cm}^2',
    difficulty: 'medium',
    skills: ['estadistica-desviacion-estandar', 'estadistica-varianza', 'estadistica-conceptos']
  },
  {
    id: 'm1-128',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Si } \\sigma = 0, \\text{ ¿qué concluir?}',
    options: ['Los datos son negativos', 'Todos los datos son iguales', 'La media es 0', 'No hay datos'],
    correctAnswer: 1,
    explanation: 'Desviación estándar 0 significa sin variación:',
    explanationLatex: '\\sigma = 0 \\rightarrow \\text{Todos los datos son iguales}',
    difficulty: 'easy',
    skills: ['estadistica-desviacion-estandar', 'estadistica-conceptos']
  },
  {
    id: 'm1-129',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Media = 80 ambos. A: } \\sigma=5, \\text{ B: } \\sigma=15. \\text{ ¿Más consistente?}',
    options: ['Equipo A', 'Equipo B', 'Igual consistencia', 'No se puede determinar'],
    correctAnswer: 0,
    explanation: 'Menor desviación estándar indica mayor consistencia:',
    explanationLatex: '\\sigma_A < \\sigma_B \\rightarrow \\text{Equipo A más consistente}',
    difficulty: 'medium',
    skills: ['estadistica-desviacion-estandar', 'estadistica-interpretacion', 'estadistica-conceptos']
  },
  {
    id: 'm1-130',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Si datos } \\times 2, \\text{ ¿qué pasa con el rango?}',
    options: ['Se mantiene', 'Se duplica', 'Se cuadruplica', 'Depende de los datos'],
    correctAnswer: 1,
    explanation: 'El rango también se multiplica:',
    explanationLatex: '\\text{Rango nuevo} = 2 \\times \\text{máx} - 2 \\times \\text{mín} = 2(\\text{máx} - \\text{mín}) = 2 \\times \\text{Rango viejo}',
    difficulty: 'hard',
    skills: ['estadistica-rango', 'estadistica-conceptos', 'algebra-propiedades']
  },
  {
    id: 'm1-131',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    questionLatex: '\\text{Edades: 10, 12, 14, 16 años. En meses, ¿qué pasa con } \\sigma?',
    options: ['Se mantiene', 'Se multiplica por 12', 'Se divide por 12', 'Se multiplica por 144'],
    correctAnswer: 1,
    explanation: 'Al cambiar de unidades multiplicando por 12:',
    explanationLatex: '\\sigma_{\\text{meses}} = 12 \\times \\sigma_{\\text{años}}',
    difficulty: 'hard',
    skills: ['estadistica-desviacion-estandar', 'estadistica-conceptos', 'algebra-propiedades']
  }
];
