import { Question } from '../../../types';

export const m1GeometriaPitagorasQuestions: Question[] = [
  {
    id: 'm1-3',
    level: 'M1',
    topic: 'Geometría',
    subject: 'geometría',
    question: 'Un triángulo rectángulo tiene catetos de 3 cm y 4 cm. ¿Cuál es la longitud de su hipotenusa?',
    questionLatex: '\\text{Un triángulo rectángulo tiene catetos de 3 cm y 4 cm. ¿Cuál es la longitud de su hipotenusa?}',
    options: ['5 cm', '6 cm', '7 cm', '8 cm'],
    correctAnswer: 0,
    explanation: 'Por el teorema de Pitágoras:',
    explanationLatex: 'h^2 = 3^2 + 4^2 = 9 + 16 = 25 \\text{, entonces } h = \\sqrt{25} = 5 \\text{ cm}',
    difficulty: 'easy',
    skills: ['geometria-triangulos', 'geometria-pitagoras', 'numeros-raices', 'numeros-potencias']
  },
  {
    id: 'm1-20',
    level: 'M1',
    topic: 'Geometría',
    subject: 'geometría',
    question: 'La distancia entre los puntos $A(1, 2)$ y $B(4, 6)$ es:',
    questionLatex: '\\text{La distancia entre los puntos } A(1, 2) \\text{ y } B(4, 6) \\text{ es:}',
    options: ['3', '4', '5', '7'],
    correctAnswer: 2,
    explanation: 'Usamos la fórmula de distancia:',
    explanationLatex: 'd = \\sqrt{(4-1)^2 + (6-2)^2} = \\sqrt{9 + 16} = \\sqrt{25} = 5',
    difficulty: 'medium',
    skills: ['geometria-plano-cartesiano', 'geometria-distancia', 'geometria-pitagoras', 'numeros-raices', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-geo-visual-1',
    level: 'M1',
    topic: 'Geometría',
    subject: 'geometría',
    question: 'En el siguiente triángulo rectángulo, si los catetos miden 6 cm y 8 cm, ¿cuánto mide la hipotenusa?',
    questionLatex: '\\text{En el siguiente triángulo rectángulo, si los catetos miden 6 cm y 8 cm, ¿cuánto mide la hipotenusa?}',
    options: ['9 cm', '10 cm', '12 cm', '14 cm'],
    correctAnswer: 1,
    explanation: 'Usando el teorema de Pitágoras:',
    explanationLatex: 'c^2 = a^2 + b^2 = 6^2 + 8^2 = 36 + 64 = 100 \\quad \\Rightarrow \\quad c = \\sqrt{100} = 10 \\text{ cm}',
    difficulty: 'easy',
    skills: ['geometria-triangulos', 'geometria-pitagoras', 'numeros-raices', 'numeros-potencias', 'numeros-operaciones-basicas'],
    visualData: {
      type: 'geometry',
      data: [
        {
          type: 'triangle',
          points: [
            { x: 50, y: 200, label: 'A' },
            { x: 200, y: 200, label: 'B' },
            { x: 50, y: 80, label: 'C' }
          ],
          labels: {
            sides: ['8 cm', '10 cm', '6 cm']
          },
          dimensions: {
            showSides: true
          }
        }
      ]
    }
  },
  {
    id: 'm1-202',
    level: 'M1',
    topic: 'Geometría',
    subject: 'geometría',
    question: 'Un cuadrado está inscrito en un círculo de radio 5 cm. ¿Cuál es el lado del cuadrado aproximadamente?',
    questionLatex: '\\text{Cuadrado inscrito en círculo de radio 5 cm. Lado aprox.?}',
    options: ['5 cm', '7.07 cm', '10 cm', '14.14 cm'],
    correctAnswer: 1,
    explanation: 'La diagonal del cuadrado es el diámetro del círculo (10 cm):',
    explanationLatex: 'l = \\frac{10}{\\sqrt{2}} \\approx 7.07 \\text{ cm}',
    difficulty: 'hard',
    skills: ['geometria-circulos', 'geometria-cuadrados', 'geometria-figuras-inscritas', 'numeros-raices', 'geometria-pitagoras']
  },
  {
    id: 'm1-207',
    level: 'M1',
    topic: 'Geometría',
    subject: 'geometría',
    question: 'Un triángulo rectángulo tiene catetos de 5 cm y 12 cm. ¿Cuál es la hipotenusa?',
    questionLatex: '\\text{Catetos 5 cm y 12 cm. Hipotenusa?}',
    options: ['10 cm', '11 cm', '13 cm', '17 cm'],
    correctAnswer: 2,
    explanation: 'Aplicamos el teorema de Pitágoras:',
    explanationLatex: 'c^2 = 5^2 + 12^2 = 25 + 144 = 169 \\rightarrow c = \\sqrt{169} = 13 \\text{ cm}',
    difficulty: 'easy',
    skills: ['geometria-triangulos', 'geometria-pitagoras', 'geometria-triangulo-rectangulo', 'numeros-raices', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-208',
    level: 'M1',
    topic: 'Geometría',
    subject: 'geometría',
    question: 'En un triángulo rectángulo, la hipotenusa mide 10 cm y un cateto mide 6 cm. ¿Cuánto mide el otro cateto?',
    questionLatex: '\\text{Hipotenusa 10 cm, cateto 6 cm. Otro cateto?}',
    options: ['4 cm', '6 cm', '8 cm', '12 cm'],
    correctAnswer: 2,
    explanation: 'Despejamos el cateto desconocido:',
    explanationLatex: 'b^2 = 10^2 - 6^2 = 100 - 36 = 64 \\rightarrow b = \\sqrt{64} = 8 \\text{ cm}',
    difficulty: 'easy',
    skills: ['geometria-triangulos', 'geometria-pitagoras', 'geometria-triangulo-rectangulo', 'numeros-raices', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-209',
    level: 'M1',
    topic: 'Geometría',
    subject: 'geometría',
    question: 'Un triángulo tiene lados 7 cm, 24 cm y 25 cm. ¿Es un triángulo rectángulo?',
    questionLatex: '\\text{Lados 7 cm, 24 cm, 25 cm. ¿Es rectángulo?}',
    options: ['Sí', 'No', 'Falta información', 'Solo si es isósceles'],
    correctAnswer: 0,
    explanation: 'Verificamos el teorema de Pitágoras:',
    explanationLatex: '7^2 + 24^2 = 49 + 576 = 625 = 25^2 \\quad \\checkmark',
    difficulty: 'medium',
    skills: ['geometria-triangulos', 'geometria-pitagoras', 'geometria-triangulo-rectangulo', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-210',
    level: 'M1',
    topic: 'Geometría',
    subject: 'geometría',
    question: 'La diagonal de un rectángulo de 9 cm de largo y 12 cm de ancho mide:',
    questionLatex: '\\text{Diagonal de rectángulo 9×12 cm:}',
    options: ['13 cm', '15 cm', '17 cm', '21 cm'],
    correctAnswer: 1,
    explanation: 'La diagonal forma un triángulo rectángulo:',
    explanationLatex: 'd^2 = 9^2 + 12^2 = 81 + 144 = 225 \\rightarrow d = 15 \\text{ cm}',
    difficulty: 'easy',
    skills: ['geometria-rectangulos', 'geometria-pitagoras', 'geometria-diagonales', 'numeros-raices', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-211',
    level: 'M1',
    topic: 'Geometría',
    subject: 'geometría',
    question: 'Un cuadrado tiene diagonal de 10 cm. ¿Cuánto mide su lado aproximadamente?',
    questionLatex: '\\text{Cuadrado con diagonal 10 cm. Lado aprox.?}',
    options: ['5 cm', '7.07 cm', '8 cm', '10 cm'],
    correctAnswer: 1,
    explanation: 'En un cuadrado: diagonal = lado × √2',
    explanationLatex: 'l \\times \\sqrt{2} = 10 \\rightarrow l = \\frac{10}{\\sqrt{2}} \\approx 7.07 \\text{ cm}',
    difficulty: 'medium',
    skills: ['geometria-cuadrados', 'geometria-pitagoras', 'geometria-diagonales', 'numeros-raices', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-212',
    level: 'M1',
    topic: 'Geometría',
    subject: 'geometría',
    question: 'Una escalera de 5 m se apoya en una pared. Si la base está a 3 m de la pared, ¿a qué altura llega?',
    questionLatex: '\\text{Escalera 5 m, base a 3 m. ¿Altura?}',
    options: ['2 m', '3 m', '4 m', '5 m'],
    correctAnswer: 2,
    explanation: 'Aplicamos Pitágoras:',
    explanationLatex: 'h^2 = 5^2 - 3^2 = 25 - 9 = 16 \\rightarrow h = 4 \\text{ m}',
    difficulty: 'easy',
    skills: ['geometria-pitagoras', 'geometria-aplicaciones', 'geometria-triangulo-rectangulo', 'numeros-raices', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-213',
    level: 'M1',
    topic: 'Geometría',
    subject: 'geometría',
    question: 'La distancia entre los puntos A(0, 0) y B(3, 4) es:',
    questionLatex: '\\text{Distancia entre } A(0, 0) \\text{ y } B(3, 4):',
    options: ['3', '4', '5', '7'],
    correctAnswer: 2,
    explanation: 'Fórmula de distancia:',
    explanationLatex: 'd = \\sqrt{(3-0)^2 + (4-0)^2} = \\sqrt{9 + 16} = \\sqrt{25} = 5',
    difficulty: 'easy',
    skills: ['geometria-plano-cartesiano', 'geometria-distancia', 'geometria-pitagoras', 'numeros-raices', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-214',
    level: 'M1',
    topic: 'Geometría',
    subject: 'geometría',
    question: 'La distancia entre P(2, 3) y Q(6, 6) es:',
    questionLatex: '\\text{Distancia entre } P(2, 3) \\text{ y } Q(6, 6):',
    options: ['3', '4', '5', '7'],
    correctAnswer: 2,
    explanation: 'Aplicamos la fórmula:',
    explanationLatex: 'd = \\sqrt{(6-2)^2 + (6-3)^2} = \\sqrt{16 + 9} = \\sqrt{25} = 5',
    difficulty: 'medium',
    skills: ['geometria-plano-cartesiano', 'geometria-distancia', 'geometria-pitagoras', 'numeros-raices', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-215',
    level: 'M1',
    topic: 'Geometría',
    subject: 'geometría',
    question: 'Un punto está a 5 unidades del origen en el eje x positivo. Otro punto está a 12 unidades en el eje y positivo. ¿Cuál es la distancia entre ellos?',
    questionLatex: '\\text{Punto (5,0) y punto (0,12). Distancia?}',
    options: ['7', '10', '13', '17'],
    correctAnswer: 2,
    explanation: 'Distancia entre (5,0) y (0,12):',
    explanationLatex: 'd = \\sqrt{5^2 + 12^2} = \\sqrt{25 + 144} = \\sqrt{169} = 13',
    difficulty: 'medium',
    skills: ['geometria-plano-cartesiano', 'geometria-distancia', 'geometria-pitagoras', 'numeros-raices', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-216',
    level: 'M1',
    topic: 'Geometría',
    subject: 'geometría',
    question: '¿Cuál de los siguientes conjuntos forma una terna pitagórica?',
    questionLatex: '\\text{¿Cuál forma terna pitagórica?}',
    options: ['(2, 3, 4)', '(5, 12, 13)', '(6, 7, 8)', '(7, 8, 9)'],
    correctAnswer: 1,
    explanation: 'Verificamos: 5² + 12² = 25 + 144 = 169 = 13²:',
    explanationLatex: '(5, 12, 13) \\text{ es terna pitagórica}',
    difficulty: 'easy',
    skills: ['geometria-pitagoras', 'geometria-ternas-pitagoricas', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-217',
    level: 'M1',
    topic: 'Geometría',
    subject: 'geometría',
    question: 'Si (3, 4, 5) es una terna pitagórica, ¿cuál de las siguientes también lo es?',
    questionLatex: '\\text{Si (3,4,5) es terna, ¿cuál también?}',
    options: ['(4, 5, 6)', '(6, 8, 10)', '(5, 6, 7)', '(7, 8, 9)'],
    correctAnswer: 1,
    explanation: 'Múltiplos de una terna pitagórica también lo son:',
    explanationLatex: '(6, 8, 10) = 2(3, 4, 5)',
    difficulty: 'medium',
    skills: ['geometria-pitagoras', 'geometria-ternas-pitagoricas', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-218',
    level: 'M1',
    topic: 'Geometría',
    subject: 'geometría',
    question: '¿Cuál es la hipotenusa de un triángulo con catetos 8 y 15?',
    questionLatex: '\\text{Catetos 8 y 15. Hipotenusa?}',
    options: ['15', '16', '17', '23'],
    correctAnswer: 2,
    explanation: 'Terna pitagórica (8, 15, 17):',
    explanationLatex: '8^2 + 15^2 = 64 + 225 = 289 = 17^2',
    difficulty: 'easy',
    skills: ['geometria-pitagoras', 'geometria-ternas-pitagoricas', 'geometria-triangulo-rectangulo', 'numeros-potencias', 'numeros-raices', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-219',
    level: 'M1',
    topic: 'Geometría',
    subject: 'geometría',
    question: 'Un poste de 6 m de altura proyecta una sombra de 8 m. ¿Cuál es la distancia desde la punta del poste hasta el extremo de la sombra?',
    questionLatex: '\\text{Poste 6 m, sombra 8 m. Distancia punta a extremo?}',
    options: ['8 m', '10 m', '12 m', '14 m'],
    correctAnswer: 1,
    explanation: 'Aplicamos Pitágoras:',
    explanationLatex: 'd^2 = 6^2 + 8^2 = 36 + 64 = 100 \\rightarrow d = 10 \\text{ m}',
    difficulty: 'medium',
    skills: ['geometria-pitagoras', 'geometria-aplicaciones', 'numeros-raices', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-220',
    level: 'M1',
    topic: 'Geometría',
    subject: 'geometría',
    question: 'Un barco navega 12 km al norte y luego 16 km al este. ¿A qué distancia está del punto de partida?',
    questionLatex: '\\text{Barco: 12 km norte, 16 km este. Distancia al origen?}',
    options: ['18 km', '20 km', '22 km', '28 km'],
    correctAnswer: 1,
    explanation: 'Los desplazamientos forman un triángulo rectángulo:',
    explanationLatex: 'd^2 = 12^2 + 16^2 = 144 + 256 = 400 \\rightarrow d = 20 \\text{ km}',
    difficulty: 'medium',
    skills: ['geometria-pitagoras', 'geometria-aplicaciones', 'numeros-raices', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-221',
    level: 'M1',
    topic: 'Geometría',
    subject: 'geometría',
    question: 'La altura de un triángulo equilátero de lado 6 cm es aproximadamente:',
    questionLatex: '\\text{Altura de triángulo equilátero con lado 6 cm:}',
    options: ['3 cm', '4.24 cm', '5.20 cm', '6 cm'],
    correctAnswer: 2,
    explanation: 'La altura divide al triángulo en dos triángulos 30-60-90:',
    explanationLatex: 'h^2 = 6^2 - 3^2 = 36 - 9 = 27 \\rightarrow h = \\sqrt{27} \\approx 5.20 \\text{ cm}',
    difficulty: 'hard',
    skills: ['geometria-triangulos', 'geometria-triangulo-equilatero', 'geometria-pitagoras', 'numeros-raices', 'numeros-potencias', 'numeros-operaciones-basicas']
  }
];
