import { Question } from '../types';

export const m1AlgebraQuestions: Question[] = [
  {
    id: 'm1-2',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $f(x) = 2x + 3$, ¿cuál es el valor de $f(5)$?',
    questionLatex: '\\text{Si } f(x) = 2x + 3 \\text{, ¿cuál es el valor de } f(5)?',
    options: ['10', '11', '12', '13'],
    correctAnswer: 3,
    explanation: 'Sustituimos $x = 5$:',
    explanationLatex: 'f(5) = 2(5) + 3 = 10 + 3 = 13',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-evaluacion-funciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-5',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver la ecuación: $2x - 5 = 11$',
    questionLatex: '\\text{Resolver la ecuación: } 2x - 5 = 11',
    options: ['$x = 6$', '$x = 7$', '$x = 8$', '$x = 9$'],
    optionsLatex: ['x = 6', 'x = 7', 'x = 8', 'x = 9'],
    correctAnswer: 2,
    explanation: 'Despejamos $x$:',
    explanationLatex: '2x - 5 = 11 \\rightarrow 2x = 16 \\rightarrow x = 8',
    difficulty: 'easy',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-13',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar la expresión: $3x + 5x - 2x$',
    questionLatex: '\\text{Simplificar la expresión: } 3x + 5x - 2x',
    options: ['$6x$', '$10x$', '$8x$', '$5x$'],
    optionsLatex: ['6x', '10x', '8x', '5x'],
    correctAnswer: 0,
    explanation: 'Sumamos y restamos los coeficientes de términos semejantes:',
    explanationLatex: '3x + 5x - 2x = (3 + 5 - 2)x = 6x',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-14',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Factorizar: $x^2 - 9$',
    questionLatex: '\\text{Factorizar: } x^2 - 9',
    options: ['$(x-3)(x-3)$', '$(x+3)(x+3)$', '$(x-3)(x+3)$', '$x(x-9)$'],
    optionsLatex: ['(x-3)(x-3)', '(x+3)(x+3)', '(x-3)(x+3)', 'x(x-9)'],
    correctAnswer: 2,
    explanation: 'Es una diferencia de cuadrados:',
    explanationLatex: 'x^2 - 9 = x^2 - 3^2 = (x-3)(x+3)',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'algebra-diferencia-cuadrados', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-15',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $y = 3x - 2$, ¿cuál es la pendiente de la recta?',
    questionLatex: '\\text{Si } y = 3x - 2 \\text{, ¿cuál es la pendiente de la recta?}',
    options: ['-2', '2', '3', '-3'],
    correctAnswer: 2,
    explanation: 'En la forma $y = mx + b$, $m$ es la pendiente:',
    explanationLatex: 'y = 3x - 2 \\quad \\Rightarrow \\quad m = 3',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-funciones-lineales', 'algebra-pendiente']
  },
  {
    id: 'm1-16',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver la desigualdad: $2x + 3 > 7$',
    questionLatex: '\\text{Resolver la desigualdad: } 2x + 3 > 7',
    options: ['$x > 2$', '$x < 2$', '$x > 5$', '$x < 5$'],
    optionsLatex: ['x > 2', 'x < 2', 'x > 5', 'x < 5'],
    correctAnswer: 0,
    explanation: 'Despejamos $x$ igual que en una ecuación:',
    explanationLatex: '2x + 3 > 7 \\rightarrow 2x > 4 \\rightarrow x > 2',
    difficulty: 'medium',
    skills: ['algebra-desigualdades', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-30',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $x + 5 = 12$, ¿cuál es el valor de $2x$?',
    questionLatex: '\\text{Si } x + 5 = 12 \\text{, ¿cuál es el valor de } 2x?',
    options: ['7', '10', '14', '17'],
    correctAnswer: 2,
    explanation: 'Primero encontramos x, luego calculamos 2x:',
    explanationLatex: 'x + 5 = 12 \\rightarrow x = 7 \\quad \\Rightarrow \\quad 2x = 2(7) = 14',
    difficulty: 'easy',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-31',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Expandir: $(x + 3)(x + 2)$',
    questionLatex: '\\text{Expandir: } (x + 3)(x + 2)',
    options: ['$x^2 + 5x + 6$', '$x^2 + 6x + 5$', '$x^2 + 5x + 5$', '$x^2 + 6x + 6$'],
    optionsLatex: ['x^2 + 5x + 6', 'x^2 + 6x + 5', 'x^2 + 5x + 5', 'x^2 + 6x + 6'],
    correctAnswer: 0,
    explanation: 'Aplicamos la propiedad distributiva:',
    explanationLatex: '(x + 3)(x + 2) = x^2 + 2x + 3x + 6 = x^2 + 5x + 6',
    difficulty: 'medium',
    skills: ['algebra-expansion', 'algebra-propiedad-distributiva', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-32',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $f(x) = x^2 - 1$, ¿cuál es $f(3)$?',
    questionLatex: '\\text{Si } f(x) = x^2 - 1 \\text{, ¿cuál es } f(3)?',
    options: ['6', '7', '8', '9'],
    correctAnswer: 2,
    explanation: 'Sustituimos x por 3:',
    explanationLatex: 'f(3) = 3^2 - 1 = 9 - 1 = 8',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-evaluacion-funciones', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-33',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\frac{x}{3} + 2 = 5$',
    questionLatex: '\\text{Resolver: } \\frac{x}{3} + 2 = 5',
    options: ['$x = 3$', '$x = 6$', '$x = 9$', '$x = 12$'],
    optionsLatex: ['x = 3', 'x = 6', 'x = 9', 'x = 12'],
    correctAnswer: 2,
    explanation: 'Despejamos x:',
    explanationLatex: '\\frac{x}{3} + 2 = 5 \\rightarrow \\frac{x}{3} = 3 \\rightarrow x = 9',
    difficulty: 'easy',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },

  // NEW QUESTIONS - BATCH 1: EXPRESIONES ALGEBRAICAS (9 questions)

  // Operaciones con monomios - Multiplicación (3)
  {
    id: 'm1-123',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el resultado de $(3x^2)(4x^3)$?',
    questionLatex: '\\text{¿Cuál es el resultado de } (3x^2)(4x^3)?',
    options: ['$7x^5$', '$12x^5$', '$7x^6$', '$12x^6$'],
    optionsLatex: ['7x^5', '12x^5', '7x^6', '12x^6'],
    correctAnswer: 1,
    explanation: 'Multiplicamos los coeficientes y sumamos los exponentes:',
    explanationLatex: '(3x^2)(4x^3) = 3 \\times 4 \\times x^{2+3} = 12x^5',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-124',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $(2a^3b)(5ab^2)$',
    questionLatex: '\\text{Simplificar: } (2a^3b)(5ab^2)',
    options: ['$10a^3b^2$', '$7a^4b^3$', '$10a^4b^3$', '$7a^3b^2$'],
    optionsLatex: ['10a^3b^2', '7a^4b^3', '10a^4b^3', '7a^3b^2'],
    correctAnswer: 2,
    explanation: 'Multiplicamos coeficientes y sumamos exponentes de cada variable:',
    explanationLatex: '(2a^3b)(5ab^2) = 2 \\times 5 \\times a^{3+1} \\times b^{1+2} = 10a^4b^3',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-125',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Juan multiplica dos monomios: $(-3x^2y)$ y $(2xy^3)$. ¿Cuál es el resultado?',
    questionLatex: '\\text{Juan multiplica dos monomios: } (-3x^2y) \\text{ y } (2xy^3). \\text{ ¿Cuál es el resultado?}',
    options: ['$-6x^2y^3$', '$-6x^3y^4$', '$-5x^3y^4$', '$6x^3y^4$'],
    optionsLatex: ['-6x^2y^3', '-6x^3y^4', '-5x^3y^4', '6x^3y^4'],
    correctAnswer: 1,
    explanation: 'Multiplicamos coeficientes (incluyendo signos) y sumamos exponentes:',
    explanationLatex: '(-3x^2y)(2xy^3) = -3 \\times 2 \\times x^{2+1} \\times y^{1+3} = -6x^3y^4',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-enteros', 'numeros-operaciones-basicas']
  },

  // Operaciones con monomios - División (3)
  {
    id: 'm1-126',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el resultado de $\\frac{12x^5}{4x^2}$?',
    questionLatex: '\\text{¿Cuál es el resultado de } \\frac{12x^5}{4x^2}?',
    options: ['$3x^3$', '$8x^3$', '$3x^{10}$', '$8x^7$'],
    optionsLatex: ['3x^3', '8x^3', '3x^{10}', '8x^7'],
    correctAnswer: 0,
    explanation: 'Dividimos los coeficientes y restamos los exponentes:',
    explanationLatex: '\\frac{12x^5}{4x^2} = \\frac{12}{4} \\times x^{5-2} = 3x^3',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-127',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $\\frac{18a^4b^3}{6a^2b}$',
    questionLatex: '\\text{Simplificar: } \\frac{18a^4b^3}{6a^2b}',
    options: ['$3a^2b^2$', '$12a^2b^2$', '$3a^6b^4$', '$12a^6b^4$'],
    optionsLatex: ['3a^2b^2', '12a^2b^2', '3a^6b^4', '12a^6b^4'],
    correctAnswer: 0,
    explanation: 'Dividimos coeficientes y restamos exponentes de cada variable:',
    explanationLatex: '\\frac{18a^4b^3}{6a^2b} = \\frac{18}{6} \\times a^{4-2} \\times b^{3-1} = 3a^2b^2',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-128',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Calcular: $\\frac{-24x^6y^4}{8x^2y}$',
    questionLatex: '\\text{Calcular: } \\frac{-24x^6y^4}{8x^2y}',
    options: ['$-3x^4y^3$', '$3x^4y^3$', '$-3x^8y^5$', '$-16x^4y^3$'],
    optionsLatex: ['-3x^4y^3', '3x^4y^3', '-3x^8y^5', '-16x^4y^3'],
    correctAnswer: 0,
    explanation: 'Dividimos coeficientes con signo y restamos exponentes:',
    explanationLatex: '\\frac{-24x^6y^4}{8x^2y} = \\frac{-24}{8} \\times x^{6-2} \\times y^{4-1} = -3x^4y^3',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-enteros', 'numeros-operaciones-basicas']
  },

  // Operaciones con monomios - Potencias (3)
  {
    id: 'm1-129',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el resultado de $(2x^3)^2$?',
    questionLatex: '\\text{¿Cuál es el resultado de } (2x^3)^2?',
    options: ['$2x^6$', '$4x^6$', '$2x^5$', '$4x^5$'],
    optionsLatex: ['2x^6', '4x^6', '2x^5', '4x^5'],
    correctAnswer: 1,
    explanation: 'Elevamos el coeficiente y multiplicamos los exponentes:',
    explanationLatex: '(2x^3)^2 = 2^2 \\times (x^3)^2 = 4 \\times x^{3 \\times 2} = 4x^6',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-130',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $(3a^2b)^3$',
    questionLatex: '\\text{Simplificar: } (3a^2b)^3',
    options: ['$9a^5b^3$', '$27a^5b^3$', '$9a^6b^3$', '$27a^6b^3$'],
    optionsLatex: ['9a^5b^3', '27a^5b^3', '9a^6b^3', '27a^6b^3'],
    correctAnswer: 3,
    explanation: 'Elevamos cada factor a la potencia:',
    explanationLatex: '(3a^2b)^3 = 3^3 \\times (a^2)^3 \\times b^3 = 27 \\times a^6 \\times b^3 = 27a^6b^3',
    difficulty: 'hard',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-131',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Calcular: $(-2xy^2)^3$',
    questionLatex: '\\text{Calcular: } (-2xy^2)^3',
    options: ['$-8x^3y^6$', '$8x^3y^6$', '$-6x^3y^5$', '$-8x^4y^6$'],
    optionsLatex: ['-8x^3y^6', '8x^3y^6', '-6x^3y^5', '-8x^4y^6'],
    correctAnswer: 0,
    explanation: 'Elevamos cada factor, recordando que (-2)³ = -8:',
    explanationLatex: '(-2xy^2)^3 = (-2)^3 \\times x^3 \\times (y^2)^3 = -8 \\times x^3 \\times y^6 = -8x^3y^6',
    difficulty: 'hard',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-enteros', 'numeros-operaciones-basicas']
  },

  // BATCH 2: EVALUACIÓN Y SIMPLIFICACIÓN (9 questions)

  // Evaluación de expresiones con múltiples variables (3)
  {
    id: 'm1-132',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $a = 2$ y $b = 3$, ¿cuál es el valor de $3a + 2b$?',
    questionLatex: '\\text{Si } a = 2 \\text{ y } b = 3, \\text{ ¿cuál es el valor de } 3a + 2b?',
    options: ['8', '11', '12', '15'],
    correctAnswer: 2,
    explanation: 'Sustituimos los valores y calculamos:',
    explanationLatex: '3a + 2b = 3(2) + 2(3) = 6 + 6 = 12',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'algebra-evaluacion-funciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-133',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Evaluar $x^2 - 2xy + y^2$ cuando $x = 5$ y $y = 3$',
    questionLatex: '\\text{Evaluar } x^2 - 2xy + y^2 \\text{ cuando } x = 5 \\text{ y } y = 3',
    options: ['4', '9', '16', '25'],
    correctAnswer: 0,
    explanation: 'Sustituimos los valores en la expresión:',
    explanationLatex: 'x^2 - 2xy + y^2 = 5^2 - 2(5)(3) + 3^2 = 25 - 30 + 9 = 4',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'algebra-evaluacion-funciones', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-134',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $a = -2$, $b = 4$ y $c = 1$, calcular $\\frac{a^2 + b}{c}$',
    questionLatex: '\\text{Si } a = -2, b = 4 \\text{ y } c = 1, \\text{ calcular } \\frac{a^2 + b}{c}',
    options: ['0', '4', '6', '8'],
    correctAnswer: 3,
    explanation: 'Sustituimos y evaluamos paso a paso:',
    explanationLatex: '\\frac{a^2 + b}{c} = \\frac{(-2)^2 + 4}{1} = \\frac{4 + 4}{1} = 8',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'algebra-evaluacion-funciones', 'numeros-potencias', 'numeros-enteros', 'numeros-operaciones-basicas']
  },

  // Simplificación avanzada con paréntesis (3)
  {
    id: 'm1-135',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $2(x + 3) - 3(x - 1)$',
    questionLatex: '\\text{Simplificar: } 2(x + 3) - 3(x - 1)',
    options: ['$-x + 9$', '$-x + 3$', '$x + 9$', '$5x + 3$'],
    optionsLatex: ['-x + 9', '-x + 3', 'x + 9', '5x + 3'],
    correctAnswer: 0,
    explanation: 'Aplicamos distributiva y combinamos términos:',
    explanationLatex: '2(x + 3) - 3(x - 1) = 2x + 6 - 3x + 3 = -x + 9',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-136',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $5x - [2x - (3x - 4)]$',
    questionLatex: '\\text{Simplificar: } 5x - [2x - (3x - 4)]',
    options: ['$6x - 4$', '$6x + 4$', '$4x - 4$', '$4x + 4$'],
    optionsLatex: ['6x - 4', '6x + 4', '4x - 4', '4x + 4'],
    correctAnswer: 1,
    explanation: 'Resolvemos de adentro hacia afuera:',
    explanationLatex: '5x - [2x - (3x - 4)] = 5x - [2x - 3x + 4] = 5x - [-x + 4] = 5x + x - 4 = 6x + 4',
    difficulty: 'hard',
    skills: ['algebra-expresiones', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-137',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $3(2a - b) - 2(a + 3b)$',
    questionLatex: '\\text{Simplificar: } 3(2a - b) - 2(a + 3b)',
    options: ['$4a - 9b$', '$4a + 9b$', '$8a - 9b$', '$8a + 3b$'],
    optionsLatex: ['4a - 9b', '4a + 9b', '8a - 9b', '8a + 3b'],
    correctAnswer: 0,
    explanation: 'Aplicamos distributiva y simplificamos:',
    explanationLatex: '3(2a - b) - 2(a + 3b) = 6a - 3b - 2a - 6b = 4a - 9b',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },

  // Valor numérico con aplicaciones (3)
  {
    id: 'm1-138',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'El perímetro de un rectángulo se calcula con $P = 2l + 2a$. Si $l = 8$ cm y $a = 5$ cm, ¿cuál es el perímetro?',
    questionLatex: '\\text{El perímetro de un rectángulo es } P = 2l + 2a. \\text{ Si } l = 8 \\text{ cm y } a = 5 \\text{ cm, ¿cuál es el perímetro?}',
    options: ['13 cm', '21 cm', '26 cm', '40 cm'],
    correctAnswer: 2,
    explanation: 'Sustituimos los valores en la fórmula:',
    explanationLatex: 'P = 2l + 2a = 2(8) + 2(5) = 16 + 10 = 26 \\text{ cm}',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'algebra-evaluacion-funciones', 'geometria-perimetro', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-139',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'La distancia recorrida es $d = vt$ donde $v$ es velocidad y $t$ es tiempo. Si un auto viaja a $v = 80$ km/h por $t = 2.5$ horas, ¿qué distancia recorre?',
    questionLatex: '\\text{La distancia es } d = vt. \\text{ Si } v = 80 \\text{ km/h y } t = 2.5 \\text{ h, ¿qué distancia recorre?}',
    options: ['160 km', '180 km', '200 km', '220 km'],
    correctAnswer: 2,
    explanation: 'Multiplicamos velocidad por tiempo:',
    explanationLatex: 'd = vt = 80 \\times 2.5 = 200 \\text{ km}',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'algebra-evaluacion-funciones', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-140',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'La temperatura en Fahrenheit se calcula con $F = \\frac{9}{5}C + 32$. Si $C = 25°$, ¿cuál es la temperatura en Fahrenheit?',
    questionLatex: '\\text{La temperatura es } F = \\frac{9}{5}C + 32. \\text{ Si } C = 25°, \\text{ ¿cuál es } F?',
    options: ['45°F', '57°F', '77°F', '93°F'],
    correctAnswer: 2,
    explanation: 'Sustituimos C = 25 en la fórmula:',
    explanationLatex: 'F = \\frac{9}{5}(25) + 32 = \\frac{225}{5} + 32 = 45 + 32 = 77°F',
    difficulty: 'hard',
    skills: ['algebra-expresiones', 'algebra-evaluacion-funciones', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },

  // BATCH 3: ECUACIONES LINEALES AVANZADAS (9 questions)

  // Ecuaciones con fracciones (3)
  {
    id: 'm1-141',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\frac{x}{2} + \\frac{x}{3} = 10$',
    questionLatex: '\\text{Resolver: } \\frac{x}{2} + \\frac{x}{3} = 10',
    options: ['$x = 6$', '$x = 12$', '$x = 15$', '$x = 20$'],
    optionsLatex: ['x = 6', 'x = 12', 'x = 15', 'x = 20'],
    correctAnswer: 1,
    explanation: 'Encontramos común denominador y despejamos:',
    explanationLatex: '\\frac{x}{2} + \\frac{x}{3} = 10 \\rightarrow \\frac{3x + 2x}{6} = 10 \\rightarrow \\frac{5x}{6} = 10 \\rightarrow x = 12',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-fracciones', 'numeros-fracciones-comun-denominador', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-142',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\frac{2x - 1}{3} = 5$',
    questionLatex: '\\text{Resolver: } \\frac{2x - 1}{3} = 5',
    options: ['$x = 7$', '$x = 8$', '$x = 9$', '$x = 10$'],
    optionsLatex: ['x = 7', 'x = 8', 'x = 9', 'x = 10'],
    correctAnswer: 1,
    explanation: 'Multiplicamos ambos lados por 3 y despejamos:',
    explanationLatex: '\\frac{2x - 1}{3} = 5 \\rightarrow 2x - 1 = 15 \\rightarrow 2x = 16 \\rightarrow x = 8',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-143',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\frac{x + 2}{4} - \\frac{x - 1}{2} = 1$',
    questionLatex: '\\text{Resolver: } \\frac{x + 2}{4} - \\frac{x - 1}{2} = 1',
    options: ['$x = -4$', '$x = -6$', '$x = 4$', '$x = 6$'],
    optionsLatex: ['x = -4', 'x = -6', 'x = 4', 'x = 6'],
    correctAnswer: 1,
    explanation: 'Usamos común denominador 4 y resolvemos:',
    explanationLatex: '\\frac{x + 2}{4} - \\frac{2(x - 1)}{4} = 1 \\rightarrow \\frac{x + 2 - 2x + 2}{4} = 1 \\rightarrow \\frac{4 - x}{4} = 1 \\rightarrow 4 - x = 4 \\rightarrow x = -6',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-fracciones', 'numeros-fracciones-comun-denominador', 'numeros-operaciones-basicas']
  },

  // Ecuaciones con paréntesis (3)
  {
    id: 'm1-144',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $3(x - 2) = 2(x + 1)$',
    questionLatex: '\\text{Resolver: } 3(x - 2) = 2(x + 1)',
    options: ['$x = 6$', '$x = 7$', '$x = 8$', '$x = 9$'],
    optionsLatex: ['x = 6', 'x = 7', 'x = 8', 'x = 9'],
    correctAnswer: 2,
    explanation: 'Aplicamos distributiva en ambos lados y despejamos:',
    explanationLatex: '3(x - 2) = 2(x + 1) \\rightarrow 3x - 6 = 2x + 2 \\rightarrow 3x - 2x = 2 + 6 \\rightarrow x = 8',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'algebra-propiedad-distributiva', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-145',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $4(2x + 1) - 3(x - 2) = 22$',
    questionLatex: '\\text{Resolver: } 4(2x + 1) - 3(x - 2) = 22',
    options: ['$x = 2$', '$x = 3$', '$x = 4$', '$x = 5$'],
    optionsLatex: ['x = 2', 'x = 3', 'x = 4', 'x = 5'],
    correctAnswer: 0,
    explanation: 'Expandimos y simplificamos:',
    explanationLatex: '4(2x + 1) - 3(x - 2) = 22 \\rightarrow 8x + 4 - 3x + 6 = 22 \\rightarrow 5x + 10 = 22 \\rightarrow 5x = 12 \\rightarrow x = 2',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-146',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $2[x - (3 - x)] = 10$',
    questionLatex: '\\text{Resolver: } 2[x - (3 - x)] = 10',
    options: ['$x = 2$', '$x = 3$', '$x = 4$', '$x = 5$'],
    optionsLatex: ['x = 2', 'x = 3', 'x = 4', 'x = 5'],
    correctAnswer: 2,
    explanation: 'Resolvemos el paréntesis interno primero:',
    explanationLatex: '2[x - (3 - x)] = 10 \\rightarrow 2[x - 3 + x] = 10 \\rightarrow 2[2x - 3] = 10 \\rightarrow 4x - 6 = 10 \\rightarrow 4x = 16 \\rightarrow x = 4',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'algebra-propiedad-distributiva', 'numeros-operaciones-basicas']
  },

  // Problemas verbales (edad, consecutivos, perímetro) (3)
  {
    id: 'm1-147',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Pedro tiene el doble de edad que su hermana Ana. Si Ana tiene $x$ años y la suma de sus edades es 36 años, ¿cuántos años tiene Pedro?',
    questionLatex: '\\text{Pedro tiene el doble de edad que Ana. Si Ana tiene } x \\text{ años y la suma es 36 años, ¿cuántos años tiene Pedro?}',
    options: ['12 años', '18 años', '24 años', '30 años'],
    correctAnswer: 2,
    explanation: 'Planteamos la ecuación donde Pedro tiene 2x años:',
    explanationLatex: 'x + 2x = 36 \\rightarrow 3x = 36 \\rightarrow x = 12 \\text{ (Ana)} \\quad \\Rightarrow \\quad \\text{Pedro} = 2(12) = 24 \\text{ años}',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-148',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'La suma de tres números consecutivos es 48. ¿Cuál es el número mayor?',
    questionLatex: '\\text{La suma de tres números consecutivos es 48. ¿Cuál es el número mayor?}',
    options: ['15', '16', '17', '18'],
    correctAnswer: 2,
    explanation: 'Si el primer número es x, los consecutivos son x+1 y x+2:',
    explanationLatex: 'x + (x + 1) + (x + 2) = 48 \\rightarrow 3x + 3 = 48 \\rightarrow 3x = 45 \\rightarrow x = 15 \\quad \\Rightarrow \\quad \\text{mayor} = 15 + 2 = 17',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-149',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Un rectángulo tiene un largo que es 5 cm mayor que su ancho. Si el perímetro es 50 cm, ¿cuál es el ancho?',
    questionLatex: '\\text{Un rectángulo tiene largo 5 cm mayor que el ancho. Si el perímetro es 50 cm, ¿cuál es el ancho?}',
    options: ['8 cm', '10 cm', '12 cm', '15 cm'],
    correctAnswer: 1,
    explanation: 'Si el ancho es x, el largo es x+5. Perímetro: 2x + 2(x+5) = 50:',
    explanationLatex: '2x + 2(x + 5) = 50 \\rightarrow 2x + 2x + 10 = 50 \\rightarrow 4x = 40 \\rightarrow x = 10 \\text{ cm}',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'geometria-perimetro', 'geometria-rectangulos', 'numeros-operaciones-basicas']
  }
];
