import { Question } from '../types';

export const m1AlgebraQuestions: Question[] = [
  {
    id: 'm1-2',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $f(x) = 2x + 3$, ¿cuál es el valor de $f(5)$?',
    questionLatex: '\\text{Si } f(x) = 2x + 3 \\text{, ¿cuál es el valor de } f(5)?',
    options: ['10', '11', '12', '13'],
    correctAnswer: 3,
    explanation: 'Sustituimos $x = 5$:',
    explanationLatex: 'f(5) = 2(5) + 3 = 10 + 3 = 13',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-evaluacion-funciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-5',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver la ecuación: $2x - 5 = 11$',
    questionLatex: '\\text{Resolver la ecuación: } 2x - 5 = 11',
    options: ['$x = 6$', '$x = 7$', '$x = 8$', '$x = 9$'],
    optionsLatex: ['x = 6', 'x = 7', 'x = 8', 'x = 9'],
    correctAnswer: 2,
    explanation: 'Despejamos $x$:',
    explanationLatex: '2x - 5 = 11 \\rightarrow 2x = 16 \\rightarrow x = 8',
    difficulty: 'easy',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-13',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar la expresión: $3x + 5x - 2x$',
    questionLatex: '\\text{Simplificar la expresión: } 3x + 5x - 2x',
    options: ['$6x$', '$10x$', '$8x$', '$5x$'],
    optionsLatex: ['6x', '10x', '8x', '5x'],
    correctAnswer: 0,
    explanation: 'Sumamos y restamos los coeficientes de términos semejantes:',
    explanationLatex: '3x + 5x - 2x = (3 + 5 - 2)x = 6x',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-14',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Factorizar: $x^2 - 9$',
    questionLatex: '\\text{Factorizar: } x^2 - 9',
    options: ['$(x-3)(x-3)$', '$(x+3)(x+3)$', '$(x-3)(x+3)$', '$x(x-9)$'],
    optionsLatex: ['(x-3)(x-3)', '(x+3)(x+3)', '(x-3)(x+3)', 'x(x-9)'],
    correctAnswer: 2,
    explanation: 'Es una diferencia de cuadrados:',
    explanationLatex: 'x^2 - 9 = x^2 - 3^2 = (x-3)(x+3)',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'algebra-diferencia-cuadrados', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-15',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $y = 3x - 2$, ¿cuál es la pendiente de la recta?',
    questionLatex: '\\text{Si } y = 3x - 2 \\text{, ¿cuál es la pendiente de la recta?}',
    options: ['-2', '2', '3', '-3'],
    correctAnswer: 2,
    explanation: 'En la forma $y = mx + b$, $m$ es la pendiente:',
    explanationLatex: 'y = 3x - 2 \\quad \\Rightarrow \\quad m = 3',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-funciones-lineales', 'algebra-pendiente']
  },
  {
    id: 'm1-16',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver la desigualdad: $2x + 3 > 7$',
    questionLatex: '\\text{Resolver la desigualdad: } 2x + 3 > 7',
    options: ['$x > 2$', '$x < 2$', '$x > 5$', '$x < 5$'],
    optionsLatex: ['x > 2', 'x < 2', 'x > 5', 'x < 5'],
    correctAnswer: 0,
    explanation: 'Despejamos $x$ igual que en una ecuación:',
    explanationLatex: '2x + 3 > 7 \\rightarrow 2x > 4 \\rightarrow x > 2',
    difficulty: 'medium',
    skills: ['algebra-desigualdades', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-30',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $x + 5 = 12$, ¿cuál es el valor de $2x$?',
    questionLatex: '\\text{Si } x + 5 = 12 \\text{, ¿cuál es el valor de } 2x?',
    options: ['7', '10', '14', '17'],
    correctAnswer: 2,
    explanation: 'Primero encontramos x, luego calculamos 2x:',
    explanationLatex: 'x + 5 = 12 \\rightarrow x = 7 \\quad \\Rightarrow \\quad 2x = 2(7) = 14',
    difficulty: 'easy',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-31',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Expandir: $(x + 3)(x + 2)$',
    questionLatex: '\\text{Expandir: } (x + 3)(x + 2)',
    options: ['$x^2 + 5x + 6$', '$x^2 + 6x + 5$', '$x^2 + 5x + 5$', '$x^2 + 6x + 6$'],
    optionsLatex: ['x^2 + 5x + 6', 'x^2 + 6x + 5', 'x^2 + 5x + 5', 'x^2 + 6x + 6'],
    correctAnswer: 0,
    explanation: 'Aplicamos la propiedad distributiva:',
    explanationLatex: '(x + 3)(x + 2) = x^2 + 2x + 3x + 6 = x^2 + 5x + 6',
    difficulty: 'medium',
    skills: ['algebra-expansion', 'algebra-propiedad-distributiva', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-32',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $f(x) = x^2 - 1$, ¿cuál es $f(3)$?',
    questionLatex: '\\text{Si } f(x) = x^2 - 1 \\text{, ¿cuál es } f(3)?',
    options: ['6', '7', '8', '9'],
    correctAnswer: 2,
    explanation: 'Sustituimos x por 3:',
    explanationLatex: 'f(3) = 3^2 - 1 = 9 - 1 = 8',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-evaluacion-funciones', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-33',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\frac{x}{3} + 2 = 5$',
    questionLatex: '\\text{Resolver: } \\frac{x}{3} + 2 = 5',
    options: ['$x = 3$', '$x = 6$', '$x = 9$', '$x = 12$'],
    optionsLatex: ['x = 3', 'x = 6', 'x = 9', 'x = 12'],
    correctAnswer: 2,
    explanation: 'Despejamos x:',
    explanationLatex: '\\frac{x}{3} + 2 = 5 \\rightarrow \\frac{x}{3} = 3 \\rightarrow x = 9',
    difficulty: 'easy',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },

  // NEW QUESTIONS - BATCH 1: EXPRESIONES ALGEBRAICAS (9 questions)

  // Operaciones con monomios - Multiplicación (3)
  {
    id: 'm1-123',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el resultado de $(3x^2)(4x^3)$?',
    questionLatex: '\\text{¿Cuál es el resultado de } (3x^2)(4x^3)?',
    options: ['$7x^5$', '$12x^5$', '$7x^6$', '$12x^6$'],
    optionsLatex: ['7x^5', '12x^5', '7x^6', '12x^6'],
    correctAnswer: 1,
    explanation: 'Multiplicamos los coeficientes y sumamos los exponentes:',
    explanationLatex: '(3x^2)(4x^3) = 3 \\times 4 \\times x^{2+3} = 12x^5',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-124',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $(2a^3b)(5ab^2)$',
    questionLatex: '\\text{Simplificar: } (2a^3b)(5ab^2)',
    options: ['$10a^3b^2$', '$7a^4b^3$', '$10a^4b^3$', '$7a^3b^2$'],
    optionsLatex: ['10a^3b^2', '7a^4b^3', '10a^4b^3', '7a^3b^2'],
    correctAnswer: 2,
    explanation: 'Multiplicamos coeficientes y sumamos exponentes de cada variable:',
    explanationLatex: '(2a^3b)(5ab^2) = 2 \\times 5 \\times a^{3+1} \\times b^{1+2} = 10a^4b^3',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-125',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Juan multiplica dos monomios: $(-3x^2y)$ y $(2xy^3)$. ¿Cuál es el resultado?',
    questionLatex: '\\text{Juan multiplica dos monomios: } (-3x^2y) \\text{ y } (2xy^3). \\text{ ¿Cuál es el resultado?}',
    options: ['$-6x^2y^3$', '$-6x^3y^4$', '$-5x^3y^4$', '$6x^3y^4$'],
    optionsLatex: ['-6x^2y^3', '-6x^3y^4', '-5x^3y^4', '6x^3y^4'],
    correctAnswer: 1,
    explanation: 'Multiplicamos coeficientes (incluyendo signos) y sumamos exponentes:',
    explanationLatex: '(-3x^2y)(2xy^3) = -3 \\times 2 \\times x^{2+1} \\times y^{1+3} = -6x^3y^4',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-enteros', 'numeros-operaciones-basicas']
  },

  // Operaciones con monomios - División (3)
  {
    id: 'm1-126',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el resultado de $\\frac{12x^5}{4x^2}$?',
    questionLatex: '\\text{¿Cuál es el resultado de } \\frac{12x^5}{4x^2}?',
    options: ['$3x^3$', '$8x^3$', '$3x^{10}$', '$8x^7$'],
    optionsLatex: ['3x^3', '8x^3', '3x^{10}', '8x^7'],
    correctAnswer: 0,
    explanation: 'Dividimos los coeficientes y restamos los exponentes:',
    explanationLatex: '\\frac{12x^5}{4x^2} = \\frac{12}{4} \\times x^{5-2} = 3x^3',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-127',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $\\frac{18a^4b^3}{6a^2b}$',
    questionLatex: '\\text{Simplificar: } \\frac{18a^4b^3}{6a^2b}',
    options: ['$3a^2b^2$', '$12a^2b^2$', '$3a^6b^4$', '$12a^6b^4$'],
    optionsLatex: ['3a^2b^2', '12a^2b^2', '3a^6b^4', '12a^6b^4'],
    correctAnswer: 0,
    explanation: 'Dividimos coeficientes y restamos exponentes de cada variable:',
    explanationLatex: '\\frac{18a^4b^3}{6a^2b} = \\frac{18}{6} \\times a^{4-2} \\times b^{3-1} = 3a^2b^2',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-128',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Calcular: $\\frac{-24x^6y^4}{8x^2y}$',
    questionLatex: '\\text{Calcular: } \\frac{-24x^6y^4}{8x^2y}',
    options: ['$-3x^4y^3$', '$3x^4y^3$', '$-3x^8y^5$', '$-16x^4y^3$'],
    optionsLatex: ['-3x^4y^3', '3x^4y^3', '-3x^8y^5', '-16x^4y^3'],
    correctAnswer: 0,
    explanation: 'Dividimos coeficientes con signo y restamos exponentes:',
    explanationLatex: '\\frac{-24x^6y^4}{8x^2y} = \\frac{-24}{8} \\times x^{6-2} \\times y^{4-1} = -3x^4y^3',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-enteros', 'numeros-operaciones-basicas']
  },

  // Operaciones con monomios - Potencias (3)
  {
    id: 'm1-129',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el resultado de $(2x^3)^2$?',
    questionLatex: '\\text{¿Cuál es el resultado de } (2x^3)^2?',
    options: ['$2x^6$', '$4x^6$', '$2x^5$', '$4x^5$'],
    optionsLatex: ['2x^6', '4x^6', '2x^5', '4x^5'],
    correctAnswer: 1,
    explanation: 'Elevamos el coeficiente y multiplicamos los exponentes:',
    explanationLatex: '(2x^3)^2 = 2^2 \\times (x^3)^2 = 4 \\times x^{3 \\times 2} = 4x^6',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-130',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $(3a^2b)^3$',
    questionLatex: '\\text{Simplificar: } (3a^2b)^3',
    options: ['$9a^5b^3$', '$27a^5b^3$', '$9a^6b^3$', '$27a^6b^3$'],
    optionsLatex: ['9a^5b^3', '27a^5b^3', '9a^6b^3', '27a^6b^3'],
    correctAnswer: 3,
    explanation: 'Elevamos cada factor a la potencia:',
    explanationLatex: '(3a^2b)^3 = 3^3 \\times (a^2)^3 \\times b^3 = 27 \\times a^6 \\times b^3 = 27a^6b^3',
    difficulty: 'hard',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-131',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Calcular: $(-2xy^2)^3$',
    questionLatex: '\\text{Calcular: } (-2xy^2)^3',
    options: ['$-8x^3y^6$', '$8x^3y^6$', '$-6x^3y^5$', '$-8x^4y^6$'],
    optionsLatex: ['-8x^3y^6', '8x^3y^6', '-6x^3y^5', '-8x^4y^6'],
    correctAnswer: 0,
    explanation: 'Elevamos cada factor, recordando que (-2)³ = -8:',
    explanationLatex: '(-2xy^2)^3 = (-2)^3 \\times x^3 \\times (y^2)^3 = -8 \\times x^3 \\times y^6 = -8x^3y^6',
    difficulty: 'hard',
    skills: ['algebra-expresiones', 'numeros-potencias-propiedades', 'numeros-enteros', 'numeros-operaciones-basicas']
  },

  // BATCH 2: EVALUACIÓN Y SIMPLIFICACIÓN (9 questions)

  // Evaluación de expresiones con múltiples variables (3)
  {
    id: 'm1-132',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $a = 2$ y $b = 3$, ¿cuál es el valor de $3a + 2b$?',
    questionLatex: '\\text{Si } a = 2 \\text{ y } b = 3, \\text{ ¿cuál es el valor de } 3a + 2b?',
    options: ['8', '11', '12', '15'],
    correctAnswer: 2,
    explanation: 'Sustituimos los valores y calculamos:',
    explanationLatex: '3a + 2b = 3(2) + 2(3) = 6 + 6 = 12',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'algebra-evaluacion-funciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-133',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Evaluar $x^2 - 2xy + y^2$ cuando $x = 5$ y $y = 3$',
    questionLatex: '\\text{Evaluar } x^2 - 2xy + y^2 \\text{ cuando } x = 5 \\text{ y } y = 3',
    options: ['4', '9', '16', '25'],
    correctAnswer: 0,
    explanation: 'Sustituimos los valores en la expresión:',
    explanationLatex: 'x^2 - 2xy + y^2 = 5^2 - 2(5)(3) + 3^2 = 25 - 30 + 9 = 4',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'algebra-evaluacion-funciones', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-134',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $a = -2$, $b = 4$ y $c = 1$, calcular $\\frac{a^2 + b}{c}$',
    questionLatex: '\\text{Si } a = -2, b = 4 \\text{ y } c = 1, \\text{ calcular } \\frac{a^2 + b}{c}',
    options: ['0', '4', '6', '8'],
    correctAnswer: 3,
    explanation: 'Sustituimos y evaluamos paso a paso:',
    explanationLatex: '\\frac{a^2 + b}{c} = \\frac{(-2)^2 + 4}{1} = \\frac{4 + 4}{1} = 8',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'algebra-evaluacion-funciones', 'numeros-potencias', 'numeros-enteros', 'numeros-operaciones-basicas']
  },

  // Simplificación avanzada con paréntesis (3)
  {
    id: 'm1-135',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $2(x + 3) - 3(x - 1)$',
    questionLatex: '\\text{Simplificar: } 2(x + 3) - 3(x - 1)',
    options: ['$-x + 9$', '$-x + 3$', '$x + 9$', '$5x + 3$'],
    optionsLatex: ['-x + 9', '-x + 3', 'x + 9', '5x + 3'],
    correctAnswer: 0,
    explanation: 'Aplicamos distributiva y combinamos términos:',
    explanationLatex: '2(x + 3) - 3(x - 1) = 2x + 6 - 3x + 3 = -x + 9',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-136',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $5x - [2x - (3x - 4)]$',
    questionLatex: '\\text{Simplificar: } 5x - [2x - (3x - 4)]',
    options: ['$6x - 4$', '$6x + 4$', '$4x - 4$', '$4x + 4$'],
    optionsLatex: ['6x - 4', '6x + 4', '4x - 4', '4x + 4'],
    correctAnswer: 1,
    explanation: 'Resolvemos de adentro hacia afuera:',
    explanationLatex: '5x - [2x - (3x - 4)] = 5x - [2x - 3x + 4] = 5x - [-x + 4] = 5x + x - 4 = 6x + 4',
    difficulty: 'hard',
    skills: ['algebra-expresiones', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-137',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Simplificar: $3(2a - b) - 2(a + 3b)$',
    questionLatex: '\\text{Simplificar: } 3(2a - b) - 2(a + 3b)',
    options: ['$4a - 9b$', '$4a + 9b$', '$8a - 9b$', '$8a + 3b$'],
    optionsLatex: ['4a - 9b', '4a + 9b', '8a - 9b', '8a + 3b'],
    correctAnswer: 0,
    explanation: 'Aplicamos distributiva y simplificamos:',
    explanationLatex: '3(2a - b) - 2(a + 3b) = 6a - 3b - 2a - 6b = 4a - 9b',
    difficulty: 'medium',
    skills: ['algebra-expresiones', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },

  // Valor numérico con aplicaciones (3)
  {
    id: 'm1-138',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'El perímetro de un rectángulo se calcula con $P = 2l + 2a$. Si $l = 8$ cm y $a = 5$ cm, ¿cuál es el perímetro?',
    questionLatex: '\\text{El perímetro de un rectángulo es } P = 2l + 2a. \\text{ Si } l = 8 \\text{ cm y } a = 5 \\text{ cm, ¿cuál es el perímetro?}',
    options: ['13 cm', '21 cm', '26 cm', '40 cm'],
    correctAnswer: 2,
    explanation: 'Sustituimos los valores en la fórmula:',
    explanationLatex: 'P = 2l + 2a = 2(8) + 2(5) = 16 + 10 = 26 \\text{ cm}',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'algebra-evaluacion-funciones', 'geometria-perimetro', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-139',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'La distancia recorrida es $d = vt$ donde $v$ es velocidad y $t$ es tiempo. Si un auto viaja a $v = 80$ km/h por $t = 2.5$ horas, ¿qué distancia recorre?',
    questionLatex: '\\text{La distancia es } d = vt. \\text{ Si } v = 80 \\text{ km/h y } t = 2.5 \\text{ h, ¿qué distancia recorre?}',
    options: ['160 km', '180 km', '200 km', '220 km'],
    correctAnswer: 2,
    explanation: 'Multiplicamos velocidad por tiempo:',
    explanationLatex: 'd = vt = 80 \\times 2.5 = 200 \\text{ km}',
    difficulty: 'easy',
    skills: ['algebra-expresiones', 'algebra-evaluacion-funciones', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-140',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'La temperatura en Fahrenheit se calcula con $F = \\frac{9}{5}C + 32$. Si $C = 25°$, ¿cuál es la temperatura en Fahrenheit?',
    questionLatex: '\\text{La temperatura es } F = \\frac{9}{5}C + 32. \\text{ Si } C = 25°, \\text{ ¿cuál es } F?',
    options: ['45°F', '57°F', '77°F', '93°F'],
    correctAnswer: 2,
    explanation: 'Sustituimos C = 25 en la fórmula:',
    explanationLatex: 'F = \\frac{9}{5}(25) + 32 = \\frac{225}{5} + 32 = 45 + 32 = 77°F',
    difficulty: 'hard',
    skills: ['algebra-expresiones', 'algebra-evaluacion-funciones', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },

  // BATCH 3: ECUACIONES LINEALES AVANZADAS (9 questions)

  // Ecuaciones con fracciones (3)
  {
    id: 'm1-141',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\frac{x}{2} + \\frac{x}{3} = 10$',
    questionLatex: '\\text{Resolver: } \\frac{x}{2} + \\frac{x}{3} = 10',
    options: ['$x = 6$', '$x = 12$', '$x = 15$', '$x = 20$'],
    optionsLatex: ['x = 6', 'x = 12', 'x = 15', 'x = 20'],
    correctAnswer: 1,
    explanation: 'Encontramos común denominador y despejamos:',
    explanationLatex: '\\frac{x}{2} + \\frac{x}{3} = 10 \\rightarrow \\frac{3x + 2x}{6} = 10 \\rightarrow \\frac{5x}{6} = 10 \\rightarrow x = 12',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-fracciones', 'numeros-fracciones-comun-denominador', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-142',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\frac{2x - 1}{3} = 5$',
    questionLatex: '\\text{Resolver: } \\frac{2x - 1}{3} = 5',
    options: ['$x = 7$', '$x = 8$', '$x = 9$', '$x = 10$'],
    optionsLatex: ['x = 7', 'x = 8', 'x = 9', 'x = 10'],
    correctAnswer: 1,
    explanation: 'Multiplicamos ambos lados por 3 y despejamos:',
    explanationLatex: '\\frac{2x - 1}{3} = 5 \\rightarrow 2x - 1 = 15 \\rightarrow 2x = 16 \\rightarrow x = 8',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-143',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\frac{x + 2}{4} - \\frac{x - 1}{2} = 1$',
    questionLatex: '\\text{Resolver: } \\frac{x + 2}{4} - \\frac{x - 1}{2} = 1',
    options: ['$x = -4$', '$x = -6$', '$x = 4$', '$x = 6$'],
    optionsLatex: ['x = -4', 'x = -6', 'x = 4', 'x = 6'],
    correctAnswer: 1,
    explanation: 'Usamos común denominador 4 y resolvemos:',
    explanationLatex: '\\frac{x + 2}{4} - \\frac{2(x - 1)}{4} = 1 \\rightarrow \\frac{x + 2 - 2x + 2}{4} = 1 \\rightarrow \\frac{4 - x}{4} = 1 \\rightarrow 4 - x = 4 \\rightarrow x = -6',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-fracciones', 'numeros-fracciones-comun-denominador', 'numeros-operaciones-basicas']
  },

  // Ecuaciones con paréntesis (3)
  {
    id: 'm1-144',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $3(x - 2) = 2(x + 1)$',
    questionLatex: '\\text{Resolver: } 3(x - 2) = 2(x + 1)',
    options: ['$x = 6$', '$x = 7$', '$x = 8$', '$x = 9$'],
    optionsLatex: ['x = 6', 'x = 7', 'x = 8', 'x = 9'],
    correctAnswer: 2,
    explanation: 'Aplicamos distributiva en ambos lados y despejamos:',
    explanationLatex: '3(x - 2) = 2(x + 1) \\rightarrow 3x - 6 = 2x + 2 \\rightarrow 3x - 2x = 2 + 6 \\rightarrow x = 8',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'algebra-propiedad-distributiva', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-145',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $4(2x + 1) - 3(x - 2) = 22$',
    questionLatex: '\\text{Resolver: } 4(2x + 1) - 3(x - 2) = 22',
    options: ['$x = 2$', '$x = 3$', '$x = 4$', '$x = 5$'],
    optionsLatex: ['x = 2', 'x = 3', 'x = 4', 'x = 5'],
    correctAnswer: 0,
    explanation: 'Expandimos y simplificamos:',
    explanationLatex: '4(2x + 1) - 3(x - 2) = 22 \\rightarrow 8x + 4 - 3x + 6 = 22 \\rightarrow 5x + 10 = 22 \\rightarrow 5x = 12 \\rightarrow x = 2',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'algebra-propiedad-distributiva', 'algebra-terminos-semejantes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-146',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $2[x - (3 - x)] = 10$',
    questionLatex: '\\text{Resolver: } 2[x - (3 - x)] = 10',
    options: ['$x = 2$', '$x = 3$', '$x = 4$', '$x = 5$'],
    optionsLatex: ['x = 2', 'x = 3', 'x = 4', 'x = 5'],
    correctAnswer: 2,
    explanation: 'Resolvemos el paréntesis interno primero:',
    explanationLatex: '2[x - (3 - x)] = 10 \\rightarrow 2[x - 3 + x] = 10 \\rightarrow 2[2x - 3] = 10 \\rightarrow 4x - 6 = 10 \\rightarrow 4x = 16 \\rightarrow x = 4',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'algebra-propiedad-distributiva', 'numeros-operaciones-basicas']
  },

  // Problemas verbales (edad, consecutivos, perímetro) (3)
  {
    id: 'm1-147',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Pedro tiene el doble de edad que su hermana Ana. Si Ana tiene $x$ años y la suma de sus edades es 36 años, ¿cuántos años tiene Pedro?',
    questionLatex: '\\text{Pedro tiene el doble de edad que Ana. Si Ana tiene } x \\text{ años y la suma es 36 años, ¿cuántos años tiene Pedro?}',
    options: ['12 años', '18 años', '24 años', '30 años'],
    correctAnswer: 2,
    explanation: 'Planteamos la ecuación donde Pedro tiene 2x años:',
    explanationLatex: 'x + 2x = 36 \\rightarrow 3x = 36 \\rightarrow x = 12 \\text{ (Ana)} \\quad \\Rightarrow \\quad \\text{Pedro} = 2(12) = 24 \\text{ años}',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-148',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'La suma de tres números consecutivos es 48. ¿Cuál es el número mayor?',
    questionLatex: '\\text{La suma de tres números consecutivos es 48. ¿Cuál es el número mayor?}',
    options: ['15', '16', '17', '18'],
    correctAnswer: 2,
    explanation: 'Si el primer número es x, los consecutivos son x+1 y x+2:',
    explanationLatex: 'x + (x + 1) + (x + 2) = 48 \\rightarrow 3x + 3 = 48 \\rightarrow 3x = 45 \\rightarrow x = 15 \\quad \\Rightarrow \\quad \\text{mayor} = 15 + 2 = 17',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-149',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Un rectángulo tiene un largo que es 5 cm mayor que su ancho. Si el perímetro es 50 cm, ¿cuál es el ancho?',
    questionLatex: '\\text{Un rectángulo tiene largo 5 cm mayor que el ancho. Si el perímetro es 50 cm, ¿cuál es el ancho?}',
    options: ['8 cm', '10 cm', '12 cm', '15 cm'],
    correctAnswer: 1,
    explanation: 'Si el ancho es x, el largo es x+5. Perímetro: 2x + 2(x+5) = 50:',
    explanationLatex: '2x + 2(x + 5) = 50 \\rightarrow 2x + 2x + 10 = 50 \\rightarrow 4x = 40 \\rightarrow x = 10 \\text{ cm}',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-lineales', 'algebra-despeje', 'geometria-perimetro', 'geometria-rectangulos', 'numeros-operaciones-basicas']
  },

  // BATCH 4: FACTORIZACIÓN (9 questions)

  // Factor común (3)
  {
    id: 'm1-150',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Factorizar: $6x + 9$',
    questionLatex: '\\text{Factorizar: } 6x + 9',
    options: ['$3(2x + 3)$', '$6(x + 9)$', '$3(2x + 9)$', '$2(3x + 3)$'],
    optionsLatex: ['3(2x + 3)', '6(x + 9)', '3(2x + 9)', '2(3x + 3)'],
    correctAnswer: 0,
    explanation: 'Sacamos el factor común 3:',
    explanationLatex: '6x + 9 = 3(2x) + 3(3) = 3(2x + 3)',
    difficulty: 'easy',
    skills: ['algebra-factorizacion', 'numeros-mcd-mcm', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-151',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Factorizar: $4x^2 - 8x$',
    questionLatex: '\\text{Factorizar: } 4x^2 - 8x',
    options: ['$4x(x - 2)$', '$4(x^2 - 2x)$', '$x(4x - 8)$', '$2x(2x - 4)$'],
    optionsLatex: ['4x(x - 2)', '4(x^2 - 2x)', 'x(4x - 8)', '2x(2x - 4)'],
    correctAnswer: 0,
    explanation: 'Sacamos el factor común 4x:',
    explanationLatex: '4x^2 - 8x = 4x(x) - 4x(2) = 4x(x - 2)',
    difficulty: 'easy',
    skills: ['algebra-factorizacion', 'algebra-expresiones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-152',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Factorizar: $6a^3b + 9a^2b^2 - 12ab$',
    questionLatex: '\\text{Factorizar: } 6a^3b + 9a^2b^2 - 12ab',
    options: ['$3ab(2a^2 + 3ab - 4)$', '$6ab(a^2 + ab - 2)$', '$3a(2a^2b + 3ab^2 - 4b)$', '$ab(6a^2 + 9ab - 12)$'],
    optionsLatex: ['3ab(2a^2 + 3ab - 4)', '6ab(a^2 + ab - 2)', '3a(2a^2b + 3ab^2 - 4b)', 'ab(6a^2 + 9ab - 12)'],
    correctAnswer: 0,
    explanation: 'Identificamos el factor común: 3ab es el MCD de los términos:',
    explanationLatex: '6a^3b + 9a^2b^2 - 12ab = 3ab(2a^2) + 3ab(3ab) - 3ab(4) = 3ab(2a^2 + 3ab - 4)',
    difficulty: 'hard',
    skills: ['algebra-factorizacion', 'algebra-expresiones', 'numeros-mcd-mcm', 'numeros-operaciones-basicas']
  },

  // Trinomio cuadrado perfecto (3)
  {
    id: 'm1-153',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Factorizar: $x^2 + 6x + 9$',
    questionLatex: '\\text{Factorizar: } x^2 + 6x + 9',
    options: ['$(x + 3)^2$', '$(x - 3)^2$', '$(x + 3)(x - 3)$', '$(x + 9)(x + 1)$'],
    optionsLatex: ['(x + 3)^2', '(x - 3)^2', '(x + 3)(x - 3)', '(x + 9)(x + 1)'],
    correctAnswer: 0,
    explanation: 'Es un trinomio cuadrado perfecto de la forma $a^2 + 2ab + b^2 = (a + b)^2$:',
    explanationLatex: 'x^2 + 6x + 9 = x^2 + 2(x)(3) + 3^2 = (x + 3)^2',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-154',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Factorizar: $4x^2 - 12x + 9$',
    questionLatex: '\\text{Factorizar: } 4x^2 - 12x + 9',
    options: ['$(2x - 3)^2$', '$(2x + 3)^2$', '$(4x - 3)^2$', '$(x - 3)^2$'],
    optionsLatex: ['(2x - 3)^2', '(2x + 3)^2', '(4x - 3)^2', '(x - 3)^2'],
    correctAnswer: 0,
    explanation: 'Es un trinomio cuadrado perfecto: $a^2 - 2ab + b^2 = (a - b)^2$:',
    explanationLatex: '4x^2 - 12x + 9 = (2x)^2 - 2(2x)(3) + 3^2 = (2x - 3)^2',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-155',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál de las siguientes expresiones es un trinomio cuadrado perfecto?',
    questionLatex: '\\text{¿Cuál de las siguientes expresiones es un trinomio cuadrado perfecto?}',
    options: ['$x^2 + 4x + 4$', '$x^2 + 4x + 2$', '$x^2 + 2x + 4$', '$x^2 + 8x + 4$'],
    optionsLatex: ['x^2 + 4x + 4', 'x^2 + 4x + 2', 'x^2 + 2x + 4', 'x^2 + 8x + 4'],
    correctAnswer: 0,
    explanation: 'Para ser TCP, el tercer término debe ser el cuadrado de la mitad del coeficiente de x:',
    explanationLatex: 'x^2 + 4x + 4 = x^2 + 2(x)(2) + 2^2 = (x + 2)^2 \\text{ es TCP}',
    difficulty: 'hard',
    skills: ['algebra-factorizacion', 'numeros-operaciones-basicas']
  },

  // Factorización de trinomios x² + bx + c (3)
  {
    id: 'm1-156',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Factorizar: $x^2 + 7x + 12$',
    questionLatex: '\\text{Factorizar: } x^2 + 7x + 12',
    options: ['$(x + 3)(x + 4)$', '$(x + 2)(x + 6)$', '$(x + 1)(x + 12)$', '$(x + 3)(x + 5)$'],
    optionsLatex: ['(x + 3)(x + 4)', '(x + 2)(x + 6)', '(x + 1)(x + 12)', '(x + 3)(x + 5)'],
    correctAnswer: 0,
    explanation: 'Buscamos dos números que sumen 7 y multipliquen 12: 3 y 4:',
    explanationLatex: 'x^2 + 7x + 12 = (x + 3)(x + 4) \\quad \\text{porque } 3 + 4 = 7 \\text{ y } 3 \\times 4 = 12',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-157',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Factorizar: $x^2 - 5x + 6$',
    questionLatex: '\\text{Factorizar: } x^2 - 5x + 6',
    options: ['$(x - 2)(x - 3)$', '$(x + 2)(x + 3)$', '$(x - 1)(x - 6)$', '$(x - 2)(x + 3)$'],
    optionsLatex: ['(x - 2)(x - 3)', '(x + 2)(x + 3)', '(x - 1)(x - 6)', '(x - 2)(x + 3)'],
    correctAnswer: 0,
    explanation: 'Buscamos dos números que sumen -5 y multipliquen 6: -2 y -3:',
    explanationLatex: 'x^2 - 5x + 6 = (x - 2)(x - 3) \\quad \\text{porque } (-2) + (-3) = -5 \\text{ y } (-2)(-3) = 6',
    difficulty: 'medium',
    skills: ['algebra-factorizacion', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-158',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Factorizar: $x^2 + 2x - 15$',
    questionLatex: '\\text{Factorizar: } x^2 + 2x - 15',
    options: ['$(x + 5)(x - 3)$', '$(x - 5)(x + 3)$', '$(x + 15)(x - 1)$', '$(x + 3)(x - 5)$'],
    optionsLatex: ['(x + 5)(x - 3)', '(x - 5)(x + 3)', '(x + 15)(x - 1)', '(x + 3)(x - 5)'],
    correctAnswer: 0,
    explanation: 'Buscamos dos números que sumen 2 y multipliquen -15: 5 y -3:',
    explanationLatex: 'x^2 + 2x - 15 = (x + 5)(x - 3) \\quad \\text{porque } 5 + (-3) = 2 \\text{ y } 5(-3) = -15',
    difficulty: 'hard',
    skills: ['algebra-factorizacion', 'numeros-enteros', 'numeros-operaciones-basicas']
  },

  // BATCH 5: PRODUCTOS NOTABLES (9 questions)

  // Cuadrado de binomio (a+b)², (a-b)² (3)
  {
    id: 'm1-159',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Expandir: $(x + 5)^2$',
    questionLatex: '\\text{Expandir: } (x + 5)^2',
    options: ['$x^2 + 25$', '$x^2 + 10x + 25$', '$x^2 + 5x + 25$', '$x^2 + 10x + 10$'],
    optionsLatex: ['x^2 + 25', 'x^2 + 10x + 25', 'x^2 + 5x + 25', 'x^2 + 10x + 10'],
    correctAnswer: 1,
    explanation: 'Aplicamos la fórmula del cuadrado de un binomio: $(a + b)^2 = a^2 + 2ab + b^2$',
    explanationLatex: '(x + 5)^2 = x^2 + 2(x)(5) + 5^2 = x^2 + 10x + 25',
    difficulty: 'easy',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-160',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Expandir: $(2x - 3)^2$',
    questionLatex: '\\text{Expandir: } (2x - 3)^2',
    options: ['$4x^2 - 12x + 9$', '$4x^2 + 12x + 9$', '$4x^2 - 6x + 9$', '$2x^2 - 6x + 9$'],
    optionsLatex: ['4x^2 - 12x + 9', '4x^2 + 12x + 9', '4x^2 - 6x + 9', '2x^2 - 6x + 9'],
    correctAnswer: 0,
    explanation: 'Aplicamos $(a - b)^2 = a^2 - 2ab + b^2$:',
    explanationLatex: '(2x - 3)^2 = (2x)^2 - 2(2x)(3) + 3^2 = 4x^2 - 12x + 9',
    difficulty: 'medium',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-161',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'María quiere expandir $(3a + 2b)^2$. ¿Cuál es el resultado correcto?',
    questionLatex: '\\text{María quiere expandir } (3a + 2b)^2. \\text{ ¿Cuál es el resultado correcto?}',
    options: ['$9a^2 + 4b^2$', '$9a^2 + 6ab + 4b^2$', '$9a^2 + 12ab + 4b^2$', '$3a^2 + 12ab + 2b^2$'],
    optionsLatex: ['9a^2 + 4b^2', '9a^2 + 6ab + 4b^2', '9a^2 + 12ab + 4b^2', '3a^2 + 12ab + 2b^2'],
    correctAnswer: 2,
    explanation: 'Aplicamos $(a + b)^2 = a^2 + 2ab + b^2$ con a = 3a y b = 2b:',
    explanationLatex: '(3a + 2b)^2 = (3a)^2 + 2(3a)(2b) + (2b)^2 = 9a^2 + 12ab + 4b^2',
    difficulty: 'hard',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-operaciones-basicas']
  },

  // Suma por diferencia (a+b)(a-b) (3)
  {
    id: 'm1-162',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Expandir: $(x + 4)(x - 4)$',
    questionLatex: '\\text{Expandir: } (x + 4)(x - 4)',
    options: ['$x^2 - 16$', '$x^2 + 16$', '$x^2 - 8x - 16$', '$x^2 + 8x - 16$'],
    optionsLatex: ['x^2 - 16', 'x^2 + 16', 'x^2 - 8x - 16', 'x^2 + 8x - 16'],
    correctAnswer: 0,
    explanation: 'Aplicamos la diferencia de cuadrados: $(a + b)(a - b) = a^2 - b^2$',
    explanationLatex: '(x + 4)(x - 4) = x^2 - 4^2 = x^2 - 16',
    difficulty: 'easy',
    skills: ['algebra-productos-notables', 'algebra-diferencia-cuadrados', 'algebra-expansion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-163',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Calcular: $(3x + 5)(3x - 5)$',
    questionLatex: '\\text{Calcular: } (3x + 5)(3x - 5)',
    options: ['$3x^2 - 25$', '$9x^2 - 25$', '$9x^2 - 30x - 25$', '$9x^2 + 25$'],
    optionsLatex: ['3x^2 - 25', '9x^2 - 25', '9x^2 - 30x - 25', '9x^2 + 25'],
    correctAnswer: 1,
    explanation: 'Aplicamos $(a + b)(a - b) = a^2 - b^2$ con a = 3x y b = 5:',
    explanationLatex: '(3x + 5)(3x - 5) = (3x)^2 - 5^2 = 9x^2 - 25',
    difficulty: 'medium',
    skills: ['algebra-productos-notables', 'algebra-diferencia-cuadrados', 'algebra-expansion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-164',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Un terreno cuadrado de lado $x$ metros se expande $3$ metros en una dirección pero se reduce $3$ metros en la otra. ¿Cuál es el área del terreno rectangular resultante?',
    questionLatex: '\\text{Un terreno cuadrado de lado } x \\text{ m se expande 3 m en una dirección pero se reduce 3 m en la otra. ¿Cuál es el área?}',
    options: ['$x^2$ m²', '$x^2 - 9$ m²', '$x^2 + 9$ m²', '$x^2 - 6x - 9$ m²'],
    optionsLatex: ['x^2 \\text{ m}^2', 'x^2 - 9 \\text{ m}^2', 'x^2 + 9 \\text{ m}^2', 'x^2 - 6x - 9 \\text{ m}^2'],
    correctAnswer: 1,
    explanation: 'El área es (x + 3)(x - 3), que es una diferencia de cuadrados:',
    explanationLatex: '\\text{Área} = (x + 3)(x - 3) = x^2 - 9 \\text{ m}^2',
    difficulty: 'hard',
    skills: ['algebra-productos-notables', 'algebra-diferencia-cuadrados', 'geometria-area', 'numeros-operaciones-basicas']
  },

  // Cubo de binomio (a+b)³, (a-b)³ (3)
  {
    id: 'm1-165',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Expandir: $(x + 2)^3$',
    questionLatex: '\\text{Expandir: } (x + 2)^3',
    options: ['$x^3 + 6x^2 + 12x + 8$', '$x^3 + 8$', '$x^3 + 2x^2 + 4x + 8$', '$x^3 + 6x^2 + 8x + 8$'],
    optionsLatex: ['x^3 + 6x^2 + 12x + 8', 'x^3 + 8', 'x^3 + 2x^2 + 4x + 8', 'x^3 + 6x^2 + 8x + 8'],
    correctAnswer: 0,
    explanation: 'Aplicamos $(a + b)^3 = a^3 + 3a^2b + 3ab^2 + b^3$:',
    explanationLatex: '(x + 2)^3 = x^3 + 3x^2(2) + 3x(2^2) + 2^3 = x^3 + 6x^2 + 12x + 8',
    difficulty: 'medium',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-166',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Expandir: $(x - 1)^3$',
    questionLatex: '\\text{Expandir: } (x - 1)^3',
    options: ['$x^3 - 3x^2 + 3x - 1$', '$x^3 - 1$', '$x^3 - x^2 - x - 1$', '$x^3 + 3x^2 - 3x + 1$'],
    optionsLatex: ['x^3 - 3x^2 + 3x - 1', 'x^3 - 1', 'x^3 - x^2 - x - 1', 'x^3 + 3x^2 - 3x + 1'],
    correctAnswer: 0,
    explanation: 'Aplicamos $(a - b)^3 = a^3 - 3a^2b + 3ab^2 - b^3$:',
    explanationLatex: '(x - 1)^3 = x^3 - 3x^2(1) + 3x(1^2) - 1^3 = x^3 - 3x^2 + 3x - 1',
    difficulty: 'medium',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-167',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el coeficiente del término $x^2$ en la expansión de $(2x + 1)^3$?',
    questionLatex: '\\text{¿Cuál es el coeficiente del término } x^2 \\text{ en la expansión de } (2x + 1)^3?',
    options: ['6', '12', '24', '8'],
    correctAnswer: 1,
    explanation: 'Expandimos usando $(a + b)^3 = a^3 + 3a^2b + 3ab^2 + b^3$:',
    explanationLatex: '(2x + 1)^3 = (2x)^3 + 3(2x)^2(1) + 3(2x)(1)^2 + 1^3 = 8x^3 + 12x^2 + 6x + 1',
    difficulty: 'hard',
    skills: ['algebra-productos-notables', 'algebra-expansion', 'numeros-potencias', 'numeros-operaciones-basicas']
  },

  // BATCH 6: FUNCIONES - DOMINIO, RANGO, TIPOS (9 questions)

  // Identificación de funciones (3)
  {
    id: 'm1-168',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál de las siguientes relaciones es una función?',
    questionLatex: '\\text{¿Cuál de las siguientes relaciones es una función?}',
    options: ['$\\{(1, 2), (1, 3), (2, 4)\\}$', '$\\{(1, 2), (2, 2), (3, 4)\\}$', '$\\{(1, 2), (2, 3), (1, 4)\\}$', '$\\{(1, 2), (1, 5), (3, 2)\\}$'],
    optionsLatex: ['\\{(1, 2), (1, 3), (2, 4)\\}', '\\{(1, 2), (2, 2), (3, 4)\\}', '\\{(1, 2), (2, 3), (1, 4)\\}', '\\{(1, 2), (1, 5), (3, 2)\\}'],
    correctAnswer: 1,
    explanation: 'Una función asigna exactamente un valor de salida a cada entrada. Solo la opción B cumple esta condición:',
    explanationLatex: '\\text{En una función, cada valor de } x \\text{ tiene exactamente un valor de } y. \\text{ Solo B cumple.}',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-relaciones-funciones']
  },
  {
    id: 'm1-169',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $f(x) = 3x - 4$, ¿cuál es el dominio de la función?',
    questionLatex: '\\text{Si } f(x) = 3x - 4, \\text{ ¿cuál es el dominio de la función?}',
    options: ['Todos los números reales', 'Solo números positivos', 'Solo números mayores que 4', 'Solo números enteros'],
    correctAnswer: 0,
    explanation: 'Una función lineal está definida para todos los números reales:',
    explanationLatex: '\\text{Dom}(f) = \\mathbb{R} \\text{ porque no hay restricciones para } x',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-dominio-rango', 'algebra-funciones-lineales']
  },
  {
    id: 'm1-170',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $g(x) = x^2$ y el dominio es $\\{-2, -1, 0, 1, 2\\}$, ¿cuál es el rango?',
    questionLatex: '\\text{Si } g(x) = x^2 \\text{ y el dominio es } \\{-2, -1, 0, 1, 2\\}, \\text{ ¿cuál es el rango?}',
    options: ['$\\{0, 1, 2, 4\\}$', '$\\{-2, -1, 0, 1, 2\\}$', '$\\{0, 1, 4\\}$', '$\\{1, 2, 4\\}$'],
    optionsLatex: ['\\{0, 1, 2, 4\\}', '\\{-2, -1, 0, 1, 2\\}', '\\{0, 1, 4\\}', '\\{1, 2, 4\\}'],
    correctAnswer: 0,
    explanation: 'Evaluamos la función para cada valor del dominio:',
    explanationLatex: 'g(-2) = 4, g(-1) = 1, g(0) = 0, g(1) = 1, g(2) = 4 \\quad \\Rightarrow \\quad \\text{Rango} = \\{0, 1, 4\\}',
    difficulty: 'medium',
    skills: ['algebra-funciones', 'algebra-dominio-rango', 'algebra-evaluacion-funciones', 'numeros-potencias']
  },

  // Tipos de funciones (3)
  {
    id: 'm1-171',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál de las siguientes funciones es una función lineal?',
    questionLatex: '\\text{¿Cuál de las siguientes funciones es una función lineal?}',
    options: ['$f(x) = x^2 + 1$', '$f(x) = 2x - 5$', '$f(x) = \\frac{1}{x}$', '$f(x) = 3$'],
    optionsLatex: ['f(x) = x^2 + 1', 'f(x) = 2x - 5', 'f(x) = \\frac{1}{x}', 'f(x) = 3'],
    correctAnswer: 1,
    explanation: 'Una función lineal tiene la forma $f(x) = mx + b$ donde $m \\neq 0$:',
    explanationLatex: 'f(x) = 2x - 5 \\text{ tiene la forma } mx + b \\text{ con } m = 2 \\text{ y } b = -5',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-funciones-lineales']
  },
  {
    id: 'm1-172',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Una función constante tiene la forma $f(x) = c$. ¿Cuál es el rango de $f(x) = 7$?',
    questionLatex: '\\text{Una función constante tiene la forma } f(x) = c. \\text{ ¿Cuál es el rango de } f(x) = 7?',
    options: ['$\\{7\\}$', 'Todos los números reales', '$\\{0, 7\\}$', '$\\{x : x \\geq 7\\}$'],
    optionsLatex: ['\\{7\\}', '\\text{Todos los números reales}', '\\{0, 7\\}', '\\{x : x \\geq 7\\}'],
    correctAnswer: 0,
    explanation: 'Una función constante siempre devuelve el mismo valor:',
    explanationLatex: '\\text{Para todo } x, f(x) = 7 \\quad \\Rightarrow \\quad \\text{Rango} = \\{7\\}',
    difficulty: 'medium',
    skills: ['algebra-funciones', 'algebra-dominio-rango', 'algebra-funciones-lineales']
  },
  {
    id: 'm1-173',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Carlos estudia una función $h(x) = ax^2 + bx + c$ donde $a \\neq 0$. ¿Qué tipo de función es?',
    questionLatex: '\\text{Carlos estudia } h(x) = ax^2 + bx + c \\text{ donde } a \\neq 0. \\text{ ¿Qué tipo de función es?}',
    options: ['Función lineal', 'Función cuadrática', 'Función constante', 'Función exponencial'],
    correctAnswer: 1,
    explanation: 'La forma $ax^2 + bx + c$ con $a \\neq 0$ define una función cuadrática:',
    explanationLatex: 'h(x) = ax^2 + bx + c \\text{ es cuadrática porque el término de mayor grado es } x^2',
    difficulty: 'medium',
    skills: ['algebra-funciones', 'algebra-funciones-cuadraticas']
  },

  // Dominio y rango de funciones específicas (3)
  {
    id: 'm1-174',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el dominio de $f(x) = \\frac{1}{x - 3}$?',
    questionLatex: '\\text{¿Cuál es el dominio de } f(x) = \\frac{1}{x - 3}?',
    options: ['Todos los reales excepto 3', 'Todos los reales excepto 0', 'Todos los reales mayores que 3', 'Todos los reales'],
    correctAnswer: 0,
    explanation: 'El denominador no puede ser cero, entonces $x - 3 \\neq 0$:',
    explanationLatex: 'x - 3 \\neq 0 \\quad \\Rightarrow \\quad x \\neq 3 \\quad \\therefore \\quad \\text{Dom}(f) = \\mathbb{R} - \\{3\\}',
    difficulty: 'medium',
    skills: ['algebra-funciones', 'algebra-dominio-rango', 'algebra-funciones-racionales']
  },
  {
    id: 'm1-175',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el dominio de $g(x) = \\sqrt{x - 2}$?',
    questionLatex: '\\text{¿Cuál es el dominio de } g(x) = \\sqrt{x - 2}?',
    options: ['$x \\geq 2$', '$x > 2$', '$x \\geq -2$', 'Todos los reales'],
    optionsLatex: ['x \\geq 2', 'x > 2', 'x \\geq -2', '\\text{Todos los reales}'],
    correctAnswer: 0,
    explanation: 'La raíz cuadrada solo está definida para valores no negativos:',
    explanationLatex: 'x - 2 \\geq 0 \\quad \\Rightarrow \\quad x \\geq 2 \\quad \\therefore \\quad \\text{Dom}(g) = [2, \\infty)',
    difficulty: 'hard',
    skills: ['algebra-funciones', 'algebra-dominio-rango', 'algebra-desigualdades', 'numeros-raices']
  },
  {
    id: 'm1-176',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si $f(x) = -x^2 + 4$, ¿cuál es el valor máximo de la función (el mayor valor del rango)?',
    questionLatex: '\\text{Si } f(x) = -x^2 + 4, \\text{ ¿cuál es el valor máximo de la función?}',
    options: ['0', '2', '4', 'No tiene máximo'],
    correctAnswer: 2,
    explanation: 'La función es una parábola que abre hacia abajo. El máximo ocurre cuando $x = 0$:',
    explanationLatex: 'f(0) = -(0)^2 + 4 = 4 \\text{ es el valor máximo porque } -x^2 \\leq 0 \\text{ para todo } x',
    difficulty: 'hard',
    skills: ['algebra-funciones', 'algebra-dominio-rango', 'algebra-funciones-cuadraticas', 'numeros-potencias']
  },

  // BATCH 7: FUNCIONES - GRÁFICAS E INTERCEPTOS (6 questions)

  // Interceptos y/x (3)
  {
    id: 'm1-177',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el intercepto con el eje $y$ de la función $f(x) = 2x - 6$?',
    questionLatex: '\\text{¿Cuál es el intercepto con el eje } y \\text{ de la función } f(x) = 2x - 6?',
    options: ['-6', '-3', '2', '6'],
    correctAnswer: 0,
    explanation: 'El intercepto con el eje $y$ ocurre cuando $x = 0$:',
    explanationLatex: 'f(0) = 2(0) - 6 = -6 \\quad \\Rightarrow \\quad \\text{Intercepto en } (0, -6)',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-interceptos', 'algebra-funciones-lineales']
  },
  {
    id: 'm1-178',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el intercepto con el eje $x$ de la función $g(x) = 3x + 9$?',
    questionLatex: '\\text{¿Cuál es el intercepto con el eje } x \\text{ de la función } g(x) = 3x + 9?',
    options: ['-3', '3', '9', '-9'],
    correctAnswer: 0,
    explanation: 'El intercepto con el eje $x$ ocurre cuando $g(x) = 0$:',
    explanationLatex: '3x + 9 = 0 \\rightarrow 3x = -9 \\rightarrow x = -3 \\quad \\Rightarrow \\quad \\text{Intercepto en } (-3, 0)',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-interceptos', 'algebra-funciones-lineales', 'algebra-ecuaciones-lineales']
  },
  {
    id: 'm1-179',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Una recta tiene ecuación $y = -2x + 8$. ¿En qué punto la recta cruza el eje $x$?',
    questionLatex: '\\text{Una recta tiene ecuación } y = -2x + 8. \\text{ ¿En qué punto cruza el eje } x?',
    options: ['$(4, 0)$', '$(0, 8)$', '$(-4, 0)$', '$(8, 0)$'],
    optionsLatex: ['(4, 0)', '(0, 8)', '(-4, 0)', '(8, 0)'],
    correctAnswer: 0,
    explanation: 'Para encontrar el intercepto con $x$, hacemos $y = 0$:',
    explanationLatex: '0 = -2x + 8 \\rightarrow 2x = 8 \\rightarrow x = 4 \\quad \\Rightarrow \\quad (4, 0)',
    difficulty: 'medium',
    skills: ['algebra-funciones', 'algebra-interceptos', 'algebra-funciones-lineales', 'algebra-ecuaciones-lineales']
  },

  // Interpretación de gráficas (3)
  {
    id: 'm1-180',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si la gráfica de $f(x)$ pasa por el punto $(3, 7)$, ¿cuál es el valor de $f(3)$?',
    questionLatex: '\\text{Si la gráfica de } f(x) \\text{ pasa por el punto } (3, 7), \\text{ ¿cuál es el valor de } f(3)?',
    options: ['3', '7', '10', '21'],
    correctAnswer: 1,
    explanation: 'Si la gráfica pasa por $(a, b)$, entonces $f(a) = b$:',
    explanationLatex: '\\text{El punto } (3, 7) \\text{ significa que cuando } x = 3, y = 7 \\quad \\therefore \\quad f(3) = 7',
    difficulty: 'easy',
    skills: ['algebra-funciones', 'algebra-evaluacion-funciones', 'algebra-graficas']
  },
  {
    id: 'm1-181',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Una función lineal tiene intercepto en $y$ igual a $5$ y pendiente $m = -1$. ¿Cuál es su ecuación?',
    questionLatex: '\\text{Una función lineal tiene intercepto en } y \\text{ igual a } 5 \\text{ y pendiente } m = -1. \\text{ ¿Cuál es su ecuación?}',
    options: ['$y = -x + 5$', '$y = x + 5$', '$y = -x - 5$', '$y = 5x - 1$'],
    optionsLatex: ['y = -x + 5', 'y = x + 5', 'y = -x - 5', 'y = 5x - 1'],
    correctAnswer: 0,
    explanation: 'Usamos la forma $y = mx + b$ donde $m$ es la pendiente y $b$ el intercepto en $y$:',
    explanationLatex: 'y = mx + b = -1 \\cdot x + 5 = -x + 5',
    difficulty: 'medium',
    skills: ['algebra-funciones', 'algebra-funciones-lineales', 'algebra-pendiente', 'algebra-interceptos']
  },
  {
    id: 'm1-182',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si la pendiente de una recta que pasa por los puntos $(2, 5)$ y $(4, 9)$ es $m$, ¿cuál es el valor de $m$?',
    questionLatex: '\\text{Si la pendiente de una recta que pasa por } (2, 5) \\text{ y } (4, 9) \\text{ es } m, \\text{ ¿cuál es } m?',
    options: ['1', '2', '3', '4'],
    correctAnswer: 1,
    explanation: 'La pendiente se calcula con $m = \\frac{y_2 - y_1}{x_2 - x_1}$:',
    explanationLatex: 'm = \\frac{9 - 5}{4 - 2} = \\frac{4}{2} = 2',
    difficulty: 'hard',
    skills: ['algebra-funciones', 'algebra-funciones-lineales', 'algebra-pendiente', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },

  // BATCH 8: SISTEMAS DE ECUACIONES (9 questions)

  // Sistemas 2x2 por sustitución (3)
  {
    id: 'm1-183',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver el sistema: $\\begin{cases} y = 2x \\\\ x + y = 6 \\end{cases}$',
    questionLatex: '\\text{Resolver el sistema: } \\begin{cases} y = 2x \\\\ x + y = 6 \\end{cases}',
    options: ['$x = 2, y = 4$', '$x = 3, y = 3$', '$x = 4, y = 2$', '$x = 1, y = 5$'],
    optionsLatex: ['x = 2, y = 4', 'x = 3, y = 3', 'x = 4, y = 2', 'x = 1, y = 5'],
    correctAnswer: 0,
    explanation: 'Sustituimos $y = 2x$ en la segunda ecuación:',
    explanationLatex: 'x + 2x = 6 \\rightarrow 3x = 6 \\rightarrow x = 2 \\quad \\Rightarrow \\quad y = 2(2) = 4',
    difficulty: 'easy',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-184',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\begin{cases} x = y + 1 \\\\ 2x + y = 8 \\end{cases}$',
    questionLatex: '\\text{Resolver: } \\begin{cases} x = y + 1 \\\\ 2x + y = 8 \\end{cases}',
    options: ['$x = 2, y = 1$', '$x = 3, y = 2$', '$x = 4, y = 3$', '$x = 5, y = 4$'],
    optionsLatex: ['x = 2, y = 1', 'x = 3, y = 2', 'x = 4, y = 3', 'x = 5, y = 4'],
    correctAnswer: 1,
    explanation: 'Sustituimos $x = y + 1$ en la segunda ecuación:',
    explanationLatex: '2(y + 1) + y = 8 \\rightarrow 2y + 2 + y = 8 \\rightarrow 3y = 6 \\rightarrow y = 2 \\quad \\Rightarrow \\quad x = 2 + 1 = 3',
    difficulty: 'medium',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-ecuaciones-lineales', 'algebra-propiedad-distributiva', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-185',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\begin{cases} y = 3x - 1 \\\\ 2x - y = 5 \\end{cases}$',
    questionLatex: '\\text{Resolver: } \\begin{cases} y = 3x - 1 \\\\ 2x - y = 5 \\end{cases}',
    options: ['$x = 4, y = 11$', '$x = 6, y = 17$', '$x = 3, y = 8$', '$x = 5, y = 14$'],
    optionsLatex: ['x = 4, y = 11', 'x = 6, y = 17', 'x = 3, y = 8', 'x = 5, y = 14'],
    correctAnswer: 0,
    explanation: 'Sustituimos $y = 3x - 1$ en la segunda ecuación:',
    explanationLatex: '2x - (3x - 1) = 5 \\rightarrow 2x - 3x + 1 = 5 \\rightarrow -x = 4 \\rightarrow x = 4 \\quad \\Rightarrow \\quad y = 3(4) - 1 = 11',
    difficulty: 'medium',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-ecuaciones-lineales', 'numeros-enteros', 'numeros-operaciones-basicas']
  },

  // Sistemas 2x2 por eliminación (3)
  {
    id: 'm1-186',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver por eliminación: $\\begin{cases} x + y = 7 \\\\ x - y = 3 \\end{cases}$',
    questionLatex: '\\text{Resolver por eliminación: } \\begin{cases} x + y = 7 \\\\ x - y = 3 \\end{cases}',
    options: ['$x = 5, y = 2$', '$x = 4, y = 3$', '$x = 6, y = 1$', '$x = 3, y = 4$'],
    optionsLatex: ['x = 5, y = 2', 'x = 4, y = 3', 'x = 6, y = 1', 'x = 3, y = 4'],
    correctAnswer: 0,
    explanation: 'Sumamos ambas ecuaciones para eliminar $y$:',
    explanationLatex: '(x + y) + (x - y) = 7 + 3 \\rightarrow 2x = 10 \\rightarrow x = 5 \\quad \\Rightarrow \\quad 5 + y = 7 \\rightarrow y = 2',
    difficulty: 'easy',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-187',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\begin{cases} 2x + y = 10 \\\\ 2x - y = 6 \\end{cases}$',
    questionLatex: '\\text{Resolver: } \\begin{cases} 2x + y = 10 \\\\ 2x - y = 6 \\end{cases}',
    options: ['$x = 4, y = 2$', '$x = 3, y = 4$', '$x = 5, y = 0$', '$x = 2, y = 6$'],
    optionsLatex: ['x = 4, y = 2', 'x = 3, y = 4', 'x = 5, y = 0', 'x = 2, y = 6'],
    correctAnswer: 0,
    explanation: 'Sumamos las ecuaciones para eliminar $y$:',
    explanationLatex: '(2x + y) + (2x - y) = 10 + 6 \\rightarrow 4x = 16 \\rightarrow x = 4 \\quad \\Rightarrow \\quad 2(4) + y = 10 \\rightarrow y = 2',
    difficulty: 'medium',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-188',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $\\begin{cases} 3x + 2y = 13 \\\\ 3x - y = 7 \\end{cases}$',
    questionLatex: '\\text{Resolver: } \\begin{cases} 3x + 2y = 13 \\\\ 3x - y = 7 \\end{cases}',
    options: ['$x = 2, y = 5$', '$x = 3, y = 2$', '$x = 4, y = 2$', '$x = 2, y = 3$'],
    optionsLatex: ['x = 2, y = 5', 'x = 3, y = 2', 'x = 4, y = 2', 'x = 2, y = 3'],
    correctAnswer: 1,
    explanation: 'Restamos la segunda ecuación de la primera para eliminar $3x$:',
    explanationLatex: '(3x + 2y) - (3x - y) = 13 - 7 \\rightarrow 3y = 6 \\rightarrow y = 2 \\quad \\Rightarrow \\quad 3x - 2 = 7 \\rightarrow x = 3',
    difficulty: 'hard',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },

  // Problemas verbales con sistemas (3)
  {
    id: 'm1-189',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'En una tienda, 2 cuadernos y 3 lápices cuestan $2.100. Si 1 cuaderno y 1 lápiz cuestan $900, ¿cuánto cuesta un cuaderno?',
    questionLatex: '\\text{2 cuadernos y 3 lápices cuestan \\$2.100. 1 cuaderno y 1 lápiz cuestan \\$900. ¿Cuánto cuesta un cuaderno?}',
    options: ['$500', '$600', '$700', '$800'],
    correctAnswer: 1,
    explanation: 'Planteamos el sistema con $c$ = cuaderno y $l$ = lápiz:',
    explanationLatex: '\\begin{cases} 2c + 3l = 2100 \\\\ c + l = 900 \\end{cases} \\rightarrow l = 900 - c \\rightarrow 2c + 3(900 - c) = 2100 \\rightarrow c = 600',
    difficulty: 'medium',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-190',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'La suma de dos números es 50 y su diferencia es 10. ¿Cuál es el número mayor?',
    questionLatex: '\\text{La suma de dos números es 50 y su diferencia es 10. ¿Cuál es el número mayor?}',
    options: ['25', '30', '35', '40'],
    correctAnswer: 1,
    explanation: 'Planteamos el sistema con $x$ e $y$ como los números:',
    explanationLatex: '\\begin{cases} x + y = 50 \\\\ x - y = 10 \\end{cases} \\rightarrow 2x = 60 \\rightarrow x = 30 \\text{ (número mayor)}',
    difficulty: 'easy',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-191',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Un estacionamiento cobra $a$ pesos por hora para autos y $m$ pesos por hora para motos. Si 3 autos y 2 motos pagan $5.000 en total, y 1 auto y 1 moto pagan $1.800, ¿cuánto cobra por hora para un auto?',
    questionLatex: '\\text{3 autos y 2 motos: \\$5.000. 1 auto y 1 moto: \\$1.800. ¿Cuánto cobra por auto?}',
    options: ['$600', '$800', '$1.000', '$1.200'],
    optionsLatex: ['\\$600', '\\$800', '\\$1.000', '\\$1.200'],
    correctAnswer: 3,
    explanation: 'Planteamos el sistema y resolvemos:',
    explanationLatex: '\\begin{cases} 3a + 2m = 5000 \\\\ a + m = 1800 \\end{cases} \\rightarrow m = 1800 - a \\rightarrow 3a + 2(1800 - a) = 5000 \\rightarrow a = 1200',
    difficulty: 'hard',
    skills: ['algebra-sistemas-ecuaciones', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },

  // BATCH 9: ECUACIONES CUADRÁTICAS (9 questions)

  // Solución por factorización (3)
  {
    id: 'm1-192',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver la ecuación: $x^2 - 5x + 6 = 0$',
    questionLatex: '\\text{Resolver la ecuación: } x^2 - 5x + 6 = 0',
    options: ['$x = 2$ o $x = 3$', '$x = 1$ o $x = 6$', '$x = -2$ o $x = -3$', '$x = 5$ o $x = 6$'],
    optionsLatex: ['x = 2 \\text{ o } x = 3', 'x = 1 \\text{ o } x = 6', 'x = -2 \\text{ o } x = -3', 'x = 5 \\text{ o } x = 6'],
    correctAnswer: 0,
    explanation: 'Factorizamos y usamos la propiedad del producto cero:',
    explanationLatex: 'x^2 - 5x + 6 = (x - 2)(x - 3) = 0 \\quad \\Rightarrow \\quad x = 2 \\text{ o } x = 3',
    difficulty: 'easy',
    skills: ['algebra-ecuaciones-cuadraticas', 'algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-193',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $x^2 + 7x + 10 = 0$',
    questionLatex: '\\text{Resolver: } x^2 + 7x + 10 = 0',
    options: ['$x = -2$ o $x = -5$', '$x = 2$ o $x = 5$', '$x = -1$ o $x = -10$', '$x = 1$ o $x = 10$'],
    optionsLatex: ['x = -2 \\text{ o } x = -5', 'x = 2 \\text{ o } x = 5', 'x = -1 \\text{ o } x = -10', 'x = 1 \\text{ o } x = 10'],
    correctAnswer: 0,
    explanation: 'Factorizamos y encontramos las raíces:',
    explanationLatex: 'x^2 + 7x + 10 = (x + 2)(x + 5) = 0 \\quad \\Rightarrow \\quad x = -2 \\text{ o } x = -5',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-cuadraticas', 'algebra-factorizacion', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-194',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Resolver: $x^2 - 9 = 0$',
    questionLatex: '\\text{Resolver: } x^2 - 9 = 0',
    options: ['$x = 3$ o $x = -3$', '$x = 9$ o $x = -9$', '$x = 3$ solamente', '$x = 9$ solamente'],
    optionsLatex: ['x = 3 \\text{ o } x = -3', 'x = 9 \\text{ o } x = -9', 'x = 3 \\text{ solamente}', 'x = 9 \\text{ solamente}'],
    correctAnswer: 0,
    explanation: 'Es una diferencia de cuadrados:',
    explanationLatex: 'x^2 - 9 = (x - 3)(x + 3) = 0 \\quad \\Rightarrow \\quad x = 3 \\text{ o } x = -3',
    difficulty: 'easy',
    skills: ['algebra-ecuaciones-cuadraticas', 'algebra-factorizacion', 'algebra-diferencia-cuadrados', 'numeros-raices']
  },

  // Fórmula cuadrática (3)
  {
    id: 'm1-195',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Usar la fórmula cuadrática para resolver: $x^2 + 2x - 3 = 0$',
    questionLatex: '\\text{Usar la fórmula cuadrática para resolver: } x^2 + 2x - 3 = 0',
    options: ['$x = 1$ o $x = -3$', '$x = -1$ o $x = 3$', '$x = 2$ o $x = -3$', '$x = -2$ o $x = 3$'],
    optionsLatex: ['x = 1 \\text{ o } x = -3', 'x = -1 \\text{ o } x = 3', 'x = 2 \\text{ o } x = -3', 'x = -2 \\text{ o } x = 3'],
    correctAnswer: 0,
    explanation: 'Aplicamos $x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}$ con $a=1, b=2, c=-3$:',
    explanationLatex: 'x = \\frac{-2 \\pm \\sqrt{4 + 12}}{2} = \\frac{-2 \\pm 4}{2} \\quad \\Rightarrow \\quad x = 1 \\text{ o } x = -3',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-cuadraticas', 'algebra-formula-cuadratica', 'numeros-raices', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-196',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: '¿Cuál es el discriminante de $x^2 - 4x + 4 = 0$?',
    questionLatex: '\\text{¿Cuál es el discriminante de } x^2 - 4x + 4 = 0?',
    options: ['0', '4', '8', '16'],
    correctAnswer: 0,
    explanation: 'El discriminante es $\\Delta = b^2 - 4ac$:',
    explanationLatex: '\\Delta = (-4)^2 - 4(1)(4) = 16 - 16 = 0 \\text{ (una raíz doble)}',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-cuadraticas', 'algebra-discriminante', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-197',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'Si el discriminante de una ecuación cuadrática es negativo, ¿qué podemos concluir sobre sus soluciones?',
    questionLatex: '\\text{Si el discriminante de una ecuación cuadrática es negativo, ¿qué podemos concluir?}',
    options: ['No tiene soluciones reales', 'Tiene dos soluciones reales distintas', 'Tiene una solución real', 'Tiene infinitas soluciones'],
    correctAnswer: 0,
    explanation: 'Un discriminante negativo indica que no hay raíces reales:',
    explanationLatex: '\\Delta < 0 \\quad \\Rightarrow \\quad \\text{No existen soluciones reales (las soluciones son complejas)}',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-cuadraticas', 'algebra-discriminante']
  },

  // Problemas de aplicación (3)
  {
    id: 'm1-198',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'La ecuación $h(t) = -5t^2 + 20t$ representa la altura de un objeto. ¿En qué tiempos $t$ el objeto está en el suelo ($h = 0$)?',
    questionLatex: '\\text{La ecuación } h(t) = -5t^2 + 20t \\text{ representa la altura. ¿Cuándo } h = 0?',
    options: ['$t = 0$ o $t = 4$', '$t = 0$ o $t = 5$', '$t = 2$ o $t = 4$', '$t = 1$ o $t = 4$'],
    optionsLatex: ['t = 0 \\text{ o } t = 4', 't = 0 \\text{ o } t = 5', 't = 2 \\text{ o } t = 4', 't = 1 \\text{ o } t = 4'],
    correctAnswer: 0,
    explanation: 'Resolvemos $-5t^2 + 20t = 0$:',
    explanationLatex: '-5t(t - 4) = 0 \\quad \\Rightarrow \\quad t = 0 \\text{ (lanzamiento) o } t = 4 \\text{ (aterrizaje)}',
    difficulty: 'medium',
    skills: ['algebra-ecuaciones-cuadraticas', 'algebra-factorizacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-199',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'El área de un rectángulo es 24 m². Si el largo es $x + 2$ y el ancho es $x$, ¿cuál es el valor de $x$?',
    questionLatex: '\\text{Área = 24 m}^2. \\text{ Largo = } x + 2, \\text{ ancho = } x. \\text{ ¿Cuál es } x?',
    options: ['4 m', '5 m', '6 m', '8 m'],
    correctAnswer: 0,
    explanation: 'Planteamos $x(x + 2) = 24$:',
    explanationLatex: 'x^2 + 2x = 24 \\rightarrow x^2 + 2x - 24 = 0 \\rightarrow (x + 6)(x - 4) = 0 \\quad \\Rightarrow \\quad x = 4 \\text{ (positivo)}',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-cuadraticas', 'algebra-factorizacion', 'geometria-area', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-200',
    level: 'M1',
    topic: 'Álgebra y Funciones',
    subject: 'álgebra',
    question: 'La parábola $y = x^2 - 6x + 8$ cruza el eje $x$ en dos puntos. ¿Cuáles son las coordenadas de esos puntos?',
    questionLatex: '\\text{La parábola } y = x^2 - 6x + 8 \\text{ cruza el eje } x \\text{ en dos puntos. ¿Cuáles son?}',
    options: ['$(2, 0)$ y $(4, 0)$', '$(1, 0)$ y $(8, 0)$', '$(-2, 0)$ y $(-4, 0)$', '$(3, 0)$ y $(6, 0)$'],
    optionsLatex: ['(2, 0) \\text{ y } (4, 0)', '(1, 0) \\text{ y } (8, 0)', '(-2, 0) \\text{ y } (-4, 0)', '(3, 0) \\text{ y } (6, 0)'],
    correctAnswer: 0,
    explanation: 'Resolvemos $x^2 - 6x + 8 = 0$ para encontrar los interceptos con $x$:',
    explanationLatex: 'x^2 - 6x + 8 = (x - 2)(x - 4) = 0 \\quad \\Rightarrow \\quad x = 2 \\text{ o } x = 4',
    difficulty: 'hard',
    skills: ['algebra-ecuaciones-cuadraticas', 'algebra-factorizacion', 'algebra-funciones-cuadraticas', 'algebra-interceptos', 'numeros-operaciones-basicas']
  }
];
