import { Question } from '../types';

export const m1NumerosQuestions: Question[] = [
  // EXISTING QUESTIONS (10)
  {
    id: 'm1-1',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Si 3 obreros construyen un muro en 12 días, ¿cuántos días tardarán 4 obreros en construir el mismo muro?',
    questionLatex: '\\text{Si 3 obreros construyen un muro en 12 días, ¿cuántos días tardarán 4 obreros en construir el mismo muro?}',
    options: ['8 días', '9 días', '10 días', '16 días'],
    correctAnswer: 1,
    explanation: 'Es una proporción inversa. Si aumentan los obreros, disminuyen los días.',
    explanationLatex: '3 \\times 12 = 4 \\times x \\text{, entonces } x = \\frac{36}{4} = 9 \\text{ días}',
    difficulty: 'easy',
    skills: ['numeros-proporcionalidad', 'numeros-proporcionalidad-inversa', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-7',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'El 25% de 80 es igual a:',
    questionLatex: '\\text{El 25\\% de 80 es igual a:}',
    options: ['15', '20', '25', '30'],
    correctAnswer: 1,
    explanation: 'Calculamos el porcentaje:',
    explanationLatex: '25\\% \\text{ de } 80 = 0.25 \\times 80 = 20',
    difficulty: 'easy',
    skills: ['numeros-porcentajes', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-9',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $\\frac{2}{3} + \\frac{1}{4}$?',
    questionLatex: '\\text{¿Cuál es el resultado de } \\frac{2}{3} + \\frac{1}{4}?',
    options: ['$\\frac{3}{7}$', '$\\frac{11}{12}$', '$\\frac{5}{6}$', '$\\frac{3}{4}$'],
    optionsLatex: ['\\frac{3}{7}', '\\frac{11}{12}', '\\frac{5}{6}', '\\frac{3}{4}'],
    correctAnswer: 1,
    explanation: 'Para sumar fracciones, necesitamos un denominador común:',
    explanationLatex: '\\frac{2}{3} + \\frac{1}{4} = \\frac{8}{12} + \\frac{3}{12} = \\frac{11}{12}',
    difficulty: 'easy',
    skills: ['numeros-fracciones', 'numeros-fracciones-suma', 'numeros-fracciones-comun-denominador', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-10',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el valor de $\\sqrt{49}$?',
    questionLatex: '\\text{¿Cuál es el valor de } \\sqrt{49}?',
    options: ['6', '7', '8', '24.5'],
    correctAnswer: 1,
    explanation: 'La raíz cuadrada de 49 es el número que multiplicado por sí mismo da 49:',
    explanationLatex: '\\sqrt{49} = 7 \\text{ porque } 7 \\times 7 = 49',
    difficulty: 'easy',
    skills: ['numeros-raices', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-11',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el Máximo Común Divisor (MCD) de 12 y 18?',
    questionLatex: '\\text{¿Cuál es el Máximo Común Divisor (MCD) de 12 y 18?}',
    options: ['2', '3', '6', '36'],
    correctAnswer: 2,
    explanation: 'Factorizamos ambos números y encontramos los factores comunes:',
    explanationLatex: '12 = 2^2 \\times 3, \\quad 18 = 2 \\times 3^2 \\quad \\Rightarrow \\quad \\text{MCD} = 2 \\times 3 = 6',
    difficulty: 'medium',
    skills: ['numeros-mcd-mcm', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-12',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $2^4$?',
    questionLatex: '\\text{¿Cuál es el resultado de } 2^4?',
    options: ['8', '16', '24', '32'],
    correctAnswer: 1,
    explanation: 'Multiplicamos 2 por sí mismo 4 veces:',
    explanationLatex: '2^4 = 2 \\times 2 \\times 2 \\times 2 = 16',
    difficulty: 'easy',
    skills: ['numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-26',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $(-3) \\times (-5)$?',
    questionLatex: '\\text{¿Cuál es el resultado de } (-3) \\times (-5)?',
    options: ['-15', '-8', '8', '15'],
    correctAnswer: 3,
    explanation: 'El producto de dos números negativos es positivo:',
    explanationLatex: '(-3) \\times (-5) = 15',
    difficulty: 'easy',
    skills: ['numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-27',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Una camisa cuesta $20.000 y tiene un descuento del 15%. ¿Cuál es el precio final?',
    questionLatex: '\\text{Una camisa cuesta \\$20.000 y tiene un descuento del 15\\%. ¿Cuál es el precio final?}',
    options: ['$15.000', '$17.000', '$17.500', '$18.000'],
    correctAnswer: 1,
    explanation: 'Calculamos el 15% de descuento y lo restamos del precio original:',
    explanationLatex: '20.000 \\times 0.15 = 3.000 \\quad \\Rightarrow \\quad 20.000 - 3.000 = 17.000',
    difficulty: 'easy',
    skills: ['numeros-porcentajes', 'numeros-porcentajes-descuentos', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-28',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Si $\\frac{3}{4}$ de un número es 15, ¿cuál es el número?',
    questionLatex: '\\text{Si } \\frac{3}{4} \\text{ de un número es 15, ¿cuál es el número?}',
    options: ['12', '18', '20', '24'],
    correctAnswer: 2,
    explanation: 'Planteamos la ecuación y despejamos:',
    explanationLatex: '\\frac{3}{4}x = 15 \\quad \\Rightarrow \\quad x = 15 \\times \\frac{4}{3} = 20',
    difficulty: 'medium',
    skills: ['numeros-fracciones', 'algebra-ecuaciones-lineales', 'algebra-despeje', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-29',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el valor de $\\frac{2^3 \\times 2^2}{2^4}$?',
    questionLatex: '\\text{¿Cuál es el valor de } \\frac{2^3 \\times 2^2}{2^4}?',
    options: ['2', '4', '8', '16'],
    correctAnswer: 0,
    explanation: 'Usamos las propiedades de los exponentes:',
    explanationLatex: '\\frac{2^3 \\times 2^2}{2^4} = \\frac{2^{3+2}}{2^4} = \\frac{2^5}{2^4} = 2^{5-4} = 2^1 = 2',
    difficulty: 'medium',
    skills: ['numeros-potencias', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },

  // NEW QUESTIONS: CATEGORY 1 - RATIONAL NUMBERS (15 questions)

  // Fraction Multiplication/Division (3)
  {
    id: 'm1-42',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $\\frac{2}{3} \\times \\frac{5}{4}$?',
    questionLatex: '\\text{¿Cuál es el resultado de } \\frac{2}{3} \\times \\frac{5}{4}?',
    options: ['$\\frac{7}{12}$', '$\\frac{10}{12}$', '$\\frac{5}{6}$', '$\\frac{10}{7}$'],
    optionsLatex: ['\\frac{7}{12}', '\\frac{10}{12}', '\\frac{5}{6}', '\\frac{10}{7}'],
    correctAnswer: 2,
    explanation: 'Para multiplicar fracciones, multiplicamos numerador por numerador y denominador por denominador:',
    explanationLatex: '\\frac{2}{3} \\times \\frac{5}{4} = \\frac{2 \\times 5}{3 \\times 4} = \\frac{10}{12} = \\frac{5}{6}',
    difficulty: 'easy',
    skills: ['numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-43',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $\\frac{3}{4} \\div \\frac{2}{5}$?',
    questionLatex: '\\text{¿Cuál es el resultado de } \\frac{3}{4} \\div \\frac{2}{5}?',
    options: ['$\\frac{6}{20}$', '$\\frac{5}{8}$', '$\\frac{15}{8}$', '$\\frac{8}{15}$'],
    optionsLatex: ['\\frac{6}{20}', '\\frac{5}{8}', '\\frac{15}{8}', '\\frac{8}{15}'],
    correctAnswer: 2,
    explanation: 'Para dividir fracciones, multiplicamos por el recíproco (invertimos la segunda fracción):',
    explanationLatex: '\\frac{3}{4} \\div \\frac{2}{5} = \\frac{3}{4} \\times \\frac{5}{2} = \\frac{15}{8}',
    difficulty: 'medium',
    skills: ['numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-44',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'María tiene $\\frac{2}{3}$ de un pastel y lo divide en 4 partes iguales. ¿Qué fracción del pastel completo es cada parte?',
    questionLatex: '\\text{María tiene } \\frac{2}{3} \\text{ de un pastel y lo divide en 4 partes iguales. ¿Qué fracción del pastel completo es cada parte?}',
    options: ['$\\frac{1}{6}$', '$\\frac{2}{12}$', '$\\frac{1}{8}$', '$\\frac{8}{3}$'],
    optionsLatex: ['\\frac{1}{6}', '\\frac{2}{12}', '\\frac{1}{8}', '\\frac{8}{3}'],
    correctAnswer: 0,
    explanation: 'Dividir una fracción entre un número entero es multiplicar por su recíproco:',
    explanationLatex: '\\frac{2}{3} \\div 4 = \\frac{2}{3} \\times \\frac{1}{4} = \\frac{2}{12} = \\frac{1}{6}',
    difficulty: 'medium',
    skills: ['numeros-fracciones', 'numeros-operaciones-basicas']
  },

  // Mixed Numbers (3)
  {
    id: 'm1-45',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Convierte el número mixto $2\\frac{3}{5}$ a fracción impropia:',
    questionLatex: '\\text{Convierte el número mixto } 2\\frac{3}{5} \\text{ a fracción impropia:}',
    options: ['$\\frac{8}{5}$', '$\\frac{11}{5}$', '$\\frac{13}{5}$', '$\\frac{6}{5}$'],
    optionsLatex: ['\\frac{8}{5}', '\\frac{11}{5}', '\\frac{13}{5}', '\\frac{6}{5}'],
    correctAnswer: 2,
    explanation: 'Multiplicamos el entero por el denominador y sumamos el numerador:',
    explanationLatex: '2\\frac{3}{5} = \\frac{(2 \\times 5) + 3}{5} = \\frac{10 + 3}{5} = \\frac{13}{5}',
    difficulty: 'easy',
    skills: ['numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-46',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Convierte la fracción impropia $\\frac{17}{4}$ a número mixto:',
    questionLatex: '\\text{Convierte la fracción impropia } \\frac{17}{4} \\text{ a número mixto:}',
    options: ['$4\\frac{1}{4}$', '$3\\frac{5}{4}$', '$4\\frac{1}{17}$', '$5\\frac{2}{4}$'],
    optionsLatex: ['4\\frac{1}{4}', '3\\frac{5}{4}', '4\\frac{1}{17}', '5\\frac{2}{4}'],
    correctAnswer: 0,
    explanation: 'Dividimos el numerador entre el denominador:',
    explanationLatex: '17 \\div 4 = 4 \\text{ con resto } 1 \\quad \\Rightarrow \\quad \\frac{17}{4} = 4\\frac{1}{4}',
    difficulty: 'easy',
    skills: ['numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-47',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $1\\frac{2}{3} + 2\\frac{1}{4}$?',
    questionLatex: '\\text{¿Cuál es el resultado de } 1\\frac{2}{3} + 2\\frac{1}{4}?',
    options: ['$3\\frac{3}{7}$', '$3\\frac{11}{12}$', '$4\\frac{5}{12}$', '$3\\frac{5}{12}$'],
    optionsLatex: ['3\\frac{3}{7}', '3\\frac{11}{12}', '4\\frac{5}{12}', '3\\frac{5}{12}'],
    correctAnswer: 1,
    explanation: 'Sumamos los enteros y las fracciones por separado:',
    explanationLatex: '(1 + 2) + \\left(\\frac{2}{3} + \\frac{1}{4}\\right) = 3 + \\frac{8}{12} + \\frac{3}{12} = 3\\frac{11}{12}',
    difficulty: 'medium',
    skills: ['numeros-fracciones', 'numeros-fracciones-suma', 'numeros-fracciones-comun-denominador', 'numeros-operaciones-basicas']
  },

  // Comparing Fractions (3)
  {
    id: 'm1-48',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál de las siguientes fracciones es mayor?',
    questionLatex: '\\text{¿Cuál de las siguientes fracciones es mayor?}',
    options: ['$\\frac{3}{4}$', '$\\frac{5}{6}$', '$\\frac{2}{3}$', '$\\frac{7}{12}$'],
    optionsLatex: ['\\frac{3}{4}', '\\frac{5}{6}', '\\frac{2}{3}', '\\frac{7}{12}'],
    correctAnswer: 1,
    explanation: 'Buscamos un denominador común (12) y comparamos:',
    explanationLatex: '\\frac{3}{4} = \\frac{9}{12}, \\quad \\frac{5}{6} = \\frac{10}{12}, \\quad \\frac{2}{3} = \\frac{8}{12}, \\quad \\frac{7}{12} = \\frac{7}{12} \\quad \\Rightarrow \\quad \\frac{5}{6} \\text{ es mayor}',
    difficulty: 'medium',
    skills: ['numeros-fracciones', 'numeros-fracciones-comun-denominador', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-49',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Ordena las fracciones de menor a mayor: $\\frac{1}{2}, \\frac{3}{5}, \\frac{2}{3}$',
    questionLatex: '\\text{Ordena las fracciones de menor a mayor: } \\frac{1}{2}, \\frac{3}{5}, \\frac{2}{3}',
    options: ['$\\frac{1}{2}, \\frac{3}{5}, \\frac{2}{3}$', '$\\frac{3}{5}, \\frac{1}{2}, \\frac{2}{3}$', '$\\frac{2}{3}, \\frac{3}{5}, \\frac{1}{2}$', '$\\frac{1}{2}, \\frac{2}{3}, \\frac{3}{5}$'],
    optionsLatex: ['\\frac{1}{2}, \\frac{3}{5}, \\frac{2}{3}', '\\frac{3}{5}, \\frac{1}{2}, \\frac{2}{3}', '\\frac{2}{3}, \\frac{3}{5}, \\frac{1}{2}', '\\frac{1}{2}, \\frac{2}{3}, \\frac{3}{5}'],
    correctAnswer: 0,
    explanation: 'Convertimos a denominador común (30):',
    explanationLatex: '\\frac{1}{2} = \\frac{15}{30}, \\quad \\frac{3}{5} = \\frac{18}{30}, \\quad \\frac{2}{3} = \\frac{20}{30} \\quad \\Rightarrow \\quad \\frac{1}{2} < \\frac{3}{5} < \\frac{2}{3}',
    difficulty: 'medium',
    skills: ['numeros-fracciones', 'numeros-fracciones-comun-denominador', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-50',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Qué fracción es equivalente a $\\frac{4}{6}$?',
    questionLatex: '\\text{¿Qué fracción es equivalente a } \\frac{4}{6}?',
    options: ['$\\frac{3}{4}$', '$\\frac{2}{3}$', '$\\frac{6}{8}$', '$\\frac{8}{10}$'],
    optionsLatex: ['\\frac{3}{4}', '\\frac{2}{3}', '\\frac{6}{8}', '\\frac{8}{10}'],
    correctAnswer: 1,
    explanation: 'Simplificamos dividiendo numerador y denominador por su MCD (2):',
    explanationLatex: '\\frac{4}{6} = \\frac{4 \\div 2}{6 \\div 2} = \\frac{2}{3}',
    difficulty: 'easy',
    skills: ['numeros-fracciones', 'numeros-mcd-mcm', 'numeros-operaciones-basicas']
  },

  // Converting Decimals ↔ Fractions (3)
  {
    id: 'm1-51',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Convierte el decimal 0.75 a fracción:',
    questionLatex: '\\text{Convierte el decimal 0.75 a fracción:}',
    options: ['$\\frac{3}{4}$', '$\\frac{7}{5}$', '$\\frac{75}{10}$', '$\\frac{15}{20}$'],
    optionsLatex: ['\\frac{3}{4}', '\\frac{7}{5}', '\\frac{75}{10}', '\\frac{15}{20}'],
    correctAnswer: 0,
    explanation: 'Escribimos el decimal como fracción y simplificamos:',
    explanationLatex: '0.75 = \\frac{75}{100} = \\frac{75 \\div 25}{100 \\div 25} = \\frac{3}{4}',
    difficulty: 'easy',
    skills: ['numeros-decimales', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-52',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Convierte la fracción $\\frac{7}{8}$ a decimal:',
    questionLatex: '\\text{Convierte la fracción } \\frac{7}{8} \\text{ a decimal:}',
    options: ['0.78', '0.875', '0.85', '0.7'],
    correctAnswer: 1,
    explanation: 'Dividimos el numerador entre el denominador:',
    explanationLatex: '\\frac{7}{8} = 7 \\div 8 = 0.875',
    difficulty: 'easy',
    skills: ['numeros-decimales', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-53',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Convierte el decimal 0.625 a fracción simplificada:',
    questionLatex: '\\text{Convierte el decimal 0.625 a fracción simplificada:}',
    options: ['$\\frac{5}{8}$', '$\\frac{625}{100}$', '$\\frac{25}{40}$', '$\\frac{3}{5}$'],
    optionsLatex: ['\\frac{5}{8}', '\\frac{625}{100}', '\\frac{25}{40}', '\\frac{3}{5}'],
    correctAnswer: 0,
    explanation: 'Convertimos y simplificamos:',
    explanationLatex: '0.625 = \\frac{625}{1000} = \\frac{625 \\div 125}{1000 \\div 125} = \\frac{5}{8}',
    difficulty: 'medium',
    skills: ['numeros-decimales', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },

  // Repeating Decimals (3)
  {
    id: 'm1-54',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'El decimal periódico $0.\\overline{3}$ (0.333...) es equivalente a:',
    questionLatex: '\\text{El decimal periódico } 0.\\overline{3} \\text{ (0.333...) es equivalente a:}',
    options: ['$\\frac{1}{3}$', '$\\frac{3}{10}$', '$\\frac{33}{100}$', '$\\frac{3}{9}$'],
    optionsLatex: ['\\frac{1}{3}', '\\frac{3}{10}', '\\frac{33}{100}', '\\frac{3}{9}'],
    correctAnswer: 0,
    explanation: 'El decimal periódico 0.333... es la fracción:',
    explanationLatex: '0.\\overline{3} = \\frac{1}{3}',
    difficulty: 'medium',
    skills: ['numeros-decimales', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-55',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál de las siguientes fracciones genera un decimal periódico?',
    questionLatex: '\\text{¿Cuál de las siguientes fracciones genera un decimal periódico?}',
    options: ['$\\frac{1}{4}$', '$\\frac{1}{5}$', '$\\frac{1}{3}$', '$\\frac{1}{8}$'],
    optionsLatex: ['\\frac{1}{4}', '\\frac{1}{5}', '\\frac{1}{3}', '\\frac{1}{8}'],
    correctAnswer: 2,
    explanation: 'Un decimal es periódico cuando el denominador tiene factores primos diferentes de 2 y 5:',
    explanationLatex: '\\frac{1}{3} = 0.\\overline{3} \\text{ (periódico). Las otras: } \\frac{1}{4}=0.25, \\frac{1}{5}=0.2, \\frac{1}{8}=0.125',
    difficulty: 'hard',
    skills: ['numeros-decimales', 'numeros-fracciones', 'numeros-factorizacion-prima', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-56',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'El decimal periódico $0.\\overline{6}$ (0.666...) es equivalente a:',
    questionLatex: '\\text{El decimal periódico } 0.\\overline{6} \\text{ (0.666...) es equivalente a:}',
    options: ['$\\frac{2}{3}$', '$\\frac{6}{10}$', '$\\frac{66}{100}$', '$\\frac{6}{9}$'],
    optionsLatex: ['\\frac{2}{3}', '\\frac{6}{10}', '\\frac{66}{100}', '\\frac{6}{9}'],
    correctAnswer: 0,
    explanation: 'El decimal periódico se convierte:',
    explanationLatex: '0.\\overline{6} = \\frac{6}{9} = \\frac{2}{3}',
    difficulty: 'medium',
    skills: ['numeros-decimales', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },

  // NEW QUESTIONS: CATEGORY 2 - NUMBER PROPERTIES (12 questions)

  // Prime/Composite Numbers (3)
  {
    id: 'm1-57',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál de los siguientes números es primo?',
    questionLatex: '\\text{¿Cuál de los siguientes números es primo?}',
    options: ['15', '17', '21', '25'],
    correctAnswer: 1,
    explanation: 'Un número primo solo es divisible por 1 y por sí mismo:',
    explanationLatex: '17 \\text{ es primo. } 15=3\\times5, \\quad 21=3\\times7, \\quad 25=5\\times5',
    difficulty: 'easy',
    skills: ['numeros-factorizacion-prima', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-58',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuántos números primos hay entre 1 y 10?',
    questionLatex: '\\text{¿Cuántos números primos hay entre 1 y 10?}',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    explanation: 'Los números primos entre 1 y 10 son:',
    explanationLatex: '2, 3, 5, 7 \\quad \\Rightarrow \\quad 4 \\text{ números primos}',
    difficulty: 'easy',
    skills: ['numeros-factorizacion-prima', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-59',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el número primo más pequeño mayor que 20?',
    questionLatex: '\\text{¿Cuál es el número primo más pequeño mayor que 20?}',
    options: ['21', '22', '23', '25'],
    correctAnswer: 2,
    explanation: 'Verificamos cada número:',
    explanationLatex: '21=3\\times7, \\quad 22=2\\times11, \\quad 23 \\text{ es primo}, \\quad 25=5\\times5',
    difficulty: 'medium',
    skills: ['numeros-factorizacion-prima', 'numeros-operaciones-basicas']
  },

  // Prime Factorization (3)
  {
    id: 'm1-60',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es la factorización prima de 24?',
    questionLatex: '\\text{¿Cuál es la factorización prima de 24?}',
    options: ['$2 \\times 12$', '$2^3 \\times 3$', '$4 \\times 6$', '$2^2 \\times 6$'],
    optionsLatex: ['2 \\times 12', '2^3 \\times 3', '4 \\times 6', '2^2 \\times 6'],
    correctAnswer: 1,
    explanation: 'Descomponemos 24 en sus factores primos:',
    explanationLatex: '24 = 2 \\times 12 = 2 \\times 2 \\times 6 = 2 \\times 2 \\times 2 \\times 3 = 2^3 \\times 3',
    difficulty: 'easy',
    skills: ['numeros-factorizacion-prima', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-61',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Si $60 = 2^2 \\times 3 \\times 5$, ¿cuál es la factorización prima de 30?',
    questionLatex: '\\text{Si } 60 = 2^2 \\times 3 \\times 5, \\text{ ¿cuál es la factorización prima de 30?}',
    options: ['$2 \\times 3 \\times 5$', '$2^2 \\times 3$', '$3 \\times 10$', '$2 \\times 15$'],
    optionsLatex: ['2 \\times 3 \\times 5', '2^2 \\times 3', '3 \\times 10', '2 \\times 15'],
    correctAnswer: 0,
    explanation: '30 es la mitad de 60, entonces quitamos un factor de 2:',
    explanationLatex: '30 = \\frac{60}{2} = \\frac{2^2 \\times 3 \\times 5}{2} = 2 \\times 3 \\times 5',
    difficulty: 'medium',
    skills: ['numeros-factorizacion-prima', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-62',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es la factorización prima de 72?',
    questionLatex: '\\text{¿Cuál es la factorización prima de 72?}',
    options: ['$2^3 \\times 3^2$', '$2^2 \\times 3^3$', '$8 \\times 9$', '$2^4 \\times 3$'],
    optionsLatex: ['2^3 \\times 3^2', '2^2 \\times 3^3', '8 \\times 9', '2^4 \\times 3'],
    correctAnswer: 0,
    explanation: 'Descomponemos completamente en factores primos:',
    explanationLatex: '72 = 8 \\times 9 = (2^3) \\times (3^2) = 2^3 \\times 3^2',
    difficulty: 'medium',
    skills: ['numeros-factorizacion-prima', 'numeros-potencias', 'numeros-operaciones-basicas']
  },

  // LCM (3)
  {
    id: 'm1-63',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el Mínimo Común Múltiplo (MCM) de 4 y 6?',
    questionLatex: '\\text{¿Cuál es el Mínimo Común Múltiplo (MCM) de 4 y 6?}',
    options: ['10', '12', '24', '2'],
    correctAnswer: 1,
    explanation: 'Encontramos el múltiplo común más pequeño:',
    explanationLatex: '\\text{Múltiplos de 4: } 4, 8, 12, 16... \\quad \\text{Múltiplos de 6: } 6, 12, 18... \\quad \\Rightarrow \\quad \\text{MCM} = 12',
    difficulty: 'easy',
    skills: ['numeros-mcd-mcm', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-64',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el MCM de 8, 12 y 18?',
    questionLatex: '\\text{¿Cuál es el MCM de 8, 12 y 18?}',
    options: ['36', '48', '72', '144'],
    correctAnswer: 2,
    explanation: 'Factorizamos y tomamos los factores con mayor exponente:',
    explanationLatex: '8=2^3, \\quad 12=2^2\\times3, \\quad 18=2\\times3^2 \\quad \\Rightarrow \\quad \\text{MCM} = 2^3\\times3^2 = 72',
    difficulty: 'hard',
    skills: ['numeros-mcd-mcm', 'numeros-factorizacion-prima', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-65',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Dos buses salen de la estación al mismo tiempo. Uno pasa cada 15 minutos y el otro cada 20 minutos. ¿En cuántos minutos volverán a coincidir en la estación?',
    questionLatex: '\\text{Dos buses salen de la estación al mismo tiempo. Uno pasa cada 15 minutos y el otro cada 20 minutos. ¿En cuántos minutos volverán a coincidir?}',
    options: ['30 minutos', '35 minutos', '60 minutos', '300 minutos'],
    correctAnswer: 2,
    explanation: 'Necesitamos el MCM de 15 y 20:',
    explanationLatex: '15 = 3 \\times 5, \\quad 20 = 2^2 \\times 5 \\quad \\Rightarrow \\quad \\text{MCM} = 2^2 \\times 3 \\times 5 = 60',
    difficulty: 'medium',
    skills: ['numeros-mcd-mcm', 'numeros-factorizacion-prima', 'numeros-operaciones-basicas']
  },

  // Divisibility Rules (3)
  {
    id: 'm1-66',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál de los siguientes números es divisible por 3?',
    questionLatex: '\\text{¿Cuál de los siguientes números es divisible por 3?}',
    options: ['124', '235', '342', '455'],
    correctAnswer: 2,
    explanation: 'Un número es divisible por 3 si la suma de sus dígitos es divisible por 3:',
    explanationLatex: '342: \\quad 3+4+2 = 9 \\text{ (divisible por 3)} \\quad \\Rightarrow \\quad 342 \\text{ es divisible por 3}',
    difficulty: 'easy',
    skills: ['numeros-operaciones-basicas']
  },
  {
    id: 'm1-67',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál de los siguientes números es divisible por 9?',
    questionLatex: '\\text{¿Cuál de los siguientes números es divisible por 9?}',
    options: ['234', '567', '729', '891'],
    correctAnswer: 2,
    explanation: 'Un número es divisible por 9 si la suma de sus dígitos es divisible por 9:',
    explanationLatex: '729: \\quad 7+2+9 = 18 \\text{ (divisible por 9)} \\quad \\Rightarrow \\quad 729 \\text{ es divisible por 9}',
    difficulty: 'medium',
    skills: ['numeros-operaciones-basicas']
  },
  {
    id: 'm1-68',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Un número de tres dígitos es divisible por 11 si:',
    questionLatex: '\\text{Un número de tres dígitos es divisible por 11 si:}',
    options: ['La suma de sus dígitos es 11', 'La diferencia entre la suma de dígitos en posiciones impares y pares es 0 o múltiplo de 11', 'El último dígito es 1', 'La suma de sus dígitos es divisible por 11'],
    correctAnswer: 1,
    explanation: 'Regla de divisibilidad por 11:',
    explanationLatex: '\\text{Ejemplo: } 121 \\rightarrow (1+1)-2 = 0 \\text{ (divisible por 11)}',
    difficulty: 'hard',
    skills: ['numeros-operaciones-basicas']
  },

  // NEW QUESTIONS: CATEGORY 3 - EXPONENTS & ROOTS (15 questions)

  // Negative Exponents (3)
  {
    id: 'm1-69',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el valor de $2^{-3}$?',
    questionLatex: '\\text{¿Cuál es el valor de } 2^{-3}?',
    options: ['$-8$', '$-6$', '$\\frac{1}{8}$', '$\\frac{1}{6}$'],
    optionsLatex: ['-8', '-6', '\\frac{1}{8}', '\\frac{1}{6}'],
    correctAnswer: 2,
    explanation: 'Un exponente negativo indica el recíproco:',
    explanationLatex: '2^{-3} = \\frac{1}{2^3} = \\frac{1}{8}',
    difficulty: 'medium',
    skills: ['numeros-potencias', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-70',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $5^{-2} \\times 5^5$?',
    questionLatex: '\\text{¿Cuál es el resultado de } 5^{-2} \\times 5^5?',
    options: ['$5^3$', '$5^{-7}$', '$5^{10}$', '$25$'],
    optionsLatex: ['5^3', '5^{-7}', '5^{10}', '25'],
    correctAnswer: 0,
    explanation: 'Sumamos los exponentes al multiplicar potencias de igual base:',
    explanationLatex: '5^{-2} \\times 5^5 = 5^{-2+5} = 5^3',
    difficulty: 'medium',
    skills: ['numeros-potencias', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-71',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Simplifica: $\\frac{3^4}{3^6}$',
    questionLatex: '\\text{Simplifica: } \\frac{3^4}{3^6}',
    options: ['$3^2$', '$3^{-2}$', '$9$', '$\\frac{1}{9}$'],
    optionsLatex: ['3^2', '3^{-2}', '9', '\\frac{1}{9}'],
    correctAnswer: 3,
    explanation: 'Restamos los exponentes al dividir potencias de igual base:',
    explanationLatex: '\\frac{3^4}{3^6} = 3^{4-6} = 3^{-2} = \\frac{1}{3^2} = \\frac{1}{9}',
    difficulty: 'hard',
    skills: ['numeros-potencias', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },

  // Fractional Exponents (3)
  {
    id: 'm1-72',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el valor de $16^{1/2}$?',
    questionLatex: '\\text{¿Cuál es el valor de } 16^{1/2}?',
    options: ['4', '8', '2', '32'],
    correctAnswer: 0,
    explanation: 'Un exponente fraccionario 1/2 representa la raíz cuadrada:',
    explanationLatex: '16^{1/2} = \\sqrt{16} = 4',
    difficulty: 'easy',
    skills: ['numeros-potencias', 'numeros-potencias-propiedades', 'numeros-raices', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-73',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el valor de $8^{1/3}$?',
    questionLatex: '\\text{¿Cuál es el valor de } 8^{1/3}?',
    options: ['2', '3', '4', '$\\frac{8}{3}$'],
    optionsLatex: ['2', '3', '4', '\\frac{8}{3}'],
    correctAnswer: 0,
    explanation: 'Un exponente 1/3 representa la raíz cúbica:',
    explanationLatex: '8^{1/3} = \\sqrt[3]{8} = 2 \\text{ porque } 2^3 = 8',
    difficulty: 'medium',
    skills: ['numeros-potencias', 'numeros-potencias-propiedades', 'numeros-raices', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-74',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el valor de $27^{2/3}$?',
    questionLatex: '\\text{¿Cuál es el valor de } 27^{2/3}?',
    options: ['3', '6', '9', '18'],
    correctAnswer: 2,
    explanation: 'El exponente fraccionario indica raíz cúbica y luego elevar al cuadrado:',
    explanationLatex: '27^{2/3} = (\\sqrt[3]{27})^2 = 3^2 = 9',
    difficulty: 'hard',
    skills: ['numeros-potencias', 'numeros-potencias-propiedades', 'numeros-raices', 'numeros-operaciones-basicas']
  },

  // Cube Roots (3)
  {
    id: 'm1-75',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el valor de $\\sqrt[3]{64}$?',
    questionLatex: '\\text{¿Cuál es el valor de } \\sqrt[3]{64}?',
    options: ['3', '4', '8', '21.3'],
    correctAnswer: 1,
    explanation: 'La raíz cúbica es el número que elevado al cubo da 64:',
    explanationLatex: '\\sqrt[3]{64} = 4 \\text{ porque } 4^3 = 64',
    difficulty: 'easy',
    skills: ['numeros-raices', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-76',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el valor de $\\sqrt[3]{-27}$?',
    questionLatex: '\\text{¿Cuál es el valor de } \\sqrt[3]{-27}?',
    options: ['$-3$', '$3$', 'No existe', '$-9$'],
    optionsLatex: ['-3', '3', '\\text{No existe}', '-9'],
    correctAnswer: 0,
    explanation: 'Las raíces cúbicas de números negativos existen y son negativas:',
    explanationLatex: '\\sqrt[3]{-27} = -3 \\text{ porque } (-3)^3 = -27',
    difficulty: 'medium',
    skills: ['numeros-raices', 'numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-77',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Si $\\sqrt[3]{x} = 5$, ¿cuál es el valor de $x$?',
    questionLatex: '\\text{Si } \\sqrt[3]{x} = 5, \\text{ ¿cuál es el valor de } x?',
    options: ['15', '25', '125', '625'],
    correctAnswer: 2,
    explanation: 'Elevamos ambos lados al cubo:',
    explanationLatex: '\\sqrt[3]{x} = 5 \\quad \\Rightarrow \\quad x = 5^3 = 125',
    difficulty: 'medium',
    skills: ['numeros-raices', 'numeros-potencias', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },

  // Simplifying Radicals (3)
  {
    id: 'm1-78',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Simplifica: $\\sqrt{50}$',
    questionLatex: '\\text{Simplifica: } \\sqrt{50}',
    options: ['$5\\sqrt{2}$', '$2\\sqrt{5}$', '$10\\sqrt{5}$', '$25\\sqrt{2}$'],
    optionsLatex: ['5\\sqrt{2}', '2\\sqrt{5}', '10\\sqrt{5}', '25\\sqrt{2}'],
    correctAnswer: 0,
    explanation: 'Factorizamos y sacamos los cuadrados perfectos:',
    explanationLatex: '\\sqrt{50} = \\sqrt{25 \\times 2} = \\sqrt{25} \\times \\sqrt{2} = 5\\sqrt{2}',
    difficulty: 'medium',
    skills: ['numeros-raices', 'numeros-factorizacion-prima', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-79',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Simplifica: $\\sqrt{72}$',
    questionLatex: '\\text{Simplifica: } \\sqrt{72}',
    options: ['$6\\sqrt{2}$', '$8\\sqrt{9}$', '$36\\sqrt{2}$', '$9\\sqrt{8}$'],
    optionsLatex: ['6\\sqrt{2}', '8\\sqrt{9}', '36\\sqrt{2}', '9\\sqrt{8}'],
    correctAnswer: 0,
    explanation: 'Factorizamos 72 y simplificamos:',
    explanationLatex: '\\sqrt{72} = \\sqrt{36 \\times 2} = 6\\sqrt{2}',
    difficulty: 'medium',
    skills: ['numeros-raices', 'numeros-factorizacion-prima', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-80',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $\\sqrt{18} + \\sqrt{8}$?',
    questionLatex: '\\text{¿Cuál es el resultado de } \\sqrt{18} + \\sqrt{8}?',
    options: ['$\\sqrt{26}$', '$5\\sqrt{2}$', '$\\sqrt{10}$', '$3\\sqrt{2} + 2\\sqrt{2}$'],
    optionsLatex: ['\\sqrt{26}', '5\\sqrt{2}', '\\sqrt{10}', '3\\sqrt{2} + 2\\sqrt{2}'],
    correctAnswer: 1,
    explanation: 'Simplificamos cada radical y sumamos:',
    explanationLatex: '\\sqrt{18} + \\sqrt{8} = 3\\sqrt{2} + 2\\sqrt{2} = 5\\sqrt{2}',
    difficulty: 'hard',
    skills: ['numeros-raices', 'numeros-factorizacion-prima', 'numeros-operaciones-basicas']
  },

  // Scientific Notation (3)
  {
    id: 'm1-81',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Expresa 5,000,000 en notación científica:',
    questionLatex: '\\text{Expresa 5,000,000 en notación científica:}',
    options: ['$5 \\times 10^5$', '$5 \\times 10^6$', '$50 \\times 10^5$', '$0.5 \\times 10^7$'],
    optionsLatex: ['5 \\times 10^5', '5 \\times 10^6', '50 \\times 10^5', '0.5 \\times 10^7'],
    correctAnswer: 1,
    explanation: 'Movemos el punto decimal 6 posiciones a la izquierda:',
    explanationLatex: '5,000,000 = 5 \\times 10^6',
    difficulty: 'easy',
    skills: ['numeros-decimales', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-82',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el valor de $3.5 \\times 10^4$?',
    questionLatex: '\\text{¿Cuál es el valor de } 3.5 \\times 10^4?',
    options: ['350', '3,500', '35,000', '350,000'],
    correctAnswer: 2,
    explanation: 'Movemos el punto decimal 4 posiciones a la derecha:',
    explanationLatex: '3.5 \\times 10^4 = 35,000',
    difficulty: 'easy',
    skills: ['numeros-decimales', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-83',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'Calcula: $(2 \\times 10^3) \\times (4 \\times 10^5)$',
    questionLatex: '\\text{Calcula: } (2 \\times 10^3) \\times (4 \\times 10^5)',
    options: ['$6 \\times 10^8$', '$8 \\times 10^8$', '$8 \\times 10^{15}$', '$6 \\times 10^{15}$'],
    optionsLatex: ['6 \\times 10^8', '8 \\times 10^8', '8 \\times 10^{15}', '6 \\times 10^{15}'],
    correctAnswer: 1,
    explanation: 'Multiplicamos los coeficientes y sumamos los exponentes:',
    explanationLatex: '(2 \\times 10^3) \\times (4 \\times 10^5) = (2 \\times 4) \\times 10^{3+5} = 8 \\times 10^8',
    difficulty: 'hard',
    skills: ['numeros-decimales', 'numeros-potencias', 'numeros-potencias-propiedades', 'numeros-operaciones-basicas']
  },

  // NEW QUESTIONS: CATEGORY 4 - PROPORTIONALITY (12 questions)

  // Direct Proportionality Word Problems (3)
  {
    id: 'm1-84',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Si 5 cuadernos cuestan $7.500, ¿cuánto costarán 8 cuadernos?',
    questionLatex: '\\text{Si 5 cuadernos cuestan \\$7.500, ¿cuánto costarán 8 cuadernos?}',
    options: ['$10.000', '$11.000', '$12.000', '$13.500'],
    correctAnswer: 2,
    explanation: 'Es una proporción directa. A más cuadernos, más costo:',
    explanationLatex: '\\frac{5}{7500} = \\frac{8}{x} \\quad \\Rightarrow \\quad x = \\frac{8 \\times 7500}{5} = 12.000',
    difficulty: 'easy',
    skills: ['numeros-proporcionalidad', 'numeros-proporcionalidad-directa', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-85',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Un auto recorre 240 km en 3 horas a velocidad constante. ¿Cuántos kilómetros recorrerá en 5 horas?',
    questionLatex: '\\text{Un auto recorre 240 km en 3 horas a velocidad constante. ¿Cuántos kilómetros recorrerá en 5 horas?}',
    options: ['360 km', '400 km', '420 km', '480 km'],
    correctAnswer: 1,
    explanation: 'La distancia es directamente proporcional al tiempo:',
    explanationLatex: '\\frac{240}{3} = \\frac{x}{5} \\quad \\Rightarrow \\quad x = \\frac{240 \\times 5}{3} = 400 \\text{ km}',
    difficulty: 'medium',
    skills: ['numeros-proporcionalidad', 'numeros-proporcionalidad-directa', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-86',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Para hacer una torta para 6 personas se necesitan 4 huevos. ¿Cuántos huevos se necesitan para una torta para 15 personas?',
    questionLatex: '\\text{Para una torta para 6 personas se necesitan 4 huevos. ¿Cuántos huevos se necesitan para 15 personas?}',
    options: ['8 huevos', '9 huevos', '10 huevos', '12 huevos'],
    correctAnswer: 2,
    explanation: 'Proporción directa entre personas y huevos:',
    explanationLatex: '\\frac{6}{4} = \\frac{15}{x} \\quad \\Rightarrow \\quad x = \\frac{15 \\times 4}{6} = 10 \\text{ huevos}',
    difficulty: 'medium',
    skills: ['numeros-proporcionalidad', 'numeros-proporcionalidad-directa', 'numeros-operaciones-basicas']
  },

  // Complex Ratio Problems (3)
  {
    id: 'm1-87',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'En un curso hay 30 estudiantes. La razón entre hombres y mujeres es 2:3. ¿Cuántos hombres hay?',
    questionLatex: '\\text{En un curso hay 30 estudiantes. La razón entre hombres y mujeres es 2:3. ¿Cuántos hombres hay?}',
    options: ['10', '12', '15', '18'],
    correctAnswer: 1,
    explanation: 'La razón 2:3 significa 2 partes de hombres y 3 de mujeres (5 partes totales):',
    explanationLatex: '\\text{Hombres} = \\frac{2}{5} \\times 30 = 12',
    difficulty: 'medium',
    skills: ['numeros-proporcionalidad', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-88',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Se reparten $60.000 entre Ana y Pedro en razón 3:2. ¿Cuánto recibe Ana?',
    questionLatex: '\\text{Se reparten \\$60.000 entre Ana y Pedro en razón 3:2. ¿Cuánto recibe Ana?}',
    options: ['$24.000', '$30.000', '$36.000', '$40.000'],
    correctAnswer: 2,
    explanation: 'Ana recibe 3 partes de un total de 5 partes:',
    explanationLatex: '\\text{Ana} = \\frac{3}{5} \\times 60.000 = 36.000',
    difficulty: 'medium',
    skills: ['numeros-proporcionalidad', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-89',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Los lados de un triángulo están en razón 3:4:5 y su perímetro es 48 cm. ¿Cuánto mide el lado más largo?',
    questionLatex: '\\text{Los lados de un triángulo están en razón 3:4:5 y su perímetro es 48 cm. ¿Cuánto mide el lado más largo?}',
    options: ['12 cm', '16 cm', '20 cm', '24 cm'],
    correctAnswer: 2,
    explanation: 'El lado más largo tiene 5 partes de un total de 12 partes:',
    explanationLatex: '\\text{Lado más largo} = \\frac{5}{12} \\times 48 = 20 \\text{ cm}',
    difficulty: 'hard',
    skills: ['numeros-proporcionalidad', 'numeros-fracciones', 'geometria-perimetro', 'numeros-operaciones-basicas']
  },

  // Three-Way Proportions (3)
  {
    id: 'm1-90',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Tres amigos reparten $90.000 en razón 2:3:4. ¿Cuánto recibe el que más gana?',
    questionLatex: '\\text{Tres amigos reparten \\$90.000 en razón 2:3:4. ¿Cuánto recibe el que más gana?}',
    options: ['$20.000', '$30.000', '$40.000', '$50.000'],
    correctAnswer: 2,
    explanation: 'El que más recibe tiene 4 partes de un total de 9 partes:',
    explanationLatex: '\\frac{4}{2+3+4} \\times 90.000 = \\frac{4}{9} \\times 90.000 = 40.000',
    difficulty: 'medium',
    skills: ['numeros-proporcionalidad', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-91',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Las edades de Juan, María y Pedro están en razón 1:2:3 y la suma de sus edades es 36 años. ¿Cuántos años tiene María?',
    questionLatex: '\\text{Las edades de Juan, María y Pedro están en razón 1:2:3 y la suma es 36 años. ¿Cuántos años tiene María?}',
    options: ['6 años', '12 años', '18 años', '24 años'],
    correctAnswer: 1,
    explanation: 'María tiene 2 partes de un total de 6 partes:',
    explanationLatex: '\\text{María} = \\frac{2}{6} \\times 36 = 12 \\text{ años}',
    difficulty: 'medium',
    skills: ['numeros-proporcionalidad', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-92',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Se mezclan tres tipos de café en razón 5:3:2 para obtener 100 kg. ¿Cuántos kg se usan del primer tipo?',
    questionLatex: '\\text{Se mezclan tres tipos de café en razón 5:3:2 para obtener 100 kg. ¿Cuántos kg del primer tipo?}',
    options: ['20 kg', '30 kg', '50 kg', '60 kg'],
    correctAnswer: 2,
    explanation: 'El primer tipo representa 5 partes de un total de 10 partes:',
    explanationLatex: '\\frac{5}{10} \\times 100 = 50 \\text{ kg}',
    difficulty: 'hard',
    skills: ['numeros-proporcionalidad', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },

  // Mixture Problems (3)
  {
    id: 'm1-93',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Se mezclan 3 litros de jugo puro con 2 litros de agua. ¿Qué fracción de la mezcla es jugo?',
    questionLatex: '\\text{Se mezclan 3 litros de jugo puro con 2 litros de agua. ¿Qué fracción de la mezcla es jugo?}',
    options: ['$\\frac{2}{5}$', '$\\frac{3}{5}$', '$\\frac{2}{3}$', '$\\frac{3}{2}$'],
    optionsLatex: ['\\frac{2}{5}', '\\frac{3}{5}', '\\frac{2}{3}', '\\frac{3}{2}'],
    correctAnswer: 1,
    explanation: 'El total de la mezcla es 5 litros, de los cuales 3 son jugo:',
    explanationLatex: '\\frac{3}{5} \\text{ de la mezcla es jugo}',
    difficulty: 'easy',
    skills: ['numeros-proporcionalidad', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-94',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Una mezcla contiene 40% de agua y 60% de alcohol. Si tengo 50 litros de mezcla, ¿cuántos litros de alcohol hay?',
    questionLatex: '\\text{Una mezcla contiene 40\\% agua y 60\\% alcohol. Con 50 litros de mezcla, ¿cuántos litros de alcohol?}',
    options: ['20 litros', '25 litros', '30 litros', '35 litros'],
    correctAnswer: 2,
    explanation: 'Calculamos el 60% de 50 litros:',
    explanationLatex: '0.60 \\times 50 = 30 \\text{ litros de alcohol}',
    difficulty: 'easy',
    skills: ['numeros-porcentajes', 'numeros-proporcionalidad', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-95',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Se mezclan 6 kg de arroz de $1.200/kg con 4 kg de arroz de $1.800/kg. ¿Cuál es el precio promedio por kg?',
    questionLatex: '\\text{Se mezclan 6 kg a \\$1.200/kg con 4 kg a \\$1.800/kg. ¿Precio promedio por kg?}',
    options: ['$1.320', '$1.440', '$1.500', '$1.560'],
    correctAnswer: 1,
    explanation: 'Calculamos el costo total y dividimos por el peso total:',
    explanationLatex: '\\frac{6(1200) + 4(1800)}{10} = \\frac{7200 + 7200}{10} = \\frac{14400}{10} = 1.440',
    difficulty: 'hard',
    skills: ['numeros-proporcionalidad', 'numeros-decimales', 'numeros-operaciones-basicas']
  },

  // NEW QUESTIONS: CATEGORY 5 - PERCENTAGES (12 questions)

  // Percentage Increase/Decrease (3)
  {
    id: 'm1-96',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'El precio de un producto aumenta de $20.000 a $25.000. ¿Cuál es el porcentaje de aumento?',
    questionLatex: '\\text{El precio aumenta de \\$20.000 a \\$25.000. ¿Porcentaje de aumento?}',
    options: ['20%', '25%', '30%', '35%'],
    correctAnswer: 1,
    explanation: 'Calculamos la diferencia y la dividimos por el valor original:',
    explanationLatex: '\\frac{25000 - 20000}{20000} \\times 100\\% = \\frac{5000}{20000} \\times 100\\% = 25\\%',
    difficulty: 'medium',
    skills: ['numeros-porcentajes', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-97',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Una población disminuye de 8.000 a 6.400 habitantes. ¿Cuál es el porcentaje de disminución?',
    questionLatex: '\\text{Una población disminuye de 8.000 a 6.400. ¿Porcentaje de disminución?}',
    options: ['15%', '20%', '25%', '30%'],
    correctAnswer: 1,
    explanation: 'Calculamos la disminución relativa:',
    explanationLatex: '\\frac{8000 - 6400}{8000} \\times 100\\% = \\frac{1600}{8000} \\times 100\\% = 20\\%',
    difficulty: 'medium',
    skills: ['numeros-porcentajes', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-98',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'El sueldo de Pedro aumentó en un 12% y ahora gana $560.000. ¿Cuánto ganaba antes?',
    questionLatex: '\\text{El sueldo aumentó 12\\% y ahora es \\$560.000. ¿Cuánto ganaba antes?}',
    options: ['$480.000', '$500.000', '$520.000', '$540.000'],
    correctAnswer: 1,
    explanation: 'Si aumentó 12%, el nuevo sueldo es 112% del original:',
    explanationLatex: '1.12x = 560000 \\quad \\Rightarrow \\quad x = \\frac{560000}{1.12} = 500.000',
    difficulty: 'hard',
    skills: ['numeros-porcentajes', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },

  // Simple Compound Interest (3)
  {
    id: 'm1-99',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Se depositan $100.000 en un banco que paga 5% de interés simple anual. ¿Cuánto dinero habrá después de 1 año?',
    questionLatex: '\\text{Se depositan \\$100.000 al 5\\% simple anual. ¿Cuánto habrá en 1 año?}',
    options: ['$105.000', '$110.000', '$115.000', '$120.000'],
    correctAnswer: 0,
    explanation: 'El interés es el 5% del capital:',
    explanationLatex: '100000 + (0.05 \\times 100000) = 100000 + 5000 = 105.000',
    difficulty: 'easy',
    skills: ['numeros-porcentajes', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-100',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Un capital de $50.000 genera $3.000 de interés simple en 1 año. ¿Cuál es la tasa de interés anual?',
    questionLatex: '\\text{Un capital de \\$50.000 genera \\$3.000 en 1 año. ¿Tasa de interés?}',
    options: ['4%', '5%', '6%', '7%'],
    correctAnswer: 2,
    explanation: 'La tasa es la razón entre el interés y el capital:',
    explanationLatex: '\\frac{3000}{50000} \\times 100\\% = 6\\%',
    difficulty: 'medium',
    skills: ['numeros-porcentajes', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-101',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Se depositan $200.000 al 8% de interés simple anual. ¿Cuánto dinero habrá después de 2 años?',
    questionLatex: '\\text{Se depositan \\$200.000 al 8\\% simple anual. ¿Cuánto en 2 años?}',
    options: ['$216.000', '$224.000', '$232.000', '$240.000'],
    correctAnswer: 2,
    explanation: 'El interés por 2 años es 16% del capital:',
    explanationLatex: '200000 + (0.08 \\times 200000 \\times 2) = 200000 + 32000 = 232.000',
    difficulty: 'medium',
    skills: ['numeros-porcentajes', 'numeros-decimales', 'numeros-operaciones-basicas']
  },

  // Percentage of Percentage (3)
  {
    id: 'm1-102',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: '¿Cuánto es el 20% del 50% de 200?',
    questionLatex: '\\text{¿Cuánto es el 20\\% del 50\\% de 200?}',
    options: ['10', '20', '30', '40'],
    correctAnswer: 1,
    explanation: 'Calculamos paso a paso:',
    explanationLatex: '50\\% \\text{ de } 200 = 100, \\quad 20\\% \\text{ de } 100 = 20',
    difficulty: 'easy',
    skills: ['numeros-porcentajes', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-103',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Un producto tiene un descuento del 30% y luego otro descuento del 10% sobre el precio rebajado. Si el precio original es $100.000, ¿cuál es el precio final?',
    questionLatex: '\\text{Descuentos sucesivos de 30\\% y 10\\% sobre \\$100.000. ¿Precio final?}',
    options: ['$60.000', '$63.000', '$66.000', '$70.000'],
    correctAnswer: 1,
    explanation: 'Aplicamos los descuentos en secuencia:',
    explanationLatex: '100000 \\times 0.70 \\times 0.90 = 70000 \\times 0.90 = 63.000',
    difficulty: 'hard',
    skills: ['numeros-porcentajes', 'numeros-porcentajes-descuentos', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-104',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: '¿Cuál es el 25% del 40% de 800?',
    questionLatex: '\\text{¿Cuál es el 25\\% del 40\\% de 800?}',
    options: ['60', '70', '80', '90'],
    correctAnswer: 2,
    explanation: 'Calculamos los porcentajes en secuencia:',
    explanationLatex: '40\\% \\text{ de } 800 = 320, \\quad 25\\% \\text{ de } 320 = 80',
    difficulty: 'medium',
    skills: ['numeros-porcentajes', 'numeros-decimales', 'numeros-operaciones-basicas']
  },

  // Finding Original Value (3)
  {
    id: 'm1-105',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'Después de un descuento del 20%, un producto cuesta $24.000. ¿Cuál era el precio original?',
    questionLatex: '\\text{Después de un descuento del 20\\%, cuesta \\$24.000. ¿Precio original?}',
    options: ['$28.000', '$30.000', '$32.000', '$36.000'],
    correctAnswer: 1,
    explanation: 'Si tiene 20% de descuento, pagamos el 80% del precio original:',
    explanationLatex: '0.80x = 24000 \\quad \\Rightarrow \\quad x = \\frac{24000}{0.80} = 30.000',
    difficulty: 'medium',
    skills: ['numeros-porcentajes', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-106',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'El precio de un producto aumentó en un 25% y ahora cuesta $50.000. ¿Cuál era el precio original?',
    questionLatex: '\\text{Aumentó 25\\% y ahora cuesta \\$50.000. ¿Precio original?}',
    options: ['$37.500', '$40.000', '$42.500', '$45.000'],
    correctAnswer: 1,
    explanation: 'El precio actual es 125% del precio original:',
    explanationLatex: '1.25x = 50000 \\quad \\Rightarrow \\quad x = \\frac{50000}{1.25} = 40.000',
    difficulty: 'medium',
    skills: ['numeros-porcentajes', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-107',
    level: 'M1',
    topic: 'Números y Proporcionalidad',
    subject: 'números',
    question: 'El 35% de un número es 70. ¿Cuál es el número?',
    questionLatex: '\\text{El 35\\% de un número es 70. ¿Cuál es el número?}',
    options: ['150', '180', '200', '240'],
    correctAnswer: 2,
    explanation: 'Planteamos la ecuación:',
    explanationLatex: '0.35x = 70 \\quad \\Rightarrow \\quad x = \\frac{70}{0.35} = 200',
    difficulty: 'hard',
    skills: ['numeros-porcentajes', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },

  // NEW QUESTIONS: CATEGORY 6 - ORDER OF OPERATIONS (6 questions)

  // PEMDAS/BODMAS Problems (3)
  {
    id: 'm1-108',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $8 + 2 \\times 5$?',
    questionLatex: '\\text{¿Cuál es el resultado de } 8 + 2 \\times 5?',
    options: ['18', '50', '26', '15'],
    correctAnswer: 0,
    explanation: 'Primero multiplicación, luego suma:',
    explanationLatex: '8 + 2 \\times 5 = 8 + 10 = 18',
    difficulty: 'easy',
    skills: ['numeros-orden-operaciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-109',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $20 - 3 \\times 4 + 6$?',
    questionLatex: '\\text{¿Cuál es el resultado de } 20 - 3 \\times 4 + 6?',
    options: ['14', '26', '74', '2'],
    correctAnswer: 0,
    explanation: 'Multiplicación primero, luego operaciones de izquierda a derecha:',
    explanationLatex: '20 - 3 \\times 4 + 6 = 20 - 12 + 6 = 14',
    difficulty: 'medium',
    skills: ['numeros-orden-operaciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-110',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $2^3 + 4 \\times 3 - 5$?',
    questionLatex: '\\text{¿Cuál es el resultado de } 2^3 + 4 \\times 3 - 5?',
    options: ['15', '19', '21', '27'],
    correctAnswer: 0,
    explanation: 'Orden: exponentes, multiplicación, luego suma y resta:',
    explanationLatex: '2^3 + 4 \\times 3 - 5 = 8 + 12 - 5 = 15',
    difficulty: 'medium',
    skills: ['numeros-orden-operaciones', 'numeros-potencias', 'numeros-operaciones-basicas']
  },

  // Mixed Operations with Parentheses (3)
  {
    id: 'm1-111',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $(8 + 2) \\times 5$?',
    questionLatex: '\\text{¿Cuál es el resultado de } (8 + 2) \\times 5?',
    options: ['18', '40', '50', '26'],
    correctAnswer: 2,
    explanation: 'Primero resolvemos el paréntesis:',
    explanationLatex: '(8 + 2) \\times 5 = 10 \\times 5 = 50',
    difficulty: 'easy',
    skills: ['numeros-orden-operaciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-112',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $3 \\times (12 - 4) + 8$?',
    questionLatex: '\\text{¿Cuál es el resultado de } 3 \\times (12 - 4) + 8?',
    options: ['24', '28', '32', '36'],
    correctAnswer: 2,
    explanation: 'Paréntesis primero, luego multiplicación y suma:',
    explanationLatex: '3 \\times (12 - 4) + 8 = 3 \\times 8 + 8 = 24 + 8 = 32',
    difficulty: 'medium',
    skills: ['numeros-orden-operaciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-113',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $[(15 - 3) \\div 4 + 2] \\times 3$?',
    questionLatex: '\\text{¿Cuál es el resultado de } [(15 - 3) \\div 4 + 2] \\times 3?',
    options: ['12', '15', '18', '21'],
    correctAnswer: 1,
    explanation: 'Resolvemos de adentro hacia afuera:',
    explanationLatex: '[(15 - 3) \\div 4 + 2] \\times 3 = [12 \\div 4 + 2] \\times 3 = [3 + 2] \\times 3 = 5 \\times 3 = 15',
    difficulty: 'hard',
    skills: ['numeros-orden-operaciones', 'numeros-operaciones-basicas']
  },

  // NEW QUESTIONS: CATEGORY 7 - NUMBER SYSTEMS (9 questions)

  // Irrational Numbers (3)
  {
    id: 'm1-114',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál de los siguientes es un número irracional?',
    questionLatex: '\\text{¿Cuál de los siguientes es un número irracional?}',
    options: ['$\\frac{22}{7}$', '$\\sqrt{16}$', '$\\pi$', '$0.\\overline{3}$'],
    optionsLatex: ['\\frac{22}{7}', '\\sqrt{16}', '\\pi', '0.\\overline{3}'],
    correctAnswer: 2,
    explanation: 'Un número irracional no puede expresarse como fracción:',
    explanationLatex: '\\pi \\text{ es irracional. } \\frac{22}{7} \\text{ y } 0.\\overline{3} \\text{ son racionales, } \\sqrt{16}=4',
    difficulty: 'medium',
    skills: ['numeros-operaciones-basicas']
  },
  {
    id: 'm1-115',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál de los siguientes es un número racional?',
    questionLatex: '\\text{¿Cuál de los siguientes es un número racional?}',
    options: ['$\\pi$', '$\\sqrt{2}$', '$\\sqrt{9}$', '$\\sqrt{7}$'],
    optionsLatex: ['\\pi', '\\sqrt{2}', '\\sqrt{9}', '\\sqrt{7}'],
    correctAnswer: 2,
    explanation: 'Un número racional puede expresarse como fracción:',
    explanationLatex: '\\sqrt{9} = 3 \\text{ (racional). Los demás son irracionales.}',
    difficulty: 'easy',
    skills: ['numeros-raices', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-116',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Aproximadamente cuánto es $\\pi + \\sqrt{2}$? (Usa $\\pi \\approx 3.14$ y $\\sqrt{2} \\approx 1.41$)',
    questionLatex: '\\text{¿Aproximadamente cuánto es } \\pi + \\sqrt{2}? \\text{ (Usa } \\pi \\approx 3.14 \\text{ y } \\sqrt{2} \\approx 1.41)',
    options: ['4.14', '4.41', '4.55', '5.55'],
    correctAnswer: 2,
    explanation: 'Sumamos las aproximaciones:',
    explanationLatex: '\\pi + \\sqrt{2} \\approx 3.14 + 1.41 = 4.55',
    difficulty: 'hard',
    skills: ['numeros-raices', 'numeros-decimales', 'numeros-operaciones-basicas']
  },

  // Number Line Representations (3)
  {
    id: 'm1-117',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'En la recta numérica, ¿qué número está exactamente a mitad de camino entre -3 y 5?',
    questionLatex: '\\text{En la recta numérica, ¿qué número está a mitad de camino entre -3 y 5?}',
    options: ['0', '1', '2', '4'],
    correctAnswer: 1,
    explanation: 'El punto medio es el promedio de los dos números:',
    explanationLatex: '\\frac{-3 + 5}{2} = \\frac{2}{2} = 1',
    difficulty: 'easy',
    skills: ['numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-118',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál número está más cerca de 0 en la recta numérica?',
    questionLatex: '\\text{¿Cuál número está más cerca de 0 en la recta numérica?}',
    options: ['-0.5', '0.6', '-0.8', '1.2'],
    correctAnswer: 0,
    explanation: 'El número más cercano a 0 es el de menor valor absoluto:',
    explanationLatex: '|-0.5| = 0.5 \\text{ es el menor}',
    difficulty: 'medium',
    skills: ['numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-119',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: 'En la recta numérica, ¿qué distancia hay entre -4 y 7?',
    questionLatex: '\\text{En la recta numérica, ¿qué distancia hay entre -4 y 7?}',
    options: ['3', '7', '11', '28'],
    correctAnswer: 2,
    explanation: 'La distancia es el valor absoluto de la diferencia:',
    explanationLatex: '|7 - (-4)| = |7 + 4| = 11',
    difficulty: 'medium',
    skills: ['numeros-enteros', 'numeros-operaciones-basicas']
  },

  // Absolute Value (3)
  {
    id: 'm1-120',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el valor de $|-8|$?',
    questionLatex: '\\text{¿Cuál es el valor de } |-8|?',
    options: ['-8', '0', '8', '16'],
    correctAnswer: 2,
    explanation: 'El valor absoluto es la distancia al cero (siempre positivo):',
    explanationLatex: '|-8| = 8',
    difficulty: 'easy',
    skills: ['numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-121',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $|5 - 9|$?',
    questionLatex: '\\text{¿Cuál es el resultado de } |5 - 9|?',
    options: ['-4', '4', '14', '-14'],
    correctAnswer: 1,
    explanation: 'Primero restamos, luego tomamos el valor absoluto:',
    explanationLatex: '|5 - 9| = |-4| = 4',
    difficulty: 'easy',
    skills: ['numeros-enteros', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-122',
    level: 'M1',
    topic: 'Números y Operaciones',
    subject: 'números',
    question: '¿Cuál es el resultado de $|-3| + |2| - |-5|$?',
    questionLatex: '\\text{¿Cuál es el resultado de } |-3| + |2| - |-5|?',
    options: ['0', '4', '6', '10'],
    correctAnswer: 0,
    explanation: 'Calculamos cada valor absoluto y luego operamos:',
    explanationLatex: '|-3| + |2| - |-5| = 3 + 2 - 5 = 0',
    difficulty: 'medium',
    skills: ['numeros-enteros', 'numeros-operaciones-basicas']
  }
];
