import { Question } from '../types';

export const m1ProbabilidadQuestions: Question[] = [
  {
    id: 'm1-4',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Al lanzar un dado de 6 caras, ¿cuál es la probabilidad de obtener un número par?',
    questionLatex: '\\text{Al lanzar un dado de 6 caras, ¿cuál es la probabilidad de obtener un número par?}',
    options: ['$\\frac{1}{6}$', '$\\frac{1}{3}$', '$\\frac{1}{2}$', '$\\frac{2}{3}$'],
    optionsLatex: ['\\frac{1}{6}', '\\frac{1}{3}', '\\frac{1}{2}', '\\frac{2}{3}'],
    correctAnswer: 2,
    explanation: 'Los números pares son 2, 4 y 6. Hay 3 casos favorables de 6 posibles:',
    explanationLatex: 'P = \\frac{3}{6} = \\frac{1}{2}',
    difficulty: 'easy',
    skills: ['probabilidad-basica', 'probabilidad-casos-favorables', 'numeros-fracciones']
  },
  {
    id: 'm1-8',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'La media aritmética de los números 4, 6, 8 y 10 es:',
    questionLatex: '\\text{La media aritmética de los números 4, 6, 8 y 10 es:}',
    options: ['6', '7', '8', '9'],
    correctAnswer: 1,
    explanation: 'Calculamos la media:',
    explanationLatex: '\\bar{x} = \\frac{4 + 6 + 8 + 10}{4} = \\frac{28}{4} = 7',
    difficulty: 'easy',
    skills: ['estadistica-media', 'numeros-operaciones-basicas', 'numeros-fracciones']
  },
  {
    id: 'm1-22',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: '¿Cuál es la mediana del conjunto de datos: 3, 7, 5, 9, 11?',
    questionLatex: '\\text{¿Cuál es la mediana del conjunto de datos: 3, 7, 5, 9, 11?}',
    options: ['5', '7', '9', '11'],
    correctAnswer: 1,
    explanation: 'Primero ordenamos los datos: 3, 5, 7, 9, 11. La mediana es el valor central:',
    explanationLatex: '\\text{Mediana} = 7',
    difficulty: 'easy',
    skills: ['estadistica-mediana', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-23',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: '¿Cuál es la moda del conjunto: 2, 3, 3, 5, 7, 3, 9?',
    questionLatex: '\\text{¿Cuál es la moda del conjunto: 2, 3, 3, 5, 7, 3, 9?}',
    options: ['2', '3', '5', '7'],
    correctAnswer: 1,
    explanation: 'La moda es el valor que más se repite:',
    explanationLatex: '\\text{Moda} = 3 \\text{ (aparece 3 veces)}',
    difficulty: 'easy',
    skills: ['estadistica-moda']
  },
  {
    id: 'm1-24',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'En una bolsa hay 5 bolas rojas y 3 azules. ¿Cuál es la probabilidad de sacar una bola azul?',
    questionLatex: '\\text{En una bolsa hay 5 bolas rojas y 3 azules. ¿Cuál es la probabilidad de sacar una bola azul?}',
    options: ['$\\frac{3}{5}$', '$\\frac{5}{8}$', '$\\frac{3}{8}$', '$\\frac{1}{3}$'],
    optionsLatex: ['\\frac{3}{5}', '\\frac{5}{8}', '\\frac{3}{8}', '\\frac{1}{3}'],
    correctAnswer: 2,
    explanation: 'La probabilidad es el cociente entre casos favorables y casos totales:',
    explanationLatex: 'P(\\text{azul}) = \\frac{3}{5+3} = \\frac{3}{8}',
    difficulty: 'easy',
    skills: ['probabilidad-basica', 'probabilidad-casos-favorables', 'numeros-fracciones']
  },
  {
    id: 'm1-25',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'El rango del conjunto de datos 12, 8, 15, 20, 9 es:',
    questionLatex: '\\text{El rango del conjunto de datos 12, 8, 15, 20, 9 es:}',
    options: ['8', '9', '12', '12'],
    correctAnswer: 2,
    explanation: 'El rango es la diferencia entre el valor máximo y mínimo:',
    explanationLatex: '\\text{Rango} = 20 - 8 = 12',
    difficulty: 'easy',
    skills: ['estadistica-rango', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-38',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Al lanzar una moneda dos veces, ¿cuál es la probabilidad de obtener dos caras?',
    questionLatex: '\\text{Al lanzar una moneda dos veces, ¿cuál es la probabilidad de obtener dos caras?}',
    options: ['$\\frac{1}{2}$', '$\\frac{1}{3}$', '$\\frac{1}{4}$', '$\\frac{2}{3}$'],
    optionsLatex: ['\\frac{1}{2}', '\\frac{1}{3}', '\\frac{1}{4}', '\\frac{2}{3}'],
    correctAnswer: 2,
    explanation: 'Los resultados posibles son CC, CS, SC, SS. Solo uno es favorable:',
    explanationLatex: 'P(\\text{dos caras}) = \\frac{1}{4}',
    difficulty: 'medium',
    skills: ['probabilidad-eventos-compuestos', 'probabilidad-basica', 'probabilidad-casos-favorables', 'numeros-fracciones']
  },
  {
    id: 'm1-39',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'La media de 5, 8, 10 y 13 es:',
    questionLatex: '\\text{La media de 5, 8, 10 y 13 es:}',
    options: ['8', '9', '10', '11'],
    correctAnswer: 1,
    explanation: 'Sumamos todos los valores y dividimos por la cantidad:',
    explanationLatex: '\\bar{x} = \\frac{5 + 8 + 10 + 13}{4} = \\frac{36}{4} = 9',
    difficulty: 'easy',
    skills: ['estadistica-media', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-40',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'En una clase hay 12 niños y 18 niñas. ¿Qué porcentaje son niños?',
    questionLatex: '\\text{En una clase hay 12 niños y 18 niñas. ¿Qué porcentaje son niños?}',
    options: ['30%', '40%', '50%', '60%'],
    correctAnswer: 1,
    explanation: 'Calculamos el porcentaje:',
    explanationLatex: '\\frac{12}{12 + 18} = \\frac{12}{30} = 0.4 = 40\\%',
    difficulty: 'easy',
    skills: ['estadistica-porcentajes', 'numeros-porcentajes', 'numeros-fracciones', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-41',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Al lanzar un dado, ¿cuál es la probabilidad de obtener un número mayor que 4?',
    questionLatex: '\\text{Al lanzar un dado, ¿cuál es la probabilidad de obtener un número mayor que 4?}',
    options: ['$\\frac{1}{6}$', '$\\frac{1}{3}$', '$\\frac{1}{2}$', '$\\frac{2}{3}$'],
    optionsLatex: ['\\frac{1}{6}', '\\frac{1}{3}', '\\frac{1}{2}', '\\frac{2}{3}'],
    correctAnswer: 1,
    explanation: 'Los números mayores que 4 son 5 y 6. Hay 2 casos favorables de 6 posibles:',
    explanationLatex: 'P = \\frac{2}{6} = \\frac{1}{3}',
    difficulty: 'easy',
    skills: ['probabilidad-basica', 'probabilidad-casos-favorables', 'numeros-fracciones']
  },

  // BATCH 1: PROBABILIDAD BÁSICA Y CONCEPTOS FUNDAMENTALES (15 questions)

  // Espacio muestral y eventos (3)
  {
    id: 'm1-42',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: '¿Cuántos elementos tiene el espacio muestral al lanzar dos monedas?',
    questionLatex: '\\text{¿Cuántos elementos tiene el espacio muestral al lanzar dos monedas?}',
    options: ['2', '3', '4', '5'],
    correctAnswer: 2,
    explanation: 'El espacio muestral es el conjunto de todos los resultados posibles:',
    explanationLatex: 'S = \\{CC, CS, SC, SS\\} \\rightarrow |S| = 4',
    difficulty: 'easy',
    skills: ['probabilidad-espacio-muestral', 'probabilidad-basica']
  },
  {
    id: 'm1-43',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Al lanzar un dado, ¿cuántos elementos tiene el evento "obtener un número primo"?',
    questionLatex: '\\text{Al lanzar un dado, ¿cuántos elementos tiene el evento "obtener un número primo"?}',
    options: ['2', '3', '4', '5'],
    correctAnswer: 1,
    explanation: 'Los números primos en un dado son 2, 3 y 5:',
    explanationLatex: 'A = \\{2, 3, 5\\} \\rightarrow |A| = 3',
    difficulty: 'easy',
    skills: ['probabilidad-eventos', 'probabilidad-espacio-muestral', 'numeros-primos']
  },
  {
    id: 'm1-44',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'En una baraja de 52 cartas, ¿cuántas cartas son rojas?',
    questionLatex: '\\text{En una baraja de 52 cartas, ¿cuántas cartas son rojas?}',
    options: ['13', '20', '26', '39'],
    correctAnswer: 2,
    explanation: 'Las cartas rojas son corazones y diamantes (cada palo tiene 13 cartas):',
    explanationLatex: '13 + 13 = 26 \\text{ cartas rojas}',
    difficulty: 'easy',
    skills: ['probabilidad-casos-favorables', 'numeros-operaciones-basicas']
  },

  // Probabilidad clásica (3)
  {
    id: 'm1-45',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'En una urna hay 4 bolas blancas, 3 negras y 5 rojas. ¿Cuál es la probabilidad de sacar una bola blanca?',
    questionLatex: '\\text{En una urna hay 4 bolas blancas, 3 negras y 5 rojas. ¿Cuál es la probabilidad de sacar una bola blanca?}',
    options: ['$\\frac{1}{4}$', '$\\frac{1}{3}$', '$\\frac{1}{2}$', '$\\frac{4}{12}$'],
    optionsLatex: ['\\frac{1}{4}', '\\frac{1}{3}', '\\frac{1}{2}', '\\frac{4}{12}'],
    correctAnswer: 1,
    explanation: 'Total de bolas: 4 + 3 + 5 = 12. Probabilidad de blanca:',
    explanationLatex: 'P(\\text{blanca}) = \\frac{4}{12} = \\frac{1}{3}',
    difficulty: 'easy',
    skills: ['probabilidad-basica', 'probabilidad-casos-favorables', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-46',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Al lanzar un dado, ¿cuál es la probabilidad de obtener un múltiplo de 3?',
    questionLatex: '\\text{Al lanzar un dado, ¿cuál es la probabilidad de obtener un múltiplo de 3?}',
    options: ['$\\frac{1}{6}$', '$\\frac{1}{3}$', '$\\frac{1}{2}$', '$\\frac{2}{3}$'],
    optionsLatex: ['\\frac{1}{6}', '\\frac{1}{3}', '\\frac{1}{2}', '\\frac{2}{3}'],
    correctAnswer: 1,
    explanation: 'Los múltiplos de 3 en un dado son 3 y 6:',
    explanationLatex: 'P = \\frac{2}{6} = \\frac{1}{3}',
    difficulty: 'easy',
    skills: ['probabilidad-basica', 'probabilidad-casos-favorables', 'numeros-multiplos', 'numeros-fracciones']
  },
  {
    id: 'm1-47',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'En una baraja española (40 cartas), ¿cuál es la probabilidad de sacar un oro?',
    questionLatex: '\\text{En una baraja española (40 cartas), ¿cuál es la probabilidad de sacar un oro?}',
    options: ['$\\frac{1}{10}$', '$\\frac{1}{4}$', '$\\frac{1}{5}$', '$\\frac{3}{10}$'],
    optionsLatex: ['\\frac{1}{10}', '\\frac{1}{4}', '\\frac{1}{5}', '\\frac{3}{10}'],
    correctAnswer: 1,
    explanation: 'Hay 10 cartas de oro en una baraja de 40 cartas:',
    explanationLatex: 'P(\\text{oro}) = \\frac{10}{40} = \\frac{1}{4}',
    difficulty: 'easy',
    skills: ['probabilidad-basica', 'probabilidad-casos-favorables', 'numeros-fracciones']
  },

  // Complemento de eventos (3)
  {
    id: 'm1-48',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Si la probabilidad de lluvia es $\\frac{3}{10}$, ¿cuál es la probabilidad de que NO llueva?',
    questionLatex: '\\text{Si la probabilidad de lluvia es } \\frac{3}{10}, \\text{ ¿cuál es la probabilidad de que NO llueva?}',
    options: ['$\\frac{3}{10}$', '$\\frac{7}{10}$', '$\\frac{1}{2}$', '$\\frac{2}{3}$'],
    optionsLatex: ['\\frac{3}{10}', '\\frac{7}{10}', '\\frac{1}{2}', '\\frac{2}{3}'],
    correctAnswer: 1,
    explanation: 'El complemento de un evento A es 1 - P(A):',
    explanationLatex: 'P(\\text{no lluvia}) = 1 - \\frac{3}{10} = \\frac{7}{10}',
    difficulty: 'easy',
    skills: ['probabilidad-complemento', 'probabilidad-basica', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-49',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Al lanzar un dado, ¿cuál es la probabilidad de NO obtener un 6?',
    questionLatex: '\\text{Al lanzar un dado, ¿cuál es la probabilidad de NO obtener un 6?}',
    options: ['$\\frac{1}{6}$', '$\\frac{1}{5}$', '$\\frac{5}{6}$', '$\\frac{2}{3}$'],
    optionsLatex: ['\\frac{1}{6}', '\\frac{1}{5}', '\\frac{5}{6}', '\\frac{2}{3}'],
    correctAnswer: 2,
    explanation: 'El complemento de obtener 6 incluye los resultados 1, 2, 3, 4, 5:',
    explanationLatex: 'P(\\text{no 6}) = 1 - P(6) = 1 - \\frac{1}{6} = \\frac{5}{6}',
    difficulty: 'easy',
    skills: ['probabilidad-complemento', 'probabilidad-basica', 'numeros-fracciones']
  },
  {
    id: 'm1-50',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Si P(A) = 0.35, ¿cuál es P(no A)?',
    questionLatex: '\\text{Si } P(A) = 0.35, \\text{ ¿cuál es } P(\\text{no } A)?',
    options: ['0.35', '0.50', '0.65', '0.75'],
    correctAnswer: 2,
    explanation: 'La probabilidad del complemento es:',
    explanationLatex: 'P(\\text{no } A) = 1 - P(A) = 1 - 0.35 = 0.65',
    difficulty: 'easy',
    skills: ['probabilidad-complemento', 'probabilidad-basica', 'numeros-decimales', 'numeros-operaciones-basicas']
  },

  // Eventos equiprobables (3)
  {
    id: 'm1-51',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se elige al azar un número del 1 al 20. ¿Cuál es la probabilidad de que sea divisible por 4?',
    questionLatex: '\\text{Se elige al azar un número del 1 al 20. ¿Cuál es la probabilidad de que sea divisible por 4?}',
    options: ['$\\frac{1}{4}$', '$\\frac{1}{5}$', '$\\frac{1}{3}$', '$\\frac{3}{10}$'],
    optionsLatex: ['\\frac{1}{4}', '\\frac{1}{5}', '\\frac{1}{3}', '\\frac{3}{10}'],
    correctAnswer: 0,
    explanation: 'Los números divisibles por 4 son: 4, 8, 12, 16, 20 (5 números):',
    explanationLatex: 'P = \\frac{5}{20} = \\frac{1}{4}',
    difficulty: 'medium',
    skills: ['probabilidad-basica', 'probabilidad-casos-favorables', 'numeros-divisores', 'numeros-fracciones']
  },
  {
    id: 'm1-52',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'En una rifa con 100 boletos numerados del 1 al 100, ¿cuál es la probabilidad de ganar con un boleto que termina en 5?',
    questionLatex: '\\text{En una rifa con 100 boletos, ¿cuál es la probabilidad de ganar con un boleto que termina en 5?}',
    options: ['$\\frac{1}{100}$', '$\\frac{1}{50}$', '$\\frac{1}{20}$', '$\\frac{1}{10}$'],
    optionsLatex: ['\\frac{1}{100}', '\\frac{1}{50}', '\\frac{1}{20}', '\\frac{1}{10}'],
    correctAnswer: 3,
    explanation: 'Los números que terminan en 5 son: 5, 15, 25, 35, 45, 55, 65, 75, 85, 95 (10 números):',
    explanationLatex: 'P = \\frac{10}{100} = \\frac{1}{10}',
    difficulty: 'medium',
    skills: ['probabilidad-basica', 'probabilidad-casos-favorables', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-53',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se extrae una letra al azar de la palabra "MATEMÁTICA". ¿Cuál es la probabilidad de obtener una A?',
    questionLatex: '\\text{Se extrae una letra al azar de la palabra "MATEMÁTICA". ¿Cuál es la probabilidad de obtener una A?}',
    options: ['$\\frac{1}{10}$', '$\\frac{2}{10}$', '$\\frac{3}{10}$', '$\\frac{4}{10}$'],
    optionsLatex: ['\\frac{1}{10}', '\\frac{2}{10}', '\\frac{3}{10}', '\\frac{4}{10}'],
    correctAnswer: 2,
    explanation: 'La palabra MATEMÁTICA tiene 10 letras, de las cuales 3 son A:',
    explanationLatex: 'P(A) = \\frac{3}{10}',
    difficulty: 'medium',
    skills: ['probabilidad-basica', 'probabilidad-casos-favorables', 'numeros-fracciones']
  },

  // Suma de probabilidades (3)
  {
    id: 'm1-54',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Al lanzar un dado, ¿cuál es la probabilidad de obtener 1 o 2?',
    questionLatex: '\\text{Al lanzar un dado, ¿cuál es la probabilidad de obtener 1 o 2?}',
    options: ['$\\frac{1}{6}$', '$\\frac{1}{3}$', '$\\frac{1}{2}$', '$\\frac{2}{3}$'],
    optionsLatex: ['\\frac{1}{6}', '\\frac{1}{3}', '\\frac{1}{2}', '\\frac{2}{3}'],
    correctAnswer: 1,
    explanation: 'Para eventos mutuamente excluyentes, sumamos las probabilidades:',
    explanationLatex: 'P(1 \\text{ o } 2) = P(1) + P(2) = \\frac{1}{6} + \\frac{1}{6} = \\frac{2}{6} = \\frac{1}{3}',
    difficulty: 'easy',
    skills: ['probabilidad-union', 'probabilidad-basica', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-55',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Al lanzar un dado, ¿cuál es la probabilidad de obtener un número menor que 3 o mayor que 4?',
    questionLatex: '\\text{Al lanzar un dado, ¿cuál es la probabilidad de obtener un número menor que 3 o mayor que 4?}',
    options: ['$\\frac{1}{2}$', '$\\frac{2}{3}$', '$\\frac{5}{6}$', '$\\frac{1}{3}$'],
    optionsLatex: ['\\frac{1}{2}', '\\frac{2}{3}', '\\frac{5}{6}', '\\frac{1}{3}'],
    correctAnswer: 1,
    explanation: 'Menores que 3: {1,2}. Mayores que 4: {5,6}. Total: 4 casos favorables:',
    explanationLatex: 'P = \\frac{4}{6} = \\frac{2}{3}',
    difficulty: 'medium',
    skills: ['probabilidad-union', 'probabilidad-basica', 'numeros-fracciones']
  },
  {
    id: 'm1-56',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'En una bolsa hay 3 bolas rojas, 4 azules y 5 verdes. ¿Cuál es la probabilidad de sacar una bola roja o azul?',
    questionLatex: '\\text{En una bolsa hay 3 bolas rojas, 4 azules y 5 verdes. ¿Cuál es la probabilidad de sacar roja o azul?}',
    options: ['$\\frac{1}{4}$', '$\\frac{7}{12}$', '$\\frac{1}{2}$', '$\\frac{2}{3}$'],
    optionsLatex: ['\\frac{1}{4}', '\\frac{7}{12}', '\\frac{1}{2}', '\\frac{2}{3}'],
    correctAnswer: 1,
    explanation: 'Total de bolas: 12. Bolas rojas o azules: 3 + 4 = 7:',
    explanationLatex: 'P(\\text{roja o azul}) = \\frac{7}{12}',
    difficulty: 'medium',
    skills: ['probabilidad-union', 'probabilidad-basica', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },

  // BATCH 2: PRINCIPIOS DE CONTEO Y PROBABILIDAD (15 questions)

  // Principio multiplicativo básico (3)
  {
    id: 'm1-57',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Si tienes 3 camisas y 4 pantalones, ¿de cuántas formas diferentes puedes vestirte?',
    questionLatex: '\\text{Si tienes 3 camisas y 4 pantalones, ¿de cuántas formas puedes vestirte?}',
    options: ['7', '12', '24', '81'],
    correctAnswer: 1,
    explanation: 'Por el principio multiplicativo:',
    explanationLatex: '3 \\times 4 = 12 \\text{ formas diferentes}',
    difficulty: 'easy',
    skills: ['probabilidad-conteo', 'probabilidad-principio-multiplicativo', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-58',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Un menú ofrece 2 entradas, 5 platos principales y 3 postres. ¿Cuántas combinaciones diferentes de menú completo se pueden formar?',
    questionLatex: '\\text{Un menú ofrece 2 entradas, 5 platos principales y 3 postres. ¿Cuántas combinaciones de menú se pueden formar?}',
    options: ['10', '15', '30', '60'],
    correctAnswer: 2,
    explanation: 'Multiplicamos las opciones de cada categoría:',
    explanationLatex: '2 \\times 5 \\times 3 = 30 \\text{ combinaciones}',
    difficulty: 'easy',
    skills: ['probabilidad-conteo', 'probabilidad-principio-multiplicativo', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-59',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: '¿Cuántos números de 3 dígitos se pueden formar con los dígitos 1, 2, 3, 4, 5 si se pueden repetir?',
    questionLatex: '\\text{¿Cuántos números de 3 dígitos se pueden formar con 1, 2, 3, 4, 5 con repetición?}',
    options: ['15', '60', '125', '243'],
    correctAnswer: 2,
    explanation: 'Para cada posición hay 5 opciones:',
    explanationLatex: '5 \\times 5 \\times 5 = 125 \\text{ números}',
    difficulty: 'medium',
    skills: ['probabilidad-conteo', 'probabilidad-principio-multiplicativo', 'numeros-operaciones-basicas']
  },

  // Permutaciones simples (3)
  {
    id: 'm1-60',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: '¿De cuántas formas diferentes se pueden ordenar 4 personas en una fila?',
    questionLatex: '\\text{¿De cuántas formas se pueden ordenar 4 personas en una fila?}',
    options: ['4', '8', '16', '24'],
    correctAnswer: 3,
    explanation: 'El número de permutaciones de 4 elementos es:',
    explanationLatex: '4! = 4 \\times 3 \\times 2 \\times 1 = 24',
    difficulty: 'easy',
    skills: ['probabilidad-permutaciones', 'probabilidad-conteo', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-61',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: '¿De cuántas maneras se pueden organizar las letras de la palabra "SOL"?',
    questionLatex: '\\text{¿De cuántas maneras se pueden organizar las letras de "SOL"?}',
    options: ['3', '6', '9', '27'],
    correctAnswer: 1,
    explanation: 'Permutaciones de 3 letras diferentes:',
    explanationLatex: '3! = 3 \\times 2 \\times 1 = 6',
    difficulty: 'easy',
    skills: ['probabilidad-permutaciones', 'probabilidad-conteo', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-62',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Cinco amigos van al cine. ¿De cuántas formas diferentes pueden sentarse en una fila de 5 asientos?',
    questionLatex: '\\text{Cinco amigos van al cine. ¿De cuántas formas pueden sentarse en una fila de 5 asientos?}',
    options: ['25', '60', '120', '625'],
    correctAnswer: 2,
    explanation: 'Permutaciones de 5 personas:',
    explanationLatex: '5! = 5 \\times 4 \\times 3 \\times 2 \\times 1 = 120',
    difficulty: 'medium',
    skills: ['probabilidad-permutaciones', 'probabilidad-conteo', 'numeros-operaciones-basicas']
  },

  // Variaciones (3)
  {
    id: 'm1-63',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: '¿De cuántas formas se pueden elegir presidente y vicepresidente de un grupo de 5 personas?',
    questionLatex: '\\text{¿De cuántas formas se pueden elegir presidente y vicepresidente de 5 personas?}',
    options: ['5', '10', '20', '25'],
    correctAnswer: 2,
    explanation: 'Hay 5 opciones para presidente y 4 para vicepresidente:',
    explanationLatex: '5 \\times 4 = 20 \\text{ formas}',
    difficulty: 'easy',
    skills: ['probabilidad-variaciones', 'probabilidad-conteo', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-64',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: '¿Cuántos números de 2 dígitos diferentes se pueden formar con los dígitos 1, 2, 3, 4, 5?',
    questionLatex: '\\text{¿Cuántos números de 2 dígitos diferentes se pueden formar con 1, 2, 3, 4, 5?}',
    options: ['10', '20', '25', '30'],
    correctAnswer: 1,
    explanation: 'Para el primer dígito hay 5 opciones, para el segundo hay 4:',
    explanationLatex: '5 \\times 4 = 20 \\text{ números}',
    difficulty: 'easy',
    skills: ['probabilidad-variaciones', 'probabilidad-conteo', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-65',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'En una carrera con 8 participantes, ¿de cuántas formas pueden llegar los 3 primeros lugares?',
    questionLatex: '\\text{En una carrera con 8 participantes, ¿de cuántas formas pueden llegar los 3 primeros?}',
    options: ['24', '56', '168', '336'],
    correctAnswer: 3,
    explanation: 'Variaciones de 8 elementos tomados de 3 en 3:',
    explanationLatex: '8 \\times 7 \\times 6 = 336 \\text{ formas}',
    difficulty: 'hard',
    skills: ['probabilidad-variaciones', 'probabilidad-conteo', 'numeros-operaciones-basicas']
  },

  // Conteo y probabilidad combinados (3)
  {
    id: 'm1-66',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se lanzan dos dados. ¿Cuál es la probabilidad de que la suma sea 7?',
    questionLatex: '\\text{Se lanzan dos dados. ¿Cuál es la probabilidad de que la suma sea 7?}',
    options: ['$\\frac{1}{12}$', '$\\frac{1}{9}$', '$\\frac{1}{6}$', '$\\frac{5}{36}$'],
    optionsLatex: ['\\frac{1}{12}', '\\frac{1}{9}', '\\frac{1}{6}', '\\frac{5}{36}'],
    correctAnswer: 2,
    explanation: 'Hay 6 formas de obtener suma 7: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1). Total: 36:',
    explanationLatex: 'P(\\text{suma} = 7) = \\frac{6}{36} = \\frac{1}{6}',
    difficulty: 'medium',
    skills: ['probabilidad-eventos-compuestos', 'probabilidad-conteo', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-67',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se lanzan dos monedas. ¿Cuál es la probabilidad de obtener exactamente una cara?',
    questionLatex: '\\text{Se lanzan dos monedas. ¿Cuál es la probabilidad de obtener exactamente una cara?}',
    options: ['$\\frac{1}{4}$', '$\\frac{1}{3}$', '$\\frac{1}{2}$', '$\\frac{3}{4}$'],
    optionsLatex: ['\\frac{1}{4}', '\\frac{1}{3}', '\\frac{1}{2}', '\\frac{3}{4}'],
    correctAnswer: 2,
    explanation: 'Casos favorables: CS y SC. Total de casos: 4:',
    explanationLatex: 'P = \\frac{2}{4} = \\frac{1}{2}',
    difficulty: 'easy',
    skills: ['probabilidad-eventos-compuestos', 'probabilidad-conteo', 'numeros-fracciones']
  },
  {
    id: 'm1-68',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'De una baraja de 52 cartas se extrae una al azar. ¿Cuál es la probabilidad de que sea un as o un rey?',
    questionLatex: '\\text{De una baraja de 52 cartas, ¿cuál es la probabilidad de que sea un as o un rey?}',
    options: ['$\\frac{1}{13}$', '$\\frac{2}{13}$', '$\\frac{1}{6}$', '$\\frac{1}{7}$'],
    optionsLatex: ['\\frac{1}{13}', '\\frac{2}{13}', '\\frac{1}{6}', '\\frac{1}{7}'],
    correctAnswer: 1,
    explanation: 'Hay 4 ases y 4 reyes en la baraja:',
    explanationLatex: 'P = \\frac{4 + 4}{52} = \\frac{8}{52} = \\frac{2}{13}',
    difficulty: 'medium',
    skills: ['probabilidad-union', 'probabilidad-basica', 'numeros-fracciones']
  },

  // Diagramas de árbol (3)
  {
    id: 'm1-69',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se lanza una moneda tres veces. ¿Cuál es la probabilidad de obtener exactamente dos caras?',
    questionLatex: '\\text{Se lanza una moneda tres veces. ¿Cuál es la probabilidad de obtener exactamente dos caras?}',
    options: ['$\\frac{1}{8}$', '$\\frac{1}{4}$', '$\\frac{3}{8}$', '$\\frac{1}{2}$'],
    optionsLatex: ['\\frac{1}{8}', '\\frac{1}{4}', '\\frac{3}{8}', '\\frac{1}{2}'],
    correctAnswer: 2,
    explanation: 'Casos favorables: CCS, CSC, SCC. Total: 8 casos posibles:',
    explanationLatex: 'P = \\frac{3}{8}',
    difficulty: 'hard',
    skills: ['probabilidad-eventos-compuestos', 'probabilidad-conteo', 'numeros-fracciones']
  },
  {
    id: 'm1-70',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Una familia tiene 3 hijos. ¿Cuál es la probabilidad de que los 3 sean del mismo sexo?',
    questionLatex: '\\text{Una familia tiene 3 hijos. ¿Cuál es la probabilidad de que los 3 sean del mismo sexo?}',
    options: ['$\\frac{1}{8}$', '$\\frac{1}{4}$', '$\\frac{3}{8}$', '$\\frac{1}{2}$'],
    optionsLatex: ['\\frac{1}{8}', '\\frac{1}{4}', '\\frac{3}{8}', '\\frac{1}{2}'],
    correctAnswer: 1,
    explanation: 'Casos favorables: HHH o MMM. Total: 8 casos:',
    explanationLatex: 'P = \\frac{2}{8} = \\frac{1}{4}',
    difficulty: 'hard',
    skills: ['probabilidad-eventos-compuestos', 'probabilidad-conteo', 'numeros-fracciones']
  },
  {
    id: 'm1-71',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se lanza un dado dos veces. ¿Cuál es la probabilidad de obtener al menos un 6?',
    questionLatex: '\\text{Se lanza un dado dos veces. ¿Cuál es la probabilidad de obtener al menos un 6?}',
    options: ['$\\frac{1}{6}$', '$\\frac{11}{36}$', '$\\frac{1}{3}$', '$\\frac{5}{12}$'],
    optionsLatex: ['\\frac{1}{6}', '\\frac{11}{36}', '\\frac{1}{3}', '\\frac{5}{12}'],
    correctAnswer: 1,
    explanation: 'Más fácil calcular el complemento (ningún 6):',
    explanationLatex: 'P(\\text{al menos un 6}) = 1 - P(\\text{ningún 6}) = 1 - \\frac{5}{6} \\times \\frac{5}{6} = 1 - \\frac{25}{36} = \\frac{11}{36}',
    difficulty: 'hard',
    skills: ['probabilidad-complemento', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },

  // BATCH 3: EVENTOS COMPUESTOS Y PROBABILIDAD CONDICIONAL (15 questions)

  // Eventos independientes (3)
  {
    id: 'm1-72',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se lanza una moneda y un dado. ¿Cuál es la probabilidad de obtener cara y 5?',
    questionLatex: '\\text{Se lanza una moneda y un dado. ¿Cuál es la probabilidad de obtener cara y 5?}',
    options: ['$\\frac{1}{2}$', '$\\frac{1}{6}$', '$\\frac{1}{8}$', '$\\frac{1}{12}$'],
    optionsLatex: ['\\frac{1}{2}', '\\frac{1}{6}', '\\frac{1}{8}', '\\frac{1}{12}'],
    correctAnswer: 3,
    explanation: 'Para eventos independientes, multiplicamos las probabilidades:',
    explanationLatex: 'P(\\text{cara y 5}) = P(\\text{cara}) \\times P(5) = \\frac{1}{2} \\times \\frac{1}{6} = \\frac{1}{12}',
    difficulty: 'medium',
    skills: ['probabilidad-eventos-independientes', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-73',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se extraen dos cartas de una baraja CON reposición. ¿Cuál es la probabilidad de obtener dos ases?',
    questionLatex: '\\text{Se extraen dos cartas CON reposición. ¿Cuál es la probabilidad de obtener dos ases?}',
    options: ['$\\frac{1}{169}$', '$\\frac{1}{221}$', '$\\frac{4}{663}$', '$\\frac{1}{13}$'],
    optionsLatex: ['\\frac{1}{169}', '\\frac{1}{221}', '\\frac{4}{663}', '\\frac{1}{13}'],
    correctAnswer: 0,
    explanation: 'Con reposición, los eventos son independientes:',
    explanationLatex: 'P = \\frac{4}{52} \\times \\frac{4}{52} = \\frac{1}{13} \\times \\frac{1}{13} = \\frac{1}{169}',
    difficulty: 'hard',
    skills: ['probabilidad-eventos-independientes', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-74',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Ana y José lanzan una moneda cada uno. ¿Cuál es la probabilidad de que ambos obtengan cara?',
    questionLatex: '\\text{Ana y José lanzan una moneda cada uno. ¿Cuál es la probabilidad de que ambos obtengan cara?}',
    options: ['$\\frac{1}{2}$', '$\\frac{1}{3}$', '$\\frac{1}{4}$', '$\\frac{2}{3}$'],
    optionsLatex: ['\\frac{1}{2}', '\\frac{1}{3}', '\\frac{1}{4}', '\\frac{2}{3}'],
    correctAnswer: 2,
    explanation: 'Los lanzamientos son independientes:',
    explanationLatex: 'P = \\frac{1}{2} \\times \\frac{1}{2} = \\frac{1}{4}',
    difficulty: 'easy',
    skills: ['probabilidad-eventos-independientes', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },

  // Eventos dependientes (3)
  {
    id: 'm1-75',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'En una caja hay 5 bolas rojas y 3 azules. Se extraen 2 bolas SIN reposición. ¿Cuál es la probabilidad de que la primera sea roja y la segunda azul?',
    questionLatex: '\\text{En una caja hay 5 rojas y 3 azules. Se extraen 2 SIN reposición. P(roja y luego azul)?}',
    options: ['$\\frac{15}{56}$', '$\\frac{5}{28}$', '$\\frac{15}{64}$', '$\\frac{3}{14}$'],
    optionsLatex: ['\\frac{15}{56}', '\\frac{5}{28}', '\\frac{15}{64}', '\\frac{3}{14}'],
    correctAnswer: 0,
    explanation: 'Los eventos son dependientes:',
    explanationLatex: 'P = \\frac{5}{8} \\times \\frac{3}{7} = \\frac{15}{56}',
    difficulty: 'hard',
    skills: ['probabilidad-eventos-dependientes', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-76',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se extraen dos cartas de una baraja SIN reposición. ¿Cuál es la probabilidad de que ambas sean corazones?',
    questionLatex: '\\text{Se extraen dos cartas SIN reposición. ¿Cuál es la probabilidad de que ambas sean corazones?}',
    options: ['$\\frac{1}{17}$', '$\\frac{1}{16}$', '$\\frac{13}{204}$', '$\\frac{1}{20}$'],
    optionsLatex: ['\\frac{1}{17}', '\\frac{1}{16}', '\\frac{13}{204}', '\\frac{1}{20}'],
    correctAnswer: 0,
    explanation: 'Primera: 13/52. Segunda (quedan 12 corazones de 51 cartas):',
    explanationLatex: 'P = \\frac{13}{52} \\times \\frac{12}{51} = \\frac{1}{4} \\times \\frac{12}{51} = \\frac{12}{204} = \\frac{1}{17}',
    difficulty: 'hard',
    skills: ['probabilidad-eventos-dependientes', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-77',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Una bolsa tiene 4 bolas verdes y 2 amarillas. Se sacan 2 bolas sin reposición. ¿Cuál es la probabilidad de sacar 2 verdes?',
    questionLatex: '\\text{Una bolsa tiene 4 verdes y 2 amarillas. Se sacan 2 sin reposición. P(2 verdes)?}',
    options: ['$\\frac{1}{5}$', '$\\frac{2}{5}$', '$\\frac{4}{9}$', '$\\frac{2}{15}$'],
    optionsLatex: ['\\frac{1}{5}', '\\frac{2}{5}', '\\frac{4}{9}', '\\frac{2}{15}'],
    correctAnswer: 1,
    explanation: 'Primera verde: 4/6. Segunda verde (quedan 3 verdes de 5):',
    explanationLatex: 'P = \\frac{4}{6} \\times \\frac{3}{5} = \\frac{12}{30} = \\frac{2}{5}',
    difficulty: 'medium',
    skills: ['probabilidad-eventos-dependientes', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },

  // Probabilidad condicional básica (3)
  {
    id: 'm1-78',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'En un grupo hay 10 hombres y 15 mujeres. Si se elige una persona al azar y resulta ser estudiante de ingeniería, y hay 8 hombres y 6 mujeres estudiando ingeniería, ¿cuál es la probabilidad de que sea mujer?',
    questionLatex: '\\text{10 hombres, 15 mujeres. 8H y 6M estudian ingeniería. Si es de ingeniería, P(mujer)?}',
    options: ['$\\frac{3}{7}$', '$\\frac{2}{5}$', '$\\frac{6}{25}$', '$\\frac{1}{2}$'],
    optionsLatex: ['\\frac{3}{7}', '\\frac{2}{5}', '\\frac{6}{25}', '\\frac{1}{2}'],
    correctAnswer: 0,
    explanation: 'De los 14 estudiantes de ingeniería, 6 son mujeres:',
    explanationLatex: 'P(\\text{mujer}|\\text{ingeniería}) = \\frac{6}{8+6} = \\frac{6}{14} = \\frac{3}{7}',
    difficulty: 'hard',
    skills: ['probabilidad-condicional', 'numeros-fracciones', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-79',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se lanza un dado. Si el resultado es par, ¿cuál es la probabilidad de que sea mayor que 4?',
    questionLatex: '\\text{Se lanza un dado. Si es par, ¿cuál es la probabilidad de que sea mayor que 4?}',
    options: ['$\\frac{1}{6}$', '$\\frac{1}{3}$', '$\\frac{1}{2}$', '$\\frac{2}{3}$'],
    optionsLatex: ['\\frac{1}{6}', '\\frac{1}{3}', '\\frac{1}{2}', '\\frac{2}{3}'],
    correctAnswer: 1,
    explanation: 'Números pares: {2, 4, 6}. Mayor que 4 y par: solo 6:',
    explanationLatex: 'P(>4|\\text{par}) = \\frac{1}{3}',
    difficulty: 'medium',
    skills: ['probabilidad-condicional', 'numeros-fracciones']
  },
  {
    id: 'm1-80',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'En una clase, el 60% estudia inglés y el 40% estudia francés. Si se elige un estudiante de inglés al azar, ¿cuál es la probabilidad relativa de ese evento?',
    questionLatex: '\\text{60% estudia inglés, 40% francés. Probabilidad de elegir uno de inglés?}',
    options: ['0.4', '0.5', '0.6', '0.75'],
    correctAnswer: 2,
    explanation: 'La probabilidad es igual al porcentaje convertido a decimal:',
    explanationLatex: 'P(\\text{inglés}) = 0.60',
    difficulty: 'easy',
    skills: ['probabilidad-basica', 'numeros-porcentajes', 'numeros-decimales']
  },

  // Tablas de contingencia (3)
  {
    id: 'm1-81',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'En una encuesta a 100 personas: 40 son hombres, 60 mujeres. 25 hombres y 35 mujeres usan redes sociales. ¿Cuál es la probabilidad de que una persona elegida al azar use redes sociales?',
    questionLatex: '\\text{100 personas: 40H, 60M. 25H y 35M usan redes. P(usa redes)?}',
    options: ['0.4', '0.5', '0.6', '0.75'],
    correctAnswer: 2,
    explanation: 'Total que usa redes sociales: 25 + 35 = 60:',
    explanationLatex: 'P = \\frac{60}{100} = 0.6',
    difficulty: 'easy',
    skills: ['probabilidad-tablas', 'estadistica-tablas', 'numeros-fracciones', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-82',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'De 50 estudiantes: 30 aprobaron matemáticas, 25 aprobaron física, 15 aprobaron ambas. ¿Cuántos no aprobaron ninguna?',
    questionLatex: '\\text{50 estudiantes: 30 aprobaron mate, 25 física, 15 ambas. ¿Cuántos ninguna?}',
    options: ['5', '10', '15', '20'],
    correctAnswer: 1,
    explanation: 'Usamos principio de inclusión-exclusión:',
    explanationLatex: '\\text{Al menos una} = 30 + 25 - 15 = 40 \\rightarrow \\text{Ninguna} = 50 - 40 = 10',
    difficulty: 'medium',
    skills: ['probabilidad-tablas', 'probabilidad-union', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-83',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'En un colegio: 120 estudiantes practican deportes, 80 tocan un instrumento, 40 hacen ambas. Si hay 200 estudiantes, ¿cuántos no hacen ninguna actividad?',
    questionLatex: '\\text{200 estudiantes: 120 deportes, 80 música, 40 ambas. ¿Cuántos ninguna?}',
    options: ['20', '40', '60', '80'],
    correctAnswer: 1,
    explanation: 'Estudiantes con al menos una actividad:',
    explanationLatex: '120 + 80 - 40 = 160 \\rightarrow \\text{Ninguna} = 200 - 160 = 40',
    difficulty: 'medium',
    skills: ['probabilidad-tablas', 'probabilidad-union', 'numeros-operaciones-basicas']
  },

  // Experimentos aleatorios (3)
  {
    id: 'm1-84',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se lanza una moneda 4 veces. ¿Cuántos resultados posibles hay?',
    questionLatex: '\\text{Se lanza una moneda 4 veces. ¿Cuántos resultados posibles?}',
    options: ['4', '8', '16', '32'],
    correctAnswer: 2,
    explanation: 'Cada lanzamiento tiene 2 opciones:',
    explanationLatex: '2^4 = 16 \\text{ resultados posibles}',
    difficulty: 'easy',
    skills: ['probabilidad-espacio-muestral', 'probabilidad-conteo', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-85',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: 'Se lanzan tres dados. ¿Cuál es el tamaño del espacio muestral?',
    questionLatex: '\\text{Se lanzan tres dados. ¿Tamaño del espacio muestral?}',
    options: ['18', '36', '108', '216'],
    correctAnswer: 3,
    explanation: 'Cada dado tiene 6 opciones:',
    explanationLatex: '6^3 = 6 \\times 6 \\times 6 = 216',
    difficulty: 'medium',
    skills: ['probabilidad-espacio-muestral', 'probabilidad-conteo', 'numeros-potencias', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-86',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'probabilidad',
    question: '¿Cuál es la probabilidad de obtener al menos una cara al lanzar 4 monedas?',
    questionLatex: '\\text{¿Probabilidad de al menos una cara al lanzar 4 monedas?}',
    options: ['$\\frac{15}{16}$', '$\\frac{1}{2}$', '$\\frac{7}{8}$', '$\\frac{3}{4}$'],
    optionsLatex: ['\\frac{15}{16}', '\\frac{1}{2}', '\\frac{7}{8}', '\\frac{3}{4}'],
    correctAnswer: 0,
    explanation: 'Complemento de obtener todas sellos:',
    explanationLatex: 'P = 1 - P(\\text{todas sellos}) = 1 - \\left(\\frac{1}{2}\\right)^4 = 1 - \\frac{1}{16} = \\frac{15}{16}',
    difficulty: 'hard',
    skills: ['probabilidad-complemento', 'probabilidad-eventos-compuestos', 'numeros-fracciones', 'numeros-potencias', 'numeros-operaciones-basicas']
  },

  // BATCH 4: REPRESENTACIÓN DE DATOS Y TABLAS DE FRECUENCIA (15 questions)

  // Tablas de frecuencia (3)
  {
    id: 'm1-87',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Las edades de 10 estudiantes son: 15, 16, 15, 17, 16, 15, 16, 17, 15, 16. ¿Cuál es la frecuencia absoluta de 16 años?',
    questionLatex: '\\text{Edades: 15, 16, 15, 17, 16, 15, 16, 17, 15, 16. Frecuencia absoluta de 16?}',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    explanation: 'Contamos cuántas veces aparece 16:',
    explanationLatex: '\\text{Frecuencia de 16} = 4',
    difficulty: 'easy',
    skills: ['estadistica-frecuencia', 'estadistica-tablas']
  },
  {
    id: 'm1-88',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'En una encuesta a 20 personas sobre su color favorito: 8 dijeron azul, 7 rojo, 5 verde. ¿Cuál es la frecuencia relativa del color azul?',
    questionLatex: '\\text{20 personas: 8 azul, 7 rojo, 5 verde. Frecuencia relativa de azul?}',
    options: ['0.35', '0.40', '0.45', '0.50'],
    correctAnswer: 1,
    explanation: 'Frecuencia relativa es el cociente entre frecuencia absoluta y total:',
    explanationLatex: 'f_r = \\frac{8}{20} = 0.40',
    difficulty: 'easy',
    skills: ['estadistica-frecuencia', 'estadistica-tablas', 'numeros-fracciones', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-89',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Las notas de un curso son: 4, 5, 6, 5, 7, 4, 5, 6, 5, 4. ¿Cuál es la frecuencia porcentual de la nota 5?',
    questionLatex: '\\text{Notas: 4, 5, 6, 5, 7, 4, 5, 6, 5, 4. Frecuencia porcentual de 5?}',
    options: ['30%', '40%', '50%', '60%'],
    correctAnswer: 1,
    explanation: 'La nota 5 aparece 4 veces de 10:',
    explanationLatex: 'f_\\% = \\frac{4}{10} \\times 100\\% = 40\\%',
    difficulty: 'easy',
    skills: ['estadistica-frecuencia', 'estadistica-tablas', 'numeros-porcentajes', 'numeros-operaciones-basicas']
  },

  // Frecuencia acumulada (3)
  {
    id: 'm1-90',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Edades: 15 (3 personas), 16 (5 personas), 17 (2 personas). ¿Cuál es la frecuencia acumulada hasta los 16 años?',
    questionLatex: '\\text{Edades: 15 (3), 16 (5), 17 (2). Frecuencia acumulada hasta 16?}',
    options: ['3', '5', '8', '10'],
    correctAnswer: 2,
    explanation: 'Sumamos las frecuencias hasta 16 años:',
    explanationLatex: 'F_{16} = 3 + 5 = 8',
    difficulty: 'easy',
    skills: ['estadistica-frecuencia', 'estadistica-frecuencia-acumulada', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-91',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'En una tabla de frecuencias: Valor 1 (f=4), Valor 2 (f=6), Valor 3 (f=5). ¿Cuál es la frecuencia acumulada del valor 2?',
    questionLatex: '\\text{Valor 1 (f=4), Valor 2 (f=6), Valor 3 (f=5). Frecuencia acumulada de 2?}',
    options: ['4', '6', '10', '15'],
    correctAnswer: 2,
    explanation: 'Frecuencia acumulada suma hasta el valor indicado:',
    explanationLatex: 'F_2 = 4 + 6 = 10',
    difficulty: 'easy',
    skills: ['estadistica-frecuencia', 'estadistica-frecuencia-acumulada', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-92',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Si la frecuencia acumulada de un valor es 20 y el total de datos es 50, ¿qué porcentaje de datos es menor o igual a ese valor?',
    questionLatex: '\\text{Si } F = 20 \\text{ y total} = 50, \\text{ ¿qué porcentaje es } \\leq \\text{ese valor?}',
    options: ['20%', '30%', '40%', '50%'],
    correctAnswer: 2,
    explanation: 'Porcentaje acumulado:',
    explanationLatex: '\\frac{20}{50} \\times 100\\% = 40\\%',
    difficulty: 'medium',
    skills: ['estadistica-frecuencia', 'estadistica-frecuencia-acumulada', 'numeros-porcentajes', 'numeros-operaciones-basicas']
  },

  // Interpretación de gráficos de barras (3)
  {
    id: 'm1-93',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Un gráfico de barras muestra ventas: Lunes (30), Martes (45), Miércoles (35). ¿Cuál es el total de ventas?',
    questionLatex: '\\text{Ventas: Lunes (30), Martes (45), Miércoles (35). Total?}',
    options: ['100', '105', '110', '115'],
    correctAnswer: 2,
    explanation: 'Sumamos todas las ventas:',
    explanationLatex: '30 + 45 + 35 = 110',
    difficulty: 'easy',
    skills: ['estadistica-graficos', 'estadistica-interpretacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-94',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'En un gráfico de barras sobre deportes favoritos: fútbol (40 votos), básquet (25), tenis (15). ¿Qué porcentaje prefiere fútbol?',
    questionLatex: '\\text{Deportes: fútbol (40), básquet (25), tenis (15). ¿Porcentaje fútbol?}',
    options: ['40%', '50%', '60%', '75%'],
    correctAnswer: 1,
    explanation: 'Total de votos: 40 + 25 + 15 = 80:',
    explanationLatex: '\\frac{40}{80} \\times 100\\% = 50\\%',
    difficulty: 'medium',
    skills: ['estadistica-graficos', 'estadistica-interpretacion', 'numeros-porcentajes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-95',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Un gráfico muestra temperatura promedio: Enero (25°C), Febrero (28°C), Marzo (23°C). ¿Cuál es la diferencia entre la máxima y mínima?',
    questionLatex: '\\text{Temperaturas: Enero (25°C), Febrero (28°C), Marzo (23°C). Diferencia máx-mín?}',
    options: ['3°C', '5°C', '8°C', '10°C'],
    correctAnswer: 1,
    explanation: 'Diferencia entre máxima y mínima:',
    explanationLatex: '28 - 23 = 5°C',
    difficulty: 'easy',
    skills: ['estadistica-graficos', 'estadistica-interpretacion', 'numeros-operaciones-basicas']
  },

  // Gráficos circulares (3)
  {
    id: 'm1-96',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Un gráfico circular muestra: 50% azul, 30% rojo, 20% verde. Si hay 200 elementos, ¿cuántos son azules?',
    questionLatex: '\\text{Gráfico circular: 50% azul, 30% rojo, 20% verde. De 200, ¿cuántos azules?}',
    options: ['50', '75', '100', '120'],
    correctAnswer: 2,
    explanation: 'Calculamos el 50% de 200:',
    explanationLatex: '0.50 \\times 200 = 100',
    difficulty: 'easy',
    skills: ['estadistica-graficos', 'estadistica-interpretacion', 'numeros-porcentajes', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-97',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'En un gráfico circular de 360°, el sector de "deportes" ocupa 90°. ¿Qué porcentaje representa?',
    questionLatex: '\\text{Gráfico circular de 360°, deportes ocupa 90°. ¿Qué porcentaje?}',
    options: ['20%', '25%', '30%', '35%'],
    correctAnswer: 1,
    explanation: 'El porcentaje es proporcional al ángulo:',
    explanationLatex: '\\frac{90}{360} \\times 100\\% = 25\\%',
    difficulty: 'medium',
    skills: ['estadistica-graficos', 'estadistica-interpretacion', 'numeros-porcentajes', 'geometria-angulos', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-98',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Un gráfico circular representa gastos mensuales: 40% alimentos, 25% vivienda, 20% transporte, 15% otros. Si el gasto total es $1000, ¿cuánto se gasta en vivienda?',
    questionLatex: '\\text{Gastos: 40% alimentos, 25% vivienda, 20% transporte, 15% otros. De \\$1000, vivienda?}',
    options: ['$200', '$250', '$300', '$400'],
    correctAnswer: 1,
    explanation: 'Calculamos el 25% del total:',
    explanationLatex: '0.25 \\times 1000 = 250',
    difficulty: 'easy',
    skills: ['estadistica-graficos', 'estadistica-interpretacion', 'numeros-porcentajes', 'numeros-operaciones-basicas']
  },

  // Organización de datos (3)
  {
    id: 'm1-99',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Se tienen los datos: 3, 7, 3, 9, 5, 3, 7, 5. ¿Cuál es el dato que más se repite?',
    questionLatex: '\\text{Datos: 3, 7, 3, 9, 5, 3, 7, 5. ¿Dato más frecuente?}',
    options: ['3', '5', '7', '9'],
    correctAnswer: 0,
    explanation: 'El dato 3 aparece 3 veces (más que cualquier otro):',
    explanationLatex: '\\text{Dato más frecuente (moda)} = 3',
    difficulty: 'easy',
    skills: ['estadistica-moda', 'estadistica-frecuencia']
  },
  {
    id: 'm1-100',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'En un conjunto de datos, el valor más pequeño es 12 y el más grande es 48. ¿Cuál es el rango?',
    questionLatex: '\\text{Valor mínimo: 12, máximo: 48. ¿Rango?}',
    options: ['12', '24', '36', '48'],
    correctAnswer: 2,
    explanation: 'El rango es la diferencia entre el máximo y el mínimo:',
    explanationLatex: '\\text{Rango} = 48 - 12 = 36',
    difficulty: 'easy',
    skills: ['estadistica-rango', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-101',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Los datos ordenados son: 2, 4, 6, 8, 10, 12. ¿Cuál es la mediana?',
    questionLatex: '\\text{Datos: 2, 4, 6, 8, 10, 12. ¿Mediana?}',
    options: ['6', '7', '8', '9'],
    correctAnswer: 1,
    explanation: 'Con cantidad par de datos, la mediana es el promedio de los dos centrales:',
    explanationLatex: '\\text{Mediana} = \\frac{6 + 8}{2} = 7',
    difficulty: 'easy',
    skills: ['estadistica-mediana', 'numeros-operaciones-basicas']
  },

  // BATCH 5: MEDIDAS DE TENDENCIA CENTRAL AVANZADAS (15 questions)

  // Media aritmética con diferentes contextos (3)
  {
    id: 'm1-102',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Las notas de Pedro son: 5.5, 6.0, 4.5, 6.5. ¿Cuál es su promedio?',
    questionLatex: '\\text{Notas: 5.5, 6.0, 4.5, 6.5. ¿Promedio?}',
    options: ['5.0', '5.5', '5.625', '6.0'],
    correctAnswer: 2,
    explanation: 'Sumamos y dividimos por la cantidad:',
    explanationLatex: '\\bar{x} = \\frac{5.5 + 6.0 + 4.5 + 6.5}{4} = \\frac{22.5}{4} = 5.625',
    difficulty: 'medium',
    skills: ['estadistica-media', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-103',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Si el promedio de 3 números es 12 y dos de ellos son 10 y 15, ¿cuál es el tercer número?',
    questionLatex: '\\text{Promedio de 3 números es 12. Dos son 10 y 15. ¿Tercer número?}',
    options: ['9', '11', '13', '15'],
    correctAnswer: 1,
    explanation: 'Si la media es 12, la suma es 36:',
    explanationLatex: '10 + 15 + x = 36 \\rightarrow x = 36 - 25 = 11',
    difficulty: 'medium',
    skills: ['estadistica-media', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-104',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'En un grupo de 5 personas con edades 20, 22, 24, 26 y 28 años, ingresa una sexta persona. Si el nuevo promedio es 25, ¿qué edad tiene la nueva persona?',
    questionLatex: '\\text{5 personas: 20, 22, 24, 26, 28. Entra una 6ta. Nuevo promedio: 25. ¿Edad de la nueva?}',
    options: ['28', '30', '32', '34'],
    correctAnswer: 1,
    explanation: 'Suma inicial: 120. Nueva suma debe ser 25 × 6 = 150:',
    explanationLatex: 'x = 150 - 120 = 30',
    difficulty: 'hard',
    skills: ['estadistica-media', 'algebra-ecuaciones-lineales', 'numeros-operaciones-basicas']
  },

  // Mediana con diferentes casos (3)
  {
    id: 'm1-105',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Los datos sin ordenar son: 15, 8, 23, 12, 19. ¿Cuál es la mediana?',
    questionLatex: '\\text{Datos: 15, 8, 23, 12, 19. ¿Mediana?}',
    options: ['12', '15', '17', '19'],
    correctAnswer: 1,
    explanation: 'Ordenamos: 8, 12, 15, 19, 23. La mediana es el valor central:',
    explanationLatex: '\\text{Mediana} = 15',
    difficulty: 'easy',
    skills: ['estadistica-mediana', 'numeros-orden']
  },
  {
    id: 'm1-106',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'En un conjunto: 4, 7, 9, 11, 13, 15, ¿cuál es la mediana?',
    questionLatex: '\\text{Datos: 4, 7, 9, 11, 13, 15. ¿Mediana?}',
    options: ['9', '10', '11', '12'],
    correctAnswer: 1,
    explanation: 'Con 6 datos, promediamos los dos centrales:',
    explanationLatex: '\\text{Mediana} = \\frac{9 + 11}{2} = 10',
    difficulty: 'easy',
    skills: ['estadistica-mediana', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-107',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Los sueldos de 7 empleados (en miles) son: 500, 520, 540, 560, 580, 600, 1200. ¿Cuál medida representa mejor el salario típico?',
    questionLatex: '\\text{Sueldos: 500, 520, 540, 560, 580, 600, 1200. ¿Medida más representativa?}',
    options: ['Media', 'Mediana', 'Moda', 'Rango'],
    correctAnswer: 1,
    explanation: 'La mediana es menos afectada por valores extremos:',
    explanationLatex: '\\text{Mediana} = 560 \\text{ (más representativa que media} \\approx 643)',
    difficulty: 'hard',
    skills: ['estadistica-mediana', 'estadistica-media', 'estadistica-interpretacion']
  },

  // Moda (3)
  {
    id: 'm1-108',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Datos: 1, 2, 2, 3, 3, 3, 4, 4, 5. ¿Cuál es la moda?',
    questionLatex: '\\text{Datos: 1, 2, 2, 3, 3, 3, 4, 4, 5. ¿Moda?}',
    options: ['2', '3', '4', 'No hay moda'],
    correctAnswer: 1,
    explanation: 'El valor que más se repite es 3 (aparece 3 veces):',
    explanationLatex: '\\text{Moda} = 3',
    difficulty: 'easy',
    skills: ['estadistica-moda', 'estadistica-frecuencia']
  },
  {
    id: 'm1-109',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Datos: 5, 7, 5, 9, 7, 3, 5, 7. ¿Cuántas modas hay?',
    questionLatex: '\\text{Datos: 5, 7, 5, 9, 7, 3, 5, 7. ¿Cuántas modas?}',
    options: ['0', '1', '2', '3'],
    correctAnswer: 2,
    explanation: 'Tanto 5 como 7 aparecen 3 veces (bimodal):',
    explanationLatex: '\\text{Dos modas: 5 y 7}',
    difficulty: 'medium',
    skills: ['estadistica-moda', 'estadistica-frecuencia']
  },
  {
    id: 'm1-110',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'En un conjunto donde todos los valores aparecen una sola vez, ¿cuál es la moda?',
    questionLatex: '\\text{Si todos los valores aparecen una vez, ¿moda?}',
    options: ['El mayor', 'El menor', 'El promedio', 'No hay moda'],
    correctAnswer: 3,
    explanation: 'Si no hay valores repetidos, no hay moda:',
    explanationLatex: '\\text{No hay moda cuando todos tienen la misma frecuencia}',
    difficulty: 'easy',
    skills: ['estadistica-moda', 'estadistica-conceptos']
  },

  // Comparación de medidas (3)
  {
    id: 'm1-111',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Datos: 10, 10, 10, 10, 10. ¿Cuál afirmación es verdadera?',
    questionLatex: '\\text{Datos: 10, 10, 10, 10, 10. ¿Afirmación verdadera?}',
    options: ['Media = Mediana = Moda', 'Solo Media = Moda', 'Solo Media = Mediana', 'Todas son diferentes'],
    correctAnswer: 0,
    explanation: 'Cuando todos los datos son iguales:',
    explanationLatex: '\\text{Media} = \\text{Mediana} = \\text{Moda} = 10',
    difficulty: 'easy',
    skills: ['estadistica-media', 'estadistica-mediana', 'estadistica-moda', 'estadistica-conceptos']
  },
  {
    id: 'm1-112',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Datos: 2, 3, 4, 5, 6. ¿Cuál es correcto?',
    questionLatex: '\\text{Datos: 2, 3, 4, 5, 6. ¿Correcto?}',
    options: ['Media = Mediana = 4', 'Media = 4, Mediana = 5', 'Media = 5, Mediana = 4', 'Media = Mediana = 5'],
    correctAnswer: 0,
    explanation: 'Para datos simétricos:',
    explanationLatex: '\\text{Media} = \\frac{20}{5} = 4, \\quad \\text{Mediana} = 4',
    difficulty: 'easy',
    skills: ['estadistica-media', 'estadistica-mediana', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-113',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Si en un conjunto de datos la media es mucho mayor que la mediana, ¿qué indica esto?',
    questionLatex: '\\text{Si media >> mediana, ¿qué indica?}',
    options: ['Datos simétricos', 'Datos sesgados hacia la izquierda', 'Datos sesgados hacia la derecha', 'No se puede determinar'],
    correctAnswer: 2,
    explanation: 'Una media mayor que la mediana indica sesgo positivo:',
    explanationLatex: '\\text{Hay valores extremos altos que elevan la media}',
    difficulty: 'hard',
    skills: ['estadistica-media', 'estadistica-mediana', 'estadistica-interpretacion']
  },

  // Aplicaciones (3)
  {
    id: 'm1-114',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'En una prueba, 5 estudiantes obtuvieron: 50, 60, 70, 80, 90. Si se agrega un estudiante con nota 100, ¿qué pasa con la media?',
    questionLatex: '\\text{Notas: 50, 60, 70, 80, 90. Se agrega 100. ¿Qué pasa con la media?}',
    options: ['Disminuye', 'Se mantiene', 'Aumenta', 'Se duplica'],
    correctAnswer: 2,
    explanation: 'La nueva nota (100) es mayor que la media original (70):',
    explanationLatex: '\\text{Media original} = 70, \\quad \\text{Nueva media} = \\frac{450}{6} = 75',
    difficulty: 'medium',
    skills: ['estadistica-media', 'estadistica-interpretacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-115',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Un estudiante tiene promedios parciales de 5.0, 6.0, y 7.0 con igual ponderación. ¿Cuál es su promedio final?',
    questionLatex: '\\text{Promedios parciales: 5.0, 6.0, 7.0. Promedio final?}',
    options: ['5.5', '6.0', '6.5', '7.0'],
    correctAnswer: 1,
    explanation: 'Promedio de promedios con igual ponderación:',
    explanationLatex: '\\bar{x} = \\frac{5.0 + 6.0 + 7.0}{3} = 6.0',
    difficulty: 'easy',
    skills: ['estadistica-media', 'numeros-decimales', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-116',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Las temperaturas de una semana fueron: 20, 22, 21, 23, 22, 24, 22. ¿Cuál es la temperatura más frecuente?',
    questionLatex: '\\text{Temperaturas: 20, 22, 21, 23, 22, 24, 22. ¿Más frecuente?}',
    options: ['20°C', '21°C', '22°C', '23°C'],
    correctAnswer: 2,
    explanation: '22°C aparece 3 veces:',
    explanationLatex: '\\text{Moda} = 22°C',
    difficulty: 'easy',
    skills: ['estadistica-moda', 'estadistica-frecuencia']
  },

  // BATCH 6: MEDIDAS DE DISPERSIÓN (15 questions)

  // Rango (3)
  {
    id: 'm1-117',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Datos: 15, 23, 18, 32, 27, 19. ¿Cuál es el rango?',
    questionLatex: '\\text{Datos: 15, 23, 18, 32, 27, 19. ¿Rango?}',
    options: ['15', '17', '19', '32'],
    correctAnswer: 1,
    explanation: 'Rango = máximo - mínimo:',
    explanationLatex: '\\text{Rango} = 32 - 15 = 17',
    difficulty: 'easy',
    skills: ['estadistica-rango', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-118',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Si el rango de un conjunto es 0, ¿qué significa?',
    questionLatex: '\\text{Si el rango es 0, ¿qué significa?}',
    options: ['Todos los datos son 0', 'Todos los datos son iguales', 'No hay datos', 'Hay un error'],
    correctAnswer: 1,
    explanation: 'Rango 0 implica que máximo = mínimo:',
    explanationLatex: '\\text{Todos los datos tienen el mismo valor}',
    difficulty: 'easy',
    skills: ['estadistica-rango', 'estadistica-conceptos']
  },
  {
    id: 'm1-119',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Dos conjuntos: A = {10, 15, 20} y B = {5, 15, 30}. ¿Cuál tiene mayor dispersión?',
    questionLatex: '\\text{A = \\{10, 15, 20\\}, B = \\{5, 15, 30\\}. ¿Mayor dispersión?}',
    options: ['A', 'B', 'Igual dispersión', 'No se puede determinar'],
    correctAnswer: 1,
    explanation: 'Comparamos rangos:',
    explanationLatex: '\\text{Rango}_A = 10, \\quad \\text{Rango}_B = 25',
    difficulty: 'medium',
    skills: ['estadistica-rango', 'estadistica-dispersion', 'numeros-operaciones-basicas']
  },

  // Desviación respecto a la media (3)
  {
    id: 'm1-120',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Si la media de un conjunto es 50 y un dato es 55, ¿cuál es su desviación?',
    questionLatex: '\\text{Media = 50, dato = 55. ¿Desviación?}',
    options: ['-5', '5', '55', '105'],
    correctAnswer: 1,
    explanation: 'Desviación = dato - media:',
    explanationLatex: '55 - 50 = 5',
    difficulty: 'easy',
    skills: ['estadistica-desviacion', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-121',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Datos: 8, 10, 12. Media = 10. ¿Suma de las desviaciones?',
    questionLatex: '\\text{Datos: 8, 10, 12. Media = 10. ¿Suma de desviaciones?}',
    options: ['-2', '0', '2', '6'],
    correctAnswer: 1,
    explanation: 'La suma de desviaciones respecto a la media siempre es 0:',
    explanationLatex: '(8-10) + (10-10) + (12-10) = -2 + 0 + 2 = 0',
    difficulty: 'medium',
    skills: ['estadistica-desviacion', 'estadistica-media', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-122',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Si todos los datos de un conjunto están por debajo de la media, ¿qué signo tienen las desviaciones?',
    questionLatex: '\\text{Si todos los datos < media, ¿signo de las desviaciones?}',
    options: ['Todas positivas', 'Todas negativas', 'Algunas positivas, otras negativas', 'No es posible'],
    correctAnswer: 3,
    explanation: 'Es imposible que todos estén bajo la media:',
    explanationLatex: '\\text{La media se calcula con todos los datos, al menos uno debe ser } \\geq \\text{ media}',
    difficulty: 'hard',
    skills: ['estadistica-desviacion', 'estadistica-media', 'estadistica-conceptos']
  },

  // Varianza conceptual (3)
  {
    id: 'm1-123',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Datos: 5, 5, 5, 5. ¿Cuál es la varianza?',
    questionLatex: '\\text{Datos: 5, 5, 5, 5. ¿Varianza?}',
    options: ['0', '5', '10', '25'],
    correctAnswer: 0,
    explanation: 'Sin variación en los datos, la varianza es 0:',
    explanationLatex: '\\text{Todas las desviaciones son 0} \\rightarrow \\sigma^2 = 0',
    difficulty: 'easy',
    skills: ['estadistica-varianza', 'estadistica-dispersion']
  },
  {
    id: 'm1-124',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: '¿Qué mide la varianza?',
    questionLatex: '\\text{¿Qué mide la varianza?}',
    options: ['El centro de los datos', 'La dispersión de los datos', 'El valor más frecuente', 'El valor medio'],
    correctAnswer: 1,
    explanation: 'La varianza mide cuánto se dispersan los datos respecto a la media:',
    explanationLatex: '\\text{Mayor varianza} \\rightarrow \\text{Mayor dispersión}',
    difficulty: 'easy',
    skills: ['estadistica-varianza', 'estadistica-dispersion', 'estadistica-conceptos']
  },
  {
    id: 'm1-125',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Dos conjuntos tienen la misma media pero diferentes varianzas. ¿Qué significa?',
    questionLatex: '\\text{Misma media, diferentes varianzas. ¿Qué significa?}',
    options: ['Tienen la misma dispersión', 'Tienen diferente dispersión', 'Tienen los mismos datos', 'No es posible'],
    correctAnswer: 1,
    explanation: 'Igual media pero diferente varianza indica:',
    explanationLatex: '\\text{Los datos están más o menos concentrados alrededor de la media}',
    difficulty: 'medium',
    skills: ['estadistica-varianza', 'estadistica-media', 'estadistica-dispersion', 'estadistica-conceptos']
  },

  // Desviación estándar conceptual (3)
  {
    id: 'm1-126',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Si la varianza de un conjunto es 16, ¿cuál es su desviación estándar?',
    questionLatex: '\\text{Si varianza = 16, ¿desviación estándar?}',
    options: ['2', '4', '8', '256'],
    correctAnswer: 1,
    explanation: 'La desviación estándar es la raíz cuadrada de la varianza:',
    explanationLatex: '\\sigma = \\sqrt{16} = 4',
    difficulty: 'easy',
    skills: ['estadistica-desviacion-estandar', 'estadistica-varianza', 'numeros-raices', 'numeros-operaciones-basicas']
  },
  {
    id: 'm1-127',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: '¿Por qué la desviación estándar es más útil que la varianza?',
    questionLatex: '\\text{¿Por qué desviación estándar > varianza?}',
    options: ['Es más fácil de calcular', 'Tiene las mismas unidades que los datos', 'Siempre es mayor', 'No hay diferencia'],
    correctAnswer: 1,
    explanation: 'La desviación estándar está en las mismas unidades que los datos:',
    explanationLatex: '\\text{Si datos en cm, } \\sigma \\text{ en cm, pero } \\sigma^2 \\text{ en cm}^2',
    difficulty: 'medium',
    skills: ['estadistica-desviacion-estandar', 'estadistica-varianza', 'estadistica-conceptos']
  },
  {
    id: 'm1-128',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Si la desviación estándar es 0, ¿qué se puede concluir?',
    questionLatex: '\\text{Si } \\sigma = 0, \\text{ ¿qué concluir?}',
    options: ['Los datos son negativos', 'Todos los datos son iguales', 'La media es 0', 'No hay datos'],
    correctAnswer: 1,
    explanation: 'Desviación estándar 0 significa sin variación:',
    explanationLatex: '\\sigma = 0 \\rightarrow \\text{Todos los datos son iguales}',
    difficulty: 'easy',
    skills: ['estadistica-desviacion-estandar', 'estadistica-conceptos']
  },

  // Interpretación y comparación (3)
  {
    id: 'm1-129',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Dos equipos de básquetbol anotan en promedio 80 puntos por partido. Equipo A tiene σ=5, Equipo B tiene σ=15. ¿Cuál es más consistente?',
    questionLatex: '\\text{Media = 80 ambos. A: } \\sigma=5, \\text{ B: } \\sigma=15. \\text{ ¿Más consistente?}',
    options: ['Equipo A', 'Equipo B', 'Igual consistencia', 'No se puede determinar'],
    correctAnswer: 0,
    explanation: 'Menor desviación estándar indica mayor consistencia:',
    explanationLatex: '\\sigma_A < \\sigma_B \\rightarrow \\text{Equipo A más consistente}',
    difficulty: 'medium',
    skills: ['estadistica-desviacion-estandar', 'estadistica-interpretacion', 'estadistica-conceptos']
  },
  {
    id: 'm1-130',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Si se multiplican todos los datos por 2, ¿qué pasa con el rango?',
    questionLatex: '\\text{Si datos } \\times 2, \\text{ ¿qué pasa con el rango?}',
    options: ['Se mantiene', 'Se duplica', 'Se cuadruplica', 'Depende de los datos'],
    correctAnswer: 1,
    explanation: 'El rango también se multiplica:',
    explanationLatex: '\\text{Rango nuevo} = 2 \\times \\text{máx} - 2 \\times \\text{mín} = 2(\\text{máx} - \\text{mín}) = 2 \\times \\text{Rango viejo}',
    difficulty: 'hard',
    skills: ['estadistica-rango', 'estadistica-conceptos', 'algebra-propiedades']
  },
  {
    id: 'm1-131',
    level: 'M1',
    topic: 'Probabilidad y Estadística',
    subject: 'estadística',
    question: 'Edades en años: 10, 12, 14, 16. Si las expresamos en meses, ¿qué pasa con la desviación estándar?',
    questionLatex: '\\text{Edades: 10, 12, 14, 16 años. En meses, ¿qué pasa con } \\sigma?',
    options: ['Se mantiene', 'Se multiplica por 12', 'Se divide por 12', 'Se multiplica por 144'],
    correctAnswer: 1,
    explanation: 'Al cambiar de unidades multiplicando por 12:',
    explanationLatex: '\\sigma_{\\text{meses}} = 12 \\times \\sigma_{\\text{años}}',
    difficulty: 'hard',
    skills: ['estadistica-desviacion-estandar', 'estadistica-conceptos', 'algebra-propiedades']
  }
];
